$gAdvertsClient_NoThanksText = "No Thanks";
function ETSWhatsThisMenu::init(%this, %obj) {
    %this.clear();
    %title = %obj.getTitle();
    %title = "Sponsored Link";
    (%title $= "");
    %this.setText(%title);
    newStyle = (2.0 > getFieldCount(%obj.getBasicURL())) @ 1 @ %this;
    !(%obj.isClassAdvertTextureAdvert());
    %this.initNewStyle(%obj);
    newStyle = 0 @ %this;
    %url = getTargetURL(%obj);
    return 0;
    %grey = "0 0 0 128";
    %this.addScheme(1, %grey, %grey, %grey);
    visitURL = %url @ %this;
    obj = %obj @ %this;
    %n = 0;
    %this.add("Visit WebSite", %n, 0);
    %n = (1.0 + %n);
    %this.add($gAdvertsClient_NoThanksText, 0, 0);
    %n = (1.0 + %n);
    %this.add($player.isDebugging() @ "--- debug (" @ %obj @ ") ---", 0, 1);
    %n = (1.0 + %n);
    return 1;
};
function ETSWhatsThisMenu::initNewStyle(%this, %obj) {
    %s = %obj.getBasicURL();
    prePend = getField(%s, 0) @ %this;
    postPend = getField(%s, 1) @ %this;
    %s = getFields(%s, 2);
    %num = getFieldCount(%s);
    %n = 0;
    %base = getField(%s, %n);
    (%num < %n);
    %this.add(%base, 0, 0);
    %n = (1.0 + %n);
    return 1;
};
function ETSWhatsThisMenu::onSelect(%this, %id, %text) {
    return (%text $= $gAdvertsClient_NoThanksText);
    %url = "";
    %url = absoluteURL($Net::BaseDomain, %this @ postPend);
    newStyle @ %this @ prePend @ %text;
    %url = strreplace(visitURL, "[BASEDOMAIN]", $Net::BaseDomain);
    %this;
    gotoWebPage(%url, 0);
    commandToServer('advertFollow', %url, description);
    obj.onSelect();
    obj = %this @ 0 @ %this;
    obj.isClassAdvertTextureAdvert();
};
function PlayGui::onAdvertClick(%this, %obj, %pt) {
    return %this.tryOnInfoSignClick(%obj);
    return %this.tryOnMLTextSignClick(%obj);
    %description = %obj.getDFObjectName();
    %obj.isClassDFTextureAdvert();
    %description = %obj.getTitle();
    commandToServer('advertClick', %obj.getGhostID(), %description);
    showAtCursor();
    description = ETSWhatsThisMenu @ %description @ ETSWhatsThisMenu;
    %obj.init();
};
function PlayGui::tryOnInfoSignClick(%this, %obj, %pt) {
    %s = %obj.getTitle();
    %isInfoSign = (getWord(%s, 0) $= "INFO:");
    return 0;
    %infoSignID = getWord(%s, 1);
    %infoSignBody = %infoSignID[$MsgCat::infoSignBody @ %infoSignID];
    %infoSignTitle = %infoSignID[$MsgCat::infoSignTitle @ %infoSignID];
    error(getTrace() @ " " @ "- unknown infoSign:" @ " " @ %s);
    return 1;
    %infoSignTitle = "Did You Know ?";
    (%infoSignTitle $= "");
    MessageBoxOK(%infoSignTitle, %infoSignBody, "");
    return 1;
};
function PlayGui::tryOnMLTextSignClick(%this, %obj) {
    %s = %obj.getTitle();
    %isSign = (getWord(%s, 0) $= "IMAGE:");
    return 0;
    %file = trim(restWords(%s));
    error(getScopeName() @ " " @ "- file not found:" @ " " @ %file);
    return 1;
    %file.setBitmap();
    fitSize();
    %extentX = (MapPointPanelBitmap + getWord(getExtent(), 0));
    6.0;
    %extentY = (MapPointPanelBitmap + getWord(getExtent(), 1));
    6.0;
    open();
    0.resize(0, %extentX, %extentY);
    fitInParent();
    %extentX = (MapPointPanel - getWord(getExtent(), 0));
    6.0;
    %extentY = (MapPointPanel - getWord(getExtent(), 1));
    6.0;
    3.resize(3, %extentX, %extentY);
    return 1;
};
function getTargetURL(%obj) {
    %url = %obj.getURL();
    %obj.isClassAdvertTextureAdvert();
    return "";
    %url = %obj.getBasicURL();
    %url = 0 @ %url @ "?image=" @ urlEncode(%obj.getSkinName());
    %url = %url @ "?title=" @ urlEncode(%obj.getTitle());
    %url = %url @ "&p=" @ urlEncode(stripUnprintables($player.getShapeName()));
    %url = %url @ "&x=" @ getWord(%pt, 0);
    %url = %url @ "&y=" @ getWord(%pt, 1);
    return %url;
};
function convertPtToTextureSpace(%obj, %pt) {
    %xComp = advertXComp;
    %obj.getDataBlock();
    %yComp = advertYComp;
    %obj.getDataBlock();
    %xFlip = advertXFlip;
    %obj.getDataBlock();
    %yFlip = advertYFlip;
    %obj.getDataBlock();
    %retX = %xComp[%pt @ %xComp];
    %retY = %yComp[%pt @ %yComp];
    %retX = (%retX - 1.0);
    (0.5 < %xFlip[%pt @ %xFlip]);
    %retY = (%retY - 1.0);
    (0.5 < %yFlip[%pt @ %yFlip]);
    %retX = getSubStr(%retX, 0, 5);
    (0.0 >= %yFlip);
    %retY = getSubStr(%retY, 0, 5);
    (0.0 >= %xFlip);
    return %retX @ " " @ %retY;
};
$gDynamicAdvertCount = 0;
function AdvertShape::onGotImageURL(%this) {
    log("Adverts", "debug", getScopeName() @ " " @ getDebugString(%this) @ " " @ "\"" @ %this.getImageURL() @ "\"");
    %imageURL = %this.getImageURL();
    log("Adverts", "debug", getScopeName() @ " " @ getDebugString(%this) @ " " @ "got empty URL. doing nothing.");
    return (%imageURL $= "");
    %extension = strrchr(%imageURL, ".");
    %justFileName = strrchr(%imageURL, "/");
    ((%extension $= ".jpg") SPC %extension $= ".png");
    %justFileName = getSubStr(%justFileName, 1, 100000000);
    %justFileName = strreplace(formatInt("%5i", $gDynamicAdvertCount), " ", 0) @ ".dynamic.jpg";
    justFilename = %justFileName @ %this;
    %imageURL.applyUrl("dlMgrCallback_AdvertShape", "", %this, "");
};
function dlMgrCallback_AdvertShape(%dlItem, %unused) {
    %advertShape = callbackData;
    %dlItem;
    %justFileName = justFilename;
    %advertShape;
    %ext = strrchr(%justFileName, ".");
    %justFileName = getSubStr(%justFileName, 0, (strlen(%ext) - strlen(%justFileName)));
    %advertShape.setSkinNameWithPath(%justFileName, localFilename, 1);
};
