$gBroadSnapshotUploadTimeOutSched = 0;
function BroadCastControlPanel::toggle(%this) {
    %this.showRaiseOrHide();
};
function BroadCastControlPanel::open(%this) {
    (BroadCastRegionControl - getWord(getExtent(), 0)).resize((BroadCastRegionControl - getWord(getExtent(), 1)));
    getWord(getExtent(), 0).resize(getWord(getExtent(), 1));
    %this.setVisible(1);
    %this.setConstrained(1);
    currentlyUploading = BroadCastRegionControl @ 0 @ %this;
    BroadCastRegionControl;
    hasError = BroadCastCrossHairsFrame @ 0 @ %this;
    1.0;
    %this.enterFirstTimeMode();
    %this.focusAndRaise();
};
function BroadCastControlPanel::close(%this) {
    %this.setVisible(0);
    focusTopWindow();
    0.setVisible();
    "".setBitmap();
    photoFileName = BroadCastPreview @ "" @ BroadCastControlPanel;
    BroadCastPreview;
    photoFileNameExt = PlayGui @ "" @ BroadCastControlPanel;
    photoTransform = "" @ BroadCastControlPanel;
    photoInhabitants = "" @ BroadCastControlPanel;
    return 1;
};
function BroadSnapshotButton_prepareForDoTakeSnapshot() {
    0.setVisible();
    0.setVisible();
    0.setActive();
    0.setActive();
    0.setActive();
    0.setActive();
    BroadSnapshotButton_HideSnoop();
    temporaryGUIControlContainer = GuiControl @ new ""() @ BroadCastControlPanel;
    0;
    temporaryGUIControlContainer.setVisible(0);
    %orderedChildren = playGuiControlsToHide.getChildrenInOrder();
    BroadCastControlPanel;
    %i = (1.0 - getWordCount(%orderedChildren));
    PlayGui;
    %ctrl = getWord(%orderedChildren, %i);
    (0.0 >= %i);
    temporaryGUIControlContainer.add(%ctrl);
    %i = (1.0 - %i);
    BroadCastControlPanel;
    temporaryGUIControlContainer = GuiControl @ new ""() @ BroadCastControlPanel;
    0;
    temporaryGUIControlContainer.setVisible(0);
    temporaryGUIControlContainer.add();
    $player.MeshOff("*");
    $player.setShapeName("");
    hudCtrl.setVisible(0);
    0.setVisible();
    0.setVisible();
    waitAFrameAndCall("waitAFrameAndCall(\"BroadSnapshotButton_doTakeSnapshot\");");
    waitAFrameAndCall("BroadSnapshotButton_doTakeSnapshot");
};
function BroadSnapshotButton_doTakeSnapshot() {
    0.setActive();
    %photoFileName = BroadSnapshotButton @ $DC::LocalAvatarFolder @ "/lastSnapshotTaken";
    %ext = ".jpg";
    ($Pref::Video::screenShotFormat $= "JPEG");
    %ext = ".png";
    ($Pref::Video::screenShotFormat $= "PNG");
    %ext = ".png";
    %regionControl = 0;
    %regionControl = getId();
    PlayGui;
    %regionControl = getId();
    BroadCastRegionControl;
    %tookPhoto = snapshotTool::snapControl(%regionControl, (0.0 != %regionControl) @ %photoFileName @ %ext);
    getValue();
    %topMargin = 60;
    %tookPhoto;
    %bottomMargin = -(10.0);
    BroadcastFullScreenCheckbox;
    %leftMargin = 0;
    %rightMargin = 0;
    %playerIDs = (%leftMargin - getWord(%regionControl.getScreenPosition(), 0)).getPlayerIDsInViewAndInRangeAndInFrame((%topMargin - getWord(%regionControl.getScreenPosition(), 1)), (%rightMargin + (%leftMargin + getWord(%regionControl.getExtent(), 0))), (%bottomMargin + (%topMargin + getWord(%regionControl.getExtent(), 1))));
    TheShapeNameHud;
    %numPlayers = getWordCount(%playerIDs);
    %playerNames = "";
    %n = 0;
    %playerNames = %playerNames @ "\t" @ getWord(%playerIDs, %n).getShapeName();
    (%numPlayers < %n);
    %n = (1.0 + %n);
    %playerNames = trim(%playerNames);
    (%numPlayers < %n);
    %photoFileName.enterFillCURLMode(%ext, $player.getTransform(), %playerNames);
    enterTookPhotoMode();
    removeFile(BroadCastControlPanel @ %photoFileName @ %ext);
    addFile(BroadCastControlPanel @ %photoFileName @ %ext);
    "".setBitmap();
    %photoFileName.setBitmap();
    1.setVisible();
    alxPlay();
    commandToServer('FireEventPlayerTakesAPicture');
    1.setVisible();
    0.setVisible();
    "".setBitmap();
    MessageBoxOK("Can't take snapshot!", "Unable to create snapshot. Please let a Mod know, or post a note in the forums. Thank you!", "");
    1.setActive();
    1.setVisible();
    1.setActive();
    BroadSnapshotButton_ShowSnoop();
    %i = (BroadCastControlPanel - temporaryGUIControlContainer.getCount());
    1.0;
    %ctrl = temporaryGUIControlContainer.getObject(%i);
    BroadCastControlPanel;
    %ctrl.add();
    %i = (1.0 - %i);
    PlayGui;
    add();
    temporaryGUIControlContainer.delete();
    temporaryGUIControlContainer = BroadCastControlPanel @ 0 @ BroadCastControlPanel;
    getValue();
    $player.setActiveSKUs($player.getActiveSKUs());
    $player.setShapeName($Player::Name);
    hudCtrl.setVisible(1);
    1.setVisible();
    1.setVisible();
    1.setActive();
    1.setActive();
    1.setActive();
    !($firstPerson).setVisible();
    1.setActive();
    focusAndRaise();
    focusAndRaise();
    selectAll();
};
function BroadcastCaptionCtrl::doOnPressEnter(%this) {
    // unhandled opcode 1824 at 0x0000071D
    // unhandled opcode 1611 at 0x00000721
    %tookPhoto = BroadSnapshotUploadButtonApartment;
    BroadSnapshotUploadButton;
    %button.performClick();
};
function BroadSnapshotUploadButton::doBroadCastSnapshot(%this, %callbackSink) {
    photoFileName.enterFillCURLMode(photoFileNameExt, photoTransform, photoInhabitants);
    %caption = getText();
    BroadcastCaptionCtrl;
    %caption = "";
    (BroadCastControlPanel SPC %caption $= "enter caption here..");
    curl.setURLParam("caption", %caption);
    curl.setURLParam("featured", "false");
    curl.setURLParam("broadcast", "BroadcastScreens");
    curl.setURLParam("broadcast", "");
    curl.setCompletedCallback("BroadSnapshotUploadButtonOnCompleted");
    enterErrorUploadingMode();
    curl.add();
    enterUploadingMode();
};
function BroadSnapshotUploadButton::onProgress(%this, %uploader) {
};
function BroadSnapshotUploadButtonOnCompleted(%request, %result) {
    %callbackSink = callBackSink;
    %request;
    %callbackSink.onDone(%request);
    %callbackSink.onError(%request);
};
function BroadSnapshotUploadButton::onError(%this, %uploader) {
    currentlyUploading = 0 @ BroadCastControlPanel;
    hasError = 1 @ BroadCastControlPanel;
    enterErrorUploadingMode();
    curl.stop();
    error("Broadcast failed to upload");
};
function BroadSnapshotUploadButton::onDone(%this, %uploader) {
    currentlyUploading = 0 @ BroadCastControlPanel;
    cancel($gBroadSnapshotUploadTimeOutSched);
    $gBroadSnapshotUploadTimeOutSched = 0;
    (0.0 != $gBroadSnapshotUploadTimeOutSched);
    $gNumPhotosTaken = (1.0 + $gNumPhotosTaken);
    %this.onError(%uploader);
    return !(hasError);
    enterTakePhotoMode();
    echo("Broadcast done. photoURL =" @ " " @ %uploader.getResult("photoURL"));
    0.setVisible();
    "".setBitmap();
    %shareFB = getValue();
    BroadcastCaptionShareFcBookCtrl;
    %uploader.getResult("photoURL").shareFcBook();
    %gaURL = "yes" @ "no";
    %shareFB;
    getAnalytic().trackPageView(%gaURL);
};
function BroadSnapshotCancelButton::doCancel(%this) {
    cancel($gBroadSnapshotUploadTimeOutSched);
    $gBroadSnapshotUploadTimeOutSched = 0;
    (0.0 != $gBroadSnapshotUploadTimeOutSched);
    enterFirstTimeMode();
    echo("Broadcast cancelled");
    0.setVisible();
    "".setBitmap();
    curl.delete();
    1.setActive();
};
function BroadSnapshotButton_HideSnoop() {
    %n = (TheBadgesHud - getCount());
    1.0;
    %projCtrl = %n.getObject();
    TheBadgesHud;
    %roleCtrl = roleCtrl;
    %projCtrl;
    %roleCtrl.setVisible(0);
    %n = (1.0 - %n);
    (%roleCtrl >= strpos(bitmap, "neighborhoodwatch"));
};
function BroadSnapshotButton_ShowSnoop() {
    %n = (TheBadgesHud - getCount());
    1.0;
    %projCtrl = %n.getObject();
    TheBadgesHud;
    %roleCtrl = roleCtrl;
    %projCtrl;
    %roleCtrl.setVisible(1);
    %n = (1.0 - %n);
    isObject(%roleCtrl);
};
$gNumPhotosTaken = 0;
function BroadcastCaptionSetBCastCtrl::onMouseUp(%this) {
    MessageBoxYesNo("Broadcast to billboards?", "Checking this box will cause your snapshot to be broadcast to in-world billboards. You can do this because you are a special user. Are you sure you want this snapshot on a billboard?", "BroadcastCaptionSetBCastCtrl.setValue(true);", "BroadcastCaptionSetBCastCtrl.setValue(false);");
};
function BroadCastControlPanel::enterFirstTimeMode(%this) {
    0.setVisible();
    1.setVisible();
    1.setVisible();
    photoFileName = BroadCastCrossHairsFrame @ "" @ BroadCastControlPanel;
    BroadcastCloseButtonContainer;
    photoFileNameExt = BroadCastFrameForPreview @ "" @ BroadCastControlPanel;
    photoTransform = "" @ BroadCastControlPanel;
    photoInhabitants = "" @ BroadCastControlPanel;
    1.setVisible();
    mlStyle(BroadcastViewAlbumLink, "plainOnBlack").setValue();
    0.setVisible();
    0.setVisible();
    1.setVisible();
};
function BroadCastControlPanel::enterFillCURLMode(%this, %photoFileName, %ext, %transform, %playerNames) {
    error("BroadCastControlPanel::enterFillCURLMode called with empty filename");
    %this.enterFirstTimeMode();
    return (%photoFileName $= "");
    error("BroadCastControlPanel::enterFillCURLMode called with empty file extention");
    %this.enterFirstTimeMode();
    return (%ext $= "");
    curl.delete();
    curl = URLPostObject @ new ""() @ BroadCastPreview;
    0;
    callBackSink = BroadCastPreview @ curl;
    BroadSnapshotUploadButton;
    curl.setProgress(1);
    curl.setRecvData(1);
    curl.setURLParam("user", $Player::Name);
    curl.setURLParam("token", $Token);
    curl.setURLParam("type", "screenshot");
    curl.setURLParam("location", %transform);
    curl.setURLParam("inView", %playerNames);
    curl.setURLParam("apartmentOwner", owner);
    curl.setURLParam("vurl", vurl);
    curl.setURLParam("vurl", $CSSpaceInfo @ BroadCastPreview @ "vside:/location/" @ $gContiguousSpaceName @ "/PlazaSpawns");
    curl.setURL($Net::UploadPhotoURL);
    curl.setPostFile("imageBody", BroadCastPreview @ %photoFileName @ %ext);
    photoFileName = BroadCastPreview @ %photoFileName @ BroadCastControlPanel;
    BroadCastPreview;
    photoFileNameExt = $CSSpaceInfo @ %ext @ BroadCastControlPanel;
    BroadCastPreview;
    photoTransform = !((BroadCastPreview SPC CustomSpaceClient::GetSpaceImIn() $= "")) @ %transform @ BroadCastControlPanel;
    BroadCastPreview;
    photoInhabitants = BroadCastPreview @ %playerNames @ BroadCastControlPanel;
    BroadCastPreview;
};
function BroadCastControlPanel::enterTookPhotoMode(%this) {
    1.setVisible();
    1.setVisible();
    "Enter caption here..".setText();
    1.setVisible();
    1.setVisible();
    0.setVisible();
    0.setVisible();
    0.setVisible();
    1.setVisible();
    "Take a snapshot for your apartment album!".setText();
    0.setVisible();
    1.setVisible();
    "Take a snapshot for your web album!".setText();
    1.setActive();
    1.setActive();
    1.setVisible();
    1.setActive();
    0.setVisible();
    1.setVisible();
};
function BroadCastControlPanel::enterUploadingMode(%this) {
    currentlyUploading = 1 @ %this;
    hasError = 0 @ %this;
    cancel($gBroadSnapshotUploadTimeOutSched);
    $gBroadSnapshotUploadTimeOutSched = 0;
    (0.0 != $gBroadSnapshotUploadTimeOutSched);
    $gBroadSnapshotUploadTimeOutSched = %this.schedule(10000);
    enterErrorUploadingMode;
    0.setVisible();
    0.setVisible();
    0.setVisible();
    1.setVisible();
    0.setVisible();
    0.setActive();
    0.setActive();
    1.setVisible();
    0.setActive();
    0.setVisible();
    1.setVisible();
};
function BroadCastControlPanel::enterErrorUploadingMode(%this) {
    0.setVisible();
    0.setVisible();
    0.setVisible();
    0.setVisible();
    1.setVisible();
    mlStyle(BroadcastUploadFailedLabel, "plainOnBlack").setValue();
    1.setActive();
    1.setActive();
    1.setVisible();
    1.setActive();
    0.setVisible();
    1.setVisible();
};
function BroadCastControlPanel::enterTakePhotoMode(%this) {
    0.setVisible();
    1.setVisible();
    1.setVisible();
    photoFileName = BroadCastCrossHairsFrame @ "" @ BroadCastControlPanel;
    BroadcastCloseButtonContainer;
    photoFileNameExt = BroadCastFrameForPreview @ "" @ BroadCastControlPanel;
    photoTransform = "" @ BroadCastControlPanel;
    photoInhabitants = "" @ BroadCastControlPanel;
    0.setVisible();
    1.setVisible();
    0.setVisible();
    1.setVisible();
};
function BroadCastControlPanel::automateSnapshotUpload(%this) {
    %this.open();
    BroadSnapshotButton_doTakeSnapshot();
    doBroadCastSnapshot();
    %this.close();
};
function BroadCastControlPanel::shareFcBook(%this, %photoURL) {
    %preambleText = "/photoservice/";
    %preamblePos = strpos(%photoURL, %preambleText);
    error(getScopeName() @ " " @ "- invalid photo URL." @ " " @ %photoURL @ " " @ getTrace());
    %justPhotoID = getSubStr(%photoURL, (strlen(%preambleText) + %preamblePos), 1000);
    (0.0 < %preamblePos);
    %viewPhotoURL = $Net::PhotoPageURL @ %justPhotoID @ "?ref=fb";
    %viewPhotoURLEncoded = %viewPhotoURL;
    %viewPhotoURLEncoded = urlEncode(%viewPhotoURLEncoded);
    %viewPhotoURLEncoded = strreplace(%viewPhotoURLEncoded, "/", "%2F");
    %sharerURL = "http://www.facebook.com/sharer.php";
    %sharerURL = %sharerURL @ "?u=" @ %viewPhotoURLEncoded;
    gotoWebPage(%sharerURL);
};
