class = BuddyHudTabs @ new () @ "TabControl";
ScriptObject;
0;
add();
vars = MissionCleanup @ BuddyHudTabs @ 0 @ "columnPadding" @ BuddyHudTabs;
isObject();
vars = !(isObject()) @ MissionCleanup @ 0 @ "rowPadding" @ BuddyHudTabs;
BuddyHudTabs;
vars = 22 @ "offlineFriendsTextboxHeight" @ BuddyHudTabs;
vars = 28 @ "buddyListLegendTextboxHeight" @ BuddyHudTabs;
vars = ColorIToHex($NameColorFriend) @ "normalTextColor" @ BuddyHudTabs;
vars = ColorFToHex(ColorConvolve($NameColorFriendF, $NameColorIdleModulationF)) @ "idleTextColor" @ BuddyHudTabs;
vars = ColorIToHex($NameColorHilite) @ "hilitedTextColor" @ BuddyHudTabs;
function BuddyHudTabs::setup(%this) {
    %this.Initialize("25 25", "platform/client/ui/separator", "16 7", "horizontal");
    %this.newTab("friends", "platform/client/buttons/buddies");
    %this.newTab("requests", "platform/client/buttons/pending");
    %this.newTab("AIM", "platform/client/buttons/aim_buddies");
    %this.newTab("UhOh", "platform/client/buttons/uhoh");
    %this.selectTabWithName("friends");
    %this.fillFriendsTab();
    %this.fillRequestsTab();
    %this.fillAIMTab();
    %this.fillUhOhTab();
    gSetField(0);
    refreshAIMBuddyList();
    position = GuiBitmapButtonCtrl @ new ""() @ "115 4";
    0;
    extent = BuddyHudWin @ BuddyHudTabContainer @ "42 21";
    favoritesTimer;
    bitmap = BuddyHudTabContainer @ BuddyHudWin @ "platform/client/buttons/inviteFriends";
    !(initialized);
    command = %this @ "doInviteFriends();";
    position = GuiMLTextCtrl @ new ""() @ "5 2";
    extent = "36 16";
    profile = "ETSNonModalProfile";
    text = "<color:ddffdd><font:arial:16>Invite!</a>";
    .add();
    setup();
};
function BuddyHudTabs::OnETSInviteFriends(%this) {
    error("no EtsInviteDialog, this should not happen");
    return !(isObject());
    open();
};
function BuddyHudTabs::fillFriendsTab(%this) {
    %theTab = %this.getTabWithName("friends");
    profile = GuiScrollCtrl @ new ""() @ "ETSScrollProfile";
    0;
    horizSizing = "width";
    vertSizing = "top relative";
    position = "0 0";
    extent = getWord(%theTab.getExtent(), 0) @ " " @ "buddyListLegendTextboxHeight" @ BuddyHudTabs @ ((vars @ "offlineFriendsTextboxHeight" @ BuddyHudTabs + vars) - getWord(%theTab.getExtent(), 1));
    minExtent = "10 10";
    sluggishness = -1;
    visible = 1;
    willFirstRespond = 1;
    hScrollBar = "alwaysOff";
    vScrollBar = "dynamic";
    constantThumbHeight = 1;
    helpTag = 0;
    %scroll = ;
    profile = GuiArray2Ctrl @ new ""() @ "CSProfileListBox";
    0;
    childrenClassName = "GuiMouseEventCtrl";
    childrenExtent = "16 18";
    spacing = "rowPadding" @ BuddyHudTabs @ vars;
    numRowsOrCols = 1;
    inRows = 0;
    hilited = 0;
    unselectedProfile = "CSProfileModelListingUnselected";
    selectedProfile = "CSProfileModelListingSelected";
    menuTextProfile = "ETSSmallTextNonModalListProfile";
    menuTextSelectedProfile = "ETSSmallTextNonModalListProfile";
    lastClicked = 0;
    paddingAboveText = 0;
    horizSizing = "width";
    vertSizing = "bottom";
    position = "columnPadding" @ BuddyHudTabs @ (vars - 0.0) @ " " @ 0;
    extent = %scroll.getExtent();
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    scroll = %scroll;
    %friendsList = ;
    %friendsList.bindClassName("MenuControl");
    %friendsList.bindClassName("TabbedTextControl");
    %friendsList.bindClassName("BuddyHudFriendsList");
    %friendsList.setName("BuddyHudFriendsList");
    %fieldWidths = "10 94 46";
    teleFieldIndex = 0 @ %friendsList;
    nameFieldIndex = 1 @ %friendsList;
    cityFieldIndex = 2 @ %friendsList;
    %friendsList.setFieldWidths(%fieldWidths, vars);
    %friendsList.clear();
    %scroll.add(%friendsList);
    %theTab.add(%scroll);
    profile = BuddyHudFriendsListOfflineFriendsBox @ new () @ "ETSSmallTextListProfile";
    GuiMLTextCtrl;
    horizSizing = "columnPadding" @ BuddyHudTabs @ 0 @ "width";
    vertSizing = "top";
    position = 4 @ " " @ "buddyListLegendTextboxHeight" @ BuddyHudTabs @ ((vars @ "offlineFriendsTextboxHeight" @ BuddyHudTabs + vars) - getWord(%theTab.getExtent(), 1));
    extent = getWord(%theTab.getExtent(), 0) @ " " @ "offlineFriendsTextboxHeight" @ BuddyHudTabs @ vars;
    minExtent = "offlineFriendsTextboxHeight" @ BuddyHudTabs @ vars @ " " @ "offlineFriendsTextboxHeight" @ BuddyHudTabs @ vars;
    sluggishness = -1;
    visible = 1;
    text = "";
    %theTab.add();
    profile = BuddyHudFriendsListLegendContainer @ new () @ "GuiDefaultProfile";
    GuiMLTextCtrl;
    horizSizing = 0 @ "width";
    vertSizing = "top";
    position = 4 @ " " @ "buddyListLegendTextboxHeight" @ BuddyHudTabs @ (vars - getWord(%theTab.getExtent(), 1));
    extent = getWord(%theTab.getExtent(), 0) @ " " @ "buddyListLegendTextboxHeight" @ BuddyHudTabs @ vars;
    minExtent = "buddyListLegendTextboxHeight" @ BuddyHudTabs @ vars @ " " @ "buddyListLegendTextboxHeight" @ BuddyHudTabs @ vars;
    profile = BuddyHudFriendsListLegend @ new () @ "ETSTinyTextListProfile";
    GuiMLTextCtrl;
    horizSizing = "width";
    vertSizing = "top";
    position = "0 0";
    extent = getWord(%theTab.getExtent(), 0) @ " " @ "buddyListLegendTextboxHeight" @ BuddyHudTabs @ vars;
    minExtent = "buddyListLegendTextboxHeight" @ BuddyHudTabs @ vars @ " " @ "buddyListLegendTextboxHeight" @ BuddyHudTabs @ vars;
    sluggishness = -1;
    visible = 1;
    text = "<tab:20,90>" @ "<spush><color:" @ "idleTextColor" @ BuddyHudTabs @ vars @ ">Dim<spop>" @ "\t" @ "= Idle" @ "\t" @ "... = In Transit" @ "\n" @ " " @ "\t" @ "= Fast Teleport";
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "6 15";
    extent = "6 9";
    minExtent = "6 9";
    visible = 1;
    bitmap = "platform/client/ui/friendsHud_lightning_n";
    %theTab.add();
    profile = BuddyHudFriendsInfo @ new () @ "ETSScrollProfile";
    GuiScrollCtrl;
    horizSizing = 0 @ "width";
    vertSizing = "top relative";
    position = "3 2";
    extent = (3.0 - getWord(%theTab.getExtent(), 0)) @ " " @ (24.0 - getWord(%theTab.getExtent(), 1));
    minExtent = "10 10";
    sluggishness = -1;
    visible = 0;
    willFirstRespond = 1;
    hScrollBar = "alwaysOff";
    vScrollBar = "dynamic";
    constantThumbHeight = 1;
    helpTag = 0;
    profile = GuiMLTextCtrl @ new ""() @ "ETSTextListProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "146 68";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = ;
    %theTab.add();
    profile = ETSInviteButton @ new () @ "BracketButton15Profile";
    GuiVariableWidthButtonCtrl;
    horizSizing = showInviteFriend() @ 0 @ "right";
    vertSizing = "top";
    position = 8 @ " " @ (18.0 - getWord(%theTab.getExtent(), 1));
    extent = "140 15";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    command = "BuddyHudTabs.OnETSInviteFriends();";
    text = "Invite Friends To Join";
    groupNum = -1;
    buttonType = "PushButton";
    %inviteButton = ;
    %theTab.add(%inviteButton);
};
function BuddyHudTabs::fillRequestsTab(%this) {
    %theTab = %this.getTabWithName("requests");
    profile = GuiMLTextCtrl @ new ""() @ "ETSTextListProfile";
    0;
    horizSizing = "width";
    vertSizing = "bottom";
    position = "0 0";
    extent = "500 80";
    minExtent = "80 80";
    sluggishness = -1;
    visible = 1;
    %requestsList = ;
    %requestsList.bindClassName("BuddyHudPlayerList");
    %requestsList.setName("BuddyHudRequestsList");
    %requestsList.bindClassName("BuddyHudRequestsList");
    profile = GuiScrollCtrl @ new ""() @ "ETSScrollProfile";
    0;
    horizSizing = "width";
    vertSizing = "top relative";
    position = "0 0";
    extent = getWord(%theTab.getExtent(), 0) @ " " @ (24.0 - getWord(%theTab.getExtent(), 1));
    minExtent = "10 10";
    sluggishness = -1;
    visible = 1;
    willFirstRespond = 1;
    hScrollBar = "alwaysOff";
    vScrollBar = "dynamic";
    constantThumbHeight = 1;
    helpTag = 0;
    %scroll = ;
    %scroll.add(%requestsList);
    %theTab.add(%scroll);
    profile = BuddyHudRequestsInfo @ new () @ "ETSScrollProfile";
    GuiScrollCtrl;
    horizSizing = 0 @ "width";
    vertSizing = "top relative";
    position = "3 2";
    extent = (3.0 - getWord(%theTab.getExtent(), 0)) @ " " @ (24.0 - getWord(%theTab.getExtent(), 1));
    minExtent = "10 10";
    sluggishness = -1;
    visible = 0;
    willFirstRespond = 1;
    hScrollBar = "alwaysOff";
    vScrollBar = "dynamic";
    constantThumbHeight = 1;
    helpTag = 0;
    profile = GuiMLTextCtrl @ new ""() @ "ETSTextListProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "146 68";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = ;
    %theTab.add();
};
function BuddyHudTabs::fillAIMTab(%this) {
    %theTab = %this.getTabWithName("AIM");
    echo("Didn't find AIM Buddies tab");
    return 0;
    $Player::AIMName = "";
    $Player::AIMPassword = "";
    profile = AIMLoginFrame @ new () @ "GuiDefaultProfile";
    GuiControl;
    horizSizing = 0 @ "width";
    vertSizing = "bottom";
    position = "4 0";
    extent = "153 190";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    profile = GuiMLTextCtrl @ new ""() @ "ETSShadowTextProfile";
    horizSizing = "width";
    vertSizing = "bottom";
    position = "0 0";
    extent = "153 16";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = "<a:http://www.aim.com/>Get an AIM Screen Name</a>";
    profile = GuiTextCtrl @ new ""() @ "ETSShadowTextProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 20";
    extent = "68 18";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = "Screen Name:";
    maxLength = 64;
    profile = AIMScreenNameField @ new () @ "ETSDarkTabbableTextEditProfile";
    GuiTextEditCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 40";
    extent = "150 16";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    variable = "Player::AIMName";
    altCommand = "AIMLoginFrame.nextControl(AIMScreenNameField);";
    maxLength = 32;
    historySize = 0;
    password = 0;
    tabComplete = 0;
    sinkAllKeyEvents = 0;
    profile = GuiTextCtrl @ new ""() @ "ETSShadowTextProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 60";
    extent = "68 18";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = "Password:";
    maxLength = 64;
    profile = AIMPasswordField @ new () @ "ETSDarkTabbableTextEditProfile";
    GuiTextEditCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 80";
    extent = "150 16";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    variable = "Player::AIMPassword";
    altCommand = "AIMLoginFrame.nextControl(AIMPasswordField);";
    maxLength = 32;
    historySize = 0;
    password = 1;
    tabComplete = 0;
    sinkAllKeyEvents = 0;
    profile = AIMRememberMeCheckbox @ new () @ "ETSCheckBoxProfile";
    GuiCheckBoxCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 105";
    extent = "94 18";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    variable = "UserPref::AIM::RememberMe";
    command = "AIMLoginFrame.update();";
    text = "Remember Me";
    groupNum = -1;
    buttonType = "ToggleButton";
    profile = AIMSavePasswordCheckbox @ new () @ "ETSCheckBoxProfile";
    GuiCheckBoxCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 125";
    extent = "94 18";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    variable = "UserPref::AIM::SavePassword";
    command = "AIMLoginFrame.update();";
    text = "Save Password";
    groupNum = -1;
    buttonType = "ToggleButton";
    profile = AIMAutoSigninCheckbox @ new () @ "ETSCheckBoxProfile";
    GuiCheckBoxCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 145";
    extent = "94 18";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    variable = "UserPref::AIM::AutoSignin";
    command = "AIMLoginFrame.update();";
    text = "Auto Sign In";
    groupNum = -1;
    buttonType = "ToggleButton";
    profile = AIMSignInButton @ new () @ "BracketButton15Profile";
    GuiVariableWidthButtonCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "95 169";
    extent = "54 15";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    command = "doAIMSignIn();";
    text = "Sign In";
    groupNum = -1;
    buttonType = "PushButton";
    %loginFrame = ;
    profile = GuiScrollCtrl @ new ""() @ "ETSScrollProfile";
    0;
    horizSizing = "width";
    vertSizing = "height";
    position = "0 0";
    extent = getWord(%theTab.getExtent(), 0) @ " " @ (24.0 - getWord(%theTab.getExtent(), 1));
    minExtent = "10 10";
    sluggishness = -1;
    visible = 0;
    willFirstRespond = 1;
    hScrollBar = "alwaysOff";
    vScrollBar = "dynamic";
    constantThumbHeight = 1;
    childMargin = "-4 -1";
    helpTag = 0;
    profile = AIMBuddyList @ new () @ "AIMTextListProfile";
    GuiTextListCtrl;
    horizSizing = "width";
    vertSizing = "bottom";
    position = "0 0";
    extent = "150 80";
    minExtent = "80 80";
    sluggishness = -1;
    visible = 1;
    command = "";
    altCommand = "AIMBuddyList.messageSelected();";
    enumerate = 1;
    resizeCell = 1;
    columns = 1;
    fitParentWidth = 1;
    clipColumnText = 1;
    %aimListScroll = ;
    profile = AIMSignOffButton @ new () @ "BracketButton15Profile";
    GuiVariableWidthButtonCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "top";
    position = 93 @ " " @ (22.0 - getWord(%theTab.getExtent(), 1));
    extent = "54 15";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 0;
    command = "doAIMSignOff();";
    text = "Sign Off";
    groupNum = -1;
    buttonType = "PushButton";
    %signOffButton = ;
    profile = AIMInviteButton @ new () @ "BracketButton15Profile";
    GuiVariableWidthButtonCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "top";
    position = 8 @ " " @ (22.0 - getWord(%theTab.getExtent(), 1));
    extent = "79 15";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 0;
    command = "AIMInviteButton.do();";
    text = "Invite Buddy";
    groupNum = -1;
    buttonType = "PushButton";
    %inviteButton = ;
    loginFrame = %loginFrame @ %theTab;
    %theTab.add(%loginFrame);
    aimListScroll = %aimListScroll @ %theTab;
    %theTab.add(%aimListScroll);
    signOffButton = %signOffButton @ %theTab;
    %theTab.add(%signOffButton);
    inviteButton = %inviteButton @ %theTab;
    %theTab.add(%inviteButton);
};
function BuddyHudTabs::wakeUp(%this) {
    %this.setup();
    %this.selectCurrentTab();
    1.setActive();
};
function AIMLoginFrame::nextControl(%this, %curControl) {
    %nextControl = "";
    %this.update();
    // unhandled opcode 2014 at 0x000013F2
    AIMScreenNameField;
    // unhandled opcode 2014 at 0x00001409
    AIMPasswordField;
    error("nextControl got invalid arg" @ " " @ %curControl);
    return (%curControl.getName() SPC %curControl.getName() SPC %nextControl $= "");
    doAIMSignIn();
    %nextControl.makeFirstResponder(1);
    %nextControl.selectAll();
};
function BuddyHudTabs::fillUhOhTab(%this) {
    %theTab = %this.getTabWithName("UhOh");
    echo("Didn't find UhOh tab");
    return 0;
    profile = GuiScrollCtrl @ new ""() @ "ETSScrollProfile";
    0;
    horizSizing = "width";
    vertSizing = "top relative";
    position = "0 0";
    extent = getWord(%theTab.getExtent(), 0) @ " " @ (24.0 - getWord(%theTab.getExtent(), 1));
    minExtent = "10 10";
    sluggishness = -1;
    visible = 1;
    willFirstRespond = 1;
    hScrollBar = "alwaysOff";
    vScrollBar = "dynamic";
    constantThumbHeight = 1;
    helpTag = 0;
    %scroll = ;
    profile = GuiMLTextCtrl @ new ""() @ "ETSTextListProfile";
    0;
    horizSizing = "width";
    vertSizing = "bottom";
    position = "0 0";
    extent = (10.0 - getWord(%scroll.getExtent(), 0)) @ " " @ (10.0 - getWord(%scroll.getExtent(), 1));
    minExtent = "10 10";
    sluggishness = -1;
    visible = 1;
    text = ;
    %body = ;
    %theTab.add(%scroll);
    %scroll.add(%body);
};
function BuddyHudTabs::setUhOhTabVisibility(%this) {
    %showIt = (UserListFriends > size());
    250.0;
    %this.showTabWithName("UhOh");
    %this.hideTabWithName("UhOh");
};
function SimGroup::hasObjectWithName(%this, %name) {
    %i = 0;
    return 1;
    %i = (1.0 + %i);
    return 0;
};
function BuddyHudWin::wakeUp(%this) {
    wakeUp();
};
function BuddyHudWin::addBuddy(%this, %buddy) {
    0.addRow(%buddy);
};
function BuddyHudWin::onlineBuddiesToString(%this) {
    %count = aimBuddyCount();
    %onlineBuddies = "";
    %n = 0;
    %state = aimGetBuddyState(%n);
    (%count < %n);
    %onlineBuddies = %onlineBuddies @ "\t" @ aimGetBuddyName(%n);
    !(((3.0 > %state) SPC %onlineBuddies $= ""));
    %onlineBuddies = aimGetBuddyName(%n);
    (1.0 < %state);
    %n = (1.0 + %n);
    return %onlineBuddies;
};
function BuddyMap::addToAIMList(%this, %key, %value) {
    rowCount().addRow(%value);
};
function BuddyHudWin::refreshAIMBuddyList(%this) {
    class = StringMap @ new ""() @ "BuddyMap";
    0;
    ignoreCase = AIMBuddyList @ isObject() @ 1;
    %onlineList = ;
    class = StringMap @ new ""() @ "BuddyMap";
    0;
    ignoreCase = 1;
    %idleAwayList = ;
    class = StringMap @ new ""() @ "BuddyMap";
    0;
    ignoreCase = 1;
    %offlineList = ;
    %onlineList.add();
    %idleAwayList.add();
    %offlineList.add();
    clear();
    %buddyCount = aimBuddyCount();
    AIMBuddyList;
    %i = 0;
    MissionCleanup;
    %buddyName = aimGetBuddyName(%i);
    (%buddyCount < %i);
    %buddyState = aimGetBuddyState(%i);
    MissionCleanup;
    %tag = "\x10\x06";
    (-(1.0) == %buddyState);
    %offlineList.put(%buddyName, isObject() @ MissionCleanup @ %tag @ %buddyName @ "\x11");
    %tag = "\x10\x06";
    (0.0 == %buddyState);
    %offlineList.put(%buddyName, MissionCleanup @ %tag @ %buddyName @ "\x11");
    %tag = "\x10\x07";
    (1.0 == %buddyState);
    %onlineList.put(%buddyName, %tag @ %buddyName @ "\x11");
    %tag = "\x10\x0B";
    (2.0 == %buddyState);
    %idleAwayList.put(%buddyName, %tag @ %buddyName @ "\x11");
    %tag = "\x10\x0C";
    (3.0 == %buddyState);
    %idleAwayList.put(%buddyName, %tag @ %buddyName @ "\x11");
    %offlineList.put(%buddyName, %buddyName);
    %i = (1.0 + %i);
    %onlineList.forEach("addToAIMList");
    %idleAwayList.forEach("addToAIMList");
    %offlineList.forEach("addToAIMList");
    %onlineList.delete();
    %idleAwayList.delete();
    %offlineList.delete();
};
function BuddyHudWin::clearSelections(%this) {
    -(1.0).setSelectedRow();
};
STATE_PARSE_RESULT = 1 @ BuddyHudWin;
STATE_PARSE_BUDDIES = 2 @ BuddyHudWin;
function BuddyHudFriendsList::onCreatedChild(%this, %child) {
    Parent::onCreatedChild(%this, %child);
    %position = %child.getPosition();
    %extent = %child.getExtent();
    %newHeight = (spacing + getWord(%extent, 1));
    %this;
    %child.resize(getWord(%position, 0), getWord(%position, 1), getWord(%extent, 0), %newHeight);
    %child.bindClassName("BuddyHudFriendsListLine");
};
function BuddyHudFriendsListLine::updateText(%this, %newText) {
    %fieldCount = getFieldCount(%newText);
    %objectCount = %this.getCount();
    %fieldCount = %objectCount;
    (%fieldCount < %objectCount);
    %i = 0;
    %this.getObject(%i).setText(getField(%newText, %i));
    %i = (1.0 + %i);
    (%fieldCount < %i);
};
function BuddyHudFriendsListLine::onMouseEnter(%this) {
    %this.updateText(entryHilited);
};
function BuddyHudFriendsListLine::onMouseLeave(%this) {
    %this.updateText(entryDefault);
};
function BuddyHudFriendsListLine::onMouseDown(%this) {
};
function BuddyHudFriendsListLine::onMouseUp(%this) {
    %name = unmunge(linkText);
    %this;
    onLeftClickPlayerName(%name, "");
};
function BuddyHudFriendsListLine::onRightMouseUp(%this) {
    %name = unmunge(linkText);
    %this;
    onRightClickPlayerName(%name);
};
$gBuddyListLastPopulateTime = "";
$gBuddyListPopulateTimer = "";
$gBuddyListMinRepopulatePeriodMS = 4000;
function BuddyHudWin::populateBuddyLists(%this) {
    %doit = 0;
    %doit = 1;
    ($gBuddyListLastPopulateTime $= "");
    %timeSinceLastPopulate = mSubS32(getSimTime(), $gBuddyListLastPopulateTime);
    %doit = 1;
    ($gBuddyListMinRepopulatePeriodMS > %timeSinceLastPopulate);
    cancel($gBuddyListPopulateTimer);
    $gBuddyListPopulateTimer = %this.schedule($gBuddyListMinRepopulatePeriodMS, "populateBuddyLists");
    !(($gBuddyListPopulateTimer $= ""));
    cancel($gBuddyListPopulateTimer);
    $gBuddyListPopulateTimer = "";
    !((%doit SPC $gBuddyListPopulateTimer $= ""));
    %this.populateBuddyListsReally();
    $gBuddyListLastPopulateTime = getSimTime();
};
function BuddyHudWin::populateBuddyListsReally(%this) {
    %timeIt = !(1);
    %startTime = getSimTime();
    %timeIt;
    %lastTime = getSimTime();
    return !(isObject());
    %vipRoleMasks = roles::getRolesMaskFromStrings("staff moderator celeb");
    %this.initializeBuddyList("FrndsOnline");
    %this.initializeBuddyList("FrndsHere");
    %this.initializeBuddyList("FrndsNPC");
    %this.initializeBuddyList("FrndsThere");
    %this.initializeBuddyList("FrndsInTransit");
    %this.initializeBuddyList("FrndsOffline");
    %this.initializeBuddyList("FavesHere");
    %this.initializeBuddyList("FavesNPC");
    %this.initializeBuddyList("FavesThere");
    %this.initializeBuddyList("FavesOffline");
    %this.initializeBuddyList("FansHere");
    %this.initializeBuddyList("FansNPC");
    %this.initializeBuddyList("FansThere");
    %this.initializeBuddyList("FansOffline");
    error(getScopeName() @ " " @ "- A" @ " " @ formatFloat("%8.3f", (1000.0 / (%startTime - getSimTime()))) @ " " @ formatFloat("%8.3f", (1000.0 / (%lastTime - getSimTime()))));
    %lastTime = getSimTime();
    %timeIt;
    %heightOfRowInFriendsList = 0;
    %offsetForVerticalPositionOfList = 0;
    %verticalPositionOfList = mMax((getWord(getPosition(), 1) - 0.0), 0);
    BuddyHudFriendsList;
    %heightOfRowInFriendsList = getWord(0.getObject().getExtent(), 1);
    BuddyHudFriendsList;
    %indexOfNameAtTopOfFriendsList = mCeil((%heightOfRowInFriendsList / %verticalPositionOfList));
    (BuddyHudFriendsList > getCount());
    %offsetForVerticalPositionOfList = (%verticalPositionOfList - (%heightOfRowInFriendsList * %indexOfNameAtTopOfFriendsList));
    0.0;
    %nameAtTopOfFriendsList = StripMLControlChars(%indexOfNameAtTopOfFriendsList.getObject().getObject(1).getText());
    BuddyHudFriendsList;
    %nameAtTopOfFriendsListisNPC = isNPCEntry;
    %indexOfNameAtTopOfFriendsList.getObject();
    %nameAtTopOfFriendsList = "";
    BuddyHudFriendsList;
    %nameAtTopOfFriendsListisNPC = 0;
    %numberOfNamesInsertedAbove = 0;
    startingPos = BuddyHudFriendsList @ getPosition() @ BuddyHudFriendsList;
    deleteMembers();
    ignoreCase = StringMap @ new ""() @ "true";
    0;
    %botsFriendsList = BuddyHudFriendsList;
    %botsFriendsList.clear();
    %botsFriendsList.add();
    startingPos = BuddyHudRequestsList @ getPosition() @ BuddyHudRequestsList;
    MissionCleanup;
    "".setText();
    error(getScopeName() @ " " @ "- B" @ " " @ formatFloat("%8.3f", (1000.0 / (%startTime - getSimTime()))) @ " " @ formatFloat("%8.3f", (1000.0 / (%lastTime - getSimTime()))));
    %lastTime = getSimTime();
    %timeIt;
    %friendCount = size();
    UserListFriends;
    %includeInListCount = 0;
    0;
    %i = 0;
    BuddyHudRequestsList;
    %friend = %i.getValue();
    UserListFriends;
    %includeInListCount = (1.0 + %includeInListCount);
    loggedIn;
    %i = (1.0 + %i);
    %friend;
    %includeInListCount.setNumChildren();
    error(getScopeName() @ " " @ "- X" @ " " @ formatFloat("%8.3f", (1000.0 / (%startTime - getSimTime()))) @ " " @ formatFloat("%8.3f", (1000.0 / (%lastTime - getSimTime()))));
    %lastTime = getSimTime();
    %timeIt;
    %friendCountOnline = 0;
    BuddyHudFriendsList;
    %i = 0;
    (%friendCount < %i);
    %friend = %i.getValue();
    UserListFriends;
    %includeInList = 1;
    (%friendCount < %i);
    %cityTagDefault = "";
    !((%friend SPC serverName $= ""));
    %cityTagHilited = "";
    (%friendCount < %i);
    %sameServerTagDefault = "";
    isObject();
    %sameServerTagHilited = "";
    MissionCleanup;
    %ghost = Player::findPlayerInstance(name);
    %friend;
    %ghost.setBuddy(1);
    %ghost.setAmFave(1);
    %listName = "FrndsNPC";
    isNPC;
    %listName = "FrndsInTransit";
    loggedIn;
    %cityTagDefault = "<bitmap:platform/client/ui/friendsHud_transition_n>";
    %friend;
    %cityTagHilited = "<bitmap:platform/client/ui/friendsHud_transition_h>";
    (%friend SPC serverName $= "");
    %listName = "FrndsOffline";
    %friend;
    %includeInList = 0;
    isObject(%ghost);
    %listName = "FrndsHere";
    (%friend SPC serverName $= $ServerName);
    %listName = "FrndsThere";
    !((%ghost $= ""));
    %list = buddyLists;
    %listName @ %this;
    log("list not defined:" @ " " @ %listName);
    %list.put(name, "placeholder");
    %sameServerTagDefault = "<modulationColor:ffffffa0><bitmap:platform/client/ui/friendsHud_lightning_i>";
    isIdle;
    %sameServerTagDefault = "<modulationColor:ffffffa0><bitmap:platform/client/ui/friendsHud_lightning_n>";
    %friend;
    %sameServerTagHilited = "<modulationColor:ffffffa0><bitmap:platform/client/ui/friendsHud_lightning_h>";
    (%friend SPC serverName $= $ServerName);
    %sameServerTagDefault = "";
    %includeInList;
    %sameServerTagHilited = "";
    %friend;
    %ignoreTag = "<strikethrough>";
    name.getIgnoreStatus();
    %ignoreTag = "";
    %friend;
    %npcOpen = "";
    isNPC;
    %npcClose = " (bot)";
    %friend;
    %npcOpen = "";
    BuddyHudWin;
    %npcClose = "";
    error;
    %cityBitmap = DestinationList::GetAreaNameIconPath(csn);
    %friend;
    %cityTagDefault = isIdle @ "_i" @ "_n" @ ">";
    %friend;
    %cityTagHilited = !(isObject(%list)) @ (relations SPC %cityTagDefault $= "") @ "<modulationColor:ffffffa0><bitmap:" @ %cityBitmap @ "<modulationColor:ffffffc0><bitmap:" @ %cityBitmap @ "_h>";
    %boldTag = "";
    %colorTagDefault = isIdle @ "idleTextColor" @ BuddyHudTabs @ vars @ "normalTextColor" @ BuddyHudTabs @ vars @ ">";
    %friend;
    %colorTagHilited = "<color:" @ "<color:" @ "hilitedTextColor" @ BuddyHudTabs @ vars @ ">";
    %visibleName = %npcOpen @ %friend @ name @ %npcClose;
    %friendNameTagDefault = "<clip:100>" @ %ignoreTag @ %boldTag @ %colorTagDefault @ %visibleName @ "</a></clip>";
    %friendNameTagHilited = "<clip:100>" @ %ignoreTag @ %boldTag @ %colorTagHilited @ %visibleName @ "</a></clip>";
    %activityName = getField(activities, 0);
    %friend;
    %activityBitmapMLText = getUserActivityMgr().getActivityBitmapMLText(%activityName);
    "";
    %activityColorDefault = "ffffff80";
    "ffffff70";
    %activityColorHilited = vars;
    isIdle @ "hilitedTextColor" @ BuddyHudTabs;
    %activityDefault = (%friend SPC activities $= "") @ %friend @ "<modulationColor:" @ %activityColorDefault @ ">" @ %activityBitmapMLText;
    %activityHilited = "<modulationColor:" @ %activityColorHilited @ ">" @ %activityBitmapMLText;
    %entryDefault = %sameServerTagDefault @ "\t" @ %friendNameTagDefault @ "\t" @ %cityTagDefault @ %activityDefault;
    %entryHilited = %sameServerTagHilited @ "\t" @ %friendNameTagHilited @ "\t" @ %cityTagHilited @ %activityHilited;
    %comparisonToNameAtTopOfList = stricmp(%visibleName, %nameAtTopOfFriendsList);
    %entryInfo = new ""();
    SimObject;
    entryDefault = 0 @ %entryDefault @ %entryInfo;
    isNPC;
    entryHilited = %friend @ %entryHilited @ %entryInfo;
    name = %friend @ name @ %entryInfo;
    %botsFriendsList.put(name, %entryInfo);
    %numberOfNamesInsertedAbove = (1.0 + %numberOfNamesInsertedAbove);
    (0.0 < %comparisonToNameAtTopOfList);
    %line = %entryDefault.addLineNoReseat();
    BuddyHudFriendsList;
    entryDefault = %nameAtTopOfFriendsListisNPC @ %entryDefault @ %line;
    %friend;
    entryHilited = %entryHilited @ %line;
    linkText = %friend @ munge(name) @ %line;
    isNPCEntry = 0 @ %line;
    %numberOfNamesInsertedAbove = (1.0 + %numberOfNamesInsertedAbove);
    (0.0 < %comparisonToNameAtTopOfList);
    %friendCountOnline = (1.0 + %friendCountOnline);
    %nameAtTopOfFriendsListisNPC;
    %i = (1.0 + %i);
    error(getScopeName() @ " " @ "- C" @ " " @ formatFloat("%8.3f", (1000.0 / (%startTime - getSimTime()))) @ " " @ formatFloat("%8.3f", (1000.0 / (%lastTime - getSimTime()))));
    %lastTime = getSimTime();
    %timeIt;
    %botFriendsCount = %botsFriendsList.size();
    (%friendCount < %i);
    %i = 0;
    %entryInfo = %botsFriendsList.getValue(%i);
    (%botFriendsCount < %i);
    %line = entryDefault.addLineNoReseat();
    %entryInfo;
    entryDefault = %entryInfo @ entryDefault @ %line;
    BuddyHudFriendsList;
    entryHilited = %entryInfo @ entryHilited @ %line;
    linkText = %entryInfo @ munge(name) @ %line;
    isNPCEntry = 1 @ %line;
    %entryInfo.delete();
    %i = (1.0 + %i);
    %botsFriendsList.clear();
    %botsFriendsList.delete();
    %newVerticalPositionOfList = ((%numberOfNamesInsertedAbove * %heightOfRowInFriendsList) - %offsetForVerticalPositionOfList);
    (BuddyHudFriendsList > getCount());
    startingPos = BuddyHudFriendsList @ getWord(startingPos, 0) @ " " @ %newVerticalPositionOfList @ BuddyHudFriendsList;
    0.0;
    error(getScopeName() @ " " @ "- D" @ " " @ formatFloat("%8.3f", (1000.0 / (%startTime - getSimTime()))) @ " " @ formatFloat("%8.3f", (1000.0 / (%lastTime - getSimTime()))));
    %lastTime = getSimTime();
    %timeIt;
    %favoriteCount = size();
    UserListFavorites;
    %i = 0;
    (%botFriendsCount < %i);
    %favorite = %i.getValue();
    UserListFavorites;
    %color = $NameColorNormal;
    (%favoriteCount < %i);
    %listName = "FavesOffline";
    %ghost = Player::findPlayerInstance(name);
    %favorite;
    %ghost.setBuddy(1);
    %ignoreTag = "<strikethrough>";
    name.getIgnoreStatus();
    %ignoreTag = "";
    %favorite;
    %npcOpen = "[ ";
    isNPC;
    %npcClose = " ]";
    %favorite;
    %npcOpen = "";
    BuddyHudWin;
    %npcClose = "";
    !((!((%ghost $= "")) SPC %listName $= ""));
    %boldTag = "";
    %colorTag = "<linkcolor:" @ ColorIToHex(%color) @ ">";
    %indent = "   ";
    %entry = "<spush>" @ %indent @ %ignoreTag @ %boldTag @ %colorTag @ "<a:gamelink player " @ %favorite @ munge(name) @ ">" @ %npcOpen @ %favorite @ name @ %npcClose @ "</a><spop>";
    %list = buddyLists;
    %listName @ %this;
    log("unknown list" @ " " @ %listName);
    %list.put(name, %entry);
    log(%favorite @ name);
    %i = (1.0 + %i);
    "unsortable fave buddy" @ " ";
    error(getScopeName() @ " " @ "- E" @ " " @ formatFloat("%8.3f", (1000.0 / (%startTime - getSimTime()))) @ " " @ formatFloat("%8.3f", (1000.0 / (%lastTime - getSimTime()))));
    %lastTime = getSimTime();
    %timeIt;
    %fanCount = size();
    UserListFans;
    %i = 0;
    (%favoriteCount < %i);
    %fan = %i.getValue();
    UserListFans;
    %listName = "";
    (%fanCount < %i);
    %color = "";
    error;
    log("relations", "warn", %fan @ name);
    %color = $NameColorNormal;
    "an NPC is a fan; weird." @ " ";
    %listName = "FansNPC";
    isNPC;
    %color = $NameColorOffline;
    (%fan SPC serverName $= "");
    %listName = "FansOffline";
    %fan;
    %color = $NameColorStaff;
    (%vipRoleMasks != (%fan & roles));
    %listName = "FansHere";
    0.0;
    %color = $NameColorNormal;
    (0.0 != %vipRoleMasks);
    %listName = "FansHere";
    (%fan SPC serverName $= $ServerName);
    %color = $NameColorElsewhere;
    relations;
    %listName = "FansThere";
    %favorite;
    %ignoreTag = "<strikethrough>";
    name.getIgnoreStatus();
    %ignoreTag = "";
    %fan;
    %npcOpen = "[ ";
    isNPC;
    %npcClose = " ]";
    %fan;
    %npcOpen = "";
    BuddyHudWin;
    %npcClose = "";
    !((error SPC %listName $= ""));
    %boldTag = "";
    relations;
    %colorTag = !(isObject(%list)) @ "<linkcolor:" @ ColorIToHex(%color) @ ">";
    %indent = "   ";
    %entry = "<spush>" @ %indent @ %ignoreTag @ %boldTag @ %colorTag @ "<a:gamelink player " @ %fan @ munge(name) @ ">" @ %npcOpen @ %fan @ name @ %npcClose @ "</a><spop>";
    %list = buddyLists;
    %listName @ %this;
    log("unknown list" @ " " @ %listName);
    %list.put(name, %entry);
    log(%fan @ name);
    %i = (1.0 + %i);
    "unsortable fan buddy" @ " ";
    %dict = safeEnsureScriptObjectWithInit("StringMap", "PlayerInstanceDict", "{ ignoreCase = true; }");
    (%fanCount < %i);
    %playerCount = %dict.size();
    error;
    %i = 0;
    relations;
    %ghost = %dict.getValue(%i);
    (%playerCount < %i);
    %ghost.setIgnore(%ghost.getShapeName().getIgnoreStatus());
    %i = (1.0 + %i);
    BuddyHudWin;
    rentabotClient_reignore();
    error(getScopeName() @ " " @ "- F" @ " " @ formatFloat("%8.3f", (1000.0 / (%startTime - getSimTime()))) @ " " @ formatFloat("%8.3f", (1000.0 / (%lastTime - getSimTime()))));
    %lastTime = getSimTime();
    %timeIt;
    %bitmap = "platform/client/buttons/pending";
    "platform/client/buttons/pending_active";
    %elButton = button;
    "requests".getTabWithName();
    %elButton.setBitmap(%bitmap);
    "You have" @ " " @ (%friendCountOnline - %friendCount) @ " " @ "friends offline".setText();
    "".setText();
    %this.setCurListName("WaitingForYourApproval");
    %this.putListIntoList("FansHere");
    %this.putListIntoList("FansThere");
    %this.putListIntoList("FansOffline");
    %this.setCurListName("YourPendingRequests");
    %this.putListIntoList("FavesHere");
    %this.putListIntoList("FavesThere");
    %this.putListIntoList("FavesOffline");
    error(getScopeName() @ " " @ "- G" @ " " @ formatFloat("%8.3f", (1000.0 / (%startTime - getSimTime()))) @ " " @ formatFloat("%8.3f", (1000.0 / (%lastTime - getSimTime()))));
    %lastTime = getSimTime();
    %timeIt;
    startingPos.scrollToPos();
    startingPos.scrollToPos();
    (0.0 == %friendCount).setVisible();
    (0.0 == (%fanCount + %favoriteCount)).setVisible();
    setUhOhTabVisibility();
    reseatChildren();
    error(getScopeName() @ " " @ "- H" @ " " @ formatFloat("%8.3f", (1000.0 / (%startTime - getSimTime()))) @ " " @ formatFloat("%8.3f", (1000.0 / (%lastTime - getSimTime()))));
    %lastTime = getSimTime();
    %timeIt;
};
function BuddyHudWin::getNamesPendingMyApproval(%this) {
    return %this.getNamesInLists("FansHere FansNPC FansThere FansOffline");
};
function BuddyHudWin::getNamesPendingTheirApproval(%this) {
    return %this.getNamesInLists("FavesHere FavesNPC FavesThere FavesOffline");
};
function BuddyHudWin::getNamesInLists(%this, %lists) {
    %ret = "";
    %delim = "";
    %n = (1.0 - getWordCount(%lists));
    %list = buddyLists;
    (0.0 >= %n) @ getWord(%lists, %n) @ %this;
    %m = (1.0 - %list.size());
    isObject(%list);
    %ret = (0.0 >= %m) @ %ret @ %delim @ %list.getKey(%m);
    %delim = "\t";
    %m = (1.0 - %m);
    %n = (1.0 - %n);
    (0.0 >= %m);
    return %ret;
};
function BuddyHudWin::initializeBuddyList(%this, %listName) {
    ignoreCase = StringMap @ new ""() @ "true";
    0;
    buddyLists = %listName @ %this @ !(isObject(buddyLists)) @ %listName @ %this;
    buddyLists.add();
    %list = buddyLists;
    MissionCleanup @ %listName @ %this @ %listName @ %this;
    %dict = safeEnsureScriptObjectWithInit("StringMap", "PlayerInstanceDict", "{ ignoreCase = true; }");
    isObject();
    %count = %list.size();
    MissionCleanup;
    %idx = 0;
    %ghost = %dict.get(%list.getKey(%idx));
    (%count < %idx);
    %ghost.setBuddy(0);
    %ghost.setAmFave(0);
    %ghost.setIgnore(0);
    %idx = (1.0 + %idx);
    isObject(%ghost);
    %list.clear();
};
function BuddyHudWin::setCurListName(%this, %listName) {
    curListName = %listName @ %this;
    listAdded = 0 @ %listName @ %this;
};
function BuddyHudWin::putListIntoList(%this, %srcList, %destList) {
    %list = buddyLists;
    %srcList @ %this;
    log("unknown list" @ " " @ %srcList);
    return error;
    listAdded = !(listAdded) @ 1 @ %this @ curListName @ %this;
    %this @ curListName @ %this;
    %colorTag = "<linkcolor:ffffff>";
    (0.0 > %list.size());
    %collapsed = "+";
    %this[%this @ curListName];
    %collapsed = "- ";
    $UserPref::buddies::collapsedLists;
    %listTitle = %this[%this @ curListName];
    $gBuddyListTitles;
    %titleLine = "<color:ffffff>" @ %colorTag @ "<a:gamelink list " @ %this @ curListName @ ">" @ %collapsed @ %listTitle @ "</a>";
    %destList.setText(%destList.getText() @ %titleLine @ "<br>");
    %formatStr = $UserPref::buddies::collapsedLists @ !(%this[%this @ curListName]) @ "<spush><linkcolor:" @ ColorIToHex("255 147 248") @ ">";
    (%this SPC curListName $= "WaitingForYourApproval");
    %destList.setText(%destList.getText() @ %formatStr @ "  [<a:gamelink approveall>Approve All</a>]   [<a:gamelink declineall>Decline All</a>]<spop><br>");
    putIntoList = !(%this[%this @ curListName]) @ %destList @ %this;
    $UserPref::buddies::collapsedLists;
    %list.forEach("addToFavList");
};
function BuddyHudWin::putListIntoTab(%this, %listName, %destMLTextCtrl) {
    %srcStringMap = buddyLists;
    %listName @ %this;
    log("unknown list" @ " " @ %listName);
    return error;
    log("unknown object" @ " " @ %destMLTextCtrl);
    %destMLTextCtrl.setText("");
    %outputText = "";
    error;
    %size = %srcStringMap.size();
    relations;
    %outputText = "";
    (0.0 == %size);
    %outputText = %srcStringMap.getValue(0);
    !(isObject(%destMLTextCtrl));
    %i = 1;
    %outputText = %outputText @ "\n" @ %srcStringMap.getValue(%i);
    (%size < %i);
    %i = (1.0 + %i);
    %destMLTextCtrl.setText(%outputText);
};
function StringMap::addToFavList(%this, %key, %value) {
    %destList = putIntoList;
    BuddyHudWin;
    %destList.setText(%destList.getText() @ %value @ "<br>");
};
function BuddyHudWin::isFriendOrFavOnlineElsewhere(%this, %playerName) {
    return 1;
    return 1;
    return 0;
};
function BuddyHudWin::isFriendOrFavOnlineHere(%this, %playerName) {
    return 1;
    return 1;
    return 0;
};
function BuddyHudWin::isFriendOrFavOffline(%this, %playerName) {
    return 1;
    return 1;
    return 0;
};
function BuddyHudWin::isOnlineHereOrNotFavorite(%this, %playerName) {
    return 1;
    return 1;
    return 1;
    return 0;
    return 0;
    return 1;
};
function BuddyHudWin::isInBuddyList(%this, %playerName, %listName) {
    %list = buddyLists;
    %listName @ %this;
    log("isInBuddyList(): unknown list" @ " " @ %listName);
    return error;
    return !((%list.get(%playerName) $= ""));
};
function BuddyHudWin::getFriendStatus(%this, %playerName) {
    safeEnsureScriptObjectWithInit("StringMap", "UserListFriends", "{ ignoreCase = true; }");
    safeEnsureScriptObjectWithInit("StringMap", "UserListFavorites", "{ ignoreCase = true; }");
    safeEnsureScriptObjectWithInit("StringMap", "UserListFans", "{ ignoreCase = true; }");
    return "friends";
    return "favorite";
    return "fan";
    return "none";
};
function BuddyHudWin::getIgnoreStatus(%this, %playerName) {
    safeEnsureScriptObjectWithInit("StringMap", "UserListIgnores", "{ ignoreCase = true; }");
    return 1;
    return 0;
};
function sendBuddyListRequest(%callback) {
    log("relations", "debug", getTrace());
    log("general", "debug", getScopeName() @ " " @ "- no token. skipping request.");
    return ($Token $= "");
    %request = sendRequest_GetUserRelations($Player::Name, "", %callback);
};
function onDoneOrErrorCallback_GetUserRelations_ProcessOnly(%request) {
    return !(isObject(%request));
    return !(%request.checkSuccess());
    safeEnsureScriptObjectWithInit("StringMap", "UserListFriends", "{ ignoreCase = true; }");
    safeEnsureScriptObjectWithInit("StringMap", "UserListFavorites", "{ ignoreCase = true; }");
    safeEnsureScriptObjectWithInit("StringMap", "UserListFans", "{ ignoreCase = true; }");
    safeEnsureScriptObjectWithInit("StringMap", "UserListIgnores", "{ ignoreCase = true; }");
    safeEnsureScriptObjectWithInit("StringMap", "UserRelationships", "{ ignoreCase = true; }");
    safeEnsureScriptObject("StringMap", "UserListUnknownServerName");
    %dict = safeEnsureScriptObjectWithInit("StringMap", "PlayerInstanceDict", "{ ignoreCase = true; }");
    %num = size();
    UserListIgnores;
    %n = 0;
    %ghost = %dict.get(%n.getKey());
    UserListIgnores;
    %ghost.setIgnore(0);
    %n = (1.0 + %n);
    isObject(%ghost);
    extractBuddyRecords(%request, "friend", 0);
    extractBuddyRecords(%request, "favorite", 0);
    extractBuddyRecords(%request, "fan", 0);
    extractBuddyRecords(%request, "ignore", 1);
    markIgnoredInList();
    markIgnoredInList();
    rentabotClient_reignore();
};
function BuddyHudWin::refreshFavoritesList(%this) {
    sendBuddyListRequest("onDoneOrErrorCallback_GetUserRelations_Full");
};
function onDoneOrErrorCallback_GetUserRelations_Full(%request) {
    log("network", "debug", getScopeName() @ " " @ "- url =" @ " " @ %request.getURL());
    return !(%request.checkSuccess());
    onDoneOrErrorCallback_GetUserRelations_ProcessOnly(%request);
    populateBuddyLists();
    tryShowPlayerInfo();
    firstTime = firstTime @ 0 @ BuddyHudWin;
    BuddyHudWin;
    open();
    "requests".selectTabWithName();
    refresh();
};
function extractBuddyRecords(%request, %list, %type, %doIgnore) {
    %list.deleteValuesAsObjects();
    %num = %request.getValue(%type @ "Count");
    log("network", "debug", getScopeName() @ " " @ "- " @ %type @ "Count =" @ " " @ %num);
    %n = 0;
    %key = (%num < %n) @ %type @ %n;
    %val = %request.getValue(%key);
    log("network", "debug", getScopeName() @ " " @ " -" @ " " @ %key @ " " @ "=" @ " " @ %val);
    %record = new ""();
    ScriptObject;
    parseBuddyRecord(%record, %val);
    %list.put(name, %record);
    name.put(%record);
    warn(!((%record SPC serverName $= "")) @ (%record SPC csn $= "") @ UserListUnknownServerName @ %record @ getScopeName() @ " " @ "- unrecogized server name '" @ %record @ serverName @ "' for " @ %type @ " user '" @ %record @ name @ "'");
    %dict = safeEnsureScriptObjectWithInit("StringMap", "PlayerInstanceDict", "{ ignoreCase = true; }");
    %doIgnore;
    %ghost = %dict.get(%list.getKey(%n));
    %record;
    %ghost.setIgnore(1);
    %n = (1.0 + %n);
    isObject(%ghost);
};
function parseBuddyRecord(%record, %val) {
    %fieldNdx = 0;
    name = getField(%val, %fieldNdx) @ %record;
    %fieldNdx = (1.0 + %fieldNdx);
    serverName = getField(%val, %fieldNdx) @ %record;
    %fieldNdx = (1.0 + %fieldNdx);
    %roles = getField(%val, %fieldNdx);
    %fieldNdx = (1.0 + %fieldNdx);
    %roles = 0;
    (%roles $= "");
    eval("%record.roles = " @ %roles @ ";");
    loggedIn = getField(%val, %fieldNdx) @ %record;
    %fieldNdx = (1.0 + %fieldNdx);
    isIdle = getField(%val, %fieldNdx) @ %record;
    %fieldNdx = (1.0 + %fieldNdx);
    isNPC = %record @ isNPCName(name) @ %record;
    isIdle = isNPC @ 0 @ %record;
    %record;
    isIdle = (%record SPC serverName $= "") @ 1 @ %record;
    isIdle = (%record SPC isIdle $= "no") @ 0 @ %record;
    isIdle = 1 @ %record;
    loggedIn = (%record SPC loggedIn $= "yes") @ %record;
    serverName = (%record SPC serverName $= "") @ $ServerName @ %record;
    isNPC;
    csn = %record @ serverName.getCityNameForServerName() @ %record;
    BuddyHudTabs;
    activities = "idle" @ "" @ %record;
    isIdle;
};
function BuddyHudTabs::getCityNameForServerName(%this, %ServerName) {
    %csn = %ServerName.cityNameForServerName();
    WorldMap;
    return %csn;
};
function BuddyHudTabs::updateUserListUnknownServerName(%this) {
    safeEnsureScriptObject("StringMap", "UserListUnknownServerName");
    %originalSize = size();
    UserListUnknownServerName;
    %i = (1.0 - %originalSize);
    %record = %i.getValue();
    UserListUnknownServerName;
    csn = %record @ serverName.getCityNameForServerName() @ %record;
    BuddyHudTabs;
    %i.getKey().remove();
    csn = UserListUnknownServerName @ "?" @ %record;
    UserListUnknownServerName;
    %i = (1.0 - %i);
    !((%record SPC csn $= ""));
    populateBuddyLists();
};
function markIgnoredInList(%list) {
    %n = (1.0 - %list.size());
    %fave = %list.getValue(%n);
    (0.0 >= %n);
    ignored = %fave @ name.getIgnoreStatus() @ %fave;
    BuddyHudWin;
    %n = (1.0 - %n);
};
$gRefreshEvenIfBuddyHudWinClosed = 1;
function clientCmdRefreshBuddies(%status) {
    log("relations", "debug", "clientCmdRefreshBuddies(" @ %status @ ")");
    refreshFavoritesList();
    $gRefreshEvenIfBuddyHudWinClosed = 0;
    BuddyHudWin;
};
function sendBuddyStatusRequest(%buddyName) {
    log("relations", "debug", getTrace());
    log("general", "debug", getScopeName() @ " " @ "- no token. skipping request.");
    return ($Token $= "");
    %request = sendRequest_GetUserRelations($Player::Name, %buddyName, "onDoneOrErrorCallback_GetUserRelations_Single");
};
function onDoneOrErrorCallback_GetUserRelations_Single(%request) {
    log("network", "debug", getScopeName() @ " " @ "- url =" @ " " @ %request.getURL());
    return !(%request.checkSuccess());
    %val = "";
    %list = "";
    %key = "friend0";
    (0.0 > %request.getValue("friendCount"));
    %val = %request.getValue(%key);
    // unhandled opcode 4020 at 0x00003B2C
    %val = UserListFriends;
    log("network", "debug", getScopeName() @ " " @ " -" @ " " @ %key @ " " @ "=" @ " " @ %val);
    %key = "favorite0";
    (0.0 > %request.getValue("favoriteCount"));
    %val = %request.getValue("favorite0");
    // unhandled opcode 4020 at 0x00003B84
    %val = UserListFavorites;
    log("network", "debug", getScopeName() @ " " @ " -" @ " " @ %key @ " " @ "=" @ " " @ %val);
    %key = "fan0";
    (0.0 > %request.getValue("fanCount"));
    %val = %request.getValue("fan0");
    // unhandled opcode 4020 at 0x00003BDC
    %val = UserListFans;
    log("network", "debug", getScopeName() @ " " @ " -" @ " " @ %key @ " " @ "=" @ " " @ %val);
    log("network", "debug", getScopeName() @ " " @ "- lost relation" @ " " @ %val);
    %name = getField(%val, 0);
    !((%val $= ""));
    %name = singleUserName;
    %request;
    %record = findRelatedPlayerRecord(%name);
    %oldList = findRelatedPlayerRecordList(%name);
    isObject(%record);
    %oldList.remove(%name);
    %record.delete();
    %record = new ""();
    ScriptObject;
    parseBuddyRecord(%record, %val);
    %list.put(name, %record);
    safeEnsureScriptObject("StringMap", "UserListUnknownServerName");
    name.put(%record);
    warn(UserListUnknownServerName @ %record @ getScopeName() @ " " @ "- unrecogized server name '" @ %record @ serverName @ "' for relation with single user '" @ %record @ name @ "'");
    refresh();
    %dict = safeEnsureScriptObjectWithInit("StringMap", "PlayerInstanceDict", "{ ignoreCase = true; }");
    WorldMap;
    %ghost = %dict.get(name);
    %record;
    %ghost.setIgnore(0);
    %oldIgnoreRecord = findRelatedPlayerRecordInList(%name);
    UserListIgnores;
    %name.remove();
    %oldIgnoreRecord.delete();
    echo("have an ignore record...");
    %key = "ignore0";
    (0.0 > %request.getValue("ignoreCount"));
    %val = %request.getValue("ignore0");
    UserListIgnores;
    %record = new ""();
    ScriptObject;
    parseBuddyRecord(%record, %val);
    name.put(%record);
    echo(%record @ name);
    %ghost.setIgnore(1);
    markIgnoredInList();
    markIgnoredInList();
    populateBuddyLists();
};
function BuddyHudTabs::setBuddyIdleStatus(%this, %buddyName, %isIdle) {
    %entry = %buddyName.get();
    UserListFriends;
    return !(isObject(%entry));
    isIdle = %isIdle @ %entry;
    activities = "idle" @ "\t" @ %entry @ activities @ %entry;
    !(hasField(activities, "idle"));
    populateBuddyLists();
};
function BuddyHudTabs::setBuddyActivities(%this, %buddyName, %activitiesList) {
    %entry = %buddyName.get();
    UserListFriends;
    return !(isObject(%entry));
    activities = %activitiesList @ %entry;
    populateBuddyLists();
};
function clientCmdUpdateBuddy(%source, %target, %action) {
    log("relations", "debug", "clientCmdUpdateBuddy(source=" @ %source @ ", target=" @ %target @ ", action=" @ %action @ ")");
    %other = %target;
    %source;
    %self = %source;
    %target;
    sendBuddyStatusRequest(%other);
    sendBuddyStatusRequest(%other);
    %source.setBuddyIdleStatus(1);
    %source.setBuddyIdleStatus(0);
    sendBuddyStatusRequest(%other);
    handleSystemMessage("msgInfoMessage", (((((%target $= $player.getShapeName()) SPC %target $= $player.getShapeName()) SPC %action $= "userJoined") SPC %action $= "userDropped") SPC %action $= "userToIdle") @ (BuddyHudTabs SPC %action $= "userToNonIdle") @ ((BuddyHudTabs SPC %action $= "friendRequestCreated") SPC %other $= %source) @ "<linkcolor:ffddeeff><a:gamelink " @ munge(%other) @ ">" @ StripMLControlChars(%other) @ "</a> has just asked to be your friend!  <a:ACCEPT " @ munge(%other) @ ">Accept</a> | <a:DECLINE " @ munge(%other) @ ">Decline</a>");
    handleSystemMessage("msgInfoMessage", "<linkcolor:ffddeeff>You have asked <a:gamelink " @ munge(%other) @ ">" @ StripMLControlChars(%other) @ "</a> to be your friend.");
    sendBuddyStatusRequest(%other);
    handleSystemMessage("msgInfoMessage", (%action $= "friendsCreated") @ "<linkcolor:ffddeeff><a:gamelink " @ munge(%other) @ ">" @ StripMLControlChars(%other) @ "</a> is now your friend.");
    %other.updateFriendRequest(1);
    sendBuddyStatusRequest(%other);
    handleSystemMessage("msgInfoMessage", (SystemMessageTextCtrl SPC %action $= "friendsRemoved") @ "<linkcolor:ffddeeff><a:gamelink " @ munge(%other) @ ">" @ StripMLControlChars(%other) @ "</a> is no longer your friend.");
    sendBuddyStatusRequest(%other);
    handleSystemMessage("msgInfoMessage", ((%action $= "friendRequestDenied") SPC %self $= %source) @ "<linkcolor:ffddeeff>You declined <a:gamelink " @ munge(%other) @ ">" @ StripMLControlChars(%other) @ "</a>'s friend request.");
    %other.updateFriendRequest(0);
    sendBuddyStatusRequest(%other);
    handleSystemMessage("msgInfoMessage", ((SystemMessageTextCtrl SPC %action $= "friendRequestCancelled") SPC %self $= %source) @ "<linkcolor:ffddeeff>You canceled your friend request to <a:gamelink " @ munge(%other) @ ">" @ StripMLControlChars(%other) @ "</a>.");
    %other.updateFriendRequest(2);
    sendBuddyStatusRequest(%other);
    handleSystemMessage("msgInfoMessage", (SystemMessageTextCtrl SPC %action $= "ignoreAdded") @ "<linkcolor:ffddeeff>You ignored <a:gamelink " @ munge(%other) @ ">" @ StripMLControlChars(%other) @ "</a>.");
    sendBuddyStatusRequest(%other);
    handleSystemMessage("msgInfoMessage", (%action $= "ignoreRemoved") @ "<linkcolor:ffddeeff>You stopped ignoring <a:gamelink " @ munge(%other) @ ">" @ StripMLControlChars(%other) @ "</a>.");
    log("relations", "error", "Unknown action: " @ %action);
};
function BuddyHudFriendsList::scrollToPos(%this, %pos) {
    BuddyHudPlayerList::scrollToPos(%this, %pos);
};
function BuddyHudFriendsList::onURL(%this, %url) {
    BuddyHudPlayerList::onURL(%this, %url);
};
function BuddyHudFriendsList::onRightURL(%this, %url) {
    BuddyHudPlayerList::onRightURL(%this, %url);
};
function BuddyHudPlayerList::scrollToPos(%this, %pos) {
    %this.getParent().scrollTo(0, (getWord(%pos, 1) - 1.0));
};
function BuddyHudPlayerList::onURL(%this, %url) {
    return !((firstWord(%url) $= "gamelink"));
    %name = unmunge(getWords(%url, 2));
    (getWord(%url, 1) $= "player");
    onLeftClickPlayerName(%name, "");
    %listName = getWords(%url, 2);
    (getWord(%url, 1) $= "list");
    %listName[$UserPref::buddies::collapsedLists @ %listName] = !(%listName[$UserPref::buddies::collapsedLists @ %listName]);
    populateBuddyListsReally();
    acceptAllOperation();
    declineAllOperation();
};
function BuddyHudPlayerList::onRightURL(%this, %url) {
    return !((firstWord(%url) $= "gamelink"));
    %name = unmunge(getWords(%url, 2));
    (getWord(%url, 1) $= "player");
    onRightClickPlayerName(%name);
};
$gLastNameClickTime = 0;
$gLastNameClickName = "";
$gLeftClickTimer = 0;
function onLeftClickPlayerName(%name, %objID) {
    %curTime = getSimTime();
    openUserWhisper(%name);
    cancel($gLeftClickTimer);
    $gLeftClickTimer = 0;
    (0.0 != $gLeftClickTimer);
    $gLeftClickTimer = schedule(450, 0, "onSingleClickPlayerName", %name, %objID);
    ((400.0 < ($gLastNameClickTime - %curTime)) SPC $gLastNameClickName $= %name);
    $gLastNameClickTime = %curTime;
    $gLastNameClickName = %name;
};
function onRightClickPlayerName(%name) {
    %name.initWithPlayerName();
    getCursorPos().showAtPoint();
};
function onSingleClickPlayerName(%name, %objID) {
    open();
    %name.showInfoFor();
    afxSelectAvatarByName(%name);
    rentabotClient_customizeBot(%objID);
};
function AIMBuddyList::messageSelected(%this) {
    %id = %this.getSelectedId();
    %buddyName = stripUnprintables(%this.getRowTextById(%id));
    %buddyName.talkTo();
};
function AIMBuddyList::inviteSelected(%this) {
    %id = %this.getSelectedId();
    %buddyName = stripUnprintables(%this.getRowTextById(%id));
    %buddyName.open();
};
function AIMBuddyList::onRightMouseDown(%this, %unused, %unused, %mousePt) {
    return (%mousePt $= "");
    %aimName = stripUnprintables(%this.getRowText(%this.getMouseOverRow()));
    %aimName.initForAIM();
    %mousePt.showAtPoint();
};
function clientCmdBeginNPCList() {
    safeEnsureScriptObjectWithInit("StringMap", "NPCList", "{ ignoreCase = true; }");
    clear();
};
function clientCmdItsAnNPC(%npcName) {
    safeEnsureScriptObjectWithInit("StringMap", "NPCList", "{ ignoreCase = true; }");
    %npcName.put(%npcName);
};
function isNPCName(%name) {
    error(getScopeName() @ " " @ "- NPC list not initialized." @ " " @ %name @ " " @ getTrace());
    return 0;
    %ret = !((NPCList SPC %name.get() $= ""));
    %ret = rentabot_isRentabotName(%name);
    !(%ret);
    return %ret;
};
function findRelatedPlayerRecordInList(%playerName, %list) {
    error(getScopeName() @ " " @ "- no list!" @ " " @ %playerName @ " " @ getDebugString(%list) @ " " @ getTrace());
    return 0;
    %rec = %list.get(%playerName);
    return %rec;
    return 0;
};
function isRelatedPlayerRecordInList(%playerName, %list) {
    return 0;
    %rec = findRelatedPlayerRecordInList(%playerName, %list);
    return isObject(%rec);
};
function findRelatedPlayerRecordList(%playerName) {
    // unhandled opcode 4020 at 0x00004733
    return %list;
    // unhandled opcode 4020 at 0x0000474D
    %list = UserListFavorites;
    return %list;
    // unhandled opcode 4020 at 0x00004767
    %list = UserListFans;
    return %list;
    // unhandled opcode 4020 at 0x00004781
    %list = UserListIgnores;
    return %list;
    return 0;
};
function findRelatedPlayerRecord(%playerName) {
    %list = findRelatedPlayerRecordList(%playerName);
    return 0;
    return findRelatedPlayerRecordInList(%playerName, %list);
};
function AIMInviteButton::do(%this) {
    inviteSelected();
    %selected = getSelectedId();
    AIMBuddyList;
    %row = %selected.getRowNumById();
    AIMBuddyList;
    %row = (1.0 + %row);
    AIMBuddyList;
    %row = 0;
    (rowCount() >= %row);
    %row.setSelectedRow();
};
function Player::onGotBuddyStatus(%this) {
    %this.schedule(0, "updateMapIcon");
};
function Player::onGotFaveStatus(%this) {
    %this.schedule(0, "updateMapIcon");
};
