$gIsTyping = 0;
$gTypingPreviewAlternator = 1;
$gLastPreviewText = "";
function Player::sendPreviewText(%this, %text) {
    %text = StripMLControlChars(%text);
    return (getSubStr(trim(%text), 0, 1) $= "/");
    %this.onGotTypingSomething(%text);
    %text = removeLastWordIfNotFollowedByWhiteSpace(%text);
    $Chat::Preview::WordBoundaries;
    %text = trim(%text);
    $gIsTyping = 0;
    !(((%text $= "") SPC %text $= $gLastPreviewText));
    commandToServer('ChatPreviewClear');
    $gLastPreviewText = %text;
    return;
    $gIsTyping = 1;
    %numChars = (1.0 + $Chat::Preview::Size);
    %start = (%numChars - strlen(%text));
    %start = 0;
    (0.0 < %start);
    %text = getSubStr(%text, %start, %numChars);
    return (%text $= $gLastPreviewText);
    $gLastPreviewText = %text;
    $gTypingPreviewAlternator = !($gTypingPreviewAlternator);
    !($UserPref::Chat::ShowTyping);
    %text = "";
    $gTypingPreviewAlternator;
    %text = " ";
    commandToServer('ChatPreview', %text);
    setIdle(0);
};
function Player::onGotChatPreview(%this, %dry) {
    %wet = TryFixBadWords(%dry);
    %this.setChatPreview(%wet);
    %this.setChatPreview("");
    %this.setChatPreview(%wet);
    %this.onGotTypingSomething(%wet);
};
function Player::onGotTypingSomething(%this, %text) {
    return (lastTypingSomethingText $= gGetField(%this));
    gSetField(%this, %text);
    cancel(gGetField(%this));
    cancel(gGetField(%this));
    %this.setTyping(0);
    %this.setTyping(1);
    gSetField(%this, %this.schedule($Chat::Preview::IsNoLongerTypingDelay, "setTyping", 0));
    gSetField(%this, %this.schedule($Chat::Preview::ChatPreviewTimeout, "onGotChatPreview", ""));
    %this.talkingAnimTimer(1);
};
function Player::talkingAnimTimer(%this, %startflag) {
    %whichAnim = 2;
    %this.triggerBoneBlendAnimation($BB_HEAD_TALK, 1, 0);
    talking = !(talking) @ 1 @ %this;
    %this;
    %this.setBlendTargetValue($BB_UPPR_MICROPHONE, 0.75);
    %this.triggerBoneBlendAnimation($BB_UPPR_MICROPHONE, 1, 0);
    %dur = %this.getBlendDuration($BB_HEAD_TALK);
    %this.hasMicrophone();
    cancel(AnimationTalkingTimer);
    AnimationTalkingTimer = %this @ "" @ %this;
    !((%this SPC AnimationTalkingTimer $= ""));
    AnimationTalkingTimer = talkingAnimTimer @ %this.schedule(%dur, 0) @ %this;
    %startflag;
    %this.triggerBoneBlendAnimation($BB_HEAD_TALK, 0, 0);
    AnimationTalkingTimer = "" @ %this;
    talking = 0 @ %this;
    %this.setBlendTargetValue($BB_UPPR_MICROPHONE, 0.2);
    %this.triggerBoneBlendAnimation($BB_UPPR_MICROPHONE, 1, 0);
};
function talkBlender::animate(%this) {
};
