function ClosetTabs::refreshStoreTab(%this) {
    clear();
    "Loading ...".add();
    return StoreCategoryPopup;
    %allCategories = "All Items" @ "\t" @ "All Garments" @ "\t" @ "All Accessories" @ "\t" @ "Tops" @ "\t" @ "Bottoms" @ "\t" @ "Hair" @ "\t" @ "Face" @ "\t" @ "Skin" @ "\t" @ "Shoes" @ "\t" @ "Ear" @ "\t" @ "Neck" @ "\t" @ "Waist" @ "\t" @ "Hands" @ "\t" @ "Bags" @ "\t" @ "Glasses" @ "\t" @ "Props" @ "\t" @ "Misc" @ "\t" @ "BodyMod";
    %storeDrwrs = Inventory::getCurrentStoreSkus().filterSkusGender($player.getGender()).getSkuDrwrs();
    SkuManager;
    update();
    %n = 0;
    StoreItemsFrame;
    %cat = getField(%allCategories, %n);
    (getFieldCount(%allCategories) < %n);
    %catDrwrs = strlwr(%cat).get();
    ThumbCategories;
    %m = 0;
    (SkuManager SPC %storeDrwrs $= "");
    %found = findWord(%storeDrwrs, getWord(%catDrwrs, %m));
    (getWordCount(%catDrwrs) < %m);
    %cat.add();
    %m = (1.0 + %m);
    StoreCategoryPopup;
    %n = (1.0 + %n);
    (getWordCount(%catDrwrs) < %m);
    loadStorePosition();
};
function ClosetTabs::fillStoreTab(%this) {
    %theTab = %this.getTabWithName("SHOPS");
    return !(isObject(%theTab));
    profile = GuiBitmapCtrl @ new ""() @ "GuiDefaultProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "26 26";
    extent = "571 37";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/closet_tabs_bracket";
    %theTab.add();
    %tabWidth = getWord(%theTab.getExtent(), 0);
    %tabHeight = getWord(%theTab.getExtent(), 1);
    profile = StoreSpecificBackground @ new () @ "GuiDefaultProfile";
    GuiBitmapCtrl;
    horizSizing = 0 @ "center";
    vertSizing = "center";
    position = (256.0 - (2.0 / %tabWidth)) @ " " @ (256.0 - (2.0 / %tabHeight));
    extent = "512 512";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 0;
    bitmap = "";
    %theTab.add();
    profile = GuiTextCtrl @ new ""() @ "ClosetTitleProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "237 17";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = "";
    maxLength = 255;
    %storename = ;
    profile = GuiMLTextCtrl @ new ""() @ "ClosetLeftInfoProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 23";
    extent = "237 17";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    allowColorChars = 0;
    maxChars = -1;
    text = "";
    %storeDesc = ;
    profile = StoreNameDescFrame @ new () @ "GuiDefaultProfile";
    GuiControl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "26 66";
    extent = "251 59";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    nameCtrl = %storename;
    descCtrl = %storeDesc;
    %nameDescFrame = ;
    %nameDescFrame.add(%storename);
    %nameDescFrame.add(%storeDesc);
    %theTab.add(%nameDescFrame);
    profile = StoreCategoryLabel @ new () @ "ClosetTitleProfile";
    GuiTextCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "181 64";
    extent = "75 20";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = "Item";
    maxLength = 255;
    %categoryLabel = ;
    %theTab.add(%categoryLabel);
    profile = StoreCategoryPopup @ new () @ "ClosetPopupProfile";
    GuiPopUp2MenuCtrl;
    scrollProfile = 0 @ "DottedScrollProfile";
    winProfile = "ClosetPopupWindowProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "180 84";
    extent = "150 17";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    maxLength = 255;
    maxPopupHeight = 200;
    allowReverse = 0;
    %categoryPopup = ;
    %theTab.add(%categoryPopup);
    position = StoreExpirationLegend @ new () @ "26 465";
    GuiControl;
    extent = 0 @ "260 20";
    visible = 0;
    lastStore = "";
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "16 16";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/expiring_icon_small";
    modulationColor = "255 255 255 255";
    profile = GuiTextCtrl @ new ""() @ "ClosetLeftInfoProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "16 -1";
    extent = "200 18";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = " = Expires after a certain amount of time.";
    maxLength = 255;
    %ctrl = ;
    %theTab.add(%ctrl);
    profile = StoreItemsFrame @ new () @ "GuiDefaultProfile";
    GuiControl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "22 120";
    extent = "467 350";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    %itemsFrame = ;
    profile = GuiTextCtrl @ new ""() @ "ClosetLeftInfoProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "1 30";
    extent = "77 16";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 0;
    text = "no matching items";
    maxLength = 255;
    %itemsInfoText = ;
    %itemsFrame.add(%itemsInfoText);
    profile = GuiTextCtrl @ new ""() @ "ClosetRightInfoProfile";
    0;
    horizSizing = "left";
    vertSizing = "bottom";
    position = "313 1";
    extent = "125 14";
    minExtent = "125 1";
    sluggishness = -1;
    visible = 1;
    text = "";
    maxLength = 255;
    %itemsRangeText = ;
    %itemsFrame.add(%itemsRangeText);
    rangeText = %itemsRangeText @ %theTab;
    profile = GuiScrollCtrl @ new ""() @ "ETSScrollProfile";
    0;
    position = "0 20";
    extent = "465 326";
    minExtent = "1 1";
    horizSizing = "right";
    vertSizing = "bottom";
    visible = 1;
    hScrollBar = "dynamic";
    vScrollBar = "dynamic";
    constantThumbHeight = 1;
    scrollMultiplier = 16.1;
    %itemsScroll = ;
    %itemsScroll.bindClassName("ClosetItemsScroll");
    itemsScroll = %itemsScroll @ %theTab;
    class = ClosetThumbnailsShop @ new () @ "ClosetThumbnails";
    GuiArray2Ctrl;
    profile = 0 @ "FocusableDefaultProfile";
    childrenClassName = "GuiMouseEventCtrl";
    childrenExtent = "109 159";
    spacing = 2;
    numRowsOrCols = 4;
    inRows = 0;
    canHilite = 0;
    infoText = %itemsInfoText;
    tab = %theTab;
    scroll = %itemsScroll;
    %thumbnails = ;
    %itemsScroll.add(%thumbnails);
    thumbnails = %thumbnails @ %itemsScroll;
    %itemsFrame.add(%itemsScroll);
    thumbnails = %thumbnails @ %itemsFrame;
    %theTab.add(%itemsFrame);
    thumbnails = %thumbnails @ %theTab;
    profile = StoreDirectoryLink @ new () @ "BracketButton13Profile";
    GuiVariableWidthButtonCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "26 124";
    extent = "126 13";
    minExtent = "1 1";
    visible = 1;
    text = "Go to Shops Directory";
    buttonType = "PushButton";
    drawText = 1;
    command = "transferFromShopToDestinationsDirectory();";
    %theTab.add();
    profile = StoreDirectoryLinkBigText @ new () @ "ClosetLeftInfoProfile";
    GuiMLTextCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "26 124";
    extent = "350 17";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 0;
    allowColorChars = 0;
    maxChars = -1;
    text = ;
    %theTab.add();
    profile = StoreDirectoryLinkBig @ new () @ "GuiDefaultProfile";
    GuiBitmapButtonCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "100 200";
    extent = "300 50";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 0;
    bitmap = "platform/client/buttons/closet_shopsDirButton";
    command = "transferFromShopToDestinationsDirectory();";
    %theTab.add();
    profile = StoreBannerFrame @ new () @ "GuiDefaultProfile";
    GuiControl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "26 483";
    extent = "464 69";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    profile = StoreBannerBrackets @ new () @ "GuiDefaultProfile";
    GuiBitmapCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "464 69";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 0;
    bitmap = "platform/client/ui/banner_bracket";
    profile = StoreBanner @ new () @ "GuiButtonProfile";
    GuiBitmapButtonCtrl;
    horizSizing = "left";
    vertSizing = "bottom";
    position = "8 6";
    extent = "448 57";
    minExtent = "2 2";
    sluggishness = -1;
    visible = 1;
    command = "StoreBanner.doAction();";
    text = "";
    groupNum = -1;
    buttonType = "PushButton";
    bitmap = "";
    drawText = 0;
    %theTab.add();
    profile = GuiBitmapCtrl @ new ""() @ "GuiDefaultProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "689 26";
    extent = "245 45";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/balance_bracket";
    profile = StoreBalanceText @ new () @ "ClosetLargeLinkProfile";
    GuiMLTextCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "9 5";
    extent = "228 42";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    maxChars = -1;
    text = "";
    %theTab.add();
    profile = StoreItemDescFrame @ new () @ "DottedWindowProfile";
    GuiWindowCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "689 84";
    extent = "245 110";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    resizeWidth = 0;
    resizeHeight = 0;
    canMove = 0;
    canClose = 0;
    canMinimize = 0;
    canMaximize = 0;
    closeCommand = "";
    profile = StoreShortDescText @ new () @ "ClosetLeftInfoProfile";
    GuiMLTextCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "3 0";
    extent = "242 25";
    lineSpacing = -3;
    profile = StoreLongDescText @ new () @ "ClosetLeftInfoProfile";
    GuiMLTextCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "3 22";
    extent = "173 16";
    lineSpacing = -3;
    %itemDescFrame = ;
    %theTab.add(%itemDescFrame);
    profile = StoreItemDescHiliteFrame @ new () @ "StoreHiliteFrameProfile";
    GuiWindowCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "679 80";
    extent = "263 124";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 0;
    resizeWidth = 0;
    resizeHeight = 0;
    canMove = 0;
    canClose = 0;
    canMinimize = 0;
    canMaximize = 0;
    closeCommand = "";
    %theTab.add();
    profile = StoreFloatingHiliteFrame @ new () @ "StoreHiliteFrameProfile";
    GuiWindowCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "119 143";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 0;
    resizeWidth = 0;
    resizeHeight = 0;
    canMove = 0;
    canClose = 0;
    canMinimize = 0;
    canMaximize = 0;
    closeCommand = "";
    %theTab.add();
    profile = StoreShoppingBag @ new () @ "DottedWindowProfile";
    GuiWindowCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "689 207";
    extent = "245 281";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    resizeWidth = 0;
    resizeHeight = 0;
    canMove = 0;
    canClose = 0;
    canMinimize = 0;
    canMaximize = 0;
    closeCommand = "";
    profile = GuiBitmapCtrl @ new ""() @ "GuiDefaultProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "7 4";
    extent = "18 13";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/cart";
    profile = GuiTextCtrl @ new ""() @ "ClosetTitleProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "28 1";
    extent = "108 20";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = "Shopping Cart";
    maxLength = 255;
    profile = StoreNoItemsText @ new () @ "ClosetLeftInfoProfile";
    GuiMLTextCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "5 28";
    extent = "221 16";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = "No items in shopping cart.";
    maxLength = 255;
    profile = GuiMLTextCtrl @ new ""() @ "ShoppingBagItemProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "7 261";
    extent = "60 16";
    minExtent = "60 1";
    sluggishness = -1;
    visible = 1;
    text = "Buy All For";
    maxLength = 255;
    profile = StorePointsTotalText @ new () @ "ClosetPointsProfile";
    GuiMLTextCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "90 261";
    extent = "60 16";
    minExtent = "60 1";
    sluggishness = -1;
    visible = 1;
    maxLength = 255;
    profile = StoreBuxTotalText @ new () @ "ClosetBuxProfile";
    GuiMLTextCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "162 261";
    extent = "50 16";
    minExtent = "50 1";
    sluggishness = -1;
    visible = 1;
    maxLength = 255;
    profile = StoreTotalButton @ new () @ "HiddenBracketButton15Profile";
    GuiVariableWidthButtonCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "85 261";
    extent = "132 16";
    minExtent = "1 1";
    visible = 1;
    command = "ClosetGui.doCheckout();";
    text = "";
    buttonType = "PushButton";
    drawText = 0;
    profile = GuiWindowCtrl @ new ""() @ "DottedWindowProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "6 258";
    extent = "233 1";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    resizeWidth = 0;
    resizeHeight = 0;
    canMove = 0;
    canClose = 0;
    canMinimize = 0;
    canMaximize = 0;
    closeCommand = "";
    %shoppingBag = ;
    profile = StoreAddItemsButton @ new () @ "BracketButton15NonDefaultProfile";
    GuiVariableWidthButtonCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "689 491";
    extent = "213 19";
    minExtent = "1 1";
    visible = 1;
    command = "StoreShoppingList.addItemsYoureWearing();";
    text = "Add Items You're Wearing To Cart";
    buttonType = "PushButton";
    drawText = 1;
    %theTab.add();
    0.setActive();
    %wi = AnimCtrl::newAnimCtrl("129 213", "18 18");
    StoreAddItemsButton;
    %wi.setDelay(60);
    %wi.addFrame("platform/client/ui/wait0.png");
    %wi.addFrame("platform/client/ui/wait1.png");
    %wi.addFrame("platform/client/ui/wait2.png");
    %wi.addFrame("platform/client/ui/wait3.png");
    %wi.addFrame("platform/client/ui/wait4.png");
    %wi.addFrame("platform/client/ui/wait5.png");
    %wi.addFrame("platform/client/ui/wait6.png");
    %wi.addFrame("platform/client/ui/wait7.png");
    %wi.add();
    waitIcon = StoreShoppingBag @ %wi @ StoreShoppingBag;
    %wi.setVisible(0);
    profile = GuiScrollCtrl @ new ""() @ "ETSScrollProfile";
    0;
    position = "3 22";
    extent = "239 232";
    minExtent = "1 1";
    horizSizing = "right";
    vertSizing = "bottom";
    visible = 1;
    hScrollBar = "alwaysOff";
    vScrollBar = "dynamic";
    constantThumbHeight = 1;
    scrollMultiplier = 2.5;
    %shoppingScroll = ;
    profile = StoreShoppingList @ new () @ "GuiDefaultProfile";
    GuiArray2Ctrl;
    childrenClassName = 0 @ "GuiMouseEventCtrl";
    childrenExtent = "233 36";
    spacing = 2;
    numRowsOrCols = 1;
    inRows = 0;
    canHilite = 0;
    scroll = %shoppingScroll;
    %shoppingList = ;
    %shoppingScroll.add(%shoppingList);
    %shoppingBag.add(%shoppingScroll);
    %theTab.add(%shoppingBag);
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "BracketButton19Profile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "829 519";
    extent = "43 19";
    minExtent = "1 1";
    visible = 1;
    command = "ClosetGui.close(false);";
    text = "Done";
    buttonType = "PushButton";
    drawText = 1;
    %doneButton = ;
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "BracketButton19NonDefaultProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "882 519";
    extent = "52 19";
    minExtent = "1 1";
    visible = 1;
    command = "ClosetGui.close(true);";
    text = "Cancel";
    buttonType = "PushButton";
    drawText = 1;
    %cancelButton = ;
    %theTab.add(%doneButton);
    doneButton = %doneButton @ %theTab;
    %theTab.add(%cancelButton);
    cancelButton = %cancelButton @ %theTab;
    1.setStoreControlsVisible();
    tabShopsInitialized = ClosetTabs @ 1 @ %this;
};
function ClosetTabs::setStoreControlsVisible(%this, %flag) {
    %flag.setVisible();
    %flag.setVisible();
    %flag.setVisible();
    %flag.setVisible();
    %flag.setVisible();
    %flag.setVisible();
    %flag.setVisible();
    %flag.setVisible();
    %flag.setVisible();
    %flag.setVisible();
    !(isInFUE()).setVisible();
    %flag.setVisible();
    %flag.setVisible();
    !(%flag).setVisible();
};
function ClosetTabs::setLeaveStoreControlsVisible(%this, %flag) {
    %flag.setVisible();
    %flag.setVisible();
};
function StoreShoppingList::onCreatedChild(%this, %child) {
    profile = GuiControl @ new ""() @ "ClosetLtBackgroundProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "233 36";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    %background = ;
    profile = GuiControl @ new ""() @ "ClosetHiliteProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "233 36";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 0;
    %hilite = ;
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "StoreItemButtonProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "1 2";
    extent = "208 15";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = "";
    groupNum = -1;
    buttonType = "PushButton";
    command = "";
    drawText = 1;
    %itemDesc = ;
    profile = GuiBitmapButtonCtrl @ new ""() @ "GuiDefaultProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "213 4";
    extent = "10 10";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    command = "StoreShoppingList.removeSku(" @ %child.getId() @ ".sku);";
    text = "";
    groupNum = -1;
    buttonType = "PushButton";
    bitmap = "platform/client/buttons/closet_close";
    drawText = 0;
    %closeBox = ;
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "208 16";
    extent = "20 20";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "";
    modulationColor = "255 255 255 100";
    %expiringIcon = ;
    profile = GuiMLTextCtrl @ new ""() @ "ClosetPointsProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "6 18";
    extent = "60 18";
    minExtent = "60 1";
    sluggishness = -1;
    visible = 1;
    allowColorChars = 0;
    maxChars = -1;
    text = "";
    %pointsLink = ;
    profile = GuiMLTextCtrl @ new ""() @ "ClosetBuxProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "78 18";
    extent = "50 18";
    minExtent = "50 1";
    sluggishness = -1;
    visible = 1;
    allowColorChars = 0;
    maxChars = -1;
    text = "";
    %buxLink = ;
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "HiddenBracketButton15Profile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "1 18";
    extent = "132 16";
    minExtent = "1 1";
    visible = 1;
    command = "ClosetGui.purchaseSkus(" @ %child @ ".sku);";
    text = "";
    buttonType = "PushButton";
    drawText = 0;
    %totalButton = ;
    %child.add(%background);
    %child.add(%hilite);
    %child.add(%itemDesc);
    %child.add(%expiringIcon);
    %child.add(%buxLink);
    %child.add(%pointsLink);
    %child.add(%totalButton);
    %child.add(%closeBox);
    background = %background @ %child;
    hiliteCtrl = %hilite @ %child;
    desc = %itemDesc @ %child;
    expiringIcon = %expiringIcon @ %child;
    pointsLink = %pointsLink @ %child;
    buxLink = %buxLink @ %child;
    points = "-" @ %child;
    bux = "-" @ %child;
    sku = 0 @ %child;
    shoppingList = %this @ %child;
    %child.bindClassName("StoreShoppingListItem");
};
function StoreShoppingList::addSku(%this, %sku) {
    return (0.0 >= findWord($Player::inventory, %sku));
    %count = %this.getCount();
    %idx = 0;
    return (%this.getObject(%idx) SPC sku $= %sku);
    %idx = (1.0 + %idx);
    %child = %this.addChild();
    (%count < %idx);
    sku = %sku @ %child;
    %si = %sku.findBySku();
    SkuManager;
    desc.setText(descShrt);
    command = %child @ desc;
    %child @ %si @ "ClosetGui.toggleSku(" @ %sku @ ");" @ "ClosetThumbnailsShop.scroll.scrollToSku(" @ %sku @ ");";
    %pointsIcon = "<bitmap:platform/client/ui/vpoints_9>";
    %buxIcon = "<bitmap:platform/client/ui/vbux_9>";
    points = %child @ Inventory::getVPointsPriceForSku(sku) @ %child;
    bux = %child @ Inventory::getVBuxPriceForSku(sku) @ %child;
    pointsLink.setText(%child @ points);
    buxLink.setText(%child @ bux);
    expiringIcon.setBitmap("platform/client/ui/expiring_icon");
    expiringIcon.setVisible(1);
    expiringIcon.setBitmap("");
    expiringIcon.setVisible(0);
    %count = thumbnails.getCount();
    StoreItemsFrame;
    %i = 0;
    %child;
    %obj = thumbnails.getObject(%i);
    StoreItemsFrame;
    toggleCartButton.setBitmap("platform/client/buttons/removeFromCart");
    %i = (1.0 + %i);
    %obj;
    %this.update();
    %this.hiliteCell(0, (1.0 - %this.getCount()));
};
function StoreShoppingList::addSkus(%this, %skulist) {
    %skulist = trim(%skulist);
    %count = getWordCount(%skulist);
    %i = 0;
    %this.addSku(getWord(%skulist, %i));
    %i = (1.0 + %i);
    (%count < %i);
};
function StoreShoppingList::removeSku(%this, %sku) {
    %count = %this.getCount();
    %i = 0;
    %obj = %this.getObject(%i);
    (%count < %i);
    %obj.delete();
    %i = (1.0 + %i);
    (%obj == sku);
    %count = thumbnails.getCount();
    StoreItemsFrame;
    %i = 0;
    (%count < %i);
    %obj = thumbnails.getObject(%i);
    StoreItemsFrame;
    toggleCartButton.setBitmap("platform/client/buttons/add2cart");
    %i = (1.0 + %i);
    %obj;
    1.setActive();
    %this.update();
};
function StoreShoppingList::removeSkus(%this, %skulist) {
    %skulist = trim(%skulist);
    %count = getWordCount(%skulist);
    %i = 0;
    %this.removeSku(getWord(%skulist, %i));
    %i = (1.0 + %i);
    (%count < %i);
};
function StoreShoppingList::clear(%this) {
    %this.removeSkus(%this.getSkus());
};
function StoreShoppingList::containsSku(%this, %sku) {
    %count = %this.getCount();
    %i = 0;
    return 1;
    %i = (1.0 + %i);
    return 0;
};
function StoreShoppingList::getSkus(%this) {
    %skus = "";
    %count = %this.getCount();
    %i = 0;
    %skus = %this.getObject(%i) @ sku;
    %skus @ " ";
    %i = (1.0 + %i);
    (%count < %i);
    return trim(%skus);
};
function StoreShoppingList::addItemsYoureWearing(%this) {
    %count = getWordCount($StoreSkusLayer);
    %i = 0;
    %this.addSku(getWord($StoreSkusLayer, %i));
    %i = (1.0 + %i);
    (%count < %i);
    0.setActive();
};
function StoreShoppingList::clear(%this) {
    Parent::clear(%this);
    %this.update();
};
function StoreShoppingList::update(%this) {
    (0.0 == %this.getCount()).setVisible();
    %this.reseatChildren();
    %this.sumPrices();
    %count = %this.getCount();
    StoreNoItemsText;
    %i = 0;
    %child = %this.getObject(%i);
    (%count < %i);
    // unhandled opcode 8756 at 0x00002231
    background.setProfile();
    %i = (1.0 + %i);
    ClosetDkBackgroundProfile;
};
function StoreShoppingList::sumPrices(%this) {
    %pointsSum = 0;
    %buxSum = 0;
    %count = %this.getCount();
    %idx = 0;
    %child = %this.getObject(%idx);
    (%count < %idx);
    %pointsSum = (points + %pointsSum);
    %child;
    %buxSum = (bux + %buxSum);
    %child;
    %idx = (1.0 + %idx);
    !((%child SPC bux $= "-"));
    %pointsIcon = "<bitmap:platform/client/ui/vpoints_9>";
    (%count < %idx);
    %buxIcon = "<bitmap:platform/client/ui/vbux_9>";
    !((%child SPC points $= "-"));
    StorePointsTotalText @ %pointsIcon @ " " @ %pointsSum.setText();
    StoreBuxTotalText @ %buxIcon @ " " @ %buxSum.setText();
    pointsTotal = %pointsSum @ %this;
    buxTotal = %buxSum @ %this;
};
function StoreShoppingList::scrollToItem(%this, %item) {
    %idx = %this.getObjectIndex(%item);
    %scroll = scroll;
    %this;
    %cellHeight = (%this + getWord(childrenExtent, 1));
    spacing;
    %numRowsVisible = (%cellHeight / getWord(%scroll.getExtent(), 1));
    %this;
    %ypos = (getWord(%this.getPosition(), 1) - 1.0);
    (0.0 >= %idx);
    %closestRow = (%cellHeight / %ypos);
    %targetRow = getWord(hilitedCell, 1);
    %this;
    %scroll.scrollTo(0, (%targetRow * %cellHeight));
    %scroll.scrollTo(0, ((spacing * 2.0) + ((1.0 + (%numRowsVisible - %targetRow)) * %cellHeight)));
};
function StoreShoppingListItem::onMouseEnterBounds(%this) {
    %idx = shoppingList.getObjectIndex(%this);
    %this;
    shoppingList.hiliteCell(0, %idx);
};
function StoreShoppingListItem::onMouseLeaveBounds(%this) {
    %this.onUnhilite();
};
function StoreShoppingListItem::onHilite(%this) {
    sku.getShortSkuDesc().setDesc();
    sku.getLongSkuDesc().setDesc();
    sku.updateAuthorWidget();
    %this.scrollToItem();
    hiliteCtrl.setVisible(1);
};
function StoreShoppingListItem::onUnhilite(%this) {
    showBaseDesc();
    showBaseDesc();
    "".updateAuthorWidget();
    0.setVisible();
    0.setVisible();
    hiliteCtrl.setVisible(0);
};
function StoreBalanceText::update(%this) {
    %pointsIcon = "<bitmap:platform/client/ui/vpoints_14>";
    %buxIcon = "<bitmap:platform/client/ui/vbux_14>";
    %pointsInfoLink = "<spush><linkcolor:159fe7><a:gamelink " @ $Net::HelpURL_VPoints @ ">>> How to earn vPoints</a><spop>";
    %getBuxLink = "<spush><linkcolor:13b93c><a:gamelink " @ $Net::AddFundsURL @ ">>> Get more vBux</a><spop>";
    %this.setText("You Have   " @ "<spush><font:Arial Bold:16><color:159fe7>" @ %pointsIcon @ " " @ commaify($Player::VPoints) @ "<spop>" @ "   " @ "<spush><font:Arial Bold:16><color:13b93c>" @ %buxIcon @ " " @ commaify($Player::VBux) @ "<spop>" @ "<br>" @ "<font:Arial Bold:13>" @ %pointsInfoLink @ "   " @ %getBuxLink);
};
function StoreBalanceText::onURL(%this, %url) {
    %url = getWords(%url, 1);
    (getWord(%url, 0) $= "gamelink");
    Parent::onURL(%this, %url);
};
function StoreItemsFrame::update(%this) {
    infoText.setText("Loading store inventory...");
    infoText.setText("Nothing in stock!");
    infoText.setText("No matching items.");
    thumbnails.setDrawers(strlwr(category).get());
};
function StoreCategoryPopup::onSelect(%this, %unused, %entries) {
    category = %entries @ StoreItemsFrame;
    update();
    0.schedule("setBaseDesc", "");
    0.schedule("setBaseDesc", "");
    getParent().scrollToTop();
};
function StoreLongDescText::setBaseDesc(%this, %desc) {
    baseText = %desc @ %this;
    %this.setText(%desc);
    0.setVisible();
    0.setVisible();
};
function StoreLongDescText::setDesc(%this, %desc) {
    %this.setText(%desc);
};
function StoreLongDescText::showBaseDesc(%this) {
    %this.setText(baseText);
};
function StoreShortDescText::setBaseDesc(%this, %desc) {
    StoreLongDescText::setBaseDesc(%this, %desc);
};
function StoreShortDescText::setDesc(%this, %desc) {
    StoreLongDescText::setDesc(%this, %desc);
};
function StoreShortDescText::showBaseDesc(%this) {
    StoreLongDescText::showBaseDesc(%this, %desc);
};
function getCurrentStoreID() {
    %storename = stripChars($gCurrentStoreName, 0123456789);
    %storename = "edoc";
    (%storename $= "edocsecret");
    return $gCurrentStoreName;
    return %storename;
};
function StoreBanner::doAction(%this) {
    %storename = getCurrentStoreID();
    gotoWebPage(!((%storename $= "")) @ $Net::PartnerURL @ "/" @ %storename, 0);
};
function updateAccountBalanceDisplays() {
    update();
    update();
};
function clientCmdUpdateAccountBalances(%newPoints, %newBux) {
    BalanceUpdateSpecialEffects("vBux", $Player::VBux, %newBux, 1);
    $Player::VBux = mFloor(%newBux);
    !((%newBux $= ""));
    BalanceUpdateSpecialEffects("vPoints", $Player::VPoints, %newPoints, 1);
    $Player::VPoints = mFloor(%newPoints);
    !((%newPoints $= ""));
    updateAccountBalanceDisplays();
};
function clientCmdRefreshVPoints() {
    getBalancesAndScores();
};
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"] = 150;
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"] = 300;
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"] = 1;
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vPoints"] = 100;
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vBux"] = 1;
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vPoints"] = 1000;
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound1 @ "vBux"] = "AudioIm_CaChing";
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound1 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound1 @ "vPoints"] = "AudioIm_vPoints1";
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound1 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound2 @ "vBux"] = "AudioIm_CaChing";
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound1 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound2 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound2 @ "vPoints"] = "AudioIm_vPoints2";
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound1 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound2 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound2 @ "vPoints"][$gBalanceUpdateSpecialEffect_GuiControl1 @ "vBux"] = "AccountBalanceVBuxText";
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound1 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound2 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound2 @ "vPoints"][$gBalanceUpdateSpecialEffect_GuiControl1 @ "vBux"][$gBalanceUpdateSpecialEffect_GuiControl1 @ "vPoints"] = "AccountBalanceVPointsText";
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound1 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound2 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound2 @ "vPoints"][$gBalanceUpdateSpecialEffect_GuiControl1 @ "vBux"][$gBalanceUpdateSpecialEffect_GuiControl1 @ "vPoints"][$gBalanceUpdateSpecialEffect_GuiControl2 @ "vBux"] = "";
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound1 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound2 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound2 @ "vPoints"][$gBalanceUpdateSpecialEffect_GuiControl1 @ "vBux"][$gBalanceUpdateSpecialEffect_GuiControl1 @ "vPoints"][$gBalanceUpdateSpecialEffect_GuiControl2 @ "vBux"][$gBalanceUpdateSpecialEffect_GuiControl2 @ "vPoints"] = "AccountBalanceHud";
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound1 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound2 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound2 @ "vPoints"][$gBalanceUpdateSpecialEffect_GuiControl1 @ "vBux"][$gBalanceUpdateSpecialEffect_GuiControl1 @ "vPoints"][$gBalanceUpdateSpecialEffect_GuiControl2 @ "vBux"][$gBalanceUpdateSpecialEffect_GuiControl2 @ "vPoints"][$gBalanceUpdateSpecialEffect_PulseCount1 @ "vBux"] = 1;
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound1 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound2 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound2 @ "vPoints"][$gBalanceUpdateSpecialEffect_GuiControl1 @ "vBux"][$gBalanceUpdateSpecialEffect_GuiControl1 @ "vPoints"][$gBalanceUpdateSpecialEffect_GuiControl2 @ "vBux"][$gBalanceUpdateSpecialEffect_GuiControl2 @ "vPoints"][$gBalanceUpdateSpecialEffect_PulseCount1 @ "vBux"][$gBalanceUpdateSpecialEffect_PulseCount1 @ "vPoints"] = 1;
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound1 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound2 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound2 @ "vPoints"][$gBalanceUpdateSpecialEffect_GuiControl1 @ "vBux"][$gBalanceUpdateSpecialEffect_GuiControl1 @ "vPoints"][$gBalanceUpdateSpecialEffect_GuiControl2 @ "vBux"][$gBalanceUpdateSpecialEffect_GuiControl2 @ "vPoints"][$gBalanceUpdateSpecialEffect_PulseCount1 @ "vBux"][$gBalanceUpdateSpecialEffect_PulseCount1 @ "vPoints"][$gBalanceUpdateSpecialEffect_PulseCount2 @ "vBux"] = 4;
$Player::VPoints[$gBalanceUpdateSpecialEffect_Delay @ "vBux"][$gBalanceUpdateSpecialEffect_Delay @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vBux"][$gBalanceUpdateSpecialEffect_Threshhold2 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound1 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound1 @ "vPoints"][$gBalanceUpdateSpecialEffect_Sound2 @ "vBux"][$gBalanceUpdateSpecialEffect_Sound2 @ "vPoints"][$gBalanceUpdateSpecialEffect_GuiControl1 @ "vBux"][$gBalanceUpdateSpecialEffect_GuiControl1 @ "vPoints"][$gBalanceUpdateSpecialEffect_GuiControl2 @ "vBux"][$gBalanceUpdateSpecialEffect_GuiControl2 @ "vPoints"][$gBalanceUpdateSpecialEffect_PulseCount1 @ "vBux"][$gBalanceUpdateSpecialEffect_PulseCount1 @ "vPoints"][$gBalanceUpdateSpecialEffect_PulseCount2 @ "vBux"][$gBalanceUpdateSpecialEffect_PulseCount2 @ "vPoints"] = 4;
function BalanceUpdateSpecialEffects(%whichBalance, %oldVal, %newVal, %notify) {
    %delta = (%oldVal - %newVal);
    schedule(3000, 0, "floatBalanceChange", %whichBalance, %delta, $player);
    %threshhold1 = %whichBalance[$gBalanceUpdateSpecialEffect_Threshhold1 @ %whichBalance];
    %notify;
    return (%threshhold1 < %delta);
    %delay = %whichBalance[$gBalanceUpdateSpecialEffect_Delay @ %whichBalance];
    %threshhold2 = %whichBalance[$gBalanceUpdateSpecialEffect_Threshhold2 @ %whichBalance];
    %sound1 = %whichBalance[$gBalanceUpdateSpecialEffect_Sound1 @ %whichBalance];
    %sound2 = %whichBalance[$gBalanceUpdateSpecialEffect_Sound2 @ %whichBalance];
    %guiControl1 = %whichBalance[$gBalanceUpdateSpecialEffect_GuiControl1 @ %whichBalance];
    %guiControl2 = %whichBalance[$gBalanceUpdateSpecialEffect_GuiControl2 @ %whichBalance];
    %pulseCount1 = %whichBalance[$gBalanceUpdateSpecialEffect_PulseCount1 @ %whichBalance];
    %pulseCount2 = %whichBalance[$gBalanceUpdateSpecialEffect_PulseCount2 @ %whichBalance];
    %sound = %sound1;
    (%threshhold2 < %delta);
    %pulseCount = %pulseCount1;
    %sound = %sound2;
    %pulseCount = %pulseCount2;
    alxPlay(%sound);
    %guiControl1.schedule(%delay, "blinkSet", "bounce", 150, 100, "0 -1 0 0", 5);
    %guiControl2.startPulse(%pulseCount);
};
function floatBalanceChange(%whichBalance, %change, %player) {
    %threshhold = 1;
    return (%threshhold < %change);
    error(getScopeName() @ " " @ "- can't find player!" @ " " @ getTrace());
    return !(isObject(%player));
    error(getScopeName() @ " " @ "- no hudCtrl to attach to!" @ " " @ getTrace());
    return !(isObject(hudCtrl));
    %isVPoints = (%whichBalance $= "vPoints");
    %alot = 100;
    1000;
    %amountNorm = mClampF((%alot / %change), 0, 1);
    %isVPoints;
    %amountNorm = (((%amountNorm - 1.0) * (%amountNorm - 1.0)) - 1.0);
    %isALot = (0.95 > %amountNorm);
    %speed = (3.0 + (2.0 * (%amountNorm - 1.0)));
    %fontTag = "<font:arial:14>";
    "<font:arial:18>";
    %currencyText = "vBux";
    "vPoints";
    %text = %isVPoints @ %fontTag @ "<b><outline>+" @ " " @ %change @ " " @ %currencyText;
    %isALot;
    %maxAge = (70.0 + (70.0 * %amountNorm));
    %baseColor = "22dd44";
    "55eeff";
    %baseAlpha = (0.6 + (0.4 * %amountNorm));
    %isVPoints;
    %player.floatText(%text, %maxAge, %speed, %baseColor, %baseAlpha);
};
function Player::floatText(%this, %text, %maxAge, %speed, %baseColor, %baseAlpha) {
    hudCtrl.updatePosition();
    %text = %this @ "<just:center>" @ %text;
    %width = 600;
    extent = GuiMLTextCtrl @ new ""() @ %width @ " " @ 18;
    0;
    position = (hudCtrl - getWord(position, 0)) @ " " @ 100.0 @ %this @ (hudCtrl + getWord(position, 1));
    %this;
    age = (2.0 / %width) @ 0;
    maxAge = %maxAge;
    speed = %speed;
    BaseColor = %baseColor;
    baseText = %text;
    baseAlpha = %baseAlpha;
    %ctrl = ;
    %ctrl.add();
    doTick();
};
function Player::floatTextSimple(%this, %text, %style) {
    %style = "";
    !(isDefined("%style"));
    %style = "default";
    (%style $= "");
    error(getScopeName() @ " " @ "- unknown style:" @ " " @ %style @ " " @ %text @ " " @ getTrace());
    %style = "default";
    (%style[$gFloatingTextStyles TAB "font" @ %style] $= "");
    %outline = "";
    "<b><outline>";
    %text = %style[%style[$gFloatingTextStyles TAB "outline" @ %style] @ "<font:" @ $gFloatingTextStyles TAB "font" @ %style] @ ">" @ %text;
    %text = %outline @ %text;
    %text = %style[$gFloatingTextStyles TAB "prepend" @ %style] @ %text;
    %text = %style[%text @ $gFloatingTextStyles TAB "append" @ %style];
    %baseColor = %style[$gFloatingTextStyles TAB "color" @ %style];
    %baseAlpha = %style[$gFloatingTextStyles TAB "baseAlpha" @ %style];
    %maxAge = %style[$gFloatingTextStyles TAB "maxAge" @ %style];
    %speed = %style[$gFloatingTextStyles TAB "speed" @ %style];
    %this.floatText(%text, %maxAge, %speed, %baseColor, %baseAlpha);
};
function ClientCmdFloatText(%playerGhostID, %text, %style) {
    %player = %playerGhostID.resolveGhostID();
    ServerConnection;
    error(getScopeName() @ " " @ "- could not resolve ghost" @ " " @ %playerGhostID @ " " @ %text);
    return !(isObject(%player));
    %player.floatTextSimple(%text, %style);
};
function ThePointsFloaterHud::doTick(%this) {
    cancel(timerID);
    timerID = %this @ "" @ %this;
    %numChildren = %this.getCount();
    return (1.0 < %numChildren);
    %n = (1.0 - %numChildren);
    %ctrl = %this.getObject(%n);
    (0.0 >= %n);
    %ageNorm = (%ctrl / age);
    maxAge;
    %ctrl.delete();
    age = (%ctrl + age);
    1.0;
    %x = getWord(position, 0);
    %ctrl;
    %y = getWord(position, 1);
    %ctrl;
    %x = (((0.2 - %ageNorm) * (%ctrl * speed)) + %x);
    3.0;
    %y = (speed - %y);
    %ctrl;
    %ctrl.reposition(%x, %y);
    %alpha = (baseAlpha * (%ageNorm - 1.0));
    %ctrl;
    %alpha = (((0.5 + (0.5 * mSin((0.03 * getSimTime())))) * %alpha) - 1.0);
    (0.2 < %ageNorm);
    %alpha1 = formatInt("%0.2X", (255.0 * %alpha));
    (0.2 > %ageNorm);
    %alpha2 = formatInt("%0.2X", (255.0 * 1.0));
    (1.0 > %ageNorm);
    %alpha2 = 00;
    (0.2 > %ageNorm);
    %colorTag = %ctrl @ "<color:" @ %ctrl @ BaseColor @ %alpha1 @ ">";
    %shadowTag = "<shadowcolor:" @ 000000 @ %alpha2 @ ">";
    %ctrl.setText(%ctrl @ baseText);
    %n = (1.0 - %n);
    %shadowTag @ %colorTag;
    timerID = %this @ %this.schedule(tickPeriodMS, "doTick") @ %this;
    (0.0 >= %n);
};
function clientCmdUpdateVPoints(%newPoints, %notify) {
    %notify = 1;
    !(isDefined("%notify"));
    BalanceUpdateSpecialEffects("vPoints", $Player::VPoints, %newPoints, %notify);
    $Player::VPoints = mFloor(%newPoints);
    !((%newPoints $= ""));
    updateAccountBalanceDisplays();
};
function clientCmdUpdateVBux(%newBux, %notify) {
    %notify = 1;
    !(isDefined("%notify"));
    BalanceUpdateSpecialEffects("vBux", $Player::VBux, %newBux, %notify);
    $Player::VBux = mFloor(%newBux);
    !((%newBux $= ""));
    updateAccountBalanceDisplays();
};
function ClosetGUI_ToggleSku_Shops(%sku) {
    %wordLoc = findWord($StoreSkusLayer, %sku);
    $StoreSkusLayer = removeWord($StoreSkusLayer, %wordLoc);
    (0.0 >= %wordLoc);
    "".setBaseDesc();
    "".setBaseDesc();
    "".updateAuthorWidget();
    $StoreSkusLayer = $StoreSkusLayer.overlaySkus(%sku);
    SkuManager;
    %sku.getShortSkuDesc().setBaseDesc();
    %sku.getLongSkuDesc().setBaseDesc();
    %sku.updateAuthorWidget();
    %count = getWordCount($StoreSkusLayer);
    ClosetTabs;
    %itemsToAdd = 0;
    ClosetTabs;
    %i = 0;
    StoreLongDescText;
    %sku2 = getWord($StoreSkusLayer, %i);
    (%count < %i);
    %itemsToAdd = 1;
    !(%sku2.containsSku());
    %i = (1.0 + %i);
    StoreShoppingList;
    %itemsToAdd.setActive();
};
