function ClosetTabs::fillClosetTab(%this) {
    %theTab = %this.getTabWithName("CLOSET");
    return !(isObject(%theTab));
    profile = GuiBitmapCtrl @ new ""() @ "GuiDefaultProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "26 26";
    extent = "571 37";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/closet_tabs_bracket";
    %theTab.add();
    profile = NoItemInBrandNameLabel @ new () @ "ClosetLeftInfoProfile";
    GuiMLTextCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "26 111";
    extent = "457 17";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    allowColorChars = 0;
    maxChars = -1;
    text = "";
    %theTab.add();
    profile = GuiTextCtrl @ new ""() @ "ClosetTitleProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "181 64";
    extent = "35 20";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = "Item";
    maxLength = 255;
    %itemLabel = ;
    %theTab.add(%itemLabel);
    profile = ClosetItemPopup @ new () @ "ClosetPopupProfile";
    GuiPopUp2MenuCtrl;
    scrollProfile = 0 @ "DottedScrollProfile";
    winProfile = "ClosetPopupWindowProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "180 84";
    extent = "150 24";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    maxLength = 255;
    maxPopupHeight = 200;
    allowReverse = 0;
    %itemPopup = ;
    %theTab.add(%itemPopup);
    %categoryList = "All Items" @ "\t" @ "All Garments" @ "\t" @ "All Accessories" @ "\t" @ "Tops" @ "\t" @ "Bottoms" @ "\t" @ "Shoes" @ "\t" @ "Ear" @ "\t" @ "Neck" @ "\t" @ "Waist" @ "\t" @ "Skin" @ "\t" @ "Hands" @ "\t" @ "Bags" @ "\t" @ "Glasses" @ "\t" @ "Props" @ "\t" @ "Misc" @ "\t" @ "BodyMod" @ "\t" @ "Badges" @ "\t" @ "Tokens";
    possibleCategoryList = %categoryList @ %itemPopup;
    displayedCategoryList = %categoryList @ %itemPopup;
    %n = 0;
    %category = getField(%categoryList, %n);
    (getFieldCount(%categoryList) < %n);
    %itemPopup.add(%category);
    %n = (1.0 + %n);
    Closet::skuListHasCategory($Player::inventory, %category);
    profile = GuiTextCtrl @ new ""() @ "ClosetTitleProfile";
    0;
    horizSizing = (getFieldCount(%categoryList) < %n) @ "right";
    vertSizing = "bottom";
    position = "27 64";
    extent = "104 20";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = "Brand";
    maxLength = 255;
    %brandLabel = ;
    %theTab.add(%brandLabel);
    profile = ClosetBrandPopup @ new () @ "ClosetPopupProfile";
    GuiPopUp2MenuCtrl;
    scrollProfile = 0 @ "DottedScrollProfile";
    winProfile = "ClosetPopupWindowProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "26 84";
    extent = "150 24";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    maxLength = 255;
    maxPopupHeight = 200;
    allowReverse = 0;
    %brandPopup = ;
    %theTab.add(%brandPopup);
    profile = ClosetItemsFrame @ new () @ "GuiDefaultProfile";
    GuiControl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "22 120";
    extent = "467 306";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    %itemsFrame = ;
    profile = GuiTextCtrl @ new ""() @ "ClosetLeftInfoProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "1 30";
    extent = "77 16";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 0;
    text = "no matching items";
    maxLength = 255;
    %itemsInfoText = ;
    %itemsFrame.add(%itemsInfoText);
    profile = GuiTextCtrl @ new ""() @ "ClosetRightInfoProfile";
    0;
    horizSizing = "left";
    vertSizing = "bottom";
    position = "313 1";
    extent = "125 14";
    minExtent = "125 1";
    sluggishness = -1;
    visible = 1;
    text = "";
    maxLength = 255;
    %itemsRangeText = ;
    %itemsFrame.add(%itemsRangeText);
    rangeText = %itemsRangeText @ %theTab;
    profile = GuiScrollCtrl @ new ""() @ "ETSScrollProfile";
    0;
    position = "0 20";
    extent = "465 282";
    minExtent = "1 1";
    horizSizing = "right";
    vertSizing = "bottom";
    visible = 1;
    hScrollBar = "dynamic";
    vScrollBar = "dynamic";
    constantThumbHeight = 1;
    scrollMultiplier = 14;
    %itemsScroll = ;
    %itemsScroll.bindClassName("ClosetItemsScroll");
    itemsScroll = %itemsScroll @ %theTab;
    class = ClosetThumbnailsCloset @ new () @ "ClosetThumbnails";
    GuiArray2Ctrl;
    profile = 0 @ "FocusableDefaultProfile";
    childrenClassName = "GuiMouseEventCtrl";
    childrenExtent = "109 138";
    spacing = 2;
    numRowsOrCols = 4;
    inRows = 0;
    canHilite = 0;
    infoText = %itemsInfoText;
    tab = %theTab;
    scroll = %itemsScroll;
    %thumbnails = ;
    %itemsScroll.add(%thumbnails);
    thumbnails = %thumbnails @ %itemsScroll;
    %itemsFrame.add(%itemsScroll);
    thumbnails = %thumbnails @ %itemsFrame;
    %theTab.add(%itemsFrame);
    thumbnails = %thumbnails @ %theTab;
    profile = ClosetShortDescText @ new () @ "ClosetLeftInfoProfile";
    GuiMLTextCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "692 84";
    extent = "242 25";
    lineSpacing = -(3.0);
    %theTab.add();
    profile = ClosetLongDescText @ new () @ "ClosetLeftInfoProfile";
    GuiMLTextCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "692 106";
    extent = "173 32";
    lineSpacing = -(3.0);
    %theTab.add();
    profile = ClosetMyOutfitsFrame @ new () @ "GuiDefaultProfile";
    GuiControl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "5 430";
    extent = "498 112";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "";
    profile = GuiBitmapCtrl @ new ""() @ "GuiDefaultProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 10";
    extent = "15 56";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/outfits";
    %myOutfitsFrame = ;
    profile = ClosetHangersFrame @ new () @ "GuiDefaultProfile";
    GuiMouseEventCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "21 0";
    extent = "471 112";
    minExtent = "1 1";
    sluggishness = -(1.0);
    visible = 1;
    %hangers = ;
    %myOutfitsFrame.add(%hangers);
    hangers = %hangers @ %myOutfitsFrame;
    %xPos = 0;
    %ypos = 0;
    %i = 0;
    profile = 0 @ new GuiObjectView @ "ClosetOutfitObjectView" @ %i() @ "GuiDefaultProfile";
    ($gClosetNumOutfits < %i);
    horizSizing = "right";
    vertSizing = "bottom";
    position = %xPos @ " " @ %ypos;
    extent = "46 112";
    minExtent = "1 1";
    sluggishness = -1;
    CamSluggishness = 0.0000001;
    visible = 1;
    %objectView = ;
    %objectView.setSimObject($player);
    %objectView.setRotation(0.2, 0, 2.8);
    %objectView.setLookAtNudge("0.2 -1 0.15");
    toonLineWidth = isObject($player) @ 2 @ %objectView;
    profile = GuiMLTextCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    position = "10 0";
    extent = "30 15";
    text = "<font:Arial:16><color:ffffff><b><outline><just:right>" @ " " @ (1.0 + %i) @ " ";
    visible = 0;
    %label = ;
    profile = GuiBitmapButtonCtrl @ new ""() @ "ClosetHangerButtonProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = %xPos @ " " @ %ypos;
    extent = "39 112";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    command = "ClosetMyOutfitsFrame.hangerSelected(" @ %i @ ");";
    text = (1.0 + %i);
    groupNum = $ClosetHangersGroup;
    buttonType = "RadioButton";
    bitmap = "platform/client/buttons/outfit";
    drawText = 0;
    index = %i;
    %button = ;
    %button.bindClassName("ClosetOutfitButton");
    %button.setName("ClosetOutfitButton" @ %i);
    %button.add(%label);
    label = %label @ %button;
    %hangers.add(%objectView);
    %hangers.add(%button);
    button = %button @ %i @ %hangers;
    %xPos = (39.0 + %xPos);
    %i = (1.0 + %i);
    %theTab.add(%myOutfitsFrame);
    profile = ClosetWhatYourWearingContainer @ new () @ "ETSNonModalProfile";
    GuiControl;
    horizSizing = ($gClosetNumOutfits < %i) @ 0 @ "right";
    vertSizing = "bottom";
    position = "689 207";
    extent = "245 281";
    %whatYoureWearingContainer = ;
    %whatYoureWearingPanel = %this.createWhatYourWearingPanel();
    %whatYoureWearingContainer.add(%whatYoureWearingPanel);
    %theTab.add(%whatYoureWearingContainer);
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "BracketButton19Profile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "829 519";
    extent = "43 19";
    minExtent = "1 1";
    visible = 1;
    command = "ClosetGui.close(false);";
    text = "Done";
    buttonType = "PushButton";
    drawText = 1;
    %doneButton = ;
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "BracketButton19NonDefaultProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "882 519";
    extent = "52 19";
    minExtent = "1 1";
    visible = 1;
    command = "ClosetGui.close(true);";
    text = "Cancel";
    buttonType = "PushButton";
    drawText = 1;
    %cancelButton = ;
    %theTab.add(%doneButton);
    doneButton = %doneButton @ %theTab;
    %theTab.add(%cancelButton);
    cancelButton = %cancelButton @ %theTab;
    %skus = getFilteredInventoryForSetDrawers();
    %brandPopup.update(%skus);
    %itemPopup.update(%skus);
    %brandPopup.SetSelected(0);
    %itemPopup.SetSelected(0);
    update();
    tabClosetInitialized = ClosetItemsFrame @ 1 @ %this;
};
function ClosetTabs::getOutfitObjectView(%this, %index) {
    return "ClosetOutfitObjectView" @ %index;
};
function ClosetTabs::getOutfitButton(%this, %index) {
    return "ClosetOutfitButton" @ %index;
};
function ClosetTabs::updateOutfitObjectView(%this, %index) {
    %objectView = %this.getOutfitObjectView(%index);
    %name = %index.getOutfitNameForHanger();
    ClosetMyOutfitsFrame;
    %objectView.setSkus($ClosetSkusBody @ " " @ %name[$ClosetSkusOutfit @ %name]);
};
$gSwimsuitOutfitIndex = 6;
function ClosetTabs::doCopyOutfit(%this, %src, %dest) {
    %title = $gSwimsuitOutfitIndex[$MsgCat::closet TAB "MSG-COPY-OUTFIT-WARN" @ "TITLE"];
    %body = %title[$MsgCat::closet TAB "MSG-COPY-OUTFIT-WARN" @ "BODY"];
    %body = strreplace(%body, "[SRC]", (1.0 + %src));
    %body = strreplace(%body, "[DST]", (1.0 + %dest));
    %body = ($gSwimsuitOutfitIndex == %dest) @ %body[%body @ "\n" @ "" @ "\n" @ $MsgCat::closet TAB "MSG-COPY-OUTFIT-WARN" @ "SWIM"];
    MessageBoxYesNo(%title, %body, "ClosetTabs.doCopyOutfitReally(" @ %src @ ", " @ %dest @ ");", "");
};
function ClosetTabs::doCopyOutfitReally(%this, %src, %dest) {
    %srcName = %src.getOutfitNameForHanger();
    ClosetMyOutfitsFrame;
    %destName = %dest.getOutfitNameForHanger();
    ClosetMyOutfitsFrame;
    %destName[$ClosetSkusOutfit @ %destName] = %srcName[$ClosetSkusOutfit @ %srcName];
    %dest.updateOutfitObjectView();
    %dest.getOutfitButton().performClick();
};
function ClosetTabs::doSwapOutfits(%this, %src, %dest) {
    %title = %dest[($gSwimsuitOutfitIndex == %dest) @ $MsgCat::closet TAB "MSG-SWAP-OUTFIT-WARN" @ "TITLE"];
    ($gSwimsuitOutfitIndex == %src);
    %body = %title[$MsgCat::closet TAB "MSG-SWAP-OUTFIT-WARN" @ "BODY"];
    MessageBoxYesNo(%title, %body, "ClosetTabs.doSwapOutfitsReally(" @ %src @ ", " @ %dest @ ");", "");
    %this.doSwapOutfitsReally(%src, %dest);
};
function ClosetTabs::doSwapOutfitsReally(%this, %src, %dest) {
    %srcName = %src.getOutfitNameForHanger();
    ClosetMyOutfitsFrame;
    %destName = %dest.getOutfitNameForHanger();
    ClosetMyOutfitsFrame;
    %tmp = %srcName[$ClosetSkusOutfit @ %srcName];
    %srcName[$ClosetSkusOutfit @ %srcName] = %destName[$ClosetSkusOutfit @ %destName];
    %destName[$ClosetSkusOutfit @ %destName] = %tmp;
    %src.updateOutfitObjectView();
    %dest.updateOutfitObjectView();
    %dest.getOutfitButton().performClick();
};
function ClosetOutfitButton::onMouseDown(%this) {
    origin = Canvas @ getCursorPos() @ %this;
};
function ClosetOutfitButton::onMouseDragged(%this, %modifier) {
    %vec = VectorSub(origin, getCursorPos());
    Canvas;
    return 0;
    %mask = $EventModifier::CTRL;
    $EventModifier::ALT;
    operation = "COPY" @ "SWAP" @ %this;
    (%mask & %modifier);
    %this.setAsDragControl(1);
    return 1;
};
function ClosetOutfitButton::makeVisualClone(%this) {
    profile = GuiObjectView @ new ""() @ "GuiDefaultProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "46 112";
    minExtent = "1 1";
    sluggishness = -1;
    CamSluggishness = 0.0000001;
    visible = 1;
    %objectView = ;
    %objectView.setSimObject($player);
    %objectView.setRotation(0.2, 0, 2.8);
    %objectView.setLookAtNudge("0.2 -1 0.15");
    toonLineWidth = isObject($player) @ 2 @ %objectView;
    %objectView.setSkus($ClosetSkusOutfit @ ClosetMyOutfitsFrame);
    profile = GuiMLTextCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    position = $ClosetSkusBody @ " " @ "10 0";
    extent = "30 15";
    text = "<font:Arial:16><color:ffffff><b><outline><just:right>" @ " " @ 1.0 @ (%this + index) @ " ";
    %label = ;
    operation = (%this SPC operation $= "") @ "SWAP" @ %this;
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "20 76";
    extent = "20 20";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 0;
    bitmap = "platform/client/ui/" @ %this @ operation;
    %operationIcon = ;
    position = GuiBitmapButtonCtrl @ new ""() @ "0 0";
    0;
    extent = %this.getExtent();
    bitmap = %this @ bitmap;
    %clone = ;
    %clone.add(%objectView);
    %clone.add(%label);
    %clone.add(%operationIcon);
    operationIcon = %operationIcon @ %clone;
    clone = %clone @ %this;
    return %clone;
};
function ClosetOutfitButton::dragAndDropCtrl(%this, %make) {
    operation = %make @ "COPY" @ %this;
    operation = "SWAP" @ %this;
    operationIcon.setBitmap(%this @ operation);
};
function ClosetOutfitButton::onDragSet(%this) {
    depressed = 1 @ %this;
    %i = 0;
    %button = %i.getOutfitButton();
    mouseOver = isObject(ClosetTabs) @ 0 @ %button;
    %i = (1.0 + %i);
    %button = %i.getOutfitButton();
    centerDragHiliteAroundCursor();
    mouseOver = %this @ clone;
    Canvas @ 1;
};
function ClosetOutfitButton::onDragReleased(%this) {
    depressed = 0 @ %this;
};
function ClosetOutfitButton::onDragAndDropEnter(%this, %dragCtrl) {
    return (-(1.0) == findWord(%dragCtrl.getNamespaceList(), "ClosetOutfitButton"));
    hiliteControl(%this, 1);
    depressed = (%dragCtrl != %this) @ 1 @ %this;
    operationIcon.setVisible(1);
    label.setVisible(1);
};
function ClosetOutfitButton::onDragAndDropLeave(%this, %dragCtrl) {
    hiliteControl(0);
    depressed = (%dragCtrl != %this) @ 0 @ %this;
    operationIcon.setVisible(0);
    label.setVisible(0);
};
function ClosetOutfitButton::onDragAndDropDrop(%this, %dragCtrl, %unused) {
    return 0;
    return 0;
    index.doCopyOutfit(index);
    index.doSwapOutfits(index);
    return 1;
};
function ClosetBrandPopup::update(%this, %skus) {
    %this.clear();
    %i = 0;
    %brand = getField($gClosetBrands, %i);
    (getFieldCount($gClosetBrands) < %i);
    %this.add(%brand);
    %i = (1.0 + %i);
    %skus.skusHaveBrands(SkuManager @ %brand[$gClosetBrandsIntrnl @ %brand] @ " ");
};
function ClosetItemPopup::update(%this, %skus) {
    "".setText();
    %prevSelText = %this.getTextById(%this.GetSelected());
    NoItemInBrandNameLabel;
    %newList = "";
    !((%skus $= ""));
    %n = 0;
    %category = getField(possibleCategoryList, %n);
    %this;
    %newList = %newList @ "\t" @ %category;
    Closet::skuListHasCategory(%skus, %category);
    %n = (1.0 + %n);
    (getFieldCount(possibleCategoryList) < %n);
    %newList = trim(%newList);
    (getFieldCount(possibleCategoryList) < %n);
    return (%this $= displayedCategoryList);
    %newList = getField(possibleCategoryList, 0);
    %this;
    displayedCategoryList = %newList @ %this;
    %prevSelText = %this.getTextById(%this.GetSelected());
    %this.clear();
    %n = 0;
    %this.add(getField(%newList, %n));
    %n = (1.0 + %n);
    (getFieldCount(%newList) < %n);
    %newSel = %this.findText(%prevSelText);
    (getFieldCount(%newList) < %n);
    %this.SetSelected(0);
    %brandString = "";
    (ClosetBrandPopup SPC getText() $= "All");
    %brandString = " basic";
    (ClosetBrandPopup SPC getText() $= "Basic");
    %brandString = ClosetBrandPopup @ getText() @ " " @ "brand";
    (0.0 < %newSel) @ " ";
    %categoryString = strlwr(%prevSelText);
    restWords(%prevSelText);
    %categoryString = "clothes";
    ((firstWord(%prevSelText) $= "All") SPC %categoryString $= "");
    %msg = %categoryString[$MsgCat::closet @ "H-NO-BRAND-ITEMS1"] @ %brandString @ " " @ %categoryString @ %categoryString[$MsgCat::closet @ "H-NO-BRAND-ITEMS2"] @ %brandString @ " " @ %brandString[$MsgCat::closet @ "H-NO-BRAND-ITEMS3"];
    %msg.setText();
    %this.setText(%prevSelText);
};
function ClosetItemsFrame::update(%this) {
    thumbnails.setDrawers("");
};
function ClosetMyOutfitsFrame::getOutfitNameForHanger(%this, %hanger) {
    return getWord(, %hanger);
};
function ClosetMyOutfitsFrame::hangerSelected(%this, %hanger) {
    currentHanger = %hanger @ %this;
    $ClosetOutfitName = %this.getOutfitNameForHanger(%hanger);
    update();
    thumbnails.setSelectedThumbs();
    updateVisibleAvatar();
};
function ClosetItemPopup::onSelect(%this, %unused, %entries) {
    return (ClosetItemsFrame SPC category $= %entries);
    category = %entries @ ClosetItemsFrame;
    $gUpdatingClosetItemPopupFromThumbnailsSetDrawers = 0;
    $gUpdatingClosetItemPopupFromThumbnailsSetDrawers;
    return;
    update();
    getParent().scrollToTop();
};
function ClosetBrandPopup::onSelect(%this, %unused, %entries) {
    return (ClosetItemsFrame SPC brand $= %entries);
    brand = %entries @ ClosetItemsFrame;
    update();
    getParent().scrollToTop();
};
function ClosetWhatYoureWearingList::onCreatedChild(%this, %child) {
    %currentTabName = name;
    getCurrentTab();
    profile = GuiControl @ new ""() @ "ClosetLtBackgroundProfile";
    0;
    horizSizing = ClosetTabs @ "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "228 36";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    %background = ;
    profile = GuiControl @ new ""() @ "ClosetHiliteProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "228 36";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 0;
    %hilite = ;
    profile = GuiMLTextCtrl @ new ""() @ "ClosetSmallLinkProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "5 2";
    extent = "206 15";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = "";
    groupNum = -1;
    command = "";
    drawText = 1;
    %itemDesc = ;
    %itemDesc.bindClassName();
    profile = GuiBitmapButtonCtrl @ new ""() @ "GuiDefaultProfile";
    0;
    horizSizing = ClosetWhatYoureWearingButton @ "right";
    vertSizing = "bottom";
    position = "213 4";
    extent = "10 10";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    command = "ClosetThumbnailsCloset.scroll.scrollToSku(" @ %child.getId() @ ".sku); ClosetGui.toggleSku(" @ %child.getId() @ ".sku);";
    text = "";
    groupNum = -1;
    buttonType = "PushButton";
    bitmap = "platform/client/buttons/closet_close";
    drawText = 0;
    %closeBox = ;
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "211 19";
    extent = "16 16";
    modulationColor = "255 255 255 100";
    %ugcStatusIcon = ;
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "88 16";
    extent = "20 20";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "";
    modulationColor = "255 255 255 100";
    %expiringIcon = ;
    profile = GuiMLTextCtrl @ new ""() @ "ClosetSmallLinkProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "80 18";
    extent = (%currentTabName $= "MY DESIGNS") @ 18.0 @ (0.0 - 146.0) @ " " @ 15;
    %authorText = ;
    %child.add(%background);
    %child.add(%hilite);
    %child.add(%ugcStatusIcon);
    %child.add(%itemDesc);
    %child.add(%expiringIcon);
    %child.add(%closeBox);
    %child.add(%authorText);
    background = %background @ %child;
    hiliteCtrl = %hilite @ %child;
    desc = %itemDesc @ %child;
    ugcStatusIcon = %ugcStatusIcon @ %child;
    expiringIcon = %expiringIcon @ %child;
    closeBox = %closeBox @ %child;
    authorText = %authorText @ %child;
    sku = 0 @ %child;
    %child.bindClassName("ClosetWhatYoureWearingItem");
};
$gNoSkuList = "400 850 875 900 950 5400 5850 5875 5900 5950 5980";
function ClosetWhatYoureWearingList::addSku(%this, %sku) {
    return (-(1.0) != findWord($gNoSkuList, %sku));
    %drawerAction = "";
    %child = %this.addChild();
    sku = %sku @ %child;
    %si = %sku.findBySku();
    SkuManager;
    %drawerAction = "  (no animation)";
    %sku.isInstrumentSku();
    %drawerAction = "  <a:gamelink stopPropAction>stop animation</a>";
    isDoingPropAction;
    %drawerAction = "  <a:gamelink startPropAction>start animation</a>";
    ClosetGui;
    desc.setText(!((SkuManager SPC %sku.getPropSkus() $= "")) @ InstrumentRegistryClient @ %child @ "<a:gamelink " @ %sku @ ">" @ %si @ descShrt @ "</a>" @ "<br><spush><font:Arial:12><color:00000099>" @ %si.getUserFacingDrawerName() @ %drawerAction @ "<spop>");
    %playerEncoded = urlEncode(stripUnprintables(author));
    %si;
    %profileURL = !((%si SPC author $= "")) @ $Net::ProfileURL @ %playerEncoded;
    authorText.setText(%child @ "<just:right><font:Arial:12><color:00000044><linkcolor:00000066>" @ "by <a:gamelink " @ %profileURL @ ">" @ %si @ author @ "</a>");
    authorText.setText("");
    expiringIcon.setBitmap("platform/client/ui/expiring_icon");
    expiringIcon.setVisible(1);
    expiringIcon.setVisible(0);
    %currentTabName = name;
    getCurrentTab();
    ugcStatusIcon.setBitmap(ClosetGui_MyShop_GetSkuUGCStatusIcon(%sku));
    ugcStatusIcon.setVisible(1);
    ugcStatusIcon.setVisible(0);
    %showRemoveButton = drwrName.isOptionalDrawer();
    %si;
    %showRemoveButton = 1;
    SkuManager;
    closeBox.setActive(%showRemoveButton);
    %this.hiliteCell(0, (1.0 - %this.getCount()));
    %this.reseatChildren();
};
function ClosetWhatYoureWearingList::setSkus(%this, %skus) {
    %propSku = $ClosetOutfitName[$ClosetSkusOutfit @ $ClosetOutfitName].getFirstPropSku();
    SkuManager;
    stopPropAction();
    lastPropSku = (%this != lastPropSku) @ %propSku @ %this;
    %propSku;
    $player.setGenre("p");
    %instrument = %propSku.getInstrumentBySku();
    InstrumentRegistryClient;
    $player.setGenre("p");
    $player.setGenre(genre);
    %this.setNumChildren(0);
    "(wearing none)".setTextWithStyle();
    0.setVisible();
    "".setTextWithStyle();
    1.setVisible();
    %skus = %skus.sortSkusByDrawer();
    SkuManager;
    %count = getWordCount(%skus);
    MyShopCopyToOutfitText;
    %i = 0;
    isObject();
    %this.addSku(getWord(%skus, %i));
    %i = (1.0 + %i);
    (%count < %i);
    skus = (%count < %i) @ %skus @ %this;
    MyShopCopyToOutfitText;
};
function ClosetWhatYoureWearingList::refresh(%this, %skus) {
    %skus.setSkus();
};
function ClosetWhatYoureWearingButton::onURL(%this, %url) {
    %url = getWords(%url, 1);
    (getWord(%url, 0) $= "gamelink");
    "".zoomToSKU();
    doPropAction();
    $ClosetOutfitName[$ClosetSkusOutfit @ $ClosetOutfitName].refresh();
    stopPropAction();
    $ClosetOutfitName[$ClosetSkusOutfit @ $ClosetOutfitName].refresh();
    scroll.scrollToSku(%url);
    ClosetGui_MyShop_ToggleCurrentSku(%url);
};
function ClosetGUI_ToggleSku_Closet(%sku) {
    %drawer = drwrName;
    %sku.findBySku();
    %removable = %drawer.isOptionalDrawer();
    SkuManager;
    %wordLoc = findWord($ClosetSkusBody, %sku);
    %sku.isBodySku();
    $ClosetSkusBody = removeWord($ClosetSkusBody, %wordLoc);
    %removable;
    $ClosetSkusBody = $ClosetSkusBody.overlaySkus(%sku);
    SkuManager;
    %wordLoc = findWord($ClosetOutfitName[$ClosetSkusOutfit @ $ClosetOutfitName], %sku);
    %sku.isOutfitSku();
    $ClosetOutfitName[$ClosetSkusOutfit @ $ClosetOutfitName] = (0.0 >= %wordLoc) @ %removable @ removeWord($ClosetOutfitName[$ClosetSkusOutfit @ $ClosetOutfitName], %wordLoc);
    SkuManager;
    $ClosetOutfitName[$ClosetSkusOutfit @ $ClosetOutfitName] = (0.0 >= %wordLoc) @ SkuManager @ $ClosetOutfitName[$ClosetSkusOutfit @ $ClosetOutfitName].overlaySkus(%sku);
    SkuManager;
    %outfitNum = findWord(SkuManager, $ClosetOutfitName);
    %objectView = %outfitNum.getOutfitObjectView();
    ClosetTabs;
    %objectView.setSkus($ClosetSkusBody @ " " @ $ClosetOutfitName[$ClosetSkusOutfit @ $ClosetOutfitName]);
};
