$gMyShopAboutLinks = "";
function ClosetTabs::fillMyShopTab(%this) {
    %theTab = %this.getTabWithName("MY DESIGNS");
    return !(isObject(%theTab));
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "26 26";
    extent = "571 37";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/closet_tabs_bracket";
    %theTab.add();
    profile = GuiTextCtrl @ new ""() @ "ClosetTitleProfile";
    0;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "26 64";
    extent = "28 20";
    text = "My Designs:";
    %theTab.add();
    %xPos = 34;
    %xGap = 6;
    %ypos = 84;
    %xSiz = 66;
    %viewType = "Accepted";
    profile = 0 @ new GuiVariableWidthButtonCtrl @ "geClosetMyShopViewButton_" @ %viewType() @ "BracketButton17NonDefaultProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = %xPos @ " " @ %ypos;
    extent = %xSiz @ " " @ 17;
    command = "ClosetGui_MyShop_SetView(\"" @ %viewType @ "\");";
    text = %viewType;
    buttonType = "PushButton";
    canHilite = 0;
    %theTab.add();
    %xPos = ((%xGap + %xSiz) + %xPos);
    %xSiz = 64;
    0;
    %viewType = "Pending";
    profile = 0 @ new GuiVariableWidthButtonCtrl @ "geClosetMyShopViewButton_" @ %viewType() @ "BracketButton17NonDefaultProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = %xPos @ " " @ 84;
    extent = %xSiz @ " " @ 17;
    command = "ClosetGui_MyShop_SetView(\"" @ %viewType @ "\");";
    text = %viewType;
    buttonType = "PushButton";
    canHilite = 0;
    %theTab.add();
    %xPos = ((%xGap + %xSiz) + %xPos);
    %xSiz = 76;
    %viewType = "Rejected";
    profile = 0 @ new GuiVariableWidthButtonCtrl @ "geClosetMyShopViewButton_" @ %viewType() @ "BracketButton17NonDefaultProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = %xPos @ " " @ 84;
    extent = %xSiz @ " " @ 17;
    command = "ClosetGui_MyShop_SetView(\"" @ %viewType @ "\");";
    text = %viewType;
    buttonType = "PushButton";
    canHilite = 0;
    %theTab.add();
    %xPos = ((%xGap + %xSiz) + %xPos);
    %xSiz = 74;
    %viewType = "Templates";
    profile = 0 @ new GuiVariableWidthButtonCtrl @ "geClosetMyShopViewButton_" @ %viewType() @ "BracketButton17NonDefaultProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = %xPos @ " " @ %ypos;
    extent = %xSiz @ " " @ 17;
    command = "ClosetGui_MyShop_SetView(\"" @ %viewType @ "\");";
    text = %viewType;
    buttonType = "PushButton";
    canHilite = 0;
    %theTab.add();
    error("TODO - need to check for FashionPolice permission");
    %viewType = "Incoming";
    0;
    profile = 0 @ new GuiVariableWidthButtonCtrl @ "geClosetMyShopViewButton_" @ %viewType() @ "BracketButton17NonDefaultProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = %xPos @ " " @ 66;
    extent = %xSiz @ " " @ 17;
    command = "ClosetGui_MyShop_SetView(\"" @ %viewType @ "\");";
    text = %viewType;
    buttonType = "PushButton";
    canHilite = 0;
    %theTab.add();
    %xPos = ((%xGap + %xSiz) + %xPos);
    profile = MyShopItemsFrame @ new () @ "GuiDefaultProfile";
    GuiControl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "22 120";
    extent = "467 368";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    %itemsFrame = ;
    profile = GuiMLTextCtrl @ new ""() @ "ClosetLeftInfoProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "5 0";
    extent = "457 16";
    minExtent = "1 1";
    sluggishness = -1;
    visible = fase;
    text = "no matching items";
    maxLength = 255;
    %itemsInfoText = ;
    %itemsFrame.add(%itemsInfoText);
    profile = GuiTextCtrl @ new ""() @ "ClosetRightInfoProfile";
    0;
    horizSizing = "left";
    vertSizing = "bottom";
    position = "313 1";
    extent = "125 14";
    minExtent = "125 1";
    sluggishness = -1;
    visible = 1;
    text = "";
    maxLength = 255;
    %ctrl = ;
    %itemsFrame.add(%ctrl);
    rangeText = %ctrl @ %theTab;
    profile = GuiMLTextCtrl @ new ""() @ "ClosetRightInfoProfile";
    0;
    horizSizing = "left";
    vertSizing = "bottom";
    position = "338 354";
    extent = "125 14";
    modal = 0;
    %ctrl = ;
    %itemsFrame.add(%ctrl);
    otherGenderText = %ctrl @ %theTab;
    profile = GuiScrollCtrl @ new ""() @ "ETSScrollProfile";
    0;
    position = "0 20";
    extent = "465 326";
    minExtent = "1 1";
    horizSizing = "right";
    vertSizing = "bottom";
    visible = 1;
    hScrollBar = "dynamic";
    vScrollBar = "dynamic";
    constantThumbHeight = 1;
    scrollMultiplier = 16.1;
    %ctrl = ;
    %ctrl.bindClassName("ClosetItemsScroll");
    itemsScroll = %ctrl @ %theTab;
    %itemsFrame.add(%ctrl);
    class = ClosetThumbnailsMyShop @ new () @ "ClosetThumbnails";
    GuiArray2Ctrl;
    profile = 0 @ "FocusableDefaultProfile";
    childrenClassName = "GuiMouseEventCtrl";
    childrenExtent = "109 159";
    spacing = 2;
    numRowsOrCols = 4;
    inRows = 0;
    canHilite = 0;
    infoText = %itemsInfoText;
    tab = %theTab;
    scroll = %theTab @ itemsScroll;
    otherGenderText = %theTab @ otherGenderText;
    %thumbnails = ;
    itemsScroll.add(%thumbnails);
    thumbnails = %theTab @ itemsScroll;
    %theTab @ %thumbnails;
    %theTab.add(%itemsFrame);
    thumbnails = %thumbnails @ %theTab;
    thumbnails = %thumbnails @ %itemsFrame;
    profile = new ""() @ ETSNonModalProfile;
    GuiControl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "689 309";
    extent = "245 179";
    profile = MyShopWhatYourWearingContainer @ new () @ "DottedWindowProfile";
    GuiWindowCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "245 179";
    resizeWidth = 0;
    resizeHeight = 0;
    canMove = 0;
    canClose = 0;
    canMinimize = 0;
    canMaximize = 0;
    canHilite = 0;
    horizSizing = MyShopCopyToOutfitText @ new () @ "left";
    GuiMLTextCtrl;
    vertSizing = "bottom";
    position = "0 2";
    extent = "233 18";
    style = "plainOnWhiteSmall";
    stripGamelink = 1;
    %itemDescFrame = ;
    %theTab.add(%itemDescFrame);
    "<just:right><a:gamelink:COPY_TO_OUTFIT>copy to outfit</a>".setTextWithStyle();
    profile = MyShopItemDeetsPanel @ new () @ "DottedWindowProfile";
    GuiWindowCtrl;
    horizSizing = MyShopCopyToOutfitText @ 0 @ "right";
    vertSizing = "bottom";
    position = "689 84";
    extent = "245 223";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    resizeWidth = 0;
    resizeHeight = 0;
    canMove = 0;
    canClose = 0;
    canMinimize = 0;
    canMaximize = 0;
    canHilite = 0;
    submitPriceValid = 0;
    submitTexturesValid = 1;
    submitDescriptionValid = 1;
    %theTab.add();
    profile = MyShopItemDeets_DescShort @ new () @ "Profile_MyShop_TextField_Bold";
    GuiTextEditCtrl;
    horizSizing = MyShopItemDeetsPanel @ 0 @ "right";
    vertSizing = "bottom";
    position = "8 3";
    extent = "222 18";
    text = "Item Details";
    readOnly = 1;
    command = "$ThisControl.onKeyStroke();";
    .add();
    horizSizing = GuiMLTextCtrl @ new ""() @ "right";
    0;
    vertSizing = "bottom";
    position = "232 5";
    extent = "10 18";
    style = "plainOnWhiteBlueLinks";
    visible = 0;
    stripGamelink = 1;
    %ctrl = ;
    %ctrl.bindClassName("MyShopGenericMLText");
    %ctrl.setTextWithStyle("<a:gamelink:MYDESIGNS_ABOUT DESCSHORT>-?</a>");
    $gMyShopAboutLinks = $gMyShopAboutLinks @ " " @ %ctrl;
    %ctrl.add();
    profile = MyShopItemDeets_DescLong @ new () @ "Profile_MyShop_TextField";
    GuiTextEditCtrl;
    horizSizing = MyShopItemDeetsPanel @ 0 @ "right";
    MyShopItemDeetsPanel;
    vertSizing = "bottom";
    position = "8 23";
    extent = "222 18";
    text = "Item Details Long";
    readOnly = 1;
    command = "$ThisControl.onKeyStroke();";
    .add();
    horizSizing = GuiMLTextCtrl @ new ""() @ "right";
    0;
    vertSizing = "bottom";
    position = "232 25";
    extent = "10 18";
    style = "plainOnWhiteBlueLinks";
    visible = 0;
    stripGamelink = 1;
    %ctrl = ;
    %ctrl.bindClassName("MyShopGenericMLText");
    %ctrl.setTextWithStyle("<a:gamelink:MYDESIGNS_ABOUT DESCLONG>-?</a>");
    $gMyShopAboutLinks = $gMyShopAboutLinks @ " " @ %ctrl;
    %ctrl.add();
    %letterWords = "A B C D";
    MyShopItemDeetsPanel;
    %posX = 0;
    %posY = 0;
    %extX = 84;
    %extY = 84;
    %dx = (13.0 + %extX);
    %dy = (4.0 + %extY);
    %n = 0;
    profile = MyShopItemDeets_TexturesScroll @ new () @ "DottedScrollProfile";
    GuiScrollCtrl;
    horizSizing = MyShopItemDeetsPanel @ 0 @ "right";
    vertSizing = "bottom";
    position = "8 43";
    extent = 210 @ " " @ (18.0 + %extY);
    hScrollBar = "dynamic";
    vScrollBar = "alwaysOff";
    profile = MyShopItemDeets_TexturesContainer @ new () @ "ETSNonModalProfile";
    GuiControl;
    position = "0 0";
    extent = %extX @ " " @ %extY;
    .add();
    profile = GuiBitmapCtrl @ new ""() @ "ClosetDkBackgroundProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = %posX @ " " @ %posY;
    extent = %extX @ " " @ %extY;
    systemDragDrop = 1;
    canHilite = 1;
    visible = 0;
    modal = GuiMLTextCtrl @ new ""() @ 0;
    position = "3 3";
    extent = "20 20";
    text = "<b><outline><shadowcolor:ffffffd0><color:000000d0>" @ getWord(%letterWords, %n);
    profile = GuiBitmapButtonCtrl @ new ""() @ "GuiDefaultProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = %extX @ " " @ %extY;
    visible = 1;
    command = "MyShop_InspectTexture(" @ %n @ ");";
    canHilite = 0;
    bitmap = "platform/client/buttons/tgf/tgf_buttonframe_100x100";
    lazyLoad = 1;
    %ctrl = ;
    %ctrl.bindClassName("geTextureDropTarget");
    %ctrl.add();
    geTextureTarget = MyShopItemDeets_TexturesContainer @ %ctrl @ %n @ MyShopItemDeetsPanel;
    %posX = (%dx + %posX);
    %n = (1.0 + %n);
    profile = GuiBitmapCtrl @ new ""() @ "ClosetDkBackgroundProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = %posX @ " " @ %posY;
    extent = %extX @ " " @ %extY;
    systemDragDrop = 1;
    canHilite = 1;
    visible = 0;
    modal = GuiMLTextCtrl @ new ""() @ 0;
    position = "3 3";
    extent = "20 20";
    text = "<b><outline><shadowcolor:ffffffd0><color:000000d0>" @ getWord(%letterWords, %n);
    profile = GuiBitmapButtonCtrl @ new ""() @ "GuiDefaultProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = %extX @ " " @ %extY;
    visible = 1;
    command = "MyShop_InspectTexture(" @ %n @ ");";
    canHilite = 0;
    bitmap = "platform/client/buttons/tgf/tgf_buttonframe_100x100";
    lazyLoad = 1;
    %ctrl = ;
    %ctrl.bindClassName("geTextureDropTarget");
    %ctrl.add();
    geTextureTarget = MyShopItemDeets_TexturesContainer @ %ctrl @ %n @ MyShopItemDeetsPanel;
    %posX = (%dx + %posX);
    %n = (1.0 + %n);
    profile = GuiBitmapCtrl @ new ""() @ "ClosetDkBackgroundProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = %posX @ " " @ %posY;
    extent = %extX @ " " @ %extY;
    systemDragDrop = 1;
    canHilite = 1;
    visible = 0;
    modal = GuiMLTextCtrl @ new ""() @ 0;
    position = "3 3";
    extent = "20 20";
    text = "<b><outline><shadowcolor:ffffffd0><color:000000d0>" @ getWord(%letterWords, %n);
    profile = GuiBitmapButtonCtrl @ new ""() @ "GuiDefaultProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = %extX @ " " @ %extY;
    visible = 1;
    command = "MyShop_InspectTexture(" @ %n @ ");";
    canHilite = 0;
    bitmap = "platform/client/buttons/tgf/tgf_buttonframe_100x100";
    lazyLoad = 1;
    %ctrl = ;
    %ctrl.bindClassName("geTextureDropTarget");
    %ctrl.add();
    geTextureTarget = MyShopItemDeets_TexturesContainer @ %ctrl @ %n @ MyShopItemDeetsPanel;
    %posX = (%dx + %posX);
    %n = (1.0 + %n);
    profile = GuiBitmapCtrl @ new ""() @ "ClosetDkBackgroundProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = %posX @ " " @ %posY;
    extent = %extX @ " " @ %extY;
    systemDragDrop = 1;
    canHilite = 1;
    visible = 0;
    modal = GuiMLTextCtrl @ new ""() @ 0;
    position = "3 3";
    extent = "20 20";
    text = "<b><outline><shadowcolor:ffffffd0><color:000000d0>" @ getWord(%letterWords, %n);
    profile = GuiBitmapButtonCtrl @ new ""() @ "GuiDefaultProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = %extX @ " " @ %extY;
    visible = 1;
    command = "MyShop_InspectTexture(" @ %n @ ");";
    canHilite = 0;
    bitmap = "platform/client/buttons/tgf/tgf_buttonframe_100x100";
    lazyLoad = 1;
    %ctrl = ;
    %ctrl.bindClassName("geTextureDropTarget");
    %ctrl.add();
    geTextureTarget = MyShopItemDeets_TexturesContainer @ %ctrl @ %n @ MyShopItemDeetsPanel;
    %posX = (%dx + %posX);
    %n = (1.0 + %n);
    horizSizing = GuiMLTextCtrl @ new ""() @ "right";
    0;
    vertSizing = "bottom";
    position = "87 71";
    extent = "10 16";
    stripGamelink = 1;
    style = "plainOnWhiteBlueLinks";
    visible = 0;
    %ctrl = ;
    %ctrl.bindClassName("MyShopGenericMLText");
    %ctrl.setTextWithStyle("<a:gamelink:MYDESIGNS_ABOUT TEXTURES>-?</a>");
    $gMyShopAboutLinks = $gMyShopAboutLinks @ " " @ %ctrl;
    %ctrl.add();
    profile = MyShopRefreshTexturesCtrl @ new () @ "BracketButton19Profile";
    GuiVariableWidthButtonCtrl;
    horizSizing = MyShopItemDeets_TexturesScroll @ 0 @ "right";
    vertSizing = "bottom";
    position = "90 200";
    extent = "119 19";
    command = "ClosetGUI_RefreshTextures();";
    text = "Reload Textures";
    buttonType = "PushButton";
    visible = 0;
    tooltip = "(Ctrl-R)";
    %ctrl = ;
    %ctrl.add();
    profile = new () @ ETSNonModalProfile;
    MyShopItemSettings;
    position = 0 @ GuiControl @ "8 142";
    MyShopItemDeetsPanel;
    extent = "232 80";
    horizSizing = "right";
    vertSizing = "bottom";
    visible = 0;
    %ctrl = ;
    %ctrl.add();
    profile = GuiMLTextCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = MyShopItemDeetsPanel @ "right";
    vertSizing = "bottom";
    position = "0 2";
    extent = "45 18";
    style = "plainOnWhite";
    stripGamelink = 1;
    %ctrl = ;
    %ctrl.setTextWithStyle("vBux:");
    %ctrl.add();
    profile = MyShopVBuxField @ new () @ "Profile_MyShop_SettingsField";
    GuiTextEditCtrl;
    horizSizing = MyShopItemSettings @ 0 @ "right";
    vertSizing = "bottom";
    position = "42 0";
    extent = "50 18";
    text = "";
    command = "$ThisControl.onKeyStroke();";
    validInputChars = 0123456789;
    tooltip = "How much this will cost";
    %ctrl = ;
    %ctrl.add();
    horizSizing = GuiMLTextCtrl @ new ""() @ "right";
    0;
    vertSizing = MyShopItemSettings @ "bottom";
    position = "94 2";
    extent = "45 18";
    style = "plainOnWhiteBlueLinks";
    visible = 0;
    stripGamelink = 1;
    %ctrl = ;
    %ctrl.bindClassName("MyShopGenericMLText");
    %ctrl.setTextWithStyle("<a:gamelink:MYDESIGNS_ABOUT VBUX>-?</a>");
    $gMyShopAboutLinks = $gMyShopAboutLinks @ " " @ %ctrl;
    %ctrl.add();
    profile = GuiMLTextCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = MyShopItemSettings @ "right";
    vertSizing = "bottom";
    position = "0 22";
    extent = "45 18";
    style = "plainOnWhite";
    %ctrl = ;
    %ctrl.setTextWithStyle("vPoints:");
    %ctrl.add();
    profile = MyShopVPointsField @ new () @ "Profile_MyShop_SettingsField";
    GuiTextEditCtrl;
    modal = MyShopItemSettings @ 0 @ 0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "42 20";
    extent = "50 18";
    text = "";
    readOnly = 1;
    command = "$ThisControl.onKeyStroke();";
    validInputChars = 0123456789;
    tooltip = "How much this will cost";
    %ctrl = ;
    %ctrl.add();
    %ctrl.setActive(0);
    horizSizing = GuiMLTextCtrl @ new ""() @ "right";
    0;
    vertSizing = MyShopItemSettings @ "bottom";
    position = "94 22";
    extent = "45 18";
    style = "plainOnWhiteBlueLinks";
    visible = 0;
    stripGamelink = 1;
    %ctrl = ;
    %ctrl.bindClassName("MyShopGenericMLText");
    %ctrl.setTextWithStyle("<a:gamelink:MYDESIGNS_ABOUT VPOINTS>-?</a>");
    $gMyShopAboutLinks = $gMyShopAboutLinks @ " " @ %ctrl;
    %ctrl.add();
    profile = MyShopPriceForSaleOption @ new () @ "ETSCheckBoxProfile2";
    GuiCheckBoxCtrl;
    horizSizing = MyShopItemSettings @ 0 @ "right";
    vertSizing = "bottom";
    position = "150 -3";
    extent = "50 18";
    text = "for sale";
    buttonType = "ToggleButton";
    tooltip = "Make this item for sale in your store";
    %ctrl = ;
    %ctrl.setValue(1);
    %ctrl.add();
    horizSizing = GuiMLTextCtrl @ new ""() @ "right";
    0;
    vertSizing = MyShopItemSettings @ "bottom";
    position = "209 0";
    extent = "10 18";
    style = "plainOnWhiteBlueLinks";
    visible = 0;
    stripGamelink = 1;
    %ctrl = ;
    %ctrl.bindClassName("MyShopGenericMLText");
    %ctrl.setTextWithStyle("<a:gamelink:MYDESIGNS_ABOUT FOR_SALE>-?</a>");
    $gMyShopAboutLinks = $gMyShopAboutLinks @ " " @ %ctrl;
    %ctrl.add();
    profile = MyShopPriceFeaturedOption @ new () @ "ETSCheckBoxProfile2";
    GuiCheckBoxCtrl;
    horizSizing = MyShopItemSettings @ 0 @ "right";
    vertSizing = "bottom";
    position = "150 12";
    extent = "85 18";
    text = "featured";
    buttonType = "ToggleButton";
    tooltip = "Make this your one item in the VHD store";
    %ctrl = ;
    %ctrl.add();
    horizSizing = GuiMLTextCtrl @ new ""() @ "right";
    0;
    vertSizing = MyShopItemSettings @ "bottom";
    position = "209 15";
    extent = "10 18";
    style = "plainOnWhiteBlueLinks";
    visible = 0;
    stripGamelink = 1;
    %ctrl = ;
    %ctrl.bindClassName("MyShopGenericMLText");
    %ctrl.setTextWithStyle("<a:gamelink:MYDESIGNS_ABOUT FEATURED>-?</a>");
    $gMyShopAboutLinks = $gMyShopAboutLinks @ " " @ %ctrl;
    %ctrl.add();
    profile = MyShopPriceOutOfRangeText @ new () @ "ETSNonModalProfile";
    GuiMLTextCtrl;
    horizSizing = MyShopItemSettings @ 0 @ "right";
    vertSizing = "bottom";
    position = "10 44";
    extent = "214 14";
    style = "plainRedSmall";
    stripGamelink = 1;
    %ctrl = ;
    %ctrl.setTextWithStyle("");
    %ctrl.add();
    profile = MyShopSubmitButton @ new () @ "BracketButton17NonDefaultProfile";
    GuiVariableWidthButtonCtrl;
    horizSizing = MyShopItemSettings @ 0 @ "right";
    vertSizing = "bottom";
    position = "10 60";
    extent = "214 17";
    command = "$ThisControl.onClick();";
    canHilite = 1;
    text = "Submit this template as a new item";
    drawText = 1;
    modulationColor = "255 255 255 64";
    command = "$ThisControl.onClick();";
    %ctrl = ;
    %ctrl.add();
    %ctrl.setActive(0);
    profile = MyShopStartNewButton @ new () @ "BracketButton19Profile";
    GuiVariableWidthButtonCtrl;
    horizSizing = MyShopItemSettings @ 0 @ "right";
    vertSizing = "bottom";
    position = "8 200";
    extent = "76 19";
    command = "$ThisControl.onClick();";
    text = "Start New";
    buttonType = "PushButton";
    visible = 0;
    tooltip = "Start designing with a new copy of this template";
    %ctrl = ;
    %ctrl.add();
    profile = MyShopDragFilesImage @ new () @ "ETSNonModalProfile";
    GuiBitmapCtrl;
    horizSizing = MyShopItemDeetsPanel @ 0 @ "left";
    vertSizing = "bottom";
    position = "907 128";
    extent = "43 174";
    bitmap = "platform/client/ui/closet_myshop_dragfiles";
    modulationColor = "255 255 255 80";
    visible = 0;
    %w = 461;
    %h = 423;
    profile = MyShopTextureInspector @ new () @ "DottedWindowProfile";
    GuiWindowCtrl;
    position = 0 @ "25 65";
    extent = %w @ " " @ %h;
    visible = 0;
    canHilite = 0;
    resizeWidth = 0;
    resizeHeight = 0;
    canMove = 0;
    canClose = 0;
    canMinimize = 0;
    canMaximize = 0;
    systemDragDrop = 1;
    canHilite = 1;
    profile = new ""() @ ETSNonModalProfile;
    GuiBitmapCtrl;
    position = "1 1";
    extent = (2.0 - %w) @ " " @ (2.0 - %h);
    wrap = 1;
    bitmap = "platform/client/ui/greyChecks";
    profile = MyShopTextureInspectorBitmap @ new () @ "ETSNonModalProfile";
    GuiBitmapCtrl;
    position = (2.0 / (%h - %w)) @ " " @ 1;
    extent = (2.0 - %h) @ " " @ (2.0 - %h);
    horizSizing = "width";
    vertSizing = "height";
    position = GuiBitmapButtonCtrl @ new ""() @ (2.0 - (16.0 - 461.0)) @ " " @ 2;
    extent = "16 16";
    command = "MyShopTextureInspector.close();";
    bitmap = "platform/client/buttons/gray_close";
    %theTab.add();
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "BracketButton19Profile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "829 519";
    extent = "43 19";
    minExtent = "1 1";
    visible = 1;
    command = "ClosetGui.close(false);";
    text = "Done";
    buttonType = "PushButton";
    drawText = 1;
    %ctrl = ;
    %theTab.add(%ctrl);
    doneButton = %ctrl @ %theTab;
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "BracketButton19NonDefaultProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "882 519";
    extent = "52 19";
    minExtent = "1 1";
    visible = 1;
    command = "ClosetGui.close(true);";
    text = "Cancel";
    buttonType = "PushButton";
    drawText = 1;
    %ctrl = ;
    %theTab.add(%ctrl);
    cancelButton = %ctrl @ %theTab;
    1.setStoreControlsVisible();
    firstLoad = ClosetTabs @ 1 @ %theTab;
    ClosetGui_MyShop_SetView();
    tabMyShopInitialized = ACCEPTED @ 1 @ %this;
};
$gPrevMyShopTypeButton = "";
function ClosetGui_MyShop_SetView(%viewType) {
    $gPrevMyShopTypeButton.setProfile();
    modal = BracketButton17NonDefaultProfile @ 1 @ $gPrevMyShopTypeButton;
    isObject($gPrevMyShopTypeButton);
    %buttonCtrl = "geClosetMyShopViewButton_" @ %viewType;
    %buttonCtrl.setProfile();
    modal = BracketButton17Profile @ 0 @ %buttonCtrl;
    $gPrevMyShopTypeButton = %buttonCtrl;
    getUGCItems(%viewType);
};
function getUGCItems(%type) {
    %type[$gUGCSkus @ %type] = "";
    %list = "template".getSkusTag($player.getGender());
    SkuManager;
    %list = SkuManager @ "template".getSkusTag($player.getOtherGender());
    %list @ " ";
    onGotUGCItems(%type, %list);
    %list = "mesh".getSkusType();
    SkuManager;
    %list = %list.filterSkusAuthor($Player::Name);
    SkuManager;
    onGotUGCItems(%type, %list);
    error(getScopeName() @ " " @ "- not implemented" @ " " @ %type @ " " @ getTrace());
    infoText.setVisible(1);
    infoText.setText("Fetching..");
    %list = %type[$gSampleUGC @ %type];
    ClosetThumbnailsMyShop;
    %n = (1.0 - getWordCount(%list));
    ClosetThumbnailsMyShop;
    %sku = getWord(%list, %n);
    (0.0 >= %n);
    %si = %sku.findBySku();
    SkuManager;
    brand = 0 @ "" @ %si;
    ((%type $= "TEMPLATES") SPC %type $= "ACCEPTED");
    tags = %si @ findAndRemoveAllOccurrencesOfWord(tags, "new") @ %si;
    expireTime = "" @ %si;
    author = ((%type $= "ACCEPTED") SPC %type $= "PENDING") @ $Player::Name @ %si;
    %n = (1.0 - %n);
    schedule(500, 0, "onGotUGCItems", %type, %list);
};
function onGotUGCItems(%type, %list) {
    %type[$gUGCSkus @ %type] = %list;
    "".setUnfilteredSkus();
    infoText.setText("rejected list not implemented yet");
    %list.setUnfilteredSkus();
    %theTab = "MY DESIGNS".getTabWithName();
    ClosetTabs;
    firstLoad = firstLoad @ 0 @ %theTab;
    %theTab;
    ClosetGui_MyShop_SetView("TEMPLATES");
    infoText.setText(%type[ClosetThumbnailsMyShop @ $MsgCat::MyShop TAB "EMPTYLIST" @ %type]);
    ClosetGui_MyShop_SetCurrentSku(%type[$gUGCPrevSku @ %type]);
};
function ClosetGui_MyShop_GetSkuUGCStatus(%sku) {
    %si = %sku.findBySku();
    SkuManager;
    return ugcStatus;
    return "TEMPLATES";
    %statusi = "ACCEPTED PENDING REJECTED TEMPLATES INCOMING";
    %status = "";
    %n = (1.0 - getWordCount(%statusi));
    %s = getWord(%statusi, %n);
    (0.0 >= %n);
    %status = %s;
    hasWord(%s[$gUGCSkus @ %s], %sku);
    %n = (1.0 - %n);
    (%status $= "");
    ugcStatus = (0.0 >= %n) @ %status @ %si;
    (%status $= "");
    error(getScopeName() @ " " @ "- no UGC status for sku" @ " " @ %sku @ " " @ getTrace());
    return %status;
};
function ClosetGui_MyShop_GetSkuUGCStatusIcon(%sku) {
    %status = ClosetGui_MyShop_GetSkuUGCStatus(%sku);
    %ret = "";
    (%status $= "");
    %ret = "platform/client/ui/ugcStatus_" @ %status;
    return %ret;
};
function MyShopItemsFrame::update(%this) {
    return !((getCurrentTab() SPC name $= "MY DESIGNS"));
    thumbnails.refilter();
    ClosetGui_MyShop_SetCurrentSku($gMyShopCurrentSku);
};
$gSkusMyShopLayer = "";
$gMyShopCurrentSku = "";
function ClosetGUI_ToggleSku_MyShop(%sku) {
    $gSkusMyShopLayer = findAndRemoveAllOccurrencesOfWord($gSkusMyShopLayer, %sku);
    hasWord($gSkusMyShopLayer, %sku);
    ClosetGui_MyShop_SetCurrentSku("");
    $gSkusMyShopLayer = $gSkusMyShopLayer.overlaySkus(%sku);
    SkuManager;
    ClosetGui_MyShop_SetCurrentSku(%sku);
};
function ClosetGui_MyShop_SetCurrentSku(%sku) {
    %itemStatus = "";
    (%sku $= "");
    %itemStatus = ClosetGui_MyShop_GetSkuUGCStatus(%sku);
    %itemStatus[$gUGCPrevSku @ %itemStatus] = %sku;
    %readOnlyDesc = 1;
    (%itemStatus $= "ACCEPTED");
    %readOnlySettings = 0;
    %showSettings = 1;
    %showSubmit = 1;
    %showAboutLinks = 1;
    %showStartNew = 1;
    "Update Item".setText();
    error(getScopeName() @ " " @ "- not implemented yet:" @ " " @ %itemStatus @ " " @ getTrace());
    %readOnlyDesc = 1;
    (MyShopSubmitButton SPC %itemStatus $= "PENDING");
    %readOnlySettings = 1;
    %showSettings = 1;
    %showSubmit = 0;
    %showAboutLinks = 1;
    %showStartNew = 1;
    error(getScopeName() @ " " @ "- not implemented yet:" @ " " @ %itemStatus @ " " @ getTrace());
    %readOnlyDesc = 1;
    (%itemStatus $= "REJECTED");
    %readOnlySettings = 1;
    %showSettings = 1;
    %showSubmit = 0;
    %showAboutLinks = 0;
    %showStartNew = 0;
    %readOnlyDesc = 0;
    (%itemStatus $= "TEMPLATES");
    %readOnlySettings = 0;
    %showSettings = 1;
    %showSubmit = 1;
    %showAboutLinks = 1;
    %showStartNew = 1;
    "Submit this template as a new item".setText();
    error(getScopeName() @ " " @ "- not implemented yet:" @ " " @ %itemStatus @ " " @ getTrace());
    %readOnlyDesc = 1;
    (MyShopSubmitButton SPC %itemStatus $= "INCOMING");
    %readOnlySettings = 1;
    %showSettings = 1;
    %showSubmit = 1;
    %showAboutLinks = 0;
    %showStartNew = 0;
    "Approve or Reject this item".setText();
    %readOnlyDesc = 1;
    MyShopSubmitButton;
    %readOnlySettings = 1;
    %showSettings = 0;
    %showSubmit = 0;
    %showAboutLinks = 0;
    %showStartNew = 0;
    %readOnlyDesc = 1;
    %readOnlySettings = 1;
    %showSettings = 0;
    %showSubmit = 0;
    %showAboutLinks = 0;
    border = 0 @ 1 @ Profile_MyShop_TextField;
    %readOnlyDesc;
    border = 0 @ 1 @ Profile_MyShop_TextField_Bold;
    %readOnlyDesc;
    border = 0 @ 1 @ Profile_MyShop_SettingsField;
    %readOnlySettings;
    readOnly = %readOnlyDesc @ MyShopItemDeets_DescShort;
    !(%readOnlyDesc).setActive();
    readOnly = MyShopItemDeets_DescShort @ %readOnlyDesc @ MyShopItemDeets_DescLong;
    !(%readOnlyDesc).setActive();
    readOnly = MyShopItemDeets_DescLong @ %readOnlySettings @ MyShopVBuxField;
    !(%readOnlySettings).setActive();
    !(%readOnlySettings).setActive();
    %showSubmit.setVisible();
    !(%readOnlySettings).setActive();
    !(%readOnlySettings).setActive();
    %showSettings.setVisible();
    %showStartNew.setVisible();
    $gMyShopAboutLinks = trim($gMyShopAboutLinks);
    MyShopStartNewButton;
    %n = (1.0 - getWordCount($gMyShopAboutLinks));
    MyShopItemSettings;
    %ctrl = getWord($gMyShopAboutLinks, %n);
    (0.0 >= %n);
    %ctrl.setVisible(%showAboutLinks);
    %n = (1.0 - %n);
    MyShopPriceFeaturedOption;
    %sku.setSkuBaseTextures();
    "".setText();
    "".setText();
    "no current item".setText();
    "".setText();
    $gMyShopCurrentSku = %sku;
    MyShopItemDeets_DescLong;
    "".zoomToSKU();
    return ClosetMainObjectView;
    %si = %sku.findBySku();
    SkuManager;
    "hmm, something went wrong. please check the bug forum.".setText();
    $gMyShopCurrentSku = "";
    MyShopItemDeets_DescLong;
    return !(isObject(%si));
    descShrt.setText();
    descLong.setText();
    $gMyShopCurrentSku = %sku;
    %si;
    %sku.zoomToSKU();
    price.setValue();
    onKeystroke();
};
function MyShopItemDeetsPanel::setSkuBaseTextures(%this, %sku) {
    geTextureTarget.setVisible(0);
    geTextureTarget.setVisible(0);
    geTextureTarget.setVisible(0);
    geTextureTarget.setVisible(0);
    %isValid = 1;
    0 @ %this @ 1 @ %this @ 2 @ %this @ 3 @ %this;
    %si = %sku.findBySku();
    SkuManager;
    %isValid = 0;
    !(isObject(%si));
    %baseTextures = %si.getTxtrNames();
    %isValid;
    %num = getWordCount(%baseTextures);
    numTextures = %num @ %this;
    %n = 0;
    %baseTexture = getWord(%baseTextures, %n);
    (%num < %n);
    %path = (ClosetGui_MyShop_GetSkuUGCStatus(%sku) $= "TEMPLATES") @ "user/textures/" @ %baseTexture;
    %path = "projects/common/characters/" @ $player.getGender() @ "_player/" @ %baseTexture;
    geTextureTarget.setBitmap(%path);
    geTextureTarget.setBitmap("projects/vside/worlds/common/swatches/Gray50");
    geTextureTarget.setVisible(1);
    baseTexture = isFile(isFile(%path @ ".jpg") @ %path @ ".png") @ %n @ %this @ %n @ %this @ %n @ %this @ %baseTexture @ %n @ %this @ geTextureTarget;
    sku = %sku @ %n @ %this @ geTextureTarget;
    %n = (1.0 + %n);
    %num = 0;
    (%num < %n);
    %stepX = (getWord(geTextureTarget.getPosition(), 0) @ 1 @ %this - getWord(geTextureTarget.getPosition(), 0));
    0 @ %this;
    %padding = (getWord(geTextureTarget.getExtent(), 0) - %stepX);
    0 @ %this;
    (%padding - (%num * %stepX)).resize(getWord(geTextureTarget.getExtent(), 1));
    %prevParent = getGroup();
    MyShopDragFilesImage;
    0.setVisible();
    "-1000 -1000".reparent("", "");
    0.setVisible();
    0.setVisible();
    %si.hasTag("TEMPLATE").setVisible();
    "151 223".reparent("", "");
    modulationColor = ClosetMainObjectViewContainer @ "200 50 180 180" @ MyShopDragFilesImage;
    MyShopDragFilesImage;
    !((%si $= originalTxtrNames)).setVisible();
    1.setVisible();
    %si.hasTag("TEMPLATE").setVisible();
    "MY DESIGNS".getTabWithName().reparent("907 128", "", "");
    modulationColor = ClosetTabs @ "0 0 0 80" @ MyShopDragFilesImage;
    MyShopDragFilesImage;
    !((%si $= originalTxtrNames)).setVisible();
    1.setVisible();
    %currParent = getGroup();
    MyShopDragFilesImage;
    5.FlashVisibility(150);
};
function ClosetGui_MyShop_ToggleCurrentSku(%sku) {
    %sku = "";
    (%sku == $gMyShopCurrentSku);
    ClosetGui_MyShop_SetCurrentSku(%sku);
};
function MyShopItemDeets_Desc::onURL(%this, %url) {
    ClosetGui_MyShop_onURL(%url, %this);
};
function MyShopCopyToOutfitText::onURL(%this, %url) {
    ClosetGui_MyShop_onURL(%url, %this);
};
function MyShopGenericMLText::onURL(%this, %url) {
    ClosetGui_MyShop_onURL(%url, %this);
};
function ClosetGui_MyShop_onURL(%url, %mlTextCtrl) {
    ClosetGui_MyShop_SetCurrentSku("");
    %sku = getWord(%url, 1);
    ((getWord(%url, 0) $= "SELECTNONE") SPC getWord(%url, 0) $= "TOGGLESKU");
    ClosetGUI_ToggleSku_MyShop(%sku);
    %sku = getWord(%url, 1);
    (getWord(%url, 0) $= "SELECTSKU");
    ClosetGui_MyShop_SetCurrentSku(%sku);
    userTips::showNow("closet_myshop_copyToOutfit");
    ClosetGUI_RefreshTextures();
    ClosetGui_About("MY DESIGNS", getWord(%url, 1));
    error(getScopeName() @ " " @ "- unknown command" @ " " @ %url @ " " @ getDebugString(%mlTextCtrl) @ " " @ getTrace());
};
function MyShopTextureInspector::onSystemDragDroppedEvent(%this, %text, %pt) {
    ClosetMainObjectView::onSystemDragDroppedEvent_MyShop(%this, %text, %pt);
};
function ClosetMainObjectView::acceptsSystemDragDropContent(%this, %text) {
    return geTextureDropTarget::acceptsSystemDragDropContent(%this, %text);
};
function ClosetMainObjectView::onSystemDragDroppedEvent_MyShop(%this, %text, %pt) {
    hiliteControl("");
    geTextureTarget.applyTexture(%text);
    MessageBoxOK("Use the texture list", (MyShopItemDeetsPanel == numTextures) @ 0 @ MyShopItemDeetsPanel);
};
function geTextureDropTarget::acceptsSystemDragDropContent(%this, %text) {
    return 0;
    return 0;
    %extension = getExtension(%text);
    echo(getScopeName() @ " " @ "- invalid extension:" @ " " @ %text);
    return 0;
    return 1;
};
function geTextureDropTarget::onSystemDragDropEvent(%this, %text, %eventType, %pt) {
    return 0;
    %this.applyTexture(%text, sku);
    return 1;
};
function geTextureDropTarget::applyTexture(%this, %texturePath) {
    %newTextureName = baseTexture;
    %this;
    %extension = getExtension(%texturePath);
    %newFullPathNoExt = "user/textures/" @ %newTextureName;
    %newFullPath = %newFullPathNoExt @ %extension;
    incomingPath = %texturePath @ %this;
    %newFullPath = ($Platform $= "macos") @ getPrefsDir() @ "/" @ %newFullPath;
    %ok = fileCopy(%texturePath, %newFullPath);
    1.setVisible();
    %otherExtension = ".png";
    ".jpg";
    %otherFullPath = %ok @ (MyShopRefreshTexturesCtrl SPC %extension $= ".png") @ "user/textures/" @ %newTextureName @ %otherExtension;
    deleteFile(%otherFullPath);
    removeFile(%newFullPath);
    addFile(%newFullPath);
    %this.setBitmap("");
    %this.setBitmap(%newFullPathNoExt);
    "".setBitmap();
    %newFullPathNoExt.setBitmap();
    reloadMeshTexture(textureName, %newFullPathNoExt);
    sku.findBySku().replaceTextureName(%newTextureName);
    error(getScopeName() @ " " @ "- could not copy" @ " " @ %texturePath @ " " @ "to" @ " " @ %newFullPath @ " " @ getTrace());
};
function ClosetGUI_RefreshTextures() {
    %n = 0;
    %obj = geTextureTarget;
    (4.0 < %n) @ %n @ MyShopItemDeetsPanel;
    %obj.applyTexture(incomingPath);
    %n = (1.0 + %n);
    %obj;
};
function ClosetGui_MyShop_CopySkusToOutfit() {
    $ClosetOutfitName[$ClosetSkusOutfit @ $ClosetOutfitName] = SkuManager @ $ClosetOutfitName[$ClosetSkusOutfit @ $ClosetOutfitName].overlaySkus($gSkusMyShopLayer);
};
function MyShopItemDeets_DescShort::onKeystroke(%this) {
    %si = $gMyShopCurrentSku.findBySku();
    SkuManager;
    return !(isObject(%si));
    descShrt = %this.getValue() @ %si;
};
function MyShopItemDeets_DescLong::onKeystroke(%this) {
    %si = $gMyShopCurrentSku.findBySku();
    SkuManager;
    return !(isObject(%si));
    descLong = %this.getValue() @ %si;
};
function MyShopVBuxField::onKeystroke(%this) {
    %si = $gMyShopCurrentSku.findBySku();
    SkuManager;
    return !(isObject(%si));
    %priceVBux = %this.getValue();
    %minPrice = price;
    %si;
    %maxPrice = (1.0 - 1000000.0);
    MyShopPriceOutOfRangeText @ "<just:center>" @ %minPrice @ " " @ "vBux minimum for this item".setTextWithStyle();
    submitPriceValid = (%minPrice < %priceVBux) @ 0 @ MyShopItemDeetsPanel;
    MyShopPriceOutOfRangeText @ "<just:center>" @ %maxPrice @ " " @ "vBux maximum".setTextWithStyle();
    submitPriceValid = (%maxPrice > %priceVBux) @ 0 @ MyShopItemDeetsPanel;
    "".setTextWithStyle();
    submitPriceValid = MyShopPriceOutOfRangeText @ 1 @ MyShopItemDeetsPanel;
    updateSubmitValidity();
    %itemMultiplier = 1;
    MyShopItemDeetsPanel;
    %multiplier = (%itemMultiplier * $gVPointsRatio);
    %priceVPoints = (%multiplier * %priceVBux);
    %priceVPoints.setText();
};
function MyShopItemDeetsPanel::updateSubmitValidity(%this) {
    %valid = 1;
    %valid = (submitPriceValid & %valid);
    %this;
    %valid = (submitTexturesValid & %valid);
    %this;
    %valid = (submitDescriptionValid & %valid);
    %this;
    1.setActive();
    modulationColor = MyShopSubmitButton @ "255 255 255 255" @ MyShopSubmitButton;
    %valid;
    0.setActive();
    modulationColor = MyShopSubmitButton @ "255 255 255 64" @ MyShopSubmitButton;
};
function MyShopSubmitButton::onClick(%this) {
    %itemType = ClosetGui_MyShop_GetSkuUGCStatus($gMyShopCurrentSku);
    MessageBoxOkCancel(%itemType[$gMyShopSubmitTitle @ %itemType], %itemType[$gMyShopSubmitBody @ %itemType], "MessageBoxOK(\"not implemented\", \"\", \"\");", "");
};
function MyShop_InspectTexture(%num) {
    close();
    showingTextureNum = MyShopTextureInspector @ "" @ MyShopTextureInspector;
    (MyShopTextureInspector SPC showingTextureNum $= %num);
    %bitmap = geTextureTarget.getBitmap();
    isVisible() @ %num @ MyShopItemDeetsPanel;
    %bitmap.setBitmap();
    open();
    getGroup().pushToBack();
    showingTextureNum = MyShopTextureInspector @ %num @ MyShopTextureInspector;
    MyShopTextureInspector;
};
function MyShopTextureInspector::open(%this) {
    %this.setVisible(1);
    otherGenderText.setVisible(0);
};
function MyShopTextureInspector::close(%this) {
    %this.setVisible(0);
    otherGenderText.setVisible(1);
};
function MyShopStartNewButton::onClick(%this) {
    %templateSku = $gMyShopCurrentSku.findTemplateSku();
    SkuManager;
    error(getScopeName() @ " " @ "- can't find template for sku" @ " " @ $gMyShopCurrentSku @ " " @ getTrace());
    return (!((ClosetGui_MyShop_GetSkuUGCStatus($gMyShopCurrentSku) $= "TEMPLATES")) SPC %templateSku $= "");
    ClosetGui_MyShop_SetView("Templates");
    ClosetGui_MyShop_SetCurrentSku(%templateSku);
    %templateSku.toggleSku();
    %si = $gMyShopCurrentSku.findBySku();
    SkuManager;
    error(getScopeName() @ " " @ "- invalid sku" @ " " @ $gMyShopCurrentSku @ " " @ getTrace());
    return !(isObject(%si));
    %trgdir = "user/textures/templates/" @ %si @ descShrt @ "/" @ getTimeStamp();
    %n = (%si - getWordCount(originalTxtrNames));
    1.0;
    %originalName = getWord(originalTxtrNames, %n);
    %si;
    %originalPath = (0.0 >= %n) @ "projects/common/characters/" @ $player.getGender() @ "_player/" @ %originalName;
    %textureName = %originalPath;
    %ext = "";
    %try = ".png";
    %ext = %try;
    isFile((%ext $= "") @ %originalPath @ %try);
    %try = ".jpg";
    %ext = %try;
    isFile((%ext $= "") @ %originalPath @ %try);
    %try = ".png";
    %ext = %try;
    isFile((%ext $= "") @ $DC::CacheFolderName @ "/" @ %originalPath @ %try);
    %originalPath = $DC::CacheFolderName @ "/" @ %originalPath;
    error(getScopeName() @ " " @ "- can't find original file" @ " " @ %originalPath @ " " @ getTrace());
    return (%ext $= "");
    %srcFile = %originalPath @ %ext;
    %workingDir = getPrefsDir();
    ($Platform $= "macos");
    %trgdir = %workingDir @ "/" @ %trgdir;
    %srcFile = %workingDir @ "/" @ %srcFile;
    %trgFile = %trgdir @ "/" @ %originalName @ %ext;
    echoDebug(getScopeName() @ " " @ "- copying" @ " " @ %srcFile @ " " @ "to" @ " " @ %trgFile);
    error(getScopeName() @ " " @ "- error copying" @ " " @ %srcFile @ " " @ "to" @ " " @ %trgFile);
    return !(fileCopy(%srcFile, %trgFile));
    textureName = %textureName @ %n @ MyShopItemDeetsPanel @ geTextureTarget;
    geTextureTarget.applyTexture(%trgFile);
    %srcFile = "platform/client/ets/ugcReadMe.txt";
    %n @ MyShopItemDeetsPanel;
    %trgFile = %trgdir @ "/readme.txt";
    fileCopy(%srcFile, %trgFile);
    %n = (1.0 - %n);
    %vsDir = ((0.0 >= %n) SPC $Platform $= "windows") @ (6.0 >= $Platform::Version::Major) @ getVirtualStoreDir() @ "/" @ %trgdir;
    openFileSystemFolder(%vsDir);
    openFileSystemFolder(%trgdir);
    openFileSystemFolder(%trgdir);
};
