function CSBrowser::getHiliteProxy(%this) {
    %ancestor = %this;
    %ancestor = %ancestor.getParent();
    isObject(%ancestor);
    return %ancestor;
    return "";
};
function CSBrowser::goToParentPath(%this) {
    Parent::goToParentPath(%this);
};
function CSBrowser::getMenuText(%this, %text) {
    return getField(strreplace(%text, "|", "\t"), 0);
};
function CSBrowser::getPathForSku(%this, %sku) {
    %si = %sku.findBySku();
    SkuManager;
    return "";
    %name = descShrt;
    %si;
    %firstPath = getField(strreplace(drwrName, ";", "" @ "\t" @ ""), 0);
    %si;
    %path = strreplace(%firstPath, "/", "" @ "\t" @ "");
    return "";
    return %this @ baseDir @ "\t" @ %path @ "\t" @ %name @ "|" @ %sku;
};
function CSBrowser::getPathsForSku(%this, %sku) {
    %si = %sku.findBySku();
    SkuManager;
    return "";
    %name = descShrt;
    %si;
    return "";
    %paths = trim(strreplace(drwrName, ";", "\n"));
    %si;
    %additionalPaths = %this.getAddlPathsForSku(%sku);
    %paths = %paths @ "\n" @ %additionalPaths;
    !((%additionalPaths $= ""));
    %paths = "All Items" @ "\n" @ %paths;
    return "";
    %toReturn = "";
    %numRecords = getRecordCount(%paths);
    %i = 0;
    %path = getRecord(%paths, %i);
    (%numRecords < %i);
    %path = trim(strreplace(%path, "/", "\t"));
    %toReturn = %toReturn @ "\n" @ %this @ baseDir @ "\t" @ %path @ "\t" @ %name @ "|" @ %sku;
    %i = (1.0 + %i);
    return trim(%toReturn);
};
$CSBrowser::NewFurnishingPath = "New Items";
function CSBrowser::getAddlPathsForSku(%this, %sku) {
    %si = %sku.findBySku();
    SkuManager;
    return !(isObject(%si));
    %brand = brand;
    %si;
    %path = "";
    %path = $CSBrowser::NewFurnishingPath;
    (%brand $= "new");
    return %path;
};
function CSBrowser::addSku(%this, %sku) {
    %paths = %this.getPathsForSku(%sku);
    %numPaths = getRecordCount(%paths);
    %i = 0;
    %path = getRecord(%paths, %i);
    (%numPaths < %i);
    %node = %this.addNode(%path);
    !((%path $= ""));
    sku = %sku @ %node;
    %i = (1.0 + %i);
};
function CSBrowser::removeSku(%this, %sku) {
    %paths = %this.getPathsForSku(%sku);
    %numPaths = getRecordCount(%paths);
    %i = 0;
    %path = getRecord(%paths, %i);
    (%numPaths < %i);
    %this.deleteNodeAtPath(%path);
    %i = (1.0 + %i);
    !((%path $= ""));
    %this.clearEmptyCategories();
    %this.update();
};
function CSBrowser::navigateToSku(%this, %sku) {
    %path = %this.getPathForSku(%sku);
    %this.goToPath(%path, 0);
};
function CSBrowser::clearEmptyCategories(%this) {
    %this.clearEmptyCategoriesAt(%this.getNode(""));
    %this.goToPath(baseDir);
};
function CSBrowser::clearEmptyCategoriesAt(%this, %node) {
    return !(isObject(%node));
    %numChildren = %node.getCount();
    %i = (1.0 - %numChildren);
    %this.clearEmptyCategoriesAt(%node.getObject(%i));
    %i = (1.0 - %i);
    (0.0 >= %i);
    %this.deleteNode(%node);
};
function CSBrowser::update(%this) {
    %this.goToCurrentPath(0);
};
$CSBrowser::TopOfListCategories = $CSBrowser::NewFurnishingPath;
function CSBrowser::goToPath(%this, %path, %focus) {
    %focus = 1;
    !(isDefined("%focus"));
    Parent::goToPath(%this, %path, %focus);
    %menu = %this.getCurrentMenu();
    %count = %menu.getCount();
    %i = 0;
    %menuItem = %menu.getChild(0, %i);
    (%count < %i);
    %sku = getSubStr(strchr(name, "|"), 1);
    %menuItem;
    %this.modifyListViewForSku(%sku, %menuItem);
    %menu.reorderChild(%menuItem, %menu.getChild(0, 0));
    %i = (1.0 + %i);
    (%menuItem >= findRecord($CSBrowser::TopOfListCategories, name));
    command = (%this == level) @ !(%this.otherBrowsersVisible()) @ %this.getId() @ ".switchToOtherBrowser();" @ 0 @ %this @ button;
    1.0;
    button.setActive(1);
};
$CSBrowser::NewFurnishingIconBitmap = "platform/client/ui/new_logo_small";
$CSBrowser::FurnishingFolderBitmap = "platform/client/ui/folderIcon";
function CSBrowser::modifyListViewForSku(%this, %sku, %menuItem) {
    %leftIcon = leftIcon;
    %menuItem;
    %rightIcon = rightIcon;
    %menuItem;
    %si = %sku.findBySku();
    SkuManager;
    %rIconBmp = "";
    !((%sku $= ""));
    %rIconBmp = $CSBrowser::NewFurnishingIconBitmap;
    (%si SPC brand $= "new");
    %rightIcon.setBitmap(%rIconBmp);
    %lIconBmp = %this.getThumbnailPathForSku(%sku, 32);
    !((%rIconBmp $= ""));
    %leftIcon.setBitmap(%lIconBmp);
    menuText.reposition(33, getWord(menuText.getPosition(), 1));
    %leftIcon.setBitmap($CSBrowser::FurnishingFolderBitmap);
    menuText.reposition(33, getWord(menuText.getPosition(), 1));
};
function CSBrowser::onCreatedChild(%this, %child, %x, %y) {
    Parent::onCreatedChild(%this, %child, %x, %y);
    menu.bindClassName("CSBrowserFrame");
};
function CSBrowserFrame::onCreatedChild(%this, %child, %x, %y) {
    Parent::onCreatedChild(%this, %child, %x, %y);
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = mMax((24.0 - getWord(%child.getExtent(), 0)), 0) @ " " @ 0;
    extent = "24 24";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "";
    rightIcon = %child;
    %child.add(rightIcon);
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = %child @ "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "24 24";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "";
    leftIcon = %child;
    %child.add(leftIcon);
};
function CSBrowserNextPrevLink::onURL(%this, %url) {
    %dir = getWord(%url, 1);
    (getWord(%url, 0) $= "gamelink");
    return;
    browser.selectNextLeaf(1, 0);
};
function CSBrowser::fillLeafPane(%this, %pane) {
    %desc = getField(Path, (%this - level));
    1.0;
    %desc = %this.getMenuText(%desc);
    %this;
    return (%this $= baseDir);
    %paneWidth = getWord(%pane.getExtent(), 0);
    %paneHeight = getWord(%pane.getExtent(), 1);
    %sku = getSubStr(strchr(getField(Path, (%this - level)), "|"), 1);
    1.0;
    %si = %sku.findBySku();
    SkuManager;
    %desc = %desc @ "\n" @ "<spush><color:ff0000>New!<spop>";
    (%si SPC brand $= "new");
    profile = GuiMLTextCtrl @ new ""() @ "H2Profile";
    0;
    horizSizing = !((%this SPC %sku $= "")) @ "right";
    vertSizing = "bottom";
    position = "5 0";
    extent = (5.0 - %paneWidth) @ " " @ 18;
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    lineSpacing = 0;
    allowColorChars = 1;
    maxChars = -1;
    text = %desc;
    %itemText = ;
    %pane.add(%itemText);
    itemText = %itemText @ %pane;
    %itemText.forceReflow();
    class = GuiMLTextCtrl @ new ""() @ "CSBrowserNextPrevLink";
    0;
    profile = "GuiDefaultProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = (30.0 - %paneWidth) @ " " @ (21.0 - getWord(%pane.getExtent(), 1));
    extent = "30 15";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    lineSpacing = 0;
    allowColorChars = 1;
    maxChars = -1;
    text = "<linkcolor:e553ff><linkcolorhl:ff93f8><a:gamelink prev><<</a>  <a:gamelink next>>></a>";
    %nextPrevText = ;
    %pane.add(%nextPrevText);
    nextPrevText = %nextPrevText @ %pane;
};
$CSBrowser::ThumbnailFilename = "projects/common/inventory/[sku]/thumb_[size]x[size]_[sku]";
$CSBrowser::MissingThumbFilename = "platform/client/ui/thumbNotFound_[size]x[size]";
function CSBrowser::getThumbnailPathForSku(%this, %sku, %size) {
    %fileName = strreplace($CSBrowser::ThumbnailFilename, "[size]", %size);
    %fileName = strreplace(%fileName, "[sku]", %sku);
    return %fileName;
};
function CSBrowser::ShowMoreFor(%this, %sku) {
    return (%sku $= "");
    %si = %sku.findBySku();
    SkuManager;
    return !(isObject(%si));
    return (%si SPC descLong $= "");
    %pathRecords = %this.getPathsForSku(%sku);
    %count = getRecordCount(%pathRecords);
    error((0.0 == %count) @ getScopeName() @ "->this CSBrowser doesn't have a path for sku = " @ %sku @ ", which is a presumably valid sku as it is in the SKUManager.");
    return;
    %pathToUse = getRecord(%pathRecords, 0);
    %i = 0;
    %aPath = getRecord(%pathRecords, %i);
    (%count < %i);
    %pathToUse = %aPath;
    (%this $= Path);
    %i = (1.0 + %i);
    trim(%aPath);
    showMoreInfo = (%count < %i) @ 1 @ %this;
    %this.goToPath(%pathToUse);
};
function CSBrowser::isNodeExpanded(%this, %path) {
    %sku = getSubStr(strchr(getField(%path, (1.0 - getFieldCount(%path))), "|"), 1);
    return 0;
    %si = %sku.findBySku();
    SkuManager;
    return (1.0 == %this.getFieldValue("showMoreInfo"));
};
function CSBrowser::fillExpandedContentPane(%this, %expandedPane) {
    %frame = %expandedPane.getParent();
    %rightEdgeOfContentPane = (%frame + getWord(contentPane.getExtent(), 0));
    getWord(contentPane.getPosition(), 0);
    %rightEdgeOfContentPane = (10.0 + %rightEdgeOfContentPane);
    %frame;
    %bottomOfItemText = (contentPane + getWord(itemText.getPosition(), 1));
    %frame;
    %sku = getSubStr(strchr(getField(Path, (%this - level)), "|"), 1);
    1.0;
    warn((%this SPC %sku $= "") @ getScopeName() @ "-> couldn't parse sku from path");
    return getWord(itemText.getExtent(), 1);
    %si = %sku.findBySku();
    SkuManager;
    warn(!(isObject(%si)) @ getScopeName() @ "-> couldn't find sku = " @ %sku @ " in skumanager!");
    return;
    position = GuiMLTextCtrl @ new ""() @ %rightEdgeOfContentPane @ " " @ %bottomOfItemText;
    0;
    extent = (5.0 - (%rightEdgeOfContentPane - getWord(%expandedPane.getExtent(), 0))) @ " " @ 18;
    text = "<color:ffffff><spush><color:00ff00>" @ %si @ descShrt @ "<spop>\n" @ %si @ descLong;
    visible = 1;
    %descText = ;
    %expandedPane.add(%descText);
    descText = %descText @ %expandedPane;
};
function CSBrowser::collapseView(%this) {
    Parent::collapseView(%this);
};
function CSBrowser::onResized(%this) {
    Parent::onResized(%this);
};
function CSBrowser::resizeParentsBy(%this, %delta) {
    %window = %this.getParent().getParent();
    %windowExt = %window.getTrgExtent();
    %window.setTrgExtent((getWord(%delta, 0) + getWord(%windowExt, 0)), (getWord(%delta, 1) + getWord(%windowExt, 1)));
    Parent::resizeParentsBy(%this, %delta);
};
function CSBrowser::otherBrowsersVisible(%this) {
    return isVisible();
};
