$gCSFurnitureMoverClipboard = "";
function CSFurnitureMover::toggle(%this) {
    %this.close();
    %this.open();
};
$CSMaximumSlots = 0;
function CSFurnitureMover::open(%this) {
    %wasOpen = %this.isVisible();
    closeCSPanelsInOtherCategories(%this);
    %this.setVisible(1);
    %this.focusAndRaise();
    %this.updateButtonStates();
    %this.updateClickText();
    %prevState = isActive();
    CSRotateZButton;
    1.setActive();
    performClick();
    %prevState.setActive();
    update();
    CustomSpaceClient::checkEditingSpace();
    push();
    getUserActivityMgr().setActivityActive("decorating", 1);
};
function CSFurnitureMover::close(%this) {
    %wasOpen = %this.isVisible();
    %this.SelectNuggetID(-(1.0));
    %this.setVisible(0);
    CustomSpaceClient::checkEditingSpace();
    focusTopWindow();
    update();
    pop();
    getUserActivityMgr().setActivityActive("decorating", 0);
    return 1;
};
function CSFurnitureMover::isInEditMode(%this) {
    return %this.isVisible();
};
function CSFurnitureMover::updateButtonStates(%this) {
    %itemSelected = (-(1.0) != $CSSelectedID);
    %itemSelected.setActive();
    %itemSelected.setActive();
    %itemSelected.setActive();
    %itemSelected.setActive();
    %itemSelected.setActive();
    %itemSelected.setActive();
    %itemSelected.setActive();
    %itemSelected.setActive();
    %itemSelected.setActive();
    $CSSelectedFreeRotate.setActive();
    $CSSelectedFreeRotate.setActive();
    %itemSelected.setActive();
    (0.0 > numUsingFurnitureAll()).setActive();
    "Drop".setText();
    "Pick Up".setText();
};
function CSFurnitureMover::updateClickText(%this) {
    %prefix = "<color:cccccc>Click = ";
    %moveBy = mRoundTo(csGetMoveClickSize(), 0.001);
    %moveUnit = " feet";
    " foot";
    (1.0 == %moveBy) @ CSMoveClickText @ %prefix @ "<color:ffffff>" @ %moveBy @ %moveUnit.setText();
    %rotateBy = mRoundTo(csGetRotateClickSize(), 0.01);
    %rotateUnit = " degrees";
    " degree";
    (1.0 == %rotateBy) @ CSRotateClickText @ %prefix @ "<color:ffffff>" @ %rotateBy @ %rotateUnit.setText();
};
function CSFurnitureMover::preSelectedNuggetChanged(%this) {
    commandToServer('SlotPickUp', CustomSpaceClient::GetSpaceImIn(), $CSSelectedID);
    $CSboolPickedUp = 0;
    $CSboolPickedUp;
    $CSboolPickedUp = 0;
    (-(1.0) != $CSSelectedID);
};
function CSFurnitureMover::SelectNuggetObject(%this, %obj) {
    $CSSelectedGhost.SetSelected(0);
    $CSSelectedGhost = 0;
    isObject($CSSelectedGhost);
    getNuggetGhostList("CSFurnitureMover::refreshGhostList");
    return (0.0 != %obj);
    %nuggetId = %obj.getInventoryNuggetID();
    return (0.0 < %nuggetId);
    $CSSelectedGhost = %obj;
    $CSSelectedIsOwned = %obj.getInventoryNuggetIsOwned();
    $CSSelectedSku = %obj.getInventoryNuggetSKU();
    $CSSelectedFreeRotate = %obj.getInventoryNuggetFreeRotate();
    $CSSelectedGhost.SetSelected(1);
    %this.SelectNuggetID(%nuggetId);
    open();
    $CSSelectedSku.navigateToSku();
    open();
    $CSSelectedSku.navigateToSku();
    commandToServer('orientTowards', $CSSelectedGhost.getGhostID(), 400);
};
function CSFurnitureMover::SelectNuggetID(%this, %id) {
    %lastSelectedID = $CSSelectedID;
    %wasSelectedOwned = $CSSelectedIsOwned;
    preSelectedNuggetChanged();
    $CSSelectedID = %id;
    CSFurnitureMover;
    update();
    %this.updateButtonStates();
    %this.open();
    %this.SelectNuggetObject(0);
    $CSSelectedSku = -(1.0);
    (0.0 >= %id);
    $CSSelectedIsOwned = 0;
    CSFurnitureMoverText;
    $CSSelectedGhost = 0;
    $CSSelectedFreeRotate = 0;
    Initialize();
    update();
};
$gCSGhostList = "";
function CSFurnitureMover::refreshGhostList(%ghostlist) {
    $gCSGhostList = %ghostlist;
    !((%ghostlist $= $gCSGhostList));
    %numGhosts = getWordCount($gCSGhostList);
    (0.0 > $CSSelectedID);
    %i = 0;
    ($CSSelectedID != $CSSelectedGhost.getInventoryNuggetID());
    %ghost = getWord($gCSGhostList, %i);
    (%numGhosts < %i);
    %ghost.SelectNuggetObject();
    rentabotClient_customizeBot(%ghost);
    %i = (1.0 + %i);
    %ghost.isClassAIPlayer();
    update();
};
function CSFurnitureMover::doCopyOrCut(%this, %obj, %operation) {
    %obj = $CSSelectedGhost;
    !(isDefined("%obj"));
    return !(isObject(%obj));
    commandToServer('CSGetTransformForID', CustomSpaceClient::GetSpaceImIn(), %obj.getInventoryNuggetID(), %obj, %operation);
};
function CSFurnitureMover::doCopy(%this, %obj) {
    %obj = $CSSelectedGhost;
    !(isDefined("%obj"));
    %this.doCopyOrCut(%obj, "copy");
};
function CSFurnitureMover::doCut(%this, %obj) {
    %obj = $CSSelectedGhost;
    !(isDefined("%obj"));
    %this.doCopyOrCut(%obj, "cut");
};
function clientCmdCSReturnTransformForID(%id, %position, %orientation, %obj, %operation) {
    return !(isObject(%obj));
    $gCSFurnitureMoverClipboard = %obj.getInventoryNuggetSKU() @ "\t" @ %position @ "\t" @ %orientation;
    %obj.SelectNuggetObject();
    csTestFreeSelectedItem();
};
$gCSFurnitureClipboardFieldCount = 3;
function CSFurnitureMover::canPaste(%this) {
    %toPaste = $gCSFurnitureMoverClipboard;
    %record = getRecord(%toPaste, 0);
    return 0;
    %sku = getField(%record, 0);
    return (numUsingFurnitureSku(%sku) > numOwnedFurnitureSku(%sku));
};
function CSFurnitureMover::doPaste(%this) {
    %this.pasteString($gCSFurnitureMoverClipboard);
};
function CSFurnitureMover::pasteString(%this, %toPaste) {
    return (trim(%toPaste) $= "");
    %record = getRecord(%toPaste, 0);
    %sku = getField(%record, 0);
    ($gCSFurnitureClipboardFieldCount == getFieldCount(%record));
    %position = getField(%record, 1);
    %orientation = getField(%record, 2);
    CustomSpaceClient::placeSkuInWorld(%sku, %position, %orientation);
    %this.schedule(0, "pasteString", getRecords(%toPaste, 1));
};
function CSFurnitureMoverText::update(%this) {
    %color = "<color:ffffff>";
    %linkcolor = "<linkcolor:e553ff>";
    %linkcolorhl = "<linkcolorhl:ff93f8>";
    %startTags = %color @ %linkcolor @ %linkcolorhl;
    %endTags = "";
    %nextPrevLinks = "<just:right><a:gamelink PREV><<</a>  <a:gamelink NEXT>>></a>";
    %clipStartTag = "<clip:190>";
    (0.0 > $CSSelectedID);
    %clipEndTag = "</clip>";
    %startTags = %startTags @ %clipStartTag;
    %endTags = %endTags @ %clipEndTag;
    %si = $CSSelectedSku.findBySku();
    SkuManager;
    $CSboolPickedUp @ CSFurnitureMoverText @ %startTags @ %si @ descShrt @ " (following me)" @ %endTags.setText();
    !($CSSelectedIsOwned) @ CSFurnitureMoverText @ %startTags @ %si @ descShrt @ " (test drive)" @ %endTags @ %nextPrevLinks.setText();
    %whichOne = 0;
    %howMany = numUsingFurnitureSku($CSSelectedSku);
    %numGhosts = getWordCount($gCSGhostList);
    !((isObject($CSSelectedGhost) SPC $gCSGhostList $= ""));
    %i = 0;
    %ghost = getWord($gCSGhostList, %i);
    (%numGhosts < %i);
    getNuggetGhostList("CSFurnitureMover::refreshGhostList");
    %whichOne = 0;
    !(isObject(%ghost));
    %sku = %ghost.getInventoryNuggetSKU();
    %whichOne = (1.0 + %whichOne);
    ($CSSelectedSku == %sku);
    %i = (1.0 + %i);
    ($CSSelectedGhost == %ghost);
    (1.0 == %howMany) @ CSFurnitureMoverText @ %startTags @ %si @ descShrt @ %endTags @ %nextPrevLinks.setText();
    (%numGhosts < %i) @ (1.0 == %whichOne) @ (0.0 > %whichOne) @ CSFurnitureMoverText @ %startTags @ %si @ descShrt @ " (" @ %whichOne @ "/" @ %howMany @ ")" @ %endTags @ %nextPrevLinks.setText();
    CSFurnitureMoverText @ %startTags @ %si @ descShrt @ %endTags.setText();
    schedule(500, 0, "getNuggetGhostList", "CSFurnitureMover::refreshGhostList");
    CSFurnitureMoverText @ %startTags @ "Click on an item in the room to select it" @ %endTags.setText();
};
function CSFurnitureMoverText::onURL(%this, %url) {
    %url = getWords(%url, 1);
    (getWord(%url, 0) $= "gamelink");
    %selectedObj = "";
    %numGhosts = getWordCount($gCSGhostList);
    (getWord(%url, 0) $= "NEXT");
    %i = 0;
    %ghost = getWord($gCSGhostList, %i);
    (%numGhosts < %i);
    %selectedObj = getWord($gCSGhostList, (%numGhosts % (1.0 + %i)));
    ($CSSelectedGhost.getInventoryNuggetID() == %ghost.getInventoryNuggetID());
    %i = (1.0 + %i);
    %numGhosts = getWordCount($gCSGhostList);
    ((%numGhosts < %i) SPC getWord(%url, 0) $= "PREV");
    %i = 0;
    %ghost = getWord($gCSGhostList, %i);
    (%numGhosts < %i);
    %selectedObj = getWord($gCSGhostList, (%numGhosts % (%numGhosts + (1.0 - %i))));
    ($CSSelectedGhost.getInventoryNuggetID() == %ghost.getInventoryNuggetID());
    %i = (1.0 + %i);
    %selectedObj.SelectNuggetObject();
};
function CSRotationResetText::onURL(%this, %url) {
    %url = getWords(%url, 1);
    (getWord(%url, 0) $= "gamelink");
    %ref = $CSSelectedID;
    (getWord(%url, 0) $= "RESET");
    return (-(1.0) == %ref);
    commandToServer('SlotResetRotation', CustomSpaceClient::GetSpaceImIn(), %ref);
};
function csGetMoveClickSize() {
    $UserPref::Spaces::Granularity = mClampF($UserPref::Spaces::Granularity, 0, 1);
    %min = 0.125;
    return (mPow(2, ($UserPref::Spaces::Granularity * 6.0)) * %min);
};
function csGetRotateClickSize() {
    $UserPref::Spaces::Granularity = mClampF($UserPref::Spaces::Granularity, 0, 1);
    %min = 1.40625;
    return (mPow(2, ($UserPref::Spaces::Granularity * 6.0)) * %min);
};
$CSSelectedGhost = 0;
$CSSelectedID = -(1.0);
$CSSelectedSku = -(1.0);
$CSSelectedIsOwned = 0;
$CSSelectedFreeRotate = 0;
$CSboolPickedUp = 0;
function csTestRotateCW() {
    %ref = $CSSelectedID;
    return (-(1.0) == %ref);
    commandToServer('SlotRotate', CustomSpaceClient::GetSpaceImIn(), %ref, rotationAxis, (180.0 / ($pi * csGetRotateClickSize())));
    setIdle(0);
};
function csTestRotateCCW() {
    %ref = $CSSelectedID;
    return (-(1.0) == %ref);
    commandToServer('SlotRotate', CustomSpaceClient::GetSpaceImIn(), %ref, rotationAxis, (180.0 / ($pi * -(csGetRotateClickSize()))));
    setIdle(0);
};
function csTestMoveLeft() {
    %ref = $CSSelectedID;
    return (-(1.0) == %ref);
    commandToServer('SlotMoveLeft', CustomSpaceClient::GetSpaceImIn(), %ref, csGetMoveClickSize());
    setIdle(0);
};
function csTestMoveRight() {
    %ref = $CSSelectedID;
    return (-(1.0) == %ref);
    commandToServer('SlotMoveRight', CustomSpaceClient::GetSpaceImIn(), %ref, csGetMoveClickSize());
    setIdle(0);
};
function csTestMoveIn() {
    %ref = $CSSelectedID;
    return (-(1.0) == %ref);
    commandToServer('SlotMoveIn', CustomSpaceClient::GetSpaceImIn(), %ref, csGetMoveClickSize());
    setIdle(0);
};
function csTestMoveOut() {
    %ref = $CSSelectedID;
    return (-(1.0) == %ref);
    commandToServer('SlotMoveOut', CustomSpaceClient::GetSpaceImIn(), %ref, csGetMoveClickSize());
    setIdle(0);
};
function csTestRaise() {
    %ref = $CSSelectedID;
    return (-(1.0) == %ref);
    commandToServer('SlotRaise', CustomSpaceClient::GetSpaceImIn(), %ref, csGetMoveClickSize());
    setIdle(0);
};
function csTestLower() {
    %ref = $CSSelectedID;
    return (-(1.0) == %ref);
    commandToServer('SlotLower', CustomSpaceClient::GetSpaceImIn(), %ref, csGetMoveClickSize());
    setIdle(0);
};
function csTestTogglePickUp() {
    %ref = $CSSelectedID;
    error("Attempting to pick up an item, but we have nothing selected currently.");
    return (-(1.0) == %ref);
    $CSboolPickedUp = !($CSboolPickedUp);
    commandToServer('SlotPickUp', CustomSpaceClient::GetSpaceImIn(), %ref);
    update();
    updateButtonStates();
    setIdle(0);
};
function csTestFreeSelectedItem() {
    %ref = $CSSelectedID;
    return (-(1.0) == %ref);
    putAwayAnotherFurnitureSku($CSSelectedSku);
    update();
    getNuggetGhostList("CSFurnitureMover::refreshGhostList");
    -(1.0).SelectNuggetID();
    commandToServer('CSDeleteRefID', CustomSpaceClient::GetSpaceImIn(), %ref);
    updateButtonStates();
    setIdle(0);
};
function customSpace::ConfirmFreeAllItems() {
    %title = "Put Everything Away";
    %body = "\nThis will put <spush><b>everything<spop> into storage!\n\n<spush><b>THERE IS NO UNDO!<spop>\n\nAre you sure?";
    %cbOkay = "CustomSpace::FreeAllItems();";
    %cbCancel = "handleSystemMessage(\"msgInfoMessage\", \"Chicken!\");";
    MessageBoxOkCancel(%title, %body, %cbOkay, %cbCancel);
};
function customSpace::FreeAllItems() {
    -(1.0).SelectNuggetID();
    commandToServer('CSDeleteAllInventory', CustomSpaceClient::GetSpaceImIn());
    getNuggetGhostList("CSFurnitureMover::refreshGhostList");
    putAwayAllFurniture();
    update();
    updateButtonStates();
    setIdle(0);
};
function CSFurnitureMover::InitForSpace(%this, %unused, %numberOfSlots) {
    $CSMaximumSlots = %numberOfSlots;
    %this.SelectNuggetID(-(1.0));
    %this.updateButtonStates();
};
function FurnitureItemContextMenu::initWithObject(%this, %obj) {
    %obj = "";
    !(isDefined("%obj"));
    %this.clear();
    obj = %obj @ %this;
    %grey = "255 255 255 128";
    %white = "255 255 255 255";
    %this.addScheme(1, %grey, %grey, %grey);
    %this.addScheme(2, %white, %white, %white);
    %schemeNormal = 0;
    %schemeDisabled = 1;
    %sku = %obj.getInventoryNuggetSKU();
    isObject(%obj);
    %si = %sku.findBySku();
    SkuManager;
    %this.setText(descShrt);
    %n = (1.0 + %n);
    %this.add("Deselect", (%obj == $CSSelectedGhost), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Select", %si, %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Drop", $CSboolPickedUp, %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Pick Up", (%obj == $CSSelectedGhost), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Put Away", %obj.getInventoryNuggetIsOwned(), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Cut", , %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Copy", , %schemeNormal);
    %schemeMoreAvailable = 1;
    0;
    %n = (1.0 + %n);
    %this.add("Place Another", (numUsingFurnitureSku(%sku) > numOwnedFurnitureSku(%sku)), %schemeMoreAvailable);
    %schemeCanBuy = 1;
    0;
    %n = (1.0 + %n);
    %this.add("Buy Another", (-(1.0) != numOwnedFurnitureSku(%sku)), %schemeCanBuy);
    %schemeReset = 1;
    0;
    %n = (1.0 + %n);
    %this.add("Reset Material", (0.0 > %obj.getActiveSku()), %schemeReset);
    %n = (1.0 + %n);
    %this.add("Buy Now", , %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Done Test Driving", , %schemeNormal);
    %schemeCanPaste = %schemeDisabled;
    %schemeNormal;
    %n = (1.0 + %n);
    %this.add("Paste", canPaste(), %schemeCanPaste);
};
function FurnitureItemContextMenu::onSelect(%this, %id, %text) {
    -(1.0).SelectNuggetID();
    obj.SelectNuggetObject();
    csTestTogglePickUp();
    obj.SelectNuggetObject();
    csTestTogglePickUp();
    obj.SelectNuggetObject();
    csTestFreeSelectedItem();
    obj.doCut();
    obj.doCopy();
    CustomSpaceClient::placeSkuInWorld(obj.getInventoryNuggetSKU());
    obj.getInventoryNuggetSKU().purchaseSkus();
    obj.getInventoryNuggetSKU().purchaseSkus();
    obj.SelectNuggetObject();
    csTestFreeSelectedItem();
    objSkusFixSku(obj, 0);
    doPaste();
};
