function CSShoppingBrowserWindow::open(%this) {
    %previouslyOpen = %this.isVisible();
    closeCSPanelsInOtherCategories(%this);
    %this.setVisible(1);
    %this.focusAndRaise();
    refreshInventory();
    open();
    update();
    CustomSpaceClient::checkEditingSpace();
    focusCurrentFrame();
};
function CSShoppingBrowserWindow::close(%this) {
    csTestFreeSelectedItem();
    %this.setVisible(0);
    resetFirstResponder();
    CustomSpaceClient::checkEditingSpace();
    update();
    return 1;
};
function CSShoppingBrowserWindow::toggle(%this) {
    %this.close();
    %this.open();
};
function CSShoppingBrowserWindow::Initialize(%this) {
    %ctrl = TreeBrowserControl::newControl("CSBrowser");
    CSShoppingBrowserContainer;
    %ctrl.bindClassName("CSShoppingBrowser");
    %ctrl.setName("CSShoppingBrowser");
    menuProfile = !(initialized) @ "ETSClearMenuProfile" @ CSShoppingBrowser;
    %this;
    selectedProfile = "ETSSelectedMenuItemNoBorderProfile" @ CSShoppingBrowser;
    1.setNumChildren();
    adjustMenuCellHeight = CSShoppingBrowser @ 1 @ CSShoppingBrowser;
    showMoreInfo = 1 @ CSInventoryBrowser;
    button.delete();
    %container = getParent();
    CSShoppingBrowser;
    profile = GuiBitmapButtonCtrl @ new ""() @ "ETSShopVerticalButtonProfile";
    0;
    horizSizing = CSShoppingBrowser @ isObject("button0".getFieldValue()) @ 0 @ CSShoppingBrowser @ "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = CSShoppingBrowser @ buttonWidth @ " " @ getWord(%container.getExtent(), 1);
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    command = "";
    text = "Shop";
    groupNum = -1;
    buttonType = "PushButton";
    bitmap = "platform/client/buttons/vbutton";
    drawText = 1;
    textRotation = 90;
    button = 0 @ CSShoppingBrowser;
    %container.add(button);
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = 0 @ CSShoppingBrowser @ "right";
    vertSizing = "top";
    position = "3 20";
    extent = "14 14";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/vbux_14";
    vBuxIcon = CSShoppingBrowser;
    %container.add(vBuxIcon);
    baseDir = CSShoppingBrowser @ "Shop" @ CSShoppingBrowser;
    baseDir.addNode();
    storeInfo = CSShoppingBrowser @ 0 @ CSShoppingBrowser;
    CSShoppingBrowser;
    refreshInventory();
    loadAvailableSkus();
    initialized = CSShoppingBrowser @ 1 @ %this;
    CSShoppingBrowser;
};
function CSShoppingBrowser::loadAvailableSkus(%this) {
    %this.clear();
    %skulist = "";
    %numSkus = 0;
    %skulist = storeInfo.getSkus();
    %this;
    %numSkus = getWordCount(%skulist);
    isObject(storeInfo);
    statusText = "No furnishings available to buy." @ "" @ %this;
    (0.0 == %numSkus);
    statusText = %this @ "Getting Store Info..." @ %this;
    %i = 0;
    %this.addSku(getWord(%skulist, %i));
    %i = (1.0 + %i);
    (%numSkus < %i);
    %this.goToPath(baseDir, 0);
    %this.update();
};
function CSShoppingBrowser::fillLeafPane(%this, %pane) {
    Parent::fillLeafPane(%this, %pane);
    %desc = getField(Path, (%this - level));
    1.0;
    %desc = %this.getMenuText(%desc);
    %this;
    %paneWidth = getWord(%pane.getExtent(), 0);
    %paneHeight = getWord(%pane.getExtent(), 1);
    buyQuantity = 1 @ %pane;
    %ypos = getWord(itemText.getExtent(), 1);
    %pane;
    %rightYPos = 18;
    !((%this $= baseDir));
    %rmVPadding = 4;
    !((%desc $= "")) SPC %desc;
    %buttonWidth = 62;
    %rightXPos = (%buttonWidth - %paneWidth);
    %sku = getSubStr(strchr(getField(Path, (%this - level)), "|"), 1);
    1.0;
    %si = %sku.findBySku();
    SkuManager;
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "BracketButton15Profile";
    0;
    horizSizing = %this @ !((%si SPC descLong $= "")) @ "right";
    vertSizing = "bottom";
    %rightYPos = (%rmVPadding + %rightYPos);
    position = (4.0 - %rightXPos) @ " ";
    extent = %buttonWidth @ " " @ 15;
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    command = "CSShoppingBrowser.showMoreFor(" @ %sku @ ");";
    text = "More..";
    groupNum = -1;
    buttonType = "PushButton";
    %moreButton = ;
    %rightYPos = (getWord(%moreButton.getExtent(), 1) + %rightYPos);
    text = %this.getFieldValue("showMoreInfo") @ "Less.." @ %moreButton;
    command = "CSShoppingBrowser.showMoreInfo = false; CSShoppingBrowser.goToCurrentPath();" @ %moreButton;
    %pane.add(%moreButton);
    moreButton = %moreButton @ %pane;
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "BracketButton15Profile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = (4.0 - %rightXPos) @ " " @ %rightYPos;
    extent = %buttonWidth @ " " @ 15;
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    command = "";
    text = "Try It!";
    groupNum = -1;
    buttonType = "PushButton";
    %testDriveButton = ;
    %rightYPos = (getWord(%testDriveButton.getExtent(), 1) + %rightYPos);
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "BracketButton15Profile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    %rightYPos = (%rmVPadding + %rightYPos);
    position = (4.0 - %rightXPos) @ " ";
    extent = %buttonWidth @ " " @ 15;
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    command = "";
    text = "Buy It!";
    groupNum = -1;
    buttonType = "PushButton";
    %buyButton = ;
    %rightYPos = (getWord(%buyButton.getExtent(), 1) + %rightYPos);
    %smallButtonWidth = 15;
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "BracketButton15Profile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = ((5.0 + (2.0 * %smallButtonWidth)) - (%buttonWidth + (4.0 - %rightXPos))) @ " " @ (%rmVPadding + %rightYPos);
    extent = %smallButtonWidth @ " " @ 15;
    command = %pane @ ".buyFewer();";
    text = "-";
    %buyFewerButton = ;
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "BracketButton15Profile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = (%smallButtonWidth - (%buttonWidth + (4.0 - %rightXPos))) @ " " @ (%rmVPadding + %rightYPos);
    extent = %smallButtonWidth @ " " @ 15;
    command = %pane @ ".buyMore();";
    text = "+";
    %buyMoreButton = ;
    %rightYPos = (getWord(%buyMoreButton.getExtent(), 1) + %rightYPos);
    %rightYPos = (%rmVPadding + %rightYPos);
    profile = GuiMLTextCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = (4.0 - %rightXPos) @ " " @ %rightYPos;
    extent = %buttonWidth @ " " @ 18;
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    lineSpacing = 0;
    allowColorChars = 1;
    maxChars = -1;
    text = "";
    %priceTextVPoints = ;
    %pane.add(%priceTextVPoints);
    priceTextVPoints = %priceTextVPoints @ %pane;
    %rightYPos = (getWord(%priceTextVPoints.getExtent(), 1) + %rightYPos);
    profile = GuiMLTextCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = (4.0 - %rightXPos) @ " " @ %rightYPos;
    extent = %buttonWidth @ " " @ 18;
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    lineSpacing = 0;
    allowColorChars = 1;
    maxChars = -1;
    text = "";
    %priceTextVBux = ;
    %pane.add(%priceTextVBux);
    priceTextVBux = %priceTextVBux @ %pane;
    %rightYPos = (getWord(%priceTextVBux.getExtent(), 1) + %rightYPos);
    %ypos = (2.0 + %ypos);
    %nextPrevTextY = getWord(nextPrevText.getPosition(), 1);
    %pane;
    %maxThumbnailHeight = (%ypos - %nextPrevTextY);
    %maxThumbnailHeight = mMin(%maxThumbnailHeight, (3.0 - %rightXPos));
    %ypos = (%ypos + (2.0 / ((%maxThumbnailHeight + %ypos) - %nextPrevTextY)));
    %ypos = mCeil(%ypos);
    %xPos = 0;
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = "right";
    vertSizing = "top";
    position = %xPos @ " " @ %ypos;
    extent = %maxThumbnailHeight @ " " @ %maxThumbnailHeight;
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = %this.getThumbnailPathForSku(%sku, 128);
    %thumbnail = ;
    %pane.add(%thumbnail);
    %pane.add(%testDriveButton);
    %pane.add(%buyButton);
    %pane.add(%buyFewerButton);
    %pane.add(%buyMoreButton);
    thumbnail = %thumbnail @ %pane;
    testDriveButton = %testDriveButton @ %pane;
    buyButton = %buyButton @ %pane;
    buyFewerButton = %buyFewerButton @ %pane;
    buyMoreButton = %buyMoreButton @ %pane;
    browser = %pane @ nextPrevText;
    CSShoppingBrowser;
    %pane.bindClassName("CSShoppingItemPane");
    %pane.update();
    profile = GuiMLTextCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = !((getWord(%pane.getNamespaceList(), 0) $= "CSShoppingItemPane")) @ "right";
    vertSizing = "bottom";
    position = "25 20";
    extent = (5.0 - %paneWidth) @ " " @ 18;
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    lineSpacing = 0;
    allowColorChars = 1;
    maxChars = -1;
    text = "<color:ffffff>" @ %this @ statusText;
    %noItemText = ;
    %pane.add(%noItemText);
};
function CSShoppingItemPane::buyMore(%this) {
    buyQuantity = (%this + buyQuantity);
    1.0;
    %this.update();
};
function CSShoppingItemPane::buyFewer(%this) {
    buyQuantity = (%this - buyQuantity);
    1.0;
    buyQuantity = %this @ buyQuantity @ %this;
    1;
    %this.update();
};
function CSShoppingBrowser::testDriveSku(%this, %sku) {
    $CSInstaTestDrive = 0;
    $CSSelectedSku = %sku;
    (0.0 > %sku);
    commandToServer('CreateInventoryBySkuJustTestingItOut', CustomSpaceClient::GetSpaceImIn(), %sku);
    error(getScopeName() @ " " @ "No sku selected");
};
function CSShoppingBrowser::purchaseSkus(%this, %skus) {
    return !(isObject(storeInfo));
    %cbPoints = "CSShoppingBrowser.purchaseSkusVPoints(\"" @ %skus @ "\");";
    %cbBux = "CSShoppingBrowser.purchaseSkusVBux(\"" @ %skus @ "\");";
    %cbCancel = "";
    ShowPurchaseSkusConfirmationDialog(%skus, %cbPoints, %cbBux, %cbCancel);
};
function CSShoppingBrowser::purchaseSkusVPoints(%this, %skus) {
    %totalPrice = Inventory::getTotalPrice("vPoints", %skus);
    isObject(storeInfo);
    %itemCount = getWordCount(%skus);
    %this;
    %itemsStr = "these" @ " " @ %itemCount @ " " @ "items";
    "this item";
    %vpointsString = "vPoints";
    "vPoint";
    %msg = (1.0 == %itemCount) @ ($Player::VPoints <= %totalPrice) @ (1.0 == %totalPrice) @ "Do you wish to purchase " @ %itemsStr @ " for " @ %totalPrice @ " " @ %vpointsString @ "?";
    %cmd = "CSShoppingBrowser.storeInfo.purchase(\"" @ %skus @ "\", \"vPoints\", \"CSShoppingBrowser::onGotPurchaseResult\");";
    MessageBoxOkCancel("Confirm Purchase", %msg, %cmd, "");
    MessageBoxOK("Not Enough vPoints", "You do not have enough vPoints to purchase " @ %itemsStr @ ".  Click <a:" @ $Net::HelpURL_VPoints @ ">here</a> for more information about earning vPoints.", "");
};
function CSShoppingBrowser::purchaseSkusVBux(%this, %skus) {
    %totalPrice = Inventory::getTotalPrice("vBux", %skus);
    isObject(storeInfo);
    %itemCount = getWordCount(%skus);
    %this;
    %itemsStr = "these" @ " " @ %itemCount @ " " @ "items";
    "this item";
    %msg = (1.0 == %itemCount) @ ($Player::VBux <= %totalPrice) @ "Do you wish to purchase " @ %itemsStr @ " for " @ %totalPrice @ " vBux?";
    %cmd = "CSShoppingBrowser.storeInfo.purchase(\"" @ %skus @ "\", \"vBux\", \"CSShoppingBrowser::onGotPurchaseResult\");";
    MessageBoxOkCancel("Confirm Purchase", %msg, %cmd, "");
    MessageBoxOK("Not Enough vBux", "You do not have enough vBux to purchase " @ %itemsStr @ ".  Click <a:" @ $Net::AddFundsURL @ ">here</a> to refill your account.", "");
};
function CSShoppingBrowser::onGotPurchaseResult(%status, %results) {
    %numResults = getWordCount(%results);
    (%status $= "success");
    %i = 0;
    %result = getWord(%results, %i);
    (%numResults < %i);
    %result = strreplace(%result, "|", " ");
    %sku = getWord(%result, 0);
    %resultCode = getWord(%result, 1);
    csTestFreeSelectedItem();
    addFurnitureSku(%sku, 1);
    loadAvailableSkus();
    CustomSpaceClient::placeSkuInWorld(%sku);
    %i = (1.0 + %i);
    (0.0 == %i);
    MessageBoxOK("Purchase Unsuccessful", "There was a problem completing your purchase.", "");
};
function CSShoppingBrowser::goToPath(%this, %path, %focus) {
    %focus = 1;
    !(isDefined("%focus"));
    %oldPath = Path;
    %this;
    Parent::goToPath(%this, %path, %focus);
    %curMenu = %this.getCurrentMenu();
    %count = %curMenu.getCount();
    %i = 0;
    %menuItem = %curMenu.getObject(%i);
    (%count < %i);
    %sku = strchr(name, "|");
    %menuItem;
    %menuItem.bindClassName("CSShoppingBrowserSKUItem");
    %i = (1.0 + %i);
    !((!((%sku $= "")) SPC getWord(%menuItem.getNamespaceList(), 0) $= "CSShoppingBrowserSKUItem"));
    vBuxIcon.reposition(3, (20.0 - getWord(%this.getExtent(), 1)));
    %pathSku = getSubStr(strchr(%path, "|"), 1);
    CSShoppingBrowser;
    csTestFreeSelectedItem();
};
$CSShoppingBrowser::InstaTestDriveEnabled = 0;
$CSInstaTestDrive = 0;
$CSShoppingBrowserSKUItem::deleteEvent = 0;
function CSShoppingBrowserSKUItem::onMouseEnterBounds(%this) {
    Parent::onMouseEnterBounds(%this);
    return !($CSShoppingBrowser::InstaTestDriveEnabled);
    warn("CSShoppingBrowserSKUItem .name has gone missing?");
    return (%this SPC name $= "");
    cancel($CSShoppingBrowserSKUItem::deleteEvent);
    %sku = getSubStr(strchr(name, "|"), 1);
    %this;
    $CSInstaTestDrive = 1;
    isEventPending($CSShoppingBrowserSKUItem::deleteEvent);
    $CSSelectedSku = %sku;
    !($CSSelectedIsOwned);
    commandToServer('CreateInventoryBySkuJustTestingItOut', CustomSpaceClient::GetSpaceImIn(), %sku);
};
function CSShoppingBrowserSKUItem::onMouseLeaveBounds(%this) {
    Parent::onMouseLeaveBounds(%this);
    $CSInstaTestDrive = 0;
    !(isEventPending($CSShoppingBrowserSKUItem::deleteEvent));
    csTestFreeSelectedItem();
    return $CSInstaTestDrive;
    warn("CSShoppingBrowserSKUItem .name has gone missing?");
    return (%this SPC name $= "");
    cancel($CSShoppingBrowserSKUItem::deleteEvent);
    %code = isEventPending($CSShoppingBrowserSKUItem::deleteEvent) @ "$CSInstaTestDrive = false;" @ "csTestFreeSelectedItem();";
    $CSInstaTestDrive;
    $CSShoppingBrowserSKUItem::deleteEvent = schedule(500, 0, "eval", %code);
};
function CSShoppingBrowser::refreshInventory(%this) {
    storeInfo.refreshInventory("CSShoppingBrowser::onGotFurnishingsStore");
    getFurnitureStore("CSShoppingBrowser::onGotFurnishingsStore");
};
function CSShoppingBrowser::onGotFurnishingsStore(%storeInfo, %status) {
    storeInfo = (%status $= "success") @ %storeInfo @ CSShoppingBrowser;
    loadAvailableSkus();
};
function CSShoppingItemPane::update(%this) {
    %sku = sku;
    node;
    return (%this SPC %sku $= "");
    %si = %sku.findBySku();
    SkuManager;
    log("inventory", "error", !(isObject(%si)) @ getScopeName() @ " " @ "- invalid sku: \"" @ %sku @ "\"." @ " " @ getTrace());
    return;
    %skus = "";
    %delim = "";
    %n = 0;
    %skus = %this @ (buyQuantity < %n) @ %skus @ %delim @ %sku;
    %delim = " ";
    %n = (1.0 + %n);
    command = %this @ testDriveButton;
    %this @ (buyQuantity < %n) @ "CSShoppingBrowser.testDriveSku(\"" @ %sku @ "\");";
    command = %this @ buyButton;
    "CSShoppingBrowser.purchaseSkus(\"" @ %skus @ "\");";
    %vpoints = priceVPoints;
    %si;
    %vbux = priceVBux;
    %si;
    %vpoints = (buyQuantity * %vpoints);
    %this;
    %vbux = (buyQuantity * %vbux);
    %this;
    buyButton.setText("Buy It!");
    buyFewerButton.setActive(0);
    buyButton.setText("Buy" @ " " @ %this @ buyQuantity @ "!");
    buyFewerButton.setActive(1);
    %vpointsIcon = "<bitmap:platform/client/ui/vpoints_14>";
    %this;
    %vbuxIcon = "<bitmap:platform/client/ui/vbux_14>";
    %this;
    priceTextVBux.setText((%this == buyQuantity) @ %this @ %this @ %this @ "<color:ffffff>" @ %vbuxIcon @ "  " @ %vbux @ "");
    priceTextVPoints.setText((%si < priceVBux) @ "-" @ 1.0 @ %this @ "<color:ffffff>" @ %vpointsIcon @ " " @ %vpoints @ "");
};
function CSShoppingBrowser::switchToOtherBrowser(%this) {
    close();
    open();
};
$gCSShoppingBrowserFilterFieldTimerID = "";
function CSShoppingBrowserFilterField::OnTextChanged(%this) {
    cancel($gCSShoppingBrowserFilterFieldTimerID);
    $gCSShoppingBrowserFilterFieldTimerID = %this.schedule(timeoutMS, "onTimer");
    %this;
};
function CSShoppingBrowserFilterField::OnEnterKey(%this) {
    %this.refilter();
};
function CSShoppingBrowserFilterField::onTimer(%this) {
    %this.refilter();
};
function CSShoppingBrowserFilterField::refilter(%this) {
    cancel($gCSShoppingBrowserFilterFieldTimerID);
    $gCSShoppingBrowserFilterFieldTimerID = "";
    %filterText = %this.getValue();
    return (%this $= prevFilterText);
    prevFilterText = %filterText @ %this;
    filterText = %filterText @ CSShoppingBrowser;
    goToCurrentPath();
    %filterText.setValue();
    filterText = CSInventoryBrowserFilterField @ %filterText @ CSInventoryBrowser;
    CSShoppingBrowser;
    goToCurrentPath();
};
