hotSpot = ETSHandCursor @ new () @ "7 0";
GuiCursor;
bitmapName = 0 @ "platform/client/ui/CUR_hand";
hotSpot = ETSDefaultCursor @ new () @ "1 1";
GuiCursor;
bitmapName = 0 @ "platform/client/ui/CUR_3dArrow";
hotSpot = MoveCursor @ new () @ "7 3";
GuiCursor;
bitmapName = 0 @ "platform/client/ui/CUR_drag";
hotSpot = UpDownCursor @ new () @ "7 7";
GuiCursor;
bitmapName = 0 @ "platform/client/ui/CUR_vert";
hotSpot = LeftRightCursor @ new () @ "7 7";
GuiCursor;
bitmapName = 0 @ "platform/client/ui/CUR_horiz";
hotSpot = NWSECursor @ new () @ "7 7";
GuiCursor;
bitmapName = 0 @ "platform/client/ui/CUR_ul_lr";
hotSpot = NESWCursor @ new () @ "7 7";
GuiCursor;
bitmapName = 0 @ "platform/client/ui/CUR_ur_ll";
