$CSCurrentSpaceName = "";
$CSSpaceName = "";
$CSBuildingName = 0;
$CSSpaceInfo = 0;
$CSBuildingInfo = 0;
function CustomSpaceClient::SetCurrentSpaceName(%spaceName) {
    $CSCurrentSpaceName = %spaceName;
};
function CustomSpaceClient::GetCurrentSpaceName() {
    return $CSCurrentSpaceName;
};
function CustomSpaceClient::GetSpaceImIn() {
    return $CSSpaceName;
};
function CustomSpaceClient::SetSpaceImIn(%buildingName, %spaceName) {
    error(getScopeName() @ " " @ "you are already in this space:" @ " " @ %spaceName);
    return !((($CSSpaceName $= %spaceName) SPC $CSSpaceName $= ""));
    $CSBuildingName = %buildingName;
    $CSSpaceName = %spaceName;
    $CSBlockedList = "";
    return ((%buildingName $= "") SPC %spaceName $= "");
    CustomSpaceClient::SetUpOwnership(1);
    return $StandAlone;
    getBuildingSpaceInfo($CSBuildingName, $CSSpaceName, "GotCustomSpaceInfo", "");
};
function CustomSpaceClient::OnClientDisconnect() {
    CustomSpaceClient::SetupClientAsNotInSpace();
};
function CustomSpaceClient::SetupClientAsNotInSpace() {
    close();
    close();
    close();
    close();
    close();
    close();
    close();
    close();
    close();
    "private space".hideTabWithName();
    destroySpaceInfo($CSSpaceInfo);
    $CSSpaceInfo = 0;
    (0.0 != $CSSpaceInfo);
    $CSBuildingInfo = 0;
    HudTabs;
    CustomSpaceClient::SetSpaceImIn("", "");
    CustomSpaceClient::SetUpOwnership(0);
};
$CS_EditingCustomSpace = 0;
function CustomSpaceClient::startEditingSpace() {
    return $CS_EditingCustomSpace;
    csRequestToEditSpace();
    $CS_EditingCustomSpace = 1;
    onCustomSpaceEditorEnable();
};
function CustomSpaceClient::stopEditingSpace() {
    return !($CS_EditingCustomSpace);
    csDoneEditingSpace();
    $CS_EditingCustomSpace = 0;
    onCustomSpaceEditorDisable();
};
function CustomSpaceClient::checkEditingSpace() {
    CustomSpaceClient::startEditingSpace();
    CustomSpaceClient::stopEditingSpace();
};
function GotCustomSpaceInfo(%buildingInfo, %spaceGroup) {
    echo("received custom space info");
    log("network", "error", (1.0 != %spaceGroup.getCount()) @ "GotCustomSpaceInfo returned a strange number of spaces (" @ %spaceGroup.getCount() @ ")");
    destroySpaceInfo($CSSpaceInfo);
    $CSBuildingInfo = %buildingInfo;
    isObject($CSSpaceInfo);
    $CSSpaceInfo = %spaceGroup.getObject(0);
    (0.0 != $CSSpaceInfo);
    %spaceGroup.remove($CSSpaceInfo);
    %spaceGroup.delete();
    %isOwner = 0;
    %isOwner = ($CSSpaceInfo == stricmp(owner, $player.getShapeName()));
    0.0;
    error("$Player is not an object. Setting space I'm in before I'm there...");
    CustomSpaceClient::SetUpOwnership(%isOwner);
    access.updateSettings(password, description);
    open();
    update();
    "MODEL_APT".selectTabWithName();
    CustomSpacesClient::setMap2DText();
    CustomSpacesClient::InitializeVideoRequest();
};
function CustomSpacesClient::setMap2DText() {
    $CSSpaceInfo @ TryFixBadWords(description).setMap2DForCustomSpacesMode(($CSSpaceInfo SPC type $= "CELEBSPACE") @ ($CSSpaceInfo @ name @ $CSSpaceInfo @ owner @ "\n\tBuilding:\t" SPC Buildings::GetDescription($CSBuildingName) $= "") @ $CSBuildingName @ Buildings::GetDescription($CSBuildingName) @ "\n\tCity:\t" @ getContiguousSpaceFullName(Buildings::GetContiguousSpace($CSBuildingName)));
};
$CSSpaceOwner = 0;
function CustomSpaceClient::SetUpOwnership(%isOwner) {
    %wasOwner = $CSSpaceOwner;
    log("network", "debug", "setting space ownership to " @ %isOwner);
    hideOP();
    disableOPlink();
    open();
    "MODEL_APT".selectTabWithName();
    close();
    0.setChangeStationAllowed();
    hideButton();
    $CSSpaceOwner = 0;
    PrivateSpacePopupMenuButton;
    showButton();
    %showSpaceOwnerTip = $Player::Name.getProperty("ShowOwnerTip", 1);
    gUserPropMgrClient;
    $Player::Name.setProperty("ShowOwnerTip", 0);
    userTips::showNow("SpaceOwner");
    $CSSpaceOwner = 1;
    gUserPropMgrClient;
    $CSBlockedList = blockedList;
    $CSSpaceInfo;
    Music::createGetMusicStreamsRequest();
    1.setChangeStationAllowed();
    csLoadMediaFavorites();
    csRequestHotMedia();
    getOwnedFurniture();
};
function CustomSpaceClient::isOwner() {
    return $CSSpaceOwner;
};
function CustomSpaceClient::placeSkuInWorld(%sku, %position, %orientation) {
    error(getScopeName() @ " " @ "No sku selected");
    return (0.0 <= %sku);
    %position = "";
    !(isDefined("%position"));
    %orientation = "";
    !(isDefined("%orientation"));
    return (numOwnedFurnitureSku(%sku) >= numUsingFurnitureSku(%sku));
    %title = "Sorry, Can't Do That";
    ($CSMaximumSlots >= numUsingFurnitureAll());
    %body = "This space can only have" @ " " @ $CSMaximumSlots @ " " @ "items in it at a time.  Put something away to make more room.";
    MessageBoxOK(%title, %body, "");
    return;
    return !(useAnotherFurnitureSku(%sku));
    $CSSelectedSku = %sku;
    commandToServer('CreateInventoryBySkuAt', CustomSpaceClient::GetSpaceImIn(), %sku, %position, %orientation);
    commandToServer('CreateInventoryBySku', CustomSpaceClient::GetSpaceImIn(), %sku);
    update();
    update();
    setIdle(0);
};
function CustomSpacesClient::InitializeVideoRequest() {
    echo("CSClientRequestVideoInit");
    commandToServer('CSClientRequestVideoInit', CustomSpaceClient::GetSpaceImIn());
};
function csRequestToEditSpace() {
    commandToServer('CSRequestToEdit', CustomSpaceClient::GetSpaceImIn());
};
function csDoneEditingSpace() {
    commandToServer('CSDoneEditing', CustomSpaceClient::GetSpaceImIn());
};
function clientCmdCSRequestToEditAccepted(%spaceName, %numberOfSlots) {
    error(getScopeName() @ " " @ "how can you accept to edit a space that you are not in?");
    return !((CustomSpaceClient::GetSpaceImIn() $= %spaceName));
    %spaceName.InitForSpace(%numberOfSlots);
};
function clientCmdCSOnUnownedInventoryTimeOut(%referenceID) {
    -(1.0).SelectNuggetID();
    $CSInstaTestDrive = 0;
    CSFurnitureMover;
    getNuggetGhostList("CSFurnitureMover::refreshGhostList");
};
function clientCmdCSRequestToEditDenied(%spaceName, %msg) {
    MessageBoxOK("Sorry", "your request to edit this space was denied" @ "\n" @ %msg, "");
};
function customSpace::SetMusicStreamID(%streamID, %displayId) {
    return (CustomSpaceClient::GetSpaceImIn() $= "");
    %displayId = "";
    !(isDefined("%displayID"));
    commandToServer('CSSetMusicStream', CustomSpaceClient::GetSpaceImIn(), %streamID, %displayId);
};
function customSpace::SetVideoURL(%videoURL) {
    return (CustomSpaceClient::GetSpaceImIn() $= "");
    commandToServer('CSSetVideoURL', CustomSpaceClient::GetSpaceImIn(), %videoURL);
};
function clientCmdCS_OnEnterSpace(%spaceName, %musicStreamId, %videoURL, %building, %CurrentLayout) {
    clientCmdCS_OnLeaveSpace(CustomSpaceClient::GetCurrentSpaceName());
    close();
    CustomSpaceClient::SetCurrentSpaceName(%spaceName);
    Initialize();
    %analyticSpace = strreplace(%spaceName, ".", " ");
    CSMediaDisplay;
    %analytic = getAnalytic();
    CSControlPanel;
    %analytic.trackPageView(!((CustomSpaceClient::GetCurrentSpaceName() $= "")) @ "/client/apartment/" @ getWord(%analyticSpace, 0) @ "/enter");
    late_OnEnterSpace(%spaceName, %musicStreamId, %videoURL, %building, %CurrentLayout);
};
function late_OnEnterSpace(%spaceName, %musicStreamId, %videoURL, %building, %CurrentLayout) {
    schedule(500, 0, %spaceName, %musicStreamId, %videoURL, %building, %CurrentLayout);
    return late_OnEnterSpace;
    CustomSpaceClient::SetSpaceImIn(%building, %spaceName);
    %musicStreamId.syncPlayingAudioStream();
    %videoURL.syncPlayingMediaStream();
    $CSLayoutSelector::NumLayouts.updateSettings(%CurrentLayout);
    Initialize();
    Initialize();
};
function clientCmdCS_OnLeaveSpace(%spaceName) {
    %analyticSpace = strreplace(%spaceName, ".", " ");
    (CustomSpaceClient::GetCurrentSpaceName() $= %spaceName);
    %analytic = getAnalytic();
    %analytic.trackPageView("/client/apartment/" @ getWord(%analyticSpace, 0) @ "/exit");
    CustomSpaceClient::SetupClientAsNotInSpace();
    destroySpaceInfo($CSSpaceInfo);
    $CSSpaceInfo = 0;
    isObject($CSSpaceInfo);
    hideButton();
    CustomSpaceClient::SetCurrentSpaceName("");
};
function destroySpaceInfo(%spaceInfo) {
    return !(isObject(%spaceInfo));
    videoplayer.unloadVideoRenderer();
    %spaceInfo.delete();
};
$CSNewInventoryGhostRefreshEvent = 0;
function clientCmdCS_OnInventoryCreated(%sku, %referenceName, %isOwned, %freeRotate) {
    %referenceName.SelectNuggetID();
    $CSSelectedIsOwned = %isOwned;
    CSFurnitureMover;
    $CSSelectedFreeRotate = %freeRotate;
    GrowingPlantClient::onPlantCreated(%referenceName);
    cancel($CSNewInventoryGhostRefreshEvent);
    $CSNewInventoryGhostRefreshEvent = schedule(500, 0, "getNuggetGhostList", "CSFurnitureMover::refreshGhostList");
    isEventPending($CSNewInventoryGhostRefreshEvent);
};
function clientCmdCS_OnInventoryCreationFailed(%sku, %isOwned) {
    refreshActiveFurniture();
    -(1.0).SelectNuggetID();
};
function clientCmdCS_OnEnterEntryPortal(%buildingName) {
    forceRightMouseUp();
    %buildingName.open();
};
function CustomSpaceClient::CheckBlockUserFromSpace(%playerName, %unblock) {
    %blockText = "unblock";
    "block";
    handleSystemMessage("msgInfoMessage", (%unblock $= "") @ ((0.0 == %unblock) SPC CustomSpaceClient::GetSpaceImIn() $= "") @ "Sorry, you must be in a space to " @ %blockText @ " users from it.");
    return 0;
    handleSystemMessage("msgInfoMessage", (%playerName $= "") @ "You didn't specify anyone to " @ %blockText);
    return 0;
    handleSystemMessage("msgInfoMessage", !($player.rolesPermissionCheckNoWarn("manageUsers")) @ !(CustomSpaceClient::isOwner()) @ "You must be the owner of a space to " @ %blockText @ " users from it.");
    return 0;
    return 1;
};
function CustomSpaceClient::setCoHostHood(%playerName, %set, %confirm) {
    %confirm = 1;
    !(isDefined("%confirm"));
    %msg = %confirm[%confirm @ $MsgCat::custSpace TAB "OWNER_ACTION" @ "COHOST-CONFIRM"];
    %set;
    %msg = strreplace(%msg, "[TARGET]", %playerName);
    MessageBoxYesNo("Make Co-Host", %msg, "CommandToServer('setCohostHood', \"" @ %playerName @ "\", true);", "");
    commandToServer('setCohostHood', %playerName, %set);
};
function CustomSpaceClient::toggleCoHostHood(%playerName) {
    %player = Player::findPlayerInstance(%playerName);
    error(getScopeName() @ " " @ "- could not find player" @ " " @ %playerName @ " " @ getTrace());
    return !(isObject(%player));
    %state = %player.isCohost();
    CustomSpaceClient::setCoHostHood(%playerName, !(%state), 0);
};
function CustomSpaceClient::TryBlockUserFromSpace(%playerName, %unblock) {
    return !(CustomSpaceClient::CheckBlockUserFromSpace(%playerName, %unblock));
    CustomSpaceClient::ReallyTryBlockUserFromSpace(%playerName, %unblock);
    return %unblock;
    MessageBoxYesNo("Block" @ " " @ %playerName @ " " @ "from this space", "This will block" @ " " @ %playerName @ " " @ "from entering this space. You can unblock them later. Do you want to block" @ " " @ %playerName @ " " @ "?", "CustomSpaceClient::ReallyTryBlockUserFromSpace(\"" @ %playerName @ "\", " @ %unblock @ ");", "");
};
function CustomSpaceClient::ReallyTryBlockUserFromSpace(%playerName, %unblock) {
    return !(CustomSpaceClient::CheckBlockUserFromSpace(%playerName, %unblock));
    %blockText = "unblock";
    "block";
    %space = CustomSpaceClient::GetSpaceImIn();
    (0.0 == %unblock);
    className = ManagerRequest @ new ""() @ "BanFromSpaceRequest";
    0;
    %request = (%unblock $= "");
    %request.add();
    blockedPlayer = MissionCleanup @ %playerName @ %request;
    isObject();
    blockText = MissionCleanup @ %blockText @ %request;
    %url = $Net::ClientServiceURL @ "/BanFromSpace" @ "?user=" @ urlEncode($Player::Name) @ "&token=" @ urlEncode($Token) @ "&space=" @ urlEncode(%space) @ "&userToBan=" @ urlEncode(%playerName);
    %url = !(((1.0 == %unblock) SPC %unblock $= "")) @ %url @ "&unban=true";
    echo("BanFromSpaceRequest: " @ %url);
    log("network", "debug", "BanFromSpaceRequest: " @ %url);
    %request.setURL(%url);
    %request.start();
};
function BanFromSpaceRequest::onDone(%this) {
    %status = findRequestStatus(%this);
    handleSystemMessage("msgInfoMessage", !((%status $= "success")) @ "" @ %this @ blockText @ " unsuccessful.");
    handleSystemMessage("msgInfoMessage", "" @ %this @ getPlayerMarkup(blockedPlayer, "", 1) @ " was " @ %this @ blockText @ "ed from this space.");
    $CSBlockedList = %this @ blockedPlayer;
    $CSBlockedList @ "\t";
    $CSBlockedList = blockedPlayer;
    %this;
    $CSBlockedList = removeField($CSBlockedList, findField($CSBlockedList, blockedPlayer));
    %this;
};
function CustomSpaceClient::TryBootAllUsersFromSpace(%space) {
    return !(CustomSpaceClient::isOwner());
    handleSystemMessage("msgInfoMessage", "You must either specify a space or be in one to boot all users.");
    return ((%space $= "") SPC CustomSpaceClient::GetSpaceImIn() $= "");
    %space = CustomSpaceClient::GetSpaceImIn();
    (%space $= "");
    className = ManagerRequest @ new ""() @ "BootAllFromSpaceRequest";
    0;
    %request = ;
    %request.add();
    spaceName = MissionCleanup @ %space @ %request;
    isObject();
    %url = MissionCleanup @ $Net::ClientServiceURL @ "/BootAllFromSpace" @ "?user=" @ urlEncode($Player::Name) @ "&token=" @ urlEncode($Token) @ "&space=" @ urlEncode(%space);
    log("network", "debug", "BootAllFromSpaceRequest: " @ %url);
    %request.setURL(%url);
    %request.start();
};
function BootAllFromSpaceRequest::onDone(%this) {
    %status = findRequestStatus(%this);
    handleSystemMessage("msgInfoMessage", !((%status $= "success")) @ "Couldn't boot all from " @ %this @ spaceName @ ".");
    handleSystemMessage("msgInfoMessage", "Booted everyone from " @ %this @ spaceName @ ".");
};
function CustomSpaceClient::doOwnerAction(%action, %target) {
    commandToServer('OwnerAction', %action, %target);
};
function teleportToAdjacentSpace(%next) {
    commandToServer('GoToNextSpaceBasedOnCamera');
    commandToServer('GoToPrevSpaceBasedOnCamera');
    return %next;
    commandToServer('GoToNextSpaceBasedOnLogicalName', CustomSpaceClient::GetSpaceImIn());
    commandToServer('GoToPrevSpaceBasedOnLogicalName', CustomSpaceClient::GetSpaceImIn());
};
function teleportToSpaceNumber(%number) {
    commandToServer('GoToSpaceNumber', %number);
};
function getBuildingDirectory(%buildingName, %callbackFn, %callbackFail) {
    %BuildingDirRequest = new ""();
    SimObject;
    %BuildingDirRequest.add();
    callback = MissionCleanup @ %callbackFn @ %BuildingDirRequest;
    isObject();
    callbackFailure = MissionCleanup @ %callbackFail @ %BuildingDirRequest;
    0;
    buildingName = %buildingName @ %BuildingDirRequest;
    spaceName = "" @ %BuildingDirRequest;
    doneBuildingInfo = 0 @ %BuildingDirRequest;
    doneCSList = 0 @ %BuildingDirRequest;
    doCheckForBuildingInfo(%BuildingDirRequest, 0);
    doGetSpaceInfo(%BuildingDirRequest);
};
function getBuildingSpaceInfo(%buildingName, %spaceName, %callbackFn, %callbackFail) {
    %BuildingDirRequest = new ""();
    SimObject;
    %BuildingDirRequest.add();
    callback = MissionCleanup @ %callbackFn @ %BuildingDirRequest;
    isObject();
    callbackFailure = MissionCleanup @ %callbackFail @ %BuildingDirRequest;
    0;
    buildingName = %buildingName @ %BuildingDirRequest;
    spaceName = %spaceName @ %BuildingDirRequest;
    doneBuildingInfo = 0 @ %BuildingDirRequest;
    doneCSList = 0 @ %BuildingDirRequest;
    doCheckForBuildingInfo(%BuildingDirRequest, 0);
    doGetSpaceInfo(%BuildingDirRequest);
};
function doCheckForBuildingInfo(%BuildingDirRequest, %forceupdate) {
    safeEnsureScriptObject("SimSet", "BuildingInfos");
    %buildingInfo = findBuildingInfo(buildingName);
    %BuildingDirRequest;
    buildingInfo = !(%forceupdate) @ %buildingInfo @ %BuildingDirRequest;
    (0.0 != %buildingInfo);
    doneBuildingInfo = 1 @ %BuildingDirRequest;
    checkDoneBuildingDirectory(%BuildingDirRequest);
    return;
    clearBuildingInfo(%buildingInfo);
    GetBuildingInfoRequest(%BuildingDirRequest);
};
function checkDoneBuildingDirectory(%BuildingDirRequest) {
    log("network", "error", "Directory tracker is not an object?!");
    return !(isObject(%BuildingDirRequest));
    log("network", "debug", "Checking directory request done.");
    log("network", "debug", %BuildingDirRequest @ doneBuildingInfo);
    log("network", "debug", %BuildingDirRequest @ doneCSList);
    linkSpaces(buildingInfo, spaces);
    %command = %BuildingDirRequest @ callback @ "( %BuildingDirRequest.buildingInfo, %BuildingDirRequest.spaces);";
    %BuildingDirRequest;
    log("network", "debug", doneCSList @ %BuildingDirRequest @ "About to eval callback: \"" @ %command @ "\"");
    eval(%command);
    %BuildingDirRequest.delete();
};
function linkSpaces(%buildingInfo, %spaceGroup) {
    log("network", "debug", "linking " @ %spaceGroup.getCount() @ " apartments to building info and floor plans");
    %idx = 0;
    %space = %spaceGroup.getObject(%idx);
    (%spaceGroup.getCount() < %idx);
    buildingInfo = %buildingInfo @ %space;
    floorplan = %space @ findFloorPlan(%buildingInfo, floorPlanName) @ %space;
    %idx = (1.0 + %idx);
};
function getOwnerSpacesInfo(%ownerName, %onCompleteFN) {
    %tracker = getOwnerSpaceInfoTracker(%ownerName);
    onCompleteFN = %onCompleteFN @ %tracker;
    %request = sendRequest_GetCustomSpaceInfo("", "", %ownerName, "onDoneOrErrorCallback_GetCustomSpaceInfo");
    tracker = %tracker @ %request;
};
function ownerHasSpaceWithFloorplan(%ownerName, %floorplanName) {
    %tracker = getOwnerSpaceInfoTracker(%ownerName);
    %count = %tracker.getCount();
    error(getScopeName() @ " " @ "- user owns no spaces! (tracker not filled yet, probably)" @ " " @ %ownerName @ " " @ getTrace());
    return 0;
    %n = 0;
    %space = %tracker.getObject(%n);
    (%count < %n);
    %space.dumpValues();
    %fpn = %space.get("floorPlan");
    return 1;
    %n = (1.0 + %n);
    return 0;
};
function getOwnerSpaceInfoTracker(%ownerName) {
    safeEnsureScriptObject("StringMap", "gOwnerSpaceInfoTrackers", 0);
    %tracker = %ownerName.get();
    gOwnerSpaceInfoTrackers;
    %tracker = safeNewScriptObject("SimSet", "", 0);
    !(isObject(%tracker));
    %ownerName.put(%tracker);
    ownerName = gOwnerSpaceInfoTrackers @ %ownerName @ %tracker;
    return %tracker;
};
function onDoneOrErrorCallback_GetCustomSpaceInfo(%request, %result) {
    log("network", "debug", getScopeName() @ " " @ "- url =" @ " " @ %request.getURL());
    %tracker = tracker;
    %request;
    error(getScopeName() @ " " @ "- no tracker. should be impossible.");
    return !(isObject(tracker));
    %cb = completionCallback;
    %tracker;
    call(%cb, %request);
    return !((!(%request.checkSuccess()) SPC %cb $= ""));
    %tracker.deleteMembers();
    %listBase = "space";
    %numSpaces = %request.getResult(%listBase @ "Count");
    %n = 0;
    %map = safeNewScriptObject("StringMap", "", 0);
    (%numSpaces < %n);
    %listItemNameBase = %listBase @ %n;
    %fields = "";
    %fields = %fields @ "\t" @ "URI";
    %fields = %fields @ "\t" @ "access";
    %fields = %fields @ "\t" @ "audioStream";
    %fields = %fields @ "\t" @ "building";
    %fields = %fields @ "\t" @ "customSpaceId";
    %fields = %fields @ "\t" @ "description";
    %fields = %fields @ "\t" @ "featured";
    %fields = %fields @ "\t" @ "floorPlan";
    %fields = %fields @ "\t" @ "friendOccupancy";
    %fields = %fields @ "\t" @ "location.areaName";
    %fields = %fields @ "\t" @ "location.buildingName";
    %fields = %fields @ "\t" @ "location.serverName";
    %fields = %fields @ "\t" @ "longDescription";
    %fields = %fields @ "\t" @ "name";
    %fields = %fields @ "\t" @ "occupancy";
    %fields = %fields @ "\t" @ "owner";
    %fields = %fields @ "\t" @ "type";
    %fields = %fields @ "\t" @ "videoStream";
    %fields = %fields @ "\t" @ "banCount";
    %request.copyListValuesIntoMap(%map, %listItemNameBase, %fields);
    %fields = "";
    %m = 0;
    %fields = (%map.get("banCount") < %m) @ %fields @ "\t" @ "ban" @ %m;
    %m = (1.0 + %m);
    %request.copyListValuesIntoMap(%map, %listItemNameBase, %fields);
    URI = %map @ vurlClearResolution(URI) @ %map;
    (%map.get("banCount") < %m);
    %tracker.add(%map);
    %n = (1.0 + %n);
    update();
    call(onCompleteFN, %tracker);
};
function addBuildingInfo(%buildingInfo) {
    safeEnsureScriptObject("SimGroup", "BuildingInfos");
    log("network", "debug", "Adding building info for \"" @ %buildingInfo @ name @ "\" to cache");
    %buildingInfo.add();
    %buildingInfo.bringToFront();
    log("network", "debug", BuildingInfos @ "Cache now contains " @ BuildingInfos @ getCount() @ " items.");
};
function findBuildingInfo(%buildingName) {
    safeEnsureScriptObject("SimGroup", "BuildingInfos");
    %count = getCount();
    BuildingInfos;
    log("network", "debug", "Searching for \"" @ %buildingName @ "\" in cache (" @ %count @ " items)");
    %idx = 0;
    %buildingInfo = %idx.getObject();
    BuildingInfos;
    log("network", "debug", (%buildingInfo == stricmp(name, %buildingName)) @ "Found item at index " @ %idx);
    %buildingInfo.bringToFront();
    return %buildingInfo;
    %idx = (1.0 + %idx);
    log("network", "debug", "Item not found in cache");
    return 0;
};
function clearBuildingInfo(%buildingInfo) {
    safeEnsureScriptObject("SimGroup", "BuildingInfos");
    %buildingInfo.remove();
    %idx = 0;
    BuildingInfos;
    floorplan.delete();
    %idx = (1.0 + %idx);
    (floorPlanCount < %idx) @ %idx @ %buildingInfo;
    %buildingInfo.schedule(0, "delete");
};
function findFloorPlan(%buildingInfo, %floorplanName) {
    %idx = 0;
    %floorplan = floorplan;
    (floorPlanCount < %idx) @ %idx @ %buildingInfo;
    return %floorplan;
    %idx = (1.0 + %idx);
    return 0;
};
function GetBuildingInfoRequest(%tracker) {
    echo("we are in standalone, faking this");
    %command = %tracker @ callbackFailure @ "( %tracker.buildingName, \"we are in standalone mode so failing this\");";
    !((%tracker SPC callbackFailure $= ""));
    log("network", "debug", $StandAlone @ "About to eval callback: \"" @ %command @ "\"");
    eval(%command);
    return;
    className = ManagerRequest @ new ""() @ "GetBuildingInfo";
    0;
    %request = ;
    %request.add();
    %url = MissionCleanup @ isObject() @ MissionCleanup @ $Net::ClientServiceURL @ "/GetBuildingInfo" @ "?user=" @ urlEncode($Player::Name) @ "&token=" @ urlEncode($Token);
    %url = %tracker @ urlEncode(buildingName);
    %url @ "&building=";
    tracker = %tracker @ %request;
    log("network", "debug", "GetBuildingInfoRequest: " @ %url);
    %request.setURL(%url);
    %request.start();
};
function GetBuildingInfo::onDone(%this) {
    echo(getScopeName());
    %status = findRequestStatus(%this);
    log("network", "debug", "GetBuildingInfo status: " @ %status);
    echo((%status $= "fail") @ getScopeName() @ "->failed");
    %statusMsg = %this.getValue("statusMsg");
    log("network", "debug", "GetBuildingInfo failed due to: " @ %statusMsg);
    %command = tracker @ callbackFailure @ "( %this.tracker.buildingName, %statusMsg);";
    %this;
    log("network", "debug", %this @ !((tracker SPC callbackFailure $= "")) @ "About to eval callback: \"" @ %command @ "\"");
    eval(%command);
    %buildingInfo = new ""();
    SimObject;
    %buildingInfo.add();
    name = MissionCleanup @ %this.getValue("name") @ %buildingInfo;
    isObject();
    city = MissionCleanup @ %this.getValue("city") @ %buildingInfo;
    0;
    description = urlDecode(%this.getValue("description")) @ %buildingInfo;
    floorPlanCount = %this.getValue("floorPlansCount") @ %buildingInfo;
    %idx = 0;
    %floorplan = new ""();
    SimObject;
    %floorplan.add();
    name = MissionCleanup @ %this.getValue(isObject() @ MissionCleanup @ "floorPlans" @ %idx @ ".name") @ %floorplan;
    0;
    description = %this.getValue(%buildingInfo @ (floorPlanCount < %idx) @ "floorPlans" @ %idx @ ".description") @ %floorplan;
    capacity = %this.getValue("floorPlans" @ %idx @ ".capacity") @ %floorplan;
    minLevel = %this.getValue("floorPlans" @ %idx @ ".minLevel") @ %floorplan;
    priceVBux = %this.getValue("floorPlans" @ %idx @ ".priceVBux") @ %floorplan;
    priceVPoints = %this.getValue("floorPlans" @ %idx @ ".priceVPoints") @ %floorplan;
    isUpgrade = ( == stricmp(%this.getValue(0.0 @ "floorPlans" @ %idx @ ".upgrade"), "true")) @ %floorplan;
    numAvailable = %this.getValue("floorPlans" @ %idx @ ".numAvailable") @ %floorplan;
    floorplan.delete();
    floorplan = %idx @ %buildingInfo @ isObject(floorplan) @ %idx @ %buildingInfo @ %floorplan @ %idx @ %buildingInfo;
    %idx = (1.0 + %idx);
    addBuildingInfo(%buildingInfo);
    log("network", "debug", %buildingInfo @ (floorPlanCount < %idx) @ "Got building info for \"" @ %buildingInfo @ name @ "\" with " @ %buildingInfo @ floorPlanCount @ " floor plans");
    buildingInfo = %this @ tracker;
    isObject(tracker) @ %buildingInfo;
    doneBuildingInfo = %this @ tracker;
    %this @ 1;
    log("network", "warn", "%this.tracker is not an object.");
    checkDoneBuildingDirectory(tracker);
    %this.schedule(0, "delete");
};
function GetBuildingInfo::onError(%this, %unused, %errMsg) {
    %command = tracker @ callbackFailure @ "( %this.tracker.buildingName, %errMsg);";
    %this;
    log("network", "debug", %this @ !((tracker SPC callbackFailure $= "")) @ "About to eval callback: \"" @ %command @ "\"");
    eval(%command);
    log("network", "debug", "GetBuildingInfo::onError: " @ %errMsg);
    %this.schedule(0, "delete");
};
function doGetSpaceInfo(%tracker) {
    echo("we are in standalone, faking this");
    %command = %tracker @ callbackFailure @ "( %tracker.buildingName, \"we are in standalone mode so failing this\");";
    !((%tracker SPC callbackFailure $= ""));
    log("network", "debug", $StandAlone @ "About to eval fail callback: \"" @ %command @ "\"");
    eval(%command);
    return;
    className = ManagerRequest @ new ""() @ "GetSpaceInfo";
    0;
    %request = ;
    %request.add();
    %url = $Net::ClientServiceURL;
    MissionCleanup;
    %url = isObject() @ %url @ "/GetCustomSpaceInfo";
    MissionCleanup;
    %url = %url @ "?user=" @ urlEncode($Player::Name);
    %url = %url @ "&token=" @ urlEncode($Token);
    %url = %tracker @ urlEncode(buildingName);
    !((%tracker SPC buildingName $= "")) @ %url @ "&building=";
    %url = %tracker @ urlEncode(spaceName);
    !((%tracker SPC spaceName $= "")) @ %url @ "&space=";
    %url = %tracker @ urlEncode(ownerName);
    !((%tracker SPC ownerName $= "")) @ %url @ "&owner=";
    tracker = %tracker @ %request;
    %request.setURL(%url);
    %request.start();
};
function GetSpaceInfo::onDone(%this) {
    %status = findRequestStatus(%this);
    log("network", "debug", "GetSpaceInfo status: " @ %status);
    %statusMsg = %this.getValue("statusMsg");
    (%status $= "fail");
    error(getScopeName() @ " " @ "- failed w/" @ " " @ %statusMsg);
    %command = tracker @ callbackFailure @ "( %this.tracker.buildingName, %statusMsg);";
    %this;
    log("network", "debug", %this @ !((tracker SPC callbackFailure $= "")) @ "About to eval callback: \"" @ %command @ "\"");
    eval(%command);
    spaceBuildingName = %this @ tracker;
    %this.getValue("building");
    spaceCount = %this @ tracker;
    %this.getValue("spaceCount");
    spaces = %this @ tracker;
    SimGroup @ new ""();
    %idx = 0;
    0;
    %space = new ""();
    SimObject;
    %space.add();
    access = MissionCleanup @ %this.getValue(isObject() @ MissionCleanup @ "space" @ %idx @ ".access") @ %space;
    0;
    audioStream = %this @ %this.getValue(tracker @ (spaceCount < %idx) @ "space" @ %idx @ ".audioStream") @ %space;
    description = %this.getValue("space" @ %idx @ ".description") @ %space;
    isFeatured = (%this.getValue("space" @ %idx @ ".featured") $= "true") @ %space;
    floorPlanName = %this.getValue("space" @ %idx @ ".floorPlan") @ %space;
    longDescription = %this.getValue("space" @ %idx @ ".longDescription") @ %space;
    name = %this.getValue("space" @ %idx @ ".name") @ %space;
    occupancy = %this.getValue("space" @ %idx @ ".occupancy") @ %space;
    owner = %this.getValue("space" @ %idx @ ".owner") @ %space;
    password = %this.getValue("space" @ %idx @ ".password") @ %space;
    type = %this.getValue("space" @ %idx @ ".type") @ %space;
    vurl = %this.getValue("space" @ %idx @ ".URI") @ %space;
    videoStream = %this.getValue("space" @ %idx @ ".videoStream") @ %space;
    buildingName = %this.getValue("space" @ %idx @ ".building") @ %space;
    blockedList = "" @ %space;
    %banCount = %this.getValue("space" @ %idx @ ".banCount");
    %banCount = 0;
    (%banCount $= "");
    %k = 0;
    %blockedUser = %this.getValue((%banCount < %k) @ "space" @ %idx @ ".ban" @ %k);
    warn((%blockedUser $= "") @ getScopeName() @ "->banned user #" @ %k @ " out of " @ %banCount @ ", was NULL!");
    warn(0.0 @ (%space >= findField(blockedList, %blockedUser)) @ getScopeName() @ "->banned user #" @ %k @ " OUT OF " @ %banCount @ ", is a duplicate entry! entry = " @ %blockedUser @ " .");
    blockedList = %space @ blockedList @ "\t" @ %blockedUser @ %space;
    !((%space SPC blockedList $= ""));
    blockedList = %blockedUser @ %space;
    %k = (1.0 + %k);
    blockedList = %space @ trim(blockedList) @ %space;
    (%banCount < %k);
    spaces.add(%space);
    %idx = (1.0 + %idx);
    tracker;
    doneCSList = %this @ tracker;
    isObject(tracker) @ 1;
    checkDoneBuildingDirectory(tracker);
    %this.schedule(0, "delete");
};
function GetSpaceInfo::onError(%this, %unused, %errMsg) {
    log("network", "debug", "GetSpaceInfo::onError: " @ %errMsg);
    %command = tracker @ callbackFailure @ "( %this.tracker.buildingName, %errMsg);";
    %this;
    log("network", "debug", %this @ !((tracker SPC callbackFailure $= "")) @ "About to eval callback: \"" @ %command @ "\"");
    eval(%command);
    %this.schedule(0, "delete");
};
function purchaseApartmentRequest(%space, %useBux, %unused, %callback, %callbackFail) {
    className = ManagerRequest @ new ""() @ "PurchaseSpaceRequest";
    0;
    %request = ;
    %request.add();
    callback = MissionCleanup @ %callback @ %request;
    isObject();
    callbackFail = MissionCleanup @ %callbackFail @ %request;
    %url = "vbux" @ "vpoints";
    %useBux;
    log("network", "debug", $Net::ClientServiceURL @ "/PurchaseCustomSpace?" @ "user=" @ urlEncode($Player::Name) @ "&" @ "token=" @ urlEncode($Token) @ "&" @ "building=" @ %space @ buildingInfo @ urlEncode(name) @ "&" @ "floorPlan=" @ %space @ urlEncode(floorPlanName) @ "&" @ "payWith=" @ "PurchaseSpace: " @ %url);
    %request.setURL(%url);
    %request.start();
};
function PurchaseSpaceRequest::onDone(%this) {
    echo(getScopeName());
    %status = findRequestStatus(%this);
    log("network", "info", "PurchaseSpaceRequest status: " @ %status);
    %name = %this.getValue("name");
    (%status $= "success");
    %building = %this.getValue("building");
    %vurl = %this.getValue("vurl");
    warn("Server not returning space VURL in .vurl parameter.");
    %vurl = %this.getValue("URI");
    (%vurl $= "");
    %command = %this @ callback @ "( %building, %name, %vurl );";
    !((%this SPC callback $= ""));
    log("network", "debug", "About to eval callback: " @ %command);
    eval(%command);
    %result = %this.getValue("items0.validationResults");
    %command = %this @ callbackFail @ "( %result );";
    !((!((%this SPC callbackFail $= "")) SPC %result $= ""));
    %command = %this @ callbackFail @ "( \"error\" );";
    eval(%command);
    %this.schedule(0, "delete");
};
function PurchaseSpaceRequest::onError(%this, %unused, %errMsg) {
    log("network", "debug", "PurchaseSpaceRequest::onError: " @ %errMsg);
    %command = %this @ callbackFail @ "( %status );";
    !((%this SPC callbackFail $= ""));
    eval(%command);
    %this.schedule(0, "delete");
};
function getCustomSpacePurchaseInfo(%space, %callback) {
    className = ManagerRequest @ new ""() @ "CustomSpacePurchaseInfo";
    0;
    %request = ;
    %request.add();
    callback = MissionCleanup @ %callback @ %request;
    isObject();
    space = MissionCleanup @ %space @ %request;
    %url = %space @ urlEncode(floorPlanName);
    $Net::ClientServiceURL @ "/GetCustomSpacePurchaseInfo?" @ "user=" @ urlEncode($Player::Name) @ "&" @ "token=" @ urlEncode($Token) @ "&" @ "building=" @ %space @ buildingInfo @ urlEncode(name) @ "&" @ "floorPlan=";
    log("network", "debug", "PurchaseSpace: " @ %url);
    %request.setURL(%url);
    %request.start();
};
function CustomSpacePurchaseInfo::onDone(%this) {
    %status = findRequestStatus(%this);
    %statusMsg = %this.getValue("statusMsg");
    !((%status $= "success"));
    handleSystemMessage("msgInfoMessage", "" @ %this @ blockText @ " unsuccessful.");
    return;
    %floorplan = floorplan;
    space;
    sku = %this @ %this.getValue("sku") @ %floorplan;
    minLevel = %this.getValue("minLevel") @ %floorplan;
    quantity = %this.getValue("quantity") @ %floorplan;
    priceVBux = %this.getValue("priceVBux") @ %floorplan;
    priceVPoints = %this.getValue("priceVPoints") @ %floorplan;
    tradeInValueVBux = %this.getValue("tradeInCreditVBux") @ %floorplan;
    tradeInValueVPoints = %this.getValue("tradeInCreditVPoints") @ %floorplan;
    expectedError = %this.getValue("expectedError") @ %floorplan;
    isUpgrade = 0.0 @ (%floorplan > tradeInValueVPoints) @ %floorplan;
    (%floorplan > tradeInValueVBux);
    %cmd = !((%this SPC callback $= "")) @ %this @ callback @ "(" @ %this @ space @ ");";
    0.0;
    eval(%cmd);
    %this.delete();
};
function CustomSpacePurchaseInfo::onError(%this, %unused, %errMsg) {
};
function csSelectLayout(%layoutToSelect) {
    commandToServer('CSSelectLayout', CustomSpaceClient::GetSpaceImIn(), %layoutToSelect);
};
function clientCmdCSLayoutSelected(%unused, %audioStream, %videoStream) {
    refreshActiveFurniture();
    -(1.0).SelectNuggetID();
    %envMgrVideoStr = %videoStream;
    "no-video";
    CustomSpaceSettings::saveSettings(CustomSpaceClient::GetSpaceImIn(), "", "", "", %audioStream, %envMgrVideoStr);
};
function csCopyLayoutFromTo(%from, %to) {
    error((%to == %from) @ getScopeName() @ "->being asked to copy current layout into itself! returning.");
    return;
    commandToServer('CSCopyLayoutFromTo', CustomSpaceClient::GetSpaceImIn(), %from, %to);
};
function clientCmdCSGotLayoutVitals(%infoStr) {
    %layoutNum = getField(%infoStr, 0);
    %infoStr.gotCopyTargetInfo();
};
function csGetLayoutVitals(%layoutNum) {
    commandToServer('CSGetLayoutVitals', CustomSpaceClient::GetSpaceImIn(), %layoutNum);
};
function csSaveMySpacePropertiesAsDefault() {
    commandToServer('CSSaveSpacePropertiesAsDefault', CustomSpaceClient::GetSpaceImIn());
};
function csSaveLayoutAsDefault(%layoutNum) {
    commandToServer('CSSaveLayoutAsDefault', CustomSpaceClient::GetSpaceImIn(), %layoutNum);
};
function csLoadMediaFavorites() {
    %mediafavorites = $Player::Name.getProperty("mediafavoritelist", $CSSpaceInfo @ videoStream);
    $CSSpaceInfo @ audioStream @ "\t";
    echo(gUserPropMgrClient @ "vside://radio/" @ "csLoadMediaFavorites - \"" @ %mediafavorites @ "\"");
    %mediafavorites.setMediaFavorites();
};
function csSaveMediaFavorites() {
    %mediafavorites = getMediaFavorites();
    CSMediaDisplay;
    $Player::Name.setProperty("mediafavoritelist", %mediafavorites);
};
function csRequestHotMedia() {
    className = ManagerRequest @ new ""() @ "GetUrlRatingListRequest";
    0;
    %request = ;
    %request.add();
    %url = MissionCleanup @ isObject() @ MissionCleanup @ $Net::ClientServiceURL @ "/GetUrlRatingList?" @ "user=" @ urlEncode($Player::Name) @ "&" @ "token=" @ urlEncode($Token) @ "&" @ "type=VIDEO" @ "&" @ "order=BY_SHOWS" @ "&" @ "first=0" @ "&" @ "count=" @ $CSMediaDisplay::DefaultFavoriteCount;
    log("network", "debug", "requesting 'hot' media");
    %request.setURL(%url);
    %request.start();
};
function GetUrlRatingListRequest::onDone(%this) {
    %status = findRequestStatus(%this);
    %this.onError(%this, 0, %status);
    return !((%status $= "success"));
    %mediaList = "";
    %count = %this.getValue("mediaCount");
    %idx = 0;
    %mediaURL = urlDecode(%this.getValue((%count < %idx) @ ($CSMediaDisplay::DefaultFavoriteCount < %idx) @ "media" @ %idx @ ".url"));
    %viewCount = %this.getValue("media" @ %idx @ ".viewCount");
    %showCount = %this.getValue("media" @ %idx @ ".showCount");
    %mediaInfo = %mediaURL @ " " @ %viewCount @ " " @ %showCount;
    (0.0 > %showCount);
    %mediaList = %mediaInfo;
    (%mediaList $= "");
    %mediaList = %mediaList @ "\t" @ %mediaInfo;
    %idx = (1.0 + %idx);
    %mediaList.setMediaHotlist();
    %this.schedule(0, "delete");
};
function GetUrlRatingListRequest::onError(%this, %unused, %errMsg) {
    log("network", "warn", "GetUrlRatingRequest::onError: " @ %errMsg);
    %this.schedule(0, "delete");
};
function csRequestMediaStatistics(%mediaURL) {
    className = ManagerRequest @ new ""() @ "GetUrlRatingRequest";
    0;
    %request = ;
    %request.add();
    %url = MissionCleanup @ isObject() @ MissionCleanup @ $Net::ClientServiceURL @ "/GetUrlRating?" @ "user=" @ urlEncode($Player::Name) @ "&" @ "token=" @ urlEncode($Token) @ "&" @ "url=" @ urlEncode(%mediaURL);
    log("network", "debug", "UrlRating: request rating for: " @ %mediaURL);
    mediaurl = %mediaURL @ %request;
    %request.setURL(%url);
    %request.start();
};
function GetUrlRatingRequest::onDone(%this) {
    %status = findRequestStatus(%this);
    %this.onError(%this, 0, %status);
    return !((%status $= "success"));
    %mediaURL = %this.getValue("url");
    %mediaviews = %this.getValue("viewCount");
    %mediaplays = %this.getValue("showCount");
    %mediaURL.setMediaStatistics(%mediaviews, %mediaplays);
    %this.schedule(0, "delete");
};
function GetUrlRatingRequest::onError(%this, %unused, %errMsg) {
    log("network", "warn", "GetUrlRatingRequest::onError: " @ %errMsg);
    mediaurl.clearMediaStatistics();
    %this.schedule(0, "delete");
};
function csRecordMediaShow(%mediaURL, %type) {
    className = ManagerRequest @ new ""() @ "RecordUrlShowRequest";
    0;
    %request = ;
    %request.add();
    %url = MissionCleanup @ isObject() @ MissionCleanup @ $Net::ClientServiceURL @ "/RecordUrlShow?" @ "user=" @ urlEncode($Player::Name) @ "&" @ "token=" @ urlEncode($Token) @ "&" @ "url=" @ urlEncode(%mediaURL) @ "&" @ "type=" @ %type;
    log("network", "debug", "ShowRequest: request rating for: " @ %mediaURL);
    mediaurl = %mediaURL @ %request;
    %request.setURL(%url);
    %request.start();
};
function RecordUrlShowRequest::onDone(%this) {
    %status = findRequestStatus(%this);
    %this.onError(%this, 0, %status);
    return !((%status $= "success"));
    %this.schedule(0, "delete");
};
function RecordUrlShowRequest::onError(%this, %unused, %errMsg) {
    log("network", "warn", "RecordUrlShowRequest::onError: " @ %errMsg);
    %this.schedule(0, "delete");
};
function csRecordMediaView(%mediaURL, %type) {
    className = ManagerRequest @ new ""() @ "RecordUrlViewRequest";
    0;
    %request = ;
    %request.add();
    %url = MissionCleanup @ isObject() @ MissionCleanup @ $Net::ClientServiceURL @ "/RecordUrlView?" @ "user=" @ urlEncode($Player::Name) @ "&" @ "token=" @ urlEncode($Token) @ "&" @ "url=" @ urlEncode(%mediaURL) @ "&" @ "type=" @ %type;
    log("network", "debug", "ViewRequest: request rating for: " @ %mediaURL);
    mediaurl = %mediaURL @ %request;
    %request.setURL(%url);
    %request.start();
};
function RecordUrlViewRequest::onDone(%this) {
    %status = findRequestStatus(%this);
    %this.onError(%this, 0, %status);
    return !((%status $= "success"));
    %this.schedule(0, "delete");
};
function RecordUrlViewRequest::onError(%this, %unused, %errMsg) {
    log("network", "warn", "RecordUrlViewRequest::onError: " @ %errMsg);
    %this.schedule(0, "delete");
};
