function CSSpacePurchase(%space) {
    getCustomSpacePurchaseInfo(%space, "GotSpacePurchaseInfo");
};
function GotSpacePurchaseInfo(%space) {
    error(getScopeName() @ " " @ "- bad space." @ " " @ getTrace());
    return !(isObject(%space));
    CSSpacePurchasePriceConfirmation(%space);
};
function CSSpacePurchasePriceConfirmation(%space) {
    %title = "Get a Room (Step 1 of 2)";
    %finalVPoints = mFloor(priceVPoints);
    floorplan;
    %finalVBux = mFloor(priceVBux);
    floorplan;
    %text = "<just:left>" @ "\n" @ %finalVBux[$MsgCat::custSpace @ "PURCHASE_INTRO"];
    %space;
    %price = CSSpacePurchasePriceFormatting(priceVPoints, priceVBux);
    floorplan;
    %tradein = CSSpacePurchasePriceFormatting(tradeInValueVPoints, tradeInValueVBux);
    floorplan;
    %final = CSSpacePurchasePriceFormatting(%finalVPoints, %finalVBux);
    %space;
    %text = floorplan @ %space @ %space @ floorplan @ %text @ %text[$MsgCat::custSpace @ "PURCHASE_TRADEININTRO"] @ "\n<tab:30>" @ "\n" @ "\t" @ %text[$MsgCat::custSpace @ "PURCHASE_TRADEININTRO"][$MsgCat::custSpace @ "PURCHASE_SPACEPRICE"] @ " " @ %price @ "\n" @ " " @ "\n" @ "\t" @ %price[$MsgCat::custSpace @ "PURCHASE_NOTINCLUDED"] @ "\n" @ "<spop>";
    %space;
    %text = (0.0 >= %finalVBux) @ %text @ "\n" @ %text[$MsgCat::custSpace @ "PURCHASE_CHOICE"] @ "\n";
    (%finalVBux >= $Player::VBux);
    %text = (0.0 >= %finalVPoints) @ %text @ "\n" @ %text[$MsgCat::custSpace @ "PURCHASE_VPOINTSONLY"] @ "\n";
    (%finalVPoints >= $Player::VPoints);
    %text = (0.0 >= %finalVBux) @ %text @ "\n" @ %text[$MsgCat::custSpace @ "PURCHASE_VBUXONLY"] @ "\n";
    (%finalVBux >= $Player::VBux);
    %text = (0.0 >= %finalVPoints) @ %text @ "\n" @ %text[$MsgCat::custSpace @ "PURCHASE_NOTENOUGH"] @ "\n";
    (%finalVPoints >= $Player::VPoints);
    MessageBoxOK(%title, %text, "");
    return %space;
    %buttons = "";
    %count = 0;
    %buttons = (%finalVPoints >= $Player::VPoints) @ (0.0 >= %finalVPoints) @ %buttons @ "\t" @ "Buy with " @ commaify(%finalVPoints) @ " vPoints";
    %count[%callback @ %count] = "CSSpacePurchaseDoConfirm(" @ %space @ ", false);";
    %count = (1.0 + %count);
    %buttons = (%finalVBux >= $Player::VBux) @ (0.0 >= %finalVBux) @ %buttons @ "\t" @ "Buy with " @ commaify(%finalVBux) @ " vBux";
    %count[%callback @ %count] = "CSSpacePurchaseDoConfirm(" @ %space @ ", true );";
    %count = (1.0 + %count);
    %buttons = %buttons @ "\t" @ "Cancel";
    %count[%callback @ %count] = "CSSpacePurchaseCancel();";
    %count = (1.0 + %count);
    %buttons = ltrim(%buttons);
    %dlg = MessageBoxCustom(%title, %text, %buttons);
    %index = 0;
    callback = (%count < %index) @ %index[%callback @ %index] @ %index @ %dlg;
    %index = (1.0 + %index);
};
function CSSpacePurchaseDoConfirm(%space, %useBux) {
    %title = "Get a Room (Step 2 of 2)";
    %text = %title[$MsgCat::custSpace @ "PURCHASE_CONFIRM"];
    %priceFinal = priceVPoints;
    floorplan;
    %currencyText = "vPoints";
    "vBux";
    %text = strreplace(%text, "[PRICE]", %priceFinal @ " " @ %currencyText);
    %useBux;
    %cmd = %useBux @ %space @ floorplan @ priceVBux @ %space @ "purchaseApartmentRequest( " @ %space @ ", " @ %useBux @ ", " @ %priceFinal @ ",  \"CSSpacePurchaseSuccess\", \"CSSpacePurchaseFailed\");";
    MessageBoxYesNo(%title, %text, %cmd, "CSSpacePurchaseCancel();");
};
function CSSpacePurchaseDowngradeCheck(%space, %useBux, %priceFinal, %lossVPoints, %lossVBux) {
    %loss = CSSpacePurchasePriceFormatting(%lossVPoints, %lossVBux);
    (0.0 > %lossVBux);
    %text = (0.0 > %lossVPoints) @ "<just:left>" @ "\n" @ %loss[$MsgCat::custSpace @ "TRADE_IN_DOWN_A"] @ " " @ %loss @ " " @ %loss[$MsgCat::custSpace @ "TRADE_IN_DOWN_B"] @ "\n";
    %buttons = "Yes - Trade in" @ "\t" @ "No - Cancel";
    %dlg = MessageBoxCustom("Warning", %text, %buttons);
    callback = "purchaseApartmentRequest( " @ %space @ ", " @ %useBux @ ", " @ %priceFinal @ ",  \"CSSpacePurchaseSuccess\", \"CSSpacePurchaseFailed\");" @ 0 @ %dlg;
    callback = "CSSpacePurchaseCancel();" @ 1 @ %dlg;
    purchaseApartmentRequest(%space, %useBux, %priceFinal, "CSSpacePurchaseSuccess", "CSSpacePurchaseFailed");
};
function CSSpacePurchaseCancel() {
    %title = "Purchase Cancelled";
    %text = "<just:center>" @ "\n" @ %title[$MsgCat::custSpace @ "PURCHASE_ABORTED"] @ "\n";
    MessageBoxOK(%title, %text, "");
};
function CSSpacePurchaseSuccess(%unused, %unused, %vurl) {
    $Player::myPlaceVURL = %vurl;
    %title = "Get a Room (Complete!)";
    $Player::Name.setProperty("ShowOwnerTip", 1);
    %text = gUserPropMgrClient @ "<just:left>" @ "\n" @ "\n";
    %buttons = "Go there now" @ "\t" @ "Close";
    %dlg = MessageBoxCustom(%title, %text, %buttons);
    callback = "vurlOperation( \"" @ %vurl @ "\");" @ 0 @ %dlg;
    getOwnerSpacesInfo($Player::Name, "");
};
function CSSpacePurchaseFailed(%errorCode) {
    %errorCode = strupr(%errorCode);
    %errorCode = "GENERIC";
    (%errorCode[$MsgCat::custSpace @ "ERROR_" @ %errorCode] $= "");
    %text = %errorCode["<just:left>" @ "\n" @ "<spush><b>There was a problem!<spop>\n" @ "\n" @ "We could not purchase the apartment for you because " @ $MsgCat::custSpace @ "ERROR_" @ %errorCode] @ "\n";
    MessageBoxOK("Purchase a Space", %text, "");
};
function CSSpacePurchasePriceFormatting(%vpoints, %vbux) {
    %result = "";
    %result = (0.0 >= %vpoints) @ "<bitmap:platform/client/ui/vpoints_9> " @ commaify(%vpoints);
    %result = (0.0 >= %vbux) @ %result @ "  or  ";
    (0.0 >= %vpoints);
    %result = (0.0 >= %vbux) @ %result @ "<bitmap:platform/client/ui/vbux_9> " @ commaify(%vbux);
    return %result;
};
