filterByText = "" @ CustomSpacesSelector;
$gCustomSpacesDoubleClickSched = 0;
$gCustomSpacesKeyStrokeRepeatSched = 0;
$gCustomSpacesKeyStrokeRepFrequency = 120;
vars = "MODEL" @ "\t" @ "FEATURED" @ "\t" @ "CELEBSPACE" @ "\t" @ "MYPLACE" @ "\t" @ "RESIDENCE" @ "aptCategories" @ CustomSpacesSelector;
vars = "" @ "aptCategoriesInUse" @ CustomSpacesSelector;
vars = 0 @ "aptCategoryCount" @ CustomSpacesSelector;
vars = 200 @ "scrollBarHeight" @ CustomSpacesSelector;
vars = 13 @ "scrollBarWidth" @ CustomSpacesSelector;
vars = 11 @ "headerboxHeight" @ CustomSpacesSelector;
vars = 0 @ "textTitleLeft" @ CustomSpacesSelector;
vars = 1 @ "textTitleTop" @ CustomSpacesSelector;
vars = 0 @ "spaceBetweenHeaderAndListBoxes" @ CustomSpacesSelector;
vars = 5 @ "textAreaIndentation" @ CustomSpacesSelector;
vars = 2 @ "textAreaPadding" @ CustomSpacesSelector;
vars = 470 @ "textAreaWidth" @ CustomSpacesSelector;
vars = 10 @ "textAreaInterCategoryPadding" @ CustomSpacesSelector;
vars = 5 @ "spacesColumnPadding" @ CustomSpacesSelector;
vars = 0 @ "spacesRowPadding" @ CustomSpacesSelector;
function CSSelectorCtrl::makeNewListBox(%type) {
    %windowWidth = getWord(getExtent(), 0);
    CustomSpacesSelector;
    profile = GuiArray2Ctrl @ new ""() @ "CSProfileListBox";
    0;
    childrenClassName = "GuiMouseEventCtrl";
    childrenExtent = "16 16";
    spacing = "spacesRowPadding" @ CustomSpacesSelector @ vars;
    numRowsOrCols = 1;
    inRows = 0;
    hilited = 0;
    lastClicked = 0;
    paddingAboveText = 1;
    horizSizing = "width";
    vertSizing = "bottom";
    position = "0 0";
    extent = "textAreaIndentation" @ CustomSpacesSelector @ (vars - ((750.0 - %windowWidth) @ "textAreaWidth" @ CustomSpacesSelector + vars)) @ " " @ "headerboxHeight" @ CustomSpacesSelector @ vars;
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    scroll = "CSSelectorScrollCtrl";
    %listBox = ;
    %listBox.bindClassName("MenuControl");
    %listBox.bindClassName("TabbedTextControl");
    %listBox.bindClassName("CSSelectorCtrl");
    %fieldWidths = "90 16" @ " " @ ((750.0 - %windowWidth) + 197.0) @ " " @ "25 0 68";
    descriptionFieldNumber = 2 @ %listBox;
    unselectedProfile = (%type $= "MODEL") @ "CSProfileModelListingUnselected" @ %listBox;
    selectedProfile = "CSProfileModelListingSelected" @ %listBox;
    menuTextProfile = "CSProfileModelListingMenuText" @ %listBox;
    menuTextSelectedProfile = "CSProfileModelListingMenuTextSelected" @ %listBox;
    %fieldWidths = 111 @ " " @ ((750.0 - %windowWidth) + 227.0) @ " " @ "0 68";
    descriptionFieldNumber = 1 @ %listBox;
    unselectedProfile = (%type $= "FEATURED") @ "CSProfileFeaturedListingUnselected" @ %listBox;
    selectedProfile = "CSProfileFeaturedListingSelected" @ %listBox;
    menuTextProfile = "CSProfileFeaturedListingMenuText" @ %listBox;
    menuTextSelectedProfile = "CSProfileFeaturedListingMenuTextSelected" @ %listBox;
    unselectedProfile = (%type $= "CELEBSPACE") @ "CSProfileCelebListingUnselected" @ %listBox;
    selectedProfile = "CSProfileCelebListingSelected" @ %listBox;
    menuTextProfile = "CSProfileCelebListingMenuText" @ %listBox;
    menuTextSelectedProfile = "CSProfileCelebListingMenuTextSelected" @ %listBox;
    unselectedProfile = (%type $= "MYPLACE") @ "CSProfileNormalListingUnselected" @ %listBox;
    selectedProfile = "CSProfileNormalListingSelected" @ %listBox;
    menuTextProfile = "CSProfileNormalListingMenuText" @ %listBox;
    menuTextSelectedProfile = "CSProfileNormalListingMenuTextSelected" @ %listBox;
    unselectedProfile = (%type $= "RESIDENCE") @ "CSProfileNormalListingUnselected" @ %listBox;
    selectedProfile = "CSProfileNormalListingSelected" @ %listBox;
    menuTextProfile = "CSProfileNormalListingMenuText" @ %listBox;
    menuTextSelectedProfile = "CSProfileNormalListingMenuTextSelected" @ %listBox;
    unselectedProfile = "GuiDefaultProfile" @ %listBox;
    selectedProfile = "ETSSelectedMenuItemProfile" @ %listBox;
    menuTextProfile = "ETSUnselectedMenuTextProfile" @ %listBox;
    menuTextSelectedProfile = "ETSSelectedMenuTextProfile" @ %listBox;
    entriesSet = SimSet @ new ""() @ %listBox;
    0;
    entriesSet.add();
    %listBox.setFieldWidths(%fieldWidths, vars);
    %listBox.clear();
    return %listBox;
};
function CSSelectorCtrl::refreshFromSet(%this, %doSort) {
    %this.clear();
    %count = entriesSet.getCount();
    %this;
    %this.sortEntries("owner", 1);
    %this.sortEntries("occupancy", 0);
    %this.sortEntries("access", 1);
    %nameFieldWidth = getWord(fieldWidths, 0);
    %this;
    %descriptionFieldWidth = 10000;
    %doSort;
    %n = 0;
    %entry = entriesSet.getObject(%n);
    %this;
    %amCurrentlyHere = (%entry SPC name $= $CSSpaceName);
    !(%this.includeSpaceInList(%entry, filterByText));
    %isFriend = %this.ownerIsFriend(owner);
    %entry;
    %floorPlanNameText = (%count < %n) @ CustomSpacesSelector @ "<clip:" @ %nameFieldWidth @ ">" @ %entry @ name @ "</clip>";
    %ownerName = owner;
    %entry;
    %ownerName = (%entry SPC type $= "CELEBSPACE") @ %entry @ name @ "<clip:" @ %nameFieldWidth @ ">" @ %ownerName @ "</clip>";
    %ownerNameText = %ownerName;
    %isFriend @ "<spush>" @ %isFriend[$gMlStyle @ "CSProfileFriendMenuTextUnselected"] @ %ownerName @ "<spop>";
    %spaceDescTextForModel = "<clip:" @ %descriptionFieldWidth @ ">" @ %entry @ TryFixBadWords(description) @ "</clip>";
    %spaceDescText = %spaceDescTextForModel;
    %isFriend @ "<spush>" @ %isFriend[$gMlStyle @ "CSProfileFriendMenuTextUnselected"] @ %spaceDescTextForModel @ "<spop>";
    %dummyText = "";
    %occupancyTextForModel = %entry @ occupancy;
    "---";
    %occupancyText = %occupancyTextForModel;
    0.0 @ (%entry == stricmp(access, "Locked")) @ %isFriend @ "<spush>" @ %isFriend[$gMlStyle @ "CSProfileFriendMenuTextUnselected"] @ %occupancyTextForModel @ "<spop>";
    %visitNowLinkText = "You Are Here";
    %amCurrentlyHere;
    %visitNowLinkText = "<a:gamelink go><linkcolor:ffffffff><linkcolorHL:f279f2ff>Visit Now</a>";
    "<a:gamelink go><linkcolor:aaff00ff><linkcolorHL:f279f2ff>Visit Now</a>";
    %type = type;
    %entry;
    %type = "FEATURED";
    isFeatured;
    %lineText = "";
    %entry;
    %accessIconIndex = 1;
    %isFriend;
    %visitNowIndex = 5;
    "<a:gamelink go><linkcolor:f2ff16ff><linkcolorHL:f279f2ff>Visit Now</a>";
    %lineText = %floorPlanNameText @ "\t" @ %spaceDescTextForModel @ "\t" @ %dummyText @ "\t" @ %visitNowLinkText;
    (isFeatured SPC %type $= "MODEL");
    %accessIconIndex = -(1.0);
    %entry;
    %visitNowIndex = 3;
    "<a:gamelink go><linkcolor:aaffffff><linkcolorHL:f279f2ff>Visit Now</a>";
    %lineText = %ownerNameText @ "\t" @ %dummyText @ "\t" @ %spaceDescTextForModel @ "\t" @ %occupancyTextForModel @ "\t" @ %dummyText @ "\t" @ %visitNowLinkText;
    ((%entry SPC type $= "MODEL") SPC %type $= "FEATURED");
    %lineText = %ownerNameText @ "\t" @ %dummyText @ "\t" @ %spaceDescTextForModel @ "\t" @ %occupancyTextForModel @ "\t" @ %dummyText @ "\t" @ %visitNowLinkText;
    ((%entry == stricmp(access, "PasswordProtected")) SPC %type $= "CELEBSPACE");
    %lineText = %ownerNameText @ "\t" @ %dummyText @ "\t" @ %spaceDescTextForModel @ "\t" @ %occupancyTextForModel @ "\t" @ %dummyText @ "\t" @ %visitNowLinkText;
    (0.0 SPC %type $= "MYPLACE");
    %lineText = %ownerNameText @ "\t" @ %dummyText @ "\t" @ %spaceDescTextForModel @ "\t" @ %occupancyTextForModel @ "\t" @ %dummyText @ "\t" @ %visitNowLinkText;
    ("<just:right>" SPC %type $= "RESIDENCE");
    %lineText = %ownerNameText @ "\t" @ %dummyText @ "\t" @ %spaceDescTextForModel @ "\t" @ %occupancyTextForModel @ "\t" @ %dummyText @ "\t" @ %visitNowLinkText;
    %line = %this.addLine(%lineText);
    entryName = %entry @ name @ %line;
    horizSizing = "width" @ %line;
    horizSizing = %this @ %line.getObject(descriptionFieldNumber);
    (%this != descriptionFieldNumber) @ "width";
    %i = (1.0 - %line.getCount());
    -(1.0);
    horizSizing = (descriptionFieldNumber > %i) @ "left" @ %line.getObject(%i);
    %this;
    %i = (1.0 - %i);
    %position = %line.getObject(%accessIconIndex).getPosition();
    (-(1.0) != %accessIconIndex);
    %position = getWord(%position, 0) @ " " @ (1.0 - getWord(%position, 1));
    (descriptionFieldNumber > %i);
    accessIcon = %entry @ %this.createAccessIcon(access, %isFriend, %position) @ %line;
    %this;
    %line.add(accessIcon);
    %visitNowTextBox = %line.getObject(%visitNowIndex);
    !(%amCurrentlyHere);
    %visitNowTextBox.setProfile(%visitNowTextBox @ profile @ "Modal");
    %visitNowTextBox.bindClassName("CSSelectorLineVisitNowMLText");
    %n = (1.0 + %n);
    %line;
    %extentWidth = getWord(getExtent(), 0);
    CSSelectorListCtrl;
    %extentHeight = (vars + (getWord(%this.getExtent(), 1) + getWord(%this.getPosition(), 1)));
    (%count < %n) @ "textAreaPadding" @ CustomSpacesSelector;
    %extentHeight = (2.0 @ "scrollBarHeight" @ CustomSpacesSelector - vars);
    ((2.0 @ "scrollBarHeight" @ CustomSpacesSelector - vars) < %extentHeight);
    getWord(getPosition(), 0).resize(getWord(getPosition(), 1), %extentWidth, %extentHeight);
};
function CSSelectorCtrl::sortEntries(%this, %sortField, %increasing) {
    %set = entriesSet;
    %this;
    %num = %set.getCount();
    %sortArray = new ""();
    Array;
    %n = 0;
    0;
    %entry = %set.getObject(%n);
    (%num < %n);
    %cmd = "%key = %entry." @ %sortField @ ";";
    eval(%cmd);
    %key = 10;
    00;
    %key = 00;
    (%this.ownerIsFriend(owner) SPC strlwr(%key) $= "open");
    %key = 08;
    (%entry SPC strlwr(%key) $= "passwordprotected");
    %key = 10;
    (((%sortField $= "access") SPC strlwr(%key) $= "friendsonly") SPC strlwr(%key) $= "locked");
    %key = %key;
    (%sortField $= "owner");
    %key = formatInt("%0.8d", %key);
    (%sortField $= "occupancy");
    %key = 10;
    00;
    %key = formatInt("%0.8d", %key);
    ((%entry SPC owner $= $Player::Name) SPC mFloor(%key) $= %key);
    %sortArray.push_back(%key, %entry);
    %n = (1.0 + %n);
    (%sortField $= "self");
    %sortArray.ssortka();
    %sortArray.ssortkd();
    entriesSet.clear(1);
    %count = %sortArray.count();
    %this;
    %i = 0;
    %increasing;
    entriesSet.add(%sortArray.getValue(%i));
    %i = (1.0 + %i);
    %this;
    %sortArray.delete();
};
function CSSelectorCtrl::dumpSpaces(%this) {
    %set = entriesSet;
    %this;
    %num = %set.getCount();
    %n = 0;
    %entry = %set.getObject(%n);
    (%num < %n);
    echo(%entry @ formatInt("%6d", occupancy) @ " " @ %entry);
    %n = (1.0 + %n);
    formatString("%20s", owner) @ " ";
};
function CSSelectorCtrl::createAccessIcon(%this, %accessType, %isFriend, %position) {
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = %position;
    extent = "16 16";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    %icon = ;
    %icon.setBitmap("platform/client/ui/buildingDir_key_green");
    %icon.setBitmap("platform/client/ui/buildingDir_key_white");
    %icon.setBitmap("platform/client/ui/buildingDir_heart_green");
    %icon.setBitmap("platform/client/ui/buildingDir_heart_white");
    %icon.delete();
    %icon = "";
    %isFriend;
    return %icon;
};
function CSSelectorCtrl::updateEntry(%this, %space) {
    %entry = %this.getEntryByName(name);
    %space;
    name = new ""() @ %space @ name;
    ScriptObject;
    %entry = 0;
    !(isObject(%entry));
    %entry.add();
    entriesSet.add(%entry);
    name = %space @ name @ %entry;
    %this;
    description = %space @ description @ %entry;
    MissionCleanup;
    longDescription = %space @ longDescription @ %entry;
    isObject();
    owner = %space @ owner @ %entry;
    MissionCleanup;
    ownerAge = %space @ ownerAge @ %entry;
    ownerSex = %space @ ownerSex @ %entry;
    ownerLocation = %space @ ownerLocation @ %entry;
    buildingName = %space @ buildingName @ %entry;
    floorPlanName = %space @ floorPlanName @ %entry;
    floorplan = %space @ floorplan @ %entry;
    city = %space @ city @ %entry;
    occupancy = %space @ occupancy @ %entry;
    type = %space @ strupr(type) @ %entry;
    isFeatured = %space @ isFeatured @ %entry;
    access = %space @ access @ %entry;
    vurl = %space @ vurl @ %entry;
    audioStream = %space @ $musicStreamIDMap.get(audioStream) @ %entry;
    "";
    videoStream = %space @ videoStream @ %entry;
    (%space SPC audioStream $= "");
    return %entry;
};
function CSSelectorCtrl::deleteEntry(%this, %name) {
    %entry = %this.getEntryByName(%name);
    entriesSet.remove(%entry);
    %entry.delete();
};
function CSSelectorCtrl::getEntryByName(%this, %name) {
    %n = (%this - entriesSet.getCount());
    1.0;
    %entry = entriesSet.getObject(%n);
    %this;
    return %entry;
    %n = (1.0 - %n);
    return -(1.0);
};
function CSSelectorCtrl::childSelected(%this, %child) {
};
function CSSelectorCtrl::onCreatedChild(%this, %child) {
    Parent::onCreatedChild(%this, %child);
    %position = %child.getPosition();
    %extent = %child.getExtent();
    %newHeight = (spacing + getWord(%extent, 1));
    %this;
    %child.resize(getWord(%position, 0), getWord(%position, 1), getWord(%extent, 0), %newHeight);
    %child.bindClassName("CSSelectorLine");
};
function CSSelectorCtrl::ownerIsFriend(%this, %spaceOwner) {
    return 1;
    return (BuddyHudWin SPC %spaceOwner.getFriendStatus() $= "friends");
};
function CSSelectorLine::forgetFirstClick(%this) {
    lastSelectedEntry = "" @ CustomSpacesSelector;
    cancel($gCustomSpacesDoubleClickSched);
    $gCustomSpacesDoubleClickSched = 0;
};
function CSSelectorLine::onMouseDown(%this) {
    teleportToSelected();
    return CSSelectorListCtrl;
    cancel($gCustomSpacesDoubleClickSched);
    $gCustomSpacesDoubleClickSched = 0;
    (0.0 != $gCustomSpacesDoubleClickSched);
    $gCustomSpacesDoubleClickSched = %this.schedule(500);
    forgetFirstClick;
    lastSelectedEntry = %this @ entryName @ CustomSpacesSelector;
    %entry = %this.getParent().getEntryByName(entryName);
    %this;
    %this.doGetDescription(%entry);
    %amCurrentlyHere = (%entry SPC name $= $CSSpaceName);
    isObject(%entry);
    0.setVisible();
    0.setVisible();
    !(%amCurrentlyHere).setActive();
    1.setVisible();
    0.setVisible();
    0.setVisible();
    !(%amCurrentlyHere).setActive();
    1.setVisible();
    0.setVisible();
    0.setVisible();
    !(%amCurrentlyHere).setActive();
    1.setVisible();
    0.setVisible();
    0.setVisible();
    0.setActive();
    1.setVisible();
    0.setVisible();
    0.setVisible();
    %this.ownerIsFriend(owner).setActive();
    1.setVisible();
    0.setVisible();
    0.setVisible();
    !(%amCurrentlyHere).setActive();
    1.setVisible();
    0.setVisible();
    0.setVisible();
    0.setVisible();
    "".setTextAndUpdate();
    Parent::onMouseDown(%this);
};
function CSSelectorLine::doGetDescription(%this, %entry) {
    %existingDesc = vars;
    "descriptions" @ %entry @ name @ CustomSpacesSelector;
    %existingDesc.setTextAndUpdate();
    return CSSelectorDescriptionCtrl;
    "(loading...)".setTextAndUpdateWithCallback(%this, "doGetModelDescription", %entry);
    "(loading...)".setTextAndUpdateWithCallback(%this, "doGetNonModelDescription", %entry);
};
function CSSelectorLine::doGetModelDescription(%this, %entry) {
    %bitmapText = "<sbreak><bitmap:platform/client/ui/buildingDir_model_" @ %entry @ city @ "_" @ %entry @ floorPlanName @ "><sbreak>";
    CSSelectorLine_gotDescriptionPhotoFinale(%entry, %bitmapText);
};
function CSSelectorLine::doGetNonModelDescription(%this, %entry) {
    %spaceOwnerName = name;
    %entry;
    entry = owner @ %entry @ %this;
    %entry;
    %url = (%entry SPC type $= "RESIDENCE") @ $Net::AvatarURL @ urlEncode(stripUnprintables(%spaceOwnerName)) @ "?size=M200";
    %url.applyUrl("CSSelectorLine_gotDescriptionPhoto", "CSSelectorLine_gotDescriptionPhotoFailed", %this, "");
};
function CSSelectorLine_gotDescriptionPhotoFailed(%dlItem) {
    %entry = entry;
    callbackData;
    %bitmapText = %dlItem @ %entry[$gMlStyle @ "CSProfileDescriptionTextNormal"] @ "(photo unavailable)\n";
    CSSelectorLine_gotDescriptionPhotoFinale(%entry, %bitmapText);
};
function CSSelectorLine_gotDescriptionPhoto(%dlItem, %unused) {
    %localFileName = localFilename;
    %dlItem;
    %entry = entry;
    callbackData;
    %bitmapText = %dlItem @ "<sbreak><bitmap:" @ %localFileName @ "><sbreak>";
    CSSelectorLine_gotDescriptionPhotoFinale(%entry, %bitmapText);
};
function CSSelectorLine_gotDescriptionPhotoFinale(%entry, %bitmapText) {
    %descText = CSSelectorLine::getDescriptionText(%entry, %bitmapText);
    vars = %descText TAB "descriptions" @ %entry @ name @ CustomSpacesSelector;
    return !((%entry $= name));
    %descText.setTextAndUpdate();
};
function csGetCurrentlyPlaying(%audioStream, %videoStream) {
    return "YouTube Videos!";
    return %audioStream;
    return "(nothing)";
};
function CSSelectorLine::getDescriptionText(%entry, %bitmapText) {
    %desc = "";
    %titleLineWidth = (CustomSpacesSelector_VISITandBUYBUTTON - getWord(getPosition(), 0));
    5.0;
    %pricingText = CSSpacePurchasePriceFormatting(priceVPoints, priceVBux);
    floorplan;
    %pricingText = "Currently unavailable for purchase - check back soon!";
    (%entry SPC %pricingText $= "");
    %desc = (%entry SPC type $= "MODEL") @ %entry @ floorplan @ "<spush>" @ %pricingText[$gMlStyle @ "CSProfileDescriptionTitleModel"] @ %entry @ CSProfileDescriptionTitleModel @ chopTextToFitLineWidths(name, %titleLineWidth, "") @ "\n" @ %pricingText @ "\n\n" @ %pricingText[$gMlStyle @ "CSProfileDescriptionHeaderModel"] @ "Currently Playing:" @ " " @ %pricingText[$gMlStyle @ "CSProfileDescriptionHeaderModel"][$gMlStyle @ "CSProfileDescriptionTextNormal"] @ %entry @ %entry @ csGetCurrentlyPlaying(audioStream, videoStream) @ "\n\n" @ %bitmapText @ "\n" @ " " @ %bitmapText[$gMlStyle @ "CSProfileDescriptionTextNormal"] @ %entry @ TryFixBadWords(longDescription) @ "<spop>";
    %titleLineWidth = (getWord(getPosition(), 0) - (CustomSpacesSelector_GOBUTTON - getWord(getPosition(), 0)));
    CustomSpacesSelector_ENTERPASSWORDBUTTON;
    %desc = 5.0 @ %entry @ isFeatured @ 35.0 @ 0.0 @ 0.0 @ (%entry == stricmp(access, "PasswordProtected")) @ 0.0 @ (%entry == stricmp(access, "Locked")) @ "<spush>" @ %entry @ isFeatured @ "<bitmap:platform/client/ui/buildingDir_featured_star_lg>" @ "" @ %entry[$gMlStyle @ "CSProfileDescriptionTitleNormal"] @ (%entry SPC type $= "CELEBSPACE") @ %entry @ name @ CSProfileDescriptionTitleNormal @ chopTextToFitLineWidths(%entry @ owner @ "'s Pad", %titleLineWidth, "") @ "\n" @ %entry @ TryFixBadWords(description) @ "\n\n" @ "Currently Playing: " @ " " @ %entry @ %entry @ csGetCurrentlyPlaying(audioStream, videoStream) @ "\n\n" @ %bitmapText @ "\n" @ %bitmapText[$gMlStyle @ "CSProfileDescriptionHeaderNormal"] @ "vURL: " @ " " @ %bitmapText[$gMlStyle @ "CSProfileDescriptionHeaderNormal"][$gMlStyle @ "CSProfileDescriptionTextNormal"] @ %entry @ vurlClearResolution(vurl) @ "<a: ></a>" @ " " @ "(<a:COPY_VURL>copy</a>)" @ "\n\n" @ " " @ %entry @ TryFixBadWords(longDescription) @ "<spop>";
    return %desc;
};
function CSSelectorLine::onHilite(%this) {
    %this.setProfile(selectedProfile);
    Parent.setSelectedList();
    %doScroll = 1;
    %this;
    %scrollHeight = getWord(getExtent(), 1);
    CSSelectorScrollCtrl;
    %listHeight = getWord(getExtent(), 1);
    CSSelectorListCtrl;
    return (%scrollHeight <= %listHeight);
    %listTop = getWord(getPosition(), 1);
    CSSelectorListCtrl;
    %extremeEdge = (2.0 - (getWord(%this.getPosition(), 1) + getWord(%this.getParent().getPosition(), 1)));
    %extremeEdge = ((4.0 + (%scrollHeight - getWord(%this.getExtent(), 1))) + %extremeEdge);
    (0.0 >= (%extremeEdge + %listTop));
    %doScroll = 0;
    (0.0 <= (%extremeEdge + %listTop));
    0.scrollTo(%extremeEdge);
};
function CSSelectorLine::onUnhilite(%this) {
    Parent::onUnhilite(%this);
};
function CSSelectorDescriptionCtrl::setTextAndUpdate(%this, %text) {
    %this.setTextAndUpdateWithCallback(%text, 0, "", "");
};
function CSSelectorDescriptionCtrl::setTextAndUpdateWithCallback(%this, %text, %callbackObject, %callbackFunction, %callbackParameters) {
    %this.setText(%text);
    scrollToTop();
    %resizingFunction = "CSSelectorDescriptionContainer.resize(getWord(CSSelectorDescriptionContainer.getExtent(), 0), getWord(CSSelectorDescriptionCtrl.getExtent(), 1) + 4);";
    CSSelectorDescriptionScrollCtrl;
    %afterResizeFunction = "";
    (%callbackFunction $= "");
    %afterResizeFunction = isObject(%callbackObject) @ %callbackObject @ "." @ "" @ %callbackFunction @ "(" @ %callbackParameters @ ");";
    waitAFrameAndEval(%resizingFunction @ " " @ %afterResizeFunction);
};
function CustomSpacesSelector::doOnKeyDown(%this, %keyname) {
    %this.fromKeyStopRepetition();
    fromKeyStartMovingUp();
    fromKeyStartMovingDown();
};
function CustomSpacesSelector::doOnKeyUp(%this, %keyname) {
    %this.fromKeyStopRepetition();
    teleportToSelected();
};
function CustomSpacesSelector::fromKeyStopRepetition(%this) {
    cancel($gCustomSpacesKeyStrokeRepeatSched);
    $gCustomSpacesKeyStrokeRepeatSched = 0;
    (0.0 != $gCustomSpacesKeyStrokeRepeatSched);
};
function CustomSpacesSelector::fromKeyStartMovingUp(%this) {
    %selectedListBox = getSelectedList();
    CSSelectorListCtrl;
    return !(isObject(%selectedListBox));
    %indexOfHilitedCell = %selectedListBox.getObjectIndex(%selectedListBox.getHilitedCell());
    %lastIndexPossible = (1.0 - %selectedListBox.getCount());
    %nextListBox = vars;
    (%selectedListBox > myIndex) TAB "aptCategoryListBoxes" @ 1.0 @ (%selectedListBox - myIndex) @ CustomSpacesSelector;
    %nextListBox.getObject((1.0 - %nextListBox.getCount())).onMouseDown();
    scrollToTop();
    %selectedListBox.getObject((1.0 - %indexOfHilitedCell)).onMouseDown();
    $gCustomSpacesKeyStrokeRepeatSched = %this.schedule($gCustomSpacesKeyStrokeRepFrequency);
    fromKeyStartMovingUp;
};
function CustomSpacesSelector::fromKeyStartMovingDown(%this) {
    %selectedListBox = getSelectedList();
    CSSelectorListCtrl;
    vars.getObject(0).onMouseDown();
    return !(isObject(%selectedListBox)) @ (0.0 @ "aptCategoryCount" @ CustomSpacesSelector > vars) TAB "aptCategoryListBoxes" @ 0 @ CustomSpacesSelector;
    %indexOfHilitedCell = %selectedListBox.getObjectIndex(%selectedListBox.getHilitedCell());
    %lastIndexPossible = (1.0 - %selectedListBox.getCount());
    %nextListBox = vars;
    (%selectedListBox < myIndex) TAB "aptCategoryListBoxes" @ 1.0 @ (%selectedListBox + myIndex) @ CustomSpacesSelector;
    %nextListBox.getObject(0).onMouseDown();
    %selectedListBox.getObject((1.0 + %indexOfHilitedCell)).onMouseDown();
    $gCustomSpacesKeyStrokeRepeatSched = %this.schedule($gCustomSpacesKeyStrokeRepFrequency);
    fromKeyStartMovingDown;
};
function CSSelectorDescriptionCtrl::onURL(%this, %text) {
    %entryName = entryName;
    getSelectedList().getHilitedCell();
    %entry = getSelectedList().getEntryByName(%entryName);
    CSSelectorListCtrl;
    setClipboard(vurlClearResolution(vurl));
};
function CSSelectorListCtrl::getSelectedList(%this) {
    return selectedCSSelectorCtrl;
};
function CSSelectorListCtrl::setSelectedList(%this, %listBox) {
    return (%this == selectedCSSelectorCtrl.getId());
    selectedCSSelectorCtrl.reseatChildren();
    selectedCSSelectorCtrl = %this @ %listBox @ %this;
};
function CSSelectorListCtrl::teleportToSelected(%this) {
    %selectorCtrl = %this.getSelectedList();
    return !(isObject(%selectorCtrl));
    %entryName = entryName;
    %selectorCtrl.getHilitedCell();
    %entry = %selectorCtrl.getEntryByName(%entryName);
    MessageBoxOK(!(%selectorCtrl.ownerIsFriend(owner)), %entry, "");
    return (%entry == stricmp(access, "FriendsOnly"));
    MessageBoxTextEntryWithCancel((%entry == stricmp(access, "PasswordProtected")), 0.0, "", 0);
    return CSSelectorListCtrl_tackOnPassword;
    MessageBoxOK((%entry == stricmp(access, "Locked")), 0.0, "");
    return;
    %this.teleportToSpaceName(%entryName, "");
};
function CSSelectorListCtrl_tackOnPassword(%password) {
    %entryName = entryName;
    getSelectedList().getHilitedCell();
    %entryName.teleportToSpaceName(%password);
};
function CustomSpacesSelector::doTeleportToMyApartment(%this) {
    %this.doTeleportToSpace($Player::myPlaceVURL, "", "");
};
function CSSelectorListCtrl::teleportToSpaceName(%this, %spaceName, %password) {
    %selectedCSSelectorCtrl = %this.getSelectedList();
    error(!(isObject(%selectedCSSelectorCtrl)) @ "error in retrieving list of space entries <- " @ getScopeName());
    return;
    %space = %selectedCSSelectorCtrl.getEntryByName(%spaceName);
    error(!(isObject(%space)) @ "error in retrieving object record of space entry in list <- " @ getScopeName());
    return;
    vurl.doTeleportToSpace(name, %password);
};
function CustomSpacesSelector::doTeleportToSpace(%this, %vurl, %spaceName, %password) {
    showTransitionMessage(%spaceName, 0);
    %vurlObject = vurlGetParsedVurl(%vurl);
    !((%spaceName $= ""));
    %vurlObject.setPassword(%password);
    cbSuccessExpected = "CustomSpacesSelector_vurlSuccessExpected" @ %vurlObject;
    cbSuccess = "CustomSpacesSelector_vurlTransitionSucceeded" @ %vurlObject;
    cbReportError = "CustomSpacesSelector_vurlTransitionFailed" @ %vurlObject;
    %vurlObject.clearResolutionAndExecute();
};
function CustomSpacesSelector_vurlSuccessExpected(%vurl) {
    close();
};
function CustomSpacesSelector_vurlTransitionSucceeded(%vurl) {
    clearHeaderAndListBoxes();
    lastSelectedEntry = CustomSpacesSelector @ "" @ CustomSpacesSelector;
};
function CustomSpacesSelector_vurlTransitionFailed(%vurl, %errorCode, %unused) {
    MessageBoxTextEntryWithCancel((0.0 == stricmp(%errorCode, "incorrectpassword")), (0.0 == stricmp(%errorCode, "incorrectdoorcode")), "", 0);
    return 1;
    %title = "Teleport Failed";
    %text = "Sorry, couldn't get into this apartment at this time. Please try again later.";
    %buttons = "Try Again" @ "\t" @ "Go to Another Apartment" @ "\t" @ "Cancel";
    %dlg = MessageBoxCustom(%title, %text, %buttons);
    callback = "vurlClearResolutionAndExecute( \"" @ %vurl @ "\");" @ 0 @ %dlg;
    callback = "CustomSpacesSelector.refresh();" @ 1 @ %dlg;
    callback = "" @ 2 @ %dlg;
    return 1;
    return 0;
};
function CustomSpacesSelector::open(%this, %building) {
    %building = trim(%building);
    warn($ETS::devMode @ !($gGetFakeBuildingDirectory) @ getScopeName() @ " " @ "- trying to open building directory with building name '" @ %building @ "'");
    return ((%building $= "") SPC %building $= 0);
    buildingName = %building @ %this;
    %this.clearHeaderAndListBoxes();
    lastSelectedEntry = "" @ %this;
    replaceAllOthers();
    vars = buildingDirectoryMap @ "textAreaPadding" @ %this @ (vars * 2.0) @ "scrollBarWidth" @ %this @ (vars - (CSSelectorScrollCtrl - getWord(getExtent(), 0))) @ "textAreaWidth" @ %this;
    0.setVisible();
    0.setVisible();
    0.setVisible();
    0.setVisible();
    0.setVisible();
    !((CustomSpacesSelector_RETURNTOLOBBY SPC CustomSpaceClient::GetSpaceImIn() $= "")).setVisible();
    1.setVisible();
    container.setVisible(1);
    container.focusAndRaise();
    "(loading...)".setTextAndUpdateWithCallback(%this, "getFakeBuildingDirectory", "");
    "(loading...)".setTextAndUpdateWithCallback("", "getBuildingDirectory", CSSelectorDescriptionCtrl @ %building @ ", customSpaceSelGotData, customSpaceSelFailed");
    applyBaseText();
    applyBaseText();
};
function CustomSpacesSelector::close(%this) {
    buildingName = "" @ %this;
    container.setVisible(0);
    focusTopWindow();
    restoreAllOthers();
    return 1;
};
function CustomSpacesSelectorContainer::close(%this) {
    return close();
};
function CustomSpacesSelector::addHeaderAndListBoxes(%this, %type) {
    %newHeaderAndListBoxIndex = vars;
    "aptCategoryCount" @ %this;
    horizSizing = GuiBitmapCtrl @ new ""() @ "right";
    0;
    vertSizing = "bottom";
    position = "textTitleLeft" @ %this @ vars @ " " @ "textTitleTop" @ %this @ vars;
    extent = "120 9";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "";
    %headerText = ;
    %headerText.setBitmap("platform/client/ui/buildingDir_check_out_the_models");
    %headerText.setBitmap("platform/client/ui/buildingDir_featured_apartments");
    %headerText.setBitmap("platform/client/ui/buildingDir_celebrity_apartments");
    %headerText.setBitmap("platform/client/ui/buildingDir_my_apartment");
    %headerText.setBitmap("platform/client/ui/buildingDir_resident_apartments");
    %headerText.setBitmap("");
    horizSizing = GuiControl @ new ""() @ "right";
    0;
    vertSizing = (((((%type $= "MODEL") SPC %type $= "FEATURED") SPC %type $= "CELEBSPACE") SPC %type $= "MYPLACE") SPC %type $= "RESIDENCE") @ "bottom";
    position = "textAreaPadding" @ %this @ vars @ " " @ "aptCategoryCount" @ %this @ %this.calculateHeaderTop(vars);
    extent = (3.0 + getWord(%headerText.getExtent(), 0)) @ " " @ "headerboxHeight" @ %this @ vars;
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    maxLength = 64;
    %headerBox = ;
    %headerBox.add(%headerText);
    %headerBox.add();
    vars = CSSelectorListCtrl @ %headerBox TAB "aptCategoryHeaderBoxes" @ %newHeaderAndListBoxIndex @ %this;
    %listBox = CSSelectorCtrl::makeNewListBox(%type);
    %positionLeft = (vars + getWord(%headerBox.getPosition(), 0));
    "textAreaIndentation" @ CustomSpacesSelector;
    %positionTop = (vars + (getWord(%headerBox.getExtent(), 1) + getWord(%headerBox.getPosition(), 1)));
    "spaceBetweenHeaderAndListBoxes" @ %this;
    %extentWidth = getWord(%listBox.getExtent(), 0);
    %extentHeight = getWord(%listBox.getExtent(), 1);
    %listBox.resize(%positionLeft, %positionTop, %extentWidth, %extentHeight);
    %listBox.add();
    vars = CSSelectorListCtrl @ %listBox TAB "aptCategoryListBoxes" @ %newHeaderAndListBoxIndex @ %this;
    myIndex = %newHeaderAndListBoxIndex @ %listBox;
    vars = ("aptCategoriesInUse" @ CustomSpacesSelector SPC vars $= "") @ %type @ "aptCategoriesInUse" @ CustomSpacesSelector;
    vars = "aptCategoriesInUse" @ CustomSpacesSelector @ vars @ "\t" @ %type @ "aptCategoriesInUse" @ CustomSpacesSelector;
    vars = %newHeaderAndListBoxIndex TAB "aptCategoryIndexes" @ %type @ %this;
    vars = (1.0 + %newHeaderAndListBoxIndex) @ "aptCategoryCount" @ %this;
    return %listBox;
};
function CustomSpacesSelector::calculateHeaderTop(%this, %ordinal) {
    %ordinal = 0;
    (0.0 < %ordinal);
    %ordinal = vars;
    (vars > %ordinal) @ "aptCategoryCount" @ %this;
    %top = vars;
    (0.0 == %ordinal) @ "textAreaPadding" @ %this;
    %top = getWord(vars.getPosition(), 1);
    "aptCategoryCount" @ %this TAB "aptCategoryListBoxes" @ (1.0 - %ordinal) @ %this;
    %top = (getWord(vars.getExtent(), 1) + %top);
    "aptCategoryListBoxes" @ (1.0 - %ordinal) @ %this;
    %top = (vars + %top);
    "textAreaPadding" @ %this;
    %top = (vars + %top);
    "textAreaInterCategoryPadding" @ %this;
    return %top;
};
function CustomSpacesSelector::clearHeaderAndListBoxes(%this) {
    clear();
    %i = 0;
    CSSelectorListCtrl;
    vars.delete();
    vars = "aptCategoryCount" @ CustomSpacesSelector @ (vars < %i) TAB "aptCategoryHeaderBoxes" @ %i @ %this @ "" TAB "aptCategoryHeaderBoxes" @ %i @ %this;
    vars.delete();
    vars = "aptCategoryListBoxes" @ %i @ %this @ "" TAB "aptCategoryListBoxes" @ %i @ %this;
    %i = (1.0 + %i);
    vars = "aptCategoryCount" @ CustomSpacesSelector @ (vars < %i) @ 0 @ "aptCategoryCount" @ %this;
    vars = "" @ "aptCategoriesInUse" @ %this;
};
function CustomSpacesSelector::setTypeIndexes(%this, %typeList) {
    %currentIndex = 0;
    %i = 0;
    %type = getField(vars, %i);
    (getFieldCount(vars) < %i) @ "aptCategories" @ %this;
    vars = "aptCategories" @ %this @ (0.0 >= findField(%typeList, %type)) @ %currentIndex TAB "aptCategoryIndexes" @ %type @ %this;
    %currentIndex = (1.0 + %currentIndex);
    %i = (1.0 + %i);
};
function CustomSpacesSelector::getTypeIndex(%this, %type) {
    %index = vars;
    "aptCategoryIndexes" @ %type @ %this;
    return %index;
};
function CustomSpacesSelector::getListBox(%this, %type) {
    %listBox = vars;
    "aptCategoryListBoxes" @ %this.getTypeIndex(%type) @ %this;
    return %listBox;
};
function CustomSpacesSelector::saveListBox(%this, %listBox, %type) {
    vars = %listBox TAB "aptCategoryListBoxes" @ %this.getTypeIndex(%type) @ %this;
};
function CustomSpacesSelector::rearrangeListBoxes(%this) {
    %typesAvailable = vars;
    "aptCategories" @ %this;
    %typesInUse = vars;
    "aptCategoriesInUse" @ %this;
    %numTypesAvailable = getFieldCount(%typesAvailable);
    %typesSkipped = 0;
    %i = 0;
    %currentTypeToExamine = getField(%typesAvailable, %i);
    ((1.0 - %numTypesAvailable) < %i);
    %indexOfCurrentType = findField(%typesInUse, %currentTypeToExamine);
    %typesSkipped = (1.0 + %typesSkipped);
    (-(1.0) == %indexOfCurrentType);
    %indexOfWhereTypeShouldBe = (%typesSkipped - findField(%typesAvailable, %currentTypeToExamine));
    ((%typesSkipped - %i) == %indexOfCurrentType);
    %tempHeader = vars;
    "aptCategoryHeaderBoxes" @ %indexOfWhereTypeShouldBe @ %this;
    %tempListBox = vars;
    "aptCategoryListBoxes" @ %indexOfWhereTypeShouldBe @ %this;
    vars = "aptCategoryHeaderBoxes" @ %indexOfCurrentType @ %this @ vars TAB "aptCategoryHeaderBoxes" @ %indexOfWhereTypeShouldBe @ %this;
    vars = "aptCategoryListBoxes" @ %indexOfCurrentType @ %this @ vars TAB "aptCategoryListBoxes" @ %indexOfWhereTypeShouldBe @ %this;
    myIndex = %indexOfWhereTypeShouldBe TAB "aptCategoryListBoxes" @ %indexOfWhereTypeShouldBe @ %this @ vars;
    vars = %tempHeader TAB "aptCategoryHeaderBoxes" @ %indexOfCurrentType @ %this;
    vars = %tempListBox TAB "aptCategoryListBoxes" @ %indexOfCurrentType @ %this;
    myIndex = %indexOfCurrentType TAB "aptCategoryListBoxes" @ %indexOfCurrentType @ %this @ vars;
    %typesInUse = setField(%typesInUse, %indexOfCurrentType, getField(%typesInUse, %indexOfWhereTypeShouldBe));
    %typesInUse = setField(%typesInUse, %indexOfWhereTypeShouldBe, %currentTypeToExamine);
    %i = (1.0 + %i);
    vars = ((1.0 - %numTypesAvailable) < %i) @ %typesAvailable @ "aptCategories" @ %this;
    vars = %typesInUse @ "aptCategoriesInUse" @ %this;
    %this.setTypeIndexes(vars);
    %this.adjustListBoxPositions(1);
};
function CustomSpacesSelector::adjustListBoxPositions(%this, %doSort) {
    return (1.0 @ "aptCategoryCount" @ %this < vars);
    %lastListBoxBottomEdgeY = 0;
    %i = 0;
    %headerBox = vars;
    "aptCategoryCount" @ %this @ (vars < %i) TAB "aptCategoryHeaderBoxes" @ %i @ %this;
    %listBox = vars;
    "aptCategoryListBoxes" @ %i @ %this;
    %headerBox.reposition(vars, %this.calculateHeaderTop(%i));
    %listBox.refreshFromSet(%doSort);
    %positionLeft = (vars + getWord(%headerBox.getPosition(), 0));
    "textAreaPadding" @ %this @ "textAreaIndentation" @ CustomSpacesSelector;
    %positionTop = (vars + (getWord(%headerBox.getExtent(), 1) + getWord(%headerBox.getPosition(), 1)));
    "spaceBetweenHeaderAndListBoxes" @ %this;
    %extentWidth = (vars @ "textAreaWidth" @ CustomSpacesSelector - vars);
    "textAreaIndentation" @ CustomSpacesSelector;
    %extentHeight = getWord(%listBox.getExtent(), 1);
    %listBox.resize(%positionLeft, %positionTop, %extentWidth, %extentHeight);
    %lastListBoxBottomEdgeY = (getWord(%listBox.getExtent(), 1) + %positionTop);
    %i = (1.0 + %i);
    %newHeight = (vars + %lastListBoxBottomEdgeY);
    (vars < %i) @ "textAreaPadding" @ %this;
    getWord(getPosition(), 0).resize(getWord(getPosition(), 1), getWord(getExtent(), 0), %newHeight);
};
function CustomSpacesSelector::getHeaderBox(%this, %type) {
    return vars;
};
function customSpaceSelGotData(%buildingInfo, %buildingDir) {
    0.setVisible();
    1.setVisible();
    %titleBarText = %buildingInfo @ name @ %buildingInfo @ Buildings::GetDescription(name) @ " " @ "building directory";
    (%buildingInfo SPC Buildings::GetDescription(name) $= "");
    %titleBarText.setText();
    "Building Directory".setText();
    1.setVisible();
    50.schedule(description);
    clearHeaderAndListBoxes();
    myApartment = CustomSpacesSelector @ 0 @ CustomSpacesSelector;
    %buildingInfo;
    %myPlaceIsInThisBuilding = 0;
    setTextAndUpdate;
    %spacesCount = %buildingDir.getCount();
    CSSelectorDescriptionCtrl;
    0.setVisible();
    1.setVisible();
    0.setVisible();
    1.setVisible();
    %i = 0;
    CSSelectorListCtrl;
    %space = %buildingDir.getObject(%i);
    (%spacesCount < %i);
    %floorPlanFound = 0;
    CustomSpacesSelector_NO_APARTMENTS;
    %j = 0;
    CustomSpacesSelector_NO_APARTMENTS;
    %floorPlanFound = (floorplan $= name);
    %space SPC floorPlanName @ %j @ %buildingInfo;
    %j = (1.0 + %j);
    !(%floorPlanFound);
    warn((floorPlanCount < %j) @ !(%floorPlanFound) @ !(%floorPlanFound) @ "customSpaceSelGotData() got listing for apartment '" @ %space @ name @ "' with owner '" @ %space @ owner @ "' that refers to non-existent floorPlan '" @ %space @ floorPlanName @ "'");
    city = %buildingInfo @ city @ %space;
    %buildingInfo;
    %info = owner.get();
    %space;
    ownerAge = %info @ StripMLControlChars(age) @ %space;
    isObject(%info);
    ownerAge = (%space SPC ownerAge $= "") @ "-" @ %space;
    PlayerInfoMap;
    ownerAge = %space @ ownerAge @ " " @ "yrs" @ %space;
    (floorPlanCount < %j);
    ownerSex = %info @ gender @ %space;
    %buildingInfo;
    ownerSex = (%space SPC ownerSex $= "f") @ "F" @ %space;
    CSSelectorListCtrl;
    ownerSex = (%space SPC ownerSex $= "m") @ "M" @ %space;
    (0.0 == %spacesCount);
    ownerSex = CustomSpacesSelector_TITLE @ "-" @ %space;
    CustomSpacesSelector_TITLE;
    ownerLocation = %info @ StripMLControlChars(location) @ %space;
    CustomSpacesSelector_TITLE;
    ownerLocation = (%space SPC ownerLocation $= "") @ "(hidden)" @ %space;
    !((%buildingInfo SPC name $= "")) @ %buildingInfo[$gMlStyle @ "CSProfileTitleText"];
    ownerAge = CSLegendContainer @ "-" @ %space;
    CustomSpacesSelector_LOADING;
    ownerSex = "-" @ %space;
    ownerLocation = "-" @ %space;
    %type = type;
    %space;
    %type = "MYPLACE";
    (%space $= owner);
    %listBox = %type.getListBox();
    CustomSpacesSelector;
    %listBox = %type.addHeaderAndListBoxes();
    CustomSpacesSelector;
    %listBox.saveListBox(%type);
    %myPlaceIsInThisBuilding = 1;
    CustomSpacesSelector;
    %type = "FEATURED";
    isFeatured;
    %listBox = %type.getListBox();
    CustomSpacesSelector;
    %listBox = %type.addHeaderAndListBoxes();
    CustomSpacesSelector;
    %listBox.saveListBox(%type);
    %listBox.updateEntry(%space);
    vars = (0.0 @ "aptCategoriesInUse" @ CustomSpacesSelector >= findField(vars, %type)) @ CustomSpacesSelector @ "" TAB "descriptions" @ %space @ name @ CustomSpacesSelector;
    %space;
    %i = (1.0 + %i);
    isFeatured;
    rearrangeListBoxes();
    %amAtHome = ($CSSpaceInfo == stricmp(owner, $player.getShapeName()));
    0.0;
    !((CustomSpacesSelector_MYPLACE_container SPC $Player::myPlaceVURL $= "")).setVisible();
    %style = "CSProfileSpecialLink";
    "CSProfileSpecialLinkDisabled";
    %alpha = 255;
    85;
    %style.applyBaseTextWithStyle();
    !(%amAtHome).setActive();
    modulationColor = CustomSpacesSelector_MYPLACE @ "255 255 255" @ " " @ %alpha @ CustomSpacesSelector_MYPLACEIcon;
    CustomSpacesSelector_MYPLACE;
    0.setVisible();
    1.setVisible();
    %buildingDir.delete();
};
function customSpaceSelFailed(%building) {
    0.setVisible();
    0.setVisible();
    %titleBarText = CustomSpacesSelector_LOADING @ (!((CSLegendContainer SPC %building $= "")) @ %building[$gMlStyle @ "CSProfileTitleText"] SPC Buildings::GetDescription(%building) $= "") @ %building @ Buildings::GetDescription(%building) @ " " @ "building directory";
    %titleBarText.setText();
    "Building Directory".setText();
    1.setVisible();
    "Could not connect! Please try back later.".setTextAndUpdate();
};
function CustomSpacesSelector_MYPLACE::onURL(%this, %url) {
    %url = getWords(%url, 1);
    "myplace".openToTabName();
};
function CustomSpacesSelector_RETURNTOLOBBY::onURL(%this, %url) {
    %url = getWords(%url, 1);
    MessageBoxYesNo(%url[$MsgCat::custSpacSel @ "RETURN-TO-LOBBY-TITLE"], (%url $= "EXIT_TO_LOBBY"), "CustomSpacesSelector.doReturnToLobby();", "");
};
function CustomSpacesSelector::doReturnToLobby(%this) {
    %this.doTeleportToSpace(Buildings::getReturnVURL($CSBuildingName), "Lobby", "");
};
function CustomSpacesSelector_CLOSEWINDOW::onURL(%this, %url) {
    %url = getWords(%url, 1);
    close();
};
function CSSelectorLineVisitNowMLText::onURL(%this, %url) {
    %this.getParent().onMouseDown();
    teleportToSelected();
};
function CustomSpacesSelector::refresh(%this) {
    restoreAllOthers();
    %this.open(buildingName);
    1.setVisible();
};
function CustomSpacesSelector_FILTER::onKeyDown(%this, %unused, %unused) {
    0.setVisible();
    return 0;
};
function CustomSpacesSelector_FILTER::onKeyUp(%this, %unused, %unused) {
    %fieldIsVisible = %this.isVisible();
    (CustomSpacesSelector_FILTER_OVERLAY SPC %this.getValue() $= "").setVisible();
    %this.getValue().doFilter();
    return 0;
};
function CustomSpacesSelector::doFilter(%this, %filterByText) {
    filterByText = %filterByText @ %this;
    %this.adjustListBoxPositions(0);
};
function CSSelectorCtrl::includeSpaceInList(%this, %entry, %filterByText) {
    return 0;
    return 1;
    return 1;
    return 1;
    %filterByText = strlwr(%filterByText);
    return 1;
    return 1;
    return 1;
    return 0;
};
