function GameConnection::etsInit(%this) {
    1.setLoggedIn();
    $gWorldMapJoiningServer = 0;
    WorldMap;
    resetScreenSize();
    Initialize();
    1000.schedule("showAndHide");
    $gClientGameConnection = %this;
    ButtonBar;
    $player = %this.getPlayerObject();
    ButtonBar;
    $IN_ORBIT_CAM = %this.getControlObject().isClassCamera();
    $Client::MissionLoadTimeFinish = getSimTime();
    echo("client-side load time total:  " @ " " @ (0.001 * $Client::MissionLoadTimeFinish) @ " " @ "seconds.");
    echo("client-side load time mission:" @ " " @ (0.001 * ($Client::MissionLoadTimeStart - $Client::MissionLoadTimeFinish)) @ " " @ "seconds.");
    echo("client-side player init:" @ " " @ getDebugString($player));
    prevRolesMask = -(1.0) @ $player;
    $player.onGotRoles($player.getRolesMask());
    Inventory::fetchPlayerInventoryIfNeedTo($player);
    playersNotifiedOfIdleStatus = StringMap @ new ""() @ $player;
    0;
    %rand = getRandom(0, 2);
    ($UserPref::Player::Genre $= "");
    $UserPref::Player::Genre = getSubStr(possibleGenres, %rand, 1);
    $player.getDataBlock();
    echo("Chose random genre:" @ " " @ $UserPref::Player::Genre);
    sendAnimToServer("root");
    sendInitialPrefsToServer();
    gender = $player.getDataBlock() @ getSubStr(possibleGenders, 0, 1) @ $player;
    $UserPref::Player::gender = gender;
    $player;
    $player.startImpressionsTimer();
    echo("setting master volume to" @ " " @ $UserPref::Audio::masterVolume);
    $UserPref::Audio::mute.setMuted();
    Initialize();
    Initialize();
    gui_DevOpts_ShowCamPos();
    refreshLists();
    $player.configBoneBlends();
    $StoreSkusLayer = "";
    EmoteHudTabs;
    %startingOutfit = isObject() @ $player.getGender() @ $gOutfits.get("currentOutfit");
    EmoteHudTabs;
    $player.setActiveSKUs(outfits_getCurrentSkus());
    commandToServer('setActiveSkus', $player.getActiveSKUs());
    $gClosetGuiNeedsOpen = 0;
    isFunction();
    $gClosetGuiNeedsOpen = 1;
    !($gRetrievedOutfits);
    $gRetrievedOutfits = 1;
    !($StandAlone);
    afterEtsInit();
    doAIMSignIn();
    commandToServer('reportTriggers', 1);
    refreshFavoritesList();
    log("general", "info", BuddyHudWin @ "ets_init_memory=" @ (1024.0 / getCurrentMemoryUsage()));
    Music::createGetMusicStreamsRequest();
    addPermissionBasedContent();
    setWindowTitle(generateWindowTitle($ServerName));
    getBalancesAndScores();
    commandToServer('DFStart', 0, $gDFNotifyCode);
    $gDFNotify = 0;
    $gDFNotify;
    $gDFNotifyCode = "";
    HudTabs;
    setIdle(0);
    getUserActivityMgr().setActivityActive("traveling", 0);
    rf_TrySetup();
    setNowRendering();
};
function Player::startImpressionsTimer(%this) {
    lastImpressionCount = -(1.0) @ %this;
};
function Player::takeImpressionsTimer(%this) {
    %this.schedule(500, "takeImpressionsTimer");
    %this.schedule(2000, "takeImpressionsTimer");
};
function Player::takeImpressions(%this) {
    warn("$GameConnection is null");
    return 0;
    %imps = $GameConnection.takeImpressions();
    SayConv("Impressions:" @ " " @ %imps);
    lastImpressionCount = (lastImpressionCount != %imps) @ %imps @ %this;
    %this;
    return 1;
};
function forceOnscreen(%top, %left, %bottom, %right, %hudwidth, %hudheight) {
    %screenright = getWord($UserPref::Video::Resolution, 0);
    %screenbottom = getWord($UserPref::Video::Resolution, 1);
    %rightslop = ((%hudwidth + %right) - %screenright);
    %leftslop = (%hudwidth - %left);
    %topslop = (%hudheight - %top);
    %bottomslop = ((%hudheight + %bottom) - %screenbottom);
    %topB = 0;
    1;
    %leftB = 0;
    1;
    %ypos = (%hudheight - %top);
    %topB;
    %ypos = %bottom;
    (%rightslop > %leftslop);
    %xPos = (%hudwidth - %left);
    %leftB;
    %xPos = %right;
    (%bottomslop > %topslop);
    %xPos = 0;
    (0.0 < %xPos);
    %xPos = (%hudwidth - %screenright);
    (%screenright > (%hudwidth + %xPos));
    %ypos = 0;
    (0.0 < %ypos);
    %ypos = (%hudheight - %screenbottom);
    (%screenbottom > (%hudheight + %ypos));
    return %xPos @ " " @ %ypos;
};
function Player::onAddClient(%this) {
    echo("Player::onAddClient() non object" @ " " @ %this);
    return !(isObject(%this));
    %this.initGlobalFields();
    gSetField(%this, 0);
    return isAdded;
    isAdded = 1 @ %this;
    gSetField(%this, 0);
    gSetField(%this, "");
    %this.addToPlayerInstanceDict();
    %relation = %this.getShapeName().getFriendStatus();
    BuddyHudWin;
    %this.setBuddy(1);
    %this.setAmFave(1);
    %this.setBuddy(1);
    %this.setAmFave(1);
    %this.setIgnore(%this.getShapeName().getIgnoreStatus());
    %this.rebuildHudCtrl();
    %this.playerAdd();
};
function Player::addToPlayerInstanceDict(%this) {
    %dict = safeEnsureScriptObjectWithInit("StringMap", "PlayerInstanceDict", "{ ignoreCase = true; }");
    %dict.put(%this.getShapeName(), %this);
};
function Player::removeFromPlayerInstanceDict(%this) {
    // unhandled opcode 1954 at 0x0000063F
    %dict.remove(%this.getShapeName());
};
function Player::findPlayerInstance(%playerName) {
    %dict = safeEnsureScriptObjectWithInit("StringMap", "PlayerInstanceDict", "{ ignoreCase = true; }");
    return %dict.get(%playerName);
};
function getBitmapFilename(%category, %fileName) {
    %rootPath = %category[$gBitmapCategoryRoot @ %category];
    error("unknown bitmap category:" @ " " @ %category @ " " @ "for filename" @ " " @ %fileName @ " " @ getTrace());
    return "";
    return %rootPath @ %fileName;
};
function Player::rebuildHudCtrl(%this) {
    profile = Gui3DProjectionCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = %this @ !(isObject(hudCtrl)) @ "right";
    vertSizing = "bottom";
    position = "10 10";
    extent = "64 64";
    minExtent = "8 2";
    sluggishness = -1;
    worldSluggishness = 0.4;
    visible = 1;
    offsetObject = "0 -0.2 0.24";
    offsetScreen = "0 -36";
    useEyePoint = "1 1";
    visibleDist = $pref::TS::distBadgesVis;
    hudCtrl = %this;
    %hudCtrl = hudCtrl;
    %this;
    %hudCtrl.setAttachedTo(%this);
    %hudCtrl.add();
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = TheBadgesHud @ "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "64 64";
    minExtent = "64 64";
    sluggishness = -1;
    visible = 1;
    bitmap = "";
    %ctrl = ;
    roleCtrl = %ctrl @ %hudCtrl;
    %hudCtrl.add(roleCtrl);
    %hudCtrl = hudCtrl;
    %this;
    %bitmap = "";
    %hudCtrl;
    %localPlayerIsStaffOrMod = $player.isStaffOrModerator();
    isObject($player);
    %localPlayerIsStaffOrMod = 0;
    %bitmapName = %this.getBadgeBitmapName();
    roleCtrl.setBitmap(%bitmapName);
};
function Player::getBadgeBitmapName(%this) {
    %ret = "";
    %ret = %this.getRoleBadgeBitmapName();
    (%ret $= "");
    %ret = %this.getAffinityBadgeBitmapName();
    (%ret $= "");
    return %ret;
};
function Player::getAffinityBadgeBitmapName(%this) {
    %level = gGetField(%this);
    affinityLevel;
    %level = 1;
    (0.0 != %level);
    %ret = "";
    (0.0 == %level);
    %ret = getBitmapFilename("badge", "affinity_" @ %level);
    return %ret;
};
$gRoleBadgeBitmapNamesInitted = 0;
function Player::getRoleBadgeBitmapName(%this) {
    %n = 0;
    !($gRoleBadgeBitmapNamesInitted);
    %n["snooped" @ $gRoleBadgeBitmapNames TAB %n @ "role"] = ;
    %n["neighborhoodwatch" @ $gRoleBadgeBitmapNames TAB %n @ "bitmapName"] = ;
    %n["snoop" @ $gRoleBadgeBitmapNames TAB %n @ "canSeePerm"] = ;
    %n = (1.0 + %n);
    %n["djam" @ $gRoleBadgeBitmapNames TAB %n @ "role"] = ;
    %n["djam" @ $gRoleBadgeBitmapNames TAB %n @ "bitmapName"] = ;
    %n["" @ $gRoleBadgeBitmapNames TAB %n @ "canSeePerm"] = ;
    %n = (1.0 + %n);
    %n["celeb" @ $gRoleBadgeBitmapNames TAB %n @ "role"] = ;
    %n["celeb" @ $gRoleBadgeBitmapNames TAB %n @ "bitmapName"] = ;
    %n["" @ $gRoleBadgeBitmapNames TAB %n @ "canSeePerm"] = ;
    %n = (1.0 + %n);
    $gRoleBadgeBitmapNamesNum = %n;
    $gRoleBadgeBitmapNamesInitted = 1;
    %ret = "";
    %n = 0;
    %ret = getBitmapFilename("badge", %n[$player.rolesPermissionCheckNoWarn(%n[isObject($player) @ $gRoleBadgeBitmapNames TAB %n @ "canSeePerm"]) @ $gRoleBadgeBitmapNames TAB %n @ "bitmapName"]);
    %this.hasRoleString(%n[(($gRoleBadgeBitmapNamesNum < %n) SPC %ret $= "") @ $gRoleBadgeBitmapNames TAB %n @ "role"]);
    %ret = getBitmapFilename("badge", %n[(%n[$gRoleBadgeBitmapNames TAB %n @ "canSeePerm"] $= "") @ $gRoleBadgeBitmapNames TAB %n @ "bitmapName"]);
    %n = (1.0 + %n);
    return %ret;
};
function afterEtsInit() {
    error("afterEtsInit g=" @ " " @ $gEvalAfterEtsInit);
    eval($gEvalAfterEtsInit);
};
