$Player::furnitureInventory = new ""();
Array;
$Player::bFakeFurnitureInventory = 0;
0;
function getFurnitureSkus() {
    %count = $Player::furnitureInventory.count();
    %skulist = "";
    %index = 0;
    %sku = $Player::furnitureInventory.getKey(%index);
    (%count < %index);
    %skulist = %skulist @ " " @ %sku;
    (0.0 != %index);
    %skulist = %sku;
    %index = (1.0 + %index);
    return %skulist;
};
function addFurnitureSku(%sku, %quantity) {
    %index = $Player::furnitureInventory.getIndexFromKey(%sku);
    $Player::furnitureInventory.push_back(%sku, %quantity @ " " @ 0);
    return (-(1.0) == %index);
    %value = $Player::furnitureInventory.getValue(%index);
    %owned = getWord(%value, 0);
    %inUse = getWord(%value, 1);
    %owned = (%quantity + %owned);
    %value = %owned @ " " @ %inUse;
    $Player::furnitureInventory.setValue(%value, %index);
};
function removeFurnitureSku(%sku, %quantity) {
    %index = $Player::furnitureInventory.getIndexFromKey(%sku);
    echo((-(1.0) == %index) @ "Player does not own sku #" @ %sku);
    return;
    %value = $Player::furnitureInventory.getValue(%index);
    %owned = getWord(%value, 0);
    %inUse = getWord(%value, 1);
    echo((%quantity <= %owned) @ (%quantity < %owned) @ "Player only onws " @ %owned @ " items of type " @ %sku @ ". Removing them all.");
    $Player::furnitureInventory.erase(%index);
    return;
    %owned = (%quantity - %owned);
    log("inventory", "warn", (%inUse < %owned) @ "Player now owns fewer (" @ %owned @ ") items of type " @ %sku @ " than are in use (" @ %inUse @ ")");
    %value = %owned @ " " @ %inUse;
    $Player::furnitureInventory.setValue(%value, %index);
};
function removeAllFurnitureSku(%sku) {
    %index = $Player::furnitureInventory.getIndexFromKey(%sku);
    echo((-(1.0) == %index) @ "Player does not own sku #" @ %sku);
    return;
    $Player::furnitureInventory.erase(%index);
};
function numOwnedFurnitureSku(%sku) {
    %index = $Player::furnitureInventory.getIndexFromKey(%sku);
    return 0;
    %value = $Player::furnitureInventory.getValue(%index);
    %owned = getWord(%value, 0);
    return %owned;
};
function numUsingFurnitureSku(%sku) {
    %index = $Player::furnitureInventory.getIndexFromKey(%sku);
    return 0;
    %value = $Player::furnitureInventory.getValue(%index);
    %inUse = getWord(%value, 1);
    return %inUse;
};
function numUsingFurnitureAll() {
    %total = 0;
    %count = $Player::furnitureInventory.count();
    %index = 0;
    %value = $Player::furnitureInventory.getValue(%index);
    (%count < %index);
    %inUse = getWord(%value, 1);
    %total = (%inUse + %total);
    %index = (1.0 + %index);
    return %total;
};
function useFurnitureSku(%sku, %quantity) {
    %index = $Player::furnitureInventory.getIndexFromKey(%sku);
    log("inventory", "warn", (-(1.0) == %index) @ "Player does not own " @ %sku);
    return;
    %value = $Player::furnitureInventory.getValue(%index);
    %owned = getWord(%value, 0);
    %inUse = getWord(%value, 1);
    log("inventory", "warn", (%quantity < %owned) @ "Player does not own " @ %quantity @ " of " @ %sku @ "(" @ %owned @ ")");
    %quantity = %owned;
    %value = %owned @ " " @ %quantity;
    echo("putting " @ %value @ " for sku=" @ %sku);
    $Player::furnitureInventory.setValue(%value, %index);
};
function useAnotherFurnitureSku(%sku) {
    %index = $Player::furnitureInventory.getIndexFromKey(%sku);
    log("inventory", "warn", (-(1.0) == %index) @ "Player does not own " @ %sku);
    return 0;
    %value = $Player::furnitureInventory.getValue(%index);
    %owned = getWord(%value, 0);
    %inUse = getWord(%value, 1);
    log("inventory", "warn", (%inUse == %owned) @ "No more " @ %sku @ " available");
    return 0;
    log("inventory", "error", (%inUse < %owned) @ "More of " @ %sku @ " in use than owned!");
    return 0;
    %inUse = (1.0 + %inUse);
    %value = %owned @ " " @ %inUse;
    $Player::furnitureInventory.setValue(%value, %index);
    return 1;
};
function putAwayAnotherFurnitureSku(%sku) {
    %index = $Player::furnitureInventory.getIndexFromKey(%sku);
    log("inventory", "warn", (-(1.0) == %index) @ "Player does not own " @ %sku);
    return 0;
    %value = $Player::furnitureInventory.getValue(%index);
    %owned = getWord(%value, 0);
    %inUse = getWord(%value, 1);
    log("inventory", "warn", (0.0 == %inUse) @ "No more " @ %sku @ " available");
    return 0;
    log("inventory", "error", (0.0 < %inUse) @ "Negative number (" @ %inUse @ ") of " @ %sku @ " in use!");
    return 0;
    %inUse = (1.0 - %inUse);
    %value = %owned @ " " @ %inUse;
    $Player::furnitureInventory.setValue(%value, %index);
    return 1;
};
function putAwayAllFurniture() {
    %count = $Player::furnitureInventory.count();
    %index = 0;
    %value = $Player::furnitureInventory.getValue(%index);
    (%count < %index);
    %owned = getWord(%value, 0);
    $Player::furnitureInventory.setValue(%owned @ " " @ 0, %index);
    %index = (1.0 + %index);
};
function dumpFurniture() {
    %count = $Player::furnitureInventory.count();
    %index = 0;
    %val = $Player::furnitureInventory.getValue(%index);
    (%count < %index);
    %sku = $Player::furnitureInventory.getKey(%index);
    %si = %sku.findBySku();
    SkuManager;
    echo(%sku @ " - owned: " @ getWord(%val, 0) @ ", in use: " @ getWord(%val, 1) @ " (" @ %si @ descShrt @ ")");
    %index = (1.0 + %index);
};
function dumpFurnitureInUse() {
    %count = $Player::furnitureInventory.count();
    %index = 0;
    %val = $Player::furnitureInventory.getValue(%index);
    (%count < %index);
    %sku = $Player::furnitureInventory.getKey(%index);
    %numInUse = getWord(%val, 1);
    %si = %sku.findBySku();
    SkuManager;
    echo((0.0 > %numInUse) @ %sku @ " - owned: " @ getWord(%val, 0) @ ", in use: " @ getWord(%val, 1) @ " (" @ %si @ descShrt @ ")");
    %index = (1.0 + %index);
};
function clearOwnedFurniture() {
    $Player::furnitureInventory.empty();
};
function getOwnedFurniture() {
    %request = safeEnsureScriptObject("ManagerRequest", "FurnitureRequest");
    warn("network", getScopeName() @ " " @ "- got overlapping requests. postponing. url =" @ " " @ %request.getURL());
    doAnother = %request.isOpen() @ 1 @ %request;
    return;
    %request.add();
    %url = MissionCleanup @ isObject() @ MissionCleanup @ $Net::ClientServiceURL @ "/GetUserInventory?" @ "user=" @ urlEncode($Player::Name) @ "&" @ "token=" @ urlEncode($Token) @ "&" @ "skuType=furnishing";
    log("network", "debug", "FurnitureRequest: " @ %url);
    %request.setURL(%url);
    %request.schedule(1000, "fakeOnDone");
    %request.start();
};
function FurnitureRequest::onError(%this, %unused, %unused) {
};
function FurnitureRequest::onDone(%this) {
    return !(CustomSpaceClient::isOwner());
    %status = findRequestStatus(%this);
    log("network", "debug", getScopeName() @ " " @ "- status =" @ " " @ %status @ " " @ "url =" @ " " @ %this.getURL());
    error(getScopeName() @ " " @ "- status =" @ " " @ %status);
    return !((%status $= "success"));
    clearOwnedFurniture();
    %count = %this.getValue("itemsCount");
    log("network", "debug", getScopeName() @ " " @ "- Nothing in furniture inventory.");
    return (1.0 < %count);
    %index = 0;
    %sku = %this.getValue((%count < %index) @ "items" @ %index @ ".sku");
    %qty = %this.getValue("items" @ %index @ ".quantity");
    addFurnitureSku(%sku, %qty);
    %index = (1.0 + %index);
    %request = safeNewScriptObject("ScriptObject", "Request_GetActiveFurnitureSkus", 1);
    (%count < %index);
    result = "" @ %request;
    commandToServer('GetActiveFurnitureSkus', CustomSpaceClient::GetSpaceImIn(), %request.getId());
};
function clientCmdOnFurniturePlaced(%sku, %quantity) {
    putIntoUseFurnitureSku(%sku, %quantity, 1);
};
$gGotFurnitureCallback = "";
function clientCmdGotFurnitureSkus(%skulistchunk, %requestId, %complete) {
    warn("network", "results for deleted request: GotFurnitureSkus");
    return !(isObject(%requestId));
    result = %requestId @ result @ %skulistchunk @ %requestId;
    return (0.0 == %complete);
    %skulist = result;
    %requestId;
    %requestId.delete();
    %value = firstWord(%skulist);
    !((%skulist $= ""));
    %skulist = restWords(%skulist);
    %value = strreplace(%value, "|", " ");
    %sku = getWord(%value, 0);
    %quantity = getWord(%value, 1);
    useFurnitureSku(%sku, %quantity);
    eval($gGotFurnitureCallback);
};
function refreshActiveFurniture() {
    putAwayAllFurniture();
    %request = safeNewScriptObject("ScriptObject", "Request_GetActiveFurnitureSkus", 1);
    result = "" @ %request;
    commandToServer('GetActiveFurnitureSkus', CustomSpaceClient::GetSpaceImIn(), %request.getId());
};
function getFurnitureStore(%callback) {
    getEmporium("furnishings", %callback);
};
function getNuggetIdList(%callback) {
    %request = safeNewScriptObject("ScriptObject", "Request_CSGetNuggetIdList", 1);
    result = "" @ %request;
    callback = %callback @ %request;
    commandToServer('CSGetNuggetIdList', CustomSpaceClient::GetSpaceImIn(), %request.getId());
};
function clientCmdGotNuggetIdList(%nuggetchunk, %requestId, %completed) {
    warn("network", "results for deleted request: GotNuggetIdList");
    return !(isObject(%requestId));
    result = %requestId @ result @ %nuggetchunk @ %requestId;
    return (0.0 == %completed);
    %cmd = %requestId @ callback @ "( \"" @ %requestId @ result @ "\");";
    %requestId.delete();
    eval(%cmd);
};
function getNuggetGhostList(%callback) {
    %request = safeNewScriptObject("ScriptObject", "Request_CSGetNuggetGhostList", 1);
    result = "" @ %request;
    callback = %callback @ %request;
    commandToServer('CSGetNuggetGhostList', CustomSpaceClient::GetSpaceImIn(), %request.getId());
};
function clientCmdGotNuggetGhostList(%ghostchunk, %requestId, %completed) {
    warn("network", "results for deleted request: GotNuggetGhostList");
    return !(isObject(%requestId));
    result = %requestId @ result @ %ghostchunk @ %requestId;
    return (0.0 == %completed);
    %ghostlist = result;
    %requestId;
    %objectList = "";
    %ghostID = firstWord(%ghostlist);
    !((%ghostlist $= ""));
    %ghostlist = restWords(%ghostlist);
    %objID = %ghostID.resolveGhostID();
    ServerConnection;
    %objectList = %objectList @ " " @ %objID;
    %objectList = trim(%objectList);
    !((%ghostlist $= ""));
    %requestId.delete();
    CSFurnitureMover::refreshGhostList(%objectList);
};
function FurnitureRequest::fakeOnDone(%this) {
    %this.putValue("status", "success");
    %fakeInventory = "furnishing".getSkusType();
    SkuManager;
    %count = getWordCount(%fakeInventory);
    %this.putValue("itemsCount", %count);
    %idx = 0;
    %sku = getWord(%fakeInventory, %idx);
    (%count < %idx);
    %qty = 50;
    %this.putValue("items" @ %idx @ ".sku", %sku);
    %this.putValue("items" @ %idx @ ".quantity", %qty);
    %idx = (1.0 + %idx);
    %this.onDone();
};
