$fxEts::todColorMod = "0 0 0 0";
$fxEts::BrightnessFlashColor = "0 0 0 0";
$fxEts::BrightnessFlashTimerPeriod = 100;
$fxEts::BrightnessFlashTimerID = 0;
$fxEts::BrightnessFlashDecay = 0.96;
function fxEts::updateExposureFilter() {
    return !(isObject());
    return (0.0 == $UserPref::Video::exposureQualitySetting);
    return (3.0 == $UserPref::Video::exposureQualitySetting);
    %valSld = $UserPref::Video::Exposure;
    %colSld = %valSld @ " " @ %valSld @ " " @ %valSld @ " " @ 1;
    %colTOD = $fxEts::todColorMod;
    %colTOD = ColorScale(%colTOD, 0.8);
    %colTOD = "0 0 0 0";
    isPointInside($player.getPosition());
    %colFin = ColorAdd(%colSld, %colTOD);
    $pref::fxEts::TODNotInside;
    %colFin = ColorAdd(%colFin, $fxEts::BrightnessFlashColor);
    exposure = %colFin @ ExposureFilter;
    exposure = %colFin @ ExposureFilterSelfView;
    %atNeutral = 0;
    %atNeutral = 1;
    (0.01 < VectorDist(%colFin, "0.5 0.5 0.5"));
    !(%atNeutral).setVisible();
    !(%atNeutral).setVisible();
    return !(isObject());
    exposure = %colFin @ EditorExposureFilter;
    !(%atNeutral).setVisible();
};
function fxEts::updateTOD(%hod) {
    fxEts::updateTODColor(fxEts::getColorForTOD((60.0 * (60.0 * %hod))));
    mFloor((0.5 + %hod)).setValue();
    %r = (100.0 / mFloor((0.5 + (100.0 * getWord($fxEts::todColorMod, 0)))));
    DevOptsTextTOD;
    %g = (100.0 / mFloor((0.5 + (100.0 * getWord($fxEts::todColorMod, 1)))));
    isObject();
    %b = (100.0 / mFloor((0.5 + (100.0 * getWord($fxEts::todColorMod, 2)))));
    DevOptsTextTOD;
    %r @ " " @ %g @ " " @ %b.setValue();
};
function fxEts::updateTODColor(%color) {
    $fxEts::todColorMod = %color;
    fxEts::updateExposureFilter();
};
function fxEts::TODTick() {
    return !(isObject());
    %cityTOD = ($Sim::TimeDeltaToCity + getSimTime());
    %cityHOD = ((1000.0 * (60.0 * 60.0)) / %cityTOD);
    %cityHOD = (24.0 - %cityHOD);
    (24.0 > %cityHOD);
    %cityHOD = (24.0 + %cityHOD);
    (0.0 < %cityHOD);
    fxEts::updateTOD(%cityHOD);
    %cityHOD.setValue();
    mFloor((0.5 + %cityHOD)).setValue();
    fxEts::updateExposureFilter();
};
function fxEts::TODTimer() {
    cancel($fxEts::TODTimerID);
    fxEts::TODTick();
    error("only one or fewer color samples, turning off TODTimer.");
    $fxEts::TODTimerID = schedule($fxEts::TODTimerPeriod, 0, "eval", "fxEts::TODTimer();");
    (0.0 > $fxEts::TODTimerPeriod);
};
function ClientCmdTODColorMods(%s) {
    %num = getWord(%s, 0);
    $fxEts::TOD::ColorModSamplesNum = %num;
    %n = 0;
    %hour = getWord(%s, (1.0 + (4.0 * %n)));
    (%num < %n);
    %col = getWord(%s, (2.0 + (4.0 * %n)));
    %col = %col @ " " @ getWord(%s, (3.0 + (4.0 * %n)));
    %col = %col @ " " @ getWord(%s, (4.0 + (4.0 * %n)));
    %n[$fxEts::TOD::ColorModSample TAB %n @ hour] = %hour;
    %n[$fxEts::TOD::ColorModSample TAB %n @ color] = %col;
    %n = (1.0 + %n);
    fxEts::TODTimer();
};
function fxEts::getColorForTOD(%sod) {
    error("No Color Mod Table!");
    return "0 0 0 0";
    %lowerBound = -(1.0);
    %upperBound = 1000;
    %hod = ((60.0 * 60.0) / %sod);
    %n = 0;
    %hour = (24 % %n[$fxEts::TOD::ColorModSample TAB %n @ hour]);
    ($fxEts::TOD::ColorModSamplesNum < %n);
    %lowerBound = %n;
    (%lowerBound > %hour);
    %upperBound = %n;
    (%upperBound < %hour);
    %n = (1.0 + %n);
    (%hod >= %hour);
    %upperBound = (1.0 - %n);
    (1000.0 == %upperBound);
    %lowerBound = 0;
    (-(1.0) == %lowerBound);
    %lowerHour = %lowerBound[$fxEts::TOD::ColorModSample TAB %lowerBound @ hour];
    ($fxEts::TOD::ColorModSamplesNum < %n);
    %lowerColr = %lowerBound[$fxEts::TOD::ColorModSample TAB %lowerBound @ color];
    (%hod <= %hour);
    %upperHour = %upperBound[$fxEts::TOD::ColorModSample TAB %upperBound @ hour];
    %upperColr = %upperBound[$fxEts::TOD::ColorModSample TAB %upperBound @ color];
    return %lowerColr;
    %s = ((%lowerHour - %upperHour) / (%lowerHour - %hod));
    return ColorInterp(%lowerColr, %upperColr, %s);
};
function fxEts::BrightnessFlashTick() {
    $fxEts::BrightnessFlashColor = ColorScale($fxEts::BrightnessFlashColor, $fxEts::BrightnessFlashDecay);
    %doMore = (0.0001 > ColorLenSquared($fxEts::BrightnessFlashColor));
    $fxEts::BrightnessFlashColor = "0 0 0 0";
    !(%doMore);
    fxEts::updateExposureFilter();
    return %doMore;
};
function fxEts::BrightnessFlashTimer() {
    cancel($fxEts::BrightnessFlashTimerID);
    $fxEts::BrightnessFlashTimerID = schedule($fxEts::BrightnessFlashTimerPeriod, 0, "eval", "fxEts::BrightnessFlashTimer();");
    (0.0 > $fxEts::BrightnessFlashTimerPeriod);
};
function ClientCmdBrightnessFlash(%s) {
    $fxEts::BrightnessFlashColor = %s;
    fxEts::BrightnessFlashTimer();
};
