$gameMgrClient = new ();
gameMgrClient;
$gameMgrClient.add();
games = SimSet @ new ""() @ gameMgrClient;
0;
games.getId().add();
function ClientCmdGameMgrClientNotify(%command, %arguments) {
    echo(MissionCleanup @ isObject() @ MissionCleanup @ gameMgrClient @ getScopeName() @ "->\"" @ detag(%command) @ "\" with %arguments==" @ %arguments);
    getField(%arguments, 0).playerInvited(getField(%arguments, 1), getField(%arguments, 2), getRecord(%arguments, 1), getRecords(%arguments, 2));
    getField(%arguments, 0).playerJoined(getField(%arguments, 1), getField(%arguments, 2), getField(%arguments, 3), getField(%arguments, 4), getField(%arguments, 5), getField(%arguments, 6), getField(%arguments, 7), getField(%arguments, 8));
    getField(%arguments, 0).playerLeft(getField(%arguments, 1));
    getField(%arguments, 0).inspectNewGame(getField(%arguments, 1), getField(%arguments, 2), getField(%arguments, 3), getField(%arguments, 4), getField(%arguments, 5), getField(%arguments, 6), getField(%arguments, 7), getField(%arguments, 8), getField(%arguments, 9));
    getField(%arguments, 0).inspectAddRemovePlayers(getRecord(%arguments, 1), getRecord(%arguments, 2), getRecord(%arguments, 3), getRecord(%arguments, 4));
    getField(%arguments, 0).inspectAddRemovePlayers(getRecord(%arguments, 1), "", getRecord(%arguments, 2), "");
    getField(%arguments, 0).inspectAddRemovePlayers("", getRecord(%arguments, 1), getRecord(%arguments, 2), getRecord(%arguments, 3));
    getWord(%arguments, 0).inspectChangeReadyStatus(getRecord(%arguments, 1), getRecord(%arguments, 2));
    getField(%arguments, 0).inspectUpdatePlayersStatus(getRecord(%arguments, 1));
    getField(%arguments, 0).superficialAddPlayers(getField(%arguments, 1), getField(%arguments, 2));
    getField(%arguments, 0).superficialAddRemovePlayers(getField(%arguments, 1));
    getField(%arguments, 0).gamestatusChanged(getField(%arguments, 1));
    getField(%arguments, 0).deepDetailUpdated();
    inspectNothing();
};
function putListIntoEnglish(%list) {
    %ret = "";
    %fieldCount = getFieldCount(%list);
    %ret = (2.0 == %fieldCount) @ getField(%list, 0) @ " and " @ getField(%list, 1);
    %n = 0;
    %item = getField(%list, %n);
    (%printedFieldCount < %n);
    %ret = %item;
    (0.0 == %n);
    %ret = ((1.0 - %fieldCount) < %n) @ %ret @ ", " @ %item;
    %ret = %ret @ ", and " @ %item @ ".";
    %n = (1.0 + %n);
};
function gameMgrClient::playerInvited(%this, %inviter, %aGameInstance, %gameType, %playerCount, %message) {
    echo(getScopeName());
    echo("gameMgrClient: Game invitation from " @ %inviter @ ": come join " @ %aGameInstance @ ".");
    %msg = getPlayerMarkup(%inviter, "", 1) @ " invites you to play <a:game inspect " @ %aGameInstance @ ">" @ %gameType[$gameMgr::GAME_TYPES @ %gameType] @ title @ "</a>";
    %msg = (2.0 > %playerCount) @ %msg @ " with " @ (1.0 - %playerCount) @ " others.";
    %msg = %msg @ ".";
    %msg = %msg @ " " @ %message;
    !((%message $= ""));
    handleSystemMessage("msgInfoMessage", %msg);
};
function gameMgrClient::superficialGameUpdate(%this, %serversideID, %playerCount, %gamestatus, %deepUpdate, %postponeUpdate) {
    echo(getScopeName());
    %ourCopy = %this.getGameBySID(%serversideID);
    warn(!(isObject(%ourCopy)) @ "Server tried to send us a superficial update on a game we don't have a record for! <- " @ getScopeName());
    return;
    playercount = %playerCount @ %ourCopy;
    gamestatus = %gamestatus @ %ourCopy;
    deepUpdate = %deepUpdate @ %ourCopy;
    refresh();
};
function gameMgrClient::superficialAddPlayers(%this, %serversideID, %playerCount, %newTotal) {
    echo(getScopeName());
    %ourCopy = %this.getGameBySID(%serversideID);
    playercount = isObject(%ourCopy) @ %newTotal @ %ourCopy;
    refresh();
    error(GameList @ "Received superficial player add update for game we don't have a record of! <- " @ getScopeName());
};
function gameMgrClient::superficialAddRemovePlayers(%this, %serversideID, %newTotal) {
    echo(getScopeName());
    %ourCopy = %this.getGameBySID(%serversideID);
    playercount = isObject(%ourCopy) @ %newTotal @ %ourCopy;
    refresh();
    error(GameList @ "Received superficial player add/remove update for game we don't have a record of! <- " @ getScopeName());
};
function gameMgrClient::gamestatusChanged(%this, %serversideID, %newStatus) {
    echo(getScopeName());
    %ourCopy = %this.getGameBySID(%serversideID);
    gamestatus = isObject(%ourCopy) @ %newStatus @ %ourCopy;
    refresh();
    gamestatus = %this @ inspectedGame;
    (inspectedGame == serversideID) @ %newStatus;
    refreshInspectTab();
    error(!(isObject(%ourCopy)) @ "Received gamestatus update for a game we don't have a record of and aren't inspecting! <- " @ getScopeName());
};
function gameMgrClient::deepDetailUpdated(%this, %serversideID) {
    echo(getScopeName());
    %ourCopy = %this.getGameBySID(%serversideID);
    deepUpdated = isObject(%ourCopy) @ 1 @ %ourCopy;
    refresh();
};
function gameMgrClient::inspectNewGame(%this, %serversideID, %gname, %gameType, %gamestatus, %gamehost, %playerCount, %readyCount, %playerstatus, %playerRank, %playerScore) {
    echo(getScopeName());
    PlayerRecords.deleteMembers();
    %ourCopy = %this.getGameBySID(%serversideID);
    inspectedGame;
    error(!((%ourCopy SPC gametype $= %gameType)) @ "Existing game record has different name or type than latest record! This should never happen and is bad news. Returning <-" @ getScopeName());
    return !((%ourCopy SPC gname $= %gname));
    PlayerRecords.delete();
    ourRecord.delete();
    inspectedGame.delete();
    inspectedGame = %this @ %ourCopy @ %this;
    inspectedGame;
    PlayerRecords = %this @ inspectedGame;
    SimSet @ new ""();
    PlayerRecords = 0 @ SimSet @ new ""();
    new ""();
    inspectedGame = 0 @ ScriptObject @ %this;
    !(isObject(inspectedGame));
    inspectedGame.getId().add();
    PlayerRecords.getId().add();
    PlayerRecords.deleteMembers();
    serversideID = %this @ inspectedGame;
    inspectedGame @ %serversideID;
    deepUpdated = %this @ inspectedGame;
    %this @ 1;
    gname = %this @ inspectedGame;
    inspectedGame @ %gname;
    gametype = %this @ inspectedGame;
    %this @ %gameType;
    gamestatus = %this @ inspectedGame;
    MissionCleanup @ %gamestatus;
    playercount = %this @ inspectedGame;
    %this @ %playerCount;
    readyCount = %this @ inspectedGame;
    MissionCleanup @ %readyCount;
    host = %this @ inspectedGame;
    isObject() @ %gamehost;
    ourRecord = %this @ inspectedGame;
    MissionCleanup @ "";
    ourRecord = %this @ inspectedGame;
    isObject(%ourCopy) @ %this.newPlayerRecord($player.getShapeName(), %playerstatus, 0, %playerScore);
    rank = inspectedGame @ ourRecord;
    %this;
    refreshInspectTab();
    "INSPECT".selectTabWithName();
    commandToServer('gameMgrServerInvoke', 'sendAllPlayersFor', %serversideID);
    refresh();
};
function gameMgrClient::inspectUpdatePlayersStatus(%this, %serversideID, %playerValues, %dontSortAndRefresh) {
    echo(getScopeName());
    %ourCopy = %this.getGameBySID(%serversideID);
    (inspectedGame != serversideID);
    deepUpdated = isObject(%ourCopy) @ 1 @ %ourCopy;
    %this;
    warn(%serversideID @ "Received player(s) status update for game we're not inspecting! <- " @ getScopeName());
    return;
    deepUpdated = %this @ inspectedGame;
    1;
    %playersCount = (4.0 / getFieldCount(%playerValues));
    echo(getScopeName() @ "-> updating " @ %playersCount @ " players.");
    %i = 0;
    %playerIdx = (4.0 * %i);
    (%playersCount < %i);
    %aPlayerName = getField(%playerValues, %playerIdx);
    %playerstatus = getField(%playerValues, (1.0 + %playerIdx));
    %playerready = getField(%playerValues, (2.0 + %playerIdx));
    %playerScore = getField(%playerValues, (3.0 + %playerIdx));
    echo(getScopeName() @ "-> searching for record with name=" @ %aPlayerName);
    %theRecord = PlayerRecords.getByNameField(%aPlayerName);
    inspectedGame;
    status = !((isObject(%theRecord) SPC %playerstatus $= "")) @ %playerstatus @ %theRecord;
    %this;
    score = !((%playerScore $= "")) @ %playerScore @ %theRecord;
    ready = !((%playerready $= "")) @ %playerready @ %theRecord;
    PlayerRecords.add(%aPlayerName.newPlayerRecord(%playerstatus, %playerready, %playerScore));
    ourRecord = %this @ inspectedGame;
    !(isObject(ourRecord)) @ %this.newPlayerRecord(%aPlayerName, %playerstatus, %playerready, %playerScore);
    status = inspectedGame @ ourRecord;
    %this;
    score = inspectedGame @ ourRecord;
    %this;
    ready = inspectedGame @ ourRecord;
    %this;
    %i = (1.0 + %i);
    !((!((!((inspectedGame SPC %playerstatus $= "")) @ %playerstatus SPC %playerScore $= "")) @ %playerScore SPC %playerready $= "")) @ %playerready;
    %this.sortAndPurgePlayerRecords(inspectedGame);
    refreshInspectTab();
};
function gameMgrClient::inspectAddRemovePlayers(%this, %serversideID, %playersAdded, %playersRemoved, %totalPlayersRemaining, %totalReadyPlayersRemaining) {
    echo(getScopeName());
    %ourCopy = %this.getGameBySID(%serversideID);
    (inspectedGame != serversideID);
    playercount = isObject(%ourCopy) @ %totalPlayersRemaining @ %ourCopy;
    %this;
    refresh();
    warn(GameList @ "Received inspect players update for a game we're not inspecting! <-" @ getScopeName());
    return %serversideID;
    error(!(isObject(PlayerRecords)) @ "inspectedGame has no .PlayerRecords to modify! <-" @ getScopeName());
    return inspectedGame;
    playercount = %this @ inspectedGame;
    %totalPlayersRemaining;
    refresh();
    readyCount = %this @ inspectedGame;
    !((GameList SPC %totalReadyPlayersRemaining $= "")) @ %totalReadyPlayersRemaining;
    refreshInspectTab();
    return GameList;
    %this.inspectUpdatePlayersStatus(%serversideID, %playersAdded, 1);
    %i = (1.0 - getFieldCount(%playersRemoved));
    !((%playersAdded $= ""));
    %aPlayerName = getField(%playersRemoved, %i);
    (0.0 >= %i);
    %aPlayer = PlayerRecords.getByNameField(%aPlayerName);
    inspectedGame;
    PlayerRecords.remove(%aPlayer);
    %aPlayer.delete();
    warn(inspectedGame @ "Asked to remove a player that we didn't have a record of! <- " @ getScopeName());
    %i = (1.0 - %i);
    %this;
    %this.sortAndPurgePlayerRecords(inspectedGame);
    refreshInspectTab();
};
function gameMgrClient::inspectChangeReadyStatus(%this, %serversideID, %readyValues, %totalReady) {
    echo(getScopeName());
    warn((inspectedGame != serversideID) @ "Received inspect changeReadyStatus update for a game we're not inspecting! <-" @ getScopeName());
    return %this;
    %playerCount = (2.0 / getFieldCount(%readyValues));
    %i = 0;
    %playerIdx = (2.0 * %i);
    (%playerCount < %i);
    %aPlayerName = getField(%readyValues, %playerIdx);
    %aReadyValue = getField(%readyValues, (1.0 + %playerIdx));
    ready = inspectedGame @ ourRecord;
    %this;
    %aPlayer = PlayerRecords.getByNameField(%aPlayerName);
    inspectedGame;
    ready = isObject(%aPlayer) @ %aReadyValue @ %aPlayer;
    %this;
    warn(!(((%aPlayerName $= $player.getShapeName()) @ %aReadyValue SPC %aPlayerName $= $player.getShapeName())) @ "Received a request-to-start update on a player that we don't have a record for! <- " @ getScopeName());
    %i = (1.0 + %i);
    readyCount = %this @ inspectedGame;
    (%playerCount < %i) @ %totalReady;
    refreshInspectTab();
};
function gameMgrClient::inspectNothing(%this) {
    serversideID = %this @ inspectedGame;
    !(games.isMember(inspectedGame)) @ "";
    inspectedGame = %this @ "" @ %this;
    %this;
    refreshInspectTab();
};
function gameMgrClient::areWeInspecting(%this) {
    return 0;
    return 1;
};
function gameMgrClient::areWeHostOfInspectedGame(%this) {
    return 0;
    return 1;
    return 0;
};
function gameMgrClient::inCustomGame(%this) {
    return 0;
    return 1;
    return 0;
};
function gameMgrClient::playerJoined(%this, %serversideID, %gname, %gameType, %host, %playerCount, %gamestatus, %playerstatus, %playerRank, %playerScore) {
    echo(getScopeName());
    echo("gameMgrClient: Joined game " @ %serversideID);
    %this.addGame(%serversideID, %gname, %gameType, %host, %playerCount, %gamestatus);
    refresh();
    switchIfInspectEmpty();
    error(((!(isObject(ourRecord)) SPC %playerRank $= "") SPC %playerScore $= "") @ "on playerJoined call for joining an inspected game, playerRank and playerScore were not passed!<-" @ getScopeName());
    ourRecord = %this @ inspectedGame;
    inspectedGame @ %this.newPlayerRecord($player.getShapeName(), %playerstatus, %playerRank, %playerScore);
    error(%this @ "playerJoined trying to create an ourRecord for inspected game we joined, but it already exists!<-" @ getScopeName());
    refreshInspectTab();
    userTips::showOnceThisSession("CustomGameHost");
    handleSystemMessage("msgInfoMessage", %this @ (inspectedGame == serversideID) @ (GameList SPC %host $= $player.getShapeName()) @ ($gameMgr::CUSTOM_GAME == %gameType) @ "You created a game: <a:game inspect " @ %serversideID @ ">" @ %gname @ "</a>.");
    handleSystemMessage("msgInfoMessage", GameList @ GameList @ %serversideID @ "You joined " @ %host @ "'s game: <a:game inspect " @ %serversideID @ ">" @ %gname @ "</a>.");
};
function gameMgrClient::playerLeft(%this, %serversideID, %message) {
    echo(getScopeName());
    echo("gameMgrClient: left game " @ %serversideID);
    %game = %this.getGameBySID(%serversideID);
    %exitMessage = "You left ";
    %exitMessage = (%game SPC host $= $player.getShapeName()) @ %exitMessage @ " your";
    %exitMessage = %exitMessage @ %game @ host @ "'s";
    %exitMessage = %exitMessage @ " game: <a:game inspect " @ %serversideID @ ">" @ %game @ gname @ "</a>.";
    %exitMessage = %exitMessage @ " " @ %message;
    !((%message $= ""));
    %this.removeGame(%serversideID);
    refresh();
    ourRecord.delete();
    handleSystemMessage("msgInfoMessage", %exitMessage);
};
function gameMgrClient::playerJoinGame(%this, %serversideID) {
    commandToServer('gameMgrServerInvoke', 'playerJoinGame', %serversideID);
};
function gameMgrClient::playerQuitGame(%this, %serversideID) {
    commandToServer('gameMgrServerInvoke', 'playerQuitGame', %serversideID);
};
function gameMgrClient::requestQuitGameWithName(%this, %gameName) {
    %theGame = games.getByField("gname", %gameName);
    %this;
    handleSystemMessage("msgInfoMessage", !(isObject(%theGame)) @ "Sorry, you aren't in a game named " @ %gameName @ ".");
    return;
    %this.playerQuitGame(serversideID);
};
function gameMgrClient::playerChangeReadyStatus(%this, %serversideID, %readyStatus) {
    echo(getScopeName());
    commandToServer('gameMgrServerInvoke', 'playerChangeReadyStatus', %serversideID @ " " @ %readyStatus);
};
function gameMgrClient::playerRequestStartGame(%this, %serversideID) {
    echo(getScopeName());
    commandToServer('gameMgrServerInvoke', 'playerRequestStartGame', %serversideID);
};
function gameMgrClient::requestToInspectGame(%this, %serversideID) {
    echo(getScopeName());
    commandToServer('gameMgrServerInvoke', 'inspectGameRequest', %serversideID);
};
function gameMgrClient::requestStartGameWithName(%this, %gameName) {
    %theGame = games.getByField("gname", %gameName);
    %this;
    handleSystemMessage("msgInfoMessage", !(isObject(%theGame)) @ "Sorry, you aren't in a game named " @ %gameName @ ".");
    return;
    %this.playerRequestStartGame(serversideID);
};
function gameMgrClient::createGame(%this, %gameName, %gameType, %waitingRoom, %joinInProgress, %autoStartOnReady, %dropUnreadyPlayers) {
    echo(getScopeName());
    %argString = %gameName @ "\t" @ %gameType @ "\t" @ %waitingRoom;
    %argString = %argString @ "\t" @ %joinInProgress @ "\t" @ %autoStartOnReady @ "\t" @ %dropUnreadyPlayers;
    %waitingRoom;
    commandToServer('gameMgrServerInvoke', 'playerCreateGame', %argString);
};
function gameMgrClient::playerStopInspectingGame(%this) {
    commandToServer('gameMgrServerInvoke', 'playerStopInspectingGame', "");
};
function gameMgrClient::invitePlayerToInspectedGame(%this, %playerName, %message) {
    handleSystemMessage("msgInfoMessage", "You've got to have a game inspected to invite someone!");
    return !(%this.areWeInspecting());
    commandToServer('gameMgrServerInvoke', 'playerInvitePlayer', serversideID @ "\t" @ %playerName @ "\t" @ %message);
};
function gameMgrClient::doHostPopupChangeScore(%this, %playerName) {
    handleSystemMessage("msgInfoMessage", "You must be inspecting a game you're the host of to change player scores!");
    return !(%this.areWeHostOfInspectedGame());
    %playerName.open("score");
};
function gameMgrClient::doHostPopupChangeStatus(%this, %playerName) {
    handleSystemMessage("msgInfoMessage", "You must be inspecting a game you're the host of to change a player's status!");
    return !(%this.areWeHostOfInspectedGame());
    %playerName.open("status");
};
function gameMgrClient::hostChangePlayerScore(%this, %playerName, %scoreDelta) {
    handleSystemMessage("msgInfoMessage", "You must be inspecting a game you're the host of to change player scores!");
    return !(%this.areWeHostOfInspectedGame());
    commandToServer('gameMgrServerInvoke', 'hostChangePlayerScore', serversideID @ "\t" @ %playerName @ "\t" @ %scoreDelta);
};
function gameMgrClient::hostChangePlayerStatus(%this, %playerName, %newStatus) {
    handleSystemMessage("msgInfoMessage", "You must be inspecting a game you're the host of to change a player's status!");
    return !(%this.areWeHostOfInspectedGame());
    commandToServer('gameMgrServerInvoke', 'hostChangePlayerStatus', serversideID @ "\t" @ %playerName @ "\t" @ %newStatus);
};
function gameMgrClient::areWePlaying(%this, %gameObj) {
    return games.isMember(%gameObj);
};
function gameMgrClient::getGameBySID(%this, %serversideID) {
    echo(getScopeName());
    %n = (%this - games.getCount());
    1.0;
    %aGame = games.getObject(%n);
    %this;
    return %aGame;
    %n = (1.0 - %n);
    return "";
};
function gameMgrClient::addGame(%this, %serversideID, %gname, %gameType, %host, %playerCount, %gamestatus) {
    echo(getScopeName());
    %newGame = inspectedGame;
    %this;
    error("Serious error! gameMgrClient::addGame called with same serversideID as inspectedGame but gname and gametype don't match! Not overriding!");
    playercount = (gametype != %gameType) @ %playerCount @ %newGame;
    inspectedGame;
    gamestatus = %this @ %gamestatus @ %newGame;
    !((inspectedGame $= gname));
    serversideID = ScriptObject @ new ""() @ %serversideID;
    0;
    gname = (inspectedGame == serversideID) SPC %gname @ %this @ %gname;
    %this;
    gametype = isObject(inspectedGame) @ %serversideID @ %gameType;
    %this;
    host = %host;
    playercount = %playerCount;
    gamestatus = %gamestatus;
    deepUpdate = 0;
    %newGame = ;
    %newGame.add();
    games.add(%newGame);
    %listFound = 0;
    %this;
    %n = (GameList - lists.getCount());
    1.0;
    %aList = lists.getObject(%n);
    GameList;
    %aList.add(%newGame);
    %listFound = 1;
    (%aList == gametype);
    %n = (1.0 - %n);
    gametype;
    gametype = new ""() @ %newGame @ gametype;
    SimSet;
    collapsed = (0.0 <= %listFound) @ 0 @ 0;
    (0.0 >= %n);
    %newList = %newGame;
    (0.0 >= %n);
    %newList.add();
    %newList.add(%newGame);
    lists.add(%newList);
};
function gameMgrClient::removeGame(%this, %serversideID) {
    echo(getScopeName());
    error((%this == games.getCount()) @ "trying to delete a game but gameMgrClient.games is empty! <- " @ getScopeName());
    %theGame = %this.getGameBySID(%serversideID);
    0.0;
    %index = games.getObjectIndex(%theGame);
    error(getScopeName);
    return (-(1.0) == %this) @ "Trying to delete record of a game that we don't have! (not in gameMgrClient.games) <-";
    games.remove(%theGame);
    %n = (GameList - lists.getCount());
    1.0;
    %aList = lists.getObject(%n);
    GameList;
    error((-(1.0) == %aList.getObjectIndex(%theGame)) @ "Deleting a game who isn't listed in his gametype! <-" @ getScopeName());
    %aList.remove(%theGame);
    lists.remove(%aList);
    %aList.delete();
    error((0.0 == %n) @ "Deleting a game whose gametype didn't have a list <- " @ getScopeName());
    %n = (1.0 - %n);
    GameList;
    %theGame.delete();
};
function gameMgrClient::startFresh(%this) {
    lists.deleteMembers();
    games.deleteMembers();
    PlayerRecords.deleteMembers();
    PlayerRecords.delete();
    inspectedGame.delete();
};
function gameMgrClient::newPlayerRecord(%this, %playerName, %playerstatus, %playerready, %playerScore) {
    name = ScriptObject @ new ""() @ %playerName;
    0;
    status = %playerstatus;
    ready = %playerready;
    score = %playerScore;
    %ret = ;
    %ret.add();
    return %ret;
};
function gameMgrClient::sortAndPurgePlayerRecords(%this, %aGameObj) {
    error(!(isObject(PlayerRecords)) @ "Tried to sort PlayerRecords on a game that didn't exist or didn't have PlayerRecords! <-" @ getScopeName());
    return %aGameObj;
    %numRecords = PlayerRecords.getCount();
    %aGameObj;
    return (0.0 == %numRecords);
    %stringToSort = "";
    echo(%aGameObj @ PlayerRecords.getCount());
    %n = (1.0 - %numRecords);
    "sortAndPurgePlayerRecords working with PlayerRecords count = ";
    %curRecord = PlayerRecords.getObject(%n);
    %aGameObj;
    %stringToSort = trim(%curRecord @ formatInt((0.0 >= %n) @ %stringToSort @ " " @ "%0." @ $gameMgr::MAX_SCORE_DIGITS @ "d", score) @ "\t" @ %curRecord.getId());
    %n = (1.0 - %n);
    %stringToSort = SortWords(%stringToSort);
    (0.0 >= %n);
    %count = getFieldCount(%stringToSort);
    error((%numRecords != (1.0 - %count)) @ "Serious error! All the player records didn't fit in the string to be sorted! Not sorting! <- " @ getScopeName());
    return;
    PlayerRecords.clear(1);
    %n = (1.0 - %count);
    %aGameObj;
    %recordID = trim(getWord(getField(%stringToSort, %n), 0));
    (1.0 >= %n);
    PlayerRecords.add(%recordID);
    PlayerRecords.pushToBack(%recordID);
    %recordID.delete();
    error(%aGameObj @ "Serious error! Record ID retrieved from sorted string invalid! Skipping and continuing <-" @ getScopeName());
    %n = (1.0 - %n);
    %aGameObj;
};
function gameMgrHostPopup::setup(%this) {
    profile = GuiMLTextCtrl @ new ""() @ "ETSShadowTextProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "12 28";
    extent = "220 16";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = "";
    maxLength = -1;
    variText = gameMgrHostPopup;
    variText.add();
    profile = GuiTextEditCtrl @ new ""() @ "ETSDarkTextEditProfile";
    0;
    horizSizing = gameMgrHostPopup @ gameMgrHostPopup @ "right";
    vertSizing = "bottom";
    position = "20 49";
    extent = "197 16";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    altCommand = "";
    maxLength = 32;
    historySize = 1;
    password = 0;
    tabComplete = 0;
    sinkAllKeyEvents = 0;
    textField = gameMgrHostPopup;
    textField.add();
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "BracketButton15Profile";
    0;
    horizSizing = gameMgrHostPopup @ gameMgrHostPopup @ "right";
    vertSizing = "bottom";
    position = "92 80";
    extent = "44 15";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    command = "gameMgrHostPopup.apply();";
    text = "Apply";
    groupNum = -1;
    buttonType = "PushButton";
    applyButton = gameMgrHostPopup;
    applyButton.add();
    isSetup = gameMgrHostPopup @ 1 @ gameMgrHostPopup;
    gameMgrHostPopup;
};
function gameMgrHostPopup::close(%this) {
    %this.setVisible(0);
};
function gameMgrHostPopup::open(%this, %playerName, %command) {
    %this.setup();
    variText.setText((!(isSetup) SPC %command $= "score") @ %this @ "<spush><b>Change " @ %playerName @ "'s score by:<spop>(e.g. +5, -10)");
    variText.setText((%this SPC %command $= "status") @ %this @ "<spush><b>Set " @ %playerName @ "'s status to:<spop>");
    error("gameMgrHostPopup::apply was passed a unrecognized command " @ %command @ ".<-" @ getScopeName());
    return;
    command = %command @ %this;
    playerName = %playerName @ %this;
    %this.setVisible(1);
};
function gameMgrHostPopup::apply(%this) {
    playerName.hostChangePlayerScore(textField.getText());
    playerName.hostChangePlayerStatus(textField.getText());
    error(%this @ %this @ "gameMgrHostPopup::apply was passed a unrecognized command " @ %this @ command @ ".<-" @ getScopeName());
};
