function drinks_confirmInitiateGift(%otherPlayerName) {
    %sku = $player.getActiveDrinkSku();
    error(getScopeName() @ " " @ "- no drink!" @ " " @ getTrace());
    return (%sku $= "");
    %si = %sku.findBySku();
    SkuManager;
    %msg = %si[$MsgCat::giftingItems @ "DLG-BODY-GIVE-CONFIRM"];
    %msg = strreplace(%msg, "[ITEMNAME]", descShrt);
    %si;
    %msg = strreplace(%msg, "[OTHERPLAYER]", %otherPlayerName);
    %dlg = MessageBoxYesNo(%msg[$MsgCat::giftingItems @ "DLG-TITLE-GIVE-CONFIRM"], %msg, "giftingItems_onInitiate($gThisDialog);", "");
    otherPlayerName = %otherPlayerName @ %dlg;
    giftSkus = %sku @ %dlg;
    making = 0 @ %dlg;
};
function drinks_confirmInitiateMake(%otherPlayerName, %sku) {
    %otherPlayer = Player::findPlayerInstance(%otherPlayerName);
    error(getScopeName() @ " " @ "- can't find other player" @ " " @ %otherPlayerName @ " " @ getTrace());
    return !(isObject(%otherPlayer));
    %si = %sku.findBySku();
    SkuManager;
    %msg = $Player::Name[$MsgCat::giftingItems @ "DLG-BODY-MAKE-SELF-CONFIRM"];
    (%otherPlayerName $= $Player::Name);
    %msg = %msg[$MsgCat::giftingItems @ "DLG-BODY-MAKE-CONFIRM"];
    %msg = strreplace(%msg, "[ITEMNAME]", descShrt);
    %si;
    %msg = strreplace(%msg, "[OTHERPLAYER]", %otherPlayerName);
    %dlg = MessageBoxYesNo(%msg[$MsgCat::giftingItems @ "DLG-TITLE-MAKE-CONFIRM"], %msg, "giftingItems_onInitiate($gThisDialog);", "");
    otherPlayerName = %otherPlayerName @ %dlg;
    giftSkus = %sku @ %dlg;
    making = 1 @ %dlg;
};
function giftingItems_onInitiate(%dlg) {
    %transactionID = MD5(getRandom(0, 1000000));
    commandToServer('GiftingItems_Initiated', otherPlayerName, %transactionID, giftSkus, making);
    %otherDlg = "";
    (%dlg SPC otherPlayerName $= $Player::Name);
    %otherDlg = MessageBoxOK("The Gift of Libation", "<br>Checking with" @ " " @ %dlg @ otherPlayerName @ "..<br>", "");
    %dlg;
    giftingItems_registerPendingTransactionGiver(%transactionID, otherPlayerName, giftSkus, %otherDlg, making);
};
function ClientCmdGiftingItems_Initiated(%otherPlayerName, %skus, %transactionID, %making) {
    %otherPlayer = Player::findPlayerInstance(%otherPlayerName);
    error(getScopeName() @ " " @ "- could not find other player:" @ " " @ %otherPlayerName);
    GiftingItemsClient_DoAcceptOrDecline(%otherPlayerName, %transactionID, 0, "E-ENVSERVER-UNKNOWN");
    return !(isObject(%otherPlayer));
    error("// oxe 20090219 - todo - decide if this is good or if we want a new one");
    %acceptModeStrangers = $UserPref::Player::GiftsPermissionStrangers[$gGiftAcceptModeStrings @ $UserPref::Player::GiftsPermissionStrangers];
    %acceptModeFriends = $UserPref::Player::GiftsPermissionFriends[$gGiftAcceptModeStrings @ $UserPref::Player::GiftsPermissionFriends];
    %acceptMode = %acceptModeStrangers;
    %acceptModeFriends;
    giftingItems_registerPendingTransactionRecipient(%transactionID, %otherPlayerName, %skus, 1, %making);
    GiftingItemsClient_DoAcceptOrDecline(%otherPlayerName, %transactionID, 1, "ACCEPTED-AUTO");
    GiftingItemsClient_DoAcceptOrDecline(%otherPlayerName, %transactionID, 0, "DECLINED-AUTO");
    GiftingItemsClient_DoAcceptOrDecline(%otherPlayerName, %transactionID, 0, "DECLINED-BUSY");
    giftingItems_registerPendingTransactionRecipient(%transactionID, %otherPlayerName, %skus, 0, %making);
    giftTransactionID = isVisible() @ %transactionID @ geGiftingPanel;
    geGiftingPanel;
    personalMessage = (((%otherPlayer.isFriend() SPC %acceptMode $= "accept") SPC %acceptMode $= "decline") SPC %acceptMode $= "ask") @ "" @ geGiftingPanel;
    skus = %skus @ geGiftingPanel;
    GiftType = "items" @ geGiftingPanel;
    making = %making @ geGiftingPanel;
    %otherPlayerName.open("items_acceptDecline");
};
function GiftingItemsClient_DoAcceptOrDecline(%otherPlayerName, %transactionID, %accepted, %messageCode) {
    commandToServer('GiftingItems_AcceptedOrDeclined', %otherPlayerName, %transactionID, %accepted, %messageCode);
};
function ClientCmdGiftingItems_AcceptedOrDeclinedOrInvalid(%transactionID, %accepted, %messageCode) {
    %pendingTransactionRecord = giftingItems_getPendingTransactionClient(%transactionID);
    error(getScopeName() @ " " @ "- no such pending transaction:" @ " " @ %transactionID);
    return !(isObject(%pendingTransactionRecord));
    dlg.close();
    %otherPlayerName = targetPlayerName;
    %pendingTransactionRecord;
    %otherPlayer = Player::findPlayerInstance(%otherPlayerName);
    !(%accepted);
    error(getScopeName() @ " " @ "- can't find other player:" @ " " @ %otherPlayerName @ " " @ %transactionID);
    %messageCode = "E-TARGET-MISSING";
    !(isObject(%otherPlayer));
    %text = strreplace(%messageCode[$MsgCat::gifting @ %messageCode], "[OTHERPLAYER]", %pendingTransactionRecord @ isObject(dlg) @ %pendingTransactionRecord @ "<linkcolor:ffddeeff><a:gamelink " @ munge(%otherPlayerName) @ ">" @ StripMLControlChars(%otherPlayerName) @ "</a>");
    %text = strreplace(%text, "[OTHERPLAYER_HIM_HER_IT]", getPronounHimHerIt(%otherPlayer));
    %text = strreplace(%text, "[OTHERPLAYER_HE_SHE_IT]", getPronounHeSheIt(%otherPlayer));
    MessageBoxOK("Woops..", %text, "");
    giftingItems_deletePendingTransactionClient(%transactionID);
};
function ClientCmdGiftingItems_Completed(%transactionID, %succeeded) {
    %transactionRecord = giftingItems_getPendingTransactionClient(%transactionID);
    error(getScopeName() @ " " @ "- no such pending transaction:" @ " " @ %transactionID);
    return !(isObject(%transactionRecord));
    %amSource = (%transactionRecord SPC sourcePlayerName $= $Player::Name);
    %otherPlayerName = sourcePlayerName;
    %transactionRecord;
    %amAlphaAndOmega = (targetPlayerName SPC %otherPlayerName $= $Player::Name);
    %transactionRecord;
    %skus = skus;
    %transactionRecord;
    schedule(3000, 0, "updateInventorySkus", %skus, "", 1, 1, %otherPlayerName);
    updateInventorySkus("", %skus, 0, 1, %otherPlayerName);
    %autoAccepted = autoAccepted;
    %transactionRecord;
    updateInventorySkus(%skus, "", %autoAccepted, 1, %otherPlayerName);
    %msg = %amSource;
    %amAlphaAndOmega;
    MessageBoxOK("Woops...", %msg);
    %dlg = dlg;
    %transactionRecord;
    %dlg.close();
    giftingItems_deletePendingTransactionClient(%transactionID);
};
