$gGiftingEnabled_vPoints = 0;
$gGiftingEnabled_vBux = 0;
$gGiftingEnabled_vPoints = 1;
$StandAlone;
$gGiftingEnabled_vBux = 1;
function geGiftingPanel::open(%this, %otherPlayerName, %whichScreen) {
    return (%otherPlayerName $= $Player::Name);
    %request = new ""();
    ManagerRequest;
    parseGiftingSettings(%request);
    %request.delete();
    error(getScopeName() @ " " @ "- using hardcoded daily caps.");
    setMyRespektPoints(54321, 0);
    %otherPlayer = Player::findPlayerInstance(%otherPlayerName);
    0;
    error(getScopeName() @ " " @ "- could not find other player:" @ " " @ %otherPlayerName @ " " @ getTrace());
    return !(isObject(%otherPlayer));
    %text = !(%this.isInRange(%otherPlayer));
    (%whichScreen $= "initiate");
    %text = strreplace(%text, "[OTHERPLAYER]", %otherPlayerName);
    MessageBoxOK("Get Closer!", %text, "");
    return;
    requestPlayerInfoFor(%otherPlayerName);
    add();
    1.setVisible();
    getWord(getExtent(), 0).resize(getWord(getExtent(), 1));
    0.reposition(0);
    focusAndRaise();
    %this.ensureAdded();
    %this.setVisible(1);
    %this.focusAndRaise();
    setActionMapsEnabled(0);
    otherPlayerName = PlayGui @ %otherPlayerName @ %this;
    PlayGui;
    sourcePlayerName = (geGiftingPanelBackground SPC %whichScreen $= "acceptDecline") @ %otherPlayerName @ %this;
    PlayGui;
    targetPlayerName = geGiftingPanelBackground @ $Player::Name @ %this;
    PlayGui;
    sourcePlayerName = PlayGui @ $Player::Name @ %this;
    geGiftingPanelBackground;
    targetPlayerName = geGiftingPanelBackground @ %otherPlayerName @ %this;
    geGiftingPanelBackground;
    0.setValue();
    0.setValue();
    "".setValue();
    "".setValue();
    currentScreen = geGiftingEditMsg @ %whichScreen @ %this;
    geGiftingEditAmt;
    %this.refresh();
};
function geGiftingPanel::close(%this, %accepted, %messageCode) {
    %this.setVisible(0);
    focusTopWindow();
    0.setVisible();
    setActionMapsEnabled(1);
    %accepted = 0;
    !(isDefined("%accepted"));
    %messageCode = "DECLINED";
    !(isDefined("%messageCode"));
    %this.doAccept(sourcePlayerName, giftTransactionID, %accepted, %messageCode);
    cancel($gGiftingPanelAcceptDeclineTimerID);
    return 1;
};
function geGiftingPanel::openFromPendingTransactionRecord(%this, %pendingTransactionRecord) {
    targetPlayerName.open("initiate");
    (%pendingTransactionRecord SPC currencyType $= "vPoints").setValue();
    (%pendingTransactionRecord SPC currencyType $= "vBux").setValue();
    currencyAmount.setValue();
    personalMessage.setValue();
    refresh();
    1.makeFirstResponder();
};
function geGiftingPanel::isInRange(%this, %otherPlayer) {
    return 0;
    %coAnimEntry = findCoAnimEntry("gift");
    %range = getField(%coAnimEntry, 3);
    %ret = Math::isInRange($player.getPosition(), %otherPlayer.getPosition(), %range);
    return %ret;
};
function geGiftingPanel::refresh(%this) {
    %ghost = Player::findPlayerInstance(otherPlayerName);
    %this;
    error(%this @ otherPlayerName);
    %this.close();
    return getScopeName() @ " " @ "- couldn't find target player:" @ " ";
    %text = %this @ otherPlayerName;
    "<just:right><clip:1000>";
    %text.setTextWithStyle();
    %otherPlayerPortraitUrl = geGiftingOtherPlayerName @ $Net::AvatarURL @ %this @ urlEncode(otherPlayerName) @ "?size=M";
    geGiftingOtherPlayerPortrait @ "platform/client/ui/tgf/tgf_profile_default_" @ %ghost.getGender().setBitmap();
    %otherPlayerPortraitUrl.downloadAndApplyBitmap();
    1.setVisible();
    0.setVisible();
    0.setVisible();
    %this.refreshScreen_Initiate();
    0.setVisible();
    1.setVisible();
    0.setVisible();
    %this.refreshScreen_Confirmation();
    0.setVisible();
    0.setVisible();
    1.setVisible();
    %this.refreshScreen_AcceptDecline();
    0.setVisible();
    0.setVisible();
    1.setVisible();
    %this.refreshScreen_ItemsAcceptDecline();
    error(%this @ currentScreen @ " " @ getTrace());
};
function geGiftingPanel::refreshScreen_Initiate(%this) {
    %text = %this @ otherPlayerName;
    "The gift of cash for" @ " ";
    %text.setTextWithStyle();
    GiftType = geGiftingTitle @ "currency" @ %this;
    %amountInTheBank = %this.getAmountInBankOfCurrentCurrency();
    %level = $player.getRespektLevel();
    %levelName = respektLevelToNameWithIndefiniteArticle(%level);
    %limitVpGive = getGiftingCapsForLevel(%level, "vPoints", "give");
    %limitVbGet = getGiftingCapsForLevel(%level, "vPoints", "recv");
    %limitVbGive = getGiftingCapsForLevel(%level, "vBux", "give");
    %limitVbGet = getGiftingCapsForLevel(%level, "vBux", "recv");
    %text = textBody;
    geGiftingTextLimits;
    %text = strreplace(%text, "[LEVEL]", %level);
    %text = strreplace(%text, "[LEVELNAME]", %levelName);
    %text = strreplace(%text, "[VPGIVE]", %limitVpGive);
    %text = strreplace(%text, "[VBGIVE]", %limitVbGive);
    %text = !($gGiftingEnabled_vBux) @ %text @ "<br><color:ff3333>Gifting is temporarily disabled.";
    !($gGiftingEnabled_vPoints);
    %text = !($gGiftingEnabled_vPoints) @ %text @ "<br><color:ff3333>Gifting vPoints is temporarily disabled.";
    %text = !($gGiftingEnabled_vBux) @ %text @ "<br><color:ff3333>Gifting vBux is temporarily disabled.";
    %text.setTextWithStyle();
    %enableVP = $gGiftingEnabled_vPoints;
    (0.0 > %limitVpGive);
    %enableVB = $gGiftingEnabled_vBux;
    (0.0 > %limitVbGive);
    %enableVP.setActive();
    %enableVB.setActive();
    geGiftingTextType @ textBody.setTextWithStyle();
    textBodyI.setTextWithStyle();
    textBodyI.setTextWithStyle();
    %currencyType = "vBux";
    "vPoints";
    %vpText = "vPoints";
    getValue();
    %vbText = "vBux";
    geGiftingCurrencyType_vPoints;
    %currencyText = getValue() @ geGiftingCurrencyType_vPoints @ getValue() @ "<spush><color:159fe7>" @ %vpText @ "<spop> " @ "<spush><color:13b93c>" @ %vbText @ "<spop>";
    geGiftingCurrencyType_vBux;
    %text = textBody;
    geGiftingTextAmt;
    %text = strreplace(%text, "[GIFTTYPE]", %currencyText);
    getValue();
    %text = geGiftingCurrencyType_vPoints @ "<spush><font:Arial Bold:20>2.<spop> " @ %text;
    geGiftingText3;
    %vpText = "vPoints";
    "vPoint";
    %vbText = "vBux";
    "vBuck";
    %currencyText = (geGiftingEditAmt == getValue()) @ geGiftingCurrencyType_vPoints @ getValue() @ "<spush><color:159fe7>" @ %vpText @ "<spop> " @ "<spush><color:13b93c>" @ %vbText @ "<spop>";
    1.0;
    %currencyText = (geGiftingEditAmt == getValue()) @ geGiftingEditAmt @ (getValue() < %amountInTheBank) @ %currencyText @ " <spush><b><color:ff0000dd>.. you only have " @ %amountInTheBank @ "!";
    1.0;
    %text.setTextWithStyle();
    %currencyText.setTextWithStyle();
    1.setVisible();
    "<color:ffffff40><spush><font:Arial Bold:20>2.<spop> amount".setTextWithStyle();
    "".setTextWithStyle();
    0.setVisible();
    geGiftingTextMsg @ textBody.setTextWithStyle();
    1.setVisible();
    1.setActive();
    "<color:ffffff40><spush><font:Arial Bold:20>3.<spop> message".setTextWithStyle();
    0.setVisible();
    1.makeFirstResponder();
    0.setActive();
    1.setVisible();
    0.setActive();
    "< Back".setText();
    "Next >".setText();
    1.setVisible();
};
function geGiftingPanel::getGiftDescription(%this) {
    %ret = gifting_composeGiftDescriptionCurrency(currencyType, currencyAmount);
    %this;
    %ret = gifting_composeGiftDescriptionItems(skus);
    %this;
    return %ret;
};
function gifting_composeGiftDescriptionCurrency(%currencyType, %currencyAmount) {
    %vpText = "vPoints";
    "vPoint";
    %vbText = "vBux";
    "vBuck";
    %text = (1.0 == %currencyAmount) @ (1.0 == %currencyAmount) @ (%currencyAmount @ " " SPC %currencyType $= "VPOINTS") @ "<spush><color:159fe7>" @ %vpText @ "<spop>" @ "<spush><color:13b93c>" @ %vbText @ "<spop>";
    return %text;
};
function gifting_composeGiftDescriptionCurrency2(%currencyType, %currencyAmount) {
    %vpText = "vPoints";
    "vPoint";
    %vbText = "vBux";
    "vBuck";
    %aFew = 5;
    50;
    %sardonicism = "";
    "whole ";
    %text = (1.0 == %currencyAmount) @ ((1.0 == %currencyAmount) SPC %currencyType $= "VPOINTS") @ ((%aFew < %currencyAmount) @ %currencyAmount @ " " @ %sardonicism SPC %currencyType $= "VPOINTS") @ "<spush><color:002288>" @ %vpText @ "<spop>" @ "<spush><color:005500>" @ %vbText @ "<spop>";
    return %text;
};
function gifting_composeGiftDescriptionItems(%skus) {
    %text = SkuManager @ %skus.getSkuShortDescriptions("and a ", 0);
    "a" @ " ";
    return %text;
};
function geGiftingPanel::refreshScreen_Confirmation(%this) {
    1.setVisible();
    1.setActive();
    "< Back".setText();
    personalMessage = geGiftingEditMsg @ getValue() @ %this;
    geGiftingButtonBack;
    personalMessage = %this @ StripMLControlChars(personalMessage) @ %this;
    geGiftingButtonBack;
    personalMessage = (%this SPC personalMessage $= "") @ "(no message)" @ %this;
    geGiftingButtonBack;
    %text = "<tab:80>";
    %text = %text @ %text[$MsgCat::gifting @ "CAVEAT-MUNEROR"];
    %text = %text @ "<br>";
    %text = %text @ "<br>Giving:" @ "\t" @ %this.getGiftDescription();
    %text = %this @ targetPlayerName;
    %text @ "<br>To:" @ "\t";
    %text = %this @ personalMessage;
    %text @ "<br>With Message:" @ "\t";
    %text = strreplace(%text, "[GIFTDESC]", %this.getGiftDescription());
    %text.setTextWithStyle();
    "Give!".setText();
    1.makeFirstResponder();
    1.setVisible();
};
$gGiftingPanelAcceptDeclineTimerID = 0;
function geGiftingPanel::refreshScreen_AcceptDecline(%this) {
    %text = "The gift of cash";
    %text.setTextWithStyle();
    "DECLINE".setText();
    1.setActive();
    "ACCEPT".setText();
    1.setActive();
    0.setVisible();
    %otherPlayer = Player::findPlayerInstance(otherPlayerName);
    %this;
    %text = "";
    geGiftingButtonCancel;
    %text = geGiftingButtonNext @ %text @ %text[$MsgCat::gifting @ "ACCEPT-OR-DECLINE"];
    geGiftingButtonNext;
    %text = strreplace(%text, "[OTHERPLAYER]", otherPlayerName);
    %this;
    %text = strreplace(%text, "[PERSONALMESSAGE]", personalMessage);
    %this;
    %text = strreplace(%text, "[GIFTAMOUNT]", currencyAmount);
    %this;
    %text = strreplace(%text, "[GIFTTYPE]", currencyType);
    %this;
    %text = strreplace(%text, "[GIFTDESC]", %this.getGiftDescription());
    geGiftingButtonBack;
    %text = strreplace(%text, "[OTHERPLAYER_HE_SHE_IT]", getPronounHeSheIt(%otherPlayer));
    geGiftingButtonBack;
    %text = strreplace(%text, "[OTHERPLAYER_HIM_HER_IT]", getPronounHimHerIt(%otherPlayer));
    geGiftingTitle;
    %text = strreplace(%text, "[IT_THEM]", getPronounItThem(currencyAmount));
    %this;
    %text.setTextWithStyle();
    %this.startCountdownTimer((1000.0 * 30.0));
};
function geGiftingPanel::refreshScreen_ItemsAcceptDecline(%this) {
    %text = "The Gift of Libation";
    %text.setTextWithStyle();
    GiftType = geGiftingTitle @ "items" @ %this;
    "DECLINE".setText();
    1.setActive();
    "ACCEPT".setText();
    1.setActive();
    0.setVisible();
    %otherPlayer = Player::findPlayerInstance(otherPlayerName);
    %this;
    %numItems = getWordCount(skus);
    %this;
    %text = %this[$MsgCat::giftingItems @ "ACCEPT-OR-DECLINE-MAKING"][$MsgCat::giftingItems @ "ACCEPT-OR-DECLINE"];
    %this[$MsgCat::giftingItems @ "ACCEPT-OR-DECLINE-MAKING"];
    %text = strreplace(%text, "[OTHERPLAYER]", otherPlayerName);
    %this;
    %text = strreplace(%text, "[GIFTDESC]", %this.getGiftDescription());
    making;
    %text = strreplace(%text, "[OTHERPLAYER_HE_SHE_IT]", getPronounHeSheIt(%otherPlayer));
    %this;
    %text = strreplace(%text, "[OTHERPLAYER_HIM_HER_IT]", getPronounHimHerIt(%otherPlayer));
    geGiftingButtonCancel;
    %text = strreplace(%text, "[IT_THEM]", getPronounItThem(%numItems));
    geGiftingButtonNext;
    %text.setTextWithStyle();
    %this.startCountdownTimer((1000.0 * 30.0));
};
function geGiftingPanel::startCountdownTimer(%this, %milliseconds) {
    $gGiftingPanelCountdownMSRemaining = %milliseconds;
    %this.countdownTick();
};
function geGiftingPanel::countdownTick(%this) {
    %tickPeriod = 100;
    $gGiftingPanelCountdownMSRemaining = (%tickPeriod - $gGiftingPanelCountdownMSRemaining);
    rotRadians = (6.0 / (0.001 * $gGiftingPanelCountdownMSRemaining)) @ geGiftingAcceptDeclineClock_littleHand;
    rotRadians = (0.001 * $gGiftingPanelCountdownMSRemaining) @ geGiftingAcceptDeclineClock_bigHand;
    %text = mFloor((0.5 + (0.001 * $gGiftingPanelCountdownMSRemaining)));
    %text = %text @ "..";
    %text.setTextWithStyle();
    cancel($gGiftingPanelAcceptDeclineTimerID);
    $gGiftingPanelAcceptDeclineTimerID = %this.schedule(%tickPeriod, "countdownTick");
    %this.isVisible();
    %this.close(0, "DECLINED-TIMEOUT");
    %text = %this[$MsgCat::giftingItems @ "E-TOOSLOW"][$MsgCat::giftingItems @ "E-TOOSLOW"];
    %this[$MsgCat::giftingItems @ "E-TOOSLOW"];
    %text = strreplace(%text, "[OTHERPLAYER]", otherPlayerName);
    %this;
    %text = strreplace(%text, "[PERSONALMESSAGE]", personalMessage);
    %this;
    handleSystemMessage("msgInfoMessage", %text);
};
function geGiftingEditAmt::validate(%this) {
    refresh();
};
function geGiftingEditAmt::onEnter(%this) {
    1.makeFirstResponder();
};
function geGiftingEditMsg::validate(%this) {
    refresh();
};
function geGiftingEditMsg::onEnter(%this) {
    eval(command);
};
function geGiftingPanel::onNext(%this) {
    %this.onNext_Initiate();
    %this.onNext_Confirmation();
    %this.onNext_AcceptDecline();
    %this.onNext_Items_AcceptDecline();
    error(%this @ currentScreen @ " " @ getTrace());
};
function geGiftingPanel::onBack(%this) {
    %this.onBack_Initiate();
    %this.onBack_Confirmation();
    %this.onBack_AcceptDecline();
    %this.onBack_Items_AcceptDecline();
    error(%this @ currentScreen @ " " @ getTrace());
};
function geGiftingPanel::onNext_Initiate(%this) {
    currencyType = "vPoints" @ "vBux" @ %this;
    getValue();
    currencyAmount = geGiftingEditAmt @ getValue() @ %this;
    geGiftingCurrencyType_vPoints;
    %amountInTheBank = %this.getAmountInBankOfCurrentCurrency();
    "".setValue();
    error(%this @ currencyAmount @ " " @ %amountInTheBank @ " " @ getTrace());
    MessageBoxOK("Something is Wrong", "Hm, something went wrong.\nPlease enter a new amount..", "");
    %this.refresh();
    return getScopeName() @ " " @ "- trying to give more money than owned!" @ " ";
    currentScreen = "confirmation" @ %this;
    %this.refresh();
};
function geGiftingPanel::onNext_Confirmation(%this) {
    %dlg = MessageBoxOK("The Gift of Cash", "<br>Sending" @ " " @ %this.getGiftDescription() @ " " @ "to" @ " " @ %this @ targetPlayerName @ "..<br>", "");
    %dlg.onDryRunSuccess();
    %request = sendRequest_GiftCurrency(targetPlayerName, currencyType, currencyAmount, 1);
    onDoneOrErrorCallback_GiftCurrency;
    dlg = %this @ %dlg @ %request;
    %this;
    %this.close();
};
function geGiftingPanel::onNext_AcceptDecline(%this) {
    %this.close(1, "ACCEPTED");
};
function geGiftingPanel::onNext_Items_AcceptDecline(%this) {
    %this.close(1, "ACCEPTED");
};
function geGiftingPanel::onBack_AcceptDecline(%this) {
    %this.close();
};
function geGiftingPanel::onBack_Items_AcceptDecline(%this) {
    %this.close();
};
function geGiftingPanel::onDryRunSuccess(%this, %dlg) {
    %giftTransactionID = MD5(getRandom(0, 1000000));
    commandToServer('GiftingCurrency_Initiated', targetPlayerName, %giftTransactionID, personalMessage, currencyType, currencyAmount);
    %this.registerPendingTransaction(%giftTransactionID, currencyType, currencyAmount, targetPlayerName, %dlg, personalMessage);
};
function geGiftingPanel::registerPendingTransaction(%this, %giftTransactionID, %currencyType, %currencyAmount, %targetPlayerName, %dlg, %personalMessage) {
    PendingTransactionsList = !(isObject(PendingTransactionsList)) @ safeNewScriptObject("StringMap", "", 0) @ %this;
    %this;
    error(getScopeName() @ " " @ "- transaction already exists!" @ " " @ %giftTransactionID @ " " @ getTrace());
    return !((%this SPC PendingTransactionsList.get(%giftTransactionID) $= ""));
    %pendingTransactionRecord = safeNewScriptObject("ScriptObject", "", 0);
    giftTransactionID = %giftTransactionID @ %pendingTransactionRecord;
    currencyType = %currencyType @ %pendingTransactionRecord;
    currencyAmount = %currencyAmount @ %pendingTransactionRecord;
    targetPlayerName = %targetPlayerName @ %pendingTransactionRecord;
    dlg = %dlg @ %pendingTransactionRecord;
    personalMessage = %personalMessage @ %pendingTransactionRecord;
    PendingTransactionsList.put(%giftTransactionID, %pendingTransactionRecord);
};
function geGiftingPanel::getPendingTransaction(%this, %giftTransactionID) {
    error(getScopeName() @ " " @ "- no PendingTransactionsList!" @ " " @ getTrace());
    return "";
    %pendingTransactionRecord = PendingTransactionsList.get(%giftTransactionID);
    %this;
    error(getScopeName() @ " " @ "- no such transaction:" @ " " @ %giftTransactionID @ " " @ getTrace());
    return "";
    return %pendingTransactionRecord;
};
function geGiftingPanel::deletePendingTransaction(%this, %giftTransactionID) {
    error(getScopeName() @ " " @ "- no PendingTransactionsList!" @ " " @ getTrace());
    return "";
    %pendingTransactionRecord = PendingTransactionsList.get(%giftTransactionID);
    %this;
    error(getScopeName() @ " " @ "- no such transaction:" @ " " @ %giftTransactionID @ " " @ getTrace());
    return "";
    %pendingTransactionRecord.delete();
    PendingTransactionsList.remove(%giftTransactionID);
};
function ClientCmdGiftingCurrency_Initiated(%sourcePlayerName, %giftTransactionID, %personalMessage, %currencyType, %currencyAmount) {
    %sourcePlayer = Player::findPlayerInstance(%sourcePlayerName);
    error(getScopeName() @ " " @ "- could not find source player:" @ " " @ %sourcePlayerName);
    %sourcePlayerName.doAccept(%giftTransactionID, 0, "E-ENVSERVER-UNKNOWN");
    return geGiftingPanel;
    %acceptModeStrangers = $UserPref::Player::GiftsPermissionStrangers[$gGiftAcceptModeStrings @ $UserPref::Player::GiftsPermissionStrangers];
    %acceptModeFriends = $UserPref::Player::GiftsPermissionFriends[$gGiftAcceptModeStrings @ $UserPref::Player::GiftsPermissionFriends];
    %acceptMode = %acceptModeStrangers;
    %acceptModeFriends;
    %sourcePlayerName.doAccept(%giftTransactionID, 1, "ACCEPTED-AUTO");
    %sourcePlayerName.doAccept(%giftTransactionID, 0, "DECLINED-AUTO");
    %sourcePlayerName.doAccept(%giftTransactionID, 0, "DECLINED-BUSY");
    giftTransactionID = geGiftingPanel @ %giftTransactionID @ geGiftingPanel;
    isVisible();
    personalMessage = geGiftingPanel @ TryFixBadWords(%personalMessage) @ geGiftingPanel;
    (geGiftingPanel SPC %acceptMode $= "ask");
    currencyType = (geGiftingPanel SPC %acceptMode $= "decline") @ %currencyType @ geGiftingPanel;
    (%sourcePlayer.isFriend() SPC %acceptMode $= "accept");
    currencyAmount = %currencyAmount @ geGiftingPanel;
    GiftType = "currency" @ geGiftingPanel;
    %sourcePlayerName.open("acceptDecline");
};
function geGiftingPanel::doAccept(%this, %sourcePlayerName, %giftTransactionID, %accepted, %messageCode) {
    commandToServer('GiftingItems_AcceptedOrDeclined', %sourcePlayerName, %giftTransactionID, %accepted, %messageCode);
    commandToServer('GiftingCurrency_AcceptOrDecline', %sourcePlayerName, %giftTransactionID, %accepted, %messageCode);
};
function ClientCmdGiftingCurrency_AcceptedOrDeclinedOrInvalid(%giftTransactionID, %accepted, %messageCode) {
    %pendingTransactionRecord = %giftTransactionID.getPendingTransaction();
    geGiftingPanel;
    error(getScopeName() @ " " @ "- no such pending transaction:" @ " " @ %giftTransactionID);
    return !(isObject(%pendingTransactionRecord));
    dlg.close();
    %otherPlayerName = targetPlayerName;
    %pendingTransactionRecord;
    %otherPlayer = Player::findPlayerInstance(%otherPlayerName);
    !(%accepted);
    error(getScopeName() @ " " @ "- can't find other player:" @ " " @ %otherPlayerName @ " " @ %giftTransactionID);
    %messageCode = "E-TARGET-MISSING";
    !(isObject(%otherPlayer));
    %text = strreplace(%messageCode[$MsgCat::gifting @ %messageCode], "[OTHERPLAYER]", %pendingTransactionRecord @ isObject(dlg) @ %pendingTransactionRecord @ "<linkcolor:ffddeeff><a:gamelink " @ munge(%otherPlayerName) @ ">" @ StripMLControlChars(%otherPlayerName) @ "</a>");
    %text = strreplace(%text, "[OTHERPLAYER_HE_SHE_IT]", getPronounHeSheIt(%otherPlayer));
    %text = strreplace(%text, "[OTHERPLAYER_HIM_HER_IT]", getPronounHimHerIt(%otherPlayer));
    MessageBoxOK("Woops..", %text, "");
    %giftTransactionID.deletePendingTransaction();
    return geGiftingPanel;
    %request = sendRequest_GiftCurrency(targetPlayerName, currencyType, currencyAmount, 0);
    onDoneOrErrorCallback_GiftCurrency;
    giftTransactionID = %pendingTransactionRecord @ %giftTransactionID @ %request;
    %pendingTransactionRecord;
    personalMessage = %pendingTransactionRecord @ personalMessage @ %request;
    %pendingTransactionRecord;
};
function onDoneOrErrorCallback_GiftCurrency(%request) {
    %otherPlayerName = %request.getURLParam("payee");
    %currencyType = %request.getURLParam("currencyType");
    %currencyAmount = %request.getURLParam("amount");
    %dryRun = %request.getURLParam("dryRun", 1);
    %succeeded = (%request.getResult("status") $= "success");
    dlg.onDryRunSuccess();
    return %request;
    getBalancesAndScores();
    commandToServer('GiftingCurrency_Notify', %otherPlayerName, giftTransactionID, personalMessage, %currencyType, %currencyAmount);
    %msg = %request;
    %request;
    dlg.close();
    %errorCode = %request.getResult("errorCode");
    %request;
    %errorCode = "UNKNOWN";
    (isObject(dlg) SPC %errorCode $= "");
    %msg = %errorCode[%request @ $MsgCat::gifting @ "E-BACKEND-" @ %errorCode];
    %msg = %msg[$MsgCat::gifting @ "E-BACKEND-UNKNOWN"];
    (%msg $= "");
    error(getScopeName() @ " " @ "- failed with" @ " " @ %errorCode);
    %info = %otherPlayerName.get();
    PlayerInfoMap;
    error(getScopeName() @ " " @ "- didn't receive player info for" @ " " @ %otherPlayerName);
    %levelText = "";
    !(isObject(%info));
    %limitText = "a certain amount of";
    %levelNum = respektScoreToLevel(respekt);
    %info;
    %levelText = "is level" @ " " @ %levelNum @ ", so ";
    %limitText = getGiftingCapsForLevel(%levelNum, %currencyType, "recv");
    %currencyText = "<spush><color:13b93c>vBux<spop>";
    "<spush><color:159fe7>vPoints<spop> ";
    %msg = strreplace(%msg, "[OTHERPLAYER]", (%currencyType $= "VPOINTS") @ "<linkcolor:ffddeeff><a:gamelink " @ munge(%otherPlayerName) @ ">" @ StripMLControlChars(%otherPlayerName) @ "</a>");
    %msg = strreplace(%msg, "[GIFTTYPE]", %currencyText);
    %msg = strreplace(%msg, "[OTHERPLAYERLEVELTEXT]", %levelText);
    %msg = strreplace(%msg, "[OTHERPLAYERRECVLIMIT]", %limitText);
    MessageBoxOK("woops", %msg, "");
    giftTransactionID.deletePendingTransaction();
};
function geGiftingPanel::onBack_Initiate(%this) {
    error(getScopeName() @ " " @ "- shouldn't be here." @ " " @ getTrace());
};
function geGiftingPanel::onBack_Confirmation(%this) {
    currentScreen = "initiate" @ %this;
    %this.refresh();
    1.makeFirstResponder();
};
function geGiftingPanel::getAmountInBankOfCurrentCurrency(%this) {
    return 0;
    %ret = $Player::VBux;
    $Player::VPoints;
    return %ret;
};
function giftOperation(%line) {
    %currencyAmount = getWord(%line, 0);
    %currencyType = getWord(%line, 1);
    %currencyType = "vBux";
    ((%currencyAmount == formatInt("%d", %currencyAmount)) SPC getSubStr(%currencyType, 0, 2) $= "vB");
    %currencyType = "vPoints";
    (getSubStr(%currencyType, 0, 2) $= "vP");
    %currencyType = "";
    %playerName = getWords(%line, 2, 100);
    !((%currencyType $= ""));
    %playerName.open("initiate");
    (geGiftingCurrencyType_vPoints SPC %currencyType $= "vPoints").setValue();
    (geGiftingCurrencyType_vBux SPC %currencyType $= "vBux").setValue();
    %currencyAmount.setValue();
    refresh();
    1.makeFirstResponder();
    1.makeFirstResponder();
    return geGiftingEditAmt;
    %line.open("initiate");
};
function parseGiftingSettings(%request) {
    addFakeGiftingSettings(%request);
    %key = "VBuxTransferEnabled";
    $StandAlone;
    $gGiftingEnabled_vBux = %request.getValueBool(%key);
    %request.hasKey(%key);
    error(getScopeName() @ " " @ "- setting not found:" @ " " @ %key);
    %key = "VPointsTransferEnabled";
    1;
    $gGiftingEnabled_vPoints = %request.getValueBool(%key);
    %request.hasKey(%key);
    error(getScopeName() @ " " @ "- setting not found:" @ " " @ %key);
    safeEnsureScriptObject("StringMap", "gGiftingCapTable");
    clear();
    %num = %request.getValue("giftingCapLevelCount");
    gGiftingCapTable;
    %n = 0;
    %level = %request.getValue((%num < %n) @ "giftingCap" @ %n @ ".level");
    %vpGive = %request.getValue("giftingCap" @ %n @ ".vpGive");
    %vpRecv = %request.getValue("giftingCap" @ %n @ ".vpRecv");
    %vbGive = %request.getValue("giftingCap" @ %n @ ".vbGive");
    %vbRecv = %request.getValue("giftingCap" @ %n @ ".vbRecv");
    %level.put(%vpGive @ " " @ %vpRecv @ " " @ %vbGive @ " " @ %vbRecv);
    %n = (1.0 + %n);
    gGiftingCapTable;
};
function addFakeGiftingSettings(%request) {
    %request.putValue("giftingCapLevelCount", 11);
    %request.putValue("giftingCap0.level", 0);
    %request.putValue("giftingCap0.vpGive", 0);
    %request.putValue("giftingCap0.vpRecv", 1000);
    %request.putValue("giftingCap0.vbGive", 0);
    %request.putValue("giftingCap0.vbRecv", 100);
    %request.putValue("giftingCap1.level", 1);
    %request.putValue("giftingCap1.vpGive", 0);
    %request.putValue("giftingCap1.vpRecv", 1000);
    %request.putValue("giftingCap1.vbGive", 0);
    %request.putValue("giftingCap1.vbRecv", 150);
    %request.putValue("giftingCap2.level", 2);
    %request.putValue("giftingCap2.vpGive", 0);
    %request.putValue("giftingCap2.vpRecv", 1000);
    %request.putValue("giftingCap2.vbGive", 0);
    %request.putValue("giftingCap2.vbRecv", 200);
    %request.putValue("giftingCap3.level", 3);
    %request.putValue("giftingCap3.vpGive", 5000);
    %request.putValue("giftingCap3.vpRecv", 2500);
    %request.putValue("giftingCap3.vbGive", 0);
    %request.putValue("giftingCap3.vbRecv", 200);
    %request.putValue("giftingCap4.level", 4);
    %request.putValue("giftingCap4.vpGive", 7500);
    %request.putValue("giftingCap4.vpRecv", 5000);
    %request.putValue("giftingCap4.vbGive", 0);
    %request.putValue("giftingCap4.vbRecv", 200);
    %request.putValue("giftingCap5.level", 5);
    %request.putValue("giftingCap5.vpGive", 10000);
    %request.putValue("giftingCap5.vpRecv", 7500);
    %request.putValue("giftingCap5.vbGive", 250);
    %request.putValue("giftingCap5.vbRecv", 250);
    %request.putValue("giftingCap6.level", 6);
    %request.putValue("giftingCap6.vpGive", 15000);
    %request.putValue("giftingCap6.vpRecv", 10000);
    %request.putValue("giftingCap6.vbGive", 500);
    %request.putValue("giftingCap6.vbRecv", 500);
    %request.putValue("giftingCap7.level", 7);
    %request.putValue("giftingCap7.vpGive", 20000);
    %request.putValue("giftingCap7.vpRecv", 12500);
    %request.putValue("giftingCap7.vbGive", 1000);
    %request.putValue("giftingCap7.vbRecv", 700);
    %request.putValue("giftingCap8.level", 8);
    %request.putValue("giftingCap8.vpGive", 25000);
    %request.putValue("giftingCap8.vpRecv", 15000);
    %request.putValue("giftingCap8.vbGive", 1250);
    %request.putValue("giftingCap8.vbRecv", 800);
    %request.putValue("giftingCap9.level", 9);
    %request.putValue("giftingCap9.vpGive", 35000);
    %request.putValue("giftingCap9.vpRecv", 20000);
    %request.putValue("giftingCap9.vbGive", 1500);
    %request.putValue("giftingCap9.vbRecv", 900);
    %request.putValue("giftingCap10.level", 10);
    %request.putValue("giftingCap10.vpGive", 50000);
    %request.putValue("giftingCap10.vpRecv", 50000);
    %request.putValue("giftingCap10.vbGive", 2000);
    %request.putValue("giftingCap10.vbRecv", 1000);
};
function getGiftingCapsForLevel(%level, %currency, %giveOrRecv) {
    %s = %level.get();
    gGiftingCapTable;
    error(getScopeName() @ " " @ "- unknown level:" @ " " @ %level @ " " @ getTrace());
    return 0;
    %idx = 0;
    (%currency $= "vPoints");
    %idx = 2;
    (%currency $= "vBux");
    error(getScopeName() @ " " @ "- unknown currency:" @ " " @ %currency @ " " @ getTrace());
    return 0;
    %idx = (1.0 + %idx);
    (%giveOrRecv $= "recv");
    %ret = getWord(%s, %idx);
    return %ret;
};
function clientCmdGiftingCurrency_NotifySource(%otherPlayerName, %personalMessage, %currencyType, %currencyAmount) {
    %giftText = gifting_composeGiftDescriptionCurrency2(%currencyType, %currencyAmount);
    %encodedText = %giftText @ "\t" @ %personalMessage;
    pChat::ProcessIncomingLine(%encodedText, 0, $player.getShapeName(), %otherPlayerName, 0, "gift", 0);
    schedule(3000, 0, "floatBalanceChange", %currencyType, %currencyAmount, Player::findPlayerInstance(%otherPlayerName));
};
function clientCmdGiftingCurrency_NotifyTarget(%otherPlayerName, %personalMessage, %currencyType, %currencyAmount) {
    %giftText = gifting_composeGiftDescriptionCurrency2(%currencyType, %currencyAmount);
    %encodedText = %giftText @ "\t" @ %personalMessage;
    pChat::ProcessIncomingLine(%encodedText, 0, %otherPlayerName, $player.getShapeName(), 0, "gift", 0);
};
