class = geHighScoresPanelTabs @ new () @ "TabControl";
ScriptObject;
0;
add();
function toggleHighScoresPanel() {
    toggleVisibleState();
};
safeEnsureScriptObject("StringMap", "HumanReadableGameNamesMap");
"TheGrind".put("The Grind");
"Materiel".put("Materiel");
"Sumo".put("Sumo");
function geHighScoresPanel::open(%this, %gameName, %gameStationId) {
    %this.Initialize();
    %this.setVisible(1);
    %this.focusAndRaise();
    selectCurrentTab();
    gameName = geHighScoresPanelTabs @ %gameName @ %this;
    PlayGui;
    gameStationId = HumanReadableGameNamesMap @ %gameStationId @ %this;
    HumanReadableGameNamesMap;
    %humanReadableGameName = gameName.get();
    %this;
    %colon = ": ";
    "";
    (HumanReadableGameNamesMap SPC %humanReadableGameName $= "") @ geHighScoresTitleText @ "High Scores" @ %colon @ %humanReadableGameName.setText();
    %request = sendRequest_GetHighGameScores($Player::Name, gameName, 0, 25, "onDoneOrErrorCallback_GetHighGameScores");
    %this;
    global = HumanReadableGameNamesMap @ 1 @ %request;
    %this.requestStarted();
    %request = sendRequest_GetHighGameScoresForStation($Player::Name, gameStationId, 0, 25, "onDoneOrErrorCallback_GetHighGameScores");
    %this;
    global = 0 @ %request;
    %this.requestStarted();
};
function clientCmdOpenHighScoresFor(%gameName, %gameStationId) {
    %gameName.open(%gameStationId);
};
function geHighScoresPanel::close(%this) {
    %this.setVisible(0);
    focusTopWindow();
    return 1;
};
function geHighScoresPanel::Initialize(%this) {
    setup();
    requestsPending = !(isObject(waitIcon)) @ 0 @ %this;
    %this;
    waitIcon = geHighScoresPanelTabs @ AnimCtrl::newAnimCtrl("457 24", "18 18") @ %this;
    waitIcon.setDelay(60);
    waitIcon.addFrame("platform/client/ui/wait0.png");
    waitIcon.addFrame("platform/client/ui/wait1.png");
    waitIcon.addFrame("platform/client/ui/wait2.png");
    waitIcon.addFrame("platform/client/ui/wait3.png");
    waitIcon.addFrame("platform/client/ui/wait4.png");
    waitIcon.addFrame("platform/client/ui/wait5.png");
    waitIcon.addFrame("platform/client/ui/wait6.png");
    waitIcon.addFrame("platform/client/ui/wait7.png");
    waitIcon.setVisible(0);
    %this.add(waitIcon);
};
function geHighScoresPanel::requestStarted(%this) {
    requestsPending = (%this + requestsPending);
    1.0;
    waitIcon.setVisible(1);
    waitIcon.start();
};
function geHighScoresPanel::requestStopped(%this) {
    requestsPending = (%this - requestsPending);
    1.0;
    requestsPending = (%this <= requestsPending) @ 0 @ %this;
    0.0;
    waitIcon.stop();
    waitIcon.setVisible(0);
};
function onDoneOrErrorCallback_GetHighGameScores(%request) {
    requestStopped();
    %global = global;
    %request;
    %tabName = "This Machine";
    "Global";
    %tab = %tabName.getTabWithName();
    geHighScoresPanelTabs;
    error(getTrace() @ " " @ "tab with name" @ " " @ %tabName @ " " @ "not found!");
    return !(isObject(%tab));
    %dataTable = DataTable;
    %tab;
    %dataTable.removeRowsByIndex(0, %dataTable.getRowCount());
    %count = %request.getValue("scores.scoresCount");
    %dataTable.addRows(%count);
    %userRanking = "";
    %userScore = "";
    %userScoreDate = "";
    %i = 0;
    %prefix = (%count < %i) @ "scores.scores" @ %i;
    %score = %request.getValue(%prefix @ ".score");
    %scoreRanking = %request.getValue(%prefix @ ".scoreRanking");
    %userName = %request.getValue(%prefix @ ".userName");
    %dateAttained = %request.getValue(%prefix @ ".dateAttained");
    %userRanking = %scoreRanking;
    ((%userName $= $Player::Name) SPC %userRanking $= "");
    %userScore = %score;
    %userScoreDate = %dateAttained;
    %style = "UserName_Normal";
    "UserName_Friend";
    %rowData = "rank" @ "\t" @ %scoreRanking @ "\t" @ %scoreRanking @ "\n" @ "avatar" @ "\t" @ %userName @ "\t" @ "platform/client/ui/tgf/tgf_profile_default" @ "\n" @ "username" @ "\t" @ %userName @ "\t" @ mlStyle(%userName, %style) @ "\n" @ "date" @ "\t" @ %dateAttained @ "\t" @ %dateAttained @ "\n" @ "score" @ "\t" @ %score @ "\t" @ %score;
    (BuddyHudWin SPC %userName.getFriendStatus() $= "friends");
    %dataTable.setRowDataByIndex(%i, %rowData);
    %rowData = "avatar" @ "\t" @ %userName @ "\t" @ $Net::AvatarURL @ urlEncode(%userName) @ "?size=S";
    %dataTable.setRowDataByIndex(%i, %rowData);
    %i = (1.0 + %i);
    %dataTable.updateListeners();
    %userRanking = %request.getValue("scores.userRanking");
    ((%count < %i) SPC %userRanking $= "");
    %userScore = %request.getValue("scores.userScore");
    %userScoreDate = %request.getValue("scores.userScoreDate");
    %hrGameName = gameName.get();
    geHighScoresPanel;
    %text = %global @ HumanReadableGameNamesMap @ "You have no score for " @ %hrGameName @ ".";
    (%userRanking $= "");
    %text = "You have no score on this machine.";
    noScoreText.setText(%text);
    noScoreText.setVisible(1);
    userScoresPanel.setVisible(0);
    usernameField.setText(%tab @ "<clip:111>" @ $Player::Name);
    bestScoreField.setText(%userScore);
    rankField.setText(%userRanking);
    dateField.setText(%userScoreDate);
    noScoreText.setVisible(0);
    userScoresPanel.setVisible(1);
};
function geHighScoresPanelTabs::createButton(%this, %bitmapName, %tab, %name) {
    profile = GuiBitmapButtonCtrl @ new ""() @ "ClipboardTabButtonProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = %this @ buttonSize;
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    command = %this.getId() @ ".selectTab(" @ %tab.getId() @ ");";
    text = %name;
    groupNum = -1;
    buttonType = "PushButton";
    bitmap = %bitmapName;
    helpTag = 0;
    drawText = 1;
    return;
};
function geHighScoresPanelTabs::setup(%this) {
    %this.Initialize("109 25", "", "0 0", "horizontal");
    %this.newTab("This Machine", "platform/client/buttons/clipboard_tab");
    %this.newTab("Global", "platform/client/buttons/clipboard_tab");
    %this.selectTabWithName("This Machine");
    %this.fillTabs();
};
function geHighScoresPanelTabs::fillTabs(%this) {
    %this.fillTabWithName("This Machine");
    %this.fillTabWithName("Global");
};
function geHighScoresPanelTabs::fillTabWithName(%this, %tabName) {
    %tab = %this.getTabWithName(%tabName);
    return !(isObject(%tab));
    %tab.setProfile();
    %dataTable = new ""();
    DataTable;
    DataTable = 0 @ %dataTable @ %tab;
    ClipboardProfile;
    %dataTable.addColumn("rank", "Rank", "number", 30);
    %dataTable.addColumn("avatar", "", "image", 20, 0);
    %dataTable.addColumn("username", "Name", "string", 150);
    %dataTable.addColumn("date", "Date", "string", 180);
    %dataTable.addColumn("score", "High Score", "number", 70);
    position = GuiTableCtrl @ new ""() @ "5 5";
    0;
    extent = "460 372";
    horizSizing = "width";
    vertSizing = "height";
    visible = 1;
    spacing = 2;
    %guiTable = ;
    %guiTable.bindClassName("geHighScoresGuiTable");
    %guiTable.setChildrenExtents(17);
    %guiTable.setDataTable(%dataTable);
    GuiTable = %guiTable @ %tab;
    %tab.add(%guiTable);
    %guiTable.setHeaderCellProfile();
    %guiTable.setHeaderCellButtonProfile();
    %guiTable.setHeaderCellMLTextProfile();
    profile = GuiControl @ new ""() @ "GuiDefaultProfile";
    0;
    horizSizing = ClipboardHeaderCellButtonProfile @ ClipboardHeaderMLTextProfile @ "width";
    ClipboardHeaderCellProfile;
    vertSizing = "top";
    position = "5 380";
    extent = "460 50";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    %userScoresPanel = ;
    userScoresPanel = %userScoresPanel @ %tab;
    %tab.add(%userScoresPanel);
    profile = GuiTextCtrl @ new ""() @ "ClipboardTextProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "55 18";
    minExtent = "l l";
    sluggishness = -1;
    visible = 1;
    text = "Player Name: ";
    maxLength = 255;
    %userScoresPanel.add();
    profile = GuiMLTextCtrl @ new ""() @ "ClipboardTextProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "70 2";
    extent = "111 18";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = "";
    %usernameField = ;
    usernameField = %usernameField @ %tab;
    %userScoresPanel.add(%usernameField);
    profile = GuiTextCtrl @ new ""() @ "ClipboardTextProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "200 0";
    extent = "55 18";
    minExtent = "l l";
    sluggishness = -1;
    visible = 1;
    text = "Best Score: ";
    maxLength = 255;
    %userScoresPanel.add();
    profile = GuiTextCtrl @ new ""() @ "ClipboardTextProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "305 0";
    extent = "55 18";
    minExtent = "l l";
    sluggishness = -1;
    visible = 1;
    text = "";
    maxLength = 255;
    %bestScoreField = ;
    bestScoreField = %bestScoreField @ %tab;
    %userScoresPanel.add(%bestScoreField);
    profile = GuiTextCtrl @ new ""() @ "ClipboardTextProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 25";
    extent = "55 18";
    minExtent = "l l";
    sluggishness = -1;
    visible = 1;
    text = "Rank: ";
    maxLength = 255;
    %userScoresPanel.add();
    profile = GuiTextCtrl @ new ""() @ "ClipboardTextProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "70 25";
    extent = "55 18";
    minExtent = "l l";
    sluggishness = -1;
    visible = 1;
    text = "";
    maxLength = 255;
    %rankField = ;
    rankField = %rankField @ %tab;
    %userScoresPanel.add(%rankField);
    profile = GuiTextCtrl @ new ""() @ "ClipboardTextProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "200 25";
    extent = "55 18";
    minExtent = "l l";
    sluggishness = -1;
    visible = 1;
    text = "Date of Best Score: ";
    maxLength = 255;
    %userScoresPanel.add();
    profile = GuiTextCtrl @ new ""() @ "ClipboardTextProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "305 25";
    extent = "55 18";
    minExtent = "l l";
    sluggishness = -1;
    visible = 1;
    text = "";
    maxLength = 255;
    %dateField = ;
    dateField = %dateField @ %tab;
    %userScoresPanel.add(%dateField);
    profile = GuiTextCtrl @ new ""() @ "ClipboardTextProfile";
    0;
    horizSizing = "right";
    vertSizing = "top";
    position = "5 380";
    extent = "55 18";
    minExtent = "l l";
    sluggishness = -1;
    visible = 0;
    text = "";
    maxLength = 255;
    %noScoreText = ;
    noScoreText = %noScoreText @ %tab;
    %tab.add(%noScoreText);
};
function geHighScoresGuiTable::doSetupRowGuiArray(%this, %rowArray) {
    Parent::doSetupRowGuiArray(%this, %rowArray);
    DataTable = %this.getDataTable() @ %rowArray;
    %rowArray.bindClassName("geHighScoresGuiTableRow");
};
function geHighScoresGuiTable::onRowSelected(%this, %unused, %rowIndex, %unused, %unused) {
    %cellIndex = %this.getDataTable().getColumnIndex("username");
    %userName = %this.getDataTable().getCellSortValue(%rowIndex, %cellIndex);
    onLeftClickPlayerName(%userName, "");
};
function geHighScoresGuiTableRow::onRightMouseUp(%this) {
    %rowIndex = %this.getParent().getObjectIndex(%this);
    %cellIndex = DataTable.getColumnIndex("username");
    %this;
    %userName = DataTable.getCellSortValue(%rowIndex, %cellIndex);
    %this;
    onRightClickPlayerName(%userName);
};
