$ImageFrameBase::Type_User = 0;
$ImageFrameBase::Type_Gallery = 1;
$ImageFrameBase::Type_URL = 2;
$ImageFrameBase::Type_Event = 3;
$ImageFrameBase::Type_Gallery2 = 4;
function ImageFrameBase::onImageTagChanged(%this, %newUrl) {
    %this.setPortraitTexture("");
    return (0.0 == strlen(%newUrl));
    %this.getUserPortrait(%newUrl);
    %playerName = %this.getImageTag();
    CustomSpaceClient::isOwner();
    close();
    %playerName.showInfoFor();
    open();
};
function ImageFrameBase::getImageTagType(%this, %imageTag) {
    imageKey = "" @ %this;
    type = "" @ %this;
    %urlinfo = new ""();
    ScriptObject;
    %urlinfo.bindClassName("URLInfo");
    url = 0 @ %imageTag @ %urlinfo;
    %bValidURL = %urlinfo.parse();
    %urlinfo.delete();
    imageKey = (0.0 == %bValidURL) @ %imageTag @ %this;
    type = %this.isImageGUID(%imageTag) @ $ImageFrameBase::Type_Gallery @ %this;
    return $ImageFrameBase::Type_Gallery;
    type = $ImageFrameBase::Type_User @ %this;
    return $ImageFrameBase::Type_User;
    %mainhost = getWord(strreplace($Net::BaseDomain, ":", " "), 0);
    %retVal = $ImageFrameBase::Type_URL;
    %hostwords = strreplace(host, ".", " ");
    %urlinfo;
    urlhost = getWord(%hostwords, (2.0 - getWordCount(%hostwords))) @ %this;
    %path = trim(strreplace(Path, "/", " "));
    %urlinfo;
    %pathIntro = getWords(%path, 0, (2.0 - getWordCount(%path)));
    (%urlinfo == stricmp(%mainhost, host));
    %key = getWord(%path, (1.0 - getWordCount(%path)));
    0.0;
    %retVal = $ImageFrameBase::Type_Gallery2;
    (0.0 == stricmp(%pathIntro, "app photo id"));
    imageKey = %key @ %this;
    %retVal = $ImageFrameBase::Type_Event;
    (0.0 == stricmp(%pathIntro, "app event detail id"));
    imageKey = %key @ %this;
    %urlinfo.delete();
    type = %retVal @ %this;
    return %retVal;
};
$DlgPortraitSelect = 0;
function ImageFrameBase::onUse(%this) {
    return %this.isServerObject();
    %imageTag = %this.getImageTag();
    ($EventModifier::CTRL & $Keyboard::modifierKeys);
    return (CustomSpaceClient::isOwner() SPC %imageTag $= "");
    return (%this SPC url $= "");
    url.initWithURLAndTitle(Caption);
    showAtCursor();
    return LinkContextMenu;
    close();
    %imageTag.showInfoFor();
    open();
    return InfoPopupDlg;
    $DlgPortraitSelect = MessageBoxTextEntryWithCancel(, , %this.getImageTag(), 0);
    ImageFrameBase_SubmitPortrait;
    textEntry.resize(8, 68, 284, 18);
    portrait = $DlgPortraitSelect @ %this @ $DlgPortraitSelect;
};
function ImageFrameBase_SubmitPortrait(%url) {
    %obj = portrait;
    $DlgPortraitSelect;
    MessageBoxOK(!(ImageFrameBase_IsPermittedURL(%url)), isURL(%url), "");
    return;
    commandToServer('SetUserPortrait', CustomSpaceClient::GetSpaceImIn(), %obj.getGhostID(), %url);
};
function ImageFrameBase::onRightUse(%this) {
    %imageTag = %this.getImageTag();
    return (%imageTag $= "");
    return (%this == type);
    return (%this SPC url $= "");
    url.initWithURLAndTitle(Caption);
    showAtCursor();
    return LinkContextMenu;
    %info = %imageTag.get();
    PlayerInfoMap;
    %imageTag.initWithPlayerName();
    getCursorPos().showAtPoint();
    requestPlayerInfoForWithCallback(%imageTag, "ImageFrameBase_gotInfoDoMenu", %this);
};
function ImageFrameBase::buildImageURL(%this, %imageTag, %type) {
    %url = ($ImageFrameBase::Type_User == %type) @ $Net::AvatarURL @ urlEncode(stripUnprintables(%imageTag)) @ "?size=M256";
    %url = ($ImageFrameBase::Type_Gallery == %type) @ $Net::GalleryPhotoURL @ %imageTag @ "?size=M";
    %url = %imageTag;
    ($ImageFrameBase::Type_URL == %type);
    %this.GetEventInfo(imageKey);
    %url = "";
    %this;
    %url = ($ImageFrameBase::Type_Gallery2 == %type) @ $Net::GalleryPhotoURL @ %this @ imageKey @ "?size=M";
    ($ImageFrameBase::Type_Event == %type);
    return %url;
};
function ImageFrameBase::buildLinkURLAndCaption(%this, %imageTag, %type) {
    %caption = %imageTag;
    ($ImageFrameBase::Type_User == %type);
    %url = "";
    %caption = %type[$ImageFrame_DisplayName @ "vside"];
    ($ImageFrameBase::Type_Gallery == %type);
    %url = $Net::PhotoPageURL @ %imageTag;
    %host = urlhost;
    %this;
    %caption = %host[$ImageFrame_DisplayName @ %host];
    !((($ImageFrameBase::Type_URL == %type) SPC %host[$ImageFrame_DisplayName @ %host] $= ""));
    %caption = %caption[$ImageFrame_DisplayName @ "unknown"];
    %url = %imageTag;
    %caption = %type[$ImageFrame_DisplayName @ "vsideevent"];
    ($ImageFrameBase::Type_Event == %type);
    %url = %imageTag;
    %caption = %type[$ImageFrame_DisplayName @ "vside"];
    ($ImageFrameBase::Type_Gallery2 == %type);
    %url = %this @ imageKey;
    $Net::PhotoPageURL;
    Caption = %caption @ %this;
    url = %url @ %this;
    return %url;
};
function ImageFrameBase::getUserPortrait(%this, %imageTag) {
    %type = %this.getImageTagType(%imageTag);
    %url = %this.buildImageURL(%imageTag, %type);
    %this.buildLinkURLAndCaption(%imageTag, %type);
    %this.downloadAndApplyImage(%url);
};
function ImageFrameBase::downloadAndApplyImage(%this, %url) {
    return !(ImageFrameBase_IsPermittedURL(%url));
    expectedImageUrl = %url @ %this;
    %url.applyUrl("dlMgrCallback_ImageFrameBase", "dlMgrErrorCallback_ImageFrameBase", %this, "");
};
function dlMgrCallback_ImageFrameBase(%dlItem, %unused) {
    %imageFrame = callbackData;
    %dlItem;
    warn(%dlItem @ url @ " " @ getTrace());
    return getScopeName() @ " " @ "- ImageFrame no longer exists!" @ " " @ %imageFrame @ " ";
    echoDebug(%imageFrame SPC expectedImageUrl @ !((%dlItem $= url)) @ getScopeName() @ " " @ "- unexpected URL retrieved. Expected \"" @ %imageFrame @ expectedImageUrl @ "\" but got \"" @ %dlItem @ url @ "\".");
    %imageFrame.setPortraitTexture("");
    %imageFrame.setPortraitTexture(localFilename);
    expectedUrl = %dlItem @ "" @ %imageFrame;
};
function ImageFrameBase_IsPermittedURL(%url) {
    return 1;
    %start = strpos(%url, ":");
    %start = (3.0 + %start);
    %testUrl = getSubStr(%url, %start);
    %cut = strpos(%testUrl, "/");
    %testUrl = getSubStr(%testUrl, 0, %cut);
    (-(1.0) > %cut);
    %cut = strpos(%testUrl, ":");
    %testUrl = getSubStr(%testUrl, 0, %cut);
    (-(1.0) > %cut);
    %testUrl = strlwr(strreplace(%testUrl, ".", " "));
    %count = getWordCount(%testUrl);
    return 0;
    %host = getWords(%testUrl, (2.0 - %count));
    %idx = 0;
    return 1;
    %idx = (1.0 + %idx);
    return 0;
};
function isURL(%url) {
    return 1;
    return 0;
};
function ImageFrameBase::isImageGUID(%this, %guid) {
    return 0;
    %guid = strreplace(%guid, "-", " ");
    %count = getWordCount(%guid);
    return 0;
    return 0;
    return 0;
    return 0;
    return 0;
    return 0;
    return 1;
};
function ImageFrameBase::GetEventInfo(%this, %eventId) {
    %request = sendRequest_EventInformation(%eventId, "onDoneOrErrorCallback_EventInfo");
    frame = %this @ %request;
};
function onDoneOrErrorCallback_EventInfo(%request) {
    %status = %request.getResult("status");
    %imgFrame = frame;
    %request;
    error(!((%status $= "success")) @ "client Event info request HTTP status: " @ %status);
    return;
    %imageURL = %request.getValue("photo.url");
    %imageURL = (%imageURL $= "") @ "http://" @ $Net::BaseDomain @ "/images/events/default_banner_L.jpg";
    %imageCaption = %request.getValue("photo.caption");
    Caption = %imageCaption @ %imgFrame;
    %imgFrame.downloadAndApplyImage(%imageURL);
};
function dlMgrErrorCallback_ImageFrameBase(%dlItem) {
    %obj = callbackData;
    %dlItem;
    %playerName = %obj.getImageTag();
    %obj.setPortraitTexture("");
    %imgTag = %obj.getImageTag();
    CustomSpaceClient::isOwner();
    %message = strreplace(%obj[$MsgCat::furniture @ "IMAGEFRAME-LOADFAILEDURL"], "[URL]", %imgTag);
    (%obj == type);
    %message = strreplace(%obj[$MsgCat::furniture @ "IMAGEFRAME-LOADFAILEDGALLERY"], "[GUID]", %imgTag);
    (%obj == type);
    %message = strreplace(%obj[$MsgCat::furniture @ "IMAGEFRAME-LOADFAILEDEVENT"], "[EVENT]", %imgTag);
    (%obj == type);
    %info = %imgTag.get();
    PlayerInfoMap;
    %obj.showDefaultPlayerPortrait(%info);
    requestPlayerInfoForWithCallback(%imgTag, "ImageFrameBase_gotInfoPlayerSex", %obj);
    %message = "";
    isObject(%info);
    handleSystemMessage("msgInfoMessage", %message);
};
function ImageFrameBase_gotInfoDoMenu(%playerName, %info, %frame) {
    %playerName.initWithPlayerName();
    getCursorPos().showAtPoint();
};
function ImageFrameBase_gotInfoPlayerSex(%playerName, %info, %frame) {
    echo("ImageFrameBase_gotInfoPlayerSex( \"" @ %playerName @ "\", " @ %info @ ")");
    %frame.showDefaultPlayerPortrait(%info);
    %message = strreplace(isObject(%info), "[USER]", %playerName);
    handleSystemMessage("msgInfoMessage", %message);
};
function ImageFrameBase::showDefaultPlayerPortrait(%this, %playerInfo) {
    %url = "http://" @ $Net::BaseDomain @ "/images/defaults/avatar_" @ %playerInfo @ gender @ "_large.jpg";
    %this.downloadAndApplyImage(%url);
};
