function InfoPopupDlg::open(%this) {
    %this.init();
    "affinity".selectTabWithName();
};
function InfoPopupDlg::close(%this) {
    close();
};
function InfoPopupDlg::onClose(%this) {
    %this.clear();
};
function InfoPopupDlg::isShowing(%this) {
    return (getCurrentTab() SPC name $= "affinity");
};
function InfoPopupDlg::init(%this) {
    waitIcon = !(initialized) @ AnimCtrl::newAnimCtrl("91 36", "18 18") @ %this;
    %this;
    waitIcon.setDelay(60);
    waitIcon.addFrame("platform/client/ui/wait0.png");
    waitIcon.addFrame("platform/client/ui/wait1.png");
    waitIcon.addFrame("platform/client/ui/wait2.png");
    waitIcon.addFrame("platform/client/ui/wait3.png");
    waitIcon.addFrame("platform/client/ui/wait4.png");
    waitIcon.addFrame("platform/client/ui/wait5.png");
    waitIcon.addFrame("platform/client/ui/wait6.png");
    waitIcon.addFrame("platform/client/ui/wait7.png");
    %this.add(waitIcon);
    waitIcon.setVisible(0);
    initialized = %this @ 1 @ %this;
    %this;
    playerName = %this @ "" @ %this;
    %this;
    %this.clear();
};
function InfoPopupDlg::clear(%this) {
    "".setText();
    "Click on a player or player's name to see information about them.".setText();
    0.setVisible();
    "".setText();
};
function InfoPopupDlg::showInfoFor(%this, %playerName) {
    %this.open();
    "Sorry," @ " " @ %playerName @ " " @ "doesn't have info..".setText();
    "".setText();
    "".setText();
    waitIcon.stop();
    waitIcon.setVisible(0);
    return %this;
    playerName = %playerName @ %this;
    %this.tryShowPlayerInfo();
};
function InfoPopupDlg::tryShowPlayerInfo(%this) {
    %this.init();
    %tableSettings = "<tab:88,215>";
    %fieldOpen = "" @ "\t" @ "<spush>";
    %fieldClose = "<spop>";
    echoDebug("tryShowPlayerInfo(): No playerName set.");
    return (%this SPC playerName $= "");
    %playerName = StripMLControlChars(playerName);
    %this;
    gSetField(%this, %playerName);
    %info = %playerName.get();
    PlayerInfoMap;
    waitIcon.stop();
    waitIcon.setVisible(0);
    %age = StripMLControlChars(age);
    %info;
    %age = "hidden";
    (%this SPC %age $= "");
    %gender = gender;
    %info;
    %gender = "n";
    !((!((%this SPC %gender $= "f")) SPC %gender $= "m"));
    playerGender = isObject(%info) @ %gender @ %this;
    playerNameDict;
    %location = StripMLControlChars(location);
    %info;
    %location = "hidden";
    (%location $= "");
    %tags = tags;
    %info;
    %respektScore = StripMLControlChars(respekt);
    %info;
    %respektScore = "(unknown)";
    (%respektScore $= "");
    %respektLvl = "?";
    %respektLvlName = "(unknown)";
    %respektLvl = respektScoreToLevel(%respektScore);
    %respektLvlName = respektLevelToNameWithoutArticle(%respektLvl);
    %respektRank = StripMLControlChars(respektRank);
    %info;
    %respektRank = "?";
    (%respektRank $= "");
    %ageText = "<spush><b>Age<spop>: " @ %fieldOpen @ %age @ %fieldClose;
    %locText = "<br><spush><b>Location<spop>: " @ %fieldOpen @ %location @ %fieldClose;
    %respektText = "<br><spush><b>Level:<spop>" @ %fieldOpen @ %respektLvl @ " - " @ %respektLvlName @ "<br><spush><b><a:gamelink " @ $Net::HelpURL_VPoints @ "?section=vPoints>All-time <bitmap:" @ "platform/client/ui/vpoints_14" @ "></a>:<spop>" @ %fieldOpen @ %respektScore;
    %contentTagsText = "<br><spush><b>Shared Interests (tags)<spop>:";
    %tagsText = "";
    %tagsText = $ETS::PlayerInfo::NoTags @ %tagsText @ "Interests you share with <a:PROFILE>" @ %gender[$genderPronounHimHerThem @ %gender] @ "</a> will show up here," @ "but you have none in your profile!" @ " " @ "<a:EDIT_PROFILE>Click here</a> to add some!";
    %tagsText = (%tags $= "") @ %tagsText @ "You have no interests in common with <a:PROFILE>" @ %gender[$genderPronounHimHerThem @ %gender] @ "</a>.";
    %tagsText = %tagsText @ %this.splitTagsIntoLinks(%tags, 0);
    %activitiesText = "<br><spush><b>Activities: <spop>" @ %fieldOpen @ %info @ getUserActivityMgr().getActivitiesMLText(activities, 5) @ %fieldClose;
    %playerName.setAffinityName();
    InfoPopupDlg @ InfoPopupContents @ %tableSettings @ %ageText @ %locText @ %respektText @ %activitiesText @ %contentTagsText @ "".setText();
    %this.getInfoPopupBottomText(%playerName).setText();
    forceReflow();
    forceReflow();
    %tagsText.setText();
    %ypos = (getWord(getPosition(), 1) - (InfoPopupContents + getWord(getExtent(), 1)));
    InfoPopupContents;
    %yExt = (%ypos - (InfoPopupBottom - getWord(getPosition(), 1)));
    1.0;
    0.resize(%ypos, 225, %yExt);
    1.setVisible();
    playerName = InfoPopupTagsScroll @ "" @ %this;
    InfoPopupTagsScroll;
    waitIcon.setVisible(1);
    waitIcon.start();
    %playerName.setAffinityName();
    "".setText();
    "".setText();
    requestPlayerInfoFor(playerName);
};
function InfoPopupDlg::setAffinityName(%this, %playerName) {
    %nameFieldString = %playerName;
    %visibleCharLimit = 17;
    %nameFieldString = getSubStr(%playerName, 0, (3.0 - %visibleCharLimit));
    (%visibleCharLimit > strlen(%nameFieldString));
    %nameFieldString = %nameFieldString @ "...";
    InfoPopupNameField @ "(" @ %nameFieldString @ ")".setText();
};
function InfoPopupDlg::showPlayerNotFound(%this) {
    InfoPopupContents @ "Sorry, couldn't find anyone named " @ %this @ playerName @ ".".setText();
    "".setText();
    "".setText();
};
function InfoPopupDlg::splitTagsIntoLinks(%this, %tags, %includeCategory) {
    %ret = "";
    %num = getFieldCount(%tags);
    %n = 0;
    %tag = getField(%tags, %n);
    (%num < %n);
    %ret = (0.0 > %n) @ %ret @ " | ";
    %dispTag = %tag;
    %includeCategory;
    %dispTag = getSubStr(strrchr(%tag, ":"), 1, 10000);
    %ret = %ret @ "<a:TAG" @ " " @ munge(%tag) @ ">" @ %dispTag @ "</a>";
    %n = (1.0 + %n);
    return %ret;
};
function InfoPopupDlg::getInfoPopupBottomText(%this, %playerName) {
    %profileLink = "<a:PROFILE>Web Profile</a>";
    %addRemoveIgnoreUnignore = %this.getAddRemoveIgnoreUnignoreText(%playerName);
    %ret = %profileLink @ " | " @ %addRemoveIgnoreUnignore;
    return %ret;
};
function InfoPopupDlg::getAddRemoveIgnoreUnignoreText(%this, %playerName) {
    %ret = "";
    error(getTrace() @ " " @ "- hmm. not sure how this happened.");
    return "<just:center>(favorite status unknown)";
    %friendStatus = %playerName.getFriendStatus();
    BuddyHudWin;
    %isIgnr = %playerName.getIgnoreStatus();
    BuddyHudWin;
    %faveLink = "";
    %faveLink2 = "";
    %faveText = "";
    %faveText2 = "";
    %faveLink = "FRIEND_REM";
    (%friendStatus $= "friends");
    %faveText = "Remove";
    %faveLink = "CANCEL_REQ";
    (%friendStatus $= "favorite");
    %faveText = "Cancel";
    %faveLink = "ACCEPT_REQ";
    (%friendStatus $= "fan");
    %faveText = "Accept";
    %faveLink2 = "DECLINE_REQ";
    %faveText2 = "Decline";
    %faveLink = "FRIEND_ADD";
    (%friendStatus $= "none");
    %faveText = "Add";
    %ignrLink = "REMIGNR";
    %isIgnr;
    %ignrText = "Unignore";
    %ignrLink = "ADDIGNR";
    %ignrText = "Ignore";
    %ret = "";
    %ret = !((%faveLink2 $= "")) @ %ret @ "Friend request:<a:" @ %faveLink @ ">" @ %faveText @ "</a>";
    %ret = %ret @ " | <a:" @ %faveLink2 @ ">" @ %faveText2 @ "</a>";
    %ret = %ret @ "<a:" @ %faveLink @ ">" @ %faveText @ "</a>";
    %ret = %ret @ " | <a:" @ %ignrLink @ ">" @ %ignrText @ "</a>";
    return %ret;
};
function InfoPopupDlg::stopAnimation(%this) {
    %this.init();
    waitIcon.stop();
    waitIcon.setVisible(0);
};
function InfoPopupContents::onURL(%this, %url) {
    %first = getWord(%url, 0);
    %rest = getWords(%url, 1, 10000);
    doUserProfile(playerName);
    doEditProfile();
    doViewTag(unmunge(%rest));
    doUserFavorite(playerName, "add");
    doUserFavorite(playerName, "remove");
    doUserFavorite(playerName, "cancel");
    doUserFavorite(playerName, "accept");
    doUserFavorite(playerName, "decline");
    doUserIgnore(playerName, "add");
    doUserIgnore(playerName, "remove");
};
function InfoPopupTagsText::onURL(%this, %url) {
    InfoPopupContents::onURL(%this, %url);
};
function InfoPopupNameField::onURL(%this, %url) {
    InfoPopupContents::onURL(%this, %url);
};
function InfoPopupNameField::onRightURL(%this, %url) {
    %first = getWord(%url, 0);
    onRightClickPlayerName(playerName);
};
function InfoPopupContents::sheduleBuddyRefreshIfNeeded(%this) {
};
function InfoPopupBottom::onURL(%this, %url) {
    %url.onURL();
};
