$gCurrentStoreName = "";
$gStoreNameStack = "";
$gVHDUserNameFilter = "";
$gVHDUserNoStock = 0;
$gInventoryFetchFakeDelay = 1000;
$ClientIsAuthoritativeForInventory = 0;
function clientCmdOnEnterStore(%storename) {
    log("inventory", "info", "Entering store" @ " " @ %storename);
    %idx = findWord($gStoreNameStack, %storename);
    error("Entering same store twice:" @ " " @ %storename @ " " @ "(corrected)");
    $gStoreNameStack = removeWord($gStoreNameStack, %idx);
    (-(1.0) != %idx);
    %idx = findWord($gStoreNameStack, %storename);
    $gStoreNameStack = %storename @ " " @ $gStoreNameStack;
    (-(1.0) != %idx);
    $gCurrentStoreName = %storename;
    resetStorePosition();
    Inventory::fetchStoreInventory(%storename);
    getUserActivityMgr().setActivityActive("shoppingForClothes", 1);
};
function clientCmdOnLeaveStore(%storename) {
    log("inventory", "info", "Leaving store: \"" @ %storename @ "\".");
    clientSideOnLeaveStore(%storename);
    hideButton();
};
function clientSideOnLeaveStore(%storename) {
    getUserActivityMgr().setActivityActive("shoppingForClothes", 0);
    $gStoreNameStack = "";
    (%storename $= "");
    $gCurrentStoreName = "";
    $StoreSkusLayer = "";
    return;
    %idx = findWord($gStoreNameStack, %storename);
    $gStoreNameStack = removeWord($gStoreNameStack, %idx);
    (-(1.0) != %idx);
    $gCurrentStoreName = getWord($gStoreNameStack, 0);
    $StoreSkusLayer = "";
    resetStorePosition();
};
function clientCmdOnEnterVHDUserStore(%userName) {
    %spaceName = CustomSpaceClient::GetCurrentSpaceName();
    %seppos = strpos(%spaceName, ".");
    %seppos = (1.0 + %seppos);
    (-(1.0) > %seppos);
    %len = (%seppos - strlen(%spaceName));
    %userName = getSubStr(%spaceName, %seppos, %len);
    %userName = "";
    $gVHDUserNameFilter = %userName;
    %storename = "vhd";
    %idx = findWord($gStoreNameStack, %storename);
    error("Entering same store twice:" @ " " @ %storename @ " " @ "(corrected)");
    $gStoreNameStack = removeWord($gStoreNameStack, %idx);
    (-(1.0) != %idx);
    %idx = findWord($gStoreNameStack, %storename);
    $gStoreNameStack = %storename @ " " @ $gStoreNameStack;
    (-(1.0) != %idx);
    $gCurrentStoreName = %storename;
    resetStorePosition();
    Inventory::fetchVHDUserStoreInventory(%storename);
    getUserActivityMgr().setActivityActive("shoppingForClothes", 1);
};
function clientCmdOnLeaveVHDUserStore(%storename) {
    log("inventory", "info", "Leaving store: \"" @ %storename @ "\".");
    clientSideOnLeaveVHDUserStore(%storename);
    hideButton();
};
function clientSideOnLeaveVHDUserStore(%storename) {
    getUserActivityMgr().setActivityActive("shoppingForClothes", 0);
    $gStoreNameStack = "";
    (%storename $= "");
    $gCurrentStoreName = "";
    $StoreSkusLayer = "";
    return;
    %idx = findWord($gStoreNameStack, %storename);
    $gStoreNameStack = removeWord($gStoreNameStack, %idx);
    (-(1.0) != %idx);
    $gCurrentStoreName = getWord($gStoreNameStack, 0);
    $StoreSkusLayer = "";
    resetStorePosition();
    $gVHDUserNameFilter = "";
};
function Inventory::fetchVHDUserStoreInventory(%storename) {
    schedule($gInventoryFetchFakeDelay, 0, "fakeVHDUserStoreInventoryGotFetchResults", %storename);
    return $StandAlone;
    sendRequest_GetStoreInventory($Player::Name, %storename, "OnGotDoneOrError_GetVHDUserStoreInventory");
};
function OnGotDoneOrError_GetVHDUserStoreInventory(%request) {
    %storename = storeName;
    %request;
    Inventory::clearStore(%storename);
    %storename[$gStoreStockRevision @ %storename] = %request.checkSuccess() @ %request.getValue("storeRevisionDate");
    Inventory::clearStore(%storename);
    Inventory::onGotStoreInventory(%storename);
    return (%request.getValue("errorCode") $= "storeNotFound");
    %num = %request.getValue("itemsCount");
    %hasAuthoredInventory = 0;
    %n = 0;
    (0.0 > strlen($gVHDUserNameFilter));
    %prefix = (%num < %n) @ "items" @ %n @ ".";
    %sku = %request.getValue(%prefix @ "sku");
    %si = %sku.findBySku();
    SkuManager;
    %hasAuthoredInventory = 1;
    (%si == stricmp(author, $gVHDUserNameFilter));
    %n = (1.0 + %n);
    0.0;
    $gVHDUserNoStock = !(%hasAuthoredInventory);
    (%num < %n);
    %n = 0;
    %prefix = (%num < %n) @ "items" @ %n @ ".";
    %sku = %request.getValue(%prefix @ "sku");
    %authorMatch = 0;
    %si = %sku.findBySku();
    SkuManager;
    %authorMatch = 0;
    1;
    %qty = %request.getValue(%authorMatch @ %prefix @ "quantity");
    !(%hasAuthoredInventory);
    %vpoints = %request.getValue((%si == stricmp(author, $gVHDUserNameFilter)) @ %prefix @ "priceVPoints");
    0.0;
    %vbux = %request.getValue(%hasAuthoredInventory @ %prefix @ "priceVBux");
    Inventory::addItemToStore(%storename, %sku, %qty, %vpoints, %vbux);
    %n = (1.0 + %n);
    Inventory::sortStoreInventory(%storename);
    Inventory::onGotVHDUserStoreInventory(%storename);
    shoppingCartSkus.addSkus();
};
function Inventory::onGotVHDUserStoreInventory(%storename) {
    %hasUserNameFilter = 0;
    1;
    %storename[$gStoreStockLoaded @ %storename] = 1;
    !(($gVHDUserNameFilter $= ""));
    saveStorePosition();
    ClosetTabs::refreshStoreTab();
    %storeLongName = !($gVHDUserNoStock) @ $gVHDUserNameFilter @ "'s vHD Store";
    %hasUserNameFilter;
    %storeDesc = %storeLongName @ " " @ "- press F5 or click \"Shop\" to start shopping!";
    ((getCurrentTab() SPC name $= "SHOPS") SPC $gCurrentStoreName $= %storename);
    %storeLongName = $gVHDUserNoStock @ $gVHDUserNameFilter @ " doesn't have any vHD Designs.";
    ClosetTabs;
    %storeDesc = %storeLongName @ " " @ "- Instead press F5 or click \"Shop\" to start browsing the full range of clothing from vSide House of Design!";
    isVisible();
    %storeLongName = %storename[$gDestinationNames @ %storename];
    ClosetGui;
    %storeDesc = %storename[$gDestinationDescsInWorld @ %storename];
    error(getScopeName() @ " " @ "- no store long name for" @ " " @ %storename);
    error(getScopeName() @ " " @ "- no store desc for" @ " " @ %storename);
    handleSystemMessage("msgInfoMessage", %storeDesc);
    showButton();
    "".setValue();
};
function fakeVHDUserStoreInventoryGotFetchResults(%storename) {
    echo("Fake store fetch results for" @ " " @ %storename);
    Inventory::clearStore(%storename);
    %skus = %storename.getStoreSkus();
    SkuManager;
    %qtys = %storename.getStoreQtys();
    SkuManager;
    %skusNum = getWordCount(%skus);
    %qtysNum = getWordCount(%qtys);
    error(getScopeName() @ " " @ "- mismatched number of skus and quantities:" @ " " @ %skusNum @ " " @ %qtysNum);
    %hasAuthoredInventory = 0;
    (getWordCount(%qtys) != %skusNum);
    %n = 0;
    !(($gVHDUserNameFilter $= ""));
    %sku = %request.getValue((%num < %n) @ %prefix @ "sku");
    %si = %sku.findBySku();
    SkuManager;
    %hasAuthoredInventory = 1;
    (%si SPC author $= $gVHDUserNameFilter);
    %n = (1.0 + %n);
    $gVHDUserNoStock = !(%hasAuthoredInventory);
    (%num < %n);
    %n = 0;
    %sku = getWord(%skus, %n);
    (%skusNum < %n);
    %qty = getWord(%qtys, %n);
    (%qtysNum < %n);
    %qty = -(1.0);
    %authorMatch = 0;
    %si = %sku.findBySku();
    SkuManager;
    %authorMatch = 0;
    1;
    %vbux = price;
    %si;
    %vpoints = (%si * price);
    2.0;
    Inventory::addItemToStore(%storename, %sku, %qty, %vpoints, %vbux);
    %n = (1.0 + %n);
    %authorMatch;
    Inventory::onGotVHDUserStoreInventory(%storename);
};
function resetStorePosition() {
    $gStoreScrollPos = 0;
    $gStoreCurrentCategory = "";
};
function loadStorePosition() {
    %presentCategory = getText();
    StoreCategoryPopup;
    0.SetSelected();
    %catIndex = $gStoreCurrentCategory.findText();
    StoreCategoryPopup;
    %catIndex.SetSelected();
    $gStoreCurrentCategory = %presentCategory;
    StoreCategoryPopup;
    $gStoreScrollPos = 0;
    ((0.0 >= %catIndex) SPC $gStoreScrollPos $= "");
    itemsScroll.scrollTo(0, $gStoreScrollPos);
};
function saveStorePosition() {
    $gStoreScrollPos = (getWord(thumbnails.getPosition(), 1) - 0.0);
    "Shops".getTabWithName();
    $gStoreCurrentCategory = getText();
    StoreCategoryPopup;
};
function clientCmdUpdateInventorySkus(%invChangedSkus, %notify, %autoEquip) {
    log("inventory", "info", "clientCmdUpdateInventorySkus(): invChangedSkus (<skus-added> | <skus-removed>) =" @ %invChangedSkus);
    %invChangedSkus = strreplace(%invChangedSkus, "\t", " ");
    %invChangedSkus = strreplace(%invChangedSkus, "|", "\t");
    %skusAdded = trim(getField(%invChangedSkus, 0));
    %skusRemoved = trim(getField(%invChangedSkus, 1));
    log("inventory", "debug", getScopeName() @ " " @ "- skus   Added=" @ %skusAdded);
    log("inventory", "debug", getScopeName() @ " " @ "- skus Removed=" @ %skusRemoved);
    updateInventorySkus(%skusAdded, %skusRemoved, %notify, %autoEquip, "");
};
function updateInventorySkus(%skusAdded, %skusRemoved, %notify, %autoEquip, %srcName) {
    %entryTime = getRealTime();
    echoDebug(getScopeName() @ " " @ "skus added  :" @ " " @ %skusAdded);
    echoDebug(getScopeName() @ " " @ "skus removed:" @ " " @ %skusRemoved);
    $player.addInventorySKUs(%skusAdded);
    $player.removeInventorySKUs(%skusRemoved);
    $Player::inventory.update();
    notifyUserOfSkusGained(%skusAdded, %srcName, %autoEquip);
    Inventory::equipOrWearSkus(%skusAdded);
    getOwnedFurniture();
    %exitTime = getRealTime();
    CustomSpaceClient::isOwner();
    error(getScopeName() @ " " @ "- time:" @ " " @ mSubS32(%exitTime, %entryTime));
};
function clientCmdGiftReceived(%skus, %srcName) {
    $player.addInventorySKUs(%skus);
    notifyUserOfSkusGained(%skus, %srcName, 0);
    selectCurrentTab();
};
function clientCmdInventoryExpiration(%skusAboutToExpire, %skusJustExpired) {
    log("inventory", "info", "clientCmdInventoryExpiration(): skusAboutToExpire (<sku>|<numItems>|<remaining>|<reason>SPC<next>) =\"" @ %skusAboutToExpire @ "\", skusJustExpired (<sku>|<numItems>|<reason>|<replacementSKU>SPC<next>) = \"" @ %skusJustExpired @ "\"");
    %skusAboutToExpire = strreplace(%skusAboutToExpire, " ", "\n");
    %skusAboutToExpire = strreplace(%skusAboutToExpire, "|", "\t");
    %skusJustExpired = strreplace(%skusJustExpired, " ", "\n");
    %skusJustExpired = strreplace(%skusJustExpired, "|", "\t");
    %aboutToExpireCount = getRecordCount(%skusAboutToExpire);
    %justExpiredCount = getRecordCount(%skusJustExpired);
    error((0.0 == %justExpiredCount) @ getScopeName() @ "-> received empty update... this shouldn't happen.");
    return (0.0 == %aboutToExpireCount);
    // unhandled opcode 2149 at 0x00000C49
    %justExpiredCount = AudioProfile_JustExpired;
    (0.0 > %justExpiredCount);
    // unhandled opcode 2149 at 0x00000C59
    %aboutToExpireCount = AudioProfile_ExpiringSoon;
    (0.0 > %aboutToExpireCount);
    schedule(500, 0, "alxPlay", %sound);
    %msg = "";
    %listOfSkusJustExpired = "";
    %activeSkus = $player.getActiveSKUs();
    %justExpiredCount;
    %realExpiredCount = 0;
    %i = 0;
    %itemStr = getRecord(%skusJustExpired, %i);
    (%justExpiredCount < %i);
    %num = getField(%itemStr, 1);
    %realExpiredCount = (%num + %realExpiredCount);
    %i = (1.0 + %i);
    %msg = (1.0 > %realExpiredCount) @ %realExpiredCount @ " of your items just expired (";
    (%justExpiredCount < %i);
    %msg = "Your ";
    %listOfSkusJustExpired = "";
    %listOfUniqueSkusJustExpired = "";
    %i = 0;
    %msg = (0.0 > %i) @ %msg @ ", ";
    (%justExpiredCount < %i);
    %itemStr = getRecord(%skusJustExpired, %i);
    %sku = getField(%itemStr, 0);
    %num = getField(%itemStr, 1);
    %reason = getField(%itemStr, 2);
    %replaceSKU = getField(%itemStr, 3);
    %num = 1;
    (%num $= "");
    %si = %sku.findBySku();
    SkuManager;
    %name = descShrt;
    %si;
    error(isObject(%si) @ getScopeName() @ "-> unknown sku just expired");
    %name = "(oops, bug)";
    %msg = (1.0 > %num) @ %msg @ %num;
    %msg = "s" @ "";
    (1.0 > %num);
    removeExpiredSkuFromOutfits(%sku, %replaceSKU, 0);
    %activeSkus = removeAndReplaceSkuFromSkuList(%activeSkus, %sku, %replaceSKU);
    %msg @ %name;
    %listOfUniqueSkusJustExpired = %sku;
    (%listOfUniqueSkusJustExpired $= "");
    %listOfUniqueSkusJustExpired = %listOfUniqueSkusJustExpired @ " " @ %sku;
    %k = 0;
    %listOfSkusJustExpired = (%num < %k) @ %listOfSkusJustExpired @ %sku @ " ";
    %k = (1.0 + %k);
    %i = (1.0 + %i);
    (%num < %k);
    notifyUserOfSkusExpired(%listOfUniqueSkusJustExpired, "");
    outfits_persist();
    commandToServer('SetActiveSkus', %activeSkus);
    %msg = (1.0 > %justExpiredCount) @ %msg @ ")";
    (0.0 > %justExpiredCount);
    %msg = (%justExpiredCount < %i) @ %msg @ " just expired";
    %msg = %aboutToExpireCount @ %msg @ ", AND ";
    %msg = %msg @ ".";
    %realAboutToExpireCount = 0;
    %aboutToExpireCount;
    %i = 0;
    %itemStr = getRecord(%skusAboutToExpire, %i);
    (%aboutToExpireCount < %i);
    %num = getField(%itemStr, 1);
    %num = 1;
    (%num $= "");
    %realAboutToExpireCount = (%num + %realAboutToExpireCount);
    %i = (1.0 + %i);
    %msg = (%aboutToExpireCount < %i) @ (1.0 > %realAboutToExpireCount) @ %msg @ %realAboutToExpireCount @ " of your items are about to expire! (";
    %msg = (0.0 > %justExpiredCount) @ "y" @ "Y" @ "our";
    %msg;
    %i = 0;
    %msg = (0.0 > %i) @ %msg @ ", ";
    (%aboutToExpireCount < %i);
    %aboutToExpireSku = getRecord(%skusAboutToExpire, %i);
    %sku = getField(%aboutToExpireSku, 0);
    %num = getField(%aboutToExpireSku, 1);
    %remaining = getField(%aboutToExpireSku, 2);
    %reason = getField(%aboutToExpireSku, 3);
    %si = %sku.findBySku();
    SkuManager;
    %name = descShrt;
    %si;
    error(isObject(%si) @ getScopeName() @ "-> unknown sku about to expire");
    %name = "(oops, bug)";
    %msg = "s" @ "";
    (1.0 > %num);
    %msg = (1.0 == %realAboutToExpireCount) @ %msg @ " expires";
    %msg @ %num @ " " @ %name;
    %roundedRemaining = (60.0 * mFloor((60.0 / (30.0 + %remaining))));
    %msg = %msg @ " in " @ secondsToDaysHoursMinutesSeconds(%roundedRemaining);
    %i = (1.0 + %i);
    %msg = (1.0 > %realAboutToExpireCount) @ %msg @ ").";
    (%aboutToExpireCount < %i);
    %msg = %msg @ ".";
    handleSystemMessage('MsgInfoMessage', %msg);
    log("inventory", "debug", !((!((%msg $= "")) SPC %listOfSkusJustExpired $= "")) @ "clientCmdInventoryExpiration(): removed from inventory: skusJustExpired=" @ %listOfSkusJustExpired);
    $player.removeInventorySKUs(%listOfSkusJustExpired);
};
function removeAndReplaceSkuFromSkuList(%skusOutfit, %sku, %replaceSKU) {
    error(getScopeName() @ " " @ "sku is null can't remove from skusoutfits:" @ " " @ %skusOutfit @ " " @ "or replace with" @ " " @ %replaceSKU);
    return %skusOutfit;
    %idx = findWord(%skusOutfit, %sku);
    %changes = (1.0 + %changes);
    ( >= 0.0);
    %skusOutfit = removeWord(%skusOutfit, %idx);
    %skusOutfit = %replaceSKU;
    ((0.0 < findWord(%skusOutfit, %replaceSKU)) SPC %skusOutfit $= "");
    %skusOutfit = %skusOutfit @ " " @ %replaceSKU;
    !((%replaceSKU SPC %replaceSKU $= ""));
    return %skusOutfit;
};
function removeExpiredSkuFromOutfits(%oldSku, %newSku, %notifyUser) {
    error(getScopeName() @ " " @ "$player is not valid, cannot remove expired sku and replace with new one" @ " " @ %sku @ " " @ %newSku);
    return 0;
    %outfitNames = ;
    %i = 0;
    %name = getWord(%outfitNames, %i);
    ($gClosetNumOutfits < %i);
    %keyOutfit = %name;
    %keyBody = $player.getGender() @ "Body";
    %skusOutfit = $gOutfits.get(%keyOutfit);
    %skusOutfit = removeAndReplaceSkuFromSkuList(%skusOutfit, %oldSku, %newSku);
    %STOCKOutfit = %keyOutfit[$gNewStockOutfits @ %keyOutfit];
    %n = (1.0 - getWordCount(%STOCKOutfit));
    %sku = getWord(%STOCKOutfit, %n);
    (0.0 >= %n);
    %drawer = drwrName;
    %sku.findBySku();
    %optional = %drawer.isOptionalDrawer();
    SkuManager;
    %STOCKOutfit = removeWord(%STOCKOutfit, %n);
    %optional;
    %n = (1.0 - %n);
    SkuManager;
    %skusOutfit = %STOCKOutfit.overlaySkus(%skusOutfit);
    SkuManager;
    %skusBody = $gOutfits.get(%keyBody);
    (0.0 >= %n);
    %skusBody = removeAndReplaceSkuFromSkuList(%skusBody, %oldSku, %newSku);
    %STOCKBody = ;
    %n = (1.0 - getWordCount(%STOCKBody));
    %sku = getWord(%STOCKBody, %n);
    (0.0 >= %n);
    %drawer = drwrName;
    %sku.findBySku();
    %optional = %drawer.isOptionalDrawer();
    SkuManager;
    %STOCKBody = removeWord(%STOCKBody, %n);
    %optional;
    %n = (1.0 - %n);
    SkuManager;
    %skusBody = %STOCKBody.overlaySkus(%skusBody);
    SkuManager;
    $gOutfits.put(%keyBody, %skusBody);
    $gOutfits.put(%keyOutfit, %skusOutfit);
    %i = (1.0 + %i);
    (0.0 >= %n);
    notifyUserOfSkusExpired(%oldSku, "");
};
function notifyUserOfSkusGained(%skus, %srcName, %autoEquipped) {
    echo(getScopeName() @ " " @ %skus @ " " @ %srcName);
    %gender = $player.getGender();
    isObject($player);
    error(getScopeName() @ " " @ "- ERROR NO Player OBJECT using forced gender");
    %gender = "f";
    %skus = %skus.filterSkusGender(%gender);
    SkuManager;
    %skus = %skus.filterSkusVisible(1);
    SkuManager;
    echo(getScopeName() @ " " @ "- no visible skus." @ " " @ %skus @ " " @ getTrace());
    return (%skus $= "");
    %skusWearable = %skus.filterSkusWearable(1);
    SkuManager;
    %skusUnwearable = %skus.filterSkusWearable(0);
    SkuManager;
    %skusFurnishing = %skus.filterSkusType("furnishing");
    SkuManager;
    %numWearable = getWordCount(%skusWearable);
    %numUnwearable = getWordCount(%skusUnwearable);
    %numFurnishing = getWordCount(%skusFurnishing);
    %numSkus = (%numUnwearable + %numWearable);
    %numNonFurnishing = (%numFurnishing - %numSkus);
    %listWearable = %skusWearable.getSkuShortDescriptions(", ", 1, 0);
    SkuManager;
    %listUnwearable = %skusUnwearable.getSkuShortDescriptions(", ", 1, 32);
    SkuManager;
    %list = "" @ " and" @ " " @ %listUnwearable;
    ((0.0 > %numWearable) @ %listWearable SPC %listUnwearable $= "");
    %list = %listUnwearable;
    %wordNonFurnishingItThem = "them";
    "it";
    %wordNonFurnishingItemItems = "items";
    "item";
    %wordWearableItThem = "them";
    "it";
    %wordWearableItemItems = "items";
    "item";
    %wordFurnishingItThem = "them";
    "it";
    %specialOrFurniture = "furniture";
    "special or furniture";
    %specialOrFurniture = "special";
    (%numUnwearable != %numFurnishing);
    %msgUnwearable = "";
    (0.0 > %numFurnishing);
    %msgUnwearable = (1.0 == %numUnwearable) @ "One is" @ %numUnwearable @ " " @ "are" @ " " @ %specialOrFurniture @ " and can't actually be worn)";
    "" @ "\n(";
    %msgUnwearable = (1.0 == %numUnwearable) @ "It's" @ "They're" @ " " @ %specialOrFurniture @ " and can't actually be worn)";
    (0.0 == %numUnwearable) @ "\n(";
    %YoullFindStr = "";
    (0.0 > %numWearable);
    %YoullFindStr = "your non-furnishing" @ " " @ %wordNonFurnishingItemItems @ %wordNonFurnishingItThem @ " " @ "in the closet (F5).";
    (0.0 > %numFurnishing);
    %YoullFindStr = "your new furniture" @ %wordFurnishingItThem @ " " @ "in your apartment using the Space->My Furnishings panel.";
    (0.0 > %numNonFurnishing);
    %srcName = "yourself";
    ("" @ "\n" @ "And you" @ "You" @ " " @ "can place" @ " " SPC %srcName $= $Player::Name);
    %fromString = " from" @ " " @ %srcName;
    "";
    %msg = "You just got" @ " " @ (1.0 == %numSkus) @ "a new item" @ %numSkus @ " " @ "new items" @ %fromString @ "!";
    ((0.0 > %numNonFurnishing) SPC %srcName $= "");
    %msg = "You'll find" @ " " @ (0.0 > %numFurnishing) @ %YoullFindStr @ %msg @ "\n" @ "(" @ %list @ ")";
    (0.0 > %numNonFurnishing);
    %msg = !(%autoEquipped) @ %msg @ %msgUnwearable;
    (0.0 > %numNonFurnishing);
    %msg = %msg @ "\n" @ %YoullFindStr;
    (1.0 == %numFurnishing);
    %msg = (0.0 > %numWearable) @ (0.0 == %numFurnishing) @ %msg @ "\n" @ "" @ "\n" @ "Would you like to wear " @ %wordWearableItThem @ " now?";
    !(%autoEquipped);
    echo(getScopeName() @ " " @ "found a salon sku in the list, so we are wearing it immediately without asking: " @ " " @ %skus);
    Inventory::equipOrWearSkus(%skus);
    return SalonDoesListContainAnySalonRewardSKUs(%skus);
    %msg = %msg @ "\n" @ "" @ "\n" @ "Would you like to put on your wearable " @ %wordWearableItemItems @ " now?";
    %mb = MessageBoxYesNo("Score!", %msg, "Inventory::equipOrWearSkus(\"" @ %skus @ "\"); if($gAutoOrbitOnReceiveItem && !$IN_ORBIT_CAM) nextPlayerCamMode();", "");
    %mb = MessageBoxOK("Score!", %msg, "");
    text.setText(message);
};
function notifyUserOfSkusExpired(%skus, %srcName) {
    %skus = trim(%skus);
    return (%skus $= "");
    %count = getWordCount(%skus);
    return (0.0 == %count);
    %descriptions = %skus.getSkuShortDescriptions(", ", 0);
    SkuManager;
    %msg = "Some items in your outfits expired while you were away:";
    "An item in your outfits expired while you were away:";
    handleSystemMessage("msgInfoMessage", %msg @ " " @ %descriptions);
};
function Inventory::equipOrWearSkus(%skus) {
    return (%skus $= "");
    %skusNew = %skus.filterSkusGender($player.getGender());
    SkuManager;
    log("inventory", "debug", "Inventory::equipOrWearSkus(): %skus=" @ %skus @ ", %skusNew=" @ %skusNew);
    %skusDry = $player.getActiveSKUs();
    log("inventory", "debug", "Inventory::equipOrWearSkus(): %skusDry=" @ %skusDry);
    %skusWet = %skusDry.overlaySkus(%skusNew);
    SkuManager;
    log("inventory", "info", "Inventory::equipOrWearSkus(): %skusWet=" @ %skusWet);
    $ClosetOutfitName[$ClosetSkusOutfit @ $ClosetOutfitName] = isVisible() @ SkuManager @ %skusWet.filterSkusForClothing();
    ClosetGui;
    $ClosetSkusBody = %skusWet.filterSkusForBody();
    SkuManager;
    selectCurrentTab();
    updateVisibleAvatar();
    SaveOutfitAndBodySkusAsCurrent(%skusWet);
};
function Inventory::fetchStoreInventory(%storename) {
    schedule($gInventoryFetchFakeDelay, 0, "fakeStoreInventoryGotFetchResults", %storename);
    return $StandAlone;
    sendRequest_GetStoreInventory($Player::Name, %storename, "OnGotDoneOrError_GetStoreInventory");
};
function OnGotDoneOrError_GetStoreInventory(%request) {
    %storename = storeName;
    %request;
    Inventory::clearStore(%storename);
    %storename[$gStoreStockRevision @ %storename] = %request.checkSuccess() @ %request.getValue("storeRevisionDate");
    Inventory::clearStore(%storename);
    Inventory::onGotStoreInventory(%storename);
    return (%request.getValue("errorCode") $= "storeNotFound");
    %num = %request.getValue("itemsCount");
    %n = 0;
    %prefix = (%num < %n) @ "items" @ %n @ ".";
    %sku = %request.getValue(%prefix @ "sku");
    %qty = %request.getValue(%prefix @ "quantity");
    %vpoints = %request.getValue(%prefix @ "priceVPoints");
    %vbux = %request.getValue(%prefix @ "priceVBux");
    Inventory::addItemToStore(%storename, %sku, %qty, %vpoints, %vbux);
    %n = (1.0 + %n);
    Inventory::sortStoreInventory(%storename);
    Inventory::onGotStoreInventory(%storename);
    shoppingCartSkus.addSkus();
};
function Inventory::sortStoreInventory(%storename) {
    warn(getScopeName() @ " " @ "- should be done server-side. ETS-3468");
    %allSkus = getSkus().filterSkusGender($UserPref::Player::gender);
    SkuManager;
    %storename[$gStoreStockCacheSkus @ %storename] = SkuManager @ Inventory::sortSkus(%storename[$gStoreStockCacheSkus @ %storename], %allSkus);
};
function Inventory::sortSkus(%skusToSort, %orderToAppearIn) {
    %ret = "";
    %n = (1.0 - getWordCount(%orderToAppearIn));
    %sku = getWord(%orderToAppearIn, %n);
    (0.0 >= %n);
    %ret = %sku @ " " @ %ret;
    (0.0 >= findWord(%skusToSort, %sku));
    %n = (1.0 - %n);
    %ret = trim(%ret);
    (0.0 >= %n);
    return %ret;
};
function fakeStoreInventoryGotFetchResults(%storename) {
    echo("Fake store fetch results for" @ " " @ %storename);
    Inventory::clearStore(%storename);
    %skus = %storename.getStoreSkus();
    SkuManager;
    %qtys = %storename.getStoreQtys();
    SkuManager;
    %skusNum = getWordCount(%skus);
    %qtysNum = getWordCount(%qtys);
    error(getScopeName() @ " " @ "- mismatched number of skus and quantities:" @ " " @ %skusNum @ " " @ %qtysNum);
    %n = 0;
    (getWordCount(%qtys) != %skusNum);
    %sku = getWord(%skus, %n);
    (%skusNum < %n);
    %qty = getWord(%qtys, %n);
    (%qtysNum < %n);
    %qty = -(1.0);
    %si = %sku.findBySku();
    SkuManager;
    %vbux = price;
    %si;
    %vpoints = (%si * price);
    2.0;
    Inventory::addItemToStore(%storename, %sku, %qty, %vpoints, %vbux);
    %n = (1.0 + %n);
    Inventory::onGotStoreInventory(%storename);
};
function Inventory::addItemToStore(%storename, %sku, %qty, %vpoints, %vbux) {
    %storename[$gStoreStockCacheSkus @ %storename] = %storename[$gStoreStockCacheSkus @ %storename] @ %sku @ " ";
    %sku[$gStoreItemsQty @ %sku] = %qty;
    %sku[$gStoreItemsVPoints @ %sku] = (0.0 < %vpoints) @ "-" @ mFloor(%vpoints);
    %sku[$gStoreItemsVBux @ %sku] = (0.0 < %vbux) @ "-" @ mFloor(%vbux);
};
function Inventory::getVPointsPriceForSku(%sku) {
    %price = %sku[$gStoreItemsVPoints @ %sku];
    return %price;
    %si = %sku.findBySku();
    SkuManager;
    return priceVPoints;
    return "-";
};
function Inventory::getVBuxPriceForSku(%sku) {
    %price = %sku[$gStoreItemsVBux @ %sku];
    return %price;
    %si = %sku.findBySku();
    SkuManager;
    return priceVBux;
    return "-";
};
function Inventory::getTotalPrice(%currency, %skus) {
    %hasValidSku = 0;
    %total = 0;
    %count = getWordCount(%skus);
    %i = 0;
    %sku = getWord(%skus, %i);
    (%count < %i);
    %price = Inventory::getVBuxPriceForSku(%sku);
    Inventory::getVPointsPriceForSku(%sku);
    %total = (%price + %total);
    !(((%currency $= "vPoints") SPC %price $= "-"));
    %hasValidSku = 1;
    %i = (1.0 + %i);
    return "-";
};
function Inventory::filterSkusByValidPrice(%currency, %skus) {
    %validSkus = "";
    %count = getWordCount(%skus);
    %i = 0;
    %sku = getWord(%skus, %i);
    (%count < %i);
    %price = Inventory::getVBuxPriceForSku(%sku);
    Inventory::getVPointsPriceForSku(%sku);
    %validSkus = %validSkus @ " " @ %sku;
    !(((%currency $= "vPoints") SPC %price $= "-"));
    %i = (1.0 + %i);
    return trim(%validSkus);
};
function Inventory::dumpStore(%storename) {
    echo("store" @ " " @ %storename);
    %num = getWordCount(%storename[$gStoreStockCacheSkus @ %storename]);
    %n = 0;
    %sku = getWord(%storename[$gStoreStockCacheSkus @ %storename], %n);
    (%num < %n);
    %qty = %sku[$gStoreItemsQty @ %sku];
    %vps = %sku[$gStoreItemsVPoints @ %sku];
    %vbs = %sku[$gStoreItemsVBux @ %sku];
    %si = %sku.findBySku();
    SkuManager;
    echo(%si @ descShrt);
    %n = (1.0 + %n);
    "sku:" @ " " @ formatInt("%6d", %sku) @ " " @ "qty" @ " " @ formatInt("%4d", %qty) @ " " @ "vPoints" @ " " @ formatInt("%6d", %vps) @ " " @ "vBux" @ " " @ formatInt("%6d", %vbs) @ " ";
};
function Inventory::onGotStoreInventory(%storename) {
    loadAvailableSkus();
    return CSShoppingBrowser;
    %storename[$gStoreStockLoaded @ %storename] = 1;
    saveStorePosition();
    ClosetTabs::refreshStoreTab();
    %storeLongName = %storename[$gDestinationNames @ %storename];
    ((getCurrentTab() SPC name $= "SHOPS") SPC $gCurrentStoreName $= %storename);
    %storeDesc = %storename[$gDestinationDescsInWorld @ %storename];
    ClosetTabs;
    error(getScopeName() @ " " @ "- no store long name for" @ " " @ %storename);
    error(getScopeName() @ " " @ "- no store desc for" @ " " @ %storename);
    handleSystemMessage("msgInfoMessage", %storeDesc);
    showButton();
    "".setValue();
};
function Inventory::getCurrentStoreSkus() {
    return "no store";
    return $gCurrentStoreName[$gStoreStockCacheSkus @ $gCurrentStoreName];
};
function Inventory::getStoreName(%storeID) {
    return %storeID[$gDestinationNames @ %storeID];
};
function Inventory::getCurrentStoreName() {
    return "";
    return Inventory::getStoreName($gCurrentStoreName);
};
function Inventory::getStoreDescInCloset(%storeID) {
    return %storeID[$gDestinationDescsInCloset @ %storeID];
};
function Inventory::getStoreDescInWorld(%storeID) {
    return %storeID[$gDestinationDescsInWorld @ %storeID];
};
function Inventory::getCurrentStoreDescInCloset() {
    return Inventory::getStoreDescInCloset($gCurrentStoreName);
};
function Inventory::getCurrentStoreDescInWorld() {
    return Inventory::getStoreDescInWorld($gCurrentStoreName);
};
function Inventory::getStoreDrwrs(%storeID) {
    return Inventory::getStoreDrwrs($gCurrentStoreName);
};
function Inventory::getCurrentStoreDrwrs() {
    return Inventory::getStoreDrwrs($gCurrentStoreName);
};
function Inventory::fetchPlayerInventoryIfNeedTo(%playerObj) {
    echoDebug("inventory", "This should be more sophisticated. Something like if (!touched).");
    Inventory::fetchPlayerInventory(%playerObj);
};
function Inventory::fetchPlayerInventoryIfEmpty() {
    Inventory::fetchPlayerInventory();
};
function fakePlayerInventoryGotFetchResults() {
    echo("Fake player fetch inventory results");
    $Player::inventory = getBornWithSkus();
    SkuManager;
    $Player::inventory = trim($Player::inventory);
    %skus = "props".getSkusDrwr();
    SkuManager;
    $Player::inventory = $Player::inventory @ " " @ %skus;
    $Player::inventory = trim($Player::inventory);
    Inventory::onGotPlayerInventory();
};
function Inventory::onGotPlayerInventory() {
    echo("got player inventory");
    error(($Player::inventory $= "") @ getScopeName() @ "->got empty player inventory!");
    %notEmpty = 0;
    %notEmpty = 1;
    Inventory::dedupeSkus($Player::inventory);
    error(%notEmpty @ getScopeName() @ "->got empty player inventory after deduping!");
    update();
    Inventory::EnsurePlayerOwnsOutfitItems();
};
function Inventory::EnsurePlayerOwnsOutfitItems() {
    %outfitNames = ;
    %anyRemoved = 0;
    %expiredSkus = "";
    %i = 0;
    %name = getWord(%outfitNames, %i);
    ($gClosetNumOutfits < %i);
    %keyOutfit = %name;
    %keyBody = $player.getGender() @ "Body";
    %skusOutfit = $gOutfits.get(%keyOutfit);
    %skusBody = $gOutfits.get(%keyBody);
    %entireOutfit = %skusBody @ " " @ %skusOutfit;
    %count = getWordCount(%entireOutfit);
    %j = (1.0 - %count);
    %sku = getWord(%entireOutfit, %j);
    (0.0 >= %j);
    %anyRemoved = 1;
    !($player.hasInventorySKU(%sku));
    %replaceSKU = "";
    removeExpiredSkuFromOutfits(%sku, %replaceSKU, 0);
    %expiredSkus = %sku;
    ((0.0 < findWord(%expiredSkus, %sku)) SPC %expiredSkus $= "");
    %expiredSkus = %expiredSkus @ " " @ %sku;
    %j = (1.0 - %j);
    %i = (1.0 + %i);
    (0.0 >= %j);
    notifyUserOfSkusExpired(%expiredSkus, "");
    outfits_persist();
};
function Inventory::dedupeSkus(%dry) {
    %dryNum = getWordCount(%dry);
    %wet = dedupeWords(%dry);
    %wetNum = getWordCount(%wet);
    %xtra = %dry;
    (%wetNum != %dryNum);
    %n = 0;
    %sku = getWord(%wet, %n);
    (%wetNum < %n);
    %xtra = findAndRemoveFirstOccurrenceOfWord(%xtra, %sku);
    %n = (1.0 + %n);
    %count = (%wetNum - %dryNum);
    (%wetNum < %n);
    error(getScopeName() @ " " @ "- Got duplicate skus. Count: " @ " " @ %count @ " " @ "and here they are:" @ " " @ %xtra @ " " @ "dry:" @ " " @ %dry @ " " @ getTrace());
    return %wet;
};
function Inventory::clearStore(%storename) {
    %storename[$gStoreStockCacheSkus @ %storename] = "";
    %storename[$gStoreStockRevision @ %storename] = "";
};
function Inventory::giftItemToPlayer(%unused, %unused) {
};
function Inventory::fetchPlayerInventory() {
    log("inventory", "info", getScopeName());
    schedule($gInventoryFetchFakeDelay, 0, "fakePlayerInventoryGotFetchResults");
    log("inventory", "info", "standalone - using fake player inventory fetch");
    return $StandAlone;
    %request = safeNewScriptObject("ManagerRequest", "InventoryRequest");
    %url = "";
    %url = %url @ $Net::ClientServiceURL;
    %url = %url @ "/GetUserInventory";
    %request.setURL(%url);
    %request.addUrlParam("user", $Player::Name);
    %request.addUrlParam("token", $Token);
    doAnother = 0 @ %request;
    %request.start();
    log("network", "debug", getScopeName() @ " " @ "-" @ " " @ %request.getURL());
};
function InventoryRequest::tryDoAnother(%this) {
    return !(doAnother);
    log("network", "debug", getScopeName() @ " " @ "- doing another on" @ " " @ %this.getURL());
    Inventory::fetchPlayerInventory($player);
};
function InventoryRequest::onError(%this, %unused, %unused) {
    %this.tryDoAnother();
};
function InventoryRequest::onDone(%this) {
    error(!(%this.checkSuccess()) @ getScopeName() @ "->InventoryRequest failed! Inventory = \"" @ $Player::inventory @ "\"");
    return;
    %array = new ""();
    Array;
    %this.parse_Inventory(%array, "qtyOwned");
    $Player::inventory = "";
    0;
    %num = %array.count();
    %n = 0;
    %skunum = skuNumber;
    %array.getValue(%n);
    $Player::inventory = $Player::inventory @ " " @ %skunum;
    (%num < %n);
    %n = (1.0 + %n);
    $Player::inventory = trim($Player::inventory);
    (%num < %n);
    $Player::inventory = $Player::inventory @ " " @ 30013;
    $Player::inventory = $Player::inventory @ " " @ 30014;
    Inventory::onGotPlayerInventory();
    %array.delete();
    %this.tryDoAnother();
};
function Player::hasInventorySKU(%this, %sku) {
    return (0.0 >= findWord($Player::inventory, %sku));
};
function Player::addInventorySKUs(%this, %skusToAdd) {
    echo("Player::addInventorySKUs skusToAdd=" @ %skusToAdd);
    %idx = (1.0 - getWordCount(%skusToAdd));
    %sku = getWord(%skusToAdd, %idx);
    (0.0 >= %idx);
    $Player::inventory = %sku @ " " @ $Player::inventory;
    !(hasWord($Player::inventory, %sku));
    %idx = (1.0 - %idx);
};
function Player::removeInventorySKUs(%this, %skusToRemove) {
    %idx = (1.0 - getWordCount(%skusToRemove));
    %sku = getWord(%skusToRemove, %idx);
    (0.0 >= %idx);
    %loc = findWord($Player::inventory, %sku);
    $Player::inventory = removeWord($Player::inventory, %loc);
    (0.0 >= %loc);
    echo(getScopeName() @ " " @ "- tried to remove sku i don't have -" @ " " @ %sku @ " " @ getTrace());
    %idx = (1.0 - %idx);
    %atLeastOneOutfitChanged = 0;
    (0.0 >= %idx);
    %activeSkus = $player.getActiveSKUs();
    %n = (1.0 - getWordCount(%skusToRemove));
    %sku = getWord(%skusToRemove, %n);
    (0.0 >= %n);
    %activeSkus = findAndRemoveFirstOccurrenceOfWord(%activeSkus, %sku);
    %m = (1.0 - $gOutfits.size());
    %outfitSkus = $gOutfits.getValue(%m);
    (0.0 >= %m);
    %outfitSkus = findAndRemoveAllOccurrencesOfWord(%outfitSkus, %sku);
    %atLeastOneOutfitChanged = 1;
    !((%outfitSkus $= $gOutfits.getValue(%m)));
    $gOutfits.put($gOutfits.getKey(%m), %outfitSkus);
    %m = (1.0 - %m);
    %n = (1.0 - %n);
    (0.0 >= %m);
    $player.setActiveSKUs(%activeSkus);
    commandToServer('SetActiveSkus', %activeSkus);
    outfits_persist();
};
function doTakeFlower(%unused) {
    error("20080131 OBSOLETE FUNCTION - returning immediately. -" @ " " @ getTrace());
    return;
};
function doGiveFlower(%unused) {
    error("20080131 OBSOLETE FUNCTION - returning immediately. -" @ " " @ getTrace());
    return;
};
function sendGiftRequest(%unused, %skus) {
    error("20080131 OBSOLETE FUNCTION - returning immediately. -" @ " " @ getTrace());
    return;
};
