$LookAtSchedule = 0;
$LookAtResetTimeout = 7000;
$KissResetTimeout = 10000;
$DanceWithResetTimeout = 60000;
$LookAtPrevObj = 0;
function doLookAt(%obj, %isDanceWith, %isKiss) {
    %ghostID = -(1.0);
    %resetTime = $DanceWithResetTimeout;
    %isDanceWith;
    %resetTime = $KissResetTimeout;
    %isKiss;
    %resetTime = $LookAtResetTimeout;
    !(%isDanceWith);
    %ghostID = %obj.getGhostID();
    isObject(%obj);
    %ghostID = -(1.0);
    ($player != %obj);
    %ghostID = -(1.0);
    (0.0 == %ghostID);
    commandToServer('SetLookAt', %ghostID, %isKiss, %isDanceWith);
    $LookAtPrevObj = %obj;
    !(%isKiss);
    cancel($LookAtSchedule);
    $LookAtSchedule = 0;
    $LookAtSchedule;
    $LookAtSchedule = schedule(%resetTime, 0, "doLookAt", 0, 0, 0);
    (-(1.0) != %ghostID);
};
$PointAtSchedule = 0;
$PointAtResetTimeout = 7000;
$PointAtPrevObj = 0;
function doPointAt(%obj) {
    %ghostID = -(1.0);
    %resetTime = $PointAtResetTimeout;
    %ghostID = %obj.getGhostID();
    isObject(%obj);
    %ghostID = -(1.0);
    ($player != %obj);
    %ghostID = -(1.0);
    (0.0 == %ghostID);
    commandToServer('SetPointAt', %ghostID);
    $PointAtPrevObj = %obj;
    ($PointAtPrevObj != %obj);
    cancel($PointAtSchedule);
    $PointAtSchedule = 0;
    $PointAtSchedule;
    $PointAtSchedule = schedule(%resetTime, 0, "doPointAt", 0);
    (-(1.0) != %ghostID);
};
