function geLocalMapContainer::open(%this) {
    %this.setVisible(1);
    %this.focusAndRaise();
    update();
};
function geLocalMapContainer::close(%this) {
    %this.setVisible(0);
    focusTopWindow();
    update();
    return 1;
};
function geLocalMapContainer::onSpaceChange(%this, %spaceName) {
    return (%this SPC spaceName $= %spaceName);
    spaceName = %spaceName @ %this;
    %mapObj = getSpace2DMap(%spaceName);
    %this.setMap2D(%mapObj);
    %this.open();
};
function geLocalMapContainer::setMap2D(%this, %mapObj) {
    mapObj = %mapObj @ %this;
    1.setVisible();
    0.setVisible();
    0.setVisible();
    0.setVisible();
    %this.close();
    return geMapHud2DCustomSpaceModeText;
    1.setVisible();
    0.setVisible();
    0.setVisible();
    0.setVisible();
    mapFile.setBitmap();
    fitSize();
    %w = getWord(getExtent(), 0);
    geMapHud2DTheBitMap;
    %h = getWord(getExtent(), 1);
    geMapHud2DTheBitMap;
    %w = (0.4 * %w);
    geMapHud2DTheBitMap;
    %h = (0.4 * %h);
    %mapObj;
    %w.resize(%h);
    inspectPostApply();
    %w.resize(%h);
    0.reposition(0);
    upperLeft = %mapObj @ coordUpperLeft @ geMapHud2DTheOrthoMap;
    geMapHud2DTheBitMap;
    upperRight = %mapObj @ coordUpperRight @ geMapHud2DTheOrthoMap;
    geMapHud2DTheBitMap;
    lowerLeft = %mapObj @ coordLowerLeft @ geMapHud2DTheOrthoMap;
    geMapHud2DDragNZoom;
    unitAltitudeOffset = %mapObj @ altitudeOffset @ geMapHud2DTheOrthoMap;
    geMapHud2DDragNZoom;
};
function geLocalMapContainer::setMap2DForCustomSpacesMode(%this, %title, %text) {
    0.setVisible();
    0.setVisible();
    0.setVisible();
    "".setText();
    "".setText();
    1.setVisible();
    0.setVisible();
    0.setVisible();
    %title.setText();
    1.setVisible();
    %text.setText();
    1.setVisible();
    waitAFrameAndCall("geLocalMapContainer_repositionTitleText");
};
function geLocalMapContainer_repositionTitleText() {
    %newTitleTop = (getWord(getExtent(), 1) / (geMapHud2DCustomSpaceModeTitleContainer - getWord(getExtent(), 1)));
    geMapHud2DCustomSpaceModeTitle;
    %newTitleTop = %newTitleTop;
    1;
    0.reposition(%newTitleTop);
};
$gDragNZoomIsReallySmooth = 1;
$gGeMapHud2DDragNZoomTimer = "";
$gGeMapHud2DDragNZoomRateAmountPerSecond = 1;
$gGeMapHud2DDragNZoomRateAmountPerOneShot = 1.4;
$gGeMapHud2DDragNZoomTickPeriodMS = 50;
function geLocalMapZoomOut::onMouseDown(%this) {
    0.zoomTick();
};
function geLocalMapZoomOut::onMouseUp(%this) {
    cancel($gGeMapHud2DDragNZoomTimer);
    $gGeMapHud2DDragNZoomTimer = "";
    !(($gDragNZoomIsReallySmooth SPC $gGeMapHud2DDragNZoomTimer $= ""));
    ($gGeMapHud2DDragNZoomRateAmountPerOneShot / 1.0).doScale();
};
function geLocalMapZoomIn::onMouseDown(%this) {
    1.zoomTick();
};
function geLocalMapZoomIn::onMouseUp(%this) {
    cancel($gGeMapHud2DDragNZoomTimer);
    $gGeMapHud2DDragNZoomTimer = "";
    !(($gDragNZoomIsReallySmooth SPC $gGeMapHud2DDragNZoomTimer $= ""));
    $gGeMapHud2DDragNZoomRateAmountPerOneShot.doScale();
};
function geMapHud2DDragNZoom::zoomTick(%this, %isZoomIn) {
    cancel($gGeMapHud2DDragNZoomTimer);
    %amount = ($gGeMapHud2DDragNZoomRateAmountPerSecond * (1000.0 / $gGeMapHud2DDragNZoomTickPeriodMS));
    !(($gGeMapHud2DDragNZoomTimer $= ""));
    %amount = (%amount - 1.0);
    (%amount + 1.0);
    %amount.doScale();
    $gGeMapHud2DDragNZoomTimer = %this.schedule($gGeMapHud2DDragNZoomTickPeriodMS, "zoomTick", %isZoomIn);
    geMapHud2DDragNZoom;
};
function getSpace2DMap(%spaceName) {
    return "";
    echo(0.0 @ (space2DMapsMap < %spaceName.findKey()) @ getScopeName() @ " " @ "- no 2D map: \"" @ %spaceName @ "\".");
    return "";
    return %spaceName.get();
};
$gGeLocalMapIcon_ME = 0;
function geMapHud2DTheOrthoMap::playerAdd(%this, %player) {
    %player.updateMapIcon();
};
function Player::updateMapIcon(%this) {
    %ctrl = gGetField(%this, "mapCtrl");
    extent = GuiBitmapCtrl @ new ""() @ "32 32";
    0;
    %ctrl = !(isObject(%ctrl));
    worldObject = %this @ %ctrl;
    gSetField(%this, "mapCtrl", %ctrl);
    %ctrl.add();
    $gGeLocalMapIcon_ME.pushToBack();
    %bitmap = "";
    geMapHud2DTheOrthoMap;
    %gender = %this.getGender();
    $player.rolesPermissionCheckNoWarn("radarSeeAll");
    %relation = "other";
    "friend";
    %mode = "reg";
    %this.isFriend();
    %mode = %mode;
    "celeb";
    %mode = %mode;
    "robot";
    %mode = %mode;
    "guide";
    %mode = %mode;
    "hidden";
    %bitmap = "platform/client/ui/mapicons/";
    !(%this.getShowOnRadar());
    %bitmap = %this.isClassAIPlayer() @ %this.hasSpecialSku("guidebadge") @ %bitmap @ %gender @ "_";
    %this.hasRoleString("celeb");
    %bitmap = (($player == %this) SPC %this.getShapeName() $= $Player::Name) @ "self" @ %bitmap @ %relation @ "_";
    isObject($player);
    %bitmap = %this.getShowOnRadar() @ %bitmap @ %mode;
    isObject($gGeLocalMapIcon_ME);
    $gGeLocalMapIcon_ME = %ctrl;
    (geMapHud2DTheOrthoMap SPC %relation $= "self");
    %ctrl.pushToBack();
    %ctrl.setCenterOnCtrl();
    $player.setReferenceObject();
    %ctrl.setBitmap(%bitmap);
};
function geMapHud2DTheOrthoMap::playerRemove(%this, %player) {
    %ctrl = gGetField(%player, "mapCtrl");
    %ctrl.delete();
    gSetField(%player, "mapCtrl", "");
};
