function MenuLayer::Initialize() {
    profile = MenuLayer @ new () @ "GuiDefaultProfile";
    GuiMouseEventCtrl;
    horizSizing = !(isObject()) @ 0 @ "width";
    MenuLayer;
    vertSizing = "height";
    position = "0 0";
    extent = getWords(getRes(), 0, 1);
    minExtent = "1 1";
    visible = 0;
    stack = "" @ MenuLayer;
    justOpened = 0 @ MenuLayer;
    activeButton = 0 @ MenuLayer;
    activeMenu = 0 @ MenuLayer;
    menus = SimSet @ new ""() @ MenuLayer;
    0;
    clones = SimSet @ new ""() @ MenuLayer;
    0;
};
function MenuLayer::show(%this) {
    return isVisible();
    MenuLayer::Initialize();
    %this.pushDialog(0);
    %this.setVisible(1);
    justOpened = Canvas @ 1 @ %this;
    %this.schedule(500, "shownForAWhile");
};
function MenuLayer::shownForAWhile(%this) {
    justOpened = 0 @ %this;
};
function MenuLayer::addCloneOf(%this, %ctrl) {
    profile = GuiMouseEventCtrl @ new ""() @ "GuiDefaultProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = %ctrl.getScreenPosition();
    extent = %ctrl.getExtent();
    minExtent = "1 1";
    sluggishness = -(1.0);
    visible = 1;
    tooltip = %ctrl @ tooltip;
    original = %ctrl;
    layer = %this;
    %clone = ;
    %clone.bindClassName("MenuButtonClone");
    %this.add(%clone);
    clones.add(%clone);
};
function MenuLayer::deleteClones(%this) {
    %count = clones.getCount();
    %this;
    %i = (1.0 - %count);
    clones.getObject(0).delete();
    %i = (1.0 - %i);
    %this;
};
function MenuLayer::setActiveButton(%this, %ctrl) {
    return !(isObject(%ctrl));
    %parent = %ctrl.getParent();
    (%this == clones.getCount());
    %count = %parent.getCount();
    isObject(%parent);
    %i = 0;
    0.0;
    %child = %parent.getObject(%i);
    (%count < %i);
    activeButton = (%ctrl.getId() == %child.getId()) @ %child.getId() @ %this;
    (%child SPC buttonType $= "MenuButton");
    %this.addCloneOf(%child);
    %i = (1.0 + %i);
    depressed = %this @ activeButton;
    (%this != activeButton.getId()) @ 0;
    menu.hide();
    activeButton = activeButton @ %ctrl.getId() @ %this;
    %this;
    depressed = %this @ activeButton;
    %ctrl.getId() @ 1;
    menu.showRelativeTo(activeButton, 1);
};
function MenuLayer::nextActiveButton(%this) {
    %next = 0;
    isObject(activeButton);
    %count = clones.getCount();
    %this;
    %i = 0;
    %this;
    %next = original;
    clones.getObject((%count % (1.0 + %i)));
    %i = (1.0 + %i);
    %this;
    %this.setActiveButton(%next);
};
function MenuLayer::previousActiveButton(%this) {
    %prev = 0;
    isObject(activeButton);
    %count = clones.getCount();
    %this;
    %i = 0;
    %this;
    %prev = original;
    clones.getObject((%count % (%count + (1.0 - %i))));
    %i = (1.0 + %i);
    %this;
    %this.setActiveButton(%prev);
};
function MenuLayer::hide(%this) {
    return !(%this.isVisible());
    %this.setVisible(0);
    %this.popDialog();
    %count = %this.getCount();
    Canvas;
    %i = 0;
    %this.getObject(%i).setVisible(0);
    %i = (1.0 + %i);
    (%count < %i);
    stack = (%count < %i) @ "" @ %this;
    depressed = %this @ activeButton;
    isObject(activeButton) @ 0;
    %this.deleteClones();
};
function MenuLayer::pop(%this) {
    %topMost = getWord(stack, 0);
    %this;
    stack = %this @ removeWord(stack, 0) @ %this;
    %topMost.hide();
    %nextHighest = getWord(stack, 0);
    %this;
    %nextHighest.makeFirstResponder(1);
};
function MenuLayer::popToMenu(%this, %menu) {
    %idx = findWord(stack, %menu);
    %this;
    %i = 0;
    (0.0 > %idx);
    scroll.setVisible(0);
    %i = (1.0 + %i);
    getWord(stack, %i);
    stack = %this @ getWords(stack, %idx) @ %this;
    (%idx < %i);
    %nextHighest = getWord(stack, 0);
    %this;
    %nextHighest.makeFirstResponder(1);
};
function MenuLayer::push(%this, %menu) {
    %menu = %menu.getId();
    %cleanStack = removeWord(stack, findWord(stack, %menu));
    %this;
    stack = %this @ trim(%menu @ " " @ %cleanStack) @ %this;
};
function MenuLayer::close(%this) {
    %this.pop();
    %this.hide();
};
function MenuLayer::onMouseDown(%this) {
    %this.hide();
};
function MenuLayer::onMouseUp(%this) {
    %this.hide();
};
function MenuLayer::onRightMouseDown(%this) {
    %this.hide();
};
function MenuLayer::newMenu(%menuName) {
    MenuLayer::Initialize();
    %menu = MenuControl::newMenuWithScroll(%menuName);
    layer = MenuLayer @ %menu;
    scroll.add();
    menus.add(%menu);
    return %menu;
};
function MenuButtonClone::onMouseEnter(%this) {
    layer.schedule(0, "setActiveButton", original);
};
function MenuButtonClone::onMouseDown(%this) {
    layer.schedule(0, "hide");
};
function MenuButtonClone::onMouseUp(%this) {
    layer.schedule(0, "onMouseUp");
};
function MenuControl::newMenuWithScroll(%menuName) {
    return %menuName.getId();
    profile = GuiScrollCtrl @ new ""() @ "ETSScrollProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "216 24";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 0;
    willFirstRespond = 1;
    hScrollBar = "alwaysOff";
    vScrollBar = "dynamic";
    constantThumbHeight = 1;
    childMargin = "0 0";
    %scroll = ;
    profile = GuiArray2Ctrl @ new ""() @ "ETSMenuProfile";
    0;
    childrenClassName = "GuiMouseEventCtrl";
    childrenExtent = "210 24";
    spacing = 2;
    numRowsOrCols = 1;
    inRows = 0;
    keyWrapX = 0;
    hilited = 0;
    unselectedProfile = "GuiDefaultProfile";
    selectedProfile = "ETSSelectedMenuItemProfile";
    menuTextProfile = "ETSUnselectedMenuTextProfile";
    menuTextSelectedProfile = "ETSSelectedMenuTextProfile";
    %menu = ;
    %menu.bindClassName("MenuControl");
    %menu.setName(%menuName);
    layer = 0 @ %menu;
    %scroll.add(%menu);
    scroll = %scroll @ %menu;
    return %menu;
};
function MenuControl::onCreatedChild(%this, %child) {
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "24 24";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "";
    %icon = ;
    %child.add(%icon);
    icon = %icon @ %child;
    profile = new ""() @ %this @ menuTextProfile;
    GuiTextCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = "30 2";
    extent = "210 20";
    minExtent = "1 1";
    sluggishness = -(1.0);
    visible = 1;
    text = "";
    maxLength = 255;
    %menuText = ;
    %child.add(%menuText);
    menuText = %menuText @ %child;
    profile = new ""() @ %this @ menuTextProfile;
    GuiTextCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = (35.0 - getWord(%child.getExtent(), 0)) @ " " @ 2;
    extent = "35 20";
    minExtent = "1 1";
    sluggishness = -(1.0);
    visible = 1;
    text = %child @ accelerator;
    maxLength = 255;
    %accelText = ;
    %child.add(%accelText);
    accelText = %accelText @ %child;
    %width = getWord(%child.getExtent(), 0);
    %height = getWord(%child.getExtent(), 1);
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = "left";
    vertSizing = "center";
    position = (10.0 - %width) @ " " @ (5.0 - (2.0 / %height));
    extent = "5 9";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 0;
    bitmap = "platform/client/ui/submenu_arrow";
    %subArrow = ;
    %child.add(%subArrow);
    subArrow = %subArrow @ %child;
    Parent = %this @ %child;
    %child.bindClassName("MenuItem");
};
function MenuControl::onKeyDown(%this, %unused, %keyCode) {
    layer.previousActiveButton();
    return 1;
    layer.nextActiveButton();
    return 1;
    return 0;
};
function MenuControl::addMenuItem(%this, %text, %command, %icon, %accelerator) {
    %item = %this.addChild();
    %item.setMenuItemText(%text);
    command = %command @ %item;
    %item.setIcon(%icon);
    %item.setAccelerator(%accelerator);
    submenu = 0 @ %item;
    subArrow.setVisible(0);
    %this.reseatChildren();
    return %item;
};
function MenuControl::addSubmenu(%this, %text, %icon, %menuName) {
    return !(isObject(layer));
    %item = %this.addChild();
    %item.setMenuItemText(%text);
    command = "" @ %item;
    %item.setIcon(%icon);
    submenu = MenuLayer::newMenu(%menuName) @ %item;
    layer = %item @ submenu;
    %this @ layer;
    subArrow.setVisible(1);
    %this.reseatChildren();
    return %item;
};
function MenuControl::showRelativeTo(%this, %baseCtrl, %vertical) {
    layer.show();
    layer.setActiveButton(%baseCtrl);
    %this.positionRelativeTo(%baseCtrl, %vertical);
    baseCtrl = %this @ %baseCtrl @ %this;
    %this;
    %this.show();
};
function MenuControl::show(%this) {
    layer.push(%this);
    scroll.setVisible(1);
    %this.hiliteCell(-(1.0), -(1.0));
    %this.makeFirstResponder(1);
};
function MenuControl::hide(%this) {
    %idx = findWord(stack, %this.getId());
    layer;
    %i = 0;
    (-(1.0) != %idx);
    scroll.setVisible(0);
    %i = (1.0 + %i);
    getWord(stack, %i);
    stack = %this @ layer;
    layer @ getWords(stack, (1.0 + %idx));
    %this.makeFirstResponder(0);
    %this.hiliteCell(-(1.0), -(1.0));
    scroll.setVisible(0);
};
function MenuControl::positionRelativeTo(%this, %baseCtrl, %vertical) {
    %scrollCtrl = scroll;
    %this;
    %screenWidth = getWord(getRes(), 0);
    %screenHeight = getWord(getRes(), 1);
    %topMargin = getWord(%baseCtrl.getScreenPosition(), 1);
    %leftMargin = getWord(%baseCtrl.getScreenPosition(), 0);
    %menuHeight = getWord(%this.getExtent(), 1);
    %vertical;
    %ctrlBottom = (%topMargin + getWord(%baseCtrl.getExtent(), 1));
    %bottomMargin = (%ctrlBottom - %screenHeight);
    %left = %leftMargin;
    (%bottomMargin <= %menuHeight);
    %top = %ctrlBottom;
    %width = getWord(%scrollCtrl.getExtent(), 0);
    %height = (2.0 + %menuHeight);
    %height = mMin(%topMargin, (2.0 + getWord(%this.getExtent(), 1)));
    (%bottomMargin >= %topMargin);
    %left = %leftMargin;
    %top = (6.0 - (%height - %topMargin));
    %width = getWord(%scrollCtrl.getExtent(), 0);
    %left = %leftMargin;
    %top = %ctrlBottom;
    %width = getWord(%scrollCtrl.getExtent(), 0);
    %height = %bottomMargin;
    %menuWidth = getWord(%this.getExtent(), 0);
    %ctrlRight = (%leftMargin + getWord(%baseCtrl.getExtent(), 0));
    %rightMargin = (%ctrlRight - %screenWidth);
    %left = %ctrlRight;
    (%leftMargin >= %rightMargin);
    %top = %topMargin;
    (%rightMargin <= %menuWidth);
    %width = getWord(%scrollCtrl.getExtent(), 0);
    %height = (2.0 + getWord(%this.getExtent(), 1));
    %left = (getWord(%scrollCtrl.getExtent(), 0) - %leftMargin);
    %top = %topMargin;
    %width = getWord(%scrollCtrl.getExtent(), 0);
    %height = (2.0 + getWord(%this.getExtent(), 1));
    %width = mMin(%width, %screenWidth);
    %height = mMin(%height, %screenHeight);
    %onscreen = onscreenCoordinates(%left, %top, %width, %height);
    %left = getWord(%onscreen, 0);
    %top = getWord(%onscreen, 1);
    %scrollCtrl.resize(%left, %top, %width, %height);
};
function MenuItem::setMenuItemText(%this, %text) {
    menuText.setText(%text);
};
function MenuItem::setIcon(%this, %icon) {
    icon.setBitmap(%icon);
};
function MenuItem::setAccelerator(%this, %accelerator) {
    accelerator = %accelerator @ %this;
    accelText.setText(%accelerator);
};
function MenuItem::onHilite(%this) {
    %scroll = scroll;
    Parent;
    %this.setProfile(selectedProfile);
    text = %this @ menuText;
    %this @ menuText.getValue();
    menuText.setProfile(menuTextSelectedProfile);
    %cellHeight = (Parent + getWord(childrenExtent, 1));
    %this;
    %numRowsVisible = (%cellHeight / getWord(%scroll.getExtent(), 1));
    spacing;
    %ypos = (getWord(Parent.getPosition(), 1) - 1.0);
    %this;
    %closestRow = (Parent / (spacing - %ypos));
    %this;
    %targetRow = getWord(hilitedCell, 1);
    Parent;
    %scroll.scrollTo(0, (spacing + (%targetRow * %cellHeight)));
    %scroll.scrollTo(0, ((1.0 + (%numRowsVisible - %targetRow)) * %cellHeight));
    %layer = layer;
    Parent;
    cancel(hoverTimer);
    hoverTimer = %layer @ %this.schedule(400, "onMouseHover") @ %layer;
    isObject(%layer);
    %currentMenu = Parent;
    %this;
    %thisIdx = findWord(stack, %currentMenu.getId());
    %layer;
    %parentMenu = getWord(stack, (1.0 + %thisIdx));
    %layer;
    %count = %parentMenu.getCount();
    isObject(%parentMenu);
    %cellIdx = -(1.0);
    (-(1.0) != %thisIdx);
    %i = 0;
    isObject(%layer);
    %cellIdx = %i;
    (%parentMenu.getObject(%i) == submenu);
    %i = (1.0 + %i);
    %currentMenu.getId();
    %parentMenu.hiliteCell(0, %cellIdx);
};
function MenuItem::onUnhilite(%this) {
    %this.setProfile(unselectedProfile);
    text = %this @ menuText;
    %this @ menuText.getValue();
    menuText.setProfile(menuTextProfile);
};
function MenuItem::onSelect(%this) {
    eval(command);
    %this.openSubmenu();
    layer.hide();
};
function MenuItem::openSubmenu(%this) {
    return !(isObject(layer));
    layer.popToMenu(Parent);
    submenu.showRelativeTo(%this, 0);
    layer.popToMenu(Parent);
};
function MenuItem::onMouseEnterBounds(%this) {
    %count = Parent.getCount();
    %this;
    %i = 0;
    %i = (1.0 + %i);
    (Parent.getObject(%i) == %this.getId());
    Parent.hiliteCell(0, %i);
};
function MenuItem::onMouseLeaveBounds(%this) {
};
function MenuItem::onMouseUp(%this) {
    %this.onSelect();
};
function MenuItem::onMouseMove(%this) {
    cancel(hoverTimer);
    hoverTimer = Parent @ layer;
    %this;
};
function MenuItem::onMouseHover(%this) {
    %this.openSubmenu();
};
