$seenThrottleMessage = 0;
$seenUnThrottleMessage = 0;
$PackageDownload::ConcurrentTextureThreshold = 10;
$PackageDownload::ConcurrentTextureMaxBytes = 10000;
$PackageDownload::MinimumCityDownloadSpeedThreshold = (1024.0 * 1.0);
$PackageDownload::MinimumCityDownloadTimeThreshold = 30;
$PackageDownload::GuestimatedSize = (1024.0 * (1024.0 * 40.0));
$PackageDownload::GuestimatedCommonSize = (1024.0 * (1024.0 * 5.0));
function queuePackageUpdatesByString(%missing) {
    %missingA = AssetManager::StringToArray(%missing);
    %missingA.reinit();
};
function queuePackageUpdates(%missing) {
    new ();
    add();
    return isActive();
    %missing = AssetManager::getMissingAssets();
    !(isObject(%missing));
    missingPackages = %missing @ packageDownload;
    init();
};
function downloadPackageUpdates(%missing) {
    queuePackageUpdates(%missing);
    start();
};
function packageDownload::reinit(%this, %missingArray) {
    %realCurrentItem = (%this - currentItem);
    1.0;
    %currentKey = missingPackages.getKey(%realCurrentItem);
    %this;
    %newMissingArray = new ""();
    Array;
    %newMissingArray.add();
    %newStatusMap = new ""();
    StringMap;
    %newStatusMap.add();
    %newStatusMap.put(%currentKey, statusMap.get(%currentKey));
    %newMissingArray.push_back(%currentKey, 0);
    echo(MissionCleanup @ (%this SPC %missingArray.getKey(0) $= %currentKey) @ "Currently downloading " @ %currentKey @ ". Will truncate current download session.");
    %i = 0;
    isObject();
    %key = %missingArray.getKey(%i);
    (%missingArray.count() < %i);
    %newStatusMap.put(%key, "incomplete");
    %newMissingArray.push_back(%key, (1.0 + %i));
    %i = (1.0 + %i);
    MissionCleanup;
    %newMissingArray.sorta();
    echo("Shifting currentItem to start. Putting new lists in place.");
    wasInterrupted = (%missingArray.count() < %i) @ 1 @ %this;
    0;
    currentItem = MissionCleanup @ 1 @ %this;
    isObject();
    statusMap.delete();
    statusMap = %this @ %newStatusMap @ %this;
    MissionCleanup;
    missingPackages.delete();
    missingPackages = %this @ %newMissingArray @ %this;
    0;
};
function packageDownload::init(%this) {
    currentItem = 0 @ %this;
    wasInterrupted = 0 @ %this;
    statusMap = StringMap @ new ""() @ %this;
    0;
    statusMap.add();
    bytesDownloadedMap = StringMap @ new ""() @ %this;
    0;
    bytesDownloadedMap.add();
    isActive = %this @ 0 @ %this;
    MissionCleanup;
    %i = 0;
    isObject();
    %key = missingPackages.getKey(%i);
    %this;
    statusMap.put(%key, "incomplete");
    bytesDownloadedMap.put(%key, 0);
    %i = (1.0 + %i);
    %this;
    return 1;
};
function packageDownload::isActive(%this) {
    return isActive;
};
function packageDownload::isDone(%this) {
    %i = 0;
    return 0;
    %i = (1.0 + %i);
    return 1;
};
function packageDownload::completedSuccessfully(%this) {
    %i = 0;
    return 0;
    %i = (1.0 + %i);
    return 1;
};
function packageDownload::getEstimatedSize(%this) {
    %total = 0;
    %i = 0;
    %total = ($PackageDownload::GuestimatedCommonSize + %total);
    (%this SPC statusMap.getKey(%i) $= $AssetManager::COMMONPACKAGE);
    %total = ($PackageDownload::GuestimatedSize + %total);
    (statusMap.size() < %i);
    %i = (1.0 + %i);
    %this;
    return %total;
};
function packageDownload::start(%this) {
    return 0;
    echo("Starting package download.");
    isActive = 1 @ %this;
    %this.downloadFile();
};
function packageDownload::doneDownloading(%this) {
    return 1;
    return 0;
};
function packageDownload::downloadFile(%this) {
    isActive = %this.doneDownloading() @ 0 @ %this;
    MessageBoxOK("Could not download", "Could not download required files. Click OK to logout.", "buttonBarMenuLogout();");
    return !(%this.completedSuccessfully());
    callBackSink.onDone(%this);
    checkForPackageUpdates(1);
    echo("resuming normal download ...");
    callBackSink = wasInterrupted @ "" @ %this;
    %this;
    return %this;
    %name = "packageDownloadClass" @ getRandom(0, 1000);
    %curl = new %name();
    URLPostObject;
    %curl.add();
    CURLObject = MissionCleanup @ %curl @ %this;
    isObject();
    %file = missingPackages.getKey(currentItem);
    %this;
    echo("Skipping empty file.");
    currentItem = (%this + currentItem);
    1.0;
    %this.downloadFile();
    return (%this SPC %file $= "");
    echo("Fetching " @ %file @ "(" @ %this @ currentItem @ ")");
    %url = $Asset::DownloadURL @ "/" @ %file;
    %curl.setURL(%url);
    %curl.setDownloadFile(%file);
    %curl.setRecvData(1);
    %curl.setProgress(1);
    %curl.setEncodings("deflate,gzip");
    echo("City threshold speed set to " @ $PackageDownload::MinimumCityDownloadSpeedThreshold @ " bytes/sec");
    %curl.setLowSpeedLimit($PackageDownload::MinimumCityDownloadSpeedThreshold);
    %curl.setLowSpeedTime($PackageDownload::MinimumCityDownloadTimeThreshold);
    callBackSink = %this @ %curl;
    NoAutoDelete = 1 @ %curl;
    packageName = %file @ %curl;
    %curl.setCompletedCallback("packageDownload_onCompletedDownload");
    statusMap.put(%file, "started");
    statusMap.put(%file, "failed");
    %curl.delete();
    echo(%this @ !(%curl.start()) @ %this @ "Problems starting download of " @ %url @ " to " @ %file);
    return;
    %curl.add();
    currentItem = (%this + currentItem);
    1.0;
};
function packageDownload::onError(%this, %request, %errNo) {
    error("Problems downloading: " @ %request.getDownloadFile());
    echo(($CURL::OperationTimedOut == %errNo) @ 3.0 @ (%this < retryCount) @ "Retrying timed-out file " @ %request.getDownloadFile() @ " (Attempt #" @ 1.0 @ (%this + retryCount) @ ")");
    retryCount = (%this + retryCount);
    1.0;
    %request.restart();
    statusMap.put(%request.getDownloadFile(), "error");
    %request.schedule(0);
    %this.downloadFile();
};
function packageDownload_onCompletedDownload(%request, %result) {
    packageName.onDone();
    %request.onError(%result);
};
function packageDownload::onDone(%this, %packageName) {
    echo("Got file " @ %packageName);
    AssetManager::updatePackageHash(%packageName);
    rescanDir("projects");
    statusMap.put(%packageName, "done");
    UpdateCityStatuses();
    %this.downloadFile();
};
function packageDownload::onProgress(%this, %this2, %dltotal, %dlnow) {
    callBackSink.onProgress(%dltotal, %dlnow);
    bytesDownloadedMap.put(packageName, %dlnow);
    echo(($PackageDownload::ConcurrentTextureThreshold > textureDownloadQueuedCount()) @ !($seenThrottleMessage) @ "textureDownloadQueuedCount is > " @ $PackageDownload::ConcurrentTextureThreshold @ ". Throttling city download.");
    $seenThrottleMessage = 1;
    %this2;
    $seenUnThrottleMessage = 0;
    packageDownload;
    CURLObject.setMaxDownloadSpeed($PackageDownload::ConcurrentTextureMaxBytes);
    echo(%this @ !($seenUnThrottleMessage) @ "Texture DownloadQueuedCount is < " @ $PackageDownload::ConcurrentTextureThreshold @ ". Un-throttling city download.");
    $seenUnThrottleMessage = 1;
    %this;
    $seenThrottleMessage = 0;
    isObject(callBackSink);
    CURLObject.setMaxDownloadSpeed(0);
};
function packageDownload::getCurrentItem(%this) {
    return missingPackages.getKey((%this - currentItem));
};
function packageDownload::getCurrentPackageIndex(%this) {
    return currentItem;
};
function packageDownload::getTotalPackages(%this) {
    return missingPackages.count();
};
function packageDownload::getCurrentCityName(%this) {
    %package = missingPackages.getKey((%this - currentItem));
    1.0;
    return "nothing";
    %package = getSubStr(strrchr(%package, "/"), 1, 100);
    %city = AssetManager::packageToCity(%package);
    %city = "common";
    (%city $= "");
    return %city;
};
function packageDownload::getItemStatus(%this, %package) {
    return statusMap.get(%package);
    return "incomplete";
};
function packageDownload::getCurrentItemStatus(%this) {
    return statusMap.get(%this.getCurrentItem());
};
function packageDownload::getPercentComplete(%this, %city) {
    %package = AssetManager::cityToPackage(%city);
    return 0;
    return 1;
    %currentDownloaded = bytesDownloadedMap.get(%package);
    %this;
    return 0;
    %percent = ($PackageDownload::GuestimatedCommonSize / %currentDownloaded);
    (%package $= $AssetManager::COMMONPACKAGE);
    %percent = ($PackageDownload::GuestimatedSize / %currentDownloaded);
    return %percent;
};
function packageDownload::getStatus(%this) {
    return %this.getCurrentItemStatus();
};
function packageDownload::getStatusForCity(%this, %city) {
    %package = AssetManager::cityToPackage(%city);
    %status = %this.getItemStatus(%package);
    %common_status = %this.getItemStatus($AssetManager::COMMONPACKAGE);
    return "done";
    return %status;
};
function checkForPackageUpdates(%startDownload) {
    return !(isValidHostAddress($Net::DownloadHost));
    className = ManagerRequest @ new ""() @ "packageDownloadCheck";
    0;
    %request = ;
    %request.add();
    startDownload = %startDownload @ %startDownload @ %request;
    MissionCleanup;
    startDownload = isObject() @ 0 @ %request;
    MissionCleanup;
    %request.setURL($Asset::DownloadURL @ "/checksums_resp.txt");
    %request.start();
};
function packageDownloadCheck::onError(%this, %unused, %errorName) {
    log("Admin", "error", getScopeName() @ " " @ getDebugString(%this) @ " " @ "- error = " @ " " @ %errorName @ " " @ "url = " @ " " @ %this.getURL());
    log("Admin", "error", "Could not contact download site. Turning off package download.");
    $AutoDownloadPackages = 0;
    %this.schedule(0);
};
function packageDownloadCheck::onDone(%this) {
    %status = findRequestStatus(%this);
    log("network", "info", getScopeName() @ " " @ "- packageDownloadCheck status =" @ " " @ %status @ " " @ "url =" @ " " @ %this.getURL());
    log("Admin", "error", getScopeName() @ " " @ "- status =" @ " " @ %status);
    log("Admin", "error", "Could not contact download site. Turning off package download.");
    $AutoDownloadPackages = 0;
    !((%status $= "success"));
    %this.schedule(0);
    return delete;
    %map = AssetManager::StringToMap(AssetManager::getCurrentAssetSet());
    %badpackages = new ""();
    Array;
    %badpackages.add();
    %available = %this.getValue("client_version");
    MissionCleanup;
    %buildVersion = formatInt("%d", getBuildVersion());
    isObject();
    %protocolVersion = formatInt("%d", getProtocolVersion());
    MissionCleanup;
    echo("There's a newer client version available. Letting normal upgrade process take over from here.");
    queuePackageUpdates(%badpackages);
    return (%protocolVersion > %available);
    %orderMap = AssetManager::getPackageOrder();
    %tempOrderArray = new ""();
    Array;
    %tempOrderArray.add();
    %n = 0;
    MissionCleanup;
    %key = %map.getKey(%n);
    (%orderMap.size() < %n);
    %remoteValue = %this.getValue(%key);
    (isObject() SPC %key $= "");
    %tempOrderArray.push_back(%key, %orderMap.get(%key));
    %n = (1.0 + %n);
    !(packageUpToDate(%map.get(%key), %remoteValue));
    %tempOrderArray.sorta();
    %n = 0;
    (%orderMap.size() < %n);
    %key = %tempOrderArray.getKey(%n);
    (%tempOrderArray.count() < %n);
    %badpackages.push_back(%key, %n);
    %n = (1.0 + %n);
    MissionCleanup;
    %badpackages.sorta();
    %tempOrderArray.delete();
    queuePackageUpdates(%badpackages);
    echo("Starting download of package updates.");
    downloadPackageUpdates();
    %this.schedule(0);
};
