$flowerGiftingEnabled = 0;
function PlayerContextMenu::init(%this, %playerName, %friendStatus, %isIgnore, %playerClicked) {
    %playerClicked = Player::findPlayerInstance(%playerName);
    !(isObject(%playerClicked));
    %this.clear();
    %hasName = !((%playerName $= ""));
    %playerName = "no-name";
    !(%hasName);
    %isNPC = isNPCName(%playerName);
    %isRentabot = rentabot_isRentabotName(%playerName);
    %sameServer = (%playerName.get() SPC serverName $= $ServerName);
    UserListFriends;
    %isRealPlayer = 0;
    !(%playerClicked.isClassAIPlayer());
    %isIdle = 0;
    %playerClicked.getAFK();
    %grey = "255 255 255 128";
    isObject(%playerClicked);
    %white = "255 255 255 255";
    isObject(%playerClicked);
    %this.addScheme(1, %grey, %grey, %grey);
    %this.addScheme(2, %white, %white, %white);
    %schemeNormal = 0;
    isObject(%playerClicked);
    %schemeDisabled = 1;
    %schemeProfile = 0;
    %schemeFavorite = 0;
    %schemePM = 1;
    0;
    %schemeIgnore = 0;
    isObject();
    %schemeReport = 0;
    pChat;
    %schemeTeleport = 0;
    %schemeMimic = 0;
    %schemeFlyTo = 0;
    %schemeTrack = 0;
    %schemeSaySumpn = 0;
    %schemeWhisper = %schemePM;
    %schemeGifting = 0;
    %schemeDanceWith = 0;
    %schemeKiss = 0;
    %schemeInfo = 2;
    %n = -(1.0);
    %onlineHere = %playerName.isOnlineHereOrNotFavorite();
    BuddyHudWin;
    %ignorable = 1;
    ($player != %playerClicked);
    %ignorable = !(%playerClicked.rolesPermissionCheckNoWarn("omnivocal"));
    isObject(%playerClicked);
    %n = (1.0 + %n);
    %this.add("** Look At My Clothes **", !((isObject(%playerClicked) SPC getWearingItemWithMoreInfo(%playerClicked) $= "")), %schemeProfile);
    %n = (1.0 + %n);
    %this.add("View Profile", %hasName, %schemeProfile);
    %n = (1.0 + %n);
    %this.add("Remove from Friends", (%friendStatus $= "friends"), %schemeFavorite);
    %n = (1.0 + %n);
    %this.add("Cancel Friend Request", (%friendStatus $= "favorite"), %schemeFavorite);
    %n = (1.0 + %n);
    %this.add("Accept Friend Request", (%friendStatus $= "fan"), %schemeFavorite);
    %n = (1.0 + %n);
    %this.add("Decline Friend Request", , %schemeFavorite);
    %n = (1.0 + %n);
    %this.add("Add to Friends", (%friendStatus $= "none"), %schemeFavorite);
    %n = (1.0 + %n);
    %this.add("Whisper", %onlineHere, %schemePM);
    %n = (1.0 + %n);
    %this.add("Two-Player Action..", !(%isIdle), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Two-Player Action.. - Too Far!", !(%playerClicked.isInRange()), %schemeDisabled);
    %n = (1.0 + %n);
    %this.add("Two-Player Action.. - Idle!", %isIdle, %schemeDisabled);
    %n = (1.0 + %n);
    %this.add("Give vCurrency", !(%isIdle), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Give vCurrency - Too Far!", !(%playerClicked.isInRange()), %schemeDisabled);
    %n = (1.0 + %n);
    %this.add("Give vCurrency - Idle!", %isIdle, %schemeDisabled);
    %n = (1.0 + %n);
    %this.add("Give Drink", !(%isIdle), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Give Drink - Too Far!", !(%playerClicked.isInRange()), %schemeDisabled);
    %n = (1.0 + %n);
    %this.add("Give Drink - Idle!", %isIdle, %schemeDisabled);
    %n = (1.0 + %n);
    %this.add("Give Gift", geGiftingPanel, %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Make Drink", !(%isIdle), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Make Drink - Too Far!", !(%playerClicked.isInRange()), %schemeDisabled);
    %n = (1.0 + %n);
    %this.add("Make Drink - Idle!", %isIdle, %schemeDisabled);
    %n = (1.0 + %n);
    %this.add("Request Music", %playerClicked.getCanHandleMusicRequest(), %schemeNormal);
    %this.add("Applaud For Me!");
    %n = (1.0 + %n);
    %this.add("This Space: Unmake Co-Host", %playerClicked.isCohost(), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("This Space: Make Co-Host", %isRealPlayer, %schemeNormal);
    %n = (1.0 + %n);
    %this.add("This Space: Kick", !(%playerClicked.isHost()), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("This Space: Block", (-(1.0) == findField($CSBlockedList, %playerName)), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("This Space: Unblock", $player.isHost(), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("This Space: Customize", %isRentabot, %schemeNormal);
    %n = (1.0 + %n);
    %this.add("This Space: Summon", !(%playerClicked.isClassAIPlayer()), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("This Space: Respawn", !(%playerClicked.isHost()), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Unignore", %isIgnore, %schemeIgnore);
    %n = (1.0 + %n);
    %this.add("Ignore", %ignorable, %schemeIgnore);
    %n = (1.0 + %n);
    %this.add("Teleport To", ($player != %playerClicked), %schemeTeleport);
    %n = (1.0 + %n);
    %this.add("Report Abuse", !(%isRentabot), %schemeProfile);
    %skuSelf = getSpecialSKU($player, "flower");
    %isNPC;
    %skuThem = getSpecialSKU(%playerClicked, "flower");
    isObject(%playerClicked);
    %n = (1.0 + %n);
    %this.add("Take Flower", !($player.hasInventorySKU(%skuSelf)), %schemeGifting);
    %skuSelf = getSpecialSKU($player, "flower");
    !(%isNPC);
    %n = (1.0 + %n);
    %this.add("Give Flower", $player.hasInventorySKU(%skuSelf), %schemeGifting);
    %helpmesku = getSpecialSKU(%playerClicked, "helpmebadge");
    isObject(%playerClicked);
    %n = (1.0 + %n);
    %this.addIfPermitted("answerHelpMe", "Turn off Help Request", %playerClicked.hasActiveSKU(%helpmesku), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("** Look At My Clothes **", !((isObject(%playerClicked) SPC getWearingItemWithMoreInfo(%playerClicked) $= "")), 0);
    %n = (1.0 + %n);
    %this.add("My Profile & Account (web)", isObject(%playerClicked), 0);
    %n = (1.0 + %n);
    %this.add("Edit Away Message", %playerClicked.hasActiveSKU(%skuThem), 0);
    %n = (1.0 + %n);
    %this.add("Back From Idle", isIdle(), 0);
    %n = (1.0 + %n);
    %this.add("Go Idle", $flowerGiftingEnabled, 0);
    %n = (1.0 + %n);
    %this.add("Allow Teleports", $UserPref::Player::TeleportBlock, 0);
    %n = (1.0 + %n);
    %this.add("Refuse Teleports", %onlineHere, 0);
    %n = (1.0 + %n);
    %this.add("Allow Whispers", $UserPref::Player::WhisperBlock, 0);
    %n = (1.0 + %n);
    %this.add("Refuse Whispers", isObject(%playerClicked), 0);
    %n = (1.0 + %n);
    %this.add("Allow Yells", $UserPref::Player::YellBlock, 0);
    %n = (1.0 + %n);
    %this.add("Refuse Yells", CustomSpaceClient::isOwner(), 0);
    %n = (1.0 + %n);
    %this.add("Respawn Me!", %isNPC, 0);
    %n = (1.0 + %n);
    %this.add("Stop being Co-Host", %playerClicked.isCohost(), 0);
    %text = "";
    (%onlineHere SPC %friendStatus $= "friends");
    %sku = getSpecialSKU(%playerClicked, "hostBadge");
    %playerClicked.isHost();
    %text = "Hide Host Badge";
    hasWord(%playerClicked.getActiveSKUs(), %sku);
    %text = "Wear Host Badge";
    $player.isHost();
    %sku = getSpecialSKU(%playerClicked, "cohostBadge");
    %playerClicked.isCohost();
    %text = "Hide Cohost Badge";
    hasWord(%playerClicked.getActiveSKUs(), %sku);
    %text = "Wear Cohost Badge";
    !(%playerClicked.rolesPermissionCheckNoWarn("customspaceImmune"));
    %n = (1.0 + %n);
    %this.add(%text, !(($player.isHostOrCohost() SPC %text $= "")), 0);
    %n = (1.0 + %n);
    %this.add("Make Drink", $player.getActiveSKUs().hasSkuWithAnyTags("drinkMaker"), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Drop Microphone", %playerClicked.hasMicrophone(), 0);
    %this.add("Invite to game");
    %this.add("Change score");
    %this.add("Change status");
    %n = (1.0 + %n);
    %this.addIfPermitted("snoop", "        --- mod/staff ---", areWeHostOfInspectedGame(), %schemeDisabled);
    %n = (1.0 + %n);
    %this.addIfPermitted("manageUsersBasic", "Ban...", gameMgrClient, %schemeNormal);
    %n = (1.0 + %n);
    %this.addIfPermitted("manageUsersBasic", "Manage on Web", inCustomGame(), %schemeNormal);
    %n = (1.0 + %n);
    %this.addIfPermitted("track", "Fly To", gameMgrClient, %schemeFlyTo);
    %n = (1.0 + %n);
    %this.addIfPermitted("track", "Track", ($player != %playerClicked), %schemeTrack);
    %n = (1.0 + %n);
    %this.addIfPermitted("manageUsersBasic", "Peek at GameState", areWeInspecting(), %schemeNormal);
    %n = (1.0 + %n);
    %this.addIfPermitted("snoop", "unSnoop", %playerClicked.hasRoleString("snooped"), %schemeNormal);
    %n = (1.0 + %n);
    %this.addIfPermitted("snoop", "Snoop", isObject(%playerClicked), %schemeNormal);
    %n = (1.0 + %n);
    %this.addIfPermitted("snoop", "Snoop", gameMgrClient, %schemeNormal);
    %n = (1.0 + %n);
    %this.addIfPermitted("snoop", "unSnoop", SkuManager, %schemeNormal);
    %n = (1.0 + %n);
    %this.addIfPermitted("track", "Teleport To", CustomSpaceClient::isOwner(), %schemeTeleport);
    %n = (1.0 + %n);
    %this.addIfPermitted("summon", "Respawn", isObject(%playerClicked), %schemeNormal);
    %n = (1.0 + %n);
    %this.addIfPermitted("summon", "Summon", !(%isRentabot), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Revoke Microphone", %playerClicked.hasMicrophone(), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Give Microphone", isObject(%playerClicked), %schemeNormal);
    %n = (1.0 + %n);
    %this.add($player.rolesPermissionCheckNoWarn("microphones") @ $player.isDebugging() @ "        --- debug --- (" @ %playerClicked @ ")", $player.isHostOrCohost(), %schemeDisabled);
    %n = (1.0 + %n);
    %this.add("Set Height: really tall", $StandAlone, %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Set Height: tall", %isNPC, %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Set Height: medium", CustomSpaceClient::isOwner(), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Set Height: short", %isRealPlayer, %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Set Height: really short", $player.isHost(), %schemeNormal);
    %n = (1.0 + %n);
    %this.add("Relative Transform", $player.isHostOrCohost(), %schemeSaySumpn);
    %n = (1.0 + %n);
    %this.add("Body Mod", isObject(%playerClicked), %schemeSaySumpn);
    %n = (1.0 + %n);
    %this.add("Puppetry: Copy Skus", isObject(%playerClicked), %schemeSaySumpn);
    %n = (1.0 + %n);
    %this.add("Puppetry: Paste Skus", geGiftingPanel, %schemeSaySumpn);
    %n = (1.0 + %n);
    %this.add("Puppetry: Speak", isObject(), %schemeSaySumpn);
    %n = (1.0 + %n);
    %this.add("Puppetry: Whisper", isObject(), %schemeWhisper);
    %n = (1.0 + %n);
    %this.add("Puppetry: Yell", isObject(), %schemeSaySumpn);
    %n = (1.0 + %n);
    %this.add("Puppetry: SOS", isObject(), %schemeSaySumpn);
    %n = (1.0 + %n);
    %this.add("Puppetry: Dance", (pChat SPC %playerClicked.getClassName() $= "AIPlayer"), %schemeSaySumpn);
    %n = (1.0 + %n);
    %this.add("Puppetry: Emote", pChat, %schemeSaySumpn);
    %n = (1.0 + %n);
    %this.add("Puppetry: Be Still", pChat, %schemeSaySumpn);
    %n = (1.0 + %n);
    %this.add("Puppetry: Puppy", pChat, %schemeSaySumpn);
    %n = (1.0 + %n);
    %this.add("Puppetry: Badge", isObject(), %schemeSaySumpn);
    %n = (1.0 + %n);
    %this.add("Puppetry: Dance With", pChat, %schemeSaySumpn);
    %n = (1.0 + %n);
    %this.add("Puppetry: Kiss", %playerClicked.isInRange(), %schemeSaySumpn);
    %title = %playerName;
    geGiftingPanel;
    %title = %title @ " " @ "(this is you)";
    ($player == %playerClicked);
    %title = %title @ " " @ "(a bot)";
    %isNPC;
    %this.setText(%title);
    gSetField(%this, "playerName", %playerName);
    gSetField(%this, "player", %playerClicked);
    gSetField(%this, "aimName", "");
};
function PlayerContextMenu::initForAIM(%this, %aimName) {
    %this.clear();
    %n = -(1.0);
    %n = (1.0 + %n);
    %this.add("Message", , 0);
    %n = (1.0 + %n);
    %this.add("Send Invite", showInviteFriend(), 0);
    %this.setText(%aimName);
    gSetField(%this, "playerName", "");
    gSetField(%this, "player", "");
    gSetField(%this, "aimName", %aimName);
};
function PlayerContextMenu::addIfPermitted(%this, %permName, %text, %n, %scheme) {
    %skuGuide = getSpecialSKU($player, "guidebadge");
    ($player.rolesPermissionCheckNoWarn(%permName) SPC %permName $= "answerHelpMe");
    %skuSGuide = getSpecialSKU($player, "seniorguidebadge");
    return !($player.hasActiveSKU(%skuSGuide));
    %this.add(%text, %n, %scheme);
};
function PlayerContextMenu::initWithPlayerName(%this, %playerName) {
    %playerObj = $player;
    (%playerName $= $player.getShapeName());
    %playerObj = 0;
    %this.init(%playerName, %playerName.getFriendStatus(), %playerName.getIgnoreStatus(), %playerObj);
};
function PlayerContextMenu::initWithPlayer(%this, %player) {
    %playerName = %player.getShapeName();
    %this.init(%playerName, %playerName.getFriendStatus(), %playerName.getIgnoreStatus(), %player);
};
function PlayerContextMenu::onSelect(%this, %unused, %text) {
    %player = gGetField(%this, "player");
    %playerName = gGetField(%this, "playerName");
    %aimName = gGetField(%this, "aimName");
    %handled = 0;
    %handled = 1;
    !(%handled);
    doUserProfile(%playerName);
    doUserFavorite(%playerName, "remove");
    doUserFavorite(%playerName, "cancel");
    doUserFavorite(%playerName, "accept");
    doUserFavorite(%playerName, "decline");
    doUserFavorite(%playerName, "add");
    openUserWhisper(%playerName);
    %playerName.open();
    %playerName.open("initiate");
    drinks_confirmInitiateGift(%playerName);
    gotoWebPage((TwoPlayerEmotesPanel SPC %text $= "Give vCurrency") @ ((geGiftingPanel SPC %text $= "Give Drink") SPC %text $= "Give Gift") @ "http://www.vside.com/app/gifting/user/" @ urlEncode(%playerName) @ "/", 0);
    $gSalonChairCurrent = "";
    (((((((((%text $= "View Profile") SPC %text $= "Remove from Friends") SPC %text $= "Cancel Friend Request") SPC %text $= "Accept Friend Request") SPC %text $= "Decline Friend Request") SPC %text $= "Add to Friends") SPC %text $= "Whisper") SPC %text $= "Two-Player Action..") SPC %text $= "Make Drink");
    ShowSalonMenu("drinks", "n", %playerName);
    gotoWebPage($Net::MusicURL);
    %playerName.invitePlayerToInspectedGame();
    %playerName.doHostPopupChangeScore();
    %playerName.doHostPopupChangeStatus();
    %handled = 0;
    gameMgrClient;
    %handled = 1;
    !(%handled);
    CustomSpaceClient::setCoHostHood(%playerName, 1);
    CustomSpaceClient::setCoHostHood(%playerName, 0);
    CustomSpaceClient::setCoHostHood(%playerName, 0);
    delayedRemoveSku(getSpecialSKU($player, "hostBadge"));
    delayedWearSku(getSpecialSKU($player, "hostBadge"));
    delayedRemoveSku(getSpecialSKU($player, "cohostBadge"));
    delayedWearSku(getSpecialSKU($player, "cohostBadge"));
    CustomSpaceClient::doOwnerAction("kick", %playerName);
    CustomSpaceClient::TryBlockUserFromSpace(%playerName, 0);
    CustomSpaceClient::TryBlockUserFromSpace(%playerName, 1);
    CustomSpaceClient::doOwnerAction("summon", %playerName);
    CustomSpaceClient::doOwnerAction("respawn", %playerName);
    CustomSpaceClient::doOwnerAction("teleport", %playerName);
    rentabotClient_customizeBot(%player);
    doUserIgnore(%playerName, "add");
    doUserIgnore(%playerName, "remove");
    doUserMimic(%player);
    doUserReport(%playerName, "abuse");
    doEditProfile();
    doEditAwayMessage();
    setIdle(1);
    setIdle(0);
    0.setValue();
    doTeleportBlock();
    1.setValue();
    doTeleportBlock();
    0.setValue();
    doWhisperBlock(1);
    1.setValue();
    doWhisperBlock(1);
    0.setValue();
    1.setValue();
    doRespawnMe();
    doDropMic();
    doLookAtMyClothes(%player);
    doCheerFor(%playerName);
    %handled = 0;
    ((((YellBlockCheckBox SPC %text $= "Respawn Me!") SPC %text $= "Drop Microphone") SPC %text $= "** Look At My Clothes **") SPC %text $= "Applaud For Me!");
    %handled = 1;
    !(%handled);
    %playerName.get().setHeight(1.15);
    %playerName.get().setHeight(1.075);
    %playerName.get().setHeight(1);
    %playerName.get().setHeight(0.93);
    %playerName.get().setHeight(0.86);
    doUserSaySomething(%playerName);
    doUserWhisperSomething(%playerName);
    doUserYellSomething(%playerName);
    doUserSosSomething(%playerName);
    doUserAutoEmote(%playerName, "dance");
    doUserAutoEmote(%playerName, "emote");
    doUserAutoEmoteRate(%playerName, "blend", 300, 200);
    doUserAutoEmote(%playerName, "");
    doUserPuppy(%playerName);
    doUserBadge(%playerName);
    doDanceWith(%player);
    doKiss(%player);
    doUserCopySkus(%playerName);
    doUserPasteSkus(%playerName);
    doUserBodyMod(%player);
    doUserRelativeTransform(%player);
    teleportOperation(%playerName);
    doUserFlyTo(%playerName);
    doUserPeekAtGameState(%playerName);
    doUserTrack(%playerName);
    doUserSnoop(%playerName, 1);
    doUserSnoop(%playerName, 0);
    doUserRespawn(%playerName);
    doUserSummon(%playerName);
    doUserBan(%playerName);
    doUserManage(%playerName);
    doTakeFlower(%playerName);
    doGiveFlower(%playerName);
    doTurnOffHelpme(%playerName);
    doMicrophoneGiveOrRevoke(%playerName, 0);
    doMicrophoneGiveOrRevoke(%playerName, 1);
    %aimName.talkTo();
    %aimName.open();
    %handled = 0;
    AimInviteDialog;
};
function PlayerContextMenu::showComingSoon(%this, %featureName) {
    MessageBoxOK(%featureName @ " " @ "- Coming Soon!", "The" @ " " @ %featureName @ " " @ "feature will be here soon!", "");
};
function PlayGui::onRMBPlayer(%this, %obj) {
    %obj.initWithPlayer();
    getCursorPos().showAtPoint();
};
function BuddyHudRequestsList::onRightMouseUp(%this) {
    %text = stripUnprintables(%this.getRowText(%this.getMouseOverRow()));
    %text.initWithPlayerName();
    getCursorPos().showAtPoint();
    warn("Got empty player name from right click on FavoritesList");
};
function doUserMimic(%player) {
    commandToServer('EtsPlayerClickedSharedAnim', %player.getGhostID());
};
function doGiftInventoryItemToPlayer(%playerName, %sku) {
    commandToServer('GiftInventoryItemToPlayer', %playerName, %sku);
};
function doRespawnMe() {
    commandToServer('respawnMe');
};
function doDropMic() {
    commandToServer('dropMic');
};
function doDanceWith(%obj) {
    doLookAt(%obj, 1, 0);
};
function doKiss(%obj) {
    doLookAt(%obj, 0, 1, 0);
};
$InspectSkusMap = 0;
function getWearingItemWithMoreInfo(%player) {
    $InspectSkusMap = new ""();
    StringMap;
    $InspectSkusMap.add();
    $InspectSkusMap.put(22228, "neptune");
    $InspectSkusMap.put(22229, "neptune");
    $InspectSkusMap.put(32261, "rtv");
    $InspectSkusMap.put(32262, "rtv");
    $InspectSkusMap.put(22212, "masquerade");
    $InspectSkusMap.put(22213, "masquerade");
    $InspectSkusMap.put(32259, "viper");
    $InspectSkusMap.put(32260, "viper");
    $InspectSkusMap.put(22210, "wireless");
    $InspectSkusMap.put(22211, "wireless");
    $InspectSkusMap.put(32257, "visionvamp");
    $InspectSkusMap.put(32258, "visionvamp");
    $InspectSkusMap.put(22230, "crown");
    $InspectSkusMap.put(22231, "crown");
    $InspectSkusMap.put(32274, "cosmicyoga");
    $InspectSkusMap.put(32275, "cosmicyoga");
    $InspectSkusMap.put(22214, "royalflush");
    $InspectSkusMap.put(22215, "royalflush");
    $InspectSkusMap.put(32255, "warrior");
    $InspectSkusMap.put(32256, "warrior");
    %skusList = %player.getActiveSKUs();
    MissionCleanup;
    %num = getWordCount(%skusList);
    isObject();
    %inspectTextDir = "projects/common/inventoryInspect/";
    MissionCleanup;
    %i = 0;
    0;
    %skunum = getWord(%skusList, %i);
    (%num < %i);
    %mapped = $InspectSkusMap.get(%skunum);
    !(isObject($InspectSkusMap));
    %skunum = %mapped;
    !((%mapped $= ""));
    %inspectFile = %inspectTextDir @ %skunum @ ".txt";
    %fo = new ""();
    FileObject;
    %fo.delete();
    return %inspectFile;
    %fo.delete();
    %i = (1.0 + %i);
    return "";
};
function doLookAtMyClothes(%player) {
    echo("TODO:  make this pick the proper thing");
    %file = getWearingItemWithMoreInfo(%player);
    echo("looking closer at player's clothes");
    %file.OnInspect();
};
function doCheerFor(%playerName) {
    "applause".open(%playerName);
};
function doTurnOffHelpme(%playerName) {
    commandToServer('TurnOffHelpMeMode', %playerName);
};
