$Net::TwitterBaseInsecure = "http" @ "://twitter.com";
$Net::TwitterBaseSecure = "https" @ "://twitter.com";
function sendRequest_Twitter_verify_credentials(%user, %pass, %callbackHandler) {
    %request = safeNewScriptObject("URLPostObject", "", 0);
    %url = "";
    %url = %url @ $Net::TwitterBaseSecure;
    %url = %url @ "/account/verify_credentials.xml";
    %url.setURL(%request);
    %user @ ":" @ %pass.setUserNameAndPassword(%request);
    %callbackHandler.setCompletedCallback(%request);
    0.setAutoParseResults(%request);
    %request.start();
    return %request;
};
function sendRequest_Twitter_statuses_update(%user, %pass, %tweetText, %callbackHandler) {
    %request = safeNewScriptObject("URLPostObject", "", 0);
    %url = "";
    %url = %url @ $Net::TwitterBaseSecure;
    %url = %url @ "/statuses/update.xml";
    %url.setURL(%request);
    %user @ ":" @ %pass.setUserNameAndPassword(%request);
    %callbackHandler.setCompletedCallback(%request);
    0.setAutoParseResults(%request);
    %tweetText.setBodyParam(%request, "status");
    %request.start();
    return %request;
};
$Net::BitlyAPIBaseInsecure = "http" @ "://api.bit.ly";
$Net::BitlyAPILogin = "vside";
$Net::BitlyAPIKey = "R_6758b664dc52a268180b030a0b3e88bf";
function sendRequest_Bitly_shorten(%longUrl, %callbackHandler) {
    %request = safeNewScriptObject("URLPostObject", "", 0);
    %url = "";
    %url = %url @ $Net::BitlyAPIBaseInsecure;
    %url = %url @ "/shorten";
    %url.setURL(%request);
    $Net::BitlyAPILogin @ ":" @ $Net::BitlyAPIKey.setUserNameAndPassword(%request);
    %callbackHandler.setCompletedCallback(%request);
    0.setAutoParseResults(%request);
    %longUrl.setURLParam(%request, "longUrl");
    "xml".setURLParam(%request, "format");
    "2.0.1".setURLParam(%request, "version");
    %request.start();
    return %request;
};
