function SalonStyleSelector::refreshAvailableStyles(%this) {
    ShowSalonMenu(lastTypeOfSalon, lastClientGender);
};
function ShowSalonMenu(%typeOfSalon, %clientGender, %targetPlayerName) {
    %targetPlayerName = "";
    !(isDefined("%targetPlayerName"));
    lastTypeOfSalon = %typeOfSalon @ SalonStyleSelector;
    lastClientGender = %clientGender @ SalonStyleSelector;
    open();
    %targetPlayer = Player::findPlayerInstance(%targetPlayerName);
    "";
    targetPlayer = (SalonStyleSelector SPC %targetPlayerName $= "") @ %targetPlayer @ SalonStyleSelector;
    %thumbsDirectory = "platform/client/ui/salon/salonthumbs_";
    SalonStyleSelectorChair @ %thumbsDirectory @ %typeOfSalon.setBitmap();
    %text = "Choose" @ " " @ %typeOfSalon[$SALON_CHAIR_DEF_PROPDESC @ %typeOfSalon] @ " " @ "Prop";
    %text.setText();
    %text = %typeOfSalon[$SALON_CHAIR_DEF_SALONMENUDESC @ %typeOfSalon];
    ShowPropsButton;
    %text = strreplace(%text, "[TARGET]", %targetPlayerName);
    %text.setText();
    closeButton.setVisible(%typeOfSalon[$SALON_CHAIR_DEF_CANCLOSE @ %typeOfSalon]);
    %propSku = $player.getActivePropSku();
    SalonStyleSelector;
    %propThumbsDir = "platform/client/ui/props/propthumbs_";
    gePropsWindowTitle;
    %propThumbFile = "" @ %propThumbsDir @ %propSku;
    (%propSku $= "");
    "".setBitmap();
    %propThumbFile.setBitmap();
    %list = skuGuiList;
    SalonStyleSelector;
    %list.setNumChildren(0);
    childrenExtent = %list @ ((spacing * 2.0) - getWord(%list.getExtent(), 0)) @ " " @ 40 @ %list;
    SalonStyleSelectorProp;
    %width = getWord(childrenExtent, 0);
    %list;
    %i = 0;
    SalonStyleSelectorProp;
    %skunum = %i[$SALON_STYLE_SKU @ %i];
    ($NUM_SALON_STYLES < %i);
    %grouping = %i[$SALON_STYLE_GROUPING @ %i];
    !(isFile((%propThumbFile $= "") @ %propThumbFile @ ".png"));
    %req = %i[$SALON_STYLE_REQUIREDSKUS @ %i];
    %si = %skunum.findBySku();
    SkuManager;
    %iconPath = (%si SPC gender $= "n") @ %thumbsDirectory @ %skunum;
    (%si SPC gender $= %clientGender);
    %linkStart = isObject(%si) @ "<a:gamelink chooseStyle" @ " " @ %i @ ">";
    !(DoesPlayerHaveItemActive($player, %req));
    %thumbnail = "";
    !((!((%grouping $= %typeOfSalon)) SPC %req $= ""));
    %description = descShrt;
    %si;
    %text = %linkStart @ %thumbnail @ " " @ "<clip:" @ %width @ ">" @ %description @ "</clip></a>";
    %text = mlStyle(%text, "salonPanel");
    %item = %list.addChild();
    extent = GuiBitmapCtrl @ new ""() @ "46 40";
    0;
    bitmap = %iconPath;
    position = GuiBitmapButtonCtrl @ new ""() @ "1 1";
    extent = "44 38";
    bitmap = "platform/client/buttons/tgf/tgf_buttonframe_190x109";
    command = "SalonChooseStyle(" @ %i @ ");";
    %iconCtrl = ;
    position = GuiMLTextCtrl @ new ""() @ "50 13";
    0;
    extent = "142 20";
    bitmap = %iconPath;
    %textCtrl = ;
    %item.add(%iconCtrl);
    %item.add(%textCtrl);
    %textCtrl.bindClassName("SalonStyleSelectorRow");
    %textCtrl.setProfile();
    %textCtrl.setText(%text);
    %i = (1.0 + %i);
    InfoWindowTextListProfile;
    %list.reseatChildren();
    %msg = "No styles available.\nChoose another prop.";
    "No styles available.\nTry choosing a prop.";
    noSkuGuiText.setText(SalonStyleSelector @ "<just:center>" @ %msg);
    noSkuGuiText.setText("");
};
function SalonStyleSelectorRow::onURL(%this, %url) {
    %url = restWords(%url);
    (firstWord(%url) $= "gamelink");
    %styleNumber = getWord(%url, 1);
    (firstWord(%url) $= "chooseStyle");
    SalonChooseStyle(%styleNumber);
};
function clientCmdShowSalonMenu(%salonChair, %gender, %typeOfSalon) {
    $gSalonChairCurrent = %salonChair;
    ShowSalonMenu(%typeOfSalon, %gender);
};
function clientCmdHideSalonMenu(%salonChair) {
    return !(($gSalonChairCurrent $= %salonChair));
    cancel($gSalonStylistAnimSchedule);
    $gSalonStylistAnimSchedule = 0;
    $gSalonChairCurrent = 0;
    close();
};
function SalonGiveTheStyleToClient(%styleNumber) {
    cancel($gSalonStylistAnimSchedule);
    $gSalonStylistAnimSchedule = 0;
    commandToServer('SalonChooseStyle', $gSalonChairCurrent, %styleNumber);
};
function SalonChooseStyle(%styleNumber) {
    cancel($gSalonStylistAnimSchedule);
    $gSalonStylistAnimSchedule = 0;
    %sku = %styleNumber[$SALON_STYLE_SKU @ %styleNumber];
    %req = %styleNumber[$SALON_STYLE_REQUIREDSKUS @ %styleNumber];
    %reqMsg = %styleNumber[$SALON_STYLE_REQUREDSKUSMESSAGE @ %styleNumber];
    %anim = %styleNumber[$SALON_STYLE_ANIMATION @ %styleNumber];
    %cutTime = %styleNumber[$SALON_STYLE_CUTTIME @ %styleNumber];
    %reqname = getSkuShortName(%req);
    !(DoesPlayerHaveItemActive($player, %req));
    MessageBoxOK("vSalon", %reqMsg, "");
    return !((%req $= ""));
    drinks_confirmInitiateMake(targetPlayer.getShapeName(), %sku);
    commandToServer('EtsPlayAnimName', %anim);
    $gSalonStylistAnimSchedule = schedule(%cutTime, 0, "SalonGiveTheStyleToClient", %styleNumber);
    SalonStyleSelector;
};
$gSalonStylistAnimSchedule = 0;
$gSalonChairCurrent = 0;
