function Player::onGotSKUs(%this) {
    currentBaseActiveSkus = %this.getActiveSKUs() @ %this;
    %this.setBlendTargetValue($BB_UPPR_MICROPHONE, 0.2);
    %this.triggerBoneBlendAnimation($BB_UPPR_MICROPHONE, 1, 0);
    %this.setBlendTargetValue($BB_UPPR_MICROPHONE, 0);
    %this.triggerBoneBlendAnimation($BB_UPPR_MICROPHONE, 0, 0);
    return !((%this.hasMicrophone() SPC %this.getShapeName() $= $Player::Name));
    %skus = %this.getActiveSKUs();
    %gender = %this.getGender();
    %outfitName = $gOutfits.get("currentOutfit");
    $gOutfits.put(%gender @ "Body", %skus.filterSkusForBody());
    $gOutfits.put(SkuManager @ %gender @ %outfitName, %skus.filterSkusForClothing());
    $Player::IsInHelpMeMode = %this.isInHelpMeMode();
    SkuManager;
    refreshAvailableStyles();
    %instrumentGenre = "";
    SalonStyleSelector;
    %usingInstrument = 0;
    isObject();
    %i = (InstrumentRegistryClient - getInstrumentCount());
    1.0;
    %instrument = %i.getInstrumentByIndex();
    InstrumentRegistryClient;
    "instrument".open(name);
    %instrumentGenre = genre;
    %instrument;
    %usingInstrument = 1;
    %instrument;
    %i = (1.0 - %i);
    ApplauseMeterGui;
    closingFromServer = (ApplauseMeterGui SPC applauseMeterUse $= "instrument") @ 1 @ ApplauseMeterGui;
    !(%usingInstrument);
    close();
    %propSku = %this.getActivePropSku();
    ApplauseMeterGui;
    %currentGenre = %this.getGenre();
    !(%usingInstrument);
    %propGenre = %currentGenre;
    isPropGenre(%currentGenre);
    %propGenre = "y";
    ((0.0 >= %i) SPC %propSku $= "");
    %propGenre = %propSku.get();
    PropGenreMap;
    error(getScopeName() @ " " @ "- could not find genre for sku" @ " " @ %propSku @ " " @ "using y." @ " " @ getTrace());
    %propGenre = "y";
    (hasWord(%skus, skus) SPC %propGenre $= "");
    %currentGenreIsInstrumentGenre = %currentGenre.isInstrumentGenre();
    InstrumentRegistryClient;
    %currentGenreIsPropGenre = isPropGenre(%currentGenre);
    !(%usingInstrument) @ %gender @ %instrument;
    commandToServer('EnterSpecialGenre', %instrumentGenre);
    commandToServer('ExitSpecialGenre', %currentGenre);
    commandToServer('EnterSpecialGenre', %propGenre);
    commandToServer('ExitSpecialGenre', %propGenre);
    commandToServer('SwitchSpecialGenre', %currentGenre, %propGenre);
    commandToServer('setGenre', $UserPref::Player::Genre);
    updateHelpMeModeMenu();
    updateModeIcon();
    %this.resetSkuEffectsClient();
    %n = (1.0 - getWordCount(%skus));
    MessageHud;
    %sku = getWord(%skus, %n);
    (0.0 >= %n);
    trySkuNotification(%sku);
    %this.trySkuEffectsClient(%sku);
    %n = (1.0 - %n);
    !(hasWord(prevActiveSkus, %sku));
    prevActiveSkus = (0.0 >= %n) @ %this.getActiveSKUs() @ %this;
    %this;
};
function Player::applySkuBadge(%this, %skunum) {
    %prevSkuBadge = gGetField(%this);
    prevSkuBadge;
    return (%skunum == %prevSkuBadge);
    gSetField(%this, %skunum);
    %this.updateMapIcon();
    %hudCtrl = hudCtrl;
    %this;
    return !(isObject(%hudCtrl));
    trySkuNotification(%skunum);
    badge.setVisible(0);
    return %hudCtrl;
    %si = %skunum.findBySku();
    SkuManager;
    return !(isObject(%si));
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = %hudCtrl @ !(isObject(badge)) @ "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "64 64";
    minExtent = "64 64";
    sluggishness = -1;
    visible = 1;
    %ctrl = ;
    %hudCtrl.add(%ctrl);
    badge = %ctrl @ %hudCtrl;
    %bitmap = getBitmapFilename("badge", getWord(%si.getTxtrNames(), 0));
    badge.setBitmap(%bitmap);
    badge.setVisible(1);
};
$gSkuNotificationsMap = 0;
function initSkuNotificationsMap() {
    return isObject($gSkuNotificationsMap);
    $gSkuNotificationsMap = safeNewScriptObject("StringMap", "", 1);
    $gSkuNotificationsMap.put(17002, "displayMicrophoneHelp();");
    $gSkuNotificationsMap.put(27002, "displayMicrophoneHelp();");
};
function trySkuNotification(%skunum) {
    initSkuNotificationsMap();
    %cmd = $gSkuNotificationsMap.get(%skunum);
    eval(%cmd);
};
function Player::resetSkuEffectsClient(%this) {
    %this.staggerSetAmount(0);
};
function Player::trySkuEffectsClient(%this, %sku) {
    %si = %sku.findBySku();
    SkuManager;
    %this.staggerSetAmount(0.1);
    %this.staggerSetAmount(0.05);
    %this.staggerSetAmount(0.01);
};
function SkuItem::getBitmapPath(%this) {
    %ret = getBitmapFilename(skuType, getWord(%this.getTxtrNames(), 1));
    %this;
    %ret = getBitmapFilename(skuType, getWord(%this.getTxtrNames(), 0));
    %this;
};
