$gDifSkusCurrentDif = "";
$gDifSkusCurrentBaseSwatch = "";
$gDifSkusCurrentSwatch = "";
$gSwatchPaintingModeOn = 0;
function tryOnMouseOverSwatches(%obj) {
    %swallowed = 0;
    %swallowed = 1;
    objectIsSwatchable(%obj);
    onMouseOverSwatchObj(%obj);
    onMouseOverSwatchObj(0);
    return %swallowed;
};
function onMouseOverSwatchObj(%obj) {
    $gDifSkusCurrentDif = %obj;
    %obj = "";
    !($gSwatchPaintingModeOn);
    $gDifSkusCurrentBaseSwatch = getLastRayCastTextureName().findByTexture();
    PlayGui;
    $gDifSkusCurrentBaseSwatch = "obj" @ " " @ %obj;
    (0.0 > %obj.getInventoryNuggetSKU());
    $TSControl::objSelContinuous = 1;
    SkuManager;
    $gDifSkusCurrentBaseSwatch = 0;
    ($TypeMasks::InteriorObjectType & %obj.getType());
    $TSControl::objSelContinuous = 0;
    isObject(%obj);
    updateSwatchBrush();
};
function updateSwatchBrush() {
    profile = geSwatchBrushContainer @ new () @ "SwatchBrushProfile";
    GuiControl;
    extent = !(isObject()) @ 0 @ "72 72";
    geSwatchBrushContainer;
    profile = geSwatchBrushBitmap @ new () @ "ETSNonModalProfile";
    GuiBitmapCtrl;
    extent = "70 70";
    position = "1 1";
    modulationColor = "255 255 255 200";
    profile = geSwatchBrushObjectShadowBitmap @ new () @ "ETSNonModalProfile";
    GuiBitmapCtrl;
    position = "1 34";
    extent = "33 33";
    modulationColor = "0 0 0 200";
    profile = geSwatchBrushObjectBitmap @ new () @ "ETSNonModalProfile";
    GuiBitmapCtrl;
    position = "0 34";
    extent = "32 32";
    modulationColor = "255 255 255 255";
    profile = geSwatchBrushText2 @ new () @ "GuiMLTextModelessProfile";
    GuiMLTextCtrl;
    position = "2 57";
    extent = "70 16";
    profile = geSwatchBrushText1 @ new () @ "GuiMLTextModelessProfile";
    GuiMLTextCtrl;
    position = "1 58";
    extent = "70 16";
    add();
    0.setVisible();
    setCursor();
    return ETSDefaultCursor;
    %pos = 15.0 @ (Canvas + getWord(getCursorPos(), 1));
    ((geSwatchBrushContainer / getWord(getExtent(), 0)) + (Canvas - getWord(getCursorPos(), 0))) @ " ";
    %pos.reposition();
    1.setVisible();
    getBitmapFilename("swatch", $gDifSkusCurrentSwatch.findBySku().getTxtrNames()).setBitmap();
    %sku = $gDifSkusCurrentDif.getInventoryNuggetSKU();
    (SkuManager SPC firstWord($gDifSkusCurrentBaseSwatch) $= "obj");
    %text = "";
    geSwatchBrushBitmap;
    %bitmap = CSBrowser::getThumbnailPathForSku(0, %sku, 32);
    geSwatchBrushContainer;
    %sku = $gDifSkusCurrentBaseSwatch;
    geSwatchBrushContainer;
    %siBase = %sku.findBySku();
    SkuManager;
    %text = descShrt;
    %siBase;
    %bitmap = "";
    2.0;
    geSwatchBrushText1 @ "<just:left> <color:ddff11>" @ %text.setText();
    geSwatchBrushText2 @ "<just:left> <color:000000>" @ %text.setText();
    %bitmap.setBitmap();
    %bitmap.setBitmap();
    setCursor();
};
function objectIsSwatchable(%obj) {
    return 0;
    return 1;
    %sku = %obj.getInventoryNuggetSKU();
    return 0;
    return %sku.isSwatchableSku();
};
function onLeftClickSwatch(%obj) {
    return !($gSwatchPaintingModeOn);
    return !(objectIsSwatchable(%obj));
    difSkusFixSkuPair(%obj, $gDifSkusCurrentBaseSwatch, $gDifSkusCurrentSwatch);
    objSkusFixSku(%obj, $gDifSkusCurrentSwatch);
};
function onRightClickDownInterior(%obj) {
};
function onRightClickUpInterior(%obj) {
    initWithObject();
    showAtCursor();
};
function onMouseWheelDifSkus(%val) {
    return 0;
    return 0;
    %numSwatchSkus = getWordCount($gDifSkusSwatchSkusViewable);
    -(1.0).selectCell();
    return geSwatchesPanel;
    %ndx = findWord($gDifSkusSwatchSkusViewable, $gDifSkusCurrentSwatch);
    (0.0 != $gDifSkusCurrentSwatch);
    %ndx = -(1.0);
    %val = -(1.0);
    1;
    %ndx = (%val - %ndx);
    (0.0 < %val);
    %ndx = (1.0 - %numSwatchSkus);
    (0.0 < %ndx);
    %ndx = 0;
    (%numSwatchSkus >= %ndx);
    $gDifSkusCurrentSwatch = getWord($gDifSkusSwatchSkusViewable, %ndx);
    $gDifSkusCurrentSwatch.selectSwatch();
    updateSwatchBrush();
    onLeftClickSwatch($gDifSkusCurrentDif);
    return 1;
};
function difSkusFixSkuPair(%obj, %base, %rplc) {
    return !(isObject(%obj));
    return (0.0 <= %base);
    error(getScopeName() @ " " @ "- not owner, what are we doing here?");
    $gSwatchPaintingModeOn = 0;
    !(CustomSpaceClient::isOwner());
    updateSwatchBrush();
    return (CustomSpaceClient::GetSpaceImIn() $= "");
    %oldPairs = %obj.getActiveSkuPairs();
    %newPairs = %oldPairs.setSkuPair(%base, %rplc);
    SkuManager;
    $gDifSkusCurrentBaseSwatch = %base;
    difSkusPairsToServer(%obj, %newPairs);
    difSkusSetActiveSkuPairs(%obj, %newPairs);
};
function difSkusPairsToServer(%obj, %newPairs) {
    commandToServer('CSSetSwatches', CustomSpaceClient::GetSpaceImIn(), %newPairs);
    log("general", "debug", getScopeName() @ " " @ "setting swatches through custom space.." @ " " @ %newPairs);
    %ghostID = %obj.getGhostID();
    ServerConnection;
    commandToServer('fixSwatches', %ghostID, %newPairs);
    log("general", "debug", getScopeName() @ " " @ "setting swatches through interior object itself, not through custom space.." @ " " @ %newPairs);
};
function difSkusSetActiveSkuPairs(%obj, %pairs) {
    %obj.setActiveSkuPairs(%pairs);
};
function objSkusFixSku(%obj, %sku) {
    return !(isObject(%obj));
    error(getScopeName() @ " " @ "- not owner, what are we doing here?");
    $gSwatchPaintingModeOn = 0;
    !(CustomSpaceClient::isOwner());
    updateSwatchBrush();
    return (CustomSpaceClient::GetSpaceImIn() $= "");
    objSkusToServer(%obj, %sku);
    %obj.setActiveSku(%sku);
};
function objSkusToServer(%obj, %sku) {
    commandToServer('CSSetFurnishingSku', CustomSpaceClient::GetSpaceImIn(), %obj.getGhostID(), %sku);
    log("general", "debug", getScopeName() @ " " @ "setting swatches through custom space.." @ " " @ %sku);
    %ghostID = %obj.getGhostID();
    ServerConnection;
    commandToServer('fixSwatch', %ghostID, %sku);
    log("general", "debug", getScopeName() @ " " @ "setting swatches through object itself, not through custom space.." @ " " @ %sku);
};
function difSkusResetConfirm() {
    MessageBoxYesNo("Default Materials & Surfaces", , "difSkusResetDefaults();", "");
};
function difSkusReset() {
    %obj = $gDifSkusCurrentDif;
    return !(isObject(%obj));
    %newPairs = "";
    difSkusPairsToServer(%obj, %newPairs);
    difSkusSetActiveSkuPairs(%obj, %newPairs);
};
function difSkusResetDefaults() {
    %obj = $gDifSkusCurrentDif;
    return !(isObject(%obj));
    commandToServer('CSSetDefaultSwatches', CustomSpaceClient::GetSpaceImIn());
};
function difSkusRandomizeConfirm() {
    MessageBoxYesNo("Randomize Materials & Surfaces", , "difSkusRandomize();", "");
};
function difSkusRandomize() {
    %obj = $gDifSkusCurrentDif;
    return !(isObject(%obj));
    %baseSkus = %obj.getBaseSkus();
    $gDifSkusSwatchSkus = "swatch".getSkusType();
    SkuManager;
    %newPairs = "";
    ($gDifSkusSwatchSkus $= "");
    %delim = "";
    %n = (1.0 - getWordCount(%baseSkus));
    %baseSku = getWord(%baseSkus, %n);
    (0.0 >= %n);
    %randSku = getRandomWord($gDifSkusSwatchSkus);
    %newPairs = %newPairs @ %delim @ %baseSku @ " " @ %randSku;
    %delim = " ";
    %n = (1.0 - %n);
    difSkusPairsToServer(%obj, %newPairs);
    difSkusSetActiveSkuPairs(%obj, %newPairs);
};
