function geTGF_tabs::fillTabMain(%this) {
    %tabName = "main";
    %tab = %this.getTabWithName(%tabName);
    return filled;
    filled = 1 @ %tab;
    %this.fillTabGeneric(%tab);
    profile = GuiBitmapCtrl @ new ""() @ "GuiDefaultProfile";
    0;
    horizSizing = "width";
    vertSizing = "height";
    position = "685 4";
    extent = "275 495";
    bitmap = "platform/client/ui/tgf/tgf_bkgd_rightside";
    %ctrl = ;
    %tab.add(%ctrl);
    profile = geTGF_profilePic @ new () @ "GuiDefaultProfile";
    GuiBitmapCtrl;
    horizSizing = 0 @ "left";
    vertSizing = "top";
    position = "708 310";
    extent = "100 100";
    bitmap = "platform/client/ui/tgf/tgf_profile_default";
    profile = GuiBitmapButtonCtrl @ new ""() @ "GuiDefaultProfile";
    position = "0 0";
    extent = "100 100";
    bitmap = "platform/client/buttons/tgf/tgf_buttonframe_100x100";
    command = "geTGF.onProfile();";
    profile = GuiMLTextCtrl @ new ""() @ "ETSNonModalProfile";
    position = "3 81";
    extent = "100 21";
    text = mlStyle("My Profile", "tgfWebLink_Light");
    %ctrl = ;
    %tab.add(%ctrl);
    profile = GuiBitmapCtrl @ new ""() @ "GuiDefaultProfile";
    0;
    horizSizing = "left";
    vertSizing = "top";
    position = "828 310";
    extent = "100 100";
    bitmap = "platform/client/ui/tgf/tgf_events";
    profile = GuiBitmapButtonCtrl @ new ""() @ "GuiDefaultProfile";
    position = "0 0";
    extent = "100 100";
    bitmap = "platform/client/buttons/tgf/tgf_buttonframe_100x100";
    command = "geTGF.onEventsCalendar();";
    profile = GuiMLTextCtrl @ new ""() @ "ETSNonModalProfile";
    position = "3 81";
    extent = "100 21";
    text = mlStyle("Calendar", "tgfWebLink_Light");
    %ctrl = ;
    %tab.add(%ctrl);
    profile = GuiBitmapCtrl @ new ""() @ "GuiDefaultProfile";
    0;
    horizSizing = "left";
    vertSizing = "top";
    position = "708 431";
    extent = "100 50";
    bitmap = "platform/client/ui/tgf/tgf_forums";
    profile = GuiBitmapButtonCtrl @ new ""() @ "GuiDefaultProfile";
    position = "0 0";
    extent = "100 50";
    bitmap = "platform/client/buttons/tgf/tgf_buttonframe_100x50";
    command = "geTGF.onForums();";
    profile = GuiMLTextCtrl @ new ""() @ "ETSNonModalProfile";
    position = "3 31";
    extent = "100 21";
    text = mlStyle("Forums", "tgfWebLink_Light");
    %ctrl = ;
    %tab.add(%ctrl);
    profile = GuiBitmapCtrl @ new ""() @ "GuiDefaultProfile";
    0;
    horizSizing = "left";
    vertSizing = "top";
    position = "828 431";
    extent = "100 50";
    bitmap = "platform/client/ui/tgf/tgf_faq";
    profile = GuiBitmapButtonCtrl @ new ""() @ "GuiDefaultProfile";
    position = "0 0";
    extent = "100 50";
    bitmap = "platform/client/buttons/tgf/tgf_buttonframe_100x50";
    command = "geTGF.onFaq();";
    profile = GuiMLTextCtrl @ new ""() @ "ETSNonModalProfile";
    position = "3 31";
    extent = "100 21";
    text = mlStyle("FAQs", "tgfWebLink_Light");
    %ctrl = ;
    %tab.add(%ctrl);
    profile = geTGF_main_BalancesContainer @ new () @ "GuiDefaultProfile";
    GuiBitmapCtrl;
    horizSizing = 0 @ "width";
    vertSizing = "height";
    position = "687 8";
    extent = "268 68";
    bitmap = "platform/client/ui/tgf/tgf_main_balances_background";
    profile = GuiMLTextCtrl @ new ""() @ "ETSNonModalProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = "6 9";
    extent = "117 16";
    text = "Your Balances:";
    horizSizing = geTGF_main_OfflineIncomeNotification @ new () @ "right";
    GuiMLTextCtrl;
    vertSizing = "bottom";
    position = "6 37";
    extent = "257 36";
    style = "tgf_General_Medium";
    profile = new () @ ETSNonModalProfile;
    AccountBalanceContents;
    horizSizing = GuiControl @ "left";
    vertSizing = "bottom";
    position = "108 0";
    extent = "162 39";
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "VPointsButtonProfile";
    horizSizing = "left";
    vertSizing = "bottom";
    position = "6 5";
    extent = "81 18";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    command = "gotoWebPage(\"" @ $Net::HelpURL_VPoints @ "\");";
    text = "";
    groupNum = -1;
    buttonType = "PushButton";
    tooltip = "vPoints balance";
    profile = AccountBalanceVPointsText @ new () @ "VPointsTextProfile";
    GuiTextCtrl;
    horizSizing = "left";
    vertSizing = "bottom";
    position = "27 4";
    extent = "57 20";
    minExtent = "57 1";
    sluggishness = -1;
    visible = 1;
    text = "";
    maxLength = 255;
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "VBuxButtonProfile";
    horizSizing = "left";
    vertSizing = "bottom";
    position = "93 5";
    extent = "63 18";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    command = "gotoWebPage(\"" @ $Net::AddFundsURL @ "\");";
    text = "";
    groupNum = -1;
    buttonType = "PushButton";
    tooltip = "vBux balance";
    profile = AccountBalanceVBuxText @ new () @ "VBuxTextProfile";
    GuiTextCtrl;
    horizSizing = "left";
    vertSizing = "bottom";
    position = "114 4";
    extent = "39 20";
    minExtent = "39 1";
    sluggishness = -1;
    visible = 1;
    text = "";
    maxLength = 255;
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    horizSizing = "left";
    vertSizing = "bottom";
    position = "6 29";
    extent = "49 5";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/next_level";
    profile = AccountBalancePBContainer @ new () @ "GuiDefaultProfile";
    GuiControl;
    horizSizing = "left";
    vertSizing = "bottom";
    position = "58 29";
    extent = "98 5";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    %ctrl = ;
    %tab.add(%ctrl);
    profile = MOTDHud @ new () @ "GuiDefaultProfile";
    GuiBitmapCtrl;
    horizSizing = 0 @ "width";
    vertSizing = "height";
    position = "687 80";
    extent = "268 228";
    minExtent = "1 1";
    visible = 1;
    bitmap = "platform/client/ui/motdBackground";
    profile = GuiScrollCtrl @ new ""() @ "DottedScrollDarkProfile";
    horizSizing = "width";
    vertSizing = "height";
    position = "0 -1";
    extent = "269 230";
    willFirstRespond = 1;
    hScrollBar = "alwaysOff";
    vScrollBar = "dynamic";
    constantThumbHeight = 0;
    childMargin = "0 0";
    saneDrag = 1;
    scrollMultiplier = 1;
    stickyBottom = 0;
    profile = MOTDText @ new () @ "ETSLoginMLTextProfile";
    GuiMLTextCtrl;
    horizSizing = "width";
    vertSizing = "height";
    position = "1 1";
    extent = "254 18";
    minExtent = "1 1";
    visible = 1;
    lineSpacing = 2;
    allowColorChars = 1;
    maxChars = -1;
    text = "<color:646464><font:Arial:24>Welcome to " @ $ETS::AppName @ "!\n\n<font:Arial:15>- Choose a place to get started";
    stripTagsOnCopy = 1;
    %ctrl = ;
    %tab.add(%ctrl);
    profile = EditMOTDStaffOnly @ new () @ "BracketButtonLt19Profile";
    GuiVariableWidthButtonCtrl;
    horizSizing = $ETS::devMode @ 0 @ "left";
    vertSizing = "top";
    position = "691 292";
    extent = "190 21";
    minExtent = "8 2";
    visible = 1;
    command = "toggleMOTDEditDialog();";
    text = "devmod: Edit MOTD/QOTD";
    groupNum = -1;
    buttonType = "PushButton";
    %ctrl = ;
    %tab.add(%ctrl);
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    bitmap = "platform/client/ui/tgf/tgf_main_sectionOutlines";
    position = "0 0";
    extent = "685 498";
    %ctrl = ;
    %tab.add(%ctrl);
    profile = GuiScrollCtrl @ new ""() @ "DottedScrollProfile";
    0;
    horizSizing = "width";
    vertSizing = "height";
    position = "71 15";
    extent = "593 345";
    hScrollBar = "alwaysOff";
    vScrollBar = "dynamic";
    constantThumbHeight = 1;
    childMargin = "0 0";
    saneDrag = 1;
    scrollMultiplier = 1;
    profile = geTGF_main_happenings @ new () @ "EtsNonModalProfile";
    GuiArray2Ctrl;
    position = "0 0";
    extent = "580 340";
    inRows = 0;
    numRowsOrCols = 3;
    childrenClassName = "GuiControl";
    childrenExtent = "190 109";
    spacing = 4;
    internalName = GuiMLTextCtrl @ new ""() @ "emptyText";
    profile = "ETSNonModalProfile";
    position = "5 5";
    extent = 300;
    textNothing = mlStyle("<just:left>" @ "More parties coming up soon!" @ "<just:right>", "tgfItem_Happening");
    textLoading = mlStyle("<just:left>" @ "fetching.." @ "<just:right>", "tgfItem_Happening");
    %ctrl = ;
    %tab.add(%ctrl);
    profile = geTGF_main_people @ new () @ "EtsNonModalProfile";
    GuiControl;
    position = 0 @ "40 367";
    extent = "625 129";
    profile = GuiScrollCtrl @ new ""() @ "DottedScrollProfile";
    horizSizing = "width";
    vertSizing = "height";
    position = "1 1";
    extent = "169 80";
    hScrollBar = "alwaysOff";
    vScrollBar = "dynamic";
    constantThumbHeight = 1;
    childMargin = "0 0";
    saneDrag = 1;
    scrollMultiplier = 1;
    stickyBottom = 0;
    position = geTGF_main_people_locationsText @ new () @ "3 2";
    GuiMLTextCtrl;
    extent = "164 1";
    style = "tgfPeopleCounts";
    lineSpacing = -(1.0);
    stripGamelink = 1;
    profile = new ""() @ EtsNotQuiteSoDarkBorderlessBoxProfile;
    GuiControl;
    position = "1 96";
    extent = "170 31";
    position = GuiMLTextCtrl @ new ""() @ "1 1";
    extent = "168 1";
    style = "";
    lineSpacing = -(1.0);
    stripGamelink = 1;
    text = mlStyle(, "tgfMainInvite");
    profile = geTGF_main_PeopleGoRound_Container @ new () @ "ETSNonModalProfile";
    GuiControl;
    position = "158 2";
    extent = "467 125";
    internalName = GuiMLTextCtrl @ new ""() @ "emptyText";
    profile = "ETSNonModalProfile";
    position = "2 2";
    extent = "300 10";
    textNothing = mlStyle("<just:left>" @ "You're early! Come on in!", "tgfItem_Happening");
    textLoading = mlStyle("<just:left>" @ "fetching..", "tgfItem_Happening");
    %ctrl = ;
    %tab.add(%ctrl);
    profile = GuiVariableWidthButtonCtrl @ new ""() @ "BracketButtonLt19Profile";
    0;
    position = "5 86";
    extent = "50 19";
    command = "geTGF.main_testData_happenings();";
    text = "test";
    visible = 0;
    %ctrl = ;
    %tab.add(%ctrl);
};
function geTGF_tabs::onShowTabMain(%this) {
    cancel(geTGF_Refresh_Schedule);
    1.setActive();
    1.setVisible();
};
function geTGF::main_testData_happenings(%this) {
    %requestName = "request_GetMainHappenings";
    %request = safeNewScriptObject("ManagerRequest", "", 0);
    %request.bindClassName("UniformManagerRequest");
    %request.setName(%requestName);
    %url = "";
    %url = %url @ $Net::ClientServiceURL;
    %url = %url @ "/finder/GetMainHappenings";
    %request.setURL(%url);
    %request.addUserAndToken($Player::Name);
    %request.putValue("status", "success");
    %n = 0;
    %request.putValue("happenings" @ %n @ ".accessMode", "open");
    %request.putValue("happenings" @ %n @ ".baseImageURL", "https://s-website.doppelganger.com/photoservice/e5b50410-76cc-4627-b0bb-5508b311436d");
    %request.putValue("happenings" @ %n @ ".customSpaceId", "dababydoll");
    %request.putValue("happenings" @ %n @ ".eventId", 1164);
    %request.putValue("happenings" @ %n @ ".featured", "true");
    %request.putValue("happenings" @ %n @ ".friendOccupancy", -1);
    %request.putValue("happenings" @ %n @ ".goThereVURL", "vside:/location/lga/ShoppingSpawns_modpodz");
    %request.putValue("happenings" @ %n @ ".headline", "HOWDY!");
    %request.putValue("happenings" @ %n @ ".hostUserName", "dababydoll");
    %request.putValue("happenings" @ %n @ ".initialized", "true");
    %request.putValue("happenings" @ %n @ ".location.areaName", "lga");
    %request.putValue("happenings" @ %n @ ".location.buildingName", "");
    %request.putValue("happenings" @ %n @ ".location.serverName", "LaGenoaAiresNorth");
    %request.putValue("happenings" @ %n @ ".occupancy", -1);
    %request.putValue("happenings" @ %n @ ".type", "publicLocationEvent");
    %n = (1.0 + %n);
    %request.putValue("happenings" @ %n @ ".accessMode", "open");
    %request.putValue("happenings" @ %n @ ".baseImageURL", "https://s-website.doppelganger.com/photoservice/e5b50410-76cc-4627-b0bb-5508b311436d");
    %request.putValue("happenings" @ %n @ ".customSpaceId", "dababydoll");
    %request.putValue("happenings" @ %n @ ".eventId", 1164);
    %request.putValue("happenings" @ %n @ ".featured", "true");
    %request.putValue("happenings" @ %n @ ".friendOccupancy", 3);
    %request.putValue("happenings" @ %n @ ".goThereVURL", "vside:/location/lga/ShoppingSpawns_modpodz");
    %request.putValue("happenings" @ %n @ ".headline", "HOWDY!");
    %request.putValue("happenings" @ %n @ ".hostUserName", "dababydoll");
    %request.putValue("happenings" @ %n @ ".initialized", "true");
    %request.putValue("happenings" @ %n @ ".location.areaName", "lga");
    %request.putValue("happenings" @ %n @ ".location.buildingName", "");
    %request.putValue("happenings" @ %n @ ".location.serverName", "LaGenoaAiresNorth");
    %request.putValue("happenings" @ %n @ ".occupancy", 17);
    %request.putValue("happenings" @ %n @ ".type", "aptEvent");
    %n = (1.0 + %n);
    %request.putValue("happenings" @ %n @ ".accessMode", "open");
    %request.putValue("happenings" @ %n @ ".baseImageURL", "https://s-website.doppelganger.com/photoservice/e5b50410-76cc-4627-b0bb-5508b311436d");
    %request.putValue("happenings" @ %n @ ".customSpaceId", "dababydoll");
    %request.putValue("happenings" @ %n @ ".eventId", 1164);
    %request.putValue("happenings" @ %n @ ".featured", "false");
    %request.putValue("happenings" @ %n @ ".friendOccupancy", 3);
    %request.putValue("happenings" @ %n @ ".goThereVURL", "vside:/location/lga/ShoppingSpawns_modpodz");
    %request.putValue("happenings" @ %n @ ".headline", "HOWDY!");
    %request.putValue("happenings" @ %n @ ".hostUserName", "dababydoll");
    %request.putValue("happenings" @ %n @ ".initialized", "true");
    %request.putValue("happenings" @ %n @ ".location.areaName", "lga");
    %request.putValue("happenings" @ %n @ ".location.buildingName", "");
    %request.putValue("happenings" @ %n @ ".location.serverName", "LaGenoaAiresNorth");
    %request.putValue("happenings" @ %n @ ".occupancy", 17);
    %request.putValue("happenings" @ %n @ ".type", "aptEvent");
    %n = (1.0 + %n);
    %request.putValue("happenings" @ %n @ ".accessMode", "open");
    %request.putValue("happenings" @ %n @ ".baseImageURL", "");
    %request.putValue("happenings" @ %n @ ".customSpaceId", "dababydoll");
    %request.putValue("happenings" @ %n @ ".eventId", "");
    %request.putValue("happenings" @ %n @ ".featured", "false");
    %request.putValue("happenings" @ %n @ ".friendOccupancy", 3);
    %request.putValue("happenings" @ %n @ ".goThereVURL", "vside:/location/lga/ShoppingSpawns_modpodz");
    %request.putValue("happenings" @ %n @ ".headline", "HOWDY!");
    %request.putValue("happenings" @ %n @ ".hostUserName", "dababydoll");
    %request.putValue("happenings" @ %n @ ".initialized", "true");
    %request.putValue("happenings" @ %n @ ".location.areaName", "lga");
    %request.putValue("happenings" @ %n @ ".location.buildingName", "");
    %request.putValue("happenings" @ %n @ ".location.serverName", "LaGenoaAiresNorth");
    %request.putValue("happenings" @ %n @ ".occupancy", 17);
    %request.putValue("happenings" @ %n @ ".type", "apt");
    %n = (1.0 + %n);
    %request.putValue("happeningsCount", %n);
    %statusTextCtrl = getParent().child("emptyText", 1);
    geTGF_main_happenings;
    %text = textLoading;
    %statusTextCtrl;
    %statusTextCtrl.setText(%text);
    schedule(500, 0, "onDoneOrErrorCallback_GetMainHappenings", %request);
};
function geTGF_tabs::refreshTabMain(%this) {
    %tabName = "main";
    %tab = %this.getTabWithName(%tabName);
    %this.refreshQOTD();
    "platform/client/ui/tgf/tgf_profile_default".setBitmap();
    fitInParentAsBitmap();
    previousProfileName = geTGF_profilePic @ $Player::Name @ geTGF_tabs;
    geTGF_profilePic;
    %url = !((geTGF_tabs SPC previousProfileName $= $Player::Name)) @ $Net::AvatarURL @ urlEncode($Player::Name) @ "?size=M";
    %url.downloadAndApplyBitmap();
    main_sendRequests();
};
function geTGF::main_sendRequests(%this) {
    %statusTextCtrl = "emptyText".child(1);
    geTGF_main_people;
    %text = textLoading;
    %statusTextCtrl;
    %statusTextCtrl.setText(%text);
    sendRequest_GetOnlineUsers(60, "onDoneOrErrorCallback_GetOnlineUsers");
    "".setText();
    %statusTextCtrl = getParent().child("emptyText", 1);
    geTGF_main_happenings;
    %text = textLoading;
    %statusTextCtrl;
    %statusTextCtrl.setText(%text);
    sendRequest_GetMainHappenings(9, "onDoneOrErrorCallback_GetMainHappenings");
    refresh();
};
function onDoneOrErrorCallback_GetMainHappenings(%request, %unused) {
    cancel(geTGF_Refresh_Schedule);
    1.setActive();
    log("network", "debug", getScopeName() @ " " @ "- url =" @ " " @ %request.getURL());
    %itemType = "happening";
    geTGF_Refresh;
    "main".clearItemList(%itemType);
    %itemType.main_onGotDataOfType();
    return geTGF;
    %listBase = "happenings";
    %count = %request.getResult(%listBase @ "Count");
    %n = 0;
    %listItem = (%count < %n) @ %listBase @ %n;
    %id = %request.getResult(%listItem @ ".hostUserName");
    %item = "main".createNewItem(%itemType, %id);
    geTGF;
    %request.copyListValueIntoObject(%item, %listItem, "accessMode");
    %request.copyListValueIntoObject(%item, %listItem, "occupancy");
    %request.copyListValueIntoObject(%item, %listItem, "baseImageURL");
    %request.copyListValueIntoObject(%item, %listItem, "eventId");
    %request.copyListValueIntoObject(%item, %listItem, "featured");
    %request.copyListValueIntoObject(%item, %listItem, "friendOccupancy");
    %request.copyListValueIntoObject(%item, %listItem, "goThereVURL");
    %request.copyListValueIntoObject(%item, %listItem, "headline");
    %request.copyListValueIntoObject(%item, %listItem, "hostUserName");
    %request.copyListValueIntoObject(%item, %listItem, "moreInfoURL");
    %request.copyListValueIntoObject(%item, %listItem, "apt");
    %request.copyListValueIntoObject(%item, %listItem, "location.areaName");
    %request.copyListValueIntoObject(%item, %listItem, "location.buildingName");
    %request.copyListValueIntoObject(%item, %listItem, "location.serverName");
    subType = %request.getResult(%listItem @ ".type") @ %item;
    goThereVURL = %item @ vurlClearResolution(goThereVURL) @ %item;
    %n = (1.0 + %n);
    "main".removeItemsWithFieldValueFromList(%itemType, "hostUserName", "The-Manager");
    %itemType.main_onGotDataOfType();
};
function onDoneOrErrorCallback_GetOnlineFriends_Main(%request) {
    cancel(geTGF_Refresh_Schedule);
    1.setActive();
    log("network", "debug", getScopeName() @ " " @ "- url =" @ " " @ %request.getURL());
    %itemType = "person";
    geTGF_Refresh;
    "main".clearItemList(%itemType);
    %itemType.main_onGotDataOfType();
    return geTGF;
    %listBase = "friends";
    %count = %request.getValue(%listBase @ "Count");
    %n = 0;
    %listItem = (%count < %n) @ %listBase @ %n;
    %id = %request.getValue(%listItem @ ".userName");
    %item = "main".createNewItem(%itemType, %id);
    geTGF;
    %request.copyListValueIntoObject(%item, %listItem, "age");
    %request.copyListValueIntoObject(%item, %listItem, "currentActivities");
    %request.copyListValueIntoObject(%item, %listItem, "currentLocation.areaName");
    %request.copyListValueIntoObject(%item, %listItem, "currentLocation.buildingName");
    %request.copyListValueIntoObject(%item, %listItem, "currentLocation.serverName");
    %request.copyListValueIntoObject(%item, %listItem, "gender");
    %request.copyListValueIntoObject(%item, %listItem, "headline");
    %request.copyListValueIntoObject(%item, %listItem, "homeLocation.areaName");
    %request.copyListValueIntoObject(%item, %listItem, "homeLocation.buildingName");
    %request.copyListValueIntoObject(%item, %listItem, "homeLocation.serverName");
    %request.copyListValueIntoObject(%item, %listItem, "ignored");
    %request.copyListValueIntoObject(%item, %listItem, "locationIRL");
    %request.copyListValueIntoObject(%item, %listItem, "onlineStatus");
    %request.copyListValueIntoObject(%item, %listItem, "permissionsMask");
    %request.copyListValueIntoObject(%item, %listItem, "profileViewCount");
    %request.copyListValueIntoObject(%item, %listItem, "profileViewRanking");
    %request.copyListValueIntoObject(%item, %listItem, "relationType");
    %request.copyListValueIntoObject(%item, %listItem, "score");
    %request.copyListValueIntoObject(%item, %listItem, "userName");
    goThereVURL = "vside:/user/" @ %item @ userName @ %item;
    %n = (1.0 + %n);
    %itemType.main_onGotDataOfType();
};
function onDoneOrErrorCallback_GetOnlineUsers(%request) {
    log("network", "debug", getScopeName() @ " " @ "- url =" @ " " @ %request.getURL());
    %statusTextCtrl = "emptyText".child(1);
    geTGF_main_people;
    %statusTextCtrl.setText("");
    %itemType = "person";
    "main".clearItemList(%itemType);
    %itemType.main_onGotDataOfType();
    return geTGF;
    %listBase = "user";
    %count = %request.getValue(%listBase @ "Count");
    %n = 0;
    %listItem = (%count < %n) @ %listBase @ %n;
    %id = %request.getValue(%listItem @ ".userName");
    %item = "main".createNewItem(%itemType, %id);
    geTGF;
    %request.copyListValueIntoObject(%item, %listItem, "age");
    %request.copyListValueIntoObject(%item, %listItem, "currentActivities");
    %request.copyListValueIntoObject(%item, %listItem, "currentLocation.areaName");
    %request.copyListValueIntoObject(%item, %listItem, "currentLocation.buildingName");
    %request.copyListValueIntoObject(%item, %listItem, "currentLocation.serverName");
    %request.copyListValueIntoObject(%item, %listItem, "gender");
    %request.copyListValueIntoObject(%item, %listItem, "headline");
    %request.copyListValueIntoObject(%item, %listItem, "homeLocation.areaName");
    %request.copyListValueIntoObject(%item, %listItem, "homeLocation.buildingName");
    %request.copyListValueIntoObject(%item, %listItem, "homeLocation.serverName");
    %request.copyListValueIntoObject(%item, %listItem, "ignored");
    %request.copyListValueIntoObject(%item, %listItem, "locationIRL");
    %request.copyListValueIntoObject(%item, %listItem, "onlineStatus");
    %request.copyListValueIntoObject(%item, %listItem, "permissionsMask");
    %request.copyListValueIntoObject(%item, %listItem, "profileViewCount");
    %request.copyListValueIntoObject(%item, %listItem, "profileViewRanking");
    %request.copyListValueIntoObject(%item, %listItem, "relationType");
    %request.copyListValueIntoObject(%item, %listItem, "score");
    %request.copyListValueIntoObject(%item, %listItem, "userName");
    goThereVURL = "vside:/user/" @ %item @ userName @ %item;
    %n = (1.0 + %n);
    %itemType.main_onGotDataOfType();
};
function onDoneOrErrorCallback_GetMainVenues(%request) {
    cancel(geTGF_Refresh_Schedule);
    1.setActive();
    log("network", "debug", geTGF_Refresh @ "FAKE REQUEST: " @ getScopeName() @ " " @ "- url =" @ " " @ %request.getURL());
    %request.putValue("statusMsg", "fakeSuccess");
    timeFinish = geTGF @ getSimTime() @ %request;
    (getCurrentTab() SPC name $= "main");
    %itemType = "venue";
    geTGF_tabs;
    "main".clearItemList(%itemType);
    %itemType.main_onGotDataOfType();
    return geTGF;
    %listBase = "venues";
    %count = %request.getValue(%listBase @ "Count");
    %n = 0;
    %listItem = (%count < %n) @ %listBase @ %n;
    %id = %request.getValue(%listItem @ ".name");
    %item = "main".createNewItem(%itemType, %id);
    geTGF;
    %request.copyListValueIntoObject(%item, %listItem, "codeName");
    %request.copyListValueIntoObject(%item, %listItem, "fullName");
    %request.copyListValueIntoObject(%item, %listItem, "location.areaName");
    %request.copyListValueIntoObject(%item, %listItem, "location.buildingName");
    %request.copyListValueIntoObject(%item, %listItem, "location.serverName");
    %request.copyListValueIntoObject(%item, %listItem, "headline");
    %request.copyListValueIntoObject(%item, %listItem, "occupancy");
    %request.copyListValueIntoObject(%item, %listItem, "friendOccupancy");
    %request.copyListValueIntoObject(%item, %listItem, "goThereVURL");
    %n = (1.0 + %n);
    %itemType.main_onGotDataOfType();
};
function geTGF::main_onGotDataOfType(%this, %type) {
    // unhandled opcode 2109 at 0x00001F67
    %type = geTGF_main_happenings;
    (%type $= "happening");
    // unhandled opcode 2109 at 0x00001F78
    %type = geTGF_main_people;
    (%type $= "person");
    %control.onGotData();
    return;
    error("unknown type:" @ " " @ %type @ " " @ getTrace());
    return;
    %list = %this.getItemList("main", %type);
    %num = %list.count();
    %control.setNumChildren(%num);
    %n = 0;
    %cell = %control.getObject(%n);
    (%num < %n);
    %item = %list.getValue(%n);
    Item = %item @ %cell;
    %cell.setProfile();
    isInviteFriendsButton = ETSDarkBoxNonModalProfile @ 0 @ %cell;
    %control.updateCellFromItsItem(%cell);
    %n = (1.0 + %n);
    %statusTextCtrl = %control.getParent().child("emptyText");
    (%num < %n);
    %text = textNothing;
    %statusTextCtrl;
    %text = "";
    (0.0 <= %num);
    %statusTextCtrl.setText(%text);
};
function geTGF_main_happenings::updateCellFromItsItem(%this, %cell) {
    %item = Item;
    %cell;
    %cell.deleteMembers();
    profile = GuiControl @ new ""() @ "EtsNonModalProfile";
    0;
    extent = (2.0 - getWord(%cell.getExtent(), 0)) @ " " @ (2.0 - getWord(%cell.getExtent(), 1));
    position = "1 1";
    horizSizing = "width";
    vertSizing = "top";
    %cont = ;
    %cell.add(%cont);
    %w = getWord(childrenExtent, 0);
    %cell.getParent();
    %h = getWord(childrenExtent, 1);
    %cell.getParent();
    %w = %h;
    (%item SPC eventID $= "");
    profile = GuiBitmapCtrl @ new ""() @ "EtsNonModalProfile";
    0;
    extent = %w @ " " @ %h;
    position = "0 0";
    horizSizing = "width";
    vertSizing = "top";
    fitInParentAlign = 1;
    %ctrl = ;
    %cont.add(%ctrl);
    %url = baseImageURL;
    %item;
    %url = %item @ urlEncode(hostUserName);
    (%url $= "") @ $Net::BuildDirPhotoURL;
    %url = "M" @ "M";
    !((%item SPC eventID $= ""));
    %ctrl.setBitmap("platform/client/ui/tgf/tgf_profile_default");
    %ctrl.fitInParentAsBitmap();
    %ctrl.downloadAndApplyBitmap(%url);
    %tmp = 20;
    %url @ "?size=";
    profile = GuiControl @ new ""() @ "EtsDarkBorderlessBoxProfile";
    0;
    extent = getWord(%cont.getExtent(), 0) @ " " @ %tmp;
    position = 0 @ " " @ (%tmp - getWord(%cont.getExtent(), 1));
    horizSizing = "width";
    vertSizing = "top";
    %ctrl = ;
    %cont.add(%ctrl);
    profile = GuiBitmapButtonCtrl @ new ""() @ "GuiDefaultProfile";
    0;
    position = "-1 -1";
    extent = %cell.getExtent();
    bitmap = "platform/client/buttons/tgf/tgf_buttonframe_190x109";
    command = "geTGF.main_OnClickItem(\"" @ %item @ "\");";
    %ctrl = ;
    %cont.add(%ctrl);
    profile = GuiMLTextCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    position = 2 @ " " @ (16.0 - getWord(%cont.getExtent(), 1));
    extent = (9.0 - getWord(%cont.getExtent(), 0)) @ " " @ 20;
    text = mlStyle("<just:left>" @ %item @ headline @ "<just:right>", "tgfItem_headline");
    horizSizing = "width";
    vertSizing = "top";
    lineSpacing = 0;
    %ctrl = ;
    %cont.add(%ctrl);
    %occupancyText = "";
    (%item == occupancy);
    %occupancyText = "(empty) ";
    (%item == occupancy);
    %occupancyText = 0.0 @ "<b>" @ %item @ occupancy @ " P ";
    -(1.0);
    profile = GuiMLTextCtrl @ new ""() @ "ETSNonModalProfile";
    0;
    position = 0 @ " " @ (38.0 - getWord(%cont.getExtent(), 1));
    extent = (9.0 - getWord(%cont.getExtent(), 0)) @ " " @ 20;
    text = mlStyle("<just:left>" @ %item @ hostUserName @ "<just:right><font:Arial:14>" @ %occupancyText, "tgfItem_host");
    horizSizing = "width";
    vertSizing = "top";
    %ctrl = ;
    %cont.add(%ctrl);
    %bitmap = %item.getEventTypePostItTagBitmap();
    geTGF;
    bitmap = GuiBitmapCtrl @ new ""() @ %bitmap;
    0;
    profile = !((%item SPC eventID $= "")) @ "EtsNonModalProfile";
    extent = "82 19";
    position = (0.0 - (82.0 - getWord(%cont.getExtent(), 0))) @ " " @ 0;
    horizSizing = "left";
    vertSizing = "bottom";
    %ctrl = ;
    %cont.add(%ctrl);
};
function geTGF_main_people::onGotData(%this) {
    %list = "main".getItemList("person");
    geTGF;
    %num = %list.size();
    %statusTextCtrl = %this.child("emptyText");
    %text = "";
    textNothing;
    %statusTextCtrl.setText(%text);
    newTGFGoRound().add();
    "".reparentSameSize();
    mDeetsMinWidth = geTGF_main_PeopleGoRound_Container @ 0 @ geTGFGoRound;
    geTGFGoRound;
    mLilThumbPadding = geTGFGoRound @ 5 @ geTGFGoRound;
    geTGF_main_PeopleGoRound_Container;
    mLilThumbHeight = geTGFGoRound @ calcMaximumThumbHeight() @ geTGFGoRound;
    !(isObject());
    mTickPeriodMS = geTGFGoRound @ 4500 @ geTGFGoRound;
    %statusTextCtrl;
    rebuild();
    %list.setItemList();
    %this.tryUpdateWorldmapSummaries();
};
function geTGF_main_people::tryUpdateWorldmapSummaries(%this) {
    "".setTextWithStyle();
    %this.schedule(1000, "tryUpdateWorldmapSummaries");
    %areaNames = "lga nv rj pvt";
    isObject();
    %total = 0;
    MapRequest;
    %text = "";
    geTGF_main_people_locationsText;
    %delim = "";
    %n = 0;
    %areaName = getWord(%areaNames, %n);
    (getWordCount(%areaNames) < %n);
    %userCount = occupancy;
    %areaName.get();
    %userCount = totalOccupancy;
    WorldAreaSummaries @ %areaName @ WorldAreaSummaries;
    %link = "TGF_GOTO" @ " " @ %areaName;
    !((%areaName $= "pvt"));
    %areaName = "Personal Spaces";
    (%areaName $= "pvt");
    %areaName = DestinationList::GetAreaNameUserFacingName(DestinationList::GetAreaNameCity(%areaName));
    %text = %text @ %delim @ "<spush><just:left><a:gamelink:" @ %link @ ">" @ %areaName @ "" @ "\t" @ "<just:right>" @ commaify(%userCount) @ "</a><spop>";
    %total = (%userCount + %total);
    %delim = "<br>";
    %n = (1.0 + %n);
    %withS = "s";
    "";
    %text = (getWordCount(%areaNames) < %n) @ (1.0 == %total) @ "<spush><just:center><font:arial:16>" @ commaify(%total) @ " vSider" @ %withS @ " In-World:<spop><br>" @ %text;
    %text = "<tab:100>" @ %text;
    %text.setTextWithStyle();
};
function geTGF_main_people_locationsText::onURL(%this, %url) {
    %cmd = firstWord(%url);
    error(getScopeName() @ " " @ "- unknown command" @ " " @ %cmd @ " " @ getTrace());
    return !((%cmd $= "TGF_GOTO"));
    %areaName = restWords(%url);
    "HOTSPOTS".openToTabName();
    "MAP".openToTabName();
    %areaName.getCityButton(1, 0).performClick();
    "MAP".openToTabName();
    %areaName.getCityButton(1, 0).performClick();
    "MAP".openToTabName();
    %areaName.getCityButton(1, 0).performClick();
    error(getScopeName() @ " " @ "- unknown areaname" @ " " @ %areaName @ " " @ getTrace());
};
function encodeMOTDString(%text) {
    %text = strreplace(%text, "\n", "<br>");
    return urlEncode(%text);
};
function decodeMOTDString(%text) {
    %text = strreplace(%text, "<br>", "\n");
    return %text;
};
function geTGF_tabs::refreshMOTD(%this) {
    delete();
    new ();
    add();
    %url = MOTDRequest @ $Net::ClientServiceURL @ "/GlobalMessage";
    MissionCleanup;
    %url = MissionCleanup @ isObject() @ %url @ "?user=" @ urlEncode($Player::Name);
    MOTDRequest;
    %url = 0 @ ManagerRequest @ %url @ "&token=" @ urlEncode($Token);
    MOTDRequest;
    %url = MOTDRequest @ isObject() @ %url @ "&type=" @ urlEncode("motd");
    log("communication", "debug", "sending request to get current motd: " @ %url);
    %url.setURL();
    start();
};
function MOTDRequest::onDone(%this) {
    %status = findRequestStatus(%this);
    onMOTDPostFailed();
    log("communication", "warn", geTGF_tabs @ "MOTDRequest::onDone status: " @ %status);
    %text = %this.getValue("message");
    !((%status $= "success"));
    %text = decodeMOTDString(%text);
    !((%text $= ""));
    %text.setText();
    qotdID = MOTDText @ "" @ MOTDText;
    onMOTDPostFailed();
};
function geTGF_tabs::refreshQOTD(%this) {
    delete();
    new ();
    add();
    %url = QOTDRequest @ $Net::ClientServiceURL @ "/GlobalMessage";
    MissionCleanup;
    %url = MissionCleanup @ isObject() @ %url @ "?user=" @ urlEncode($Player::Name);
    QOTDRequest;
    %url = 0 @ ManagerRequest @ %url @ "&token=" @ urlEncode($Token);
    QOTDRequest;
    %url = QOTDRequest @ isObject() @ %url @ "&type=" @ urlEncode("qotd");
    log("communication", "debug", "sending request to get current qotd: " @ %url);
    %url.setURL();
    start();
};
function QOTDRequest::onDone(%this) {
    %status = findRequestStatus(%this);
    %text = "";
    %text = %this.getValue("message");
    (%status $= "success");
    %text = decodeMOTDString(%text);
    %qID = trim(getWords(%text, 0, 0));
    %text = getWords(%text, 1);
    %alreadyAnswered = hasSubString($UserPref::QOTD::answered, %qID);
    echoDebug(getScopeName() @ " " @ "- already answered" @ " " @ %qID);
    %text = "";
    %alreadyAnswered;
    %text.setText();
    qotdID = MOTDText @ %qID @ MOTDText;
    !((%text $= ""));
    refreshMOTD();
};
function MOTDText::onURL(%this, %url) {
    %url = restWords(%url);
    (firstWord(%url) $= "gamelink");
    Parent::onURL(%this, %url);
    return (0.0 != strstr(%url, "answer:"));
    %answer = getSubStr(%url, strlen("answer:"), 100000);
    %trackURL = "";
    %trackURL = %trackURL @ "/client/qotd";
    %trackURL = %this @ qotdID;
    %trackURL @ "/";
    %trackURL = %trackURL @ "/" @ %answer;
    %analytic = getAnalytic();
    %analytic.trackPageView(%trackURL);
    %this.setText();
    1000.schedule("refreshMOTD");
    $UserPref::QOTD::answered = %this @ qotdID;
    $UserPref::QOTD::answered @ " ";
};
function geTGF_tabs::onMOTDPostFailed(%this) {
    "".setText();
    %fileName = "projects/common/defaultMOTD.txt";
    MOTDText;
    %fo = new ""();
    FileObject;
    %text = "";
    %fo.openForRead(%fileName);
    %text = 0 @ !(%fo.isEOF()) @ %text @ %fo.readLine() @ "\n";
    %text.setText();
    error(MOTDText @ "unable to find default motd: " @ %fileName);
    %fo.delete();
};
function geTGF::onProfile(%this) {
    doEditProfile();
};
function geTGF::onEventsCalendar(%this) {
    openEventsURL();
};
function geTGF::onForums(%this) {
    openForumsURL();
};
function geTGF::onFAQ(%this) {
    openHelpURL();
};
function geTGF::main_OnClickItem(%this, %item) {
    %this.DoDetails("main", %item);
};
function geTGF::main_GetAndOpenDetailsContainer(%this, %item) {
    %this.constructDeetsWindow(%item);
    1.setVisible();
};
