function TreeBrowserControl::newControl(%parent, %name) {
    return !(isObject(%parent));
    profile = GuiArray2Ctrl @ new ""() @ "GuiDefaultProfile";
    0;
    position = "0 0";
    extent = %parent.getExtent();
    childrenClassName = "GuiControl";
    childrenExtent = %parent.getExtent();
    spacing = 0;
    numRowsOrCols = 1;
    inRows = 1;
    sluggishness = 0.5;
    %ctrl = ;
    %ctrl.bindClassName("TreeBrowserControl");
    %ctrl.bindClassName(%name);
    %ctrl.setName(%name);
    %parent.add(%ctrl);
    Parent = %parent @ %ctrl;
    idCounter = 0 @ %ctrl;
    level = 0 @ %ctrl;
    numButtons = 0 @ %ctrl;
    buttonWidth = 20 @ %ctrl;
    buttonPadding = 1 @ %ctrl;
    title = "" @ %ctrl;
    menuProfile = "ETSMenuProfile" @ %ctrl;
    selectedProfile = "ETSSelectedMenuItemProfile" @ %ctrl;
    menuTextProfile = "ETSUnselectedMenuTextProfile" @ %ctrl;
    menuTextSelectedProfile = "ETSSelectedMenuTextProfile" @ %ctrl;
    adjustMenuCellHeight = 0 @ %ctrl;
    isExpanded = 0 @ %ctrl;
    expandDelta = "250 0" @ %ctrl;
    name = SimGroup @ new ""() @ "";
    0;
    root = %ctrl;
    nodeDictionary = safeNewScriptObject("StringMap", "", 0) @ %ctrl;
    root.add();
    Path = %ctrl @ "" @ %ctrl;
    RootGroup;
    %ctrl.goToPath("");
    return %ctrl;
};
function TreeBrowserControl::onResized(%this) {
    %curMenu = %this.getCurrentMenu();
    %hilitedIdx = -(1.0);
    %hilitedCell = %curMenu.getHilitedCell();
    isObject(%curMenu);
    %hilitedIdx = %curMenu.getObjectIndex(%hilitedCell);
    isObject(%hilitedCell);
    %parentExtent = %this.getParent().getTrgExtent();
    collapsedParentExtent = %this @ getWords(VectorSub(%parentExtent @ " " @ 0, expandDelta @ " " @ 0), 0, 1) @ %this;
    isExpanded;
    childrenExtent = %this @ %parentExtent @ %this;
    %this.setNumChildren(0);
    %this.goToCurrentPath();
    %curMenu = %this.getCurrentMenu();
    (0.0 >= %hilitedIdx);
    %curMenu.hiliteCell(%curMenu.getObject(%hilitedIdx));
};
function TreeBrowserControl::onCreatedChild(%this, %child, %x, %unused) {
    %leftPadding = (buttonPadding * (%this + buttonWidth));
    %this;
    %contentsExtentX = (getWord(collapsedParentExtent, 0) - getWord(%child.getExtent(), 0));
    %this;
    %contentsExtentY = getWord(%child.getExtent(), 1);
    getWord(collapsedParentExtent, 1);
    profile = GuiControl @ new ""() @ "FocusableDefaultProfile";
    0;
    horizSizing = isExpanded @ %this @ "width";
    %this;
    vertSizing = %this @ isExpanded @ "height";
    %leftPadding;
    position = %x @ "0 0";
    extent = %child.getExtent();
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    hiliteProxy = %this.getHiliteProxy();
    treeBrowser = %this;
    expandedPane = %child;
    %child.add(expandedPane);
    profile = GuiControl @ new ""() @ "FocusableDefaultProfile";
    0;
    horizSizing = %child @ "right";
    vertSizing = "bottom";
    position = %this @ buttonPadding @ (%this - (buttonWidth - %leftPadding)) @ " " @ 0;
    extent = %this @ buttonPadding @ (%this + (buttonWidth + %contentsExtentX)) @ " " @ %contentsExtentY;
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    hiliteProxy = %this.getHiliteProxy();
    treeBrowser = %this;
    contentPane = %child;
    contentPane.bindClassName("TreeBrowserContentPane");
    %child.add(contentPane);
    profile = GuiScrollCtrl @ new ""() @ "ETSScrollProfile";
    0;
    horizSizing = %child @ %child @ "right";
    vertSizing = "bottom";
    position = %leftPadding @ " " @ 0;
    extent = %contentsExtentX @ " " @ %contentsExtentY;
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    willFirstRespond = 1;
    hScrollBar = "alwaysOff";
    vScrollBar = "dynamic";
    constantThumbHeight = 1;
    childMargin = "0 0";
    scroll = %child;
    %menuCellSpacing = 2;
    %menuTrgCellHeight = 24;
    %numCanFit = mFloor(((%menuCellSpacing + %menuTrgCellHeight) / %contentsExtentY));
    adjustMenuCellHeight;
    %menuTrgCellHeight = (%menuCellSpacing - (%numCanFit / %contentsExtentY));
    %this;
    %d = (mFloor(%menuTrgCellHeight) - %menuTrgCellHeight);
    %menuTrgCellHeight = mCeil(%menuTrgCellHeight);
    (0.5 >= %d);
    %menuTrgCellHeight = mFloor(%menuTrgCellHeight);
    profile = new ""() @ %this @ menuProfile;
    GuiArray2Ctrl;
    childrenClassName = 0 @ "GuiMouseEventCtrl";
    childrenExtent = (6.0 - %contentsExtentX) @ " " @ %menuTrgCellHeight;
    spacing = %menuCellSpacing;
    numRowsOrCols = 1;
    inRows = 0;
    hiliteProxy = %this.getHiliteProxy();
    hilited = 0;
    unselectedProfile = "GuiDefaultProfile";
    selectedProfile = %this @ selectedProfile;
    menuTextProfile = %this @ menuTextProfile;
    menuTextSelectedProfile = %this @ menuTextSelectedProfile;
    treeBrowser = %this;
    menu = %child;
    menu.bindClassName("MenuControl");
    menu.bindClassName("TreeBrowserFrame");
    layer = %child @ menu;
    %child @ 0;
    scroll.add(menu);
    scroll = %child @ menu;
    %child @ scroll;
    %child.add(scroll);
};
function TreeBrowserControl::getHiliteProxy(%this) {
    return "";
};
function TreeBrowserControl::scrollToLevel(%this, %level) {
    level = %level @ %this;
    %this.setTrgPosition((getWord(childrenExtent, 0) * -(%level)), 0);
};
function TreeBrowserControl::goToCurrentPath(%this, %focus) {
    %focus = 1;
    !(isDefined("%focus"));
    %this.goToPath(Path, %focus);
};
function TreeBrowserControl::goToParentPath(%this) {
    %currentNodeName = name;
    %this.getNode(Path);
    %parentPath = getFields(Path, 0, (%this - getFieldCount(Path)));
    2.0;
    %this.goToPath(%parentPath);
    %menu = %this.getCurrentMenu();
    %this;
    %count = %menu.getCount();
    %this;
    %i = 0;
    %menuItem = %menu.getObject(%i);
    (%count < %i);
    %menu.hiliteCell(0, %i);
    %i = (1.0 + %i);
    (%menuItem SPC name $= %currentNodeName);
};
function TreeBrowserControl::getMenuText(%this, %text) {
    return %text;
};
function TreeBrowserControl::goToPath(%this, %path, %focus) {
    %focus = 1;
    !(isDefined("%focus"));
    %path = trim(%path);
    %node = %this.getNode(%path);
    return 0;
    %pathchanged = !((%this SPC Path $= %path));
    Path = %path @ %this;
    %oldLevel = level;
    %this;
    level = getFieldCount(%path) @ %this;
    %level = ;
    %this.setNumChildren((1.0 + %level));
    %this.scrollToLevel(%level);
    %leafNode = 0;
    (%level <= %this.getCount());
    %expanded = %this.isNodeExpanded(Path);
    %this;
    %oldChild = %this.getChild(%oldLevel, 0);
    (%oldLevel != %level);
    expandedPane.clear();
    %expandDelta = %this.getFieldValue("expandDelta");
    !(isExpanded);
    warn((%this SPC %expandDelta $= "") @ getScopeName() @ "->trying to expand view but no expandDelta is set. returning!");
    %this.expandView(%expandDelta);
    return %expanded;
    %this.collapseView();
    %this.focusCurrentFrame();
    return !(%expanded);
    %child = %this.getChild(%level, 0);
    %count = %node.getCount();
    contentPane.setVisible(1);
    scroll.setVisible(0);
    menu.setVisible(0);
    %leafNode = 1;
    %child;
    node = %child @ contentPane;
    %child @ %node;
    contentPane.clear();
    %this.fillLeafPane(contentPane);
    expandedPane.clear();
    expandedPane.setVisible(1);
    %this.fillExpandedContentPane(expandedPane);
    expandedPane.setVisible(0);
    contentPane.makeFirstResponder(1);
    contentPane.setVisible(0);
    scroll.setVisible(1);
    menu.setVisible(1);
    expandedPane.clear();
    expandedPane.setVisible(1);
    %this.fillExpandedFrame(expandedPane);
    expandedPane.setVisible(0);
    %currentCount = menu.getCount();
    %child;
    filterText = %this @ strlwr(filterText) @ %this;
    %child;
    filterText = %this @ trim(filterText) @ %this;
    %child;
    %count = 0;
    %child;
    %n = (1.0 - %node.getCount());
    %child;
    %subNode = %node.getObject(%n);
    (0.0 >= %n);
    passesFilter = %this @ %this.nodePassesFilter(%subNode, filterText) @ %subNode;
    isExpanded;
    %count = (1.0 + %count);
    passesFilter;
    %n = (1.0 - %n);
    %subNode;
    Path = (%count != %currentCount) @ "ForceUpdatePlease!!!" @ %child;
    (0.0 >= %n);
    menu.clear();
    deferReseat = %child @ menu;
    %child @ 1;
    %totalCount = %node.getCount();
    !((%child SPC Path $= %path));
    %n = 0;
    %this;
    %subNode = %node.getObject(%n);
    (%totalCount < %n);
    %menuItem = menu.addMenuItem(%this.getMenuText(name), %child @ %subNode @ %this.getId() @ ".select(\"" @ %subNode @ name @ "\");", "", "");
    passesFilter;
    name = %subNode @ name @ %menuItem;
    %subNode;
    %n = (1.0 + %n);
    %expanded;
    menu.reseatChildren();
    menu.hiliteCell(0, 0);
    menu.makeFirstResponder(1);
    Path = %child @ %path @ %child;
    %pathchanged;
    %numButtons = %level;
    (1.0 - %level);
    %offset = 0;
    %leafNode;
    %height = getWord(%this.getExtent(), 1);
    getWord(collapsedParentExtent, 1);
    %i = 0;
    %this;
    profile = GuiBitmapButtonCtrl @ new ""() @ "ETSVerticalButtonProfile";
    0;
    horizSizing = (%numButtons < %i) @ %i @ %this @ !(isObject(button)) @ "right";
    (mMax(%numButtons, numButtons) < %i);
    vertSizing = isExpanded @ %this @ "bottom";
    %this;
    position = %focus @ %this.isVisibleRecursive() @ %offset @ " " @ 0;
    %child;
    extent = %child @ %this @ buttonWidth @ " " @ %height;
    (%totalCount < %n);
    minExtent = %child @ %child @ "1 1";
    %child;
    sluggishness = %pathchanged @ %child @ -1;
    %this.isVisibleRecursive();
    visible = %child @ %focus @ 1;
    %child;
    command = %child @ %child @ "";
    isExpanded;
    text = %expanded @ %this @ "";
    %child;
    groupNum = %child @ %child @ -1;
    (0.0 == %count);
    buttonType = "PushButton";
    bitmap = "platform/client/buttons/vbutton";
    drawText = 1;
    textRotation = 90;
    button = %i @ %this;
    Parent.add(button);
    button.resize(buttonWidth, %height);
    %button = button;
    %this @ %i @ %this;
    %button.setVisible(1);
    command = %this @ %i @ %this @ %i @ %this SPC button.getExtent() @ !((%this $= buttonWidth @ " " @ %height)) @ %i @ %this @ %this.getId() @ ".goToPath(\"" @ %this @ getFields(Path, 0, %i) @ "\");" @ %button;
    text = %this @ getField(Path, %i) @ %button;
    %button.setActive(((1.0 - %level) < %i));
    button.setVisible(0);
    %offset = ((%this + buttonWidth) + %offset);
    buttonPadding;
    %i = (1.0 + %i);
    %this;
    numButtons = (mMax(%numButtons, numButtons) < %i) @ %numButtons @ %this;
    %this;
    return 1;
};
function TreeBrowserControl::nodePassesFilter(%this, %node, %filterText) {
    return 1;
    %searchText = %this.getNodeSearchText(%node);
    %ret = (0.0 >= strstr(%searchText, %filterText));
    return %ret;
};
function TreeBrowserControl::getNodeSearchText(%this, %node) {
    return searchText;
    %sku = sku;
    %node;
    %ret = searchText;
    %sku.findBySku();
    %ret = name;
    %node;
    %n = (1.0 - %node.getCount());
    SkuManager;
    %subNode = %node.getObject(%n);
    (0.0 >= %n);
    %subNodeSearchText = %this.getNodeSearchText(%subNode);
    !((%sku $= ""));
    %w = (1.0 - getWordCount(%subNodeSearchText));
    %word = getWord(%subNodeSearchText, %w);
    (0.0 >= %w);
    %ret = %ret @ " " @ %word;
    !(hasWord(%ret, %word));
    %w = (1.0 - %w);
    %n = (1.0 - %n);
    (0.0 >= %w);
    %ret = trim(%ret);
    (0.0 >= %n);
    searchText = %ret @ %node;
    return %ret;
};
function TreeBrowserControl::expandView(%this, %delta) {
    return isExpanded;
    isExpanded = 1 @ %this;
    %collapsedParentExtent = %this.getParent().getTrgExtent();
    %this.resizeParentsBy(%delta);
    %this.onResized();
    collapsedParentExtent = %collapsedParentExtent @ %this;
    %trg = %this.getTrgPosition();
    %this.reposition(getWord(%trg, 0), getWord(%trg, 1));
};
function TreeBrowserControl::resizeParentsBy(%this, %delta) {
    %extent = %this.getParent().getTrgExtent();
    %newExtent = VectorAdd(%extent @ " " @ 0, %delta @ " " @ 0);
    %newExtent = getWords(%newExtent, 0, 1);
    %this.getParent().resize(getWord(%newExtent, 0), getWord(%newExtent, 1));
};
function TreeBrowserControl::collapseView(%this) {
    return !(isExpanded);
    isExpanded = 0 @ %this;
    %delta = VectorSub(collapsedParentExtent @ " " @ 0, %this.getParent().getTrgExtent() @ " " @ 0);
    %this;
    %this.resizeParentsBy(getWords(%delta, 0, 1));
    %this.onResized();
    %trg = %this.getTrgPosition();
    %this.reposition(getWord(%trg, 0), getWord(%trg, 1));
};
function TreeBrowserControl::isNodeExpanded(%this, %path) {
    return 0;
};
function TreeBrowserControl::fillExpandedFrame(%this, %expandedFrame) {
    %frame = %expandedFrame.getParent();
    %rightEdgeOfMenu = (%frame + getWord(menu.getExtent(), 0));
    getWord(menu.getPosition(), 0);
    position = GuiMLTextCtrl @ new ""() @ %rightEdgeOfMenu @ " " @ 0;
    0;
    extent = %frame @ "50 18";
    text = "<color:ffffff>override me!";
    visible = 1;
    %expandedFrame.add();
};
function TreeBrowserControl::fillExpandedContentPane(%this, %expandedPane) {
    %frame = %expandedPane.getParent();
    %rightEdgeOfContentPane = (%frame + getWord(contentPane.getExtent(), 0));
    getWord(contentPane.getPosition(), 0);
    position = GuiMLTextCtrl @ new ""() @ %rightEdgeOfContentPane @ " " @ 0;
    0;
    extent = %frame @ "50 18";
    text = "<color:ffffff>override me!";
    visible = 1;
    %expandedPane.add();
};
function TreeBrowserControl::isInSubdirOfPath(%this, %path) {
    %depth = getFieldCount(%path);
    return (%this $= getFields(Path, %depth));
};
function TreeBrowserControl::fillLeafPane(%this, %pane) {
    %level = level;
    %this;
    profile = GuiTextCtrl @ new ""() @ "GuiTextProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "5 0";
    extent = getWord(%pane.getExtent(), 0) @ " " @ 18;
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    text = %this @ getField(Path, (1.0 - %level));
    maxLength = 255;
    %pane.add();
};
function TreeBrowserControl::select(%this, %value) {
    %this.goToPath(Path @ "\t" @ %value);
};
function TreeBrowserControl::selectNextLeaf(%this, %forward, %slide) {
    %path = %this.getNextLeaf(Path, %forward);
    %this;
    %level = getFieldCount(%path);
    isDefined("%slide");
    level = (%this != getFieldCount(Path)) @ %level @ %this;
    %level;
    %this.reposition((getWord(childrenExtent, 0) * -(%level)), 0);
    %this.goToPath(%path);
};
function TreeBrowserControl::getNextLeaf(%this, %path, %forward) {
    %node = %this.getNode(%path);
    return "";
    %foundChildBearingNode = 1;
    (0.0 > %node.getCount());
    %foundChildBearingNode = 0;
    %depth = getFieldCount(%path);
    !(%foundChildBearingNode);
    %name = getField(%path, (1.0 - %depth));
    return "";
    %ppath = getFields(%path, 0, (2.0 - %depth));
    %pnode = %this.getNode(%ppath);
    %childCount = %pnode.getCount();
    %nidx = -(1.0);
    %i = 0;
    %child = %pnode.getObject(%i);
    (%childCount < %i);
    %nidx = %i;
    (%child SPC name $= %name);
    %i = (1.0 + %i);
    error((0.0 < %nidx) @ getScopeName() @ "->nidx < 0.");
    return "";
    %tidx = (%forward + %nidx);
    %node = %pnode.getObject(%tidx);
    (%childCount < %tidx);
    %path = %node @ name;
    %ppath @ "\t";
    %foundChildBearingNode = 1;
    (0.0 > %node.getCount());
    return %path;
    %node = %pnode;
    %path = %ppath;
    %cnt = %node.getCount();
    %slot = (1.0 - %cnt);
    0;
    %node = %node.getObject(%slot);
    (0.0 > %forward);
    %path = %node @ name;
    %path @ "\t";
    %cnt = %node.getCount();
    return %path;
};
function TreeBrowserControl::addNode(%this, %path) {
    %this.addNodeAt("", %path);
};
function TreeBrowserControl::addNodeAt(%this, %prefix, %subpath) {
    %prefix = trim(%prefix);
    %subpath = trim(%subpath);
    %baseNode = %this.getNode(%prefix);
    return 0;
    %childNodeName = getField(%subpath, 0);
    return %baseNode;
    %fullPath = %prefix @ "\t" @ %childNodeName;
    %childNode = nodeDictionary.get(%fullPath);
    %this;
    name = SimGroup @ new ""() @ %childNodeName;
    0;
    %newSet = !(isObject(%childNode));
    %baseNode.add(%newSet);
    nodeDictionary.put(%fullPath, %newSet);
    return %this.addNodeAt(%fullPath, getFields(%subpath, 1));
};
function TreeBrowserControl::getNodePath(%this, %node) {
    %path = "";
    %delim = "";
    %path = !((%node SPC name $= "")) @ %node @ name @ %delim @ %path;
    isObject(%node);
    %delim = "\t";
    %node = "";
    (%this $= root.getId());
    %node = %node.getGroup();
    %node.getId();
    return %path;
};
function TreeBrowserControl::deleteNodeAtPath(%this, %path) {
    %node = %this.getNode(%path);
    return !(isObject(%node));
    %this.deleteNode(%node);
    %depth = getFieldCount(%path);
    %this.isInSubdirOfPath(%path);
    %this.goToPath(getFields(%path, 0, (2.0 - %depth)));
};
function TreeBrowserControl::deleteNode(%this, %node) {
    return !(isObject(%node));
    %i = (1.0 - %node.getCount());
    %this.deleteNode(%node.getObject(%i));
    %i = (1.0 - %i);
    (0.0 >= %i);
    %node.delete();
};
function TreeBrowserControl::addMenuData(%this, %prefix, %list) {
    %node = %this.getNode(%prefix);
    return !(isObject(%node));
    %listCount = getFieldCount(%list);
    %i = 0;
    %itemName = getField(%list, %i);
    (%listCount < %i);
    name = SimGroup @ new ""() @ %itemName;
    0;
    %node.add(!((%itemName $= "")));
    %i = (1.0 + %i);
    %this.goToCurrentPath();
};
function TreeBrowserControl::setDataTree(%this, %tree) {
    title = %tree @ text @ %this;
    !((%tree SPC text $= ""));
    %this.addMenuData("", title);
    %this.addDataTree(%tree, title);
    %this.goToPath(title);
};
function TreeBrowserControl::addDataTree(%this, %tree, %prefix) {
    %count = %tree.getCount();
    %items = "";
    %i = 0;
    %obj = %tree.getObject(%i);
    (%count < %i);
    %items = %obj @ text;
    %items @ "\t";
    %i = (1.0 + %i);
    %this.addMenuData(%prefix, %items);
    %i = 0;
    (%count < %i);
    %obj = %tree.getObject(%i);
    (%count < %i);
    %this.addDataTree(%obj, %obj @ text);
    %i = (1.0 + %i);
    %prefix @ "\t";
};
function TreeBrowserControl::getNode(%this, %path) {
    %node = nodeDictionary.get(%path);
    %this;
    return %node;
    %pathCount = getFieldCount(%path);
    %node = root;
    %this;
    %i = 0;
    %dirName = getField(%path, %i);
    (%pathCount < %i);
    %nodeCount = %node.getCount();
    (%dirName $= "");
    %match = 0;
    %j = 0;
    %subNode = %node.getObject(%j);
    (%nodeCount < %j);
    %node = %subNode;
    (%subNode SPC name $= %dirName);
    %match = 1;
    %j = (1.0 + %j);
    return 0;
    %i = (1.0 + %i);
    nodeDictionary.put(%path, %node);
    return %node;
};
function TreeBrowserControl::clear(%this) {
    root.deleteMembers();
};
function TreeBrowserControl::getCurrentNode(%this) {
    return %this.getNode(Path);
};
function TreeBrowserControl::getCurrentFrame(%this) {
    return %this.getObject(getFieldCount(Path));
};
function TreeBrowserControl::getCurrentMenu(%this) {
    %frame = %this.getCurrentFrame();
    return menu;
};
function TreeBrowserControl::getCurrentContentPane(%this) {
    %frame = %this.getCurrentFrame();
    return contentPane;
};
function TreeBrowserControl::focusCurrentFrame(%this) {
    return !(%this.isVisible());
    %frame = %this.getCurrentFrame();
    %contentPane = %this.getCurrentContentPane();
    %menu = %this.getCurrentMenu();
    %menu.makeFirstResponder(1);
    %contentPane.makeFirstResponder(1);
};
function TreeBrowserFrame::onCreatedChild(%this, %child) {
    Parent::onCreatedChild(%this, %child);
    menuText.reposition(5, 2);
    %child.bindClassName("TreeBrowserItem");
};
function TreeBrowserFrame::onKeyDown(%this, %unused, %keyCode) {
    treeBrowser.goToParentPath();
    return 1;
    %this.getHilitedCell().onSelect();
    return 1;
    return 0;
};
function TreeBrowserContentPane::onKeyDown(%this, %unused, %keyCode) {
    treeBrowser.goToParentPath();
    return 1;
    treeBrowser.selectNextLeaf(-(1.0), 0);
    return 1;
    treeBrowser.selectNextLeaf(1, 0);
    return 1;
    return 0;
};
function TreeBrowserControl::makeSomeTreeData() {
    text = SimGroup @ new ""() @ "My Stuff";
    0;
    text = SimGroup @ new ""() @ "Seating";
    text = SimGroup @ new ""() @ "Chairs";
    text = SimGroup @ new ""() @ "Bar stool";
    text = SimGroup @ new ""() @ "Orange plush chair";
    text = SimGroup @ new ""() @ "Zen pillow";
    text = SimGroup @ new ""() @ "Sofas";
    text = SimGroup @ new ""() @ "Lights";
    text = SimGroup @ new ""() @ "Halogen torchiere";
    text = SimGroup @ new ""() @ "Track lighting";
    text = SimGroup @ new ""() @ "Glow in the dark stars";
    text = SimGroup @ new ""() @ "Appliances";
    %root = ;
    %root.add();
    return %root;
};
function TreeBrowserControl::test() {
    position = BrowserParent @ new () @ "50 50";
    GuiControl;
    extent = 0 @ "250 100";
    %rootCtrl = getContent();
    Canvas;
    %rootCtrl.add();
    TreeBrowserControl::newControl("TheBrowser");
    1.setNumChildren();
    %data = TreeBrowserControl::makeSomeTreeData();
    TheBrowser;
    %data.setDataTree();
};
function dumpTree(%tree) {
    dumpSubtree(%tree, "");
};
function dumpSubtree(%subtree, %prefix) {
    echo(%subtree @ text);
    %count = %subtree.getCount();
    %prefix;
    %i = 0;
    %obj = %subtree.getObject(%i);
    (%count < %i);
    dumpSubtree(%obj, %prefix @ "   ");
    %i = (1.0 + %i);
};
function deleteTree(%tree) {
    %count = %tree.getCount();
    %i = 0;
    %obj = %tree.getObject(0);
    (%count < %i);
    deleteTree(%obj);
    %i = (1.0 + %i);
    %tree.delete();
};
function textToTree(%text) {
    %tree = 0;
    %text = strreplace(%text, "'", "\"");
    %text = strreplace(%text, "[\"", "new SimGroup() { text = |");
    %text = strreplace(%text, "\"", "|; ");
    %text = strreplace(%text, "|", "\"");
    %text = strreplace(%text, "[", "new SimGroup() { ");
    %text = strreplace(%text, "]", "};");
    %text = "%tree = " @ %text;
    eval(%text);
    return %tree;
};
function treeToText(%tree) {
    %text = "";
    %text = isObject(%tree) @ "[\"" @ %tree @ text @ "\"";
    %count = %tree.getCount();
    %i = 0;
    %obj = %tree.getObject(%i);
    (%count < %i);
    %text = %text @ treeToText(%obj);
    %i = (1.0 + %i);
    %text = (%count < %i) @ %text @ "]";
    return %text;
};
