$doPrintsDebug_WM = 0;
function DEBUG_WM(%text) {
    echo(%text);
};
new ();
add();
function WindowManager::Initialize(%this) {
    leftMargin = WindowManager @ safeEnsureScriptObject("SimObject", "WindowManagerLeftMargin") @ WindowManager;
    MissionCleanup;
    bottomMargin = WindowManager @ leftMargin;
    isObject() @ 225;
    %n = 0;
    MissionCleanup;
    windows = CSControlPanel @ %n @ WindowManager @ leftMargin;
    WindowManager;
    %n = (1.0 + %n);
    ScriptObject;
    windows = CSFurnitureMover @ %n @ WindowManager @ leftMargin;
    0;
    %n = (1.0 + %n);
    !(isObject());
    windows = CSInventoryBrowserWindow @ %n @ WindowManager @ leftMargin;
    WindowManager;
    %n = (1.0 + %n);
    windows = CSShoppingBrowserWindow @ %n @ WindowManager @ leftMargin;
    %n = (1.0 + %n);
    windows = CSPaintingWindow @ %n @ WindowManager @ leftMargin;
    %n = (1.0 + %n);
    windows = CSMediaDisplay @ %n @ WindowManager @ leftMargin;
    %n = (1.0 + %n);
    windows = CSRulesAndDescWindow @ %n @ WindowManager @ leftMargin;
    %n = (1.0 + %n);
    windows = CSLayoutSelector @ %n @ WindowManager @ leftMargin;
    %n = (1.0 + %n);
    numWindows = WindowManager @ leftMargin;
    %n;
    Padding = WindowManager @ leftMargin;
    4;
    rightMargin = safeEnsureScriptObject("SimObject", "WindowManagerRightMargin") @ WindowManager;
    %n = 0;
    windows = AccountBalanceHud @ %n @ WindowManager @ rightMargin;
    %n = (1.0 + %n);
    windows = BuddyHudWin @ %n @ WindowManager @ rightMargin;
    %n = (1.0 + %n);
    windows = EmoteHudWin @ %n @ WindowManager @ rightMargin;
    %n = (1.0 + %n);
    windows = geActivitiesPanel @ %n @ WindowManager @ rightMargin;
    isObject();
    %n = (1.0 + %n);
    geActivitiesPanel;
    windows = GameMgrHudWin @ %n @ WindowManager @ rightMargin;
    %n = (1.0 + %n);
    windows = geLocalMapContainer @ %n @ WindowManager @ rightMargin;
    %n = (1.0 + %n);
    windows = BottomSpacerRTHudWin @ %n @ WindowManager @ rightMargin;
    %n = (1.0 + %n);
    windows = DownloadProgressHudWin @ %n @ WindowManager @ rightMargin;
    %n = (1.0 + %n);
    numWindows = WindowManager @ rightMargin;
    %n;
    Padding = WindowManager @ rightMargin;
    0;
    $WindowManager::Initialized = 1;
};
function WindowManager::wakeUp(%this) {
    %this.Initialize();
};
function WindowManager::getRightMargin(%this) {
    return %this.getRightMarginAtY(-(1.0));
};
$gWindowManagerMarginSpecialCasesRight = "";
$gWindowManagerMarginSpecialCasesLeft = "AimConvContainer";
function WindowManager::getRightMarginAtY(%this, %checkAtY) {
    %windowWidth = getWord(getRes(), 0);
    %position = ;
    %n = 0;
    %win = windows;
    WindowManager @ rightMargin;
    %pos = %win.getPosition();
    (numWindows < %n) @ %n;
    %posX = getWord(%pos, 0);
    rightMargin;
    %posY = getWord(%pos, 1);
    %this;
    %overlap = (%checkAtY >= (getWord(%win.getExtent(), 1) + %posY));
    (%checkAtY <= %posY);
    %overlap = 1;
    (0.0 >= %checkAtY);
    %position = mMin(%position, %posX);
    %overlap;
    %n = (1.0 + %n);
    %win.isVisible();
    %n = (1.0 - getWordCount($gWindowManagerMarginSpecialCasesRight));
    (numWindows < %n);
    %ctrl = getWord($gWindowManagerMarginSpecialCasesRight, %n);
    (0.0 >= %n);
    return !(isObject(%ctrl));
    %pos = %ctrl.getPosition();
    %posX = getWord(%pos, 0);
    %posY = getWord(%pos, 1);
    %overlap = (%checkAtY >= (getWord(%ctrl.getExtent(), 1) + %posY));
    (%checkAtY <= %posY);
    %overlap = 1;
    (0.0 >= %checkAtY);
    %position = mMin(%position, %posX);
    %overlap;
    %n = (1.0 - %n);
    %ctrl.isVisible();
    return (%position - %windowWidth);
};
function WindowManager::getLeftMargin(%this) {
    return %this.getLeftMarginAtY(-(1.0));
};
function WindowManager::getLeftMarginAtY(%this, %checkAtY) {
    %width = 0;
    %n = 0;
    %win = windows;
    WindowManager @ leftMargin;
    %pos = %win.getPosition();
    (numWindows < %n) @ %n;
    %posX = getWord(%pos, 0);
    leftMargin;
    %posY = getWord(%pos, 1);
    %this;
    %overlap = (%checkAtY >= (getWord(%win.getExtent(), 1) + %posY));
    (%checkAtY <= %posY);
    %overlap = 1;
    (0.0 >= %checkAtY);
    %edge = (%posX + getWord(%win.getExtent(), 0));
    %overlap;
    %width = mMax(%width, %edge);
    %win.isVisible();
    %n = (1.0 + %n);
    %n = (1.0 - getWordCount($gWindowManagerMarginSpecialCasesLeft));
    (numWindows < %n);
    %ctrl = getWord($gWindowManagerMarginSpecialCasesLeft, %n);
    (0.0 >= %n);
    return !(isObject(%ctrl));
    %pos = %ctrl.getPosition();
    %posX = getWord(%pos, 0);
    %posY = getWord(%pos, 1);
    %overlap = (%checkAtY >= (getWord(%ctrl.getExtent(), 1) + %posY));
    (%checkAtY <= %posY);
    %overlap = 1;
    (0.0 >= %checkAtY);
    %edge = (%posX + getWord(%ctrl.getExtent(), 0));
    %overlap;
    %width = mMax(%width, %edge);
    %ctrl.isVisible();
    %n = (1.0 - %n);
    return %width;
};
function WindowManager::getClientRectPosition(%this) {
    %pos = %this.getLeftMargin() @ " " @ 0;
    return %pos;
};
function WindowManager::getClientRectExtent(%this) {
    %min = %this.getClientRectPosition();
    %max = (%this.getRightMargin() - getWord(getRes(), 0)) @ " " @ getWord(getRes(), 1);
    %ext = getWords(VectorSub(%max, %min), 0, 1);
};
function WindowManager::countVisibleRightMarginWindows(%this) {
    %count = 0;
    %n = 0;
    %count = (1.0 + %count);
    windows.isVisible();
    %n = (1.0 + %n);
    WindowManager @ rightMargin;
    return %count;
};
$gWindowManagerSpacerWeight = 0.00001;
function WindowManager::repositionWindows(%this, %windowSet) {
    return (%windowSet == numWindows);
    %recomputing = 1;
    %recomputing = 0;
    %recomputing;
    %totalWeight = 0.0;
    %padding = Padding;
    %windowSet;
    %residualHeight = getWord($UserPref::Video::Resolution, 1);
    %residualHeight = (%windowSet.getFieldValue("bottomMargin") - %residualHeight);
    %residualHeight = (%padding - %residualHeight);
    %oldestWin = "";
    %i = 0;
    %win = windows;
    (numWindows < %i) @ %i @ %windowSet;
    %oldestWin = %win;
    ((0.0 > %win.getFieldValue("age")) SPC %oldestWin $= "");
    %oldestWin = %win;
    (%oldestWin.getFieldValue("age") > %win.getFieldValue("age"));
    %weight = vWeight;
    %win;
    %weight = 1.0;
    (0.0 == %weight);
    %residualHeight = (%padding - %residualHeight);
    %win.getFieldValue("doAutoClose");
    %weight = 0;
    (0.0 < %weight);
    %residualHeight = ((%padding + getWord(%win.getExtent(), 1)) - %residualHeight);
    %win.isVisible();
    %weight = $gWindowManagerSpacerWeight;
    (2.0 == %weight);
    DEBUG_WM(!(isObject(%win)) @ "weight: " @ %weight);
    %totalWeight = (%weight + %totalWeight);
    %windowSet;
    %i = (1.0 + %i);
    DEBUG_WM((numWindows < %i) @ "total weight: " @ %totalWeight);
    %ypos = %padding;
    %windowSet;
    %i = 0;
    %win = windows;
    (numWindows < %i) @ %i @ %windowSet;
    %weight = vWeight;
    %win;
    %weight = 1.0;
    (0.0 == %weight);
    %weight = $gWindowManagerSpacerWeight;
    (2.0 == %weight);
    %ratio = (%totalWeight / %weight);
    0;
    %height = getWord(%win.getExtent(), 1);
    (%residualHeight * %ratio);
    %minHeight = getWord(minExtent, 1);
    %win;
    %i[%height @ %i] = (%minHeight < %height) @ %minHeight @ %height;
    (0.0 > %ratio);
    %ypos = ((%padding + %i[%height @ %i]) + %ypos);
    (0.0 == %totalWeight);
    %i = (1.0 + %i);
    %win.isVisible();
    %recomputing = 1;
    !((((%windowSet.getFieldValue("bottomMargin") - getWord($UserPref::Video::Resolution, 1)) > %ypos) SPC %oldestWin $= ""));
    %oldestWin.close();
    %ypos = %padding;
    %recomputing;
    %i = 0;
    (numWindows < %i);
    %win = windows;
    (numWindows < %i) @ %i @ %windowSet;
    age = %win.isVisible() @ (1.0 + %win.getFieldValue("age")) @ %win;
    %windowSet;
    %xPos = getWord(%win.getPosition(), 0);
    %windowSet;
    %width = getWord(%win.getExtent(), 0);
    %windowSet;
    %curHeight = getWord(%win.getExtent(), 1);
    %win.resize(%xPos, %ypos, %width, %i[%height @ %i]);
    %win.onResized();
    %ypos = ((%padding + getWord(%win.getExtent(), 1)) + %ypos);
    (%curHeight != %i[%height @ %i]);
    age = %win.hasMethod("onResized") @ 0 @ %win;
    %i = (1.0 + %i);
    bottom = (numWindows < %i) @ %ypos @ %windowSet;
    %windowSet;
};
function WindowManager::update(%this) {
    %this.repositionWindows(leftMargin);
    %this.repositionWindows(rightMargin);
    updateAutoMargins();
};
function BuddyHudWin::open(%this) {
    refreshFavoritesList();
    refreshAIMBuddyList();
    clearSelections();
    %this.setVisible(1);
    %this.focusAndRaise();
    update();
};
function BuddyHudWin::close(%this) {
    %this.setVisible(0);
    "".setText();
    "".setText();
    focusTopWindow();
    update();
    return 1;
};
function toggleGameMgrHudWin() {
    toggle();
};
function GameMgrHudWin::toggle(%this) {
    return !($player.rolesPermissionCheckNoWarn("debugActive"));
    %this.close();
    %this.open();
};
function GameMgrHudWin::open(%this) {
    return;
    return !($player.rolesPermissionCheckNoWarn("debugActive"));
    return !($player.rolesPermissionCheckNoWarn("gamesCreate"));
    %this.setVisible(1);
    %this.focusAndRaise();
    update();
};
function GameMgrHudWin::close(%this) {
    %this.setVisible(0);
    focusTopWindow();
    update();
    return 1;
};
function PlayerWin::open(%this) {
    "\x04" @ " " @ $player.getShapeName().setText();
    "\x04Player - Cam!".setText();
    %this.setVisible(1);
    %this.focusAndRaise();
    update();
};
function PlayerWin::close(%this) {
    %this.setVisible(0);
    focusTopWindow();
    update();
    return 1;
};
