$adLogFileName = "";
$adLogCreationTimestamp = "";
function getAdLogName(%timeStamp) {
    %ServerName = stripVeryAgressively($Pref::Server::Name);
    %ServerName = "unknownServer";
    (%ServerName $= "");
    %s = $userMods @ "/server/" @ $Pref::Server::adLogFolder @ "/" @ %ServerName @ "/" @ $Pref::Server::adLogBaseName;
    %s = $Pref::Server::adLogAppendTimeStamp @ %s @ "_" @ %timeStamp;
    %s = %s @ ".log";
    return %s;
};
function checkNewAdLogFile() {
    return ($adLogCreationTimestamp $= "");
    %minsLog = getSubStr($adLogCreationTimestamp, 0, 8);
    %minsNow = getSubStr(getTimeStamp(), 0, 8);
    $adLogFileName = "";
    (0.0 > strcmp(%minsNow, %minsLog));
    $adLogCreationTimestamp = "";
    return;
};
function initAdLogFile() {
    checkNewAdLogFile();
    return $adLogFileName;
    %ts = getTimeStamp();
    %ts = getSubStr(%ts, 0, 17);
    $adLogFileName = getAdLogName(%ts);
    $adLogCreationTimestamp = %ts;
    %file = new ""();
    FileObject;
    %file.writeLine("# Evil Twin Ads Log File");
    %file.writeLine("#" @ " " @ $adLogFileName);
    %file.writeLine("#" @ " " @ %ts);
    %file.writeLine("# Action: <tab> timestamp <tab> playername <tab> imagename <tab> (image-click-coords) <tab> (advert transform) <tab> (advert scale)");
    %file.writeLine("");
    %file.close();
    echo("AdLog started:" @ " " @ $adLogFileName);
    echo("Error opening logfile:" @ " " @ $adLogFileName);
    %file.delete();
    return $adLogFileName;
};
function appendAdLogLine(%line) {
    %fn = initAdLogFile();
    %file = new ""();
    FileObject;
    %file.writeLine(%line);
    %file.close();
    echo("Error opening logfile:" @ " " @ %fn);
    echo(%line);
    %file.delete();
    return %file.openForAppend(%fn);
};
function serverCmdAdvertClick(%client, %ghostIndexClnt, %pt) {
    %playerName = detag(Player.getShapeName());
    %client;
    %obj = %client.resolveObjectFromGhostIndex(%ghostIndexClnt);
    %tex = %obj.getSkinName();
    %line = "AdClick: ";
    %line = %line @ "\t" @ getTimeStamp();
    %line = %line @ "\t" @ stripUnprintables(%playerName);
    %line = %line @ "\t" @ %obj.getSkinName();
    %line = %line @ "\t" @ %pt;
    %line = %line @ "\t" @ "(" @ %obj.getTransform() @ ")" @ "\t" @ "(" @ %obj.getScale() @ ")";
    appendAdLogLine(%line);
    return;
};
function serverCmdAdvertFollow(%client, %url) {
    %playerName = detag(Player.getShapeName());
    %client;
    %line = "AdFollow:";
    %line = %line @ "\t" @ getTimeStamp();
    %line = %line @ "\t" @ stripUnprintables(%playerName);
    %line = %line @ "\t" @ %url;
    appendAdLogLine(%line);
    return;
};
function AdGroup::init(%this) {
    num = 0 @ %this;
    dtsNum = 0 @ %this;
    sort = forward @ %this;
    offset = 0 @ %this;
    return;
};
function AdGroup::addAd(%this, %texture, %title, %url) {
    textures = %texture @ %this @ num @ %this;
    titles = %title @ %this @ num @ %this;
    urls = %url @ %this @ num @ %this;
    num = 1.0 @ (%this + num) @ %this;
    return;
};
function AdGroup::addDTSGroup(%this, %grp) {
    dtss = %grp @ %this @ dtsNum @ %this;
    dtsNum = 1.0 @ (%this + dtsNum) @ %this;
    return;
};
function AdGroup::doSwap(%this) {
    offset = 1.0 @ (%this + offset) @ %this;
    offset = (%this >= offset) @ 0 @ %this;
    num;
    %adNum = offset;
    %this;
    %numAds = 0;
    %this;
    %gn = 0;
    %dtsGrp = dtss;
    (dtsNum < %gn) @ %gn @ %this;
    %dtsNum = %dtsGrp.getCount();
    %this;
    %numAds = (%dtsNum + %numAds);
    %dn = 0;
    %dts = %dtsGrp.getObject(%dn);
    (%dtsNum < %dn);
    %adNum = getRandom((%this - num));
    1.0;
    %adNum = getRandom((%this - num));
    1.0;
    %adNum = getRandom((%this - num));
    1.0;
    prevAdNum = (prevAdNum == %adNum) @ %adNum @ %dts;
    %dts;
    %dts.setSkinName(textures);
    %dts.setTitle(titles);
    %dts.setBasicURL(urls);
    %adNum = (1.0 + %adNum);
    (prevAdNum == %adNum) @ %adNum @ %this @ %adNum @ %this @ %adNum @ %this;
    %adNum = 0;
    (num >= %adNum);
    %dn = (1.0 + %dn);
    %this;
    %gn = (1.0 + %gn);
    (%dtsNum < %dn);
    return %numAds;
};
function AdManager::doSwap(%this) {
    %numAds = 0;
    %g = 0;
    %numAds = (adGrps.doSwap() + %numAds);
    (adGrpsNum < %g) @ %g @ %this;
    %g = (1.0 + %g);
    %this;
    return %numAds;
};
function AdManager::think(%this) {
    %this.schedule((%this * periodSecs));
    echo("Putting AdManager to sleep..");
    return think;
};
function AdManager::newAdGroup(%this) {
    class = new ""() @ AdGroup;
    ScriptObject;
    manager = 0 @ %this;
    %adGrp = ;
    %adGrp.init();
    adGrps = %adGrp @ %this @ adGrpsNum @ %this;
    adGrpsNum = 1.0 @ (%this + adGrpsNum) @ %this;
    return %adGrp;
};
