shapeFile = BeckAdd @ datablock ( : BasicAmbientAnimateShapeData) @ "projects/vside/worlds/lounge/shapes/animad_beck.dts";
StaticShapeData;
0;
shapeFile = SecurityCamera @ datablock ( : BasicAmbientAnimateShapeData) @ "projects/vside/worlds/lounge/shapes/securitycamera.dts";
StaticShapeData;
0;
shapeFile = Hottubwater @ datablock ( : BasicAmbientAnimateShapeData) @ "projects/vside/worlds/lounge/shapes/hottubwater.dts";
StaticShapeData;
0;
shapeFile = SubWayTrain @ datablock ( : BasicAmbientAnimateShapeData) @ "projects/vside/worlds/lounge/shapes/subwaycar.dts";
StaticShapeData;
0;
shapeFile = ClockHand @ datablock ( : BasicAmbientAnimateShapeData) @ "projects/vside/worlds/lounge/shapes/clockhand.dts";
StaticShapeData;
0;
shapeFile = WaterEdge @ datablock ( : BasicAmbientAnimateShapeData) @ "projects/vside/worlds/lounge/shapes/wateredge.dts";
StaticShapeData;
0;
shapeFile = TreelgA @ datablock ( : BasicAmbientAnimateShapeData) @ "projects/vside/worlds/lounge/shapes/obj_flora_treelga.dts";
StaticShapeData;
0;
shapeFile = TreelgB @ datablock ( : BasicAmbientAnimateShapeData) @ "projects/vside/worlds/lounge/shapes/obj_flora_treelgb.dts";
StaticShapeData;
0;
shapeFile = foamywater @ datablock ( : BasicAmbientAnimateShapeData) @ "projects/vside/worlds/lounge/shapes/obj_misc_foamywater.dts";
StaticShapeData;
0;
shapeFile = waterwall @ datablock ( : BasicAmbientAnimateShapeData) @ "projects/vside/worlds/lounge/shapes/waterwall.dts";
StaticShapeData;
0;
shapeFile = Blimp @ datablock ( : BasicAmbientAnimateShapeData) @ "projects/vside/worlds/lounge/shapes/blimp.dts";
StaticShapeData;
0;
shapeFile = listeningStation @ datablock ( : BasicAmbientAnimateShapeData) @ "projects/vside/worlds/lounge/shapes/listening_station.dts";
StaticShapeData;
0;
shapeFile = ListeningStation2 @ datablock ( : BasicAmbientAnimateShapeData) @ "projects/vside/worlds/lounge/shapes/listening_station2.dts";
StaticShapeData;
0;
shapeFile = butterfly @ datablock ( : BasicAmbientAnimateShapeData) @ "projects/vside/worlds/lounge/shapes/obj_fauna_butterfly.dts";
StaticShapeData;
0;
