exec("./mixnmatch.cs");
exec("./scalePlayer.cs");
exec("./bots.cs");
exec("./commandsETS.cs");
exec("./spawning.cs");
exec("./advertsSrvr.cs");
exec("./conversationServer.cs");
exec("./buddy.cs");
exec("./etsCam.cs");
exec("./heartbeat.cs");
exec("./water.cs");
exec("~/common/scripts/init.cs");
exec("./NPC.cs");
exec("./permissionsServer.cs");
exec("./adminServer.cs");
exec("./systemMessageServer.cs");
if (isFile("./secret.cs"))
{
    exec("./secret.cs");
}
