function NPCManager::init(%this) {
    animSets.delete();
    animSets = StringMap @ new ""() @ %this;
    0;
    animSets.add();
    %as = animSets;
    %this;
    thinkPeriod = %this @ 1311 @ %this;
    MissionCleanup;
    NPCGroup = NPCGroup @ %this;
    %this;
    %this.resetnextAnimTimes();
    %this.assertOutfits();
    numResponseAnims = isObject(animSets) @ 0 @ %this;
    %this;
    %this.setAnimTimeMin("bouncer1", 10000);
    %this.setAnimTimeMax("bouncer1", 20000);
    %this.addAnimToSet("bouncer1", "idle2");
    %this.addAnimToSet("bouncer1", "idle1");
    %this.addAnimToSet("bouncer1", "idle1");
    %this.setAnimTimeMin("pcdkim", 10000);
    %this.setAnimTimeMax("pcdkim", 15000);
    %this.addAnimToSet("pcdkim", "talk2");
    %this.addAnimToSet("pcdkim", "talk3");
    %this.addAnimToSet("pcdkim", "listen2");
    %this.setAnimTimeMin("pcdashley", 10000);
    %this.setAnimTimeMax("pcdashley", 15000);
    %this.addAnimToSet("pcdashley", "listen");
    %this.setAnimTimeMin("pcdcarmit", 10000);
    %this.setAnimTimeMax("pcdcarmit", 15000);
    %this.addAnimToSet("pcdcarmit", "talk");
    %this.setAnimTimeMin("pcdmelody", 10000);
    %this.setAnimTimeMax("pcdmelody", 15000);
    %this.addAnimToSet("pcdmelody", "idle");
    %this.addAnimToSet("pcdmelody", "idle");
    %this.addAnimToSet("pcdmelody", "talk");
    %this.setAnimTimeMin("pcdjessica", 10000);
    %this.setAnimTimeMax("pcdjessica", 15000);
    %this.addAnimToSet("pcdjessica", "lidle1");
    %this.addAnimToSet("pcdjessica", "lidle2");
    %this.addAnimToSet("pcdjessica", "lidle3");
    %this.addAnimToSet("pcdjessica", "lidle4");
    %this.addAnimToSet("pcdjessica", "lidle5");
    %this.addAnimToSet("pcdjessica", "lidle6");
    %this.setAnimTimeMin("pcdnicole", 8000);
    %this.setAnimTimeMax("pcdnicole", 10000);
    %this.addAnimToSet("pcdnicole", "idle1");
    %this.addAnimToSet("pcdnicole", "idle2");
    %this.addAnimToSet("pcdnicole", "idle3");
    %this.addAnimToSet("pcdnicole", "idle4");
    %this.addAnimToSet("pcdnicole", "idle1");
    %this.addAnimToSet("pcdnicole", "idle1");
    %this.addAnimToSet("pcdnicole", "wave");
    %this.setAnimTimeMin("dj1", 3000);
    %this.setAnimTimeMax("dj1", 5000);
    %this.addAnimToSet("dj1", "idle");
    %this.addAnimToSet("dj1", "idle");
    %this.addAnimToSet("dj1", "idle");
    %this.addAnimToSet("dj1", "fiddle");
    %this.setAnimTimeMin("dj2", 3000);
    %this.setAnimTimeMax("dj2", 5000);
    %this.addAnimToSet("dj2", "idle");
    %this.addAnimToSet("dj2", "idle");
    %this.addAnimToSet("dj2", "idle");
    %this.addAnimToSet("dj2", "fiddle");
    %this.setAnimTimeMin("bartenderF", 10000);
    %this.setAnimTimeMax("bartenderF", 15000);
    %this.addAnimToSet("bartenderF", "fnbtfbb");
    %this.addAnimToSet("bartenderF", "fnbtidl1");
    %this.addAnimToSet("bartenderF", "fnbtidl1");
    %this.addAnimToSet("bartenderF", "fnbtlidl1");
    %this.addAnimToSet("bartenderF", "fnbtlidl1");
    %this.addAnimToSet("bartenderF", "fnbtlidl2");
    %this.addAnimToSet("bartenderF", "fnbtidl1");
    %this.addAnimToSet("bartenderF", "fnbtidl1");
    %this.addAnimToSet("bartenderF", "fnbtlidl1");
    %this.addAnimToSet("bartenderF", "fnbtlidl1");
    %this.addAnimToSet("bartenderF", "fnbtlidl2");
    %this.setAnimTimeMin("bartenderM", 10000);
    %this.setAnimTimeMax("bartenderM", 15000);
    %this.addAnimToSet("bartenderM", "mnbtfbb");
    %this.addAnimToSet("bartenderM", "mnbtidl1");
    %this.addAnimToSet("bartenderM", "mnbtidl1");
    %this.addAnimToSet("bartenderM", "mnbtlidl1");
    %this.addAnimToSet("bartenderM", "mnbtlidl2");
    %this.addAnimToSet("bartenderM", "mnbtlidl2");
    %this.addAnimToSet("bartenderM", "mnbtidl1");
    %this.addAnimToSet("bartenderM", "mnbtidl1");
    %this.addAnimToSet("bartenderM", "mnbtlidl1");
    %this.addAnimToSet("bartenderM", "mnbtlidl2");
    %this.addAnimToSet("bartenderM", "mnbtlidl2");
    %this.setAnimTimeMin("storekeepM", 10000);
    %this.setAnimTimeMax("storekeepM", 15000);
    %this.addAnimToSet("storekeepM", "mnbtidl1");
    %this.addAnimToSet("storekeepM", "mnbtlidl1");
    %this.addAnimToSet("storekeepM", "mnbtlidl2");
    %this.setAnimTimeMin("djgroupie1", 10000);
    %this.setAnimTimeMax("djgroupie1", 15000);
    %this.addAnimToSet("djgroupie1", "fhlidl1a");
    %this.addAnimToSet("djgroupie1", "fhlidl2a");
    %this.addAnimToSet("djgroupie1", "filidl1a");
    %this.addAnimToSet("djgroupie1", "filidl2a");
    %this.addAnimToSet("djgroupie1", "fplidl1a");
    %this.addAnimToSet("djgroupie1", "fplidl2a");
    %this.setAnimTimeMin("djgroupie2", 10000);
    %this.setAnimTimeMax("djgroupie2", 15000);
    %this.addAnimToSet("djgroupie2", "fnsitlsn");
    %this.addAnimToSet("djgroupie2", "fnsittlk");
    %this.setAnimTimeMin("djgroupie3", 7000);
    %this.setAnimTimeMax("djgroupie3", 9000);
    %this.addAnimToSet("djgroupie3", "midl2a");
    %this.addAnimToSet("djgroupie3", "midl2b");
    %this.addAnimToSet("djgroupie3", "midl2c");
    %this.addAnimToSet("djgroupie3", "midl2d");
    %this.addAnimToSet("djgroupie3", "mntlk2");
    %this.addAnimToSet("djgroupie3", "mntlk3");
    %this.addAnimToSet("djgroupie3", "mntlk");
    %this.addAnimToSet("djgroupie3", "micool");
    %this.addAnimToSet("djgroupie3", "miflr");
    %this.setAnimTimeMin("andrew", 3000);
    %this.setAnimTimeMax("andrew", 5000);
    %this.addAnimToSet("andrew", "idl1");
    %this.addAnimToSet("andrew", "idl2");
    %this.addAnimToSet("andrew", "idl3");
    %this.addAnimToSet("andrew", "idl4");
    %this.addAnimToSet("andrew", "vomit");
    %this.addAnimToSet("andrew", "whew");
    %this.addAnimToSet("ai_bouncer", "idle2");
    %this.addAnimToSet("ai_bouncer", "idle1");
    %this.addAnimToSet("ai_bouncer", "idle1");
    %this.addAnimToSet("ai_pcd", "");
    %this.addAnimToSet("ai_dj", "");
    %this.addAnimToSet("ai_generic", "");
    %this.addAnimToSet("ai_generic", "");
    %this.addAnimToSet("ai_generic", "");
    %this.addAnimToSet("ai_generic", "");
    %this.addAnimToSet("ai_generic", "");
    %this.addAnimToSet("ai_generic", "");
    %this.addAnimToSet("ai_generic", "");
    %this.addAnimToSet("ai_generic", "");
    %this.addAnimToSet("ai_generic", "");
    %this.addAnimToSet("ai_generic", "cnf");
    %this.addAnimToSet("ai_generic", "cnf");
    %this.addAnimToSet("ai_generic", "cnf");
    %this.addAnimToSet("ai_generic", "cnf");
    %this.addAnimToSet("ai_generic", "cnf");
    %this.addAnimToSet("ai_generic", "cnf");
    %this.addAnimToSet("ai_generic", "cnf");
    %this.addAnimToSet("ai_generic", "cnf");
    %this.addAnimToSet("ai_generic", "cnf");
    %this.addAnimToSet("ai_generic", "cnf");
    %this.addAnimToSet("ai_generic", "lol");
    %this.addAnimToSet("ai_generic", "lol");
    %this.addAnimToSet("ai_generic", "lol");
    %this.addAnimToSet("ai_generic", "lol");
    %this.addAnimToSet("ai_generic", "lol");
    %this.addAnimToSet("ai_generic", "lol");
    %this.addAnimToSet("ai_generic", "lol");
    %this.addAnimToSet("ai_generic", "lol");
    %this.addAnimToSet("ai_generic", "lol");
    %this.addAnimToSet("ai_generic", "lol");
    %this.addAnimToSet("ai_generic", "think");
    %this.addAnimToSet("ai_generic", "think");
    %this.addAnimToSet("ai_generic", "think");
    %this.addAnimToSet("ai_generic", "think");
    %this.addAnimToSet("ai_generic", "think");
    %this.addAnimToSet("ai_generic", "cool");
    %this.addAnimToSet("ai_generic", "cool");
    %this.addAnimToSet("ai_generic", "cool");
    %this.addAnimToSet("ai_generic", "nlst");
    %this.addAnimToSet("ai_generic", "nlst");
    %this.addAnimToSet("ai_generic", "nlst");
    %this.addAnimToSet("ai_generic", "ttth");
    %this.addAnimToSet("ai_generic", "cool");
    %this.addAnimToSet("ai_generic", "shhh");
    %this.addAnimToSet("ai_generic", "flr");
    %this.addAnimToSet("ai_generic", "lsn");
    %this.addAnimToSet("ai_generic", "sad");
    %this.addAnimToSet("ai_generic", "spr");
    %this.addAnimToSet("ai_generic", "srd");
    %this.addAnimToSet("ai_generic", "cry");
    %this.addAnimToSet("ai_generic", "ilve");
    %this.addAnimToSet("ai_generic", "kiss");
    %this.addAnimToSet("ai_generic", "emb");
    %this.addAnimToSet("ai_generic", "vom");
    %this.addAnimToSet("ai_generic", "slpy");
    %this.addAnimToSet("ai_generic", "whw");
    %this.addAnimToSet("ai_generic", "rotfl");
    %this.addAnimToSet("ai_generic", "apls");
    %this.addAnimToSet("ai_generic", "doh");
    %this.addAnimToSet("ai_generic", "busy");
    %this.addAnimToSet("ai_generic", "nlst");
    return;
};
function storeTransformsSet(%simSet) {
    %num = %simSet.getCount();
    %n = 0;
    %obj = %simSet.getObject(%n);
    (%num < %n);
    gSetField(%obj, %obj.getTransform());
    %n = (1.0 + %n);
    origTransform;
};
function restoreTransformsSet(%simSet) {
    %num = %simSet.getCount();
    %n = 0;
    %obj = %simSet.getObject(%n);
    (%num < %n);
    %obj.setTransform(gGetField(%obj));
    %n = (1.0 + %n);
    origTransform;
};
function copyObjectNamesToShapeNamesSet(%simSet) {
    %num = %simSet.getCount();
    %n = 0;
    %obj = %simSet.getObject(%n);
    (%num < %n);
    %obj.setShapeName(%obj.getName());
    %n = (1.0 + %n);
};
function registerInPlayerDictSet(%simSet) {
    %num = %simSet.getCount();
    %n = 0;
    %obj = %simSet.getObject(%n);
    (%num < %n);
    %obj.getShapeName().put(%obj);
    %n = (1.0 + %n);
    PlayerDict;
};
function NPCManager::resetnextAnimTimes(%this) {
    return !(isObject(NPCGroup));
    %NPCNum = NPCGroup.getCount();
    %this;
    %n = 0;
    gSetField(NPCGroup.getObject(%n), "");
    %n = (1.0 + %n);
    nextAnimTime;
};
function NPCManager::assertOutfits(%this) {
    return !(isObject(NPCGroup));
    %NPCNum = NPCGroup.getCount();
    %this;
    %n = 0;
    %npc = NPCGroup.getObject(%n);
    %this;
    %gnd = gender;
    %npc.getDataBlock();
    gender = (%NPCNum < %n) @ %gnd @ %npc;
    %npc.MeshOff(%gnd @ ".headphones.dj");
    %w = Wardrobe::findWardrobe(%gnd);
    !((%gnd $= ""));
    %os = outfit;
    %npc.getDataBlock();
    %outfit = newOutfit(%w);
    %w;
    %outfit.makeRandom();
    %outfit.deserialize(%os);
    %outfit.assert(%npc);
    %n = (1.0 + %n);
    (%os $= "random");
};
function NPCManager::setAnimTimeMin(%this, %setName, %val) {
    animSets.put(%this @ %setName @ "_TimeMin", %val);
    return;
};
function NPCManager::setAnimTimeMax(%this, %setName, %val) {
    animSets.put(%this @ %setName @ "_TimeMax", %val);
    return;
};
function NPCManager::getAnimTimeMin(%this, %setName) {
    return animSets.get(%this @ %setName @ "_TimeMin");
};
function NPCManager::getAnimTimeMax(%this, %setName) {
    return animSets.get(%this @ %setName @ "_TimeMax");
};
function NPCManager::getRandomAnimFromSet(%this, %setName) {
    %set = animSets.get(%setName);
    %this;
    %num = getWordCount(%set);
    return getWord(%set, getRandom(0, (1.0 - %num)));
};
function NPCManager::addAnimToSet(%this, %setName, %val) {
    %prev = animSets.get(%setName);
    %this;
    %newThing = %prev @ " " @ %val;
    !((%prev $= ""));
    %newThing = %val;
    animSets.put(%setName, %newThing);
    %sets = animSets.get("setNames");
    %this;
    return (-(1.0) != findWord(%sets, %setName));
    %newThing = %sets @ " " @ %setName;
    !((%sets $= ""));
    %newThing = %setName;
    animSets.put("setNames", %newThing);
    return %this;
};
function NPCManager::think(%this) {
    warn("No NPC group, going to sleep..");
    return !(isObject(NPCGroup));
    %NPCNum = NPCGroup.getCount();
    %this;
    %n = 0;
    %this.thinkNPC(NPCGroup.getObject(%n));
    %n = (1.0 + %n);
    %this;
    %this.schedule(thinkPeriod);
    return think;
};
function NPCManager::thinkNPC(%this, %npc) {
    %setName = animSetName;
    %npc.getDataBlock();
    echo("Trouble in little china");
    return !(isObject(animSets));
    %curTime = getSimTime();
    %nat = gGetField(%npc);
    nextAnimTime;
    return (%nat < %curTime);
    %nat = (getRandom(%this.getAnimTimeMin(%setName), %this.getAnimTimeMax(%setName)) + %curTime);
    gSetField(%npc, %nat);
    %animSet = animSets.get(%setName);
    %this;
    %anim = %this.getRandomAnimFromSet(%setName);
    nextAnimTime;
    %npc.playAnim(%anim);
    return;
};
function NPCManager::dumpEts(%this) {
    %sets = animSets.get("setNames");
    %this;
    %setsNum = getWordCount(%sets);
    %setN = 0;
    %set = getWord(%sets, %setN);
    (%setsNum < %setN);
    echo(%set @ " " @ "timeMin =" @ " " @ %this.getAnimTimeMin(%set) @ " " @ "timeMax =" @ " " @ %this.getAnimTimeMax(%set));
    %anims = animSets.get(%set);
    %this;
    %animsNum = getWordCount(%anims);
    %animN = 0;
    %anim = getWord(%anims, %animN);
    (%animsNum < %animN);
    echo("  " @ %anim);
    %animN = (1.0 + %animN);
    %setN = (1.0 + %setN);
    (%animsNum < %animN);
};
function NPCManager::handleTalkedToNPC(%this, %unused, %npc, %unused) {
    %setName = aiProfile;
    %npc.getDataBlock();
    %anim = %this.getRandomAnimFromSet(%setName);
    return (%anim $= "");
    %delay = getRandom(500, 1500);
    %npc.schedule(%delay, "playAnim", %anim);
    return;
};
