outfit = db_npcF @ datablock ( : PlayerF) @ "random";
PlayerData;
0;
outfit = db_npcM @ datablock ( : PlayerM) @ "random";
PlayerData;
0;
shapeFile = npc_bouncer1DB @ datablock ( : PlayerBody) @ "projects/common/characters/NPC/bouncer1/npc_bouncer1.dts";
PlayerData;
animSetName = 0 @ "bouncer1";
aiProfile = "ai_bouncer";
shapeFile = npc_pcdkimDB @ datablock ( : PlayerBody) @ "projects/common/characters/NPC/pcdkim/npc_pcdkim.dts";
PlayerData;
animSetName = 0 @ "pcdkim";
aiProfile = "ai_pcd";
shapeFile = npc_pcdashleyDB @ datablock ( : PlayerBody) @ "projects/common/characters/NPC/pcdashley/npc_pcdashley.dts";
PlayerData;
animSetName = 0 @ "pcdashley";
aiProfile = "ai_pcd";
shapeFile = npc_pcdcarmitDB @ datablock ( : PlayerBody) @ "projects/common/characters/NPC/pcdcarmit/npc_pcdcarmit.dts";
PlayerData;
animSetName = 0 @ "pcdcarmit";
aiProfile = "ai_pcd";
shapeFile = npc_pcdjessicaDB @ datablock ( : PlayerBody) @ "projects/common/characters/NPC/pcdjessica/npc_pcdjessica.dts";
PlayerData;
animSetName = 0 @ "pcdjessica";
aiProfile = "ai_pcd";
shapeFile = npc_pcdmelodyDB @ datablock ( : PlayerBody) @ "projects/common/characters/NPC/pcdmelody/npc_pcdmelody.dts";
PlayerData;
animSetName = 0 @ "pcdmelody";
aiProfile = "ai_pcd";
shapeFile = npc_pcdnicoleDB @ datablock ( : PlayerBody) @ "projects/common/characters/NPC/pcdnicole/npc_pcdnicole.dts";
PlayerData;
animSetName = 0 @ "pcdnicole";
aiProfile = "ai_pcd";
shapeFile = npc_dj1DB @ datablock ( : PlayerBody) @ "projects/common/characters/NPC/dj1/npc_dj1.dts";
PlayerData;
animSetName = 0 @ "dj1";
aiProfile = "ai_dj";
shapeFile = npc_dj2DB @ datablock ( : PlayerBody) @ "projects/common/characters/NPC/dj2/npc_dj2.dts";
PlayerData;
animSetName = 0 @ "dj2";
aiProfile = "ai_dj";
toonColorFill = npc_bartender1DB @ datablock ( : db_npcF) @ "0.3 0.3 0.3";
PlayerData;
animSetName = 0 @ "bartenderF";
outfit = "f 0 3 3 0 23 1 2 2";
aiProfile = "ai_generic";
toonColorFill = npc_bartender2DB @ datablock ( : db_npcM) @ "0.3 0.3 0.3";
PlayerData;
animSetName = 0 @ "bartenderM";
outfit = "m 15 3 2 0 42 4 20 1";
aiProfile = "ai_generic";
animSetName = npc_bartender3DB @ datablock ( : db_npcF) @ "bartenderF";
PlayerData;
outfit = 0 @ "f 25 0 2 0 23 6 5 1";
aiProfile = "ai_generic";
animSetName = npc_bartender4DB @ datablock ( : db_npcM) @ "bartenderM";
PlayerData;
outfit = 0 @ "m 29 0 0 0 40 5 22 3";
aiProfile = "ai_generic";
animSetName = npc_bartender5DB @ datablock ( : db_npcF) @ "bartenderF";
PlayerData;
outfit = 0 @ "f 30 3 0 0 20 8 10 0";
aiProfile = "ai_generic";
animSetName = npc_storekeep1DB @ datablock ( : db_npcM) @ "storekeepM";
PlayerData;
outfit = 0 @ "m 21 0 0 0 24 5 2 3";
aiProfile = "ai_generic";
animSetName = npc_djgroupie1DB @ datablock ( : db_npcF) @ "djgroupie1";
PlayerData;
outfit = 0 @ "f 4 2 3 0 20 8 10 2";
aiProfile = "ai_djGroupieSit";
animSetName = npc_djgroupie2DB @ datablock ( : db_npcF) @ "djgroupie2";
PlayerData;
outfit = 0 @ "f 28 2 3 0 22 10 12 1";
aiProfile = "ai_djGroupieSit";
animSetName = npc_djgroupie3DB @ datablock ( : db_npcM) @ "djgroupie3";
PlayerData;
outfit = 0 @ "m 3 0 0 1 11 22 11 2";
aiProfile = "ai_generic";
shapeFile = npc_andrewDB @ datablock ( : PlayerBody) @ "projects/common/characters/NPC/andrew/npc_andrew.dts";
PlayerData;
animSetName = 0 @ "andrew";
aiProfile = "andrew";
