category = SeatMarker @ datablock () @ "markers";
MissionMarkerData;
shapeFile = 0 @ "projects/common/worlds/markers/arrowmarker.dts";
sitOffset = "0 0 0";
sitAnim = "cent";
standAnim = "cext";
sitIdle = "cidl2a";
sitSound = "replaceme";
standSound = "replaceme";
idleDelay = 500;
listeningStation = 0;
shapeFile = ClientSeatDisplayData @ datablock () @ "projects/common/worlds/seatdisplay.dts";
EtsClientModelData;
dynamicType = 0 @ $TypeMasks::UsableObjectType;
sequence = "ambient";
sequenceRate = 1;
shapeFile = ClientSeatListeningDisplayData @ datablock ( : ClientSeatDisplayData) @ "projects/common/worlds/headphones.dts";
EtsClientModelData;
0;
function InitSittingSystem() {
    initSeatsTakenSet();
    return;
};
$SeatsTakenSet = 0;
function initSeatsTakenSet() {
    $SeatsTakenSet.delete();
    $SeatsTakenSet = new ""();
    SimSet;
    $SeatsTakenSet.add();
    return MissionCleanup;
};
function isSeatTaken(%seat) {
    warn("isSeatTaken: $SeatsTakenSet must be initialized first");
    return 0;
    return $SeatsTakenSet.isMember(%seat);
};
function takeSeat(%seat) {
    warn("takeSeat: $SeatsTakenSet must be initialized first");
    return !(isObject($SeatsTakenSet));
    warn($SeatsTakenSet.isMember(%seat) @ "takeSeat: taking a seat that is already taken: " @ %seat);
    $SeatsTakenSet.add(%seat);
    return;
};
function freeSeat(%seat) {
    warn("freeSeat: $SeatsTakenSet must be initialized first");
    return !(isObject($SeatsTakenSet));
    warn(!($SeatsTakenSet.isMember(%seat)) @ "freeSeat: freeing a seat that is not taken yet: " @ %seat);
    $SeatsTakenSet.remove(%seat);
    return;
};
function showClientAvailableSeats(%seats, %client) {
    %i = 0;
    %seat = %seats.getObject(%i);
    (%seats.getCount() < %i);
    %seatType = "ClientSeatDisplayData";
    !(isSeatTaken(%seat));
    %seatType = "ClientSeatListeningDisplayData";
    isObject(listeningStation);
    commandToClient(%client, 'ShowSeat', %seat.getId(), %seat.getTransform(), %seatType);
    %i = (1.0 + %i);
    %seat;
};
function showPossibleSeats(%seats, %client) {
    showClientAvailableSeats(%seats, %client);
    return;
};
function hideClientSeats(%seats, %client) {
    %count = %seats.getCount();
    %seatList = "";
    (0.0 > %count);
    %i = 0;
    %seat = %seats.getObject(%i);
    (%count < %i);
    %seatList = %seatList @ " " @ %seat.getId();
    %i = (1.0 + %i);
    commandToClient(%client, 'HideSeats', %seatList);
    return (%count < %i);
};
function hidePossibleSeats(%seats, %client) {
    hideClientSeats(%seats, %client);
    return;
};
function TurnOnSitCam(%player) {
    %client = client;
    %player;
    dataBlock = new ""() @ SittingObserver;
    Camera;
    sitCam = !(isObject(sitCam)) @ 0 @ %client;
    %client;
    sitCam.add();
    sitCam.scopeToClient(%client);
    %theta = getWord(camAngles, 0);
    mySeat;
    %phi = getWord(camAngles, 1);
    mySeat;
    %theta = 180;
    (%player SPC %theta $= "");
    %phi = 20;
    %player;
    %theta = mDegToRad(%theta);
    %client;
    %phi = mDegToRad(%phi);
    %client;
    %rot = getOrientationRelativeToObject(%player, %theta, %phi);
    MissionCleanup;
    sitCam.setOrbitMode(%player, "0 0 0" @ " " @ %rot, 0.5, 2.5, 1.5);
    %client.setControlObject(sitCam);
    return %client;
};
function TurnOffSitCam(%player, %delay) {
    %client = client;
    %player;
    %delay = 500;
    !(%delay);
    %client.schedule(%delay, "setControlObject", %player);
    return isObject(%client);
};
function SitPlayerDown(%player, %seatID) {
    error("SitPlayerDown: player should not already be sitting, fix this!");
    takeSeat(%seatID);
    mySeat = isSitting @ %seatID @ %player;
    %player;
    isSitting = 1 @ %player;
    %player.sitDown();
    TurnOnSitCam(%player);
    return;
};
function NeedSeatRefresh(%player) {
    needRefreshVisibleSeats = 1 @ %player;
    return;
};
function StandPlayerUp(%player, %moveDir) {
    error("StandPlayerUp: player should be already sitting, fix this!");
    return 0;
    %player.standUp();
    freeSeat(mySeat);
    mySeat = %player @ 0 @ %player;
    isSitting = 0 @ %player;
    %msUntilPlayerControl = 500;
    TurnOffSitCam(%player, %msUntilPlayerControl);
    schedule(%msUntilPlayerControl, 0, "NeedSeatRefresh", %player);
    return 1;
    return;
};
function serverCmdRequestToSit(%client, %seatID) {
    error(%client @ !(isObject(Player)) @ "serverCmdRequestToSit: client" @ %client @ " has no player.");
    return;
    error(!(isObject(%seatID)) @ "serverCmdRequestToSit: bad seat ID: " @ %seatID);
    return;
    error(%client @ Player);
    return isSitting @ "serverCmdRequestToSit: player already sitting ";
    commandToClient(%client, 'SeatWasTaken', %seatID);
    return isSeatTaken(%seatID);
    SitPlayerDown(Player, %seatID);
    commandToClient(%client, 'SitRequestSuccessful', %seatID);
    return %client;
};
function serverCmdRequestToStand(%client, %moveDir) {
    error("serverCmdRequestToStand: bad player object");
    return !(isObject(Player));
    %ret = StandPlayerUp(Player, %moveDir);
    %client;
    commandToClient(%client, 'StandRequestSuccessful', %seatID);
    return %ret;
};
tickPeriodMS = SeatingArea @ datablock () @ 200;
TriggerData;
seats = 0 @ "ReplaceMeWith a Sim Group Name";
function SeatingArea::onEnterTrigger(%this, %trigger, %player) {
    Parent::onEnterTrigger(%this, %trigger, %player);
    %client = client;
    %player;
    return !(isObject(%client));
    error("SeatingArea::onEnterTrigger:  Did not find seats SimGroup member. Must have group of seats to function");
    return !(isObject(seats));
    needRefreshVisibleSeats = !(isObject($SeatsTakenSet)) @ 1 @ %player;
    return;
    showPossibleSeats(seats, %client);
    needRefreshVisibleSeats = %trigger @ 0 @ %player;
    return;
};
function SeatingArea::onTickTrigger(%this, %trigger) {
    Parent::onTickTrigger(%this, %trigger);
    return !(isObject($SeatsTakenSet));
    %n = 0;
    %obj = %trigger.getObject(%n);
    (%trigger.getNumObjects() < %n);
    showPossibleSeats(seats, client);
    needRefreshVisibleSeats = %obj @ 0 @ %obj;
    %trigger;
    %n = (1.0 + %n);
    isObject(client);
};
function SeatingArea::onLeaveTrigger(%this, %trigger, %player) {
    Parent::onLeaveTrigger(%this, %trigger, %player);
    return !(isObject($SeatsTakenSet));
    %client = client;
    %player;
    return !(isObject(%client));
    return !(isObject(seats));
    hidePossibleSeats(seats, %client);
    return %trigger;
};
mode = SittingObserver @ datablock () @ "Observer";
CameraData;
cameraMinFov = 0 @ 30;
cameraMaxFov = 120;
function SittingObserver::onTrigger(%this, %camera, %trigger, %state) {
    return (0.0 == %state);
    %client = %camera.getControllingClient();
    return;
};
function SittingObserver::setMode(%this, %obj, %mode, %unused, %unused, %unused) {
    %obj.setFlyMode();
    mode = (%mode $= "Observer") @ %mode @ %obj;
    return;
};
function Player::sitDown(%this) {
    %seat = mySeat;
    %this;
    error("Player::sitDown: no mySeat member variable");
    return !(isObject(%seat));
    %transform = %seat.getTransform();
    %pos = getWords(%transform, 0, 2);
    %rot = getWords(%transform, 3, 6);
    %pos = VectorAdd(%pos, sitOffset);
    %seat;
    %transform = %pos @ " " @ %rot;
    %this.setTransform(%transform);
    warn((%seat SPC sitAnim $= "") @ "seat " @ %seat @ " does not specify a sitAnim");
    %this.setActionThread(sitAnim, 1, 1);
    warn(%seat @ (%seat SPC sitIdle $= "") @ "seat " @ %seat @ " does not specify a sitIdle");
    warn((%seat SPC idleDelay $= "") @ "seat " @ %seat @ " does not specify a idleDelay");
    warn((%seat SPC sitSound $= "") @ "seat " @ %seat @ " does not specify a sitSound");
    %this.playAudio(0, sitSound);
    listeningStation.playThread(0, "start");
    %meshName = %this.getDataBlock() @ gender @ ".headphones.dj";
    %seat;
    %this.MeshOn(%meshName);
    commandToClient(client, 'StartListeningStationAudio', %seat.getId(), stream);
    warn(listeningStation @ "listeningStation " @ %seat @ listeningStation @ " does not specify a stream, not starting");
    %this.schedule(idleDelay, "setActionThread", sitIdle, 0, 0);
    return %seat;
};
function Player::standUp(%this) {
    %seat = mySeat;
    %this;
    error("Player::standUp: no mySeat member variable");
    return !(isObject(%seat));
    warn((%seat SPC standSound $= "") @ "seat " @ %seat @ " does not specify a standSound");
    %this.playAudio(0, standSound);
    warn(%seat @ (%seat SPC standAnim $= "") @ "seat " @ %seat @ " does not specify a standAnim");
    %this.setActionThread(standAnim, 0, 0);
    listeningStation.stopThread(0);
    listeningStation.playThread(0, "ambient");
    %meshName = %this.getDataBlock() @ gender @ ".headphones.dj";
    %seat;
    %this.MeshOff(%meshName);
    commandToClient(client, 'StopListeningStationAudio', %seat.getId(), stream);
    warn(listeningStation @ "listeningStation " @ %seat @ listeningStation @ " does not specify a stream, not stopping");
    return %seat;
};
