$Gui::fontCacheDirectory = ExpandFilename("./cache");
$Gui::clipboardFile = ExpandFilename("./cache/clipboard.gui");
tab = GuiDefaultProfile @ new () @ 0;
GuiControlProfile;
canKeyFocus = !(isObject()) @ 0 @ 0;
GuiDefaultProfile;
hasBitmapArray = 0;
mouseOverSelected = 0;
opaque = 0;
fillColor = ($Platform $= "macos") @ "211 211 211" @ "192 192 192";
fillColorHL = ($Platform $= "macos") @ "244 244 244" @ "220 220 220";
fillColorNA = ($Platform $= "macos") @ "244 244 244" @ "220 220 220";
border = 0;
borderColor = "0 0 0";
borderColorHL = "128 128 128";
borderColorNA = "64 64 64";
fontType = "Arial";
fontSize = 14;
fontColor = "0 0 0";
fontColorHL = "32 100 100";
fontColorNA = "0 0 0";
fontColorSEL = "200 200 200";
drawShadow = 0;
bitmap = ($Platform $= "macos") @ "./osxWindow" @ "./darkWindow";
bitmapBase = "";
textOffset = "0 0";
hlOffset = "0 0";
hlInset = "2 2";
modal = 1;
justify = "left";
autoSizeWidth = 0;
autoSizeHeight = 0;
returnTab = 0;
numbersOnly = 0;
cursorColor = "0 0 0 255";
acceptMouseMove = 1;
acceptLeftMouse = 1;
acceptRightMouse = 1;
acceptMouseWheel = 1;
soundButtonDown = "";
soundButtonOver = "";
tab = GuiInputCtrlProfile @ new () @ 1;
GuiControlProfile;
canKeyFocus = !(isObject()) @ 0 @ 1;
GuiInputCtrlProfile;
new ();
opaque = GuiSolidDefaultProfile @ new () @ 1;
GuiControlProfile;
border = !(isObject()) @ 0 @ 0;
GuiSolidDefaultProfile;
fillColor = (GuiDialogProfile SPC $Platform $= "macos") @ "211 211 211" @ "192 192 192";
GuiControlProfile;
0;
opaque = GuiWindowProfile @ new () @ 1;
GuiControlProfile;
border = !(isObject()) @ 0 @ 2;
GuiWindowProfile;
fillColor = (!(isObject()) SPC $Platform $= "macos") @ "211 211 211" @ "192 192 192";
GuiDialogProfile;
fillColorHL = ($Platform $= "macos") @ "190 255 255" @ "64 150 150";
fillColorNA = ($Platform $= "macos") @ "255 255 255" @ "150 150 150";
fontColor = ($Platform $= "macos") @ "0 0 0" @ "255 255 255";
fontColorHL = ($Platform $= "macos") @ "200 200 200" @ "0 0 0";
text = "GuiWindowCtrl test";
bitmap = ($Platform $= "macos") @ "./osxWindow" @ "./darkWindow";
textOffset = ($Platform $= "macos") @ "5 5" @ "6 6";
hasBitmapArray = 1;
justify = ($Platform $= "macos") @ "center" @ "left";
opaque = GuiToolWindowProfile @ new () @ 1;
GuiControlProfile;
border = !(isObject()) @ 0 @ 2;
GuiToolWindowProfile;
fillColor = "192 192 192";
fillColorHL = "64 150 150";
fillColorNA = "150 150 150";
fontColor = "255 255 255";
fontColorHL = "0 0 0";
bitmap = "./torqueToolWindow";
textOffset = "6 6";
opaque = EditorToolButtonProfile @ new () @ 1;
GuiControlProfile;
border = !(isObject()) @ 0 @ 2;
EditorToolButtonProfile;
opaque = GuiContentProfile @ new () @ 1;
GuiControlProfile;
fillColor = !(isObject()) @ 0 @ "255 255 255";
GuiContentProfile;
modal = GuiControlProfile @ new "GuiModelessDialogProfile"() @ 0;
0;
!(isObject());
opaque = GuiButtonProfile @ new () @ 1;
GuiControlProfile;
border = !(isObject()) @ 0 @ 1;
GuiButtonProfile;
drawShadow = GuiModelessDialogProfile @ 0;
fontColor = "0 0 0";
fontColorHL = "32 100 100";
fixedExtent = 1;
justify = "center";
canKeyFocus = 0;
fontColorHL = GuiBorderButtonProfile @ new () @ "0 0 0";
GuiControlProfile;
0;
opaque = GuiMenuBarProfile @ new () @ 1;
GuiControlProfile;
fillColor = (0 SPC $Platform $= "macos") @ "211 211 211" @ "192 192 192";
!(isObject());
fillColorHL = !(isObject()) @ GuiMenuBarProfile @ "0 0 96";
GuiBorderButtonProfile;
border = 4;
fontColor = "0 0 0";
fontColorHL = "255 255 255";
fontColorNA = "128 128 128";
fixedExtent = 1;
justify = "center";
canKeyFocus = 0;
mouseOverSelected = 1;
bitmap = ($Platform $= "macos") @ "./osxMenu" @ "./torqueMenu";
hasBitmapArray = 1;
fontSize = GuiButtonSmProfile @ new ( : GuiButtonProfile) @ 14;
GuiControlProfile;
0;
fontSize = GuiRadioProfile @ new () @ 14;
GuiControlProfile;
fillColor = !(isObject()) @ 0 @ "232 232 232";
GuiRadioProfile;
fontColorHL = GuiButtonSmProfile @ !(isObject()) @ "32 100 100";
fixedExtent = 1;
bitmap = ($Platform $= "macos") @ "./osxRadio" @ "./torqueRadio";
hasBitmapArray = 1;
opaque = GuiScrollProfile @ new () @ 1;
GuiControlProfile;
fillColor = !(isObject()) @ 0 @ "255 255 255";
GuiScrollProfile;
border = 3;
borderThickness = 2;
borderColor = "0 0 0";
bitmap = ($Platform $= "macos") @ "./osxScroll" @ "./darkScroll";
hasBitmapArray = 1;
bitmap = GuiSliderProfile @ new () @ "./darkSlider";
GuiControlProfile;
0;
fontColor = GuiTextProfile @ new () @ "0 0 0";
GuiControlProfile;
fontColorLink = !(isObject()) @ 0 @ "255 96 96";
GuiTextProfile;
fontColorLinkHL = GuiSliderProfile @ !(isObject()) @ "0 0 255";
autoSizeWidth = 1;
autoSizeHeight = 1;
fontType = EditorTextProfile @ new () @ "Arial Bold";
GuiControlProfile;
fontColor = !(isObject()) @ 0 @ "0 0 0";
EditorTextProfile;
autoSizeWidth = 1;
autoSizeHeight = 1;
fontType = EditorTextProfileWhite @ new () @ "Arial Bold";
GuiControlProfile;
fontColor = !(isObject()) @ 0 @ "255 255 255";
EditorTextProfileWhite;
autoSizeWidth = 1;
autoSizeHeight = 1;
fontSize = GuiMediumTextProfile @ new ( : GuiTextProfile) @ 24;
GuiControlProfile;
0;
fontSize = GuiBigTextProfile @ new ( : GuiTextProfile) @ 36;
GuiControlProfile;
0;
justify = GuiCenterTextProfile @ new ( : GuiTextProfile) @ "center";
GuiControlProfile;
0;
canKeyFocus = MissionEditorProfile @ new () @ 1;
GuiControlProfile;
0;
opaque = EditorScrollProfile @ new () @ 1;
GuiControlProfile;
fillColor = !(isObject()) @ 0 @ "192 192 192 192";
EditorScrollProfile;
border = MissionEditorProfile @ !(isObject()) @ 3;
!(isObject());
borderThickness = !(isObject()) @ GuiCenterTextProfile @ 2;
GuiBigTextProfile;
borderColor = GuiMediumTextProfile @ !(isObject()) @ "0 0 0";
bitmap = "./darkScroll";
hasBitmapArray = 1;
opaque = GuiTextEditProfile @ new () @ 1;
GuiControlProfile;
fillColor = !(isObject()) @ 0 @ "255 255 255";
GuiTextEditProfile;
fillColorHL = "128 128 128";
border = 3;
borderThickness = 2;
borderColor = "0 0 0";
fontColor = "0 0 0";
fontColorHL = "255 255 255";
fontColorNA = "128 128 128";
textOffset = "0 2";
autoSizeWidth = 0;
autoSizeHeight = 1;
tab = 1;
canKeyFocus = 1;
drawShadow = 0;
opaque = GuiControlListPopupProfile @ new () @ 1;
GuiControlProfile;
fillColor = !(isObject()) @ 0 @ "255 255 255";
GuiControlListPopupProfile;
fillColorHL = "128 128 128";
border = 1;
borderColor = "0 0 0";
fontColor = "0 0 0";
fontColorHL = "255 255 255";
fontColorNA = "128 128 128";
textOffset = "0 2";
autoSizeWidth = 0;
autoSizeHeight = 1;
tab = 1;
canKeyFocus = 1;
bitmap = ($Platform $= "macos") @ "./osxScroll" @ "./darkScroll";
hasBitmapArray = 1;
fontColorHL = GuiTextArrayProfile @ new ( : GuiTextProfile) @ "32 100 100";
GuiControlProfile;
fillColorHL = !(isObject()) @ 0 @ "200 200 200";
GuiTextArrayProfile;
new ( : GuiTextProfile);
fontSize = GuiTreeViewProfile @ new () @ 13;
GuiControlProfile;
fontColor = !(isObject()) @ 0 @ "0 0 0";
GuiTreeViewProfile;
fontColorHL = GuiControlProfile @ GuiTextListProfile @ "64 150 150";
0;
canKeyFocus = GuiTextListProfile @ !(isObject()) @ 1;
autoSizeHeight = 1;
fontColorSEL = "250 250 250";
fillColorHL = "0 60 150";
fontColorNA = "240 240 240";
bitmap = "./shll_treeView";
opaque = GuiCheckBoxProfile @ new () @ 0;
GuiControlProfile;
fillColor = !(isObject()) @ 0 @ "232 232 232";
GuiCheckBoxProfile;
border = 0;
borderColor = "0 0 0";
fontSize = 14;
fontColor = "0 0 0";
fontColorHL = "32 100 100";
fixedExtent = 1;
justify = "left";
bitmap = ($Platform $= "macos") @ "./osxCheck" @ "./torqueCheck";
hasBitmapArray = 1;
opaque = GuiPopUpMenuProfile @ new () @ 1;
GuiControlProfile;
mouseOverSelected = !(isObject()) @ 0 @ 1;
GuiPopUpMenuProfile;
border = 4;
borderThickness = 2;
borderColor = "0 0 0";
fontSize = 14;
fontColor = "0 0 0";
fontColorHL = "32 100 100";
fontColorSEL = "32 100 100";
fixedExtent = 1;
justify = "center";
bitmap = ($Platform $= "macos") @ "./osxScroll" @ "./darkScroll";
hasBitmapArray = 1;
opaque = GuiEditorClassProfile @ new () @ 1;
GuiControlProfile;
fillColor = !(isObject()) @ 0 @ "232 232 232";
GuiEditorClassProfile;
border = 1;
borderColor = "0 0 0";
borderColorHL = "127 127 127";
fontColor = "0 0 0";
fontColorHL = "32 100 100";
fixedExtent = 1;
justify = "center";
bitmap = ($Platform $= "macos") @ "./osxScroll" @ "./darkScroll";
hasBitmapArray = 1;
fontColor = GuiControlProfile @ new "LoadTextProfile"() @ "66 219 234";
0;
autoSizeWidth = LoadTextProfile @ !(isObject()) @ 1;
autoSizeHeight = 1;
fontColorLink = GuiControlProfile @ new "GuiMLTextProfile"() @ "255  96  96";
0;
fontColorLinkHL = GuiMLTextProfile @ !(isObject()) @ "0     0 255";
fontColorHL = "150 200 255 200";
fillColorHL = "255 200 230  50";
canKeyFocus = 1;
canKeyFocus = GuiMLTextModelessProfile @ new ( : GuiMLTextProfile) @ 0;
GuiControlProfile;
modal = 0 @ 0;
fontColorLink = GuiControlProfile @ new "GuiMLTextNoSelectProfile"() @ "255 96 96";
0;
fontColorLinkHL = GuiMLTextNoSelectProfile @ !(isObject()) @ "0 0 255";
modal = 0;
fontColorLink = GuiMLTextEditProfile @ new () @ "255 96 96";
GuiControlProfile;
fontColorLinkHL = !(isObject()) @ 0 @ "0 0 255";
GuiMLTextEditProfile;
fillColor = "255 255 255";
fillColorHL = "128 128 128";
fontColor = "0 0 0";
fontColorHL = "255 255 255";
fontColorNA = "128 128 128";
autoSizeWidth = 1;
autoSizeHeight = 1;
tab = 1;
canKeyFocus = 1;
fontType = (new "GuiConsoleProfile"() SPC $Platform $= "macos") @ "Courier New" @ "Lucida Console";
GuiControlProfile;
fontSize = (0 SPC $Platform $= "macos") @ 14 @ 12;
!(isObject());
fontColor = GuiConsoleProfile @ "0 0 0";
fontColorHL = "130 130 130";
fontColorNA = "255 0 0";
fontColors = "  0   0   0" @ 5;
fontColors = "150 150 150" @ 6;
fontColors = "200 150  50" @ 7;
fontColors = "255   0   0" @ 8;
fontColors = "255   0 255" @ 9;
opaque = GuiControlProfile @ new "GuiProgressProfile"() @ 0;
0;
fillColor = GuiProgressProfile @ !(isObject()) @ "44 152 162 100";
border = 1;
borderColor = "78 88 120";
fontColor = GuiControlProfile @ new "GuiProgressTextProfile"() @ "0 0 0";
0;
justify = GuiProgressTextProfile @ !(isObject()) @ "center";
opaque = GuiInspectorFieldProfile @ new () @ 0;
GuiControlProfile;
fillColor = !(isObject()) @ 0 @ "255 255 255";
GuiInspectorFieldProfile;
fillColorHL = "128 128 128";
fillColorNA = "244 244 244";
border = 0;
borderColor = "190 190 190";
borderColorHL = "156 156 156";
borderColorNA = "64 64 64";
bevelColorHL = "255 255 255";
bevelColorLL = "0 0 0";
fontType = "Arial";
fontSize = 16;
fontColor = "32 32 32";
fontColorHL = "32 100 100";
fontColorNA = "0 0 0";
tab = 1;
canKeyFocus = 1;
border = GuiInspectorBackgroundProfile @ new ( : GuiInspectorFieldProfile) @ 5;
GuiControlProfile;
0;
new ( : GuiInspectorFieldProfile);
opaque = GuiControlProfile @ new "GuiInspectorTextEditProfile"() @ 0;
0;
border = GuiInspectorTextEditProfile @ !(isObject()) @ 0;
GuiInspectorDynamicFieldProfile;
tab = 0 @ GuiControlProfile @ 1;
!(isObject());
canKeyFocus = !(isObject()) @ GuiInspectorDynamicFieldProfile @ 1;
GuiInspectorBackgroundProfile;
fontType = "Arial";
fontSize = 16;
fontColor = "32 32 32";
fontColorHL = "32 100 100";
fontColorNA = "0 0 0";
mouseOverSelected = InspectorTypeEnumProfile @ new ( : GuiInspectorFieldProfile) @ 1;
GuiControlProfile;
bitmap = (0 SPC $Platform $= "macos") @ "./osxScroll" @ "./darkScroll";
!(isObject());
hasBitmapArray = InspectorTypeEnumProfile @ 1;
opaque = 1;
border = 1;
bitmap = (new ( : GuiInspectorFieldProfile) SPC $Platform $= "macos") @ "./osxCheck" @ "./torqueCheck";
InspectorTypeCheckboxProfile;
hasBitmapArray = 0 @ GuiControlProfile @ 1;
!(isObject());
opaque = InspectorTypeCheckboxProfile @ 0;
border = 0;
opaque = GuiInspectorTypeFileNameProfile @ new () @ 0;
GuiControlProfile;
border = !(isObject()) @ 0 @ 5;
GuiInspectorTypeFileNameProfile;
tab = 1;
canKeyFocus = 1;
fontType = "Arial";
fontSize = 16;
justify = "center";
fontColor = "32 32 32";
fontColorHL = "32 100 100";
fontColorNA = "0 0 0";
fillColor = "255 255 255";
fillColorHL = "128 128 128";
fillColorNA = "244 244 244";
borderColor = "190 190 190";
borderColorHL = "156 156 156";
borderColorNA = "64 64 64";
bitmap = GuiMessageWindowProfile @ new ( : GuiWindowProfile) @ "./msgWindow";
GuiControlProfile;
fillColor = !(isObject()) @ 0 @ "  0   0   0 179";
GuiMessageWindowProfile;
fontColor = "255 255 255 255";
textOffset = "12 12";
canKeyFocus = 1;
stretchBitmaps = 0;
fontColor = GuiMessageTextProfile @ new ( : GuiTextProfile) @ "255 255 255 255";
GuiControlProfile;
fontColorGL = !(isObject()) @ 0 @ "255 255 255 128";
GuiMessageTextProfile;
fontColorLink = "255 106 196 255";
bitmap = GuiVarWidthButtonProfile @ new ( : GuiDefaultProfile) @ "./varWidthButton";
GuiControlProfile;
justify = !(isObject()) @ 0 @ "center";
GuiVarWidthButtonProfile;
borderColorHL = "170 170 170 255";
hlOffset = "0 0";
hlInset = "4 2";
fontColor = "230 100 255 255";
fontColors = "255 147 248 255" @ 6;
fontColors = "147   0 137 255" @ 7;
fontColors = "100 100 100 255" @ 8;
drawShadow = 0;
canKeyFocus = GuiFocusableVWButtonProfile @ new ( : GuiVarWidthButtonProfile) @ 1;
GuiControlProfile;
tab = !(isObject()) @ 0 @ 1;
GuiFocusableVWButtonProfile;
hotSpot = DefaultCursor @ new () @ "1 1";
GuiCursor;
bitmapName = 0 @ "./CUR_3darrow";
