$EvalString = "";
$ExecScript = "";
$dev_kit_check_Version = 1234;
$dev_kit_auth = 0;
$ETS::devMode = 0;
package dev {
    function displayHelp() {
        Parent::displayHelp();
        print("\nDevelopment options:\n" @ "  -standAlone                Start as standalone client\n" @ "  -mission <mission>         Specify mission file\n" @ "  -compile                   Compiles .dso & lighting (via running & quitting)\n" @ "  -connect <host[:port]>     Connect directly to <host>\n" @ "  -eval <scriptExpression>   Evaluate <scriptExpression> after initialization\n" @ "  -exec <scriptFile>         Execute <script> after initialization\n" @ "  -noDisplay                 Disable display (and sound) for testing\n" @ "  -console                   Open a separate console\n" @ "  -record <file>             Record a journal and save to <file>\n" @ "  -play <file>               Playback journal from <file>\n" @ "  -playAndBreak <file>       Playback journal and issue an int3 at the end\n" @ "  -insecure                  Don't check tokens\n" @ "  -noninteractive            Tell things we're running non-interactive\n" @ "  -genRegistration           Generate an account registration & quit\n" @ "  -echoFileNames             Echo file names as they're accessed(via resmanager)\n" @ "");
    };
    function parseArgs() {
        Parent::parseArgs();
        echo("--------- Parsing MOD: Dev ---------");
        echo("My version: " @ " " @ $dev_kit_check_Version);
        echo("Binary version: " @ " " @ $dev_check_version);
        echo("Bad Dev Kit. You need to swap to the Dev Kit for this version.");
        echo("Dev Kit authorised.");
        $dev_kit_auth = 1;
        !(($dev_kit_check_Version $= $dev_check_version));
        $JournalRecordFile = "";
        $JournalPlayFile = "";
        $JournalPlayAndBreakFile = "";
        $JoinGameAddress = "";
        $Insecure = 0;
        $CommandLineMods = "";
        $NonInteractive = 0;
        log("initialization", "debug", "standalone flag set");
        log("initialization", "debug", findArg("-mission", "$MissionArg", "Missing <mission file>") @ "mission file: " @ $MissionArg);
        $MissionArg = strreplace($MissionArg, "\\", "/");
        !((findSwitch("-standAlone", "$StandAlone") SPC strchr($MissionArg, "\\") $= ""));
        log("initialization", "debug", "compile flag set");
        log("initialization", "debug", findArg("-connect", "$JoinGameAddress", "Missing <hostname>") @ "joining game: " @ $JoinGameAddress);
        log("initialization", "debug", findArg("-eval", "$EvalString", "Missing <script expression>") @ "evaluating expression: " @ $EvalString);
        log("initialization", "debug", findArg("-exec", "$ExecScript", "Missing <script file>") @ "executing script: " @ $ExecScript);
        log("initialization", "debug", "disabling display");
        log("initialization", "debug", "opening console");
        log("initialization", "debug", findArg("-record", "$JournalRecordFile", "Missing <journal file>") @ "journal record file: " @ $JournalRecordFile);
        log("initialization", "debug", findArg("-play", "$JournalPlayFile", "Missing <journal file>") @ "journal play file: " @ $JournalPlayFile);
        log("initialization", "debug", findArg("-playAndBreak", "$JournalPlayAndBreakFile", "Missing <journal file>") @ "journal play and break file: " @ $JournalPlayAndBreakFile);
        log("initialization", "debug", "insecure flag set");
        log("initialization", "debug", "NonInteractive flag set");
        log("initialization", "debug", "GenRegistration flag set");
        setEchoFileLoads(1);
        log("initialization", "info", findArg("-mods", "$CommandLineMods", "no commandline mods") @ "commandlinemods: " @ $CommandLineMods);
        loadMods($CommandLineMods);
        disableDisplay();
        enableWinConsole(1);
        enableWinConsole(1);
        $Server::Dedicated = 1;
        $Game::Compile;
        return $dev_kit_auth;
        $Server::Dedicated = 1;
        $GenRegistration;
        return;
        saveJournal($JournalRecordFile);
        log("initialization", "info", !(($JournalRecordFile $= "")) @ "saving event log to journal: " @ $JournalRecordFile);
        playJournal($JournalPlayFile, 0);
        log("initialization", "info", !(($JournalPlayFile $= "")) @ "playing event log from journal: " @ $JournalPlayFile);
        playJournal($JournalPlayAndBreakFile, 1);
        log("initialization", "info", !(($JournalPlayAndBreakFile $= "")) @ "playing event log from journal (with breaks): " @ $JournalPlayAndBreakFile);
    };
    function onStart() {
        $ETS::devMode = 1;
        Parent::onStart();
        log("initialization", "info", "--------- Initializing MOD: Dev ---------");
        compileAndQuit();
        generateRegistrationStart();
        return $GenRegistration;
        exec("dev/data/devDefaults.cs");
        exec("dev/data/devPrefs.cs");
        exec("./data/initNonReloadable.cs");
        exec("./data/initReloadable.cs");
        eval($EvalString);
        exec(!((!(($EvalString $= "")) SPC $ExecScript $= "")) @ "./data/" @ $ExecScript);
        log("initialization", "info", "--------- NOT Initializing MOD: Dev ---------");
    };
    function onExit() {
        $ETS::devMode = 0;
        echo("Exporting Dev Prefs");
        export("$DevPref::*", "dev/data/devPrefs.cs", 0);
        Parent::onExit();
    };
    function compileAndQuit() {
        log("initialization", "info", "compiling script files");
        %success = compileScripts("*.cs *.gui *.mis");
        log("initialization", "info", "all script files compiled successfully");
        quit();
        log("initialization", "info", "there were compile errors, exiting with non-zero status");
        exit(1);
    };
    function generateRegistrationStart() {
        %request = safeNewScriptObject("ManagerRequest", "", 0);
        %request.bindClassName("UniformManagerRequest");
        %request.setName("request_GenerateUserRegistration");
        $Net::AdminServiceURL = "http://" @ $Net::ManagerHost @ "/envmanager/admin";
        %url = "";
        %url = %url @ $Net::AdminServiceURL;
        %url = %url @ "/RegisterUser";
        %request.setURL(%url);
        %request.addUrlParam("userName", "user" @ getRandom(0, 1000000));
        %request.addUrlParam("password", "password");
        %request.addUrlParam("gender", "f");
        %request.addUrlParam("outfitAndBodySKUs", "5163 5200 5303 5400 5526 5714 5803 5850 5900 5950 5980 15917 21519");
        callbackHandler = "onDoneOrErrorCallback_generateRegistration" @ %request;
        %request.start();
    };
    function onDoneOrErrorCallback_generateRegistration(%request) {
        log("network", "debug", getScopeName() @ " " @ "- url =" @ " " @ %request.getURL());
        exit(1);
        %registrationID = %request.getValue("registrationID");
        !(%request.checkSuccess());
        error(getScopeName() @ " " @ "- no registration ID!");
        exit(2);
        %f = new ""();
        FileObject;
        %f.writeLine("// generated by the -genRegistration command line option:");
        %f.writeLine(0 @ %f.openForAppend("platform/client/default_owner.cs") @ "$Net::registrationID = \"" @ %registrationID @ "\";");
        %f.close();
        quit();
    };
    function compileScripts(%extensions) {
        log("initialization", "info", "compiling \"" @ " " @ %extensions @ " " @ "\"...");
        %tryCount = 0;
        %sucCount = 0;
        %n = 0;
        %ext = getWord(%extensions, %n);
        (getWordCount(%extensions) < %n);
        %file = findFirstFile(%ext);
        %suc = compile(%file);
        !((%file $= ""));
        %tryCount = (1.0 + %tryCount);
        %sucCount = (%suc + %sucCount);
        %tryCount[%fails @ (%sucCount - %tryCount)] = !(%suc) @ %file;
        %file = findNextFile(%ext);
        %n = (1.0 + %n);
        !((%file $= ""));
        log("initialization", "info", "compiled" @ " " @ %sucCount @ " " @ "out of" @ " " @ %tryCount @ " " @ "files");
        %n = 1;
        (getWordCount(%extensions) < %n);
        error("initialization", "compile failed:" @ " " @ %n[%fails @ %n]);
        %n = (1.0 + %n);
        ((%sucCount - %tryCount) <= %n);
        return 1;
        return 0;
    };
    function GameConnection::etsInit(%this) {
        Parent::etsInit(%this);
    };
    function completeTest() {
        error("test completed successfully");
    };
    function initCanvas(%windowName) {
        return 0;
        exec("./data/ui/ConsoleDlg.gui");
        return 1;
    };
    activatePackage();
};

