function ValidateRequest::getInfoString(%this) {
    return %this @ connection @ " " @ %this @ name @ "]";
};
function ValidateRequest::onError(%this, %errorNum, %errorName) {
    name.remove();
    connection.connectCallback("");
    connection.connectCallback("CR_TOKEN");
    return %this;
};
function ValidateRequest::onDone(%this) {
    %status = findRequestStatus(%this);
    log("login", "info", %this.getInfoString() @ " " @ "ValidateRequest::onDone:" @ " " @ %status);
    name.remove();
    connection.connectCallback("CR_TOKEN");
    return %this;
    roles = %this.getValue("permissions") @ %this;
    connection.connectCallback("CR_SERVERFULL");
    return %this;
    connection.connectCallback("");
    return %this;
};
function ValidateRequest::isTooFullForPlayer(%this, %roles) {
    %ret = 0;
    %bypassing = "";
    %bypassing = "but bypassing";
    roles::maskHasRoleString(mInt(%roles), "celeb");
    %ret = 1;
    roles::maskHasRoleString(mInt(%roles), "press");
    log("login", "warn", %this @ registeredName);
    return %ret;
};
function sendJoinRequest(%callback, %name, %token) {
    echo(getScopeName() @ " " @ "- invalid manager host - faking onJoinResponse.");
    %callback.onJoinResponse(0);
    return !(haveValidManagerHost());
    className = ManagerRequest @ new ""() @ "JoinRequest";
    0;
    %joinRequest = ;
    %joinRequest.add();
    name = MissionCleanup @ %name @ %joinRequest;
    isObject();
    inventoryCount = MissionCleanup @ 0 @ %joinRequest;
    callback = %callback @ %joinRequest;
    %url = $Net::BaseURL @ "?cmd=join" @ "&port=" @ urlEncode($Net::BoundPort) @ "&user=" @ urlEncode(%name) @ "&token=" @ urlEncode(%token);
    log("login", "debug", "sendJoinRequest: " @ %url);
    %joinRequest.setURL(%url);
    %joinRequest.start();
    return %joinRequest;
};
function JoinRequest::onError(%this, %errorNum, %errorName) {
    log("login", "error", %this @ name @ " " @ "failed due to " @ " " @ %errorNum @ " " @ "-" @ " " @ %errorName);
    %this.schedule(0);
    return delete;
};
function JoinRequest::onDone(%this) {
    %status = findRequestStatus(%this);
    log("login", "info", %this @ name @ " " @ "complete");
    buddyCount = "JoinRequest for" @ " " @ %this.getValue("numFavorites") @ %this;
    %n = 1;
    buddy = %this @ %this.getValue((buddyCount <= %n) @ "favorite" @ %n) @ %n @ %this;
    %n = (1.0 + %n);
    ignoreCount = (buddyCount <= %n) @ %this.getValue("numIgnores") @ %this;
    %this;
    %n = 1;
    ignore = %this @ %this.getValue((ignoreCount <= %n) @ "ignore" @ %n) @ %n @ %this;
    %n = (1.0 + %n);
    onBuddyCount = (ignoreCount <= %n) @ %this.getValue("numOnFavorites") @ %this;
    %this;
    %n = 1;
    onBuddy = %this @ %this.getValue((onBuddyCount <= %n) @ "onFavorite" @ %n) @ %n @ %this;
    %n = (1.0 + %n);
    onIgnoreCount = (onBuddyCount <= %n) @ %this.getValue("numOnIgnores") @ %this;
    %this;
    %n = 1;
    onIgnore = %this @ %this.getValue((onIgnoreCount <= %n) @ "onIgnore" @ %n) @ %n @ %this;
    %n = (1.0 + %n);
    registeredName = (onIgnoreCount <= %n) @ %this.getValue("registered_user") @ %this;
    %this;
    curOutfitSkus = %this.getValue("cur_outfit_skus_m") @ "m" @ %this;
    log("wardrobe", "info", "curOutfitSkus returned in ValidateRequest::onLine, curOutfitSkus[\"m\"] = " @ "m" @ %this @ curOutfitSkus);
    curOutfitSkus = %this.getValue("cur_outfit_skus_f") @ "f" @ %this;
    log("wardrobe", "info", "curOutfitSkus returned in ValidateRequest::onLine, curOutfitSkus[\"f\"] = " @ "f" @ %this @ curOutfitSkus);
    bodyAttrs = %this.getValue("bodyattrs_m") @ "m" @ %this;
    log("wardrobe", "info", "bodyAttrs_m returned in ValidateRequest::onLine, bodyAttrs[\"m\"] = " @ "m" @ %this @ bodyAttrs);
    bodyAttrs = %this.getValue("bodyattrs_f") @ "f" @ %this;
    log("wardrobe", "info", "bodyAttrs_f returned in ValidateRequest::onLine, bodyAttrs[\"f\"] = " @ "f" @ %this @ bodyAttrs);
    callback.onJoinResponse(%this);
    %trgPlayer = teleportTarget.getNorm();
    %this;
    %me = Player;
    callback;
    log("communication", "error", "invalid player object attached to connection during join");
    return !(isObject(%me));
    log("communication", "error", "teleport target doesn't exist in during join");
    return !(isObject(%trgPlayer));
    serverSideTeleportToPlayer2(%me, %trgPlayer);
    %this.schedule(0);
    return delete;
};
function DropRequest::onError(%this, %errorNum, %errorName) {
    log("drop", "error", "DropRequest for " @ %this @ name @ " failed due to " @ %errorNum @ " - " @ %errorName);
    %this.schedule(0);
    return delete;
};
function DropRequest::onDone(%this) {
    %status = findRequestStatus(%this);
    log("login", "info", "DropRequest::onDone:" @ " " @ %status);
    client.delete("CLIENT_REQUEST");
    %this.schedule(0);
    return delete;
};
function serverCmdDisconnectRequest(%client) {
    %client.postClientDrop(0, "");
    return;
};
function GameConnection::onConnectRequest(%this, %netAddress, %name, %token, %unused, %unused) {
    log("login", "info", "GameConnection::onConnectRequest: " @ %netAddress @ " " @ %this @ " " @ %name @ " " @ "token" @ " " @ %token);
    return $StandAlone;
    %client = %name.get();
    ClientDict;
    %this.connectCallback("CR_TOKEN");
    return isObject(%client);
    log("login", "warn", "incompatible assets:" @ " " @ %name);
    %this.connectCallback("CHR_CLASSCRCROOTDIRVAL");
    return !((!($Insecure) SPC %this.getCrcRootDirVal() $= $Server::crcRootDirVal));
    log("login", "error", "invalid token:" @ " " @ %name);
    %this.connectCallback("CHR_INVALID_CHALLENGE_PACKET");
    return (!($Insecure) SPC %token $= "");
    %timeout = %name.get();
    PendingValidate;
    %curSimTime = getSimTime();
    log("login", "debug", "GameConnection::onConnectRequest timeout for" @ " " @ %name @ " " @ %timeout);
    log("login", "warn", "GameConnection::onConnectRequest ignoring repeat request from" @ " " @ %netAddress @ " " @ %name);
    return (%timeout < %curSimTime);
    %timeout = (25000.0 + %curSimTime);
    log("login", "debug", "adding validate timeout" @ " " @ %timeout @ " " @ "for" @ " " @ %name);
    %name.put((25000.0 + %curSimTime));
    className = ManagerRequest @ new ""() @ "ValidateRequest";
    0;
    %validateRequest = PendingValidate;
    %validateRequest.add();
    name = MissionCleanup @ %name @ %validateRequest;
    isObject();
    connection = MissionCleanup @ %this @ %validateRequest;
    skip = 0 @ %validateRequest;
    %url = $Net::BaseURL @ "?cmd=validate";
    %bindPort = "&port=" @ urlEncode($Net::BoundPort);
    %userValue = "&user=" @ urlEncode(%name);
    %tokenValue = "&token=" @ urlEncode(%token);
    %url = %url @ %bindPort @ %userValue @ %tokenValue;
    %validateRequest.setURL(%url);
    ValidateRequest = %validateRequest @ %this;
    %validateRequest.onError();
    %validateRequest.start();
    log("login", "info", %this @ getDebugString(ValidateRequest));
    return "GameConnection::onConnectRequest: " @ " " @ getDebugString(%this) @ " ";
};
function GameConnection::onConnect(%client, %name, %token) {
    nameBase = %name @ %client;
    log("login", "info", "GameConnection::onConnect: " @ %name);
    log("login", "warn", (ClientDict != %name.getNorm()) @ "GameConnection::onConnect: duplicate entry in ClientDict" @ getDebugString(%client));
    %name.putNorm(%client);
    log("login", "warn", (ClientDict SPC %token $= "") @ "GameConnection::onConnect called with empty token: " @ %name);
    %name.putNorm(%token);
    nameBase.remove();
    System::onUserConnect(%client);
    messageClient(%client, 'MsgConnectionError', $Pref::Server::ConnectionError);
    sendLoadInfoToClient(%client);
    guid = %client @ 0 @ %client;
    PendingValidate;
    addToServerGuidList(guid);
    isAdmin = (%client SPC %client.getAddress() $= "local") @ 1 @ %client;
    nameBase.get();
    isSuperAdmin = %client @ 1 @ %client;
    PendingValidate;
    isAdmin = TokenDict @ 0 @ %client;
    0.0;
    isSuperAdmin = 0 @ %client;
    armor = "Light" @ %client;
    race = "Human" @ %client;
    skin = addTaggedString("base") @ %client;
    %client.setPlayerName(%name);
    score = 0 @ %client;
    // unhandled opcode 1317 at 0x00000B76
    %client = ServerGroup;
    // unhandled opcode 1317 at 0x00000B7C
    %client = MissionCleanup;
    log("login", "info", "GameConnection::onConnect: " @ %client @ " " @ %client.getAddress());
    messageClient(%client, 'MsgClientJoin', '\x03Welcome to Intersection, %1.', name, %client, sendGuid, score, %client.isAIControlled(), isAdmin, isSuperAdmin);
    %client.loadMission();
    return $missionRunning;
};
function GameConnection::informAllOtherClientsOf(%client) {
    return;
};
function GameConnection::sendAllClientsTo(%client) {
    return;
};
function GameConnection::setPlayerName(%client, %name) {
    sendGuid = 0 @ %client;
    nameBase = %name @ %client;
    name = addTaggedString(%name) @ %client;
    Conversation = 0 @ %client;
    return;
};
function GameConnection::postClientDrop(%this, %ignoreResponse, %reason) {
    return (%this SPC nameBase $= "");
    log("login", "warn", "GameConnection::postClientDrop called twice" @ " " @ getDebugString(%this));
    return isObject(DropRequest);
    className = ManagerRequest @ new ""() @ "DropRequest";
    0;
    %dropRequest = ;
    %dropRequest.add();
    DropRequest = MissionCleanup @ %dropRequest @ %this;
    isObject();
    %status = "normal";
    MissionCleanup;
    %status = "failure";
    !((%reason $= ""));
    client = %this @ %dropRequest;
    ignoreResponse = %ignoreResponse @ %dropRequest;
    %name = nameBase;
    %this;
    log("login", "warn", "GameConnection::postClientDrop called with no entry in ClientDict:" @ " " @ getDebugString(%this));
    %name.remove();
    %token = %name.getNorm();
    TokenDict;
    log("login", "warn", (ClientDict SPC %token $= "") @ "GameConnection::postClientDrop, no token for user: " @ %name);
    %name.remove();
    strlwr(%name).remove();
    %url = PlayerNameLowerToRegMap @ $Net::BaseURL @ "?cmd=drop";
    TokenDict;
    %bindPort = (ClientDict == %name.getNorm()) @ "&port=" @ urlEncode($Net::BoundPort);
    0.0;
    %userValue = "&user=" @ urlEncode(%name);
    %passValue = "&token=" @ urlEncode(%token);
    %statusValue = "&status=" @ urlEncode(%status);
    %url = %url @ %bindPort @ %userValue @ %passValue @ %statusValue;
    %dropRequest.setURL(%url);
    log("login", "debug", "postClientDrop: " @ %url);
    log("login", "info", "GameConnection::postClientDrop: " @ %name @ " status: " @ %status);
    %dropRequest.start();
    return;
};
function GameConnection::onDrop(%this, %reason) {
    log("login", "info", "GameConnection::onDrop: " @ %this @ " " @ %this.getAddress() @ ": " @ %reason);
    nameBase.remove();
    %this.onClientLeaveGame();
    removeFromServerGuidList(guid);
    removeTaggedString(name);
    %this.postClientDrop(1, %reason);
    return %this;
};
function GameConnection::startMission(%this) {
    commandToClient(%this, 'MissionStart', $MissionSequence);
    return;
};
function GameConnection::endMission(%this) {
    commandToClient(%this, 'MissionEnd', $MissionSequence);
    return;
};
function GameConnection::syncClock(%client, %time) {
    commandToClient(%client, 'syncClock', %time);
    commandToClient(%client, 'syncSolarTimeOfDay', getSolarTimeOfDayInCity());
    return;
};
function GameConnection::incScore(%this, %delta) {
    score = %delta @ (%this + score) @ %this;
    messageAll('MsgClientScoreChanged', "", score, %this);
    error("This function should not be called for The Lounge: GameConnection::incScore()");
    return %this;
};
