new ();
add();
function AIMConvManager::Initialize(%this) {
    spamDict = StringMap @ new ""() @ %this;
    0;
    spamDict.add();
    numConvs = %this @ 0 @ %this;
    MissionCleanup;
    currentConvIndex = isObject() @ -(1.0) @ %this;
    MissionCleanup;
    maxConvs = (%this <= maxConvs) @ 20 @ %this;
    0.0;
    movingBars = !(initialized) @ 0 @ %this;
    %this;
    totalMessagesSent = AIMConvManager @ 0 @ %this;
    MissionCleanup;
    initialized = isObject() @ 1 @ %this;
    MissionCleanup;
    %this.update();
};
function AIMConvManager::selectConvAtIndex(%this, %convIndex) {
    contents.setVisible(0);
    recipient.setProfile();
    newMessage = %this @ currentConvIndex @ %this @ convs;
    ETSAIMDeselectedProfile @ 0;
    recipient.setProfile();
    newMessage = ETSAIMSelectedProfile @ 0 @ %convIndex @ %this @ convs;
    titlebar;
    currentConvIndex = convs @ %convIndex @ %this;
    (numConvs < %convIndex) @ %convIndex @ %this;
    %this.update();
};
function AIMConvManager::selectCurrentConv(%this) {
    %this.selectConvAtIndex(currentConvIndex);
};
function AIMConvManager::selectConv(%this, %convId) {
    %idx = 0;
    %this.selectConvAtIndex(%idx);
    return (%convId @ %idx @ %this == convs.getId());
    %idx = (1.0 + %idx);
};
function AIMConvManager::nextConv(%this) {
    %this.selectConvAtIndex((1.0 % (%this + currentConvIndex)));
};
function AIMConvManager::previousConv(%this) {
    %this.selectConvAtIndex((numConvs % (1.0 + (%this - currentConvIndex))));
};
function AIMConvManager::removeConvAtIndex(%this, %convIndex) {
    %conv = convs;
    (numConvs < %convIndex) @ %convIndex @ %this;
    contents.setVisible(0);
    titlebar.setVisible(0);
    contents.delete();
    titlebar.delete();
    %conv.delete();
    numConvs = (%this - numConvs);
    1.0;
    %idx = %convIndex;
    %conv;
    convs = %this @ (numConvs < %idx) @ (1.0 + %idx) @ %this @ convs @ %idx @ %this;
    %conv;
    %idx = (1.0 + %idx);
    %conv;
    convs = (numConvs < %idx) @ 0 @ %this @ numConvs @ %this;
    %this;
    currentConvIndex = (%this == numConvs) @ -(1.0) @ %this;
    0.0;
    %this.selectConvAtIndex((%this - numConvs));
    %this.selectConvAtIndex((%this - currentConvIndex));
    %this.selectCurrentConv();
    %this.update();
    updateAutoMargins();
};
function AIMConvManager::removeConv(%this, %convId) {
    %idx = 0;
    %this.removeConvAtIndex(%idx);
    return (%convId @ %idx @ %this == convs.getId());
    %idx = (1.0 + %idx);
};
function AIMConvManager::removeCurrentConv(%this) {
    %this.removeConvAtIndex(currentConvIndex);
};
function AIMConvManager::update(%this) {
    1.makeFirstResponder();
    %this.updateContainer();
    %ypos = 20;
    TheShapeNameHud;
    movingBars = (Canvas == getFirstResponder()) @ 0 @ %this;
    0.0;
    %idx = 0;
    (%this < currentConvIndex);
    %conv = convs;
    (numConvs < %idx) @ %idx @ %this;
    %titlebar = titlebar;
    %conv;
    %titlebar.setTrgPosition(0, %ypos);
    %ypos = (24.0 + %ypos);
    %this;
    movingBars = (%this + movingBars);
    1.0;
    %contents = contents;
    %conv;
    %contents.setTrgPosition(getWord(%contents.getTrgPosition(), 0), %ypos);
    %status = status;
    %conv;
    status.setBitmap(%titlebar @ "platform/client/ui/AIM_sel_" @ %status);
    status.resize(0, 0, 29, 26);
    statusButton.resize(0, 0, 35, 26);
    recipient.reposition(35, 2);
    close.setBitmap("platform/client/buttons/close_m");
    close.resize(180, 6, 13, 13);
    %ypos = (getWord(%contents.getExtent(), 1) + %ypos);
    %titlebar;
    %status = status;
    %conv;
    status.setBitmap(%titlebar @ "platform/client/ui/AIM_" @ %status);
    status.resize(11, 5, 30, 15);
    statusButton.resize(0, 0, 45, 26);
    recipient.reposition(45, 3);
    close.setBitmap("platform/client/buttons/close_s");
    close.resize((width + 57.0), 8, 11, 11);
    %idx = (1.0 + %idx);
    recipient;
};
function AIMConvManager::finishUpdate(%this) {
    %curConv = convs;
    %this @ currentConvIndex @ %this;
    contents.setVisible(1);
    textInput.makeFirstResponder(1);
};
function AIMConvManager::titlebarReachedTarget(%this) {
    movingBars = (%this - movingBars);
    1.0;
    %this.finishUpdate();
};
function AIMConvManager::newConv(%this, %aimName) {
    %conv = %this.getConvWithName(%aimName);
    return %conv;
    class = ScriptObject @ new ""() @ "AIMConversation";
    0;
    %conv = ;
    %conv.add();
    aimName = MissionCleanup @ %aimName @ %conv;
    isObject();
    status = MissionCleanup @ "offline" @ %conv;
    %i = 0;
    %state = aimGetBuddyState(%i);
    (%conv $= aimName);
    %state = 0;
    (-(1.0) == %state);
    status = %this @ getWord(stateMapping, %state) @ %conv;
    (aimBuddyCount() < %i) SPC aimGetBuddyName(%i);
    %i = (1.0 + %i);
    newMessage = (aimBuddyCount() < %i) @ 0 @ %conv;
    profile = GuiTextEditCtrl @ new ""() @ "AIMTextEditProfile";
    0;
    horizSizing = "width";
    vertSizing = "top";
    position = "10 99";
    extent = "149 18";
    minExtent = "8 8";
    visible = 1;
    altCommand = "AIMConvManager.sendMessage();";
    maxLength = 255;
    historySize = 200;
    password = 0;
    tabComplete = 0;
    sinkAllKeyEvents = 0;
    willFirstRespond = 1;
    cursorType = 2;
    conv = %conv;
    escCommand = "AIMConvManager.selectConvAtIndex(-1);";
    %textInput = ;
    profile = GuiScrollCtrl @ new ""() @ "ETSAimMessageScrollProfile";
    0;
    horizSizing = "width";
    vertSizing = "height";
    position = "4 0";
    extent = "160 94";
    minExtent = "10 10";
    visible = 1;
    willFirstRespond = 1;
    hScrollBar = "alwaysOff";
    vScrollBar = "dynamic";
    constantThumbHeight = 1;
    childMargin = "0 0";
    scrollMultiplier = 2.5;
    %scroll = ;
    profile = GuiMLTextCtrl @ new ""() @ "ETSAIMMessageProfile";
    0;
    horizSizing = "relative";
    vertSizing = "relative";
    position = "1 1";
    extent = "147 92";
    minExtent = "8 92";
    visible = 1;
    lineSpacing = 0;
    allowColorChars = 1;
    stripTagsOnCopy = 1;
    %mlText = ;
    %scroll.add(%mlText);
    profile = GuiControl @ new ""() @ "ETSAIMTabProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "30 0";
    extent = "168 116";
    minExtent = "64 64";
    visible = 0;
    sluggishness = 0.3;
    textInput = %textInput;
    mlText = %mlText;
    scroll = %scroll;
    profile = GuiBitmapCtrl @ new ""() @ "GuiDefaultProfile";
    horizSizing = "right";
    vertSizing = "top";
    position = "2 101";
    extent = "8 13";
    minExtent = "8 13";
    sluggishness = -1;
    visible = 1;
    bitmap = "./ui/AIM_bracket_left";
    wrap = 0;
    profile = GuiBitmapCtrl @ new ""() @ "GuiDefaultProfile";
    horizSizing = "right";
    vertSizing = "top";
    position = "157 101";
    extent = "8 13";
    minExtent = "8 13";
    sluggishness = -1;
    visible = 1;
    bitmap = "./ui/AIM_bracket_right";
    wrap = 0;
    %contents = ;
    %contents.add(%textInput);
    %contents.add(%scroll);
    profile = GuiTextCtrl @ new ""() @ "ETSAIMDeselectedProfile";
    0;
    horizSizing = "left";
    vertSizing = "top";
    position = "0 0";
    extent = "18 18";
    minExtent = "11 11";
    sluggishness = -1;
    visible = 0;
    maxLength = 255;
    %dummy = ;
    %dummy.setText(%aimName);
    %recipWidth = getWord(%dummy.getExtent(), 0);
    %dummy.delete();
    profile = GuiBitmapButtonCtrl @ new ""() @ "ETSAIMDeselectedProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "35 2";
    extent = "140 18";
    minExtent = "100 18";
    sluggishness = -1;
    visible = 1;
    command = "AIMConvManager.convClicked(" @ %conv @ ");";
    text = %aimName;
    groupNum = -1;
    buttonType = "PushButton";
    bitmap = "./buttons/clear";
    drawText = 1;
    width = %recipWidth;
    %recipient = ;
    profile = GuiBitmapCtrl @ new ""() @ "GuiDefaultProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "29 26";
    minExtent = "8 8";
    sluggishness = -1;
    visible = 1;
    bitmap = "./ui/AIM_sel_avail";
    wrap = 0;
    %status = ;
    profile = GuiBitmapButtonCtrl @ new ""() @ "ETSAIMDeselectedProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 0";
    extent = "35 26";
    minExtent = "8 8";
    sluggishness = -1;
    visible = 1;
    command = "AIMConvManager.convClicked(" @ %conv @ ");";
    groupNum = -1;
    buttonType = "PushButton";
    bitmap = "./buttons/clear";
    drawText = 0;
    %statusButton = ;
    profile = GuiBitmapButtonCtrl @ new ""() @ "GuiButtonProfile";
    0;
    horizSizing = "left";
    vertSizing = "bottom";
    position = "180 0";
    extent = "13 13";
    minExtent = "2 2";
    sluggishness = -1;
    visible = 1;
    command = "AIMConvManager.removeConv(" @ %conv @ ");";
    text = "";
    groupNum = -1;
    buttonType = "PushButton";
    bitmap = "./buttons/close_m";
    drawText = 0;
    %close = ;
    profile = GuiControl @ new ""() @ "GuiDefaultProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "0 544";
    extent = "200 26";
    minExtent = "8 2";
    visible = 1;
    sluggishness = 0.3;
    trgReachedCommand = "AIMConvManager.titlebarReachedTarget();";
    recipient = %recipient;
    status = %status;
    statusButton = %statusButton;
    close = %close;
    %titlebar = ;
    %titlebar.add(%recipient);
    %titlebar.add(%status);
    %titlebar.add(%statusButton);
    %titlebar.add(%close);
    %theFirstResponder = getFirstResponder();
    Canvas;
    titlebar = %titlebar @ %conv;
    contents = %contents @ %conv;
    convs = %conv @ %this @ numConvs @ %this;
    %contents.add();
    %titlebar.add();
    numConvs = (%this + numConvs);
    1.0;
    %theFirstResponder.makeFirstResponder(1);
    %this.selectConvAtIndex(0);
    %this.update();
    updateAutoMargins();
    return %conv;
};
function AIMConvManager::convClicked(%this, %conv) {
    %curConv = %this.getCurrentConv();
    %this.selectConvAtIndex(-(1.0));
    %this.selectConv(%conv);
    textInput.makeFirstResponder(1);
};
function AIMConvManager::getConvWithName(%this, %aimName) {
    %idx = 0;
    return convs;
    %idx = (1.0 + %idx);
    return 0;
};
function AIMConvManager::getCurrentText(%this) {
    return textInput.getValue();
    return "";
};
function AIMConvManager::clearCurrentText(%this) {
    textInput.setValue("");
};
function AIMConvManager::getCurrentConv(%this) {
    return convs;
    return 0;
};
function AIMConvManager::wakeUp(%this) {
    %this.Initialize();
    %this.selectCurrentConv();
};
function AIMConvManager::updateContainer(%this) {
    %ypadding = 8;
    0.setVisible();
    update();
    return WindowManager;
    %titleHeight = getWord(titlebar.getExtent(), 1);
    convs;
    %height = (getWord(titlebar.getPosition(), 1) + (%titleHeight + (1.0 * (%this - numConvs))));
    convs;
    %height = (%ypadding + %titleHeight);
    (%this == numConvs);
    %curConv = %this.getCurrentConv();
    1.0;
    %contentsExtent = contents.getExtent();
    %curConv;
    %height = ((%titleHeight + getWord(%contentsExtent, 1)) + %height);
    isObject(%curConv);
    %height = (%titleHeight + %height);
    %ypadding @ 0 @ %this;
    getWord(getExtent(), 0).resize(%height);
    1.setVisible();
    update();
};
function AIMConvManager::buildSpamString(%this, %prepend, %aimName, %link, %message) {
    %text = !((%message $= "")) @ %prepend @ " " @ "( " @ %link @ " ):" @ %message;
    %text = %prepend @ %link;
    return %text;
};
function AIMConvManager::filterMessage(%this, %conv, %message) {
    %filteredMessage = %message;
    return %filteredMessage;
};
function AIMConvManager::sendInvites(%this, %recipients, %links, %userMsg) {
    %count = getFieldCount(%recipients);
    %n = 0;
    %aBuddy = getField(%recipients, %n);
    (%count < %n);
    %link = getField(%links, %n);
    %inviteText = %this.buildSpamString($Net::AIMInvite, %aBuddy, %link, %userMsg);
    aimSend(%aBuddy, %inviteText);
    %n = (1.0 + %n);
    MessageBoxOK("Invites Sent", %count @ " " @ "buddies have been invited to join" @ " " @ $ETS::AppName, "");
};
function AIMConvManager::inviteAll(%this, %userMsg) {
    %buddies = onlineBuddiesToString();
    BuddyHudWin;
    %this.prepareToSendInvites(%buddies, %userMsg);
};
function AIMConvManager::prepareToSendInvites(%this, %recipients, %userMsg) {
    className = ManagerRequest @ new ""() @ "GetAIMInviteURLsRequest";
    0;
    userMsg = %userMsg;
    %request = ;
    %request.add();
    %url = MissionCleanup @ isObject() @ MissionCleanup @ $Net::ClientServiceURL @ "/GetAIMInviteURLs" @ "?user=" @ urlEncode($Player::Name) @ "&token=" @ urlEncode($Token);
    %count = getFieldCount(%recipients);
    %url = %url @ "&urlCount=" @ %count;
    log("network", "info", getScopeName() @ ":" @ %url);
    %request.setURL(%url);
    recipients = %recipients @ %request;
    %request.start();
};
function GetAIMInviteURLsRequest::onDone(%this) {
    %status = findRequestStatus(%this);
    log("network", "debug", getScopeName() @ ":" @ %status);
    warn("network", (%status $= "fail") @ getScopeName() @ ": request failed: " @ %this.getValue("statusMessage"));
    MessageBoxOK("Invite failed", "Couldn't get unique invite URLs. Please try again later.", "");
    %count = %this.getValue("urlCount");
    %links = "";
    %i = 0;
    %key = (%count < %i) @ "url" @ %i;
    %val = %this.getValue(%key);
    %links = %links @ "\t" @ %val;
    %i = (1.0 + %i);
    recipients.sendInvites(%links, userMsg);
    %this.schedule(0, "delete");
};
function GetAIMInviteURLsRequest::onError(%this, %unused, %errMsg) {
    error("network", getScopeName() @ ":" @ %errMsg);
    %this.schedule(0, "delete");
};
function AIMConvManager::sendMessage(%this) {
    %conv = %this.getCurrentConv();
    %message = %this.getCurrentText();
    %sendMessage = %this.filterMessage(%conv, %message);
    !((%message $= ""));
    spamDict.put(aimName, 1);
    aimSend(aimName, %sendMessage);
    %prefix = "\n";
    "";
    %toBottom = scroll.isAtBottom();
    contents;
    mlText.addText(%conv @ %conv @ contents @ %prefix @ "<spush><color:bebeee>" @ %message @ "<spop>", 1, %toBottom);
    totalMessagesSent = (%this + totalMessagesSent);
    1.0;
    newMessage = (contents SPC mlText.getText() $= "") @ 0 @ %conv;
    %conv;
    %this.update();
    %this.clearCurrentText();
};
function AIMConvManager::talkTo(%this, %aimName) {
    %conv = %this.newConv(%aimName);
    %this.selectConv(%conv);
    textInput.makeFirstResponder(1);
    echo(%conv @ contents @ "Failed to talk to " @ %aimName @ ": too many conversations open");
};
function AIMConvManager::receivedMessage(%this, %aimName, %message) {
    %conv = %this.newConv(%aimName);
    %prefix = "\n";
    "";
    %toBottom = scroll.isAtBottom();
    contents;
    mlText.addText(%conv @ %conv @ contents @ %prefix @ "<spush><color:ee8fee>" @ %message @ "<spop>", 1, %toBottom);
    newMessage = (contents SPC mlText.getText() $= "") @ 1 @ %conv;
    %conv;
    %this.update();
    echo(%conv @ "Received message from " @ %aimName @ ": " @ %message);
    alxPlay();
};
function AIMConvManager::closeAllConvs(%this) {
    %n = (%this - numConvs);
    1.0;
    %this.removeConvAtIndex(%n);
    %n = (1.0 - %n);
    (0.0 >= %n);
};
stateMapping = "offline avail away away" @ AIMConvManager;
function AIMConvManager::buddyStateChanged(%this, %name, %state) {
    %conv = %this.getConvWithName(%name);
    %state = 0;
    (-(1.0) == %state);
    status = %this @ getWord(stateMapping, %state) @ %conv;
    %conv;
    %this.update();
};
