volume = AudioGui @ new () @ 0.6;
AudioDescription;
isLooping = 0 @ 0;
is3D = 0;
type = $SimAudioType;
volume = AudioMessage @ new () @ 1;
AudioDescription;
isLooping = 0 @ 0;
is3D = 0;
type = $SimAudioType;
fileName = AudioButtonOver @ new () @ "projects/common/sound/buttonOver.wav";
AudioProfile;
description = 0 @ "AudioGui";
preload = 0;
fileName = AudioIm_MessageIn @ new () @ "projects/common/sounds/im/messageIn.ogg";
AudioProfile;
description = 0 @ "AudioMessage";
preload = 0;
fileName = AudioIm_WhisperIn @ new () @ "projects/common/sounds/im/whisperIn.ogg";
AudioProfile;
description = 0 @ "AudioMessage";
preload = 0;
fileName = AudioIm_SystemMessageIn @ new () @ "projects/common/sounds/im/whisperIn.ogg";
AudioProfile;
description = 0 @ "AudioMessage";
preload = 0;
fileName = Audio_SOSMessageIn @ new () @ "dev/data/sounds/helpme.ogg";
AudioProfile;
description = 0 @ "AudioMessage";
preload = 0;
fileName = AudioIm_CaChing @ new () @ "projects/common/sounds/ui/caChing.ogg";
AudioProfile;
description = 0 @ "AudioMessage";
preload = 0;
fileName = AudioIm_vPoints1 @ new () @ "projects/common/sounds/ui/vPoints1.ogg";
AudioProfile;
description = 0 @ "AudioMessage";
preload = 0;
fileName = AudioIm_vPoints2 @ new () @ "projects/common/sounds/ui/vPoints2.ogg";
AudioProfile;
description = 0 @ "AudioMessage";
preload = 0;
fileName = AudioProfile_Shutter @ new () @ "projects/common/sounds/ui/shutter.ogg";
AudioProfile;
description = 0 @ "AudioMessage";
preload = 0;
fileName = AudioRespektLevelGained @ new () @ "projects/common/sounds/gameplay/questEnd.ogg";
AudioProfile;
description = 0 @ "AudioMessage";
preload = 0;
fileName = AudioProfile_ExpiringSoon @ new () @ "projects/common/sounds/ui/ticking.ogg";
AudioProfile;
description = 0 @ "AudioMessage";
fileName = AudioProfile_JustExpired @ new () @ "projects/common/sounds/ui/pop.ogg";
AudioProfile;
description = 0 @ "AudioMessage";
fileName = AudioProfile_Tutorial @ new () @ "projects/common/sounds/ui/tutorial.ogg";
AudioProfile;
description = 0 @ "AudioMessage";
preload = 0;
fileName = AudioProfile_AFX_TeleIn @ new () @ "projects/common/sounds/teleIn.ogg";
AudioProfile;
description = 0 @ "AudioMessage";
preload = 0;
fileName = AudioProfile_AFX_TeleOut @ new () @ "projects/common/sounds/teleOut.ogg";
AudioProfile;
description = 0 @ "AudioMessage";
preload = 0;
