$gClosetGuiFueStepCount = 0;
$gClosetGuiFueCurrentStep = -(1.0);
function ClosetGuiFUE::open(%this) {
    %sched = gGetField(%this, "closetGuiFUEOpenSched");
    refreshingOrInitializing;
    cancel(%sched);
    %sched = %this.schedule(250);
    open;
    gSetField(%this, "closetGuiFUEOpenSched", %sched);
    return %this;
    arrivedAtFinalTip = !(initialized) @ 0 @ %this;
    %this;
    %this.Initialize();
    %this.reposition();
    %this.showAllAsInactive();
    %this.goToStepByName(name);
};
function ClosetGuiFUE::close(%this) {
    %this.hide();
};
function ClosetGuiFUE::show(%this) {
    %sched = gGetField(%this, "closetGuiFUEShowSched");
    refreshingOrInitializing;
    cancel(%sched);
    %sched = %this.schedule(250);
    show;
    gSetField(%this, "closetGuiFUEShowSched", %sched);
    return %this;
    %this.setVisible(1);
    %this.goToStepByName(name);
};
function ClosetGuiFUE::hide(%this) {
    %this.setVisible(0);
};
function ClosetGuiFUE::reposition(%this) {
    position = (2.0 + (960.0 / (ClosetGuiPositioner - getWord(extent, 0)))) @ " " @ 1.0 @ (2.0 + (32.0 / (576.0 - (ClosetGuiPositioner - getWord(extent, 1))))) @ %this;
    1.0;
};
function ClosetGuiFUE::showAllAsInactive(%this) {
    %sched = gGetField(%this, "closetGuiFUEShowAllAsInactiveSched");
    refreshingOrInitializing;
    cancel(%sched);
    %sched = %this.schedule(250);
    showAllAsInactive;
    gSetField(%this, "closetGuiFUEShowAllAsInactiveSched", %sched);
    return %this;
    %i = 0;
    stepContainers.setVisible(0);
    stepContainers.setVisible(!(hideTipsCtrl.getValue()));
    %i = (1.0 + %i);
    %this;
    show();
};
function ClosetGuiFUE::addStep(%this, %activeContainer, %inactiveContainer) {
    error(getScopeName() @ " " @ "- empty activeContainer object -" @ " " @ getTrace());
    return 0;
    error(getScopeName() @ " " @ "- empty inactiveContainer object -" @ " " @ getTrace());
    return 0;
    %activeContainer.setVisible(0);
    %this.add(%activeContainer);
    stepContainers = %activeContainer TAB $gClosetGuiFueStepCount @ "active" @ %this;
    %inactiveContainer.setVisible(0);
    %this.add(%inactiveContainer);
    stepContainers = isObject(%inactiveContainer) @ %inactiveContainer TAB $gClosetGuiFueStepCount @ "inactive" @ %this;
    $gClosetGuiFueStepCount = (1.0 + $gClosetGuiFueStepCount);
    return 1;
};
function ClosetGuiFUE::addStepWithName(%this, %activeContainer, %inactiveContainer, %stepName) {
    stepNumbersByName = $gClosetGuiFueStepCount @ strlwr(%stepName) @ %this;
    warn(getScopeName() @ " " @ "- step" @ " " @ %stepName @ " " @ "not added -" @ " " @ getTrace());
    stepNumbersByName = !(%this.addStep(%activeContainer, %inactiveContainer)) @ -(1.0) @ strlwr(%stepName) @ %this;
    return 0;
    return 1;
};
function ClosetGuiFUE::firstStep(%this) {
    error(getScopeName() @ " " @ "- first step has not yet been set -" @ " " @ getTrace());
    return (0.0 == $gClosetGuiFueStepCount);
    %this.hideCurrentStep();
    $gClosetGuiFueCurrentStep = 0;
    %this.showCurrentStep();
};
function ClosetGuiFUE::nextStep(%this) {
    %this.hideCurrentStep();
    $gClosetGuiFueCurrentStep = (1.0 + $gClosetGuiFueCurrentStep);
    ((1.0 - $gClosetGuiFueStepCount) < $gClosetGuiFueCurrentStep);
    $gClosetGuiFueCurrentStep = -(1.0);
    (-(1.0) >= $gClosetGuiFueCurrentStep);
    %this.showCurrentStep();
};
function ClosetGuiFUE::goToStepByName(%this, %stepName) {
    error(getScopeName() @ " " @ "- invalid stepName" @ " " @ %stepName @ " " @ "-" @ " " @ getTrace());
    return 0;
    %this.hideCurrentStep();
    (closetGuiFUEShopsDirBitmap SPC $gCurrentStoreName $= "").setVisible();
    !((StoreShoppingBag SPC $gCurrentStoreName $= "")).setVisible();
    !((StoreAddItemsButton SPC $gCurrentStoreName $= "")).setVisible();
    0.setLeaveStoreControlsVisible();
    0.setVisible();
    $gClosetGuiFueCurrentStep = stepNumbersByName;
    closetGuiFUEShopsDirBitmap @ strlwr(%stepName) @ %this;
    %this.showCurrentStep();
};
function ClosetGuiFUE::goToStepByNumber(%this, %stepNumber) {
    error(getScopeName() @ " " @ "- invalid stepNumber" @ " " @ %stepNumber @ " " @ "-" @ " " @ getTrace());
    return ($gClosetGuiFueStepCount >= %stepNumber);
    %this.hideCurrentStep();
    $gClosetGuiFueCurrentStep = %stepNumber;
    %this.showCurrentStep();
};
function ClosetGuiFUE::showCurrentStep(%this) {
    return (-(1.0) == $gClosetGuiFueCurrentStep);
    %sched = gGetField(%this, "closetGuiFUEShowCurrentStepSched");
    refreshingOrInitializing;
    cancel(%sched);
    %sched = %this.schedule(250);
    showCurrentStep;
    gSetField(%this, "closetGuiFUEShowCurrentStepSched", %sched);
    return %this;
    stepContainers.setVisible(0);
    stepContainers.setVisible(!(hideTipsCtrl.getValue()));
    arrivedAtFinalTip = !(arrivedAtFinalTip) @ strlwr("Snapshot") @ %this @ (stepNumbersByName == $gClosetGuiFueCurrentStep) @ %this;
    %this;
};
function ClosetGuiFUE::hideCurrentStep(%this) {
    return (-(1.0) == $gClosetGuiFueCurrentStep);
    stepContainers.setVisible(0);
    stepContainers.setVisible(!(hideTipsCtrl.getValue()));
};
function ClosetGuiFUE::refresh(%this) {
    %sched = gGetField(%this, "closetGuiFUERefreshSched");
    refreshingOrInitializing;
    cancel(%sched);
    %sched = %this.schedule(250);
    refresh;
    gSetField(%this, "closetGuiFUERefreshSched", %sched);
    return %this;
    refreshingOrInitializing = 1 @ %this;
    deleteMembers();
    $gClosetGuiFueStepCount = 0;
    ClosetGuiFUE;
    $gClosetGuiFueCurrentStep = -(1.0);
    %this.Initialize();
    %this.showAllAsInactive();
    refreshingOrInitializing = %visible @ 0 @ %this;
};
function ClosetGuiFUE::Initialize(%this) {
    refreshingOrInitializing = 1 @ %this;
    profile = closetGuiFUEHideTipsCtrl @ new () @ "ETSCheckBoxProfile";
    GuiCheckBoxCtrl;
    horizSizing = !(isObject()) @ 0 @ "right";
    closetGuiFUEHideTipsCtrl;
    vertSizing = "bottom";
    position = "863 557";
    extent = "99 20";
    minExtent = "8 2";
    sluggishness = -1;
    visible = 0;
    text = "Don't Show Tips";
    groupNum = -1;
    buttonType = "ToggleButton";
    hideTipsCtrl = %this;
    %this.add(hideTipsCtrl);
    hideTipsCtrl = closetGuiFUEHideTipsCtrl @ %this;
    %this;
    %this.add(hideTipsCtrl);
    %buttonPosition = button.getPosition();
    "Body".getTabWithName();
    profile = GuiControl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = ClosetTabs @ ClosetGuiFUE @ horizSizing;
    %this;
    vertSizing = ClosetGuiFUE @ vertSizing;
    position = "0 0";
    extent = ClosetGuiFUE @ extent;
    minExtent = ClosetGuiFUE @ minExtent;
    sluggishness = ClosetGuiFUE @ sluggishness;
    visible = 0;
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = (10.0 - getWord(%buttonPosition, 0)) @ " " @ (10.0 - getWord(%buttonPosition, 1));
    extent = "123 82";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/closetGuiFUE_step3_active";
    profile = closetGuiFUEWelcomeImage @ new () @ "ETSNonModalProfile";
    GuiBitmapCtrl;
    horizSizing = "right";
    vertSizing = "bottom";
    position = "511 32";
    extent = "447 544";
    minExtent = "20 20";
    visible = 1;
    bitmap = "platform/client/ui/welcomeBodyPanel";
    %newActiveStep = ;
    profile = GuiControl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = ClosetGuiFUE @ horizSizing;
    vertSizing = ClosetGuiFUE @ vertSizing;
    position = "0 0";
    extent = ClosetGuiFUE @ extent;
    minExtent = ClosetGuiFUE @ minExtent;
    sluggishness = ClosetGuiFUE @ sluggishness;
    visible = 0;
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = (10.0 - getWord(%buttonPosition, 0)) @ " " @ (10.0 - getWord(%buttonPosition, 1));
    extent = "123 82";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/closetGuiFUE_step3_inactive";
    %newInactiveStep = ;
    %this.addStepWithName(%newActiveStep, %newInactiveStep, "Body");
    %buttonPosition = button.getPosition();
    "Closet".getTabWithName();
    profile = GuiControl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = ClosetTabs @ ClosetGuiFUE @ horizSizing;
    vertSizing = ClosetGuiFUE @ vertSizing;
    position = "0 0";
    extent = ClosetGuiFUE @ extent;
    minExtent = ClosetGuiFUE @ minExtent;
    sluggishness = ClosetGuiFUE @ sluggishness;
    visible = 0;
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = (10.0 - getWord(%buttonPosition, 0)) @ " " @ (10.0 - getWord(%buttonPosition, 1));
    extent = "123 82";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/closetGuiFUE_step2_active";
    %newActiveStep = new ( : closetGuiFUEWelcomeImage);
    closetGuiFUEWelcomeImage_b;
    profile = GuiControl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = GuiBitmapCtrl @ ClosetGuiFUE @ horizSizing;
    vertSizing = ClosetGuiFUE @ vertSizing;
    position = "0 0";
    extent = ClosetGuiFUE @ extent;
    minExtent = ClosetGuiFUE @ minExtent;
    sluggishness = ClosetGuiFUE @ sluggishness;
    visible = 0;
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = (10.0 - getWord(%buttonPosition, 0)) @ " " @ (10.0 - getWord(%buttonPosition, 1));
    extent = "123 82";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/closetGuiFUE_step2_inactive";
    %newInactiveStep = ;
    %this.addStepWithName(%newActiveStep, %newInactiveStep, "Closet");
    fillStoreTab();
    %button = button;
    "Shops".getTabWithName();
    %buttonPosition = %button.getPosition();
    ClosetTabs;
    profile = GuiControl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = ClosetTabs @ ClosetGuiFUE @ horizSizing;
    !(tabShopsInitialized);
    vertSizing = ClosetTabs @ ClosetGuiFUE @ vertSizing;
    position = "0 0";
    extent = ClosetGuiFUE @ extent;
    minExtent = ClosetGuiFUE @ minExtent;
    sluggishness = ClosetGuiFUE @ sluggishness;
    visible = 0;
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = (10.0 - getWord(%buttonPosition, 0)) @ " " @ (10.0 - getWord(%buttonPosition, 1));
    extent = "123 82";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/closetGuiFUE_step1_active";
    %newActiveStep = ;
    profile = closetGuiFUEShopsDirBitmap @ new () @ "ETSNonModalProfile";
    GuiBitmapCtrl;
    horizSizing = !(isObject()) @ 0 @ "right";
    closetGuiFUEShopsDirBitmap;
    vertSizing = "bottom";
    position = "35 125";
    extent = "441 375";
    minExtent = "1 1";
    sluggishness = -1;
    visible = ($gCurrentStoreName $= "");
    bitmap = "platform/client/ui/closetGuiFUE_shop_active_shopsDir";
    shopsDirBitmap = %this;
    %this.add(shopsDirBitmap);
    shopsDirBitmap = closetGuiFUEShopsDirBitmap @ %this;
    %this;
    %this.add(shopsDirBitmap);
    profile = closetGuiFUE_vPoints_vBux_Image @ new () @ "ETSNonModalProfile";
    GuiBitmapCtrl;
    horizSizing = %this @ 0 @ "right";
    vertSizing = "bottom";
    position = "607 32";
    extent = "346 340";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/closetGuiFUE_shop_active_creds";
    %credsBitmapCtrl = ;
    %newActiveStep.add(%credsBitmapCtrl);
    profile = GuiControl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = ClosetGuiFUE @ horizSizing;
    vertSizing = ClosetGuiFUE @ vertSizing;
    position = "0 0";
    extent = ClosetGuiFUE @ extent;
    minExtent = ClosetGuiFUE @ minExtent;
    sluggishness = ClosetGuiFUE @ sluggishness;
    visible = 0;
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = (10.0 - getWord(%buttonPosition, 0)) @ " " @ (10.0 - getWord(%buttonPosition, 1));
    extent = "123 82";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/closetGuiFUE_step1_inactive";
    %newInactiveStep = ;
    %this.addStepWithName(%newActiveStep, %newInactiveStep, "Shops");
    %buttonPosition = button.getPosition();
    "Snapshot".getTabWithName();
    profile = GuiControl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = ClosetTabs @ ClosetGuiFUE @ horizSizing;
    vertSizing = ClosetGuiFUE @ vertSizing;
    position = "0 0";
    extent = ClosetGuiFUE @ extent;
    minExtent = ClosetGuiFUE @ minExtent;
    sluggishness = ClosetGuiFUE @ sluggishness;
    visible = 0;
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = (10.0 - getWord(%buttonPosition, 0)) @ " " @ (10.0 - getWord(%buttonPosition, 1));
    extent = "123 82";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/closetGuiFUE_step4_active";
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = 759.0 @ (ClosetTabContainer + getWord(getPosition(), 0)) @ " " @ 492.0 @ (ClosetTabContainer + getWord(getPosition(), 0));
    extent = "123 82";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/closetGuiFUE_step5_active";
    %newActiveStep = ;
    profile = GuiControl @ new ""() @ "ETSNonModalProfile";
    0;
    horizSizing = ClosetGuiFUE @ horizSizing;
    vertSizing = ClosetGuiFUE @ vertSizing;
    position = "0 0";
    extent = ClosetGuiFUE @ extent;
    minExtent = ClosetGuiFUE @ minExtent;
    sluggishness = ClosetGuiFUE @ sluggishness;
    visible = 0;
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = (10.0 - getWord(%buttonPosition, 0)) @ " " @ (10.0 - getWord(%buttonPosition, 1));
    extent = "123 82";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/closetGuiFUE_step4_inactive";
    profile = GuiBitmapCtrl @ new ""() @ "ETSNonModalProfile";
    horizSizing = "right";
    vertSizing = "bottom";
    position = 759.0 @ (ClosetTabContainer + getWord(getPosition(), 0)) @ " " @ 492.0 @ (ClosetTabContainer + getWord(getPosition(), 0));
    extent = "123 82";
    minExtent = "1 1";
    sluggishness = -1;
    visible = 1;
    bitmap = "platform/client/ui/closetGuiFUE_step5_inactive";
    %newInactiveStep = ;
    %this.addStepWithName(%newActiveStep, %newInactiveStep, "Snapshot");
    refreshingOrInitializing = 0 @ %this;
    initialized = 1 @ %this;
};
function closetGuiFUEHideTipsCtrl::onAction(%this) {
    %this.hideTips();
    %this.showTips();
};
function closetGuiFUEHideTipsCtrl::hideTips(%this) {
    %sched = gGetField(%this, "closetGuiFUEHideTipsCtrlShowOrHideTipsSched");
    refreshingOrInitializing;
    cancel(%sched);
    %sched = %this.schedule(250);
    showOrHideTips;
    gSetField(%this, "closetGuiFUEHideTipsCtrlShowOrHideTipsSched", %sched);
    return ClosetGuiFUE;
    %i = 0;
    stepContainers.setVisible(0);
    stepContainers.setVisible(0);
    %i = (1.0 + %i);
    ($gClosetGuiFueStepCount < %i) TAB %i @ "active" @ ClosetGuiFUE TAB %i @ "inactive" @ ClosetGuiFUE @ isObject(stepContainers) TAB %i @ "inactive" @ ClosetGuiFUE;
};
function closetGuiFUEHideTipsCtrl::showTips(%this) {
    %sched = gGetField(%this, "closetGuiFUEHideTipsCtrlShowOrHideTipsSched");
    refreshingOrInitializing;
    cancel(%sched);
    %sched = %this.schedule(250);
    showOrHideTips;
    gSetField(%this, "closetGuiFUEHideTipsCtrlShowOrHideTipsSched", %sched);
    return ClosetGuiFUE;
    %i = 0;
    stepContainers.setVisible(($gClosetGuiFueCurrentStep == %i));
    stepContainers.setVisible(($gClosetGuiFueCurrentStep != %i));
    %i = (1.0 + %i);
    ($gClosetGuiFueStepCount < %i) TAB %i @ "active" @ ClosetGuiFUE TAB %i @ "inactive" @ ClosetGuiFUE @ isObject(stepContainers) TAB %i @ "inactive" @ ClosetGuiFUE;
};
