$Net::BaseDomain = "vside.com";
$Net::BaseURL = "http://" @ $Net::BaseDomain @ "/envmanager/login";
$Net::AIMInvite = "has invited you to join " @ $ETS::AppName @ ": ";
$Net::AIMInviteURL = $Net::BaseDomain @ "/?";
$pref::precipitationDensity = 0.2;
$Pref::Net::DisplayOnMaster = 0;
$UserPref::Player::AIMName = "";
$UserPref::Player::Name = "";
$UserPref::Player::DefaultFOV = 90;
$Pref::Player::CurrentFOV = 0;
$Pref::Player::zoomSpeed = 0;
$UserPref::player::outfitName = "A";
$UserPref::Player::height = $Defaults::UserPref::Player::height = 1;
$UserPref::Player::gender = "f";
$UserPref::Player::hasAIMAccount = 0;
$UserPref::Player::filterProfanity = $Defaults::UserPref::Player::filterProfanity = 1;
$UserPref::Player::awayMessage = $Pref::Player::defaultAwayMessage;
$UserPref::Player::autoReplyToWhispersWhenAway = $Defaults::UserPref::Player::autoReplyToWhispersWhenAway = 1;
$UserPref::Player::TeleportBlock = $Defaults::UserPref::Player::TeleportBlock = 0;
$UserPref::Player::WhisperBlock = $Defaults::UserPref::Player::WhisperBlock = 0;
$UserPref::Player::YellBlock = $Defaults::UserPref::Player::YellBlock = 0;
$UserPref::Player::showOnRadar = $Defaults::UserPref::Player::showOnRadar = 1;
$UserPref::Player::pointAt = 0;
$UserPref::Player::EmotesPermissionFriends = $Defaults::UserPref::Player::EmotesPermissionFriends = 1;
$UserPref::Player::EmotesPermissionStrangers = $Defaults::UserPref::Player::EmotesPermissionStrangers = 1;
$UserPref::Player::GiftsPermissionFriends = $Defaults::UserPref::Player::GiftsPermissionFriends = 1;
$UserPref::Player::GiftsPermissionStrangers = $Defaults::UserPref::Player::GiftsPermissionStrangers = 1;
$UserPref::Login::firstRun = 1;
$UserPref::Login::showLoginOptions = 0;
$UserPref::Login::RememberMe = 1;
$UserPref::Login::UseAIM = 0;
$UserPref::Login::completedRegistrations = "";
$UserPref::AIM::RememberMe = 0;
$UserPref::Snapshots::View = 0;
$UserPref::Chat::ShowTyping = $Defaults::UserPref::Chat::ShowTyping = 1;
$UserPref::Chat::PinBubble = $Defaults::UserPref::Chat::PinBubble = 0;
$Pref::Net::LagThreshold = 400;
$Pref::Net::Port = 28000;
$Pref::shadows = 2;
$Pref::HudMessageLogSize = 40;
$Pref::ChatHudLength = 3;
$Chat::Preview::Period = 1200;
$Chat::Preview::Size = 30;
$Chat::Preview::ShowOwn = !1;
$Chat::Preview::WordBoundaries = 1;
$Chat::Preview::IsNoLongerTypingDelay = 1000 * 5;
$Chat::Preview::ChatPreviewTimeout = 1000 * 10;
$Pref::Input::LinkMouseSensitivity = 1;
$Pref::Input::MouseEnabled = 1;
$Pref::Input::JoystickEnabled = 0;
$Pref::Input::KeyboardTurnSpeed = 0.05;
$Pref::sceneLighting::cacheSize = -1;
$Pref::sceneLighting::purgeMethod = "lastCreated";
$Pref::sceneLighting::cacheLighting = 1;
$Pref::sceneLighting::terrainGenerateLevel = 1;
$pref::TS::detailAdjust = 1;
$pref::TS::ToonColorOffsetFill = "0.3 0.3 0.3 0";
$pref::TS::ToonColorOffsetEdge = "0 0 0 0";
$pref::Terrain::dynamicLights = 1;
$pref::Interior::TexturedFog = 0;
$pref::Interior::swatchTextureFolder = $gBitmapCategoryRoot["swatch"];
$Interior::insideDistanceFalloff = 10;
$Pref::Video::DisplayDevice = "OpenGL";
$Pref::Video::allowOpenGL = 1;
$Pref::Video::allowD3D = 0;
$Pref::Video::preferOpenGL = 1;
$Pref::Video::appliedPref = 0;
$Pref::Video::defaultsRenderer = "Intel 915GM";
$Pref::Video::disableVerticalSync = 1;
$Pref::Video::monitorNum = 0;
$Pref::Video::profiledRenderer = "Intel 915GM";
$Pref::Video::Fullscreen = 0;
$Pref::Video::SafeModeOn = 0;
$UserPref::Video::Resolution = $Defaults::UserPref::Video::resolution = "960 544";
$UserPref::Video::ConstrainWindowDimensions = $Defaults::UserPref::Video::ConstrainWindowDimensions = 1;
$Pref::Video::screenShotFormat = "JPEG";
$UserPref::ETS::VideoRenderer::Disable = 0;
$renderQuality = 1;
$UserPref::Video::renderQualitySetting = $Defaults::UserPref::Video::renderQuality = 1;
$UserPref::Video::shadowQualitySetting = $Defaults::UserPref::Video::shadowQuality = 1;
$UserPref::Video::smalltextureQualitySetting = $Defaults::UserPref::Video::smalltextureQuality = 2;
$UserPref::Video::visibledistanceQualitySetting = $Defaults::UserPref::Video::visibledistanceQuality = 1;
$UserPref::Video::waterreflectionQualitySetting = $Defaults::UserPref::Video::waterreflectionQuality = 0;
$UserPref::Video::exposureQualitySetting = $Defaults::UserPref::Video::exposureQuality = 0;
$UserPref::Display::farNameOpacity = $Defaults::UserPref::Display::farNameOpacity = 0;
$UserPref::Display::hideNames = $Defaults::UserPref::Display::hideNames = 0;
$UserPref::Display::hideChat = $Defaults::UserPref::Display::hideChat = 0;
$UserPref::debug::alertOnLogWarning = $Defaults::UserPref::debug::alertOnLogWarning = 0;
$UserPref::debug::alertOnLogError = $Defaults::UserPref::debug::alertOnLogError = 0;
$UserPref::UI::Radar::AutoOpen = $Defaults::UserPref::UI::Radar::AutoOpen = 1;
$UserPref::UI::ShoutOut::Show::Me = $Defaults::UserPref::UI::ShoutOut::Show::Me = 1;
$UserPref::UI::ShoutOut::Show::Chat = $Defaults::UserPref::UI::ShoutOut::Show::Chat = 1;
$UserPref::UI::ShoutOut::Show::Pic = $Defaults::UserPref::UI::ShoutOut::Show::Pic = 1;
$UserPref::UI::ShoutOut::Twitter::Include = $Defaults::UserPref::UI::ShoutOut::Twitter::Include = 1;
$UserPref::UI::ShoutOut::FB::Include = $Defaults::UserPref::UI::ShoutOut::FB::Include = 1;
$UserPref::UI::ShoutOut::Ticker::Include = $Defaults::UserPref::UI::ShoutOut::Ticker::Include = 1;
$Pref::DF::debugMode = $Defaults::pref::DF::debugMode = 0;
$Pref::DF::showDefaults = $Defaults::pref::DF::showDefaults = 0;
$pref::TS::bodyMod = $Defaults::pref::TS::bodyMod = 0;
$UserPref::Video::shapeNameFontSize = $Defaults::UserPref::Video::shapeNameFontSize = 1;
$UserPref::Video::Exposure = $Defaults::UserPref::Video::Exposure = 0.5;
$pref::Video::findBestFitWhenTooLarge = 1;
$Video::allowResize = 0;
$pref::OpenGL::force16BitTexture = 0;
$pref::OpenGL::forcePalettedTexture = 0;
$pref::OpenGL::maxHardwareLights = 8;
$Pref::OpenGL::anisotropy = 1;
$pref::OpenGL::allowCompression = 1;
$Pref::OpenGL::compressionHint = 0;
$Pref::OpenGL::mipReduction = 0;
$Pref::OpenGL::interiorMipReduction = 0;
$Pref::OpenGL::skyMipReduction = 0;
$pref::OpenGL::resizedBitmapLoadingIsEnabled = 1;
if ($Platform $= "windows")
{
    $pref::OpenGL::disableEXTCompiledVertexArray = $Platform::Version::Major == 6;
}
$pref::visibleDistanceMod = 1;
$pref::TS::sgShadowDetailSize = 1000;
$pref::TS::ShadowDown = 1;
$pref::TS::distMouseOver = 28;
$pref::TS::distBadgesVis = 6;
$Pref::Audio::driver = "OpenAL";
$Pref::Audio::forceMaxDistanceUpdate = 0;
$Pref::Audio::environmentEnabled = 0;
$Pref::LOD::FPSThreshold = 15;
$Pref::LOD::ModLow = 2;
$Pref::LOD::ModMed = 1.5;
$Pref::LOD::ModHigh = 1;
$UserPref::Audio::mute = $Defaults::UserPref::Audio::mute = 0;
$UserPref::Audio::masterVolume = $Defaults::UserPref::Audio::masterVolume = 0.9;
$UserPref::Audio::channelVolume1 = $Defaults::UserPref::Audio::channelVolume1 = 0.4;
$UserPref::Audio::channelVolume2 = $Defaults::UserPref::Audio::channelVolume2 = 1;
$UserPref::Audio::channelVolume3 = 0.8;
$UserPref::Audio::channelVolume4 = 0.8;
$UserPref::Audio::channelVolume5 = 0.8;
$UserPref::Audio::channelVolume6 = 0.8;
$UserPref::Audio::channelVolume7 = 0.8;
$UserPref::Audio::channelVolume8 = 0.8;
$UserPref::Audio::NotifyChat = $Defaults::UserPref::Audio::NotifyChat = 1;
$UserPref::Audio::NotifyWhisper = $Defaults::UserPref::Audio::NotifyWhisper = 1;
$UserPref::UI::FlashTaskBar = $Defaults::UserPref::UI::FlashTaskBar = 1;
$UserPref::UI::ShowAccountHud = $Defaults::UserPref::UI::ShowAccountHud = 1;
$UserPref::UI::ShowTooltips = $Defaults::UserPref::UI::ShowTooltips = 1;
$UserPref::UI::ShowReloadTextures = $Defaults::UserPref::UI::ShowReloadTextures = 0;
$UserPref::buddies::collapsedLists["FriendsOnline"] = 0;
$UserPref::buddies::collapsedLists["WaitingForYourApproval"] = 0;
$UserPref::buddies::collapsedLists["YourPendingRequests"] = 0;
$UserPref::buddies::collapsedLists["InTransit"] = 0;
$UserPref::emotes::collapsedLists["Mood"] = 0;
$UserPref::emotes::collapsedLists["FavoriteActions"] = 0;
$UserPref::emotes::collapsedLists["Expressions"] = 1;
$UserPref::emotes::collapsedLists["Gestures"] = 1;
$UserPref::emotes::collapsedLists["DancesLounge"] = 1;
$UserPref::emotes::collapsedLists["DancesBreak"] = 1;
$UserPref::emotes::collapsedLists["DancesThrilla"] = 1;
$UserPref::emotes::collapsedLists["DancesGoGo"] = 1;
$UserPref::emotes::collapsedLists["DancesHipHop"] = 1;
$UserPref::emotes::collapsedLists["DancesJB"] = 1;
$UserPref::emotes::collapsedLists["DancesGoth"] = 1;
$Defaults::UserPref::emotes::defaultKeyCombinations = "F08" TAB "F09" TAB "F10" TAB "F11" TAB "F12" TAB "ctrl1" TAB "ctrl2" TAB "ctrl3" TAB "ctrl4" TAB "ctrl5" TAB "ctrl6" TAB "ctrl7" TAB "ctrl8" TAB "ctrl9" TAB "ctrl0";
$UserPref::emotes["f","F08"] = $Defaults::UserPref::emotes["f","F08"] = "LingyLicious" ;
$UserPref::emotes["m","F08"] = $Defaults::UserPref::emotes["m","F08"] = "The Tantrum" ;
$UserPref::emotes["f","F09"] = $Defaults::UserPref::emotes["f","F09"] = "Mooncurl" ;
$UserPref::emotes["m","F09"] = $Defaults::UserPref::emotes["m","F09"] = "Hikhoo" ;
$UserPref::emotes["f","F10"] = $Defaults::UserPref::emotes["f","F10"] = "The Coed" ;
$UserPref::emotes["m","F10"] = $Defaults::UserPref::emotes["m","F10"] = "The 101" ;
$UserPref::emotes["f","F11"] = $Defaults::UserPref::emotes["f","F11"] = "ROTFL" ;
$UserPref::emotes["m","F11"] = $Defaults::UserPref::emotes["m","F11"] = "ROTFL" ;
$UserPref::emotes["f","F12"] = $Defaults::UserPref::emotes["f","F12"] = "Wave" ;
$UserPref::emotes["m","F12"] = $Defaults::UserPref::emotes["m","F12"] = "Wave" ;
$UserPref::emotes["f","ctrl1"] = $Defaults::UserPref::emotes["f","ctrl1"] = "Funkie Chicken" ;
$UserPref::emotes["m","ctrl1"] = $Defaults::UserPref::emotes["m","ctrl1"] = "Im So Sexy" ;
$UserPref::emotes["f","ctrl2"] = $Defaults::UserPref::emotes["f","ctrl2"] = "In Your Pocket" ;
$UserPref::emotes["m","ctrl2"] = $Defaults::UserPref::emotes["m","ctrl2"] = "WooWho" ;
$UserPref::emotes["f","ctrl3"] = $Defaults::UserPref::emotes["f","ctrl3"] = "Rising Sun" ;
$UserPref::emotes["m","ctrl3"] = $Defaults::UserPref::emotes["m","ctrl3"] = "Rising Sun" ;
$UserPref::emotes["f","ctrl4"] = $Defaults::UserPref::emotes["f","ctrl4"] = "Watching You" ;
$UserPref::emotes["m","ctrl4"] = $Defaults::UserPref::emotes["m","ctrl4"] = "Crump-a-GoGo" ;
$UserPref::emotes["f","ctrl5"] = $Defaults::UserPref::emotes["f","ctrl5"] = "Slip-n-Slide" ;
$UserPref::emotes["m","ctrl5"] = $Defaults::UserPref::emotes["m","ctrl5"] = "Slip-n-Slide" ;
$UserPref::emotes["f","ctrl6"] = $Defaults::UserPref::emotes["f","ctrl6"] = "Boogaloo" ;
$UserPref::emotes["m","ctrl6"] = $Defaults::UserPref::emotes["m","ctrl6"] = "VStep" ;
$UserPref::emotes["f","ctrl7"] = $Defaults::UserPref::emotes["f","ctrl7"] = "Trixie Rock" ;
$UserPref::emotes["m","ctrl7"] = $Defaults::UserPref::emotes["m","ctrl7"] = "TopRock" ;
$UserPref::emotes["f","ctrl8"] = $Defaults::UserPref::emotes["f","ctrl8"] = "CC-Six-Step" ;
$UserPref::emotes["m","ctrl8"] = $Defaults::UserPref::emotes["m","ctrl8"] = "Six-Step" ;
$UserPref::emotes["f","ctrl9"] = $Defaults::UserPref::emotes["f","ctrl9"] = "The JFecks" ;
$UserPref::emotes["m","ctrl9"] = $Defaults::UserPref::emotes["m","ctrl9"] = "Windmill" ;
$UserPref::emotes["f","ctrl0"] = $Defaults::UserPref::emotes["f","ctrl0"] = "HollowBack" ;
$UserPref::emotes["m","ctrl0"] = $Defaults::UserPref::emotes["m","ctrl0"] = "Baby Freeze" ;
$Pref::Wardrobe::playerHeightMin = 0.855;
$Pref::Wardrobe::playerHeightMax = 1.146;
$Pref::Wardrobe::playerHeightWidthFactor = 0;
$Pref::ETS::OpenGL::TransparentDifFix = 1;
$Pref::ETS::Conv::tailAgeMin = 0;
$Pref::ETS::Conv::tailAgeHld = 3;
$Pref::ETS::Conv::tailAgeMax = 10;
$Pref::ETS::Conv::tailLenMin = 10;
$Pref::ETS::Conv::tailLenMax = 100;
$Pref::ETS::SeatMarkerVisibleDistanceSQUARED = 16;
$Pref::ETS::ButtonBar::timeout = 5000;
$UserPref::ETS::ButtonBar::AutoHide = $Defaults::UserPref::ETS::ButtonBar::AutoHide = 0;
$Pref::ETS::HudTabs::timeout = 7000;
$UserPref::HudTabs::AutoOpen["music"] = $Defaults::UserPref::HudTabs::AutoOpen["music"] = 1;
$UserPref::HudTabs::AutoClose["music"] = $Defaults::UserPref::HudTabs::AutoClose["music"] = 1;
$UserPref::HudTabs::AutoOpen["affinity"] = $Defaults::UserPref::HudTabs::AutoOpen["affinity"] = 1;
$UserPref::HudTabs::AutoClose["affinity"] = $Defaults::UserPref::HudTabs::AutoClose["affinity"] = 1;
$UserPref::HudTabs::AutoOpen["scores"] = $Defaults::UserPref::HudTabs::AutoOpen["scores"] = 0;
$UserPref::HudTabs::AutoClose["scores"] = $Defaults::UserPref::HudTabs::AutoClose["scores"] = 1;
$UserPref::HudTabs::AutoOpen["word"] = $Defaults::UserPref::HudTabs::AutoOpen["word"] = 1;
$UserPref::HudTabs::AutoClose["word"] = $Defaults::UserPref::HudTabs::AutoClose["word"] = 1;
$UserPref::HudTabs::AutoOpen["tutorial"] = $Defaults::UserPref::HudTabs::AutoOpen["tutorial"] = 1;
$UserPref::HudTabs::AutoClose["tutorial"] = $Defaults::UserPref::HudTabs::AutoClose["tutorial"] = 0;
$UserPref::General::onQuitVisitWebProfile = $Defaults::UserPref::General::onQuitVisitWebProfile = 1;
$pref::Water::RenderSpecular = 0;
$UserPref::ETS::ShowCamPos = 0;
$UserPref::ETS::AssignFlower = 0;
$UserPref::ETS::AssignFlowerSeconds = 3600;
$UserPref::Performer::AutoOpenPanel = $Defaults::UserPref::Performer::AutoOpenPanel = 1;
$UserPref::slideshow::random = $Defaults::UserPref::slideshow::random = 0;
$UserPref::Spaces::Granularity = $Defaults::UserPref::Spaces::Granularity = 4;
$UserPref::Spaces::ShowSelected = $Defaults::UserPref::Spaces::ShowSelected = 1;
$UserPref::Spaces::FaceSelected = $Defaults::UserPref::Spaces::FaceSelected = 0;
$pref::benchmarks::rootPath = $devMod @ "/benchmarks";
$pref::benchmarks::dataPath = $pref::benchmarks::rootPath @ "/data";
$pref::benchmarks::cameraPeriod = 2500;
$pref::benchmarks::fps::reps = 1;
$pref::benchmarks::fps::countTris = 1;
$pref::benchmarks::metricsLock = 1;
$pref::benchmarks::fps::countTris = 1;
$pref::benchmarks::cameraScreenshots = 1;
$fxEts::TODTimerPeriod = 30 * 1000;
$fxEts::TODTimerID = 0;
$pref::fxEts::TODNotInside = 0;
$ButtonBarVar::VerticalAdjustment = 0;
$ButtonBarVar::Initialized = 0;
$ButtonBarVar::Hidden = 0;
$Platform::CanSleepInBackground = 0;
$Player::VPoints = 0;
$Player::VBux = 0;
$Net::userOwner = "";
exec("./default_owner.cs", 0);
if ($Net::userOwner $= "")
{
    $Net::userOwner = "doppelganger";
}
$VURLcmd = "";

