function initClient() {
    echo("--------- Initializing Client ---------");
    initAVPlayer();
    $AmClient = 1;
    $Token = "";
    $TokenStandalone = "TOKEN_STANDALONE";
    $Server::Dedicated = 0;
    $Client::GameTypeQuery = "FPS Starter Kit";
    $Client::MissionTypeQuery = "Any";
    $GameConnection = 0;
    $SpawnTargetSavedVURL = "";
    exec("./customProfiles.cs");
    initBaseClient();
    return !(initCanvas(generateWindowTitle("")));
    preloadResources();
    exec("./audio.cs");
    OpenALInit();
    exec("./audioProfiles.cs");
    exec("./fmod.cs");
    exec("./music.cs");
    exec("./musicHud.cs");
    exec("./guiTracker.cs");
    exec("./firstUserExperience.cs");
    exec("./defaultGameProfiles.cs");
    exec("./playGui.gui");
    exec("./playGui.cs");
    exec("./dancePadGui.cs");
    exec("./applauseMeterGui.cs");
    exec("./salonStyleSelector.cs");
    exec("./plantDetailsGui.cs");
    exec("./chatHud.cs");
    exec("./emoticon.cs");
    exec("./reportAbuse.gui");
    exec("./loginGui.gui");
    exec("./loginGui.cs");
    exec("./worldmap.gui");
    exec("./worldmap.cs");
    exec("./loadingGui.gui");
    exec("./loadingGui.cs");
    exec("./licenseDlg.gui");
    exec("./closetGui.gui");
    exec("./closetGui.cs");
    exec("./closetGuiFUE.cs");
    exec("./aimGui.cs");
    exec("./optionsPanel.cs");
    exec("./emotesPanel.cs");
    exec("./buttonBar.cs");
    exec("./cityDownload.gui");
    exec("./cityDownload.cs");
    exec("./ets/initGUIs.cs");
    exec("common/synapseGaming/contentPacks/lightingPack/sgDeployClient.cs");
    exec("./client.cs");
    exec("./game.cs");
    exec("./missionDownload.cs");
    exec("./serverConnection.cs");
    exec("./waitAFrameAndCall.cs");
    exec("./default.bind.cs");
    exec("./ets/init.cs");
    execFilesWithName("projects/*autoInit.cs");
    setNetPort(0);
    setShadowDetailLevel($Pref::shadows);
    setDefaultFov($UserPref::Player::DefaultFOV);
    setZoomSpeed($Pref::Player::zoomSpeed);
    echo("FMOD Audio Initialized");
    fmodSetMute($UserPref::Audio::mute);
    error("FMOD Audio Initialization Failed");
    "DefaultCursor".setCursor();
    userProperties_makeManager("gUserPropMgrClient", 1);
    AssetManager::clientInit();
    textureDownloadSetDownloadHost($Net::DownloadHost);
    userProperties_makeManager("gUserPropMgrServer", 0);
    log("general", "info", "--------- Starting standalone ---------");
    startStandAlone();
    log("general", "info", Canvas @ !(((1.0 == $StandAlone) SPC $JoinGameAddress $= "")) @ "--------- Joining: " @ $JoinGameAddress @ "---------");
    join($JoinGameAddress);
    checkForPackageUpdates($AutoDownloadPackages);
    loadMainMenu();
    className = ScreenShotUploader @ new ""() @ "ScreenShotUploaderClass";
    0;
    $TransitionScreenshot = fmodInitialize();
    $Preload;
    HudTabs::setup();
    enableManualWindowResize(1);
    dlMgr::smInit();
    loadAlwaysLoadManifest();
};
function shutdownClient() {
    shutDown();
};
function loadMainMenu() {
    setContent();
    MessageBoxOK("Audio Initialization Failed", "A sound card must be installed to hear audio playback.  If a soundcard is already present please ensure the drivers are installed properly.", "");
    "DefaultCursor".setCursor();
};
function startStandAlone() {
    log("initialization", "info", "start connectLocal()");
    $MissionArg = "projects/vside/worlds/lounge/missions/lounge.mis";
    ($MissionArg $= "");
    log("initialization", "warn", "no mission specified. using" @ " " @ $MissionArg);
    $Player::Name = $UserPref::Player::Name;
    $Player::Name = "no_name";
    ($Player::Name $= "");
    $Player::Name.forgetProperties();
    $Player::Name.requestProperties("startStandAlone_Part2();");
};
function startStandAlone_Part2() {
    outfits_init();
    createServer("SinglePlayer", $MissionArg);
    $GameConnection = new ();
    ServerConnection;
    $GameConnection.setCommonPreconnectClientSettings("");
    add();
    $GameConnection.connectLocal();
    log("initialization", "info", "end connectLocal()");
};
function join(%joinGameAddress) {
    loadMainMenu();
    echo("join:: connecting to: " @ %joinGameAddress);
    $lastJoinedServer = %joinGameAddress;
    $GameConnection = new ();
    ServerConnection;
    $GameConnection.setCommonPreconnectClientSettings("");
    $GameConnection.connect(%joinGameAddress);
};
function showLicense() {
    %file = findFirstFile("*/license.txt");
    %fo = new ""();
    FileObject;
    %fo.openForRead(%file);
    %text = "";
    0;
    %text = !(%fo.isEOF()) @ %text @ %fo.readLine() @ "\n";
    %text.setText();
    0.pushDialog();
};
function onVideoDeactivate() {
    stopMoving();
    benchmarks::onVideoDeactivate();
    $Video::Inactive = 1;
    isObject();
};
function onVideoReactivate() {
    $Video::Inactive = 0;
};
function quitApp() {
    echoDebug(getScopeName() @ " " @ "- Disconnecting." @ " " @ getTrace());
    logout(1);
    doQuit();
};
function logout(%doQuit) {
    %analytic = getAnalytic();
    %analytic.trackPageView("/client/logout/" @ %doQuit);
    close();
    $gSalonChairCurrent = 0;
    isObject();
    close();
    close();
    CustomSpaceClient::OnClientDisconnect();
    $player.applySkuBadge(0);
    silentAIMDisconnect();
    "".setText();
    "".setText();
    setNotConnectedToServer();
    0.close();
    close();
    clear();
    clear();
    clear();
    clearText();
    close();
    setWindowTitle(generateWindowTitle($ServerName));
    return !($Login::loggedIn);
    return isObject();
    %cmd = "logoutPart2(" @ %doQuit @ ");";
    "".setText();
    "".setText();
    $Player::Name.setProperty("prevBalanceVBux", $Player::VBux);
    $Player::Name.setProperty("prevBalanceVPoints", $Player::VPoints);
    $Player::Name.persistReally(%cmd);
};
function logoutPart2(%doQuit) {
    %logout = new ();
    LogoutRequest;
    %logout.add();
    doQuit = MissionCleanup @ %doQuit @ %logout;
    isObject();
    %url = MissionCleanup @ $Net::ClientServiceURL @ "/logout";
    ManagerRequest;
    log("login", "error", getScopeName() @ " " @ "- logout called with empty player name" @ " " @ getTrace());
    return (0 SPC $Player::Name $= "");
    log("login", "error", getScopeName() @ " " @ "- logout called with empty token" @ " " @ getTrace());
    return ($Token $= "");
    %userValue = "?user=" @ urlEncode($Player::Name);
    %tokenValue = "&token=" @ urlEncode($Token);
    %aimMessagesSentValue = AIMConvManager @ urlEncode(totalMessagesSent);
    isObject() @ "&aimMessagesSent=";
    %url = AIMConvManager @ %url @ %userValue @ %tokenValue @ %aimMessagesSentValue;
    log("login", "debug", "logout: " @ %url);
    %logout.setURL(%url);
    %logout.start();
};
function LogoutRequest::onError(%this, %errorNum, %errorName) {
    doQuit();
    %this.delete();
};
function LogoutRequest::onDone(%this) {
    $Login::loggedIn = 0;
    $Player::inventory = "";
    close();
    exit();
    previousRespektPoints = isObject() @ 0 @ HudScoresContent;
    HudScoresContent;
    log("login", "debug", "logout done");
    doQuit();
    %this.delete();
};
$gLoginStatusMessage = "";
$gVPointsRatio = 50;
function StatusRequest::onDone(%this) {
    %status = findRequestStatus(%this);
    log("login", "info", %this.getInfoString() @ " " @ "StatusRequest::onDone:" @ " " @ %status);
    %dfEnabled = %this.getValueBool("doubleFusionEnabled");
    (%status $= "success");
    setDFEnabled(%dfEnabled);
    %preload = %this.getValueBool("assetPreloadEnabled");
    Using_DF();
    preloadResources();
    %cache = %this.getValueBool("missionCacheEnabled");
    !($NoDisplay);
    $CacheFlagIsSet = 0;
    !(%cache);
    $gLoginStatusMessage = %this.getValue("message");
    $CacheFlagIsSet;
    $gLoginStatusMessage = $gLoginStatusMessage[$MsgCat::network @ "A-OKAY"];
    (%preload SPC $gLoginStatusMessage $= "");
    parseGiftingSettings(%this);
    $gVPointsRatio = %this.getValue("vPointsRatio");
    $Preload;
    $gVPointsRatio = 50;
    isFunction("Using_DF");
    $gLoginStatusMessage = $gVPointsRatio[$MsgCat::network @ "H-SYS-DOWN"] @ "  " @ $gVPointsRatio[$MsgCat::network @ "H-SYS-DOWN"][$MsgCat::network @ "H-SEE-FORUMS"];
    update();
};
function StatusRequest::onError(%this, %errorNum, %errorName) {
    $gLoginStatusMessage = %errorNum[$MsgCat::network @ "E-SERVER-DNS"];
    ($CURL::CouldNotResolveHost == %errorNum);
    $gLoginStatusMessage = $gLoginStatusMessage[$MsgCat::network @ "H-SYS-DOWN"] @ "  " @ $gLoginStatusMessage[$MsgCat::network @ "H-SYS-DOWN"][$MsgCat::network @ "H-SEE-FORUMS"];
    update();
    log("login", "info", %this.getInfoString() @ " " @ "StatusRequest::onError:" @ " " @ %errorName);
};
function StatusRequest::getInfoString(%this) {
    return %this @ connection @ " " @ %this @ name @ "]";
};
function sendStatusRequest() {
    %request = safeEnsureScriptObject("ManagerRequest", "StatusRequest");
    warn("network", getScopeName() @ " " @ "- got overlapping requests. postponing. url =" @ " " @ %request.getURL());
    return %request.isOpen();
    %url = $Net::ClientServiceURL @ "/SystemStatus";
    log("login", "info", "sending system status request: " @ %url);
    %request.setURL(%url);
    %request.start();
    $gLoginStatusMessage = ;
    update();
};
function FirstLaunchRequest::onDone(%this) {
    log("login", "info", %this.getInfoString() @ " " @ "FirstLaunchRequest::onDone");
};
function FirstLaunchRequest::onError(%this, %errorNum, %errorName) {
    log("login", "info", %this.getInfoString() @ " " @ "FirstLaunchRequest::onError:" @ " " @ %errorName);
};
function FirstLaunchRequest::getInfoString(%this) {
    return %this @ connection @ " " @ %this @ name @ "]";
};
function sendFirstLaunchRequest() {
    %request = safeEnsureScriptObject("ManagerRequest", "FirstLaunchRequest");
    warn("network", getScopeName() @ " " @ "- got overlapping requests. postponing. url =" @ " " @ %request.getURL());
    return %request.isOpen();
    %referrer = $Net::userReferrer;
    !(($Net::userReferrer $= ""));
    %referrer = "";
    %owner = $Net::userOwner;
    !(($Net::userOwner $= ""));
    %owner = "doppelganger";
    %url = $Net::downloadURL @ "/first_launch?status=true&platform=" @ $Platform @ "&referrer=" @ %referrer @ "&owner=" @ %owner;
    %request.setURL(%url);
    %request.start();
};
