$musicStreamNameMap = 0;
$musicStreamIDMap = 0;
function Music::init() {
    %fmod = new ();
    FMod;
    add();
    %fmod.init($UserPref::Audio::mute);
    $Music::lastPos = "0 0 0";
    FMod;
};
function Music::setService(%service) {
    $Music::service = %service;
    %service.setMusicService();
};
function Music::adjustVolume() {
    %soundPos = $Music::service.getAttenuation();
    return (!(isObject($player)) SPC %soundPos $= "");
    %pos = $player.getPosition();
    Music::attenuate(%pos, %soundPos, 30, $Music::service.getSourceVolume());
    $Music::lastPos = %pos;
    ($Music::lastPos != %pos);
};
function musicAttenuationTimer() {
    Music::adjustVolume();
    schedule(250, 0, "musicAttenuationTimer");
    $Music::lastPos = "0 0 0";
    !(($Music::service.getAttenuation() $= ""));
};
function Music::attenuate(%playerPos, %soundPos, %maxDistance, %maxVolume) {
    %dist = VectorLen(VectorDist(%playerPos, %soundPos));
    %dist = %maxDistance;
    (%maxDistance > %dist);
    %vol = (%maxVolume * ((%maxDistance / %dist) - 1.0));
    $Music::service.setVolume(%vol);
};
function Music::setMuted(%flag) {
    Music::toggleMute();
};
function Music::toggleMute() {
    $UserPref::Audio::mute = !($UserPref::Audio::mute);
    %multiplier = 1;
    0;
    alxListenerf(($UserPref::Audio::masterVolume * %multiplier));
    $Music::service.setMute($UserPref::Audio::mute);
    $Music::service.setMasterVolume(($UserPref::Audio::channelVolume1 * ($UserPref::Audio::masterVolume * %multiplier)));
    fmodSetMute($UserPref::Audio::mute);
    $UserPref::Audio::mute.setMuted();
    updateText();
    $UserPref::Audio::mute.setValue();
    ffmpegSetMasterVolume(($UserPref::Audio::channelVolume1 * ($UserPref::Audio::masterVolume * %multiplier)));
    schedulePersist();
    update();
};
function doRateSong(%rating) {
    Music::rateSong(%rating);
};
function Music::rateSong(%rating) {
    %request = safeEnsureScriptObject("ManagerRequest", "RatingRequest");
    warn("network", getScopeName() @ " " @ "- got overlapping requests. postponing. url =" @ " " @ %request.getURL());
    cancel(timer);
    timer = %request @ schedule(100, 0, "doRateSong", %rating) @ %request;
    %request.isOpen();
    return;
    user_rating = %rating @ %request;
    %url = $Net::ClientServiceURL @ "/RateSong?";
    %val1 = "user=" @ urlEncode($Player::Name);
    %val2 = "&token=" @ urlEncode($Token);
    %val3 = "&artist=" @ urlEncode($Music::service.getArtist(), 255);
    %val4 = "&album=" @ urlEncode($Music::service.getAlbum(), 255);
    %val5 = "&song=" @ urlEncode($Music::service.getTitle(), 255);
    %val6 = "&rating=" @ urlEncode(%rating);
    warn((("&artist=" $= %val3) SPC "&song=" $= %val5) @ "did not have artist and song name, not sending rating request: " @ %url);
    return;
    %url = %url @ %val1 @ %val2 @ %val3 @ %val4 @ %val5 @ %val6;
    log("communication", "debug", "sending RatingRequest for rateSong: " @ %url);
    %request.setURL(%url);
    log("communication", "debug", !(%request.start()) @ "failed to send RatingRequest for rateSong: " @ %url);
};
function Music::fetchRatings(%artist, %title, %album) {
    return !(haveValidManagerHost());
    log("communication", "debug", "the get_song_ratings request will not be made because we don't have a valid user or token");
    return (($Player::Name $= "") SPC $Token $= "");
    %request = safeEnsureScriptObject("ManagerRequest", "RatingRequest");
    warn("network", getScopeName() @ " " @ "- got overlapping requests. aborting. url =" @ " " @ %request.getURL());
    return %request.isOpen();
    user_rating = 0 @ %request;
    %url = $Net::ClientServiceURL @ "/GetSongRating?";
    %val1 = "user=" @ urlEncode($Player::Name);
    %val2 = "&token=" @ urlEncode($Token);
    %val3 = "&artist=" @ urlEncode(%artist, 255);
    %val4 = "&album=" @ urlEncode(%album, 255);
    %val5 = "&song=" @ urlEncode(%title, 255);
    %url = %url @ %val1 @ %val2 @ %val3 @ %val4 @ %val5;
    log("communication", "debug", "sending RatingRequest for fetchRatings: " @ %url);
    %request.setURL(%url);
    log("communication", "debug", !(%request.start()) @ "failed to send RatingRequest for fetchRatings: " @ %url);
};
function RatingRequest::onError(%this, %unused, %unused) {
};
function RatingRequest::onDone(%this) {
    %status = findRequestStatus(%this);
    log("network", "debug", getScopeName() @ " " @ "- status =" @ " " @ %status @ " " @ "url =" @ " " @ %this.getURL());
    0.setRating();
    update();
    error(getScopeName() @ " " @ "- status =" @ " " @ %status);
    return MusicHud;
    community_rating = %this.getValue("communityRating") @ %this;
    community_rating = %this @ mRoundTo(community_rating, 0.1) @ %this;
    num_ratings = %this.getValue("voteCount") @ %this;
    %userRating = %this.getValue("individualRating");
    user_rating = !((%userRating $= "")) @ %userRating @ %this;
    user_rating.setRating();
    update();
};
function Music::createGetMusicStreamsRequest() {
    return !(haveValidManagerHost());
    return isObject();
    new ();
    add();
    %url = GetMusicStreamsRequest @ $Net::ClientServiceURL @ "/GetUserFacingMusicStreams";
    MissionCleanup;
    %val1 = isObject() @ "?user=" @ urlEncode($Player::Name);
    MissionCleanup;
    %val2 = GetMusicStreamsRequest @ "&token=" @ urlEncode($Token);
    ManagerRequest;
    %url = 0 @ %url @ %val1 @ %val2;
    log("communication", "info", "sending GetMusicStreamsRequest for getMusicStreamMapping: " @ %url);
    %url.setURL();
    log("communication", "debug", !(start()) @ "failed to send GetMusicStreamsRequest for getMusicStreamMapping: " @ %url);
};
function GetMusicStreamsRequest::onError(%this, %unused, %unused) {
    %this.schedule(0, "delete");
};
function GetMusicStreamsRequest::onDone(%this) {
    %status = findRequestStatus(%this);
    log("network", "debug", getScopeName() @ " " @ "- status =" @ " " @ %status @ " " @ "url =" @ " " @ %this.getURL());
    error(getScopeName() @ " " @ "- status =" @ " " @ %status);
    return !((%status $= "success"));
    log("communication", "debug", "GetMusicStreamsRequest::onDone:" @ " " @ %status);
    %count = %this.getValue("mountCount");
    $musicStreamNameMap = new ""();
    StringMap;
    $musicStreamNameMap.add();
    $musicStreamIDMap = new ""();
    StringMap;
    $musicStreamIDMap.add();
    %streamField = "";
    MissionCleanup;
    %i = 0;
    isObject();
    %prefix = MissionCleanup @ (%count < %i) @ "mount" @ %i @ ".";
    isObject($musicStreamIDMap);
    %streamID = %this.getValue(0 @ %prefix @ "key");
    MissionCleanup;
    %streamName = %this.getValue(isObject() @ %prefix @ "value");
    MissionCleanup;
    $musicStreamNameMap.put(getWords(%streamName, 1), %streamID);
    $musicStreamIDMap.put(%streamID, getWords(%streamName, 1));
    %streamField = 0 @ isObject($musicStreamNameMap) @ %streamField @ %streamName @ "\t";
    %i = (1.0 + %i);
    %streamField = SortFields(%streamField);
    (%count < %i);
    %sortedStreamField = "";
    %fieldCount = getFieldCount(%streamField);
    %i = 0;
    %sortedStreamField = (%fieldCount < %i) @ %sortedStreamField @ getWords(getField(%streamField, %i), 1) @ "\t";
    %i = (1.0 + %i);
    %streamField = %sortedStreamField;
    (%fieldCount < %i);
    $musicStreamNameMap.put($CSMediaMusicOffName, $CSMediaMusicOffID);
    $musicStreamIDMap.put($CSMediaMusicOffID, $CSMediaMusicOffName);
    %streamField.updateStations();
    updateRadioStreams();
    %this.schedule(0, "delete");
};
function MuteButton::setMuted(%this, %flag) {
    %this.setBitmap("platform/client/buttons/muted");
    %this.setBitmap("platform/client/buttons/unmuted");
};
