STATE_PARSE_RESULT = 1 @ WorldMap;
STATE_PARSE_SERVER_COUNT = 2 @ WorldMap;
STATE_PARSE_SERVER = 3 @ WorldMap;
STATE_PARSE_CONTINUE = 4 @ WorldMap;
buttonSize = 39 @ WorldMap;
halfButtonSize = 19 @ WorldMap;
urHereButtonSize = 15 @ WorldMap;
urHereHalfButtonSize = 7 @ WorldMap;
$CountdownTimer = "";
$lastJoinedServer = "";
$lastVURL = "";
function WorldMap::Initialize(%this) {
    initialized = !(initialized) @ 1 @ %this;
    %this;
    currentCity = "" @ %this;
    %this.setUpCities();
    safeEnsureScriptObject("SimGroup", "WorldMapServerInfoGroup");
};
function WorldMap::initCityMaps(%this) {
    currentCity = "" @ %this;
    safeEnsureScriptObject("StringMap", "WorldMapCityInfoMap");
    fillCityInfoMap();
    safeEnsureScriptObject("StringMap", "WorldMapCityNamesMap");
    fillCityNamesMap();
};
$WorldMapCityButtonGroup = 4369;
$TGFCityButtonGroup = 4370;
function WorldMap::getCityButton(%this, %cityName, %alt, %forTGF) {
    %objName = "_small_button" @ "_large_button";
    %forTGF;
    %objName = %forTGF @ %objName @ "_tgf";
    %alt;
    return %objName.getId();
    %info = %cityName.get();
    WorldMapCityInfoMap;
    return 0;
    %coords = Coords;
    %info;
    %bitmap = button;
    %info;
    %groupNum = -1;
    altButton;
    %groupNum = $WorldMapCityButtonGroup;
    %alt;
    %groupNum = $TGFCityButtonGroup;
    %forTGF;
    %buttonType = "PushButton";
    "RadioButton";
    %command = %forTGF @ %alt @ %forTGF @ "WorldMap.selectCity(" @ %cityName @ ");" @ "WorldMap.getCityButton(" @ %cityName @ ", true, false).performClick();";
    %alt;
    profile = GuiBitmapButtonCtrl @ new %objName() @ "GuiDefaultProfile";
    0;
    horizSizing = %forTGF @ %info @ "right";
    %alt;
    vertSizing = %info @ altCoords @ "bottom";
    %forTGF;
    position = %alt @ getWords(%coords, 0, 1);
    extent = getWords(%coords, 2, 3);
    minExtent = "1 1";
    visible = 1;
    command = %command;
    text = "";
    groupNum = %groupNum;
    buttonType = %buttonType;
    bitmap = getPathOfButtonResource(%bitmap);
    drawText = 0;
    cityName = %cityName;
    %button = ;
    %statusX = getWord(%coords, 0);
    %statusY = (20.0 - (getWord(%coords, 3) + getWord(%coords, 1)));
    profile = GuiMLTextCtrl @ new ""() @ "ETSLoginMLTextProfile";
    0;
    extent = getWord(%coords, 2) @ " " @ 14;
    position = %statusX @ " " @ %statusY;
    visible = 1;
    %statusLabel = ;
    statusLabel = %statusLabel @ %button;
    return %button;
};
function WorldMap::getCityPeepsCtrl(%this, %cityName) {
    %objName = "geTGF_map_peeps_" @ %cityName;
    error(getScopeName() @ " " @ "- invalid cityName -" @ " " @ %cityName @ " " @ getTrace());
    return "";
    return %objName.getId();
};
function WorldMap::getVenueButton(%this, %cityName, %venueName) {
    %cityInfo = %cityName.get();
    WorldMapCityInfoMap;
    return 0;
    %venueInfo = venues.get(%venueName);
    %cityInfo;
    return 0;
    %objName = %venueInfo @ spawnName;
    "geWorldMapVenueButton_" @ %cityName @ "_";
    return %objName.getId();
    %cmd = "WorldMap.selectVenue(\"" @ %cityName @ "\", \"" @ %venueName @ "\", " @ %venueInfo @ spawnName @ ");";
    profile = GuiBitmapButtonCtrl @ new %objName() @ "GuiDefaultProfile";
    0;
    horizSizing = "right";
    vertSizing = "bottom";
    position = %venueInfo @ getWords(Coords, 0, 1);
    extent = %venueInfo @ getWords(Coords, 2, 3);
    minExtent = "1 1";
    visible = 1;
    command = %cmd;
    text = "";
    groupNum = -1;
    buttonType = "PushButton";
    bitmap = %venueInfo @ getPathOfButtonResource(button);
    drawText = 0;
    class = "WorldMapVenueButton";
    venueInfo = %venueInfo;
    return;
};
function WorldMap::getVenueLabel(%this, %cityName, %venueName) {
    %cityInfo = %cityName.get();
    WorldMapCityInfoMap;
    return 0;
    %venueInfo = venues.get(%venueName);
    %cityInfo;
    return 0;
    %objName = %cityName @ "_" @ %venueInfo @ spawnName @ "_label";
    return %objName.getId();
    profile = GuiControl @ new %objName() @ "GuiModelessDialogProfile";
    0;
    horizSizing = "width";
    vertSizing = "height";
    position = "0 0";
    extent = "202 20";
    minExtent = "1 1";
    visible = 1;
    profile = GuiMLTextCtrl @ new ""() @ "ETSVenueNameMLTextProfile";
    horizSizing = "width";
    vertSizing = "height";
    position = "1 1";
    extent = "200 18";
    minExtent = "1 1";
    visible = 1;
    text = "<just:center><color:000000ff><font:BauhausStd-Demi:19>" @ %venueName;
    lineSpacing = 2;
    allowColorChars = 1;
    maxChars = -1;
    stripTagsOnCopy = 1;
    profile = GuiMLTextCtrl @ new ""() @ "ETSVenueNameMLTextProfile";
    horizSizing = "width";
    vertSizing = "height";
    position = "0 0";
    extent = "200 18";
    minExtent = "1 1";
    visible = 1;
    text = "<just:center><color:ffffffc8><font:BauhausStd-Demi:19>" @ %venueName;
    lineSpacing = 2;
    allowColorChars = 1;
    maxChars = -1;
    stripTagsOnCopy = 1;
    %ctrl = ;
    %button = %this.getVenueButton(%cityName, %venueName);
    %trgX = ((getWord(%ctrl.getExtent(), 0) * 0.5) - ((getWord(%button.getExtent(), 0) * 0.5) + getWord(%button.getPosition(), 0)));
    %trgY = (8.0 + (getWord(%ctrl.getExtent(), 1) - getWord(%button.getPosition(), 1)));
    %ctrl.setTrgPosition(%trgX, %trgY);
    return %ctrl;
};
function WorldMap::setUpCities(%this) {
    %size = size();
    WorldMapCityInfoMap;
    %i = 0;
    %cityName = name;
    %i.getValue();
    %largeCityButton = %this.getCityButton(%cityName, 0, 0);
    WorldMapCityInfoMap;
    %cityPeepsCtrl = %this.getCityPeepsCtrl(%cityName);
    (%size < %i);
    %largeCityButton.add();
    statusLabel.add();
    statusLabel.setVisible(0);
    %status = %cityName.getStatusForCity();
    packageDownload;
    %largeCityButton.setActive(1);
    %statusText = %this.getFullnessDesc(load, capacity);
    %largeCityButton;
    statusLabel.setText(($AutoDownloadPackages SPC %status $= "done") @ %largeCityButton @ %largeCityButton @ "<spush><font:Arial:12>" @ "Status: " @ %statusText @ "<spop>");
    %cityPeepsCtrl.setTextWithStyle("-" @ " " @ %statusText);
    %i = (1.0 + %i);
    isObject();
    UpdateCityStatuses();
};
function WorldMap::selectCity(%this, %cityName) {
    return (%this SPC currentCity $= %cityName);
    %cityInfo = %cityName.get();
    WorldMapCityInfoMap;
    warn(getScopeName() @ " " @ "- No info for city" @ " " @ %cityName @ " " @ getTrace());
    return !(isObject(%cityInfo));
    currentCity = %cityName @ %this;
    %this.setView("single_city");
    background.setBitmap();
    background.setBitmap();
    background.setBitmap();
    clear();
    venues.forEach("addVenueButton");
    venueButtons = %cityInfo @ "" @ WorldMapCityBkgd;
    WorldMapCityBkgd;
    %count = getCount();
    WorldMapCityBkgd;
    %i = 0;
    %cityInfo;
    venueButtons = venueButtons @ " " @ WorldMapCityBkgd @ %i.getObject() @ WorldMapCityBkgd;
    WorldMapCityBkgd;
    %i = (1.0 + %i);
    (%count < %i);
    1.setButtonsEnabled();
    profile = CityMapLargeTitleText @ new () @ "MapLargeLabelProfile";
    GuiMLTextCtrl;
    horizSizing = !(isObject()) @ 0 @ "right";
    CityMapLargeTitleText;
    vertSizing = (%count < %i) @ WorldMapCityBkgd @ "bottom";
    CityDownloadGui;
    position = LoadingGui @ %cityInfo @ "545 484";
    %cityInfo;
    extent = WorldMapCityBkgd @ "130 24";
    minExtent = "1 1";
    visible = 1;
    text = "";
    maxLength = 255;
    add();
    %this @ currentCity @ " " @ "DressingRoomSpawns>Go Backstage!</a>".setText();
    "".setText();
    %cityName.Maps_changedCityFilter();
    %this.getCityButton(%cityName, 1, 1).performClick();
    %this.getCityButton(%cityName, 1, 0).performClick();
};
function CityMapLargeTitleText::onURL(%this, %url) {
    return !((getWord(%url, 0) $= "VENUESPAWN"));
    %city = getWord(%url, 1);
    %spawn = getWord(%url, 2);
    "Connecting...".setText();
    %city.selectVenue("", %spawn);
};
function WorldMap::selectVenue(%this, %cityName, %venueName, %spawnName) {
    %targetVurl = "vside:/location/" @ %cityName @ "/" @ %spawnName;
    commandToServer('TeleportToVURL', %targetVurl);
    closeFully();
    return geTGF;
    %idx = GetSelected();
    WorldMapServerPopup;
    error("WorldMap::selectVenue(): invalid server selected");
    %serverInfo = %idx.getObject();
    WorldMapServerInfoGroup;
    %cityName[$UserPref::WorldMap::ServerChoice @ %cityName] = !(((getCount() >= %idx) SPC %cityName $= "")) @ %serverInfo @ serverName;
    WorldMapServerInfoGroup;
    %targetVurl = %serverInfo @ serverName;
    isVisible() @ (0.0 < %idx) @ %targetVurl @ "?server0=";
    vurlOperation(%targetVurl);
};
function WorldMap::open(%this) {
    %this.openTGF(0);
};
function WorldMap::openTGF(%this, %forTGF) {
    %this.Initialize();
    %this.updateLocation();
    %this.setBitmap("platform/client/ui/worldmapBackground");
    %this.setView("multi_city");
    %this.setView("single_city");
    %this.getCityButton($gContiguousSpaceName, 1, 0).performClick();
    %this.setVisible(1);
    DestroyMessageBoxes();
    %this.setContent();
    pushScreenSize(960, 544, 0, 1, 0);
    forTGF = Canvas @ %forTGF @ %this;
    !(%forTGF);
    1.setButtonsEnabled();
    %this.refresh();
};
function WorldMap::setLoggedIn(%this, %flag) {
    loggedIn = %flag @ %this;
};
function WorldMap::setNotConnectedToServer(%this) {
    disconnectedCleanup("");
    $ServerName = "";
    server = 0 @ %this;
    $gContiguousSpaceName = "";
    %this.setLoggedIn(0);
};
function WorldMap::close(%this) {
    %this.setVisible(0);
    setContent();
    popScreenSize();
};
function WorldMap::setView(%this, %view) {
    1.setVisible();
    1.setVisible();
    0.setVisible();
    0.setVisible();
    0.setVisible();
    0.setVisible();
    0.setVisible();
    1.setVisible();
    $ETS::devMode.setVisible();
    currentCity = DevModMapCtrls @ "" @ %this;
    geTGF_map_header;
    "".Maps_changedCityFilter();
    0.setVisible();
    0.setVisible();
    1.setVisible();
    1.setVisible();
    1.setVisible();
    1.setVisible();
    1.setVisible();
    0.setVisible();
    %this.fillServerList();
    0.setVisible();
};
function WorldMap::fillDevModServerList(%this) {
    %names = "";
    %n = (WorldMapServers - getCount());
    1.0;
    %server = %n.getObject();
    WorldMapServers;
    %name = %server.get("name");
    (0.0 >= %n);
    %name[%array TAB %name @ server] = %server;
    %name[%array TAB %name @ load] = %server.get("load");
    %name[%array TAB %name @ capacity] = %server.get("capacity");
    %name[%array TAB %name @ city] = %server.get("city");
    %names = %names @ %name @ "\t";
    %n = (1.0 - %n);
    %names = SortFields(%names, 1, 0);
    (0.0 >= %n);
    %list = "";
    %n = (1.0 - getFieldCount(%names));
    %name = getField(%names, %n);
    (0.0 >= %n);
    %load = %name[%array TAB %name @ load];
    %capacity = %name[%array TAB %name @ capacity];
    %city = %name[%array TAB %name @ city];
    %server = %name[%array TAB %name @ server];
    %line = "";
    %line = %line @ "<spush><linkcolor:bbffcc><just:left><a:gamelink " @ %server @ "> " @ %name @ "</a><spop>";
    %line = %line @ "<color:88eedd><just:right>" @ %load @ "/" @ %capacity;
    %list = %list @ %line @ "\n\t";
    %n = (1.0 - %n);
    %list.setText();
};
function WorldMap::fillServerList(%this) {
    clear();
    deleteMembers();
    %count = getCount();
    WorldMapServers;
    %i = 0;
    WorldMapServerInfoGroup;
    %serverProps = %i.getObject();
    WorldMapServers;
    %name = %serverProps.get("name");
    ((%this $= currentCity) SPC %serverProps.get("city") $= "");
    %load = %serverProps.get("load");
    !(((%count < %i) SPC %serverProps.get("mappable") $= 0)) SPC %serverProps.get("city");
    %capacity = %serverProps.get("capacity");
    WorldMapServerPopup;
    server = SimObject @ new ""() @ %serverProps;
    0;
    serverName = WorldMapServerInfoGroup @ %name;
    .add();
    WorldMapServerPopup @ %name @ " -- " @ %this.getFullnessDesc(%load, %capacity).add();
    %i = (1.0 + %i);
    0.SetSelected();
    %serverChoice = $UserPref::WorldMap::ServerChoice;
    WorldMapServerPopup;
    %count = getCount();
    WorldMapServerInfoGroup;
    %i = 0;
    !(((%count < %i) SPC %serverChoice $= ""));
    %i.SetSelected();
    %i = (1.0 + %i);
    WorldMapServerPopup;
    1.setVisible();
    1.setVisible();
    0.setVisible();
    0.setVisible();
    0.setVisible();
    1.setVisible();
};
function WorldMap::onCanvasResize(%this) {
    %this.update();
};
function WorldMap::doServerJoin(%this, %targetVurl) {
    echo("in doServerJoin: " @ %targetVurl);
    purgeResources();
    fmodShutdown();
    fmodInitialize();
    echo(isObject(server) @ "in doServerJoin " @ %this);
    %conn = new ();
    ServerConnection;
    %conn.setCommonPreconnectClientSettings(%targetVurl);
    $GameConnection = %conn;
    GameConnection;
    $ServerName = server.get("name");
    %this;
    %address = server.get("address");
    %this;
    %port = server.get("port");
    %this;
    %address = %this @ !((0 SPC %port $= "")) @ %address @ ":" @ %port;
    $lastJoinedServer = %address;
    $lastVURL = %targetVurl;
    %conn.connect(%address);
    deleteMembers();
    %analytic = getAnalytic();
    geMapHud2DTheOrthoMap;
    %analytic.trackPageView(%this @ server.get("city"));
    %this.selectCity(server.get("city"));
    $SpawnTargetSavedVURL = "";
    %this;
    TransitionCancel(1);
    echo("WorldMap::doServerJoin called when no server set");
};
$gWorldMapJoiningServer = 0;
function WorldMap::join(%this, %server, %isATransition, %targetVurl) {
    return !(isObject(%server));
    %a1 = %server.get("address");
    %p1 = %server.get("port");
    echo("connecting to: " @ %a1 @ ":" @ %p1);
    echo("using vurl: " @ %targetVurl);
    $lastJoinedServer = %server;
    $lastVURL = %targetVurl;
    %a2 = server.get("address");
    %this;
    %p2 = server.get("port");
    %this;
    echo(%this @ isObject(server) @ "current server:" @ " " @ %a2 @ ":" @ %p2);
    closeFully();
    commandToServer('TeleportToVURL', %targetVurl);
    return geTGF;
    server = %server @ %this;
    warn("WorldMap::join(): multiple clicks on servers in the world map");
    return $gWorldMapJoiningServer;
    $gWorldMapJoiningServer = 1;
    %i = 0;
    buttons.setActive(0);
    %i = (1.0 + %i);
    (numServers < %i) @ %i @ %this;
    waitForDisconnect = (numServers < %i) @ 0 @ ServerConnection;
    %this;
    echo("disconnecting...");
    waitForDisconnect = (-(1.0) != GameConnection::getServerConnection()) @ 1 @ ServerConnection;
    isObject();
    $SpawnTargetSavedVURL = %targetVurl;
    ServerConnection;
    commandToServer('DisconnectRequest');
    return %this;
    %this.doServerJoin(%targetVurl);
};
function clientCmdOpenBuildingDirectoryFromCustomSpace(%buildingName) {
    %buildingName = $CSBuildingName;
    (%buildingName $= "");
    forceRightMouseUp();
    %buildingName.open();
};
function clientCmdOpenBuildingDirectoryFromCustomSpaceCancel() {
};
function showTransitionMessage(%description, %counter) {
    extent = PlayGui @ extent @ TransitionMessage;
    text = (0.0 <= %counter) @ "" @ TransitionMessage;
    text = "Wait here for a ride to" @ " " @ %description @ " " @ " in " @ " " @ %counter @ "..\n" @ TransitionMessage;
    1.setVisible();
};
function clientCmdTransitionStartWithMessage(%description, %prompt, %counter, %vurl) {
    error(getScopeName() @ " " @ "- Description:" @ " " @ %description);
    error(getScopeName() @ " " @ "- Prompt:     " @ " " @ %prompt);
    error(getScopeName() @ " " @ "- Counter:    " @ " " @ %counter);
    error(getScopeName() @ " " @ "- vurl:       " @ " " @ %vurl);
    MessageBoxOK("Transition Error", "Couldn't figure out where to take you!\nPlease use the Map to go where you would like to go.", "toggleTGF();");
    return (%vurl $= "");
    %cmd = "vurlOperation(\"" @ %vurl @ "\");";
    %msg = "Would you like to take the train to" @ " " @ %description @ "?";
    MessageBoxYesNo("vSide Transit Service", %msg, %cmd, "");
};
function TransitionStartWithMessage(%description, %prompt, %counter, %vurl) {
    showTransitionMessage(%description, %counter);
    $CountdownTimer = schedule(1000, 0, %counter, %description, %vurl);
    TransitionCountdown;
};
function TransitionCountdown(%counter, %description, %vurl) {
    %counter = (1.0 - %counter);
    showTransitionMessage(%description, %counter);
    0.setVisible();
    closeFully();
    0.close();
    vurlOperation(%vurl);
    MessageBoxOK("Transition Error", "Couldn't figure out where to take you!\nPlease use the Map to go where you would like to go.", "");
    "Map".openToTabName();
    return geTGF;
    $CountdownTimer = schedule(1000, 0, %counter, %description, %vurl);
    TransitionCountdown;
};
function clientCmdTransitionCancel() {
    echo("Server calling transition cancel");
    TransitionCancel(0);
};
function TransitionCancel(%retry) {
    cancel($CountdownTimer);
    0.setVisible();
    echo("VURL Transition canceld... retrying next server");
    log("network", "error", "Unable to retry vurl.");
    $VURL::curVURL.delete();
    $VURL::curVURL.delete();
};
function clientCmdSetTransition(%destination, %spawnTargetVURL) {
    prepareForTransition(%destination, %spawnTargetVURL, 0);
};
function SetTransition(%destination, %spawnTargetVURL) {
    prepareForTransition(%destination, %spawnTargetVURL, 1);
};
function getServerInstance(%cityNameLongOrShort) {
    %cityNameLong = %cityNameLongOrShort.get();
    gCityNamesShortToLongMap;
    %cityNameLong = %cityNameLongOrShort;
    %cityNameLongOrShort.hasKey();
    %strLen = strlen(%cityNameLong);
    gCityNamesShortToLongMap;
    %mostSpaceSvr = 0;
    %mostSpaceAmt = 0;
    %n = (WorldMapServers - getCount());
    1.0;
    %serverObj = %n.getObject();
    WorldMapServers;
    %ServerName = %serverObj.get("name");
    (0.0 >= %n);
    %matches = !(strnicmp(%cityNameLong, %ServerName, %strLen));
    %availSpace = (%serverObj.get("load") - %serverObj.get("capacity"));
    %matches;
    %mostSpaceAmt = %availSpace;
    (%mostSpaceAmt > %availSpace);
    %mostSpaceSvr = %serverObj;
    %n = (1.0 - %n);
    warn("could not find server for" @ " " @ %cityNameLong);
    return %mostSpaceSvr;
};
function prepareForTransition(%destination, %spawnTargetVURL, %pauseForScreenshot) {
    %serverObj = getServerInstance(%destination);
    TransitionCancel(1);
    error(!(isObject(%serverObj)) @ getScopeName() @ ": did not find server for " @ %destination);
    return;
    doTransitionAfterFrames(2, %serverObj, %spawnTargetVURL);
    doTransition(%serverObj, %spawnTargetVURL);
};
$gTransitionScreenshotSchedule = 0;
$gTransitionScreenshotLastFrame = -(1.0);
function doTransitionAfterFrames(%frames, %ServerName, %spawnTargetVURL) {
    cancel($gTransitionScreenshotSchedule);
    $gTransitionScreenshotLastFrame = $Canvas::frameCount;
    (0.0 <= $gTransitionScreenshotLastFrame);
    %delta = ($gTransitionScreenshotLastFrame - $Canvas::frameCount);
    $gTransitionScreenshotLastFrame = -(1.0);
    (%frames >= %delta);
    doTransition(%ServerName, %spawnTargetVURL);
    $gTransitionScreenshotSchedule = schedule(10, 0, %frames, %ServerName, %spawnTargetVURL);
    doTransitionAfterFrames;
};
function doTransition(%server, %spawnTargetVURL) {
    cursorOff();
    $TransitionScreenshot.shootMemory("GRAYSCALE");
    cursorOn();
    %server.join(1, %spawnTargetVURL);
};
function WorldMap::cleanUpServers(%this) {
    %curServerObjId = 0;
    %savedServer = "";
    %curServerObjId = server.getId();
    %this;
    %i = 0;
    isObject(server);
    %server = %i.getObject();
    WorldMapServers;
    %savedServer = %server;
    (%curServerObjId == %server.getId());
    %server.remove();
    buddies.delete();
    %i = (1.0 + %i);
    %server;
    deleteMembers();
    %savedServer.add();
};
function WorldMap::refresh(%this) {
    return !(haveValidManagerHost());
    %this.requestMapData();
};
function WorldMap::exit(%this) {
    delete();
    endDFZone();
    purgeResources();
    fmodShutdown();
    setContent();
};
function WorldMap::update(%this) {
    %this.clearCities();
    0.setVisible();
    return !(isObject());
    %sc = getCount();
    WorldMapServers;
    %i = 0;
    %server = %i.getObject();
    WorldMapServers;
    %ismappable = %server.get("mappable");
    isObject(%server);
    %server.addCity();
    %i = (1.0 + %i);
    WorldMap;
    %this.adjustButtons();
    0.setVisible();
    %this.fillServerList();
    %this.fillDevModServerList();
    updateUserListUnknownServerName();
};
function WorldMap::adjustButtons(%this) {
    %winWidth = getWord($UserPref::Video::Resolution, 0);
    %size = buttonSize;
    WorldMap;
    %i = 0;
    %button = buttons;
    (numServers < %i) @ %i @ %this;
    %x = getWord(%button.getPosition(), 0);
    %this;
    %y = getWord(%button.getPosition(), 1);
    %button.resize(%x, %y, %size, %size);
    %i = (1.0 + %i);
};
function WorldMap::clearCities(%this) {
    %sc = %this.getCount();
    %i = (1.0 - %sc);
    %city = %this.getObject(%i);
    (0.0 >= %i);
    %this.remove(%city);
    %city.delete();
    %i = (1.0 - %i);
    !((%city SPC server $= ""));
    numServers = (0.0 >= %i) @ 0 @ %this;
    isObject(%city);
};
function WorldMap::unnormalize(%this, %location) {
    %location = %location @ " " @ 0;
    %box = "0 0 0" @ " " @ $UserPref::Video::Resolution;
    %location = mUnnormalizePointFromBox(%location, %box);
    %location = getWords(%location, 0, 1);
    %location = mFloor(getWord(%location, 0)) @ " " @ mFloor(getWord(%location, 1));
    return %location;
};
function WorldMap::validateSpot(%this, %locOrig) {
    %retries = 5;
    %valid = 0;
    %loc = %locOrig;
    %try = 0;
    %valid = 1;
    (%retries < %try);
    %n = 0;
    !(%valid);
    %valid = 0;
    (buttons < VectorDist(%loc, position));
    %n = (1.0 + %n);
    8.0 @ %n @ %this;
    %locX = (getRandom(-(15.0), 15) + getWord(%locOrig, 0));
    !(%valid);
    %locY = (getRandom(-(15.0), 15) + getWord(%locOrig, 1));
    (numServers < %n);
    %loc = %locX @ " " @ %locY;
    %this;
    %try = (1.0 + %try);
    (numServers < %n);
    return %loc;
};
function WorldMap::addCity(%this, %server) {
    %this.addCity1(%server);
};
function WorldMap::addCity1(%this, %server) {
    %centerLoc = %this.unnormalize(%server.get("location"));
    %buttonLoc = WorldMap @ (halfButtonSize - getWord(%centerLoc, 1));
    (halfButtonSize - getWord(%centerLoc, 0)) @ " ";
    %buttonLoc = %this.validateSpot(%buttonLoc);
    WorldMap;
    %load = %server.get("load");
    %capacity = %server.get("capacity");
    %fullness = mClamp(mFloor((%capacity / (%load * 8.0))), 0, 8);
    %size = buttonSize;
    WorldMap;
    profile = WorldMapServerButton @ new () @ "GuiDefaultProfile";
    GuiBitmapButtonCtrl;
    horizSizing = 0 @ "right";
    vertSizing = "bottom";
    position = %buttonLoc;
    extent = %size @ " " @ %size;
    minExtent = "8 8";
    visible = 1;
    command = "WorldMap.join(" @ %server @ ", false, \"\");";
    text = "";
    groupNum = -1;
    buttonType = "PushButton";
    bitmap = "platform/client/buttons/UI_serverstate_0" @ %fullness;
    drawText = 0;
    server = %server;
    destName = %server.get("name");
    %button = ;
    buttons = %button @ %this @ numServers @ %this;
    numServers = (%this + numServers);
    1.0;
    %this.add(%button);
    %urHereLoc = WorldMap @ (urHereHalfButtonSize - getWord(%centerLoc, 1));
    (urHereHalfButtonSize - getWord(%centerLoc, 0)) @ " ";
    getWord(%urHereLoc, 0).reposition(getWord(%urHereLoc, 1));
    1.setVisible();
};
function WorldMap::showPopup(%this, %city) {
    %server = server;
    %city;
    return !(isObject(%server));
    %winWidth = getWord($UserPref::Video::Resolution, 0);
    %scaleFactor = (960.0 / %winWidth);
    %destName = destName;
    %city;
    %address = %server.get("address");
    %capacity = %server.get("capacity");
    %load = %server.get("load");
    %port = %server.get("port");
    %destName.setText();
    %status = %city.getStatusForCity();
    packageDownload;
    %statusText = %this.getFullnessDesc(%load, %capacity);
    ($AutoDownloadPackages SPC %status $= "done");
    %statusText = "Downloading!";
    isObject();
    %statusText = %this.getFullnessDesc(%load, %capacity);
    packageDownload;
    MapHudMetaText @ "Status: " @ %statusText.setText();
    %top = getWord(%city.getPosition(), 1);
    MapHudCityText;
    %left = getWord(%city.getPosition(), 0);
    %bottom = (getWord(%city.getExtent(), 1) + %top);
    %right = (getWord(%city.getExtent(), 0) + %left);
    %hudwidth = getWord(getExtent(), 0);
    MapCityHud;
    %hudheight = getWord(getExtent(), 1);
    MapCityHud;
    %pos = (36.0 + %left) @ " " @ (5.0 + %top);
    %xPos = getWord(%pos, 0);
    %ypos = getWord(%pos, 1);
    %xPos.reposition(%ypos);
    1.setVisible();
    %this.pushToBack();
    %this.pushToBack(%city);
};
function WorldMap::getFullnessDesc(%this, %load, %capacity) {
    %fullnessDesc = "offline";
    (1.0 < %capacity);
    %fullnessDesc = "Chillin'";
    (50.0 <= %load);
    %fullnessDesc = "Groovin'";
    (125.0 <= %load);
    %fullnessDesc = "Hoppin'";
    (200.0 <= %load);
    %fullnessDesc = "Packed";
    (249.0 <= %load);
    %fullnessDesc = "Slammed";
    (349.0 <= %load);
    %fullnessDesc = "Sold Out";
    %fullnessDesc = (50.0 > %load) @ %fullnessDesc @ " (" @ %load @ ")";
    return %fullnessDesc;
};
function MapCityHud::setDepressed(%this, %flag) {
};
function WorldMapServerButton::onMouseDown(%this) {
    1.setDepressed();
};
function WorldMapServerButton::onMouseUp(%this) {
    0.setDepressed();
};
function WorldMapServerButton::onMouseEnter(%this, %unused, %unused, %unused) {
    %this.showPopup();
};
function WorldMapServerButton::onMouseLeave(%this) {
    0.setVisible();
};
function WorldMap::setCitiesActive(%this, %flag) {
    %count = getCount();
    WorldMapMultiCityLarge;
    %i = 0;
    %i.getObject().setActive(%flag);
    %i = (1.0 + %i);
    WorldMapMultiCityLarge;
};
function WorldMap::UpdateCityStatuses(%this) {
    return !(isVisible());
    %csn = "gw";
    %hasAccess = 0;
    %hasAccess = ((10.0 < $Player::Name.getProperty(gUserPropMgrClient @ "level started count " @ %csn, 0)) | %hasAccess);
    %hasAccess = (roles::maskhaspermission($player::rolesMask, "gatewaySpawn") | %hasAccess);
    %hasAccess = ($ETS::devMode | %hasAccess);
    new ();
    add();
    %n = (WorldMapServers - getCount());
    1.0;
    %serverProps = %n.getObject();
    WorldMapServers;
    %serverProps.delete();
    %n = (1.0 - %n);
    (!(%hasAccess) SPC %serverProps.get("city") $= %csn);
    %count = getCount();
    WorldMapMultiCityLarge;
    %i = 0;
    (0.0 >= %n);
    %buttonBig = %i.getObject();
    WorldMapMultiCityLarge;
    %buttonSml = citybutton;
    %buttonBig @ cityName @ TGFWorldMapMultiCitySmall;
    %statusTxtCtrl = %buttonBig @ cityName;
    (%count < %i) @ "geTGF_map_peeps_";
    load = (0.0 >= %n) @ 0 @ %buttonBig;
    WorldMapServers;
    capacity = RootGroup @ 0 @ %buttonBig;
    WorldMapServers;
    numServers = SimGroup @ 0 @ %buttonBig;
    0;
    %buttonBig.setActive(0);
    style = !(isObject()) @ "tgfMapCityPeepsInactive" @ %statusTxtCtrl;
    WorldMapServers;
    %buttonSml.setActive(0);
    new ();
    add();
    %n = (WorldMapServers - getCount());
    1.0;
    %serverProps = %n.getObject();
    WorldMapServers;
    %buttonBig.setActive(1);
    style = (%buttonBig SPC cityName $= %serverProps.get("city")) @ "tgfMapCityPeeps" @ %statusTxtCtrl;
    (0.0 >= %n);
    %buttonSml.setActive(1);
    load = (%buttonBig + load);
    %serverProps.get("load");
    capacity = (%buttonBig + capacity);
    %serverProps.get("capacity");
    servers = isObject(%buttonSml) @ %serverProps @ %buttonBig @ numServers @ %buttonBig;
    WorldMapServers;
    numServers = (%buttonBig + numServers);
    1.0;
    %n = (1.0 - %n);
    RootGroup;
    %dlStatus = cityName.getStatusForCity();
    %buttonBig;
    %statusText = %this.getFullnessDesc(load, capacity);
    %buttonBig;
    %statusText = "Downloading!";
    %buttonBig;
    %buttonBig.setActive(0);
    style = (packageDownload SPC %dlStatus $= "done") @ "tgfMapCityPeepsInactive" @ %statusTxtCtrlCtrl;
    $AutoDownloadPackages;
    %buttonSml.setActive(0);
    %statusText = %this.getFullnessDesc(load, capacity);
    %buttonBig;
    statusLabel.setText(isObject(%buttonSml) @ %buttonBig @ %buttonBig @ "<spush><font:Arial:12>" @ "Status: " @ %statusText @ "<spop>");
    style = isObject() @ "tgfMapCityPeeps" @ %statusTxtCtrl;
    packageDownload;
    %statusTxtCtrl.setTextWithStyle("-" @ " " @ %statusText);
    %i = (1.0 + %i);
    (0.0 >= %n);
};
function WorldMap::cityNameForServerName(%this, %name) {
    return "";
    %count = getCount();
    WorldMapServers;
    %i = 0;
    %server = %i.getObject();
    WorldMapServers;
    return %server.get("city");
    %i = (1.0 + %i);
    return "";
};
function WorldMap::IsApartmentServerForServerName(%this, %name) {
    return 0;
    %count = getCount();
    WorldMapServers;
    %i = 0;
    %server = %i.getObject();
    WorldMapServers;
    return !(%server.get("mappable"));
    %i = (1.0 + %i);
    return 0;
};
function WorldMap::isServerForCity(%this, %name) {
    return 0;
    %count = getCount();
    WorldMapServers;
    %i = 0;
    %server = %i.getObject();
    WorldMapServers;
    return 1;
    %i = (1.0 + %i);
    return 0;
};
function WorldMap::onWake(%this) {
};
$gRefreshWorldMapTimer = "";
function refreshWorldMap() {
    cancel($gRefreshWorldMapTimer);
    $gRefreshWorldMapTimer = "";
    return !(isAwake());
    setUpCities();
    $gRefreshWorldMapTimer = schedule(2000, 0, "refreshWorldMap");
    WorldMap;
};
function WorldMap::requestMapData(%this) {
    new ();
    add();
    %mapRequest = safeEnsureScriptObject("URLPostObject", "MapRequest");
    WorldMapServers;
    return (%mapRequest == isActive);
    %mapRequest.setURL($Net::ClientServiceURL @ "/WorldMapRefresh");
    %mapRequest.setURLParam("user", $Player::Name);
    %mapRequest.setURLParam("token", $Token);
    %mapRequest.setURLParam("version", getProtocolVersion());
    %mapRequest.setCompletedCallback("MapRequestOnCompleted");
    log("communication", "debug", "sending request for map data.");
    isActive = 1 @ %mapRequest;
    %mapRequest.start();
};
function MapRequestOnCompleted(%request, %result) {
    isActive = 0 @ %request;
    %request.parseResult();
    update();
    MessageBoxOK("Connection Error", ($CURL::CouldNotConnect == %result), "");
    MessageBoxOK("Could Not Find Server", ($CURL::CouldNotResolveHost == %result), "");
    MessageBoxOK("Server Unavailable", WorldMap, "");
    %request.schedule(0, "delete");
    %vurl = getSkipMapVurl(1);
    WorldMap;
    vurlOperation(%vurl);
};
function WorldMap::parseResult(%this, %request) {
    cleanUpServers();
    %savedServer = "";
    (WorldMapServers == getCount());
    %savedName = "";
    0.0;
    %savedServer = 0.getObject();
    WorldMapServers;
    %savedName = %savedServer.get("name");
    WorldMap;
    %numServers = %request.getResult("serverCount");
    log("communication", "error", "no servers returned in map response");
    MessageBoxOK("Server Unavailable", (0.0 == %numServers), "");
    return;
    %fields = "address capacity city description load location mappable name port version";
    %i = 0;
    %ServerName = %request.getResult((%numServers < %i) @ "server" @ %i @ ".name");
    %serverProps = %savedServer;
    !(((%ServerName $= %savedName) SPC %savedServer $= ""));
    %serverProps = new ""();
    StringMap;
    %serverProps.add();
    %j = 0;
    MissionCleanup;
    %field = getWord(%fields, %j);
    (getWordCount(%fields) < %j);
    %name = 0 @ MissionCleanup @ isObject() @ "server" @ %i @ "." @ %field;
    %value = %request.getResult(%name);
    log("communication", "debug", "adding server prop: " @ %field @ " = " @ %value);
    %serverProps.put(%field, %value);
    %j = (1.0 + %j);
    %name = %serverProps.get("name");
    ((getWordCount(%fields) < %j) SPC %serverProps.get("city") $= "");
    %count = size();
    WorldMapCityNamesMap;
    %j = 0;
    %key = %j.getKey();
    WorldMapCityNamesMap;
    %value = %j.getValue();
    WorldMapCityNamesMap;
    %serverProps.put("city", %value);
    %j = (1.0 + %j);
    (0.0 == stricmp(%key, %name));
    %serverProps.add();
    %i = (1.0 + %i);
    WorldMapServers;
    %this.TabulateWorldAreaSummary();
    %this.UpdateCityStatuses();
};
function getSkipMapVurl(%bChangeUI) {
    %ret = "";
    %ret = $VURLcmd;
    !(($VURLcmd $= ""));
    $VURLcmd = "";
    %bChangeUI;
    $Player::Name[$gTriedToAutoConnectOnceAlready @ $Player::Name] = 0;
    !(isDefined("$gTriedToAutoConnectOnceAlready" @ $Player::Name));
    log("communication", "debug", "Checking for autodest.");
    $Player::Name[$gTriedToAutoConnectOnceAlready @ $Player::Name] = 1;
    %bChangeUI;
    MessageBoxOK("Not going to gateway..", "Ordinarily, you would have been\nautomatically take to gateway here,\nbut since you're devmode, you're not.", "");
    %ret = "vside:/location/gw/mapSpawns_entry";
    %bChangeUI;
    "gw".selectCity();
    "Maps".selectTab();
    log("communication", "debug", WorldMap @ geTGF @ getScopeName() @ " " @ "- \"" @ %ret @ "\".");
    return %ret;
};
function VenuesMap::addVenueButton(%this, %key, %value) {
    currentCity.getVenueButton(%key).add();
    currentCity.getVenueLabel(%key).add();
};
function WorldMapVenueButton::onMouseEnter(%this) {
    %bitmapName = strreplace(name, "'", "");
    venueInfo;
    %bitmapName = %this @ WorldMap @ currentCity @ "_" @ strreplace(%bitmapName, " ", "_");
    %bitmap = getPathOfButtonResource("platform/client/ui/spawn_info/" @ %bitmapName);
    %bitmap.setBitmap();
    fitSize();
    (getWord(%this.getExtent(), 0) + getWord(%this.getPosition(), 0)).reposition((6.0 + getWord(%this.getPosition(), 1)));
    1.setVisible();
};
function WorldMapVenueButton::onMouseLeave(%this) {
    0.setVisible();
};
function WorldMapCityBkgd::setButtonsEnabled(%this, %flag) {
    %count = getWordCount(venueButtons);
    %this;
    %i = 0;
    %button = getWord(venueButtons, %i);
    %this;
    %button.setActive(%flag);
    %i = (1.0 + %i);
    isObject(%button);
};
function devModServerListML::onURL(%this, %url) {
    return !((firstWord(%url) $= "gamelink"));
    %serverObj = getWord(%url, 1);
    closeFully();
    %serverObj.join(0, "");
};
function devModServerListML::onRightURL(%this, %url) {
    return !((firstWord(%url) $= "gamelink"));
    %serverObj = getWord(%url, 1);
    %serverObj.dumpValues();
};
function gotVURLCommandLineList(%arg) {
    log("communication", "debug", "found the VURL argument list and it is " @ %arg);
    %url = "";
    %url = %arg;
    ($Platform $= "macos");
    %count = getWordCount(%arg);
    %i = 0;
    %value = getWord(%arg, %i);
    (%count < %i);
    %url = getWord(%arg, (1.0 + %i));
    (%value $= "-url");
    %i = (1.0 + %i);
    log("communication", "debug", (%count < %i) @ "value of URL is " @ %url);
    log("communication", "debug", "now URL is " @ %url);
    $VURLcmd = %url;
    0.setControlsActive();
    1.setVisible();
    $Player::Name = trim($Player::Name);
    LoginProgressBarCtrls;
    $Player::Name.setValue();
    $UserPref::Player::Name = $Player::Name;
    $UserPref::Login::RememberMe;
    $UserPref::Player::Password = $Player::Password;
    LoginUserNameField;
    $UserPref::Player::Name = "";
    LoginGui;
    $UserPref::Player::Password = "";
    !(loggedIn);
    envManagerLogin();
    vurlOperation($VURLcmd);
};
