exec("./common/scripts/defaultsCommon.cs");
exec("./client/defaults.cs");
exec("./server/defaults.cs", 0);
exec("./client/userprefs.cs", 0);
$UserPref::Player::Password = unmunge($UserPref::Player::Password);
$UserPref::Player::AIMPassword = unmunge($UserPref::Player::AIMPassword);
package platform {
    function displayHelp() {
        Parent::displayHelp();
        displayServerHelp();
        displayClientHelp();
    };
    function displayClientHelp() {
        print("\nClient options:\n" @ "  -manager <host[:port]>     Specify login server\n" @ "  -mainsite <url>            Specify main website\n" @ "  -download <host[:port]>    Specify download host\n" @ "  -large                     Large display\n" @ "  -small                     Small display\n" @ "  -noSound                   Disable sound\n" @ "  -display <OpenGL|D3D|Auto> Specify device or auto-detect\n" @ "  -server                    Start as server\n" @ "  -cache                     Do network caching\n" @ "  -staging                   Run in staging environment\n" @ "  -stagingrc                 Run in stagingRC environment\n" @ "  -alpha                     Run in alpha environment\n" @ "  -preload                   Run asset preloading\n" @ "  -url                       Specify a place to spawn to via vURL\n" @ "  -alphabuffer               Request an alpha buffer for OpenGL\n" @ "  -notexdelay                Disable teuxture delay load\n" @ "  -enableRawTextures         Enable use of compressed textures\n" @ "  -automated                 Automatically begin tasks like thumbnail generationg\n" @ "");
    };
    function displayServerHelp() {
        print("\nServer options:\n" @ "  -manager <host[:port]>     Specify host and port of login server\n" @ "  -mission <mission>         Specify mission file\n" @ "  -serverName                Server name\n" @ "  -nameSpaceTag              a namespace tag for private spaces and buildings default \"\"\n" @ "  -serverAddress <address>   Server bind address\n" @ "  -serverPort                Server bind port\n" @ "  -mapLocation <x,y>         Server worldmap coordinates\n" @ "  -disableChat               NPCs don't chat\n" @ "  -webloglevel <n>           Set web log level\n" @ "  -notmappable               Server will not appear on the map\n" @ "");
    };
    function rebaseURLs() {
        $Net::CrashURL = absoluteURL($Net::ManagerHost, "envmanager/envclient/CrashReport");
        $Net::ItunesURL = absoluteURL($Net::BaseDomain, "go/itunes");
        $Net::ProfileURL = absoluteURL($Net::BaseDomain, "go/profile/user/");
        $Net::ProfilesURL = absoluteURL($Net::BaseDomain, "go/profiles");
        $Net::ProfileEditURL = absoluteURL($Net::BaseDomain, "go/profile");
        $Net::AccountEditURL = absoluteURL($Net::BaseDomain, "go/account");
        $Net::AddFundsURL = absoluteURL($Net::BaseDomain, "go/account/purchase");
        $Net::AIMInviteURL = absoluteURL($Net::BaseDomain, "?");
        $Net::AvatarURL = absoluteURL($Net::BaseDomain, "photoservice/avatars/");
        $Net::BuildDirPhotoURL = absoluteURL($Net::BaseDomain, "photoservice/directory/");
        $Net::GalleryPhotoURL = absoluteURL($Net::BaseDomain, "photoservice/");
        $Net::EventDetailURL = absoluteURL($Net::BaseDomain, "go/event/id/");
        $Net::MusicURL = absoluteURL($Net::BaseDomain, "go/music");
        $Net::ViewTagURL = absoluteURL($Net::BaseDomain, "go/search/");
        $Net::HelpURL_Abuse = absoluteURL($Net::BaseDomain, "go/help/category/abuse");
        $Net::HelpURL_General = absoluteURL($Net::BaseDomain, "go/help");
        $Net::HelpURL_Guidelines = absoluteURL($Net::BaseDomain, "go/rules");
        $Net::HelpURL_MusicNEvents = absoluteURL($Net::BaseDomain, "go/help/category/musicevents");
        $Net::HelpURL_Navigation = absoluteURL($Net::BaseDomain, "go/help/category/navigation");
        $Net::HelpURL_Parents = absoluteURL($Net::BaseDomain, "go/help/category/parents");
        $Net::HelpURL_Support = absoluteURL($Net::BaseDomain, "go/help/category/support");
        $Net::HelpURL_VPoints = absoluteURL($Net::BaseDomain, "go/help/category/vpoints");
        $Net::HelpURL_VBux = absoluteURL($Net::BaseDomain, "go/help/category/vbux");
        $Net::HelpURL_VHD = absoluteURL($Net::BaseDomain, "go/help/category/vhd");
        $Net::HelpURL_MyShop = absoluteURL($Net::BaseDomain, "go/help/category/vhd");
        $Net::HelpURL_displayDevice = absoluteURL($Net::BaseDomain, "go/help/displayDevice");
        $Net::ForgotPassURL = absoluteURL($Net::BaseDomain, "go/login/forgot");
        $Net::ActivationURL = $Net::AccountEditURL;
        $Net::ReregisterURL = absoluteURL($Net::BaseDomain, "go/login/reregister");
        $Net::FinishRegistrationURL = absoluteURL($Net::BaseDomain, "app/start/registrationId/[REGISTRATIONID]");
        $Net::UploadPhotoURL = absoluteURL($Net::ManagerHost, "envmanager/envclient/uploadPhoto");
        $Net::PhotoAlbumURL = absoluteURL($Net::BaseDomain, "go/photos/user/[PLAYERNAME_URL]");
        $Net::PhotoPageURL = absoluteURL($Net::BaseDomain, "app/photo/id/");
        $Net::TermsOfUseURL = absoluteURL($Net::BaseDomain, "go/help/tou");
        $Net::EventsURL = absoluteURL($Net::BaseDomain, "go/events");
        $Net::SongPageURL = absoluteURL($Net::BaseDomain, "go/music");
        $Net::DynamicContentURL = absoluteURL($Net::BaseDomain, "dc");
        $Net::PlayerReportURL = absoluteURL($Net::ManagerHost, "envmanager/envclient/AbuseReport");
        $Net::ManageUserURL = absoluteURL($Net::ManagerHost, "envmanager/manage_user");
        $Net::inviteFriendsURL = absoluteURL($Net::BaseDomain, "app/invite");
        $Net::DashboardURL = absoluteURL($Net::BaseDomain, "go/dashboard");
        $Net::PartnerURL = absoluteURL($Net::BaseDomain, "go/partner");
        $Net::ForumsURL = absoluteURL($Net::BaseDomain, "go/forums");
        $Net::ImageInfoURL = absoluteURL($Net::BaseDomain, "go/imageinfo");
        $Net::downloadURL = "http://" @ $Net::DownloadHost;
        $Net::BaseURL = $Server::Dedicated @ "http://" @ $Net::ManagerHost @ "/envmanager/status";
        $Net::LoginURL = "http://" @ $Net::ManagerHost @ "/envmanager/login";
        $Net::ClientServiceURL = "http://" @ $Net::ManagerHost @ "/envmanager/envclient";
        $Net::ServerServiceURL = "http://" @ $Net::ManagerHost @ "/envmanager/envserver";
        $Net::BaseURL = "http://" @ $Net::ManagerHost @ "/envmanager/login";
        $Net::SecureURL = "https://" @ $Net::SecureManagerHost @ "/envmanager/login";
        $Net::LoginURL = $Net::BaseURL;
        $Net::ClientServiceURL = "http://" @ $Net::ManagerHost @ "/envmanager/envclient";
        $Net::SecureClientServiceURL = "https://" @ $Net::SecureManagerHost @ "/envmanager/envclient";
        $Net::ServerServiceURL = "http://" @ $Net::ManagerHost @ "/envmanager/envserver";
        setupProjectSpecificUrls();
    };
    function notokenURL(%url) {
        return strreplace(%url, "http", "HTTP");
    };
    function clientRebaseHosts() {
        $Net::ManagerHost = "envmanager." @ $Net::BaseDomain @ ":8080";
        $Net::SecureManagerHost = "envmanager." @ $Net::BaseDomain @ ":8443";
        $Net::DownloadHost = "download." @ $Net::BaseDomain;
    };
    function serverRebaseHosts() {
        $Net::ManagerHost = $Net::BaseDomain @ ":8081";
        $Net::IRCHost = "irc." @ $Net::BaseDomain @ ":6667";
    };
    function isValidHostAddress(%address) {
        %ret = 1;
        %ret = 0;
        (%address $= "");
        %ret = 0;
        (%address $= 0);
        %ret = 0;
        (%address $= "0:0");
        return %ret;
    };
    function haveValidManagerHost() {
        %ret = isValidHostAddress($Net::ManagerHost);
        warn(getScopeName(1) @ " " @ "- $Net::ManagerHost is invalid." @ " " @ getTrace());
        return %ret;
    };
    function haveValidToken() {
        return !(($Token $= ""));
    };
    function parseArgs() {
        Parent::parseArgs();
        echo("--------- Parsing Arg MOD: platform ---------");
        $Server::Dedicated = 1;
        !($Game::Compile);
        $Con::logBufferEnabled = 0;
        hasArg("-server");
        $Net::ManagerHost = "192.168.100.100:8081";
        hasArg("-dedicated");
        $Net::DownloadHost = "192.168.100.100:8081";
        parseServerArgs();
        parseClientArgs();
        enableWinConsole(1);
        rebaseURLs();
        setupMessages();
        $Server::Mappable = 0;
        hasArg("-notmappable");
        log("initialization", "debug", "setting the map as invisible");
        $NonInteractive = 0;
        !($Game::Compile);
        log("initialization", "debug", "Exporting net_settings.log");
        export("$Net::*", "./net_settings.log", 0);
    };
    function parseMainsiteArg() {
        %haveMainsiteArg = findArg("-mainsite", "$Net::BaseDomain", "Missing mainsite <url>");
        serverRebaseHosts();
        clientRebaseHosts();
        %testdomain = strreplace($Net::BaseDomain, ":", " ");
        $Server::Dedicated;
        %analytic = getAnalytic();
        stricmp("www.vside.com", firstWord(%testdomain));
        %analytic.setDomainAndAccount("test.vside.com", "UA-324914-24");
    };
    function parseManagerArgs() {
        %haveManagerArg = findArg("-manager", "$Net::ManagerHost", "Missing manager <host[:port]>");
        %haveSManagerArg = findArg("-smanager", "$Net::SecureManagerHost", "Missing smanager <host[:port]>");
        %colonPos = strstr($Net::ManagerHost, ":");
        %haveManagerArg;
        $Net::SecureManagerHost = !(%haveSManagerArg) @ $Net::ManagerHost @ ":8443";
        (-(1.0) == %colonPos);
        $Net::ManagerHost = $Server::Dedicated @ $Net::ManagerHost @ ":8081";
        $Net::ManagerHost = $Net::ManagerHost @ ":8080";
        %line = $Net::ManagerHost;
        !(%haveSManagerArg);
        %line = NextToken(%line, ":");
        host;
        NextToken(%line, " ");
        $Net::SecureManagerHost = (port SPC %port $= 80) @ %host @ ":443";
        $Net::SecureManagerHost = %host @ ":8443";
        %colonPos = strstr($Net::SecureManagerHost, ":");
        %haveSManagerArg;
        $Net::SecureManagerHost = (-(1.0) == %colonPos) @ $NetSecureManagerHost @ ":8443";
        log("initialization", "debug", "manager host: " @ $Net::ManagerHost);
        log("initialization", "debug", "secure manager host: " @ $Net::SecureManagerHost);
    };
    function parseDownloadArg() {
        findArg("-download", "$Net::DownloadHost", "Missing download <host[:port]>");
    };
    function parseIRCArg() {
        findArg("-irc", "$Net::IRCHost", "Missing irc <host[:port]>");
    };
    function parseURLArg() {
        findArg("-url", "$VURLcmd", "No url specified");
    };
    function parseClientArgs() {
        parseMainsiteArg();
        parseManagerArgs();
        startInitialSSLConnection();
        parseDownloadArg();
        parseURLArg();
        $CacheFlagIsSet = 0;
        log("initialization", "debug", "cache flag set");
        $Preload = 0;
        findSwitch("-cache", "$CacheFlagIsSet");
        log("initialization", "debug", "preload flag set");
        log("initialization", "debug", findArg("-extraCacheNameTag", "$Cache::ExtraNameTag", "Missing <extraCacheNameTag>") @ "cache extra tag: " @ $Cache::ExtraNameTag);
        $AutoDownloadPackages = 0;
        findSwitch("-preload", "$Preload");
        log("initialization", "debug", "usePackages specified. Start downloading ASAP.");
        $UserPref::Video::Resolution = "960 544 32";
        hasArg("-large");
        $UserPref::Video::Resolution = "480 272 32";
        hasArg("-small");
        error("initialization", "no support yet");
        $Pref::Video::DisplayDevice = "";
        (((findArg("-display", "$Pref::Video::DisplayDevice", "Missing <display device>") SPC $Pref::Video::DisplayDevice $= "D3D") SPC $Pref::Video::DisplayDevice $= "OpenGL") SPC $Pref::Video::DisplayDevice $= "Auto");
        error("initialization", findSwitch("-usePackages", "$AutoDownloadPackages") @ hasArg("-noSound") @ "Error: " @ $Pref::Video::DisplayDevice @ " not one of OpenGL|D3D|Auto");
        log("initialization", "debug", "Disabling delay loading of textures");
        $pref::OpenGL::delayLoadTextures = 0;
        hasArg("-notexdelay");
        log("initialization", "debug", "Disabling background loading of textures");
        $pref::OpenGL::backgroundLoadTextures = 0;
        hasArg("-nobgtexload");
        log("initialization", "debug", "Enable use of compressed textures");
        $pref::OpenGL::enableRawTextures = 1;
        hasArg("-enableRawTextures");
        $gAutomatedRun = 1;
        hasArg("-automated");
        $ETS::WindowTitle = generateWindowTitle("");
    };
    function generateWindowTitle(%ServerName) {
        %ServerNameString = " on server" @ " " @ %ServerName;
        "";
        %CityNameString = " in" @ " " @ $ETS::cityName;
        "";
        %LongCityNameString = "";
        ((%ServerName $= "") SPC $ETS::cityName $= "");
        %areaName = %ServerName.cityNameForServerName();
        WorldMap;
        %locationName = DestinationList::GetAreaNameUserFacingName(%areaName);
        isObject();
        %LongCityNameString = " - in" @ " " @ %locationName;
        "";
        echo(getScopeName() @ " " @ "No WorldMap, not getting long city name from server");
        %title = (WorldMap SPC %locationName $= "") @ hasArg("-staging") @ $ETS::AppName @ " (Staging Build " @ getBuildVersion() @ %ServerNameString @ ")";
        %title = hasArg("-stagingrc") @ $ETS::AppName @ " (StagingRC Build " @ getBuildVersion() @ %ServerNameString @ ")";
        %title = hasArg("-alpha") @ $ETS::AppName @ " (Alpha Build " @ getBuildVersion() @ %LongCityNameString @ ")";
        %alphabufferrequested = "";
        hasArg("-standalone");
        %alphabufferrequested = " * Alpha Buffer Requested *";
        hasArg("-alphabuffer");
        %title = $ETS::AppName @ " (Standalone Build " @ getBuildVersion() @ %ServerNameString @ %CityNameString @ %alphabufferrequested @ ")";
        %title = $ETS::AppName @ " - " @ $ETS::AppVersion @ %LongCityNameString;
        return %title;
    };
    function GetServerNameSpaceTaggedName(%name) {
        error(getScopeName() @ " " @ "- $pref::Server::NameSpaceTag is being used to modify the building and model id names, this should not be released to the public");
        %name = !(($pref::Server::NameSpaceTag $= "")) @ $pref::Server::NameSpaceTag @ %name;
        return %name;
    };
    function parseServerArgs() {
        parseMainsiteArg();
        parseManagerArgs();
        parseDownloadArg();
        parseIRCArg();
        $Pref::Net::BindAddress = "";
        log("initialization", "debug", findArg("-mission", "$MissionArg", "Missing <mission file>") @ "mission file: " @ $MissionArg);
        $MissionArg = strreplace($MissionArg, "\\", "/");
        !((strchr($MissionArg, "\\") $= ""));
        log("initialization", "debug", findArg("-nameSpaceTag", "$Pref::Server::NameSpaceTag", "Missing <namespacetag>") @ "namespacetag: " @ $pref::Server::NameSpaceTag);
        $Pref::Server::Name = !((findArg("-serverName", "$Pref::Server::Name", "Missing <server name>") SPC $pref::Server::NameSpaceTag $= "")) @ $pref::Server::NameSpaceTag @ $Pref::Server::Name;
        $Con::WindowTitle = $Con::WindowTitle @ " - " @ $Pref::Server::Name;
        log("initialization", "debug", "server name: " @ $Pref::Server::Name);
        $Con::WindowTitle = findArg("-cityName", "$Pref::Server::City", "Missing <city name>") @ $Con::WindowTitle @ " - " @ $Pref::Server::City;
        log("initialization", "debug", "city name: " @ $Pref::Server::City);
        log("initialization", "debug", findArg("-serverPort", "$Pref::Server::Port", "Missing <server port>") @ "server port: " @ $Pref::Server::Port);
        log("initialization", "debug", findArg("-serverAddress", "$Pref::Net::BindAddress", "Missing <server address>") @ "server address: " @ $Pref::Net::BindAddress);
        log("initialization", "debug", findArg("-mapLocation", "$Server::Location", "Missing <map location>") @ "map location: " @ $Server::Location);
        log("initialization", "debug", "enabling NPC chat");
        log("initialization", "debug", findSwitch("-weblogLevel", "$Server::WebLogLevel", "Missing <log level>") @ "web log level: " @ $Server::WebLogLevel);
        log("initialization", "debug", "Enabling city package requirements.");
        $Pref::Server::usePackages = 0;
        findSwitch("-usePackages", "$Pref::Server::usePackages", "Missing <usePackages>");
        hasArg("-webConfigFile");
    };
    function startInitialSSLConnection() {
        %curl = new ""();
        URLPostObject;
        %curl.setURL(0 @ "https://" @ $Net::SecureManagerHost);
        %curl.setBody(0);
        %curl.start();
    };
    function onStart() {
        Parent::onStart();
        echo("--------- Initializing MOD: platform ---------");
        exec("./client/init.cs");
        exec("./server/init.cs");
        initServer();
        exec("./common/scripts/init.cs");
        $Token = "";
        $Server::Dedicated;
        $TokenStandalone = "TOKEN_STANDALONE";
        $StandAlone;
        initDedicated();
        initClient();
        "platform/client/consoleHistory.txt".loadHistory();
        echo("---no ConsoleEntry not loading history");
    };
    function onExit() {
        dumpConsoleHistoryReally();
        shutdownClient();
        echo("Exporting client prefs");
        $UserPref::Player::Password = munge($UserPref::Player::Password);
        !($NonInteractive);
        $UserPref::Player::AIMPassword = munge($UserPref::Player::AIMPassword);
        !($Server::Dedicated);
        export("$UserPref::*", "./client/userprefs.cs", 0);
        echo("NOTE: Skipping export of userprefs.cs on non-interactive client.");
        shutdownDedicated();
        Parent::onExit();
    };
    function dumpConsoleHistorySchedule() {
        $gConsoleHistoryDumpTimer = "";
        !(isDefined("$gConsoleHistoryDumpTimer"));
        $gConsoleHistoryPeriod = 15000;
        cancel($gConsoleHistoryDumpTimer);
        $gConsoleHistoryDumpTimer = "";
        $gConsoleHistoryDumpTimer = schedule($gConsoleHistoryPeriod, 0, "dumpConsoleHistoryReally");
    };
    function dumpConsoleHistoryReally() {
        "platform/client/consoleHistory.txt".dumpHistory();
        echo("---no ConsoleEntry not dumping history");
    };
    activatePackage();
};

