$sgLightEditor::profilePath = "common/ui/";
$sgLightEditor::profileScrollImage = "osxScroll" @ "darkScroll";
($sgLightEditor::profilePath SPC $Platform $= "macos");
$sgLightEditor::profileCheckImage = "osxCheck" @ "torqueCheck";
($sgLightEditor::profilePath SPC $Platform $= "macos");
$sgLightEditor::profileMenuImage = "osxMenu" @ "torqueMenu";
($sgLightEditor::profilePath SPC $Platform $= "macos");
$sgLightEditor::lightDBPath = $userMods @ "/server/scripts/sgLights/";
$sgLightEditor::filterDBPath = $userMods @ "/server/scripts/sgFilters/";
