$MAX_FREE_BONE_BLENDS = 23;
$BB_FLAVOR_ONESHOT = 1;
$BB_FLAVOR_PINGPONG = 2;
$BB_FLAVOR_PINGPONG_SINE = 3;
$BB_FLAVOR_SETPOS = 4;
$BB_FLAVOR_LOOP = 5;
$BB_FLAVOR_HOLD_AT_N_REVERSE = 6;
$BB_FLAVOR_HOLD_AT_N_COMPLETE = 7;
$BB_FLAVOR_HOLD_AT_N_REMOVE = 8;
$BB_HEAD_LR = 0;
$BB_HEAD_UD = 1;
$BB_HEAD_TALK = 2;
$BB_HEAD_XRCST = 3;
$FIRST_FREE_BLEND_INDEX = 7;
$BB_UPPR_WAVE = 7;
$BB_UPPR_LOL = 8;
$BB_UPPR_CHUG = 9;
$BB_UPPR_CHEERS = 10;
$BB_UPPR_DANCEMIX = 11;
$BB_LOWR_DANCEMIX = 12;
$BB_UPPR_CHEERS2 = 13;
$BB_BODY_PIVOT = 14;
$BB_BODY_BEND_T0 = 15;
$BB_BODY_KISS = 16;
$BB_BODY_WALK = 17;
$BB_HEAD_KISS_LR = 18;
$BB_HEAD_KISS_UD = 19;
$BB_BODY_DANCE_WITH = 20;
$BB_UPPR_OMG = 21;
$BB_BODY_DANCE_WITH_ROLL = 22;
$BB_UPPR_FLIRT = 23;
$BB_UPPR_DRINK = 24;
$BB_UPPR_MICROPHONE = 25;
$BB_UPPR_TOAST = 26;
$BB_SIT_KISS_BEND_TO = 27;
$BB_SIT_KISS_PIVOT = 28;
$BB_UPPR_KISS = 29;
title = blendAnim_0 @ new () @ "waving";
ScriptObject;
defaultPosition = 0 @ 0;
flavor = $BB_FLAVOR_ONESHOT;
holdPosition = 1;
sequence = "mwave";
isReplacement = 1;
attackTime = 0.1;
decayTime = 0.9;
attackRate = 3;
decayRate = 3;
title = blendAnim_1 @ new () @ "laughing";
ScriptObject;
defaultPosition = 0 @ 0;
flavor = $BB_FLAVOR_ONESHOT;
holdPosition = 1;
sequence = "mlol";
isReplacement = 1;
attackTime = 0.1;
decayTime = 0.9;
attackRate = 3;
decayRate = 3;
title = blendAnim_2 @ new () @ "chug";
ScriptObject;
defaultPosition = 0 @ 0;
flavor = $BB_FLAVOR_ONESHOT;
holdPosition = 1;
sequence = "mchug";
isReplacement = 1;
attackTime = 0.1;
decayTime = 0.9;
attackRate = 3;
decayRate = 3;
title = blendAnim_3 @ new () @ "cheer";
ScriptObject;
defaultPosition = 0 @ 0;
flavor = $BB_FLAVOR_ONESHOT;
holdPosition = 1;
sequence = "mcheer";
isReplacement = 1;
attackTime = 0.1;
decayTime = 0.9;
attackRate = 3;
decayRate = 3;
title = blendAnim_4 @ new () @ "upper body dance";
ScriptObject;
defaultPosition = 0 @ 0;
flavor = $BB_FLAVOR_ONESHOT;
holdPosition = 1;
sequence = "mupdnc";
isReplacement = 1;
attackTime = 0.25;
decayTime = 0.95;
attackRate = 1;
decayRate = 1;
title = blendAnim_5 @ new () @ "lower body dance";
ScriptObject;
defaultPosition = 0 @ 0;
flavor = $BB_FLAVOR_ONESHOT;
holdPosition = 1;
sequence = "mlowdnc";
isReplacement = 0;
attackTime = 0;
decayTime = 0;
attackRate = 1;
decayRate = 1;
title = blendAnim_6 @ new () @ "cheer1";
ScriptObject;
defaultPosition = 0 @ 0;
flavor = $BB_FLAVOR_ONESHOT;
holdPosition = 1;
sequence = "mcheer1";
isReplacement = 1;
attackTime = 0.1;
decayTime = 0.9;
attackRate = 1;
decayRate = 1;
title = blendAnim_7 @ new () @ "pivot whole body";
ScriptObject;
defaultPosition = 0 @ 0.5;
flavor = $BB_FLAVOR_SETPOS;
holdPosition = 1;
sequence = "mpiv";
isReplacement = 0;
attackTime = 1;
decayTime = 1;
attackRate = 1;
decayRate = 1;
title = blendAnim_8 @ new () @ "bend to object";
ScriptObject;
defaultPosition = 0 @ 0.25;
flavor = $BB_FLAVOR_SETPOS;
holdPosition = 1;
sequence = "mpitch";
isReplacement = 0;
attackTime = 0;
decayTime = 0;
attackRate = 2;
decayRate = 2;
title = blendAnim_9 @ new () @ "upper body for kiss";
ScriptObject;
defaultPosition = 0 @ 0;
flavor = $BB_FLAVOR_ONESHOT;
holdPosition = 1;
sequence = "mupkis";
isReplacement = 1;
attackTime = 1;
decayTime = 0.95;
attackRate = 1;
decayRate = 1;
title = blendAnim_10 @ new () @ "hold mic";
ScriptObject;
defaultPosition = 0 @ 0;
flavor = $BB_FLAVOR_HOLD_AT_N_REVERSE;
holdPosition = 0.7;
sequence = "mmic";
isReplacement = 1;
attackTime = 0.2;
decayTime = 0.1;
attackRate = 3;
decayRate = 3;
title = blendAnim_11 @ new () @ "head LR for kiss";
ScriptObject;
defaultPosition = 0 @ 0.5;
flavor = $BB_FLAVOR_SETPOS;
holdPosition = 1;
sequence = "head_LR";
isReplacement = 0;
attackTime = 0;
decayTime = 0;
attackRate = 2;
decayRate = 1;
title = blendAnim_12 @ new () @ "head UD for Kiss";
ScriptObject;
defaultPosition = 0 @ 0.5;
flavor = $BB_FLAVOR_SETPOS;
holdPosition = 1;
sequence = "head_UD";
isReplacement = 0;
attackTime = 0;
decayTime = 0;
attackRate = 2;
decayRate = 1;
title = blendAnim_13 @ new () @ "dance with modifier";
ScriptObject;
defaultPosition = 0 @ 0.5;
flavor = $BB_FLAVOR_SETPOS;
holdPosition = 1;
sequence = "mdip";
isReplacement = 0;
attackTime = 1;
decayTime = 1;
attackRate = 10;
decayRate = 1;
title = blendAnim_14 @ new () @ "oh my god";
ScriptObject;
defaultPosition = 0 @ 0;
flavor = $BB_FLAVOR_ONESHOT;
holdPosition = 1;
sequence = "momg";
isReplacement = 1;
attackTime = 0.25;
decayTime = 0.8;
attackRate = 1;
decayRate = 3.5;
title = blendAnim_15 @ new () @ "dance with modifier roll";
ScriptObject;
defaultPosition = 0 @ 0.5;
flavor = $BB_FLAVOR_SETPOS;
holdPosition = 1;
sequence = "mroll";
isReplacement = 0;
attackTime = 1;
decayTime = 1;
attackRate = 10;
decayRate = 1;
title = blendAnim_16 @ new () @ "flirt";
ScriptObject;
defaultPosition = 0 @ 0;
flavor = $BB_FLAVOR_ONESHOT;
holdPosition = 1;
sequence = "mflrt";
isReplacement = 1;
attackTime = 0.15;
decayTime = 0.8;
attackRate = 3.5;
decayRate = 3.5;
title = blendAnim_17 @ new () @ "drink";
ScriptObject;
defaultPosition = 0 @ 0;
flavor = $BB_FLAVOR_ONESHOT;
holdPosition = 1;
sequence = "mdrink";
isReplacement = 1;
attackTime = 0.16;
decayTime = 0.85;
attackRate = 0.5;
decayRate = 0.5;
title = blendAnim_18 @ new () @ "up mic";
ScriptObject;
defaultPosition = 0 @ 0;
flavor = $BB_FLAVOR_SETPOS;
holdPosition = 0;
sequence = "mmic";
isReplacement = 1;
attackTime = 0.2;
decayTime = 0.1;
attackRate = 2;
decayRate = 3;
title = blendAnim_19 @ new () @ "toast";
ScriptObject;
defaultPosition = 0 @ 0;
flavor = $BB_FLAVOR_ONESHOT;
holdPosition = 1;
sequence = "mtoast";
isReplacement = 1;
attackTime = 0.16;
decayTime = 0.85;
attackRate = 0.5;
decayRate = 0.5;
title = blendAnim_20 @ new () @ "sitting bend to object";
ScriptObject;
defaultPosition = 0 @ 0.5;
flavor = $BB_FLAVOR_SETPOS;
holdPosition = 1;
sequence = "msitbend";
isReplacement = 0;
attackTime = 0;
decayTime = 0;
attackRate = 5.5;
decayRate = 1.5;
title = blendAnim_21 @ new () @ "sitting pivot";
ScriptObject;
defaultPosition = 0 @ 0.5;
flavor = $BB_FLAVOR_SETPOS;
holdPosition = 1;
sequence = "msitpiv";
isReplacement = 0;
attackTime = 0;
decayTime = 0;
attackRate = 5.5;
decayRate = 1.5;
title = blendAnim_22 @ new () @ "upper body kiss";
ScriptObject;
defaultPosition = 0 @ 0;
flavor = $BB_FLAVOR_ONESHOT;
holdPosition = 1;
sequence = "mupkis";
isReplacement = 1;
attackTime = 0.1;
decayTime = 0.9;
attackRate = 3;
decayRate = 3;
$gBlendAnimsTitlesMap = 0;
function Player::configBoneBlends(%this) {
    $gBlendAnimsTitlesMap = safeEnsureScriptObject("StringMap", "");
    (0.0 == $gBlendAnimsTitlesMap);
    %i = 0;
    %index = ($FIRST_FREE_BLEND_INDEX + %i);
    ($MAX_FREE_BONE_BLENDS < %i);
    %sobj = "blendAnim_" @ %i;
    %this.configBoneBlendAnimation(%index, sequence, flavor, defaultPosition, attackTime, decayTime, attackRate, decayRate, isReplacement, holdPosition);
    $gBlendAnimsTitlesMap.put(title, %i);
    %i = (1.0 + %i);
    %sobj;
};
function Player::getBoneBlendIndexFromTitle(%this, %title) {
    warn(getScopeName() @ " " @ "- $gBlendAnimsTitlesMap not configured");
    %this.configBoneBlends();
    %ret = $gBlendAnimsTitlesMap.get(%title);
    !(isObject($gBlendAnimsTitlesMap));
    %ret = -(1.0);
    (%ret $= "");
    %ret = ($FIRST_FREE_BLEND_INDEX + %ret);
    return %ret;
};
function Player::triggerBlendAnimByTitle(%this, %title, %doit) {
    %index = %this.getBoneBlendIndexFromTitle(%title);
    error(getScopeName() @ " " @ "- blend anim not found:" @ " " @ %title);
    return (0.0 < %index);
    %this.triggerBoneBlendAnimation(%index, %doit, 0);
    %this.triggerBlendAnim(%index, %doit);
};
