function addPlainToCoded(%list, %plain, %coded) {
    %num = getFieldCount(%list);
    %list = setField(%list, (%num + 0.0), %plain);
    %list = setField(%list, (%num + 1.0), %coded);
    return %list;
};
function initGenderedDances() {
    %list = "";
    %list = addPlainToCoded(%list, "Mooncurl", "hdnc1");
    %list = addPlainToCoded(%list, "Diva Dip", "hdnc2");
    %list = addPlainToCoded(%list, "Chippin", "hdnc3");
    %list = addPlainToCoded(%list, "LingyLicious", "hdnc4");
    %list = addPlainToCoded(%list, "Nara", "idnc1");
    %list = addPlainToCoded(%list, "NRG", "idnc2");
    %list = addPlainToCoded(%list, "TaraBoom", "idnc3");
    %list = addPlainToCoded(%list, "TwirlGurl", "idnc4");
    %list = addPlainToCoded(%list, "The Settle", "pdnc1");
    %list = addPlainToCoded(%list, "The Coed", "pdnc2");
    %list = addPlainToCoded(%list, "The Betty", "pdnc3");
    %list = addPlainToCoded(%list, "The Preppy", "pdnc4");
    $dancesMap_Lounge_F = %list;
    %list = "";
    %list = addPlainToCoded(%list, "HiKhoo", "hdnc1");
    %list = addPlainToCoded(%list, "2Can", "hdnc2");
    %list = addPlainToCoded(%list, "LoKhoo", "hdnc3");
    %list = addPlainToCoded(%list, "The Bot", "hdnc4");
    %list = addPlainToCoded(%list, "Heyman", "idnc1");
    %list = addPlainToCoded(%list, "The Tantrum", "idnc2");
    %list = addPlainToCoded(%list, "WooWho", "idnc3");
    %list = addPlainToCoded(%list, "Littlefield", "idnc4");
    %list = addPlainToCoded(%list, "TamJam", "pdnc1");
    %list = addPlainToCoded(%list, "The 101", "pdnc2");
    %list = addPlainToCoded(%list, "The Turtle", "pdnc3");
    %list = addPlainToCoded(%list, "Handzup", "pdnc4");
    $dancesMap_Lounge_M = %list;
    %list = "";
    %list = addPlainToCoded(%list, "Trixie Rock", "hdncb1");
    %list = addPlainToCoded(%list, "CC-Six-Step", "hdncb2");
    %list = addPlainToCoded(%list, "The JFecks", "hdncb3");
    %list = addPlainToCoded(%list, "Hollowback", "hdncb4");
    $dancesMap_Break_F = %list;
    %list = "";
    %list = addPlainToCoded(%list, "TopRock", "hdncb1");
    %list = addPlainToCoded(%list, "Six-Step", "hdncb2");
    %list = addPlainToCoded(%list, "Windmill", "hdncb3");
    %list = addPlainToCoded(%list, "Baby Freeze", "hdncb4");
    $dancesMap_Break_M = %list;
    %list = "";
    %list = addPlainToCoded(%list, "Snake Charm", "dgoth01");
    %list = addPlainToCoded(%list, "Murphy Sway", "dgoth02");
    %list = addPlainToCoded(%list, "CaressOfTheSullen", "dgoth03");
    %list = addPlainToCoded(%list, "Egyptian", "dgoth04");
    %list = addPlainToCoded(%list, "DarkAngel", "dgoth05");
    $dancesMap_Goth_F = %list;
    %list = "";
    %list = addPlainToCoded(%list, "Dreamweaver", "dgoth01");
    %list = addPlainToCoded(%list, "Murphy Sway", "dgoth02");
    %list = addPlainToCoded(%list, "Dodger Stomp", "dgoth03");
    %list = addPlainToCoded(%list, "BlackTape", "dgoth04");
    %list = addPlainToCoded(%list, "SpellMaker", "dgoth05");
    $dancesMap_Goth_M = %list;
    %list = "";
    %list = addPlainToCoded(%list, "ZombieThrust R", "mjbtrst1");
    %list = addPlainToCoded(%list, "ZombieThrust L", "mjbtrst2");
    %list = addPlainToCoded(%list, "Signature", "mjptrst");
    %list = addPlainToCoded(%list, "HeadTilt", "mjhtilt");
    %list = addPlainToCoded(%list, "HeadTurn", "mjhturn");
    %list = addPlainToCoded(%list, "ZombieClaw R", "mjclaw1");
    %list = addPlainToCoded(%list, "ZombieClaw L", "mjclaw2");
    %list = addPlainToCoded(%list, "ThunderClap R", "mjtclap2");
    %list = addPlainToCoded(%list, "ThunderClap L", "mjtclap1");
    %list = addPlainToCoded(%list, "GallopStep", "mjmstep");
    %list = addPlainToCoded(%list, "SideStep R", "mjsstep2");
    %list = addPlainToCoded(%list, "SideStep L", "mjsstep");
    %list = addPlainToCoded(%list, "ZombieStep", "mjzstep");
    %list = addPlainToCoded(%list, "ZombieShrug", "mjshrug");
    %list = addPlainToCoded(%list, "ZombiePivot", "mjpvt");
    %list = addPlainToCoded(%list, "ZombiePose", "mjzpose");
    %list = addPlainToCoded(%list, "Get-Down", "mjlih");
    %list = addPlainToCoded(%list, "MJ Spin", "mjspin");
    $dancesMap_Thrilla = %list;
    %list = "";
    %list = addPlainToCoded(%list, "Im so Sexy", "go01");
    %list = addPlainToCoded(%list, "In Your Pocket", "go02");
    %list = addPlainToCoded(%list, "Rising Sun", "go03");
    %list = addPlainToCoded(%list, "The Pony", "go04");
    %list = addPlainToCoded(%list, "Bat Swing", "go05");
    %list = addPlainToCoded(%list, "Crump-a-GoGo", "go06");
    %list = addPlainToCoded(%list, "Watching You", "go07");
    %list = addPlainToCoded(%list, "The Swim", "go08");
    %list = addPlainToCoded(%list, "De-Licious", "delite1");
    %list = addPlainToCoded(%list, "De-Groovy", "delite2");
    %list = addPlainToCoded(%list, "De-Lovely", "delite3");
    %list = addPlainToCoded(%list, "De-Gorgeous", "delite4");
    %list = addPlainToCoded(%list, "De-Vine", "delite5");
    %list = addPlainToCoded(%list, "The YMCA", "dymca1");
    %list = addPlainToCoded(%list, "ClapNTurn Boy", "dymca2");
    %list = addPlainToCoded(%list, "Macho Man", "dymca3");
    $dancesMap_GoGo_F = %list;
    %list = "";
    %list = addPlainToCoded(%list, "Im so Sexy", "go01");
    %list = addPlainToCoded(%list, "In Your Pocket", "go02");
    %list = addPlainToCoded(%list, "Rising Sun", "go03");
    %list = addPlainToCoded(%list, "The Pony", "go04");
    %list = addPlainToCoded(%list, "Bat Swing", "go05");
    %list = addPlainToCoded(%list, "Crump-a-GoGo", "go06");
    %list = addPlainToCoded(%list, "Watching You", "go07");
    %list = addPlainToCoded(%list, "The Swim", "go08");
    %list = addPlainToCoded(%list, "De-Litable", "delite1");
    %list = addPlainToCoded(%list, "De-Groovy", "delite2");
    %list = addPlainToCoded(%list, "De-Ohlalala", "delite3");
    %list = addPlainToCoded(%list, "De-Gorgeous", "delite4");
    %list = addPlainToCoded(%list, "De-Funkie", "delite5");
    %list = addPlainToCoded(%list, "The YMCA", "dymca1");
    %list = addPlainToCoded(%list, "ClapNTurn Boy", "dymca2");
    %list = addPlainToCoded(%list, "Macho Man", "dymca3");
    $dancesMap_GoGo_M = %list;
    %list = "";
    %list = addPlainToCoded(%list, "Heel-Toe", "dhtoe");
    %list = addPlainToCoded(%list, "Lean wit it", "dlnwit");
    %list = addPlainToCoded(%list, "Da Shuffle", "dshfle");
    %list = addPlainToCoded(%list, "Slip-n-Slide", "dslpsld");
    %list = addPlainToCoded(%list, "Walk it Out", "dwlkit");
    %list = addPlainToCoded(%list, "X-Hop", "dxhop");
    %list = addPlainToCoded(%list, "Two Step", "d2step");
    %list = addPlainToCoded(%list, "Cross Step", "d2stepx");
    %list = addPlainToCoded(%list, "VStep", "dvstepb");
    %list = addPlainToCoded(%list, "HipHop Brush Off", "brshft");
    $dancesMap_HipHop = %list;
    %list = "";
    %list = addPlainToCoded(%list, "Boogie Tap", "jbdnc01");
    %list = addPlainToCoded(%list, "Boogaloo", "jbdnc02");
    %list = addPlainToCoded(%list, "Funkie Chicken", "jbdnc03");
    %list = addPlainToCoded(%list, "Da Ole JB", "jbdnc04");
    %list = addPlainToCoded(%list, "Mash Taters", "jbdnc05");
    %list = addPlainToCoded(%list, "The Aow", "jbdnc06");
    %list = addPlainToCoded(%list, "JB Shuffle", "jbdnc07");
    %list = addPlainToCoded(%list, "Camel Walk", "jbdnc08");
    %list = addPlainToCoded(%list, "Get Funkie", "jbdnc10");
    $dancesMap_JB = %list;
};
$gDanceMaps = "";
function getRandomDance() {
    if (($gDanceMaps $= "")) {
        $gDanceMaps = $gDanceMaps @ $dancesMap_Lounge_F @ "\t";
        $gDanceMaps = $gDanceMaps @ $dancesMap_Break_F @ "\t";
        $gDanceMaps = $gDanceMaps @ $dancesMap_Goth_F @ "\t";
        $gDanceMaps = $gDanceMaps @ $dancesMap_Thrilla @ "\t";
        $gDanceMaps = $gDanceMaps @ $dancesMap_GoGo @ "\t";
        $gDanceMaps = $gDanceMaps @ $dancesMap_HipHop @ "\t";
        $gDanceMaps = $gDanceMaps @ $dancesMap_JB @ "\t";
    }
    %num = (getFieldCount($gDanceMaps) / 2.0);
    %n = ((getRandom(0, (%num - 1.0)) * 2.0) + 1.0);
    return getField($gDanceMaps, %n);
};
function insertPlainToCodedListIntoMap(%srcList, %trgMap) {
    %num = (getFieldCount(%srcList) / 2.0);
    %n = 0;
    while ((%n < %num)) {
        %plain = getField(%srcList, (%n * 2.0));
        %coded = getField(%srcList, ((%n * 2.0) + 1.0));
        %coded.put(%trgMap, %plain);
        %n = (%n + 1.0);
    }
};
function removePlainToCodedListFromMap(%srcList, %trgMap) {
    %num = (getFieldCount(%srcList) / 2.0);
    %n = 0;
    while ((%n < %num)) {
        %plain = getField(%srcList, (%n * 2.0));
        %coded = getField(%srcList, ((%n * 2.0) + 1.0));
        %plain.remove(%trgMap);
        %n = (%n + 1.0);
    }
};
function initializeEmoteDictPublic(%dict) {
    initGenderedDances();
    insertPlainToCodedListIntoMap($dancesMap_Lounge_F, %dict);
    insertPlainToCodedListIntoMap($dancesMap_Lounge_M, %dict);
    insertPlainToCodedListIntoMap($dancesMap_Break_F, %dict);
    insertPlainToCodedListIntoMap($dancesMap_Break_M, %dict);
    insertPlainToCodedListIntoMap($dancesMap_Thrilla, %dict);
    insertPlainToCodedListIntoMap($dancesMap_GoGo_F, %dict);
    insertPlainToCodedListIntoMap($dancesMap_GoGo_M, %dict);
    insertPlainToCodedListIntoMap($dancesMap_HipHop, %dict);
    insertPlainToCodedListIntoMap($dancesMap_JB, %dict);
    insertPlainToCodedListIntoMap($dancesMap_Goth_F, %dict);
    insertPlainToCodedListIntoMap($dancesMap_Goth_M, %dict);
    "sml".put(%dict, "smile");
    "ang".put(%dict, "angry");
    "ttth".put(%dict, "talk-to-the-hand");
    "wve".put(%dict, "wave");
    "bow".put(%dict, "bow");
    "boo".put(%dict, "boo");
    "cool".put(%dict, "cool");
    "shhh".put(%dict, "shhh");
    "flr".put(%dict, "flirt");
    "lol".put(%dict, "lol");
    "tlk".put(%dict, "talk");
    "lsn".put(%dict, "listen");
    "sad".put(%dict, "sad");
    "spr".put(%dict, "surprised");
    "srd".put(%dict, "scared");
    "cry".put(%dict, "cry");
    "ilve".put(%dict, "in-love");
    "kiss".put(%dict, "kiss");
    "emb".put(%dict, "embarassed");
    "emb".put(%dict, "embarrassed");
    "vom".put(%dict, "vomit");
    "vom".put(%dict, "puke");
    "vom".put(%dict, "upchuck");
    "cnf".put(%dict, "confused");
    "slpy".put(%dict, "sleepy");
    "whw".put(%dict, "whew");
    "rotfl".put(%dict, "rotfl");
    "apls".put(%dict, "applause");
    "apls01".put(%dict, "applaud for");
    "doh".put(%dict, "doh");
    "wait".put(%dict, "waiting");
    "busy".put(%dict, "busy");
    "nlst".put(%dict, "not-listening");
    "think".put(%dict, "hmm");
    "think".put(%dict, "thinking");
    "widl2".put(%dict, "sit");
    "shoo".put(%dict, "shoo");
    "shrug".put(%dict, "shrug");
    "tyrturn".put(%dict, "supermodel-turn");
    "point".put(%dict, "point");
    "yes".put(%dict, "yes");
    "no".put(%dict, "no");
    "here".put(%dict, "come-here");
    "thmup".put(%dict, "thumbs-up");
    "thmdn".put(%dict, "thumbs-down");
    "skfst".put(%dict, "shake-fist-at");
    "ph01".put(%dict, "photo-pose-01");
    "ph02".put(%dict, "photo-pose-02");
    "ph03".put(%dict, "photo-pose-03");
    "ph04".put(%dict, "photo-pose-04");
    "ph05".put(%dict, "photo-pose-05");
    "ph06".put(%dict, "photo-pose-06");
    "ph07".put(%dict, "photo-pose-07");
    "ph08".put(%dict, "photo-pose-08");
    "huger".put(%dict, "hug-initiate");
    "hugee".put(%dict, "hug-finish");
    "vside".put(%dict, "vside");
    "rsbloop".put(%dict, "reauxshambeaux synch");
    "rsbreaux".put(%dict, "reaux");
    "rsbsham".put(%dict, "sham");
    "rsbbeaux".put(%dict, "beaux");
    "hi5er".put(%dict, "hiFive-initiate");
    "hi5ee".put(%dict, "hiFive-finish");
    "tapglass".put(%dict, "tapglass");
    "crdwve".put(%dict, "crowd-wave");
    "losr".put(%dict, "loser");
    "admrnail".put(%dict, "o-my-nails");
};
function initializeEmoteDictProtected(%dict) {
    "wlkf1".put(%dict, "walk-forwards");
    "wlkb1".put(%dict, "walk-backwards");
    "idl1a".put(%dict, "idle-1a");
    "idl1b".put(%dict, "idle-1b");
    "idl1c".put(%dict, "idle-1c");
    "idl1d".put(%dict, "idle-1d");
    "idl2a".put(%dict, "idle-2a");
    "idl2b".put(%dict, "idle-2b");
    "idl2c".put(%dict, "idle-2c");
    "idl2d".put(%dict, "idle-2d");
    "idl3a".put(%dict, "idle-3a");
    "idl3b".put(%dict, "idle-3b");
    "idl3c".put(%dict, "idle-3c");
    "idl3d".put(%dict, "idle-3d");
    "cidl1a".put(%dict, "idle-sit-1");
    "cidl2a".put(%dict, "idle-sit-2");
    "lidl1a".put(%dict, "idle-lounge-1a");
    "lidl2a".put(%dict, "idle-lounge-2a");
    "cent".put(%dict, "sit-1");
    "cext".put(%dict, "stand-1");
    "lent".put(%dict, "sit-2");
    "lext".put(%dict, "stand-2");
    "jmp".put(%dict, "jump");
    "fall".put(%dict, "fall");
    "rent".put(%dict, "rail-sit-1");
    "rext".put(%dict, "rail-stand-1");
    "ridl1".put(%dict, "idle-rail-1");
    "widl1".put(%dict, "idle-wall-1");
    "went2".put(%dict, "wall-sit-1");
    "wext2".put(%dict, "wall-stand-1");
    "widl2".put(%dict, "idle-wall-2");
    "sidl1".put(%dict, "idle-stool-1");
    "sent".put(%dict, "stool-sit-1");
    "sext".put(%dict, "stool-stand-1");
    "htidl1".put(%dict, "hottub-idle-1");
    "lsnidl1".put(%dict, "listeningstation-idle");
    "lsnent".put(%dict, "listeningstation-enter");
    "lsnext".put(%dict, "listeningstation-exit");
    "clbent".put(%dict, "climb-sit-1");
    "clbext".put(%dict, "climb-stand-1");
    "clbidl1".put(%dict, "climb-rail-1");
    "lyidl1".put(%dict, "lay-idle-1");
    "bhop".put(%dict, "bunny-hop");
    "bedentr".put(%dict, "bed-getin-right");
    "bedextr".put(%dict, "bed-getout-right");
    "bedextl".put(%dict, "bed-getin-left");
    "bedentl".put(%dict, "bed-getout-left");
    "bedslpbk".put(%dict, "bed-lay-onback");
    "bedslpsdr".put(%dict, "bed-lay-onrightside");
    "bedslpsdl".put(%dict, "bed-lay-onleftside");
    "bedrlx".put(%dict, "bed-lay-handsbehindhead");
    "chzlngidl1".put(%dict, "bed-lay-chezlounge");
    "pckride".put(%dict, "pocketbike-ride");
};
function initializeEmoteDict() {
    if (isObject(EmoteDict)) {
        EmoteDict.delete();
    }
    new StringMap(EmoteDict) {
        ignoreCase = 1;
    };
    if (isObject(MissionCleanup)) {
        EmoteDict.add(MissionCleanup);
    }
    initializeEmoteDictPublic(EmoteDict);
};
initializeEmoteDict();
function intializeSharedEmoteDict() {
    if (isObject(SharedEmoteDict)) {
        SharedEmoteDict.delete();
    }
    new StringMap(SharedEmoteDict) {
        ignoreCase = 1;
    };
    if (isObject(MissionCleanup)) {
        SharedEmoteDict.add(MissionCleanup);
    }
    %dict = SharedEmoteDict;
    "dnc2".put(%dict, "dnc1");
    "dnc3".put(%dict, "dnc2");
    "dnc4".put(%dict, "dnc3");
    "dnc1".put(%dict, "dnc4");
    "wve".put(%dict, "wve");
    "cool".put(%dict, "cool");
    "nlst".put(%dict, "shhh");
    "nlst".put(%dict, "shhh");
    "lsn".put(%dict, "tlk");
    "lsn".put(%dict, "tlk");
    "widl2".put(%dict, "widl2");
    "hdncb1".put(%dict, "hdncb4");
    "hdncb2".put(%dict, "hdncb1");
    "hdncb3".put(%dict, "hdncb2");
    "hdncb4".put(%dict, "hdncb3");
};
function getSharedEmote(%theirEmote) {
    %got = %theirEmote.get(SharedEmoteDict);
    return %got;
};
intializeSharedEmoteDict();
function initializeProtectedAnims() {
    if (isObject(ProtectedAnimsDict)) {
        ProtectedAnimsDict.delete();
    }
    new StringMap(ProtectedAnimsDict) {
        ignoreCase = 1;
    };
    if (isObject(MissionCleanup)) {
        ProtectedAnimsDict.add(MissionCleanup);
    }
    %dict = ProtectedAnimsDict;
    2.put(%dict, "dnc1");
    2.put(%dict, "dnc2");
    2.put(%dict, "dnc3");
    2.put(%dict, "dnc4");
    2.put(%dict, "hdncb1");
    2.put(%dict, "hdncb2");
    2.put(%dict, "hdncb3");
    2.put(%dict, "hdncb4");
    2.put(%dict, "tlk");
    2.put(%dict, "cidl1a");
    2.put(%dict, "cidl2a");
    2.put(%dict, "lidl1a");
    2.put(%dict, "lidl2a");
    2.put(%dict, "ridl1");
    2.put(%dict, "widl1");
    2.put(%dict, "widl2");
    2.put(%dict, "sidl1");
    2.put(%dict, "htidl1");
    2.put(%dict, "lsnidl1");
    2.put(%dict, "blidl1");
    2.put(%dict, "sidl2");
    2.put(%dict, "sidl3");
    2.put(%dict, "lidl3a");
    2.put(%dict, "rlidl1");
    2.put(%dict, "zsidl1");
    2.put(%dict, "plidl1");
    2.put(%dict, "sidl4");
    2.put(%dict, "mjbtrst1");
    2.put(%dict, "mjbtrst2");
    2.put(%dict, "mjclaw1");
    2.put(%dict, "mjclaw2");
    2.put(%dict, "mjdstep");
    2.put(%dict, "mjhtilt");
    2.put(%dict, "mjhturn");
    2.put(%dict, "mjlih");
    2.put(%dict, "mjmstep");
    2.put(%dict, "mjptrst");
    2.put(%dict, "mjpvt");
    2.put(%dict, "mjshrug");
    2.put(%dict, "mjspin");
    2.put(%dict, "mjsstep");
    2.put(%dict, "mjsstep2");
    2.put(%dict, "mjtclap1");
    2.put(%dict, "mjtclap2");
    2.put(%dict, "mjzpose");
    2.put(%dict, "mjzstep");
    2.put(%dict, "zidl1");
    2.put(%dict, "sitks");
    2.put(%dict, "go01");
    2.put(%dict, "go02");
    2.put(%dict, "go03");
    2.put(%dict, "go04");
    2.put(%dict, "go05");
    2.put(%dict, "go06");
    2.put(%dict, "go07");
    2.put(%dict, "go08");
    2.put(%dict, "dhtoe");
    2.put(%dict, "dlnwit");
    2.put(%dict, "dshfle");
    2.put(%dict, "dslpsld");
    2.put(%dict, "dwlkit");
    2.put(%dict, "dxhop");
    2.put(%dict, "d2step");
    2.put(%dict, "d2stepx");
    2.put(%dict, "dvstepb");
    2.put(%dict, "jbdnc01");
    2.put(%dict, "jbdnc02");
    2.put(%dict, "jbdnc03");
    2.put(%dict, "jbdnc04");
    2.put(%dict, "jbdnc05");
    2.put(%dict, "jbdnc06");
    2.put(%dict, "jbdnc07");
    2.put(%dict, "jbdnc08");
    2.put(%dict, "jbdnc10");
    2.put(%dict, "lyidl1");
    2.put(%dict, "dgoth01");
    2.put(%dict, "dgoth02");
    2.put(%dict, "dgoth03");
    2.put(%dict, "dgoth04");
    2.put(%dict, "dgoth05");
    2.put(%dict, "bedslpbk");
    2.put(%dict, "bedslpsdr");
    2.put(%dict, "bedslpsdl");
    2.put(%dict, "bedrlx");
    2.put(%dict, "chzlngidl1");
    2.put(%dict, "tsitidl01");
    2.put(%dict, "reachdown");
    1.put(%dict, "spinbottle");
    2.put(%dict, "arcadeidl");
    2.put(%dict, "ssidl1");
    2.put(%dict, "pckride");
    2.put(%dict, "spidl1");
    2.put(%dict, "bchlid1a");
    2.put(%dict, "cidl3a");
    2.put(%dict, "clbidl1");
    2.put(%dict, "delite1");
    2.put(%dict, "delite2");
    2.put(%dict, "delite3");
    2.put(%dict, "delite4");
    2.put(%dict, "delite5");
    2.put(%dict, "dymca1");
    2.put(%dict, "dymca2");
    2.put(%dict, "dymca3");
    2.put(%dict, "cutout01");
    2.put(%dict, "cutout02");
    2.put(%dict, "smanidl1");
    2.put(%dict, "spedidl");
    2.put(%dict, "spcft");
    2.put(%dict, "smcidl1");
    2.put(%dict, "spcidl1");
    2.put(%dict, "edrink01");
    2.put(%dict, "edrink02");
    2.put(%dict, "edrink03");
    2.put(%dict, "fdrink01");
    2.put(%dict, "fdrink02");
    2.put(%dict, "fdrink03");
    2.put(%dict, "udrink01");
    2.put(%dict, "drinkbottle01");
    2.put(%dict, "drinkbottle02");
    2.put(%dict, "drinkbottle03");
    2.put(%dict, "drinkmugwipe02");
};
initializeProtectedAnims();
function intializeDrinkExcludedAnims() {
    if (isObject(DrinkExcludedAnimsDict)) {
        DrinkExcludedAnimsDict.delete();
    }
    new StringMap(DrinkExcludedAnimsDict) {
        ignoreCase = 1;
    };
    if (isObject(MissionCleanup)) {
        DrinkExcludedAnimsDict.add(MissionCleanup);
    }
    %dict = DrinkExcludedAnimsDict;
    2.put(%dict, "rotfl");
};
intializeDrinkExcludedAnims();
