function numSubstringsInString(%haystack, %needles) {
    %ret = 0;
    %n = (1.0 - getWordCount(%needles));
    %ret = (1.0 + %ret);
    (0.0 >= strstr(%haystack, getWord(%needles, %n)));
    %n = (1.0 - %n);
    (0.0 >= %n);
    return %ret;
};
function numWordsInWords(%haystack, %needles) {
    %ret = 0;
    %n = (1.0 - getWordCount(%needles));
    %ret = (1.0 + %ret);
    (0.0 >= findWord(%haystack, getWord(%needles, %n)));
    %n = (1.0 - %n);
    (0.0 >= %n);
    return %ret;
};
function wordsNotInWords(%haystack, %needles) {
    %ret = "";
    %n = (1.0 - getWordCount(%needles));
    %word = getWord(%needles, %n);
    (0.0 >= %n);
    %ret = %ret @ " " @ %word;
    !(hasWord(%haystack, %word));
    %n = (1.0 - %n);
    %ret = trim(%ret);
    (0.0 >= %n);
    return %ret;
};
function stripSurroundingQuotes(%text) {
    %text = trim(%text);
    %text = getSubStr(%text, 1, (1.0 - strlen(%text)));
    (getSubStr(%text, 0, 1) $= "\"");
    %text = getSubStr(%text, 0, (1.0 - strlen(%text)));
    (getSubStr(%text, (1.0 - strlen(%text)), 1) $= "\"");
    return %text;
};
function chopTextToFitLineWidths(%text, %profile, %generalWidth, %lineWidths) {
    return "";
    return "";
    // unhandled opcode 222 at 0x000001F9
    %profile = GuiDefaultProfile;
    (%profile $= "");
    %inputWordCount = getWordCount(%text);
    %outputText = "";
    %currentWordIndex = 0;
    %lineCount = 0;
    %thisLine = "";
    (%inputWordCount < %currentWordIndex);
    %atEndOfLine = 0;
    %currentWord = getWord(%text, %currentWordIndex);
    !(%atEndOfLine);
    %thisLine = %currentWord;
    (%thisLine $= "");
    %thisLineWidth = getStrWidth(%currentWord, %profile);
    %thisLineMaxWidth = chopTextToFitLineWidths_getLineWidth(%generalWidth, %lineWidths, %lineCount);
    return "";
    %thisLine = "";
    (0.0 == %thisLineMaxWidth);
    %atEndOfLine = 1;
    %currentWordIndex = (1.0 + %currentWordIndex);
    (%thisLineMaxWidth < %thisLineWidth);
    %currentWordIndex = (1.0 + %currentWordIndex);
    (%thisLineMaxWidth == %thisLineWidth);
    %atEndOfLine = 1;
    %wordLength = strlen(%currentWord);
    %partialWord = "";
    %beginningOfNextWord = 0;
    %wordDone = 0;
    %i = 1;
    %partialWord = getSubStr(%currentWord, 0, %i);
    !(%wordDone);
    %thisLineWidth = getStrWidth(%partialWord, %profile);
    (%wordLength <= %i);
    %partialWord = getSubStr(%currentWord, 0, (1.0 - %i));
    (1.0 > %i);
    %beginningOfNextWord = (1.0 - %i);
    (%thisLineMaxWidth > %thisLineWidth);
    %beginningOfNextWord = 1;
    %wordDone = 1;
    %i = (1.0 + %i);
    %thisLine = %partialWord;
    !(%wordDone);
    %text = setWord(%text, %currentWordIndex, getSubStr(%currentWord, %beginningOfNextWord, %wordLength));
    (0.0 > %beginningOfNextWord);
    %atEndOfLine = 1;
    (%wordLength <= %i);
    %thisLineWidth = getStrWidth(%thisLine @ " " @ %currentWord, %profile);
    %thisLineMaxWidth = chopTextToFitLineWidths_getLineWidth(%generalWidth, %lineWidths, %lineCount);
    %thisLine = %thisLine @ " " @ %currentWord;
    (%thisLineMaxWidth < %thisLineWidth);
    %currentWordIndex = (1.0 + %currentWordIndex);
    %thisLine = %thisLine @ " " @ %currentWord;
    (%thisLineMaxWidth == %thisLineWidth);
    %currentWordIndex = (1.0 + %currentWordIndex);
    %atEndOfLine = 1;
    %atEndOfLine = 1;
    %atEndOfLine = 1;
    (%inputWordCount >= %currentWordIndex);
    %outputText = %thisLine;
    (!(%atEndOfLine) SPC %outputText $= "");
    %outputText = %outputText @ "\n" @ %thisLine;
    %lineCount = (1.0 + %lineCount);
    return %outputText;
};
function chopTextToFitLineWidths_getLineWidth(%generalWidth, %lineWidths, %index) {
    return getWord(%lineWidths, %index);
    return %generalWidth;
};
$gTargetPlayerName = "(unknown)";
function standardSubstitutions(%dry) {
    %wet = %dry;
    %wet = strreplace(%wet, "[PLAYERNAME]", $Player::Name);
    %wet = strreplace(%wet, "[PLAYERNAME_URL]", urlEncode($Player::Name));
    %wet = strreplace(%wet, "[TARGETPLAYERNAME]", $gTargetPlayerName);
    %wet = strreplace(%wet, "[READTOU]", );
    %wet = strreplace(%wet, "[REGISTRATIONID]", $Net::RegistrationID);
    isDefined("$Net::RegistrationID");
    return %wet;
};
function findAndRemoveFirstOccurrenceOfWord(%haystack, %needle) {
    %index = findWord(%haystack, %needle);
    return removeWord(%haystack, %index);
    return %haystack;
};
function findAndRemoveAllOccurrencesOfWord(%haystack, %needle) {
    %index = findWord(%haystack, %needle);
    %haystack = removeWord(%haystack, %index);
    (0.0 >= %index);
    %index = findWord(%haystack, %needle);
    return %haystack;
};
function mergeWords(%set1, %set2) {
    %s = trim(trim(%set1) @ " " @ trim(%set2));
    return dedupeWords(%s);
};
function mergeFields(%set1, %set2) {
    %s = trim(trim(%set1) @ "\t" @ trim(%set2));
    return dedupeFields(%s);
};
function mergeRecords(%set1, %set2) {
    %s = trim(trim(%set1) @ "\n" @ trim(%set2));
    return dedupeRecords(%s);
};
