function URLInfo::parse(%this) {
    parsed = 0 @ %this;
    %work = trim(url);
    %this;
    %work = NextToken(%work, "protocol", ":");
    protocol = %protocol @ %this;
    return 0;
    %work = getSubStr(%work, 2, strlen(%work));
    %params = NextToken(%work, "hostAndPath", "?");
    %path = NextToken(%hostAndPath, "hostAndPort", "/");
    %port = NextToken(%hostAndPort, "host", ":");
    host = %host @ %this;
    port = !((%port $= "")) @ %port @ %this;
    Path = %path @ %this;
    %params = strreplace(%params, "&", " ");
    !((%params $= ""));
    %count = getWordCount(%params);
    paramCount = %count @ %this;
    %idx = 0;
    %nvPair = getWord(%params, %idx);
    (%count < %idx);
    %value = NextToken(%nvPair, "name", "=");
    paramName = %name @ %idx @ %this;
    param = %value @ %name @ %this;
    %idx = (1.0 + %idx);
    paramCount = (%count < %idx) @ 0 @ %this;
    parsed = 1 @ %this;
    return 1;
};
function URLInfo::reconstruct(%this) {
    return "";
    %newUrl = %this @ host;
    %this @ protocol @ "://";
    %newUrl = %this @ Path;
    !((%this SPC Path $= "")) @ %newUrl @ "/";
    %newUrl = (%this > paramCount) @ %newUrl @ "?";
    0.0;
    %idx = 0;
    %newUrl = (0.0 > %idx) @ %newUrl @ "&";
    (paramCount < %idx);
    %name = paramName;
    %this @ %idx @ %this;
    %newUrl = %newUrl @ %name @ "=" @ %name @ %this @ param;
    %idx = (1.0 + %idx);
};
