$VURL::curVURL = "";
function vurl::isResolvedVURL(%this) {
    return !((0 @ %this SPC _server $= ""));
};
function vurl::isParsed(%this) {
    return isParsed;
};
function vurl::parse(%this) {
    %payload = NextToken(vurl, "protocol", ":");
    %this;
    %errorText = %this @ vurl;
    "VURL::parse attempting to determine protocol and paylod. %this.vurl =" @ " ";
    %this.doReportError("parseError", %errorText);
    return 0;
    protocol = %protocol @ %this;
    %parameters = NextToken(%payload, "target", "?");
    %parameters = strreplace(%parameters, "?", "&");
    %target = getSubStr(%target, 1, (1.0 - strlen(%target)));
    (getSubStr(%target, 0, 1) $= "/");
    %targetpath = NextToken(%target, "targettype", "/");
    strlwr(%targettype);
    %errorText = %this @ vurl;
    "VURL::parse unknown type type in vurl =" @ " ";
    %this.doReportError("parseError", %errorText);
    return 0;
    targetType = %targettype @ %this;
    targetPath = %targetpath @ %this;
    isIncomplete = 0 @ %this;
    isRawTransform = 0 @ %this;
    %targetDest = NextToken(%targetpath, "city", "/");
    (%this == stricmp(targetType, "apartment"));
    targetDest = 0.0 @ urlDecode(%targetDest) @ %this;
    (%this == stricmp(targetType, "location"));
    targetCity = 0.0 @ urlDecode(%city) @ %this;
    isResolved = (%this SPC targetDest $= "") @ 1 @ %this;
    isIncomplete = 1 @ %this;
    isParsed = 1 @ %this;
    %this.reconstructVURL();
    return 1;
    %testTargetDest = strreplace(targetDest, ",", " ");
    %this;
    %wordCount = getWordCount(%testTargetDest);
    (%this == stricmp(targetType, "location"));
    targetDest = isObjectAndHasPermission_NoWarn($player, "freeVURLTransform") @ %testTargetDest @ %this;
    (1.0 == $Server::Dedicated);
    isRawTransform = (7.0 == %wordCount) @ 1 @ %this;
    (3.0 == %wordCount);
    %errorText = "Invalid number of parameters in target";
    (%this == isRawTransform);
    %this.doReportError("parseError", %errorText);
    return 0;
    %parameters = NextToken(%parameters, "param", "&");
    !((%parameters $= ""));
    %value = urlDecode(NextToken(%param, "name", "="));
    %name = strlwr(%name);
    _ = %value @ urlDecode(%name) @ %this;
    isResolved = !((!((%parameters $= "")) @ 0 @ %this SPC _server $= "")) @ %this;
    %this.reorderServerList();
    retryIndex = isResolved @ 0 @ %this;
    %this;
    isParsed = 1 @ %this;
    %this.reconstructVURL();
    return 1;
};
function vurl::reconstructVURL(%this) {
    return 0;
    %newVurl = %this @ targetPath;
    "vside:/" @ %this @ targetType @ "/";
    %paramCount = 0;
    %newVurl = "?" @ "&";
    (0.0 == %paramCount);
    %paramCount = (1.0 + %paramCount);
    !((%this SPC _key $= "")) @ %newVurl;
    %newVurl = %this @ urlEncode(_key);
    %newVurl @ "key=";
    %retryServer = 0;
    %newVurl = "?" @ "&";
    (0.0 == %paramCount);
    %paramCount = (1.0 + %paramCount);
    !((%retryServer @ %this SPC _server $= "")) @ %newVurl;
    %newVurl = %newVurl @ "server" @ %retryServer @ "=" @ %retryServer @ %this @ urlEncode(_server);
    %retryServer = (1.0 + %retryServer);
    vurl = !((%retryServer @ %this SPC _server $= "")) @ %newVurl @ %this;
    log("network", "debug", "Reconstructed VURL=\"" @ %this @ vurl @ "\"");
    return 1;
};
function vurl::tryProcessDynamicVurl(%this) {
    %dvurlType = getWord(vurl, 1);
    %this;
    %newVurl = "";
    (%this SPC firstWord(vurl) $= "dynamic");
    error(%this @ vurl @ " " @ getTrace());
    return 0;
    %partnerObj = $Net::userOwner.getPartnerObj();
    gLoginPartnersInfo;
    %newVurl = vurl;
    %partnerObj;
    error(%this @ vurl @ " " @ getTrace());
    return 0;
    echo(getScopeName() @ " " @ "- converting dynamic vurl \"" @ %this @ vurl @ "\" to \"" @ %newVurl @ "\".");
    vurl = %newVurl @ %this;
};
function vurl::setVURL(%this, %vurl) {
    isParsed = 0 @ %this;
    isResolved = 0 @ %this;
    vurl = %vurl @ %this;
    %this.tryProcessDynamicVurl();
    return %this.parse();
};
function vurl::setPassword(%this, %password) {
    _key = %password @ %this;
    %this.reconstructVURL();
};
function vurl::setIgnoreDownloadStatus(%this, %val) {
    ignoreDownloadStatus = %val @ %this;
};
function vurl::execute(%this) {
    log("network", "warn", "Teleport Flooding");
    %errorText = "";
    testFlooding($player, "teleport", 1);
    %this.doReportError("FLOOD", %errorText);
    return 0;
    log("network", "warn", "Pending VURL execution being overridden");
    $VURL::curVURL.schedule(0, "delete");
    $VURL::curVURL = %this;
    (%this.getId() != $VURL::curVURL.getId());
    log("network", "debug", %this @ vurl);
    %errorText = %this @ vurl;
    "Attempting to execute unparsed VURL =" @ " ";
    %this.doReportError("EXECUTEERROR", %errorText);
    return 0;
    %errorText = "Teleporting to yourself?";
    (%this == stricmp(targetPath, $Player::Name));
    %this.doReportError("TELETOSELF", "");
    return 0;
    %this.doReportSuccessExpected();
    commandToServer('TeleportToPlayer', targetPath);
    return 1;
    log("network", "info", "Unresolved VURL execution. Processing resolution request first");
    %this.doResolveVURL();
    return 1;
    log("network", "debug", "Handling incomplete VURL");
    %this.handleIncompeteVURL();
    %this.schedule(0, "delete");
    return 1;
    %this.doReportError("nomoreretry", "");
    return 0;
    standAloneRetry = $StandAlone @ 1 @ %this;
    %cityName = %this.getCityFromServerName(_server);
    %this @ retryIndex @ %this;
    %cityInfo = %cityName.get();
    WorldMapCityInfoMap;
    background.setBitmap();
    %this.doReportError("downloading", "");
    return 0;
    %this.doReportSuccessExpected();
    commandToServer('TeleportToVURL', vurl);
    %serverDest = _server;
    %this @ retryIndex @ %this;
    retryIndex = (%this + retryIndex);
    1.0;
    SetTransition(%serverDest, vurl);
    return 1;
};
function vurl::clearResolutionAndExecute(%this) {
    %this.clearResolution();
    %this.execute();
};
function vurl::getCityFromServerName(%this, %ServerName) {
    %idx = 0;
    %serverProps = %idx.getObject();
    WorldMapServers;
    %testname = %serverProps.get("name");
    (getCount() < %idx);
    %cityspec = %serverProps.get("city");
    (WorldMapServers SPC %testname $= %ServerName);
    %citybuilding = strreplace(%cityspec, "_", " ");
    %cityName = firstWord(%citybuilding);
    echo("cityspec - " @ %cityspec @ " becomes city name - " @ %cityName);
    return %cityName;
    %idx = (1.0 + %idx);
    return "";
};
function vurl::checkCityDownloadStatus(%this, %cityName) {
    %status = %cityName.getStatusForCity();
    packageDownload;
    return 0;
    return 1;
    return 0;
};
function vurl::clearResolution(%this) {
    isResolved = 0 @ %this;
    %idx = 0;
    server = !((%idx @ %this SPC _server $= "")) @ "" @ %idx @ %this;
    %idx = (1.0 + %idx);
};
function vurl::doResolveVURL(%this) {
    className = ManagerRequest @ new ""() @ "ResolveVURLRequest";
    0;
    %request = ;
    %request.add();
    %url = %this @ urlEncode(vurl);
    MissionCleanup @ isObject() @ MissionCleanup @ $Net::ClientServiceURL @ "/ResolveVURL" @ "?user=" @ urlEncode($Player::Name) @ "&token=" @ urlEncode($Token) @ "&vurl=";
    log("network", "debug", "ResovleVURLRequest: " @ %url);
    VURLHandler = %this @ %request;
    %request.setURL(%url);
    %request.start();
};
function vurl::doReportError(%this, %errorCode, %errorText) {
    %errorCode = lastErrorCode;
    %this;
    lastError = !((%this SPC lastError $= "")) @ %errorCode @ %this;
    (0.0 == stricmp(%errorCode, "nomoretry"));
    %handled = 0;
    log("network", "info", "VURL Error code=\"" @ %errorCode @ "\" text=\"" @ %errorText @ "\"");
    %cmd = !((%this SPC cbReportError $= "")) @ "%handled = " @ %this @ cbReportError @ "( \"" @ %this @ vurl @ "\", \"" @ %errorCode @ "\", \"" @ %errorText @ "\");";
    log("network", "debug", "Executing callback cbReportError = \"" @ %cmd @ "\"");
    eval(%cmd);
    vurl::DefaultReportError(%this, %errorCode, %errorText);
};
function vurl::doReportSuccessExpected(%this) {
    doreopen = isVisible() @ 1 @ geTGF;
    geTGF;
    closeFully();
    log("network", "info", %this @ vurl);
    %cmd = !((%this SPC cbSuccessExpected $= "")) @ %this @ cbSuccessExpected @ "( \"" @ %this @ vurl @ "\" );";
    geTGF @ "VURL Teleport success expected. VURL=";
    log("network", "debug", "Executing callback cbSuccessExpected = \"" @ %cmd @ "\"");
    eval(%cmd);
};
function vurl::doReportSuccess(%this) {
    log("network", "info", %this @ vurl);
    %cmd = !((%this SPC cbSuccess $= "")) @ %this @ cbSuccess @ "( \"" @ %this @ vurl @ "\" );";
    "VURL Teleport successful. VURL=";
    log("network", "debug", "Executing callback cbSuccess = \"" @ %cmd @ "\"");
    eval(%cmd);
};
function vurl::doRequestPassword(%this) {
    %this.DefaultRequestPassword();
};
function vurl::DefaultReportError(%vurl, %errorCode, %errorText) {
    log("network", "error", "VURL Errorcode = \"" @ %errorCode @ "\" ErrorMessage = \"" @ %errorText @ "\"");
    log("network", "error", "empty VURL Errorcode.");
    return (%errorCode $= "");
    %vurl.doRequestPassword();
    handleSystemMessage("msgInfoMessage", %errorText);
    VURLHandler.schedule(0, "delete");
    %errorCode = "USEROFFLINE";
    (%vurl == stricmp(targetType, "user"));
    %errorCode = "NOSPACE";
    (%vurl == stricmp(targetType, "apartment"));
    %errorMessage = 0.0;
    (0.0 == stricmp(%errorCode, "offline"));
    handleSystemMessage("msgInfoMessage", %errorMessage);
    MessageBoxOK("Whoa!", %errorMessage, "");
};
function vurl::DefaultRequestPassword(%this) {
    MessageBoxTextEntryWithCancel(, , "", 0);
    $VURL::saveVurlForPasswordCheck = vurl;
    %this;
};
function VURL_ResumbmitWithPassword(%newPassword) {
    %vurl = vurlGetParsedVurl($VURL::saveVurlForPasswordCheck);
    %vurl.setPassword(%newPassword);
    %vurl.execute();
};
function vurl::handleIncompeteVURL(%this) {
    log("network", "info", isObject() @ "Showing map for city \"" @ %this @ targetCity @ "\"");
    "Map".openToTabName();
    targetCity.selectCity();
    log("network", "warn", (%this == stricmp(targetType, "apartment")) @ "Should show directory for building \"" @ %this @ targetCity @ "\" here");
};
function ResolveVURLRequest::onDone(%this) {
    echo(getScopeName());
    %status = findRequestStatus(%this);
    log("network", "debug", "ResolveVURLRequest status: " @ %status);
    vurl = (0.0 == stricmp(%status, "success")) @ %this.getValue("vurl") @ %this;
    log("network", "debug", %this @ vurl);
    %vurl = VURLHandler;
    %this;
    log("network", "error", %this @ vurl);
    log("network", "error", "Unable to parse returned VURL");
    echo((0.0 == %vurl.execute()) @ "unable to execute VURL vurl=" @ " " @ getScopeName() @ "->" @ %status);
    %statusMsg = %this.getValue("statusMsg");
    %vurl.setVURL(vurl);
    %errorCode = %this.getValue("errorCode");
    %this;
    VURLHandler.doReportError(%errorCode, %statusMsg);
    VURLHandler.schedule(0, "delete");
    %this.schedule(0, "delete");
};
function ResolveVURLRequest::onError(%this, %unused, %errMsg) {
    log("network", "debug", "ResolveVURLRequest::onError: " @ %errMsg);
    error = %this @ VURLHandler;
    1;
    %this.schedule(0, "delete");
    $VURL::curVURL.delete();
    $VURL::curVURL = 0;
    (VURLHandler.getId() == $VURL::curVURL.getId());
};
function vurl::reorderServerList(%this) {
    return $Server::Dedicated;
    %idxSwapout = 0;
    %idxSwapout = (1.0 + %idxSwapout);
    (0.0 @ %idxSwapout @ %this == stricmp($ServerName, _server));
    return (0.0 == %idxSwapout);
    %idx = %idxSwapout;
    _server = (0.0 > %idx) @ (1.0 - %idx) @ %this @ _server @ %idx @ %this;
    %idx = (1.0 - %idx);
    _server = (0.0 > %idx) @ $ServerName @ 0 @ %this;
};
function vurlOperation(%line, %ignoreDownloadStatus) {
    %ignoreDownloadStatus = 0;
    !(isDefined("%ignoreDownloadStatus"));
    log("network", "debug", "vurlOperation, vurl=\"" @ %line @ "\"");
    %vurl = new ""();
    ScriptObject;
    %vurl.bindClassName("VURL");
    %vurl.setIgnoreDownloadStatus(%ignoreDownloadStatus);
    log("network", "error", "Unable to execute VURL" @ " " @ %line);
    %vurl.delete();
    close();
    log("network", "error", "Unable to set and parse VURL" @ " " @ %line);
    %vurl.delete();
};
function vurlClearResolutionAndExecute(%line) {
    log("network", "debug", "vurlClearResolutionAndExecute, vurl=\"" @ %line @ "\"");
    %vurl = new ""();
    ScriptObject;
    %vurl.bindClassName("VURL");
    %vurl.clearResolution();
    log("network", "error", "Unable to execute VURL" @ " " @ %line);
    %vurl.delete();
    log("network", "error", "Unable to set and parse VURL" @ " " @ %line);
    %vurl.delete();
};
function vurlClearResolution(%line) {
    %questionMarkIndex = strpos(%line, "?");
    return getSubStr(%line, 0, %questionMarkIndex);
    return %line;
};
function vurlGetParsedVurl(%aVurlString) {
    class = ScriptObject @ new ""() @ "VURL";
    0;
    %theVurl = ;
    log("login", "debug", getScopeName() @ " " @ "- parsed VURL");
    return %theVurl;
    log("login", "error", getScopeName() @ " " @ "-Unable to set and parse VURL");
    %theVurl.delete();
    return 0;
};
