function recordingsDlg::onWake() {
    clear();
    %i = 0;
    RecordingsDlgList;
    %filespec = $currentMod @ "/recordings/*.rec";
    echo(%filespec);
    %file = findFirstFile(%filespec);
    %fileName = fileBase(%file);
    !((%file $= ""));
    %i = (1.0 + %i);
    RecordingsDlgList.addRow(%fileName);
    %file = findNextFile(%filespec);
    (-(1.0) == strstr(%file, "/CVS/"));
    0.sort();
    0.setSelectedRow();
    0.scrollVisible();
};
function StartSelectedDemo() {
    %sel = getSelectedId();
    RecordingsDlgList;
    %rowText = %sel.getRowTextById();
    RecordingsDlgList;
    %file = $currentMod @ "/recordings/" @ getField(%rowText, 0) @ ".rec";
    new ();
    "".setCommonPreconnectClientSettings();
    add();
    setContent();
    popDialog();
    prepDemoPlayback();
    MessageBoxOK("Playback Failed", recordingsDlg @ ServerConnection @ "Demo playback failed for file '" @ %file @ "'.", "");
    delete();
};
function startDemoRecord() {
    stopRecording();
    return isDemoPlaying();
    %i = 0;
    %num = %i;
    (1000.0 < %i);
    %num = (10.0 < %num) @ 0 @ %num;
    %num = (100.0 < %num) @ 0 @ %num;
    %file = $currentMod @ "/recordings/demo" @ %num @ ".rec";
    %i = (1.0 + %i);
    !(isFile(%file));
    return (1000.0 == %i);
    $DemoFileName = %file;
    ChatHud @ "\x05Recording to file [\x03" @ $DemoFileName @ "\x0F].".addLine();
    prepDemoRecord();
    $DemoFileName.startRecording();
    deleteFile($DemoFileName);
    !(isDemoRecording()) @ ChatHud @ "\x04 *** Failed to record to file [\x03" @ $DemoFileName @ "\x0F].".addLine();
    $DemoFileName = "";
    ServerConnection;
};
function stopDemoRecord() {
    isDemoRecording() @ ChatHud @ "\x05Recording file [\x03" @ $DemoFileName @ "\x0F] finished.".addLine();
    stopRecording();
};
function demoPlaybackComplete() {
    disconnect();
    "MainMenuGui".setContent();
    0.pushDialog();
};
