datablock ParticleData(ChimneySmoke) {
    textureName = "~/data/shapes/particles/smoke";
    dragCoefficient = 0;
    gravityCoefficient = -(0.2);
    inheritedVelFactor = 0;
    lifetimeMS = 3000;
    lifetimeVarianceMS = 250;
    useInvAlpha = 0;
    spinRandomMin = -(30.0);
    spinRandomMax = 30;
    colors = "0.6 0.6 0.6 0.1" @ 0;
    colors = "0.6 0.6 0.6 0.1" @ 1;
    colors = "0.6 0.6 0.6 0.0" @ 2;
    sizes = 0.5 @ 0;
    sizes = 0.75 @ 1;
    sizes = 1.5 @ 2;
    times = 0 @ 0;
    times = 0.5 @ 1;
    times = 1 @ 2;
};
datablock ParticleEmitterData(ChimneySmokeEmitter) {
    ejectionPeriodMS = 20;
    periodVarianceMS = 5;
    ejectionVelocity = 0.25;
    velocityVariance = 0.1;
    thetaMin = 0;
    thetaMax = 90;
    particles = ChimneySmoke;
};
datablock ParticleEmitterNodeData(ChimneySmokeEmitterNode) {
    timeMultiple = 1;
};
datablock ParticleData(ChimneyFire1) {
    textureName = "~/data/shapes/particles/smoke";
    dragCoefficient = 0;
    gravityCoefficient = -(0.3);
    inheritedVelFactor = 0;
    lifetimeMS = 500;
    lifetimeVarianceMS = 250;
    useInvAlpha = 0;
    spinRandomMin = -(30.0);
    spinRandomMax = 30;
    colors = "0.8 0.6 0.0 0.1" @ 0;
    colors = "0.8 0.6 0.0 0.1" @ 1;
    colors = "0.0 0.0 0.0 0.0" @ 2;
    sizes = 1 @ 0;
    sizes = 1 @ 1;
    sizes = 5 @ 2;
    times = 0 @ 0;
    times = 0.5 @ 1;
    times = 1 @ 2;
};
datablock ParticleData(ChimneyFire2) {
    textureName = "~/data/shapes/particles/smoke";
    dragCoefficient = 0;
    gravityCoefficient = -(0.5);
    inheritedVelFactor = 0;
    lifetimeMS = 800;
    lifetimeVarianceMS = 150;
    useInvAlpha = 0;
    spinRandomMin = -(30.0);
    spinRandomMax = 30;
    colors = "0.6 0.6 0.0 0.1" @ 0;
    colors = "0.6 0.6 0.0 0.1" @ 1;
    colors = "0.0 0.0 0.0 0.0" @ 2;
    sizes = 0.5 @ 0;
    sizes = 0.5 @ 1;
    sizes = 0.5 @ 2;
    times = 0 @ 0;
    times = 0.5 @ 1;
    times = 1 @ 2;
};
datablock ParticleEmitterData(ChimneyFireEmitter) {
    ejectionPeriodMS = 15;
    periodVarianceMS = 5;
    ejectionVelocity = 0.25;
    velocityVariance = 0.1;
    thetaMin = 0;
    thetaMax = 90;
    particles = "ChimneyFire1" @ "\t" @ "ChimneyFire2";
};
datablock ParticleEmitterNodeData(ChimneyFireEmitterNode) {
    timeMultiple = 1;
};
