$Game::Duration = (60.0 * $Pref::Server::TimeLimit);
$Game::EndGameScore = 30;
$Game::EndGamePause = 10;
function onServerCreated() {
    $Server::GameType = "PCD";
    $Server::MissionType = "Lounge";
    $Game::StartTime = 0;
    exec("./audioProfiles.cs");
    exec("./camera.cs");
    exec("./markers.cs");
    exec("./shapeBase.cs");
    exec("./item.cs");
    exec("./staticShape.cs");
    exec("./player.cs");
    exec("./aiPlayer.cs");
    exec("./triggers.cs");
    exec("projects/common/shapes/adverts/adverts.cs");
    exec("projects/common/worlds/props.cs");
    exec("./ets/sitting.cs");
    exec("./ets/doors.cs");
    exec("./ets/ambientAnimateShape.cs");
    exec("./ets/particles.cs");
    exec("./ets/NPC_Datablocks.cs");
    exec("common/synapseGaming/contentPacks/lightingPack/sgDeployServer.cs");
    $Game::StartTime = $Sim::Time;
    schedule(0, 0);
    return serverStart;
};
function onServerDestroyed() {
    echo("server exiting");
    return;
};
function onMissionLoaded() {
    startGame();
    return;
};
function onMissionEnded() {
    cancel($Game::Schedule);
    $Game::Running = 0;
    $Game::Cycling = 0;
    return;
};
function startGame() {
    error("startGame: End the game first!");
    return $Game::Running;
    restoreTransformsSet();
    copyObjectNamesToShapeNamesSet();
    registerInPlayerDictSet();
    %clientIndex = 0;
    NPCGroup;
    %cl = %clientIndex.getObject();
    ClientGroup;
    commandToClient(%cl, 'GameStart');
    score = (getCount() < %clientIndex) @ 0 @ %cl;
    ClientGroup;
    %clientIndex = (1.0 + %clientIndex);
    NPCGroup;
    new ();
    add();
    think();
    new ();
    add();
    init();
    think();
    new ();
    add();
    init();
    think();
    InitSittingSystem();
    $Game::Schedule = schedule((1000.0 * $Game::Duration), 0, "onGameDurationEnd");
    $Game::Duration;
    $Game::Running = 1;
    NPCManager;
    return NPCManager;
};
function endGame() {
    error("endGame: No game running!");
    return !($Game::Running);
    cancel($Game::Schedule);
    %clientIndex = 0;
    %cl = %clientIndex.getObject();
    ClientGroup;
    commandToClient(%cl, 'GameEnd');
    %clientIndex = (1.0 + %clientIndex);
    (getCount() < %clientIndex);
    resetMission();
    $Game::Running = 0;
    (getCount() < %clientIndex);
    return ClientGroup;
};
function onGameDurationEnd() {
    cycleGame();
    return !(isObject());
};
function cycleGame() {
    $Game::Cycling = 1;
    !($Game::Cycling);
    $Game::Schedule = schedule(0, 0, "onCycleExec");
    return;
};
function onCycleExec() {
    endGame();
    $Game::Schedule = schedule((1000.0 * $Game::EndGamePause), 0, "onCyclePauseEnd");
    return;
};
function onCyclePauseEnd() {
    $Game::Cycling = 0;
    %search = $Server::MissionFileSpec;
    %file = findFirstFile(%search);
    %file = findNextFile(%search);
    (!((%file $= "")) SPC %file $= $Server::MissionFile);
    %file = findFirstFile(%search);
    (%file $= "");
    %file = findNextFile(%search);
    loadMission(%file);
    return !((%file $= ""));
};
function GameConnection::onClientEnterGame(%this) {
    commandToClient(%this, 'SyncClock', ($Game::StartTime - $Sim::Time));
    dataBlock = new ""() @ Observer;
    Camera;
    Camera = 0 @ %this;
    Camera.add();
    Camera.scopeToClient(%this);
    score = %this @ 0 @ %this;
    %this;
    %this.spawnPlayer();
    return MissionCleanup;
};
function GameConnection::onClientLeaveGame(%this) {
    nameBase.remove();
    %this.setPlayerObject(0);
    Camera.delete();
    Player.delete();
    return %this;
};
function GameConnection::onLeaveMissionArea(%this) {
    return;
};
function GameConnection::onEnterMissionArea(%this) {
    return;
};
function GameConnection::onDeath(%this, %unused, %sourceClient, %damageType, %unused) {
    Player.setShapeName("");
    Camera.setMode("Corpse", Player);
    %this.setControlObject(Camera);
    Player = %this @ 0 @ %this;
    %this;
    %this.incScore(-(1.0));
    messageAll('MsgClientKilled', '%1 takes his own life!', name);
    %sourceClient.incScore(1);
    messageAll('MsgClientKilled', '%1 gets nailed by %2!', name, name);
    cycleGame();
    return (%sourceClient >= score);
};
function GameConnection::spawnPlayer(%this) {
    %spawnPoint = pickSpawnPoint();
    %this.createPlayer(%spawnPoint);
    return;
};
function GameConnection::createPlayer(%this, %spawnPoint) {
    error("Attempting to create an angus ghost!");
    return (%this > Player);
    // unhandled opcode 1141 at 0x00000601
    %this = PlayerF;
    (%this SPC gender $= "f");
    // unhandled opcode 1141 at 0x00000616
    %this = PlayerM;
    (%this SPC gender $= "m");
    // unhandled opcode 1141 at 0x0000062F
    (0.0 == getRandom(0, 1));
    gender = "f" @ %this;
    // unhandled opcode 1141 at 0x00000643
    %this = PlayerM;
    gender = "m" @ %this;
    dataBlock = Player @ new ""() @ %playerDB;
    0;
    client = %this;
    %player = ;
    %rand = getRandom(0, 2);
    %genre = "h";
    (0.0 == %rand);
    %genre = "i";
    (1.0 == %rand);
    %genre = "p";
    (2.0 == %rand);
    %player.setGender(gender);
    %player.setGenre(%genre);
    %player.MeshOff(%this @ gender @ ".headphones.dj");
    %w = Wardrobe::findWardrobe(gender);
    %this;
    outfit = %w @ newOutfit(%w) @ %player;
    %this;
    outfit.assert(%player);
    %player.add();
    %player.setTransform(%spawnPoint);
    %player.setShapeName(name);
    %this.determinePermissions(%player);
    Camera.setTransform(%player.getEyeTransform());
    Player = %this @ %player @ %this;
    %this;
    %this.setControlObject(%player);
    %this.setPlayerObject(%player);
    nameBase.put(Player);
    %player.setAwayMessage($Pref::Player::defaultAwayMessage);
    echo(getDebugString(%player) @ " " @ "has away message" @ " " @ %player.getAwayMessage());
    %this.initPlayerRelations();
    echo("server-side player entered:\x03" @ " " @ getDebugString(%player));
    return %this;
};
function GameConnection::initPlayerRelations() {
    %request = request;
    %this;
    %buddyCount = buddyCount;
    %request;
    %buddyCount = (0.0 >= (1.0 - %buddyCount));
    %buddyName = buddy;
    isObject(request) @ %buddyCount @ %request;
    %buddyPlayer = %buddyName.get();
    PlayerDict;
    %player.addBuddy(%buddyPlayer);
    %buddyCount = (0.0 >= (1.0 - %buddyCount));
    %ignoreCount = ignoreCount;
    %request;
    %ignoreCount = (0.0 >= (1.0 - %ignoreCount));
    %ignoreName = ignore;
    isObject(%buddyPlayer) @ %ignoreCount @ %request;
    %ignorePlayer = %ignoreName.get();
    PlayerDict;
    %player.addIgnore(%ignorePlayer);
    %ignoreCount = (0.0 >= (1.0 - %ignoreCount));
    %onBuddyCount = onBuddyCount;
    %request;
    %onBuddyCount = (0.0 >= (1.0 - %onBuddyCount));
    %onBuddyName = onBuddy;
    isObject(%ignorePlayer) @ %onBuddyCount @ %request;
    %onBuddyPlayer = %onBuddyName.get();
    PlayerDict;
    %onBuddyPlayer.addBuddy(%player);
    warn(isObject(%onBuddyPlayer) @ "no player object for on buddy " @ %onBuddyName);
    %onBuddyCount = (0.0 >= (1.0 - %onBuddyCount));
    %onIgnoreCount = onIgnoreCount;
    %request;
    %onIgnoreCount = (0.0 >= (1.0 - %onIgnoreCount));
    %onIgnoreName = onIgnore;
    %this @ %onIgnoreCount @ %request;
    %onIgnorePlayer = %onIgnoreName.get();
    PlayerDict;
    %onIgnorePlayer.addIgnore(%player);
    warn(isObject(%onIgnorePlayer) @ "no player object for on ignore " @ %onIgnorePlayer);
    %onIgnoreCount = (0.0 >= (1.0 - %onIgnoreCount));
};
function pickSpawnPoint() {
    %groupName = "MissionGroup/PlayerDropPoints";
    %group = nameToID(%groupName);
    %count = %group.getCount();
    (-(1.0) != %group);
    %index = getRandom((1.0 - %count));
    (0.0 != %count);
    %spawn = %group.getObject(%index);
    return %spawn.getEmptySpot(1.5, 0, 1);
    error("No spawn points found in " @ %groupName);
    error("Missing spawn points group " @ %groupName);
    return "0 0 300 1 0 0 0";
};
