category = WayPointMarker @ datablock () @ "Misc";
MissionMarkerData;
shapeFile = 0 @ "projects/common/worlds/markers/octahedron.dts";
category = SpawnSphereMarker @ datablock () @ "Misc";
MissionMarkerData;
shapeFile = 0 @ "projects/common/worlds/markers/octahedron.dts";
function MissionMarkerData::Create(%block) {
    dataBlock = WayPoint @ new ""() @ %block;
    0;
    %obj = (%block $= "WayPointMarker");
    return %obj;
    dataBlock = SpawnSphere @ new ""() @ %block;
    0;
    %obj = (%block $= "SpawnSphereMarker");
    return %obj;
    dataBlock = MissionMarker @ new ""() @ %block;
    0;
    sitOffset = (%block $= "SeatMarker") @ %block @ sitOffset;
    sitAnim = %block @ sitAnim;
    standAnim = %block @ standAnim;
    sitIdle = %block @ sitIdle;
    idleDelay = %block @ idleDelay;
    listeningStation = %block @ listeningStation;
    sitSound = %block @ sitSound;
    standSound = %block @ standSound;
    %obj = ;
    return %obj;
    return -(1.0);
};
