exec("projects/common/characters/initReloadable.cs");
fileName = FootLightSoftSound @ datablock () @ "projects/common/sound/footstep_soft.wav";
AudioProfile;
description = 0 @ AudioClosest3d;
preload = 1;
fileName = FootLightHardSound @ datablock () @ "projects/common/sound/footstep_hard.wav";
AudioProfile;
description = 0 @ AudioClose3d;
preload = 1;
fileName = FootLightMetalSound @ datablock () @ "projects/common/sound/footstep_hard.wav";
AudioProfile;
description = 0 @ AudioClose3d;
preload = 1;
fileName = FootLightSnowSound @ datablock () @ "projects/common/sound/footstep_soft.wav";
AudioProfile;
description = 0 @ AudioClosest3d;
preload = 1;
fileName = FootLightShallowSplashSound @ datablock () @ "projects/common/sound/footstep_water.wav";
AudioProfile;
description = 0 @ AudioClose3d;
preload = 1;
fileName = FootLightWadingSound @ datablock () @ "projects/common/sound/footstep_water.wav";
AudioProfile;
description = 0 @ AudioClose3d;
preload = 1;
fileName = FootLightUnderwaterSound @ datablock () @ "projects/common/sound/footstep_water.wav";
AudioProfile;
description = 0 @ AudioClosest3d;
preload = 1;
fileName = FootLightBubblesSound @ datablock () @ "projects/common/sound/replaceme.wav";
AudioProfile;
description = 0 @ AudioClose3d;
preload = 1;
fileName = ArmorMoveBubblesSound @ datablock () @ "projects/common/sound/replaceme.wav";
AudioProfile;
description = 0 @ AudioCloseLooping3d;
preload = 1;
fileName = WaterBreathMaleSound @ datablock () @ "projects/common/sound/replaceme.wav";
AudioProfile;
description = 0 @ AudioClosestLooping3d;
preload = 1;
fileName = ImpactLightSoftSound @ datablock () @ "projects/common/sound/replaceme.wav";
AudioProfile;
description = 0 @ AudioClose3d;
preload = 1;
effect = ImpactSoftEffect;
fileName = ImpactLightHardSound @ datablock () @ "projects/common/sound/replaceme.wav";
AudioProfile;
description = 0 @ AudioClose3d;
preload = 1;
effect = ImpactHardEffect;
fileName = ImpactLightMetalSound @ datablock () @ "projects/common/sound/replaceme.wav";
AudioProfile;
description = 0 @ AudioClose3d;
preload = 1;
effect = ImpactMetalEffect;
fileName = ImpactLightSnowSound @ datablock () @ "projects/common/sound/replaceme.wav";
AudioProfile;
description = 0 @ AudioClosest3d;
preload = 1;
effect = ImpactSnowEffect;
fileName = ImpactLightWaterEasySound @ datablock () @ "projects/common/sound/replaceme.wav";
AudioProfile;
description = 0 @ AudioClose3d;
preload = 1;
fileName = ImpactLightWaterMediumSound @ datablock () @ "projects/common/sound/replaceme.wav";
AudioProfile;
description = 0 @ AudioClose3d;
preload = 1;
fileName = ImpactLightWaterHardSound @ datablock () @ "projects/common/sound/replaceme.wav";
AudioProfile;
description = 0 @ AudioDefault3d;
preload = 1;
fileName = ExitingWaterLightSound @ datablock () @ "projects/common/sound/replaceme.wav";
AudioProfile;
description = 0 @ AudioClose3d;
preload = 1;
dragCoefficient = PlayerSplashMist @ datablock () @ 2;
ParticleData;
gravityCoefficient = 0 @ -(0.05);
inheritedVelFactor = 0;
constantAcceleration = 0;
lifetimeMS = 400;
lifetimeVarianceMS = 100;
useInvAlpha = 0;
spinRandomMin = -(90.0);
spinRandomMax = 500;
textureName = "projects/common/characters/splash";
colors = "0.7 0.8 1.0 1.0" @ 0;
colors = "0.7 0.8 1.0 0.5" @ 1;
colors = "0.7 0.8 1.0 0.0" @ 2;
sizes = 0.5 @ 0;
sizes = 0.5 @ 1;
sizes = 0.8 @ 2;
times = 0 @ 0;
times = 0.5 @ 1;
times = 1 @ 2;
ejectionPeriodMS = PlayerSplashMistEmitter @ datablock () @ 5;
ParticleEmitterData;
periodVarianceMS = 0 @ 0;
ejectionVelocity = 3;
velocityVariance = 2;
ejectionOffset = 0;
thetaMin = 85;
thetaMax = 85;
phiReferenceVel = 0;
phiVariance = 360;
overrideAdvance = 0;
lifetimeMS = 250;
particles = "PlayerSplashMist";
dragCoefficient = PlayerBubbleParticle @ datablock () @ 0;
ParticleData;
gravityCoefficient = 0 @ -(0.5);
inheritedVelFactor = 0;
constantAcceleration = 0;
lifetimeMS = 400;
lifetimeVarianceMS = 100;
useInvAlpha = 0;
textureName = "projects/common/characters/splash";
colors = "0.7 0.8 1.0 0.4" @ 0;
colors = "0.7 0.8 1.0 0.4" @ 1;
colors = "0.7 0.8 1.0 0.0" @ 2;
sizes = 0.1 @ 0;
sizes = 0.3 @ 1;
sizes = 0.3 @ 2;
times = 0 @ 0;
times = 0.5 @ 1;
times = 1 @ 2;
ejectionPeriodMS = PlayerBubbleEmitter @ datablock () @ 1;
ParticleEmitterData;
periodVarianceMS = 0 @ 0;
ejectionVelocity = 2;
ejectionOffset = 0.5;
velocityVariance = 0.5;
thetaMin = 0;
thetaMax = 80;
phiReferenceVel = 0;
phiVariance = 360;
overrideAdvance = 0;
particles = "PlayerBubbleParticle";
dragCoefficient = PlayerFoamParticle @ datablock () @ 2;
ParticleData;
gravityCoefficient = 0 @ -(0.05);
inheritedVelFactor = 0;
constantAcceleration = 0;
lifetimeMS = 400;
lifetimeVarianceMS = 100;
useInvAlpha = 0;
spinRandomMin = -(90.0);
spinRandomMax = 500;
textureName = "projects/common/characters/splash";
colors = "0.7 0.8 1.0 0.20" @ 0;
colors = "0.7 0.8 1.0 0.20" @ 1;
colors = "0.7 0.8 1.0 0.00" @ 2;
sizes = 0.2 @ 0;
sizes = 0.4 @ 1;
sizes = 1.6 @ 2;
times = 0 @ 0;
times = 0.5 @ 1;
times = 1 @ 2;
ejectionPeriodMS = PlayerFoamEmitter @ datablock () @ 10;
ParticleEmitterData;
periodVarianceMS = 0 @ 0;
ejectionVelocity = 3;
velocityVariance = 1;
ejectionOffset = 0;
thetaMin = 85;
thetaMax = 85;
phiReferenceVel = 0;
phiVariance = 360;
overrideAdvance = 0;
particles = "PlayerFoamParticle";
dragCoefficient = PlayerFoamDropletsParticle @ datablock () @ 1;
ParticleData;
gravityCoefficient = 0 @ 0.2;
inheritedVelFactor = 0.2;
constantAcceleration = -(0.0);
lifetimeMS = 600;
lifetimeVarianceMS = 0;
textureName = "projects/common/characters/splash";
colors = "0.7 0.8 1.0 1.0" @ 0;
colors = "0.7 0.8 1.0 0.5" @ 1;
colors = "0.7 0.8 1.0 0.0" @ 2;
sizes = 0.8 @ 0;
sizes = 0.3 @ 1;
sizes = 0 @ 2;
times = 0 @ 0;
times = 0.5 @ 1;
times = 1 @ 2;
ejectionPeriodMS = PlayerFoamDropletsEmitter @ datablock () @ 7;
ParticleEmitterData;
periodVarianceMS = 0 @ 0;
ejectionVelocity = 2;
velocityVariance = 1;
ejectionOffset = 0;
thetaMin = 60;
thetaMax = 80;
phiReferenceVel = 0;
phiVariance = 360;
overrideAdvance = 0;
orientParticles = 1;
particles = "PlayerFoamDropletsParticle";
dragCoefficient = PlayerSplashParticle @ datablock () @ 1;
ParticleData;
gravityCoefficient = 0 @ 0.2;
inheritedVelFactor = 0.2;
constantAcceleration = -(0.0);
lifetimeMS = 600;
lifetimeVarianceMS = 0;
colors = "0.7 0.8 1.0 1.0" @ 0;
colors = "0.7 0.8 1.0 0.5" @ 1;
colors = "0.7 0.8 1.0 0.0" @ 2;
sizes = 0.5 @ 0;
sizes = 0.5 @ 1;
sizes = 0.5 @ 2;
times = 0 @ 0;
times = 0.5 @ 1;
times = 1 @ 2;
ejectionPeriodMS = PlayerSplashEmitter @ datablock () @ 1;
ParticleEmitterData;
periodVarianceMS = 0 @ 0;
ejectionVelocity = 3;
velocityVariance = 1;
ejectionOffset = 0;
thetaMin = 60;
thetaMax = 80;
phiReferenceVel = 0;
phiVariance = 360;
overrideAdvance = 0;
orientParticles = 1;
lifetimeMS = 100;
particles = "PlayerSplashParticle";
numSegments = PlayerSplash @ datablock () @ 15;
SplashData;
ejectionFreq = 0 @ 15;
ejectionAngle = 40;
ringLifetime = 0.5;
lifetimeMS = 300;
velocity = 4;
startRadius = 0;
acceleration = -(3.0);
texWrap = 5;
texture = "projects/common/characters/splash";
emitter = PlayerSplashEmitter @ 0;
emitter = PlayerSplashMistEmitter @ 1;
colors = "0.7 0.8 1.0 0.0" @ 0;
colors = "0.7 0.8 1.0 0.3" @ 1;
colors = "0.7 0.8 1.0 0.7" @ 2;
colors = "0.7 0.8 1.0 0.0" @ 3;
times = 0 @ 0;
times = 0.4 @ 1;
times = 0.8 @ 2;
times = 1 @ 3;
dragCoefficient = LightPuff @ datablock () @ 2;
ParticleData;
gravityCoefficient = 0 @ -(0.01);
inheritedVelFactor = 0.6;
constantAcceleration = 0;
lifetimeMS = 800;
lifetimeVarianceMS = 100;
useInvAlpha = 1;
spinRandomMin = -(35.0);
spinRandomMax = 35;
colors = "1.0 1.0 1.0 1.0" @ 0;
colors = "1.0 1.0 1.0 0.0" @ 1;
sizes = 0.1 @ 0;
sizes = 0.8 @ 1;
times = 0.3 @ 0;
times = 1 @ 1;
ejectionPeriodMS = LightPuffEmitter @ datablock () @ 35;
ParticleEmitterData;
periodVarianceMS = 0 @ 10;
ejectionVelocity = 0.2;
velocityVariance = 0.1;
ejectionOffset = 0;
thetaMin = 20;
thetaMax = 60;
phiReferenceVel = 0;
phiVariance = 360;
overrideAdvance = 0;
useEmitterColors = 1;
particles = "LightPuff";
dragCoefficient = LiftoffDust @ datablock () @ 1;
ParticleData;
gravityCoefficient = 0 @ -(0.01);
inheritedVelFactor = 0;
constantAcceleration = 0;
lifetimeMS = 1000;
lifetimeVarianceMS = 100;
useInvAlpha = 1;
spinRandomMin = -(90.0);
spinRandomMax = 500;
colors = "1.0 1.0 1.0 1.0" @ 0;
sizes = 1 @ 0;
times = 1 @ 0;
ejectionPeriodMS = LiftoffDustEmitter @ datablock () @ 5;
ParticleEmitterData;
periodVarianceMS = 0 @ 0;
ejectionVelocity = 2;
velocityVariance = 0;
ejectionOffset = 0;
thetaMin = 90;
thetaMax = 90;
phiReferenceVel = 0;
phiVariance = 360;
overrideAdvance = 0;
useEmitterColors = 1;
particles = "LiftoffDust";
sizeX = PlayerFootprint @ datablock () @ 0.25;
DecalData;
sizeY = 0 @ 0.25;
textureName = "projects/common/characters/footprint";
explodeOnMaxBounce = PlayerDebris @ datablock () @ 0;
DebrisData;
elasticity = 0 @ 0.15;
friction = 0.5;
lifetime = 4;
lifetimeVariance = 0;
minSpinSpeed = 40;
maxSpinSpeed = 600;
numBounces = 5;
bounceVariance = 0;
staticOnMaxBounce = 1;
gravModifier = 1;
useRadiusMass = 1;
baseRadius = 1;
velocity = 20;
velocityVariance = 12;
renderFirstPerson = PlayerBody @ datablock () @ 0;
PlayerData;
emap = 0 @ 1;
className = armor;
shapeFile = "projects/common/characters/f_player/f_player.dts";
cameraMaxDist = 3;
computeCRC = 1;
meshCategory01 = "feet";
meshCategory02 = "legs";
meshCategory03 = "torso";
meshCategory04 = "face";
meshCategory05 = "hair";
meshCategory06 = "glasses";
meshCategory07 = "";
meshCategory08 = "";
meshCategory09 = "";
meshCategory10 = "";
meshCategory11 = "";
meshCategory12 = "";
toonShaded = 1;
toonUseAmbient = 1;
toonStyle = 3;
toonLineWidth = 3;
toonLightMapTexture = "projects/common/cubemaps/celcube2";
toonColorOutl = "0.0 0.0 0.0";
toonColorOutl1 = "0.3 0.0 0.1";
toonColorOutl2 = "0.2 0.0 0.1";
toonColorOutl3 = "1.0 0.5 0.1";
toonColorFill = "0.0 0.0 0.0";
toonColorFillS = "1.0 0.0 0.1";
toonColorFillH = "0.4 0.8 0.9";
toonColorFillHS = "1.0 0.5 0.1";
toonColorFillAFK = "0.2 0.1 0.1";
toonMaxThicknessDist = 2;
canObserve = 1;
cmdCategory = "Clients";
cameraDefaultFov = 90;
cameraMinFov = 56;
cameraMaxFov = 120;
cameraLookatOffset = "0.2 0 -0.4";
cameraMaxDist = 2;
debrisShapeName = "";
Debris = PlayerDebris;
aiAvoidThis = 1;
minLookAngle = -(1.0);
maxLookAngle = 1.6;
maxFreelookAngle = 3;
maxTimeScale = 1.2;
maxStepHeight = 0.5;
mass = 90;
drag = 0.3;
maxDrag = 0.4;
density = 10;
maxDamage = 100;
maxEnergy = 60;
repairRate = 0.33;
energyPerDamagePoint = 75;
rechargeRate = 0.256;
runForce = (90.0 * 48.0);
runEnergyDrain = 0;
minRunEnergy = 0;
minForwardSpeed = 3;
maxForwardSpeed = 6;
minToMaxSpeedSecs = 8;
maxBackwardSpeed = 3;
maxSideSpeed = 2;
maxUnderwaterForwardSpeed = 8.4;
maxUnderwaterBackwardSpeed = 7.8;
maxUnderwaterSideSpeed = 7.8;
jumpForce = (90.0 * 8.3);
jumpEnergyDrain = 0;
minJumpEnergy = 0;
jumpDelay = 12;
recoverDelay = 9;
recoverRunForceScale = 1.2;
minImpactSpeed = 45;
speedDamageScale = 0.4;
boundingBox = "0.65 0.65 1.7";
vsPlayerRadius = 0.2;
vsPlayerPushing = 0.2;
vsPlayerMushing = 0.85;
pickupRadius = 0.5;
boxNormalHeadPercentage = 0.83;
boxNormalTorsoPercentage = 0.49;
boxHeadLeftPercentage = 0;
boxHeadRightPercentage = 1;
boxHeadBackPercentage = 0;
boxHeadFrontPercentage = 1;
DecalData = PlayerFootprint;
decalOffset = 0.25;
footPuffEmitter = LightPuffEmitter;
footPuffNumParts = 10;
footPuffRadius = 0.25;
dustEmitter = LiftoffDustEmitter;
Splash = PlayerSplash;
splashVelocity = 4;
splashAngle = 67;
splashFreqMod = 300;
splashVelEpsilon = 0.6;
bubbleEmitTime = 0.4;
splashEmitter = PlayerFoamDropletsEmitter @ 0;
splashEmitter = PlayerFoamEmitter @ 1;
splashEmitter = PlayerBubbleEmitter @ 2;
mediumSplashSoundVelocity = 10;
hardSplashSoundVelocity = 20;
exitSplashSoundVelocity = 5;
runSurfaceAngle = 70;
jumpSurfaceAngle = 80;
minJumpSpeed = 20;
maxJumpSpeed = 30;
horizMaxSpeed = 68;
horizResistSpeed = 33;
horizResistFactor = 0.35;
upMaxSpeed = 80;
upResistSpeed = 25;
upResistFactor = 0.3;
footstepSplashHeight = 0.35;
FootSound0 = StepSoundWood;
FootSound1 = StepSoundDefault;
FootSound2 = StepSoundDefault;
FootSound3 = StepSoundDefault;
FootShallowSound = StepSoundDefault;
FootWadingSound = StepSoundDefault;
FootUnderwaterSound = StepSoundDefault;
groundImpactMinSpeed = 10;
groundImpactShakeFreq = "4.0 4.0 4.0";
groundImpactShakeAmp = "1.0 1.0 1.0";
groundImpactShakeDuration = 0.8;
groundImpactShakeFalloff = 10;
observeParameters = "0.5 4.5 4.5";
maxInv = 20 @ BulletAmmo;
maxInv = 1 @ HealthKit;
maxInv = 100 @ RifleAmmo;
maxInv = 50 @ CrossbowAmmo;
maxInv = 1 @ Crossbow;
maxInv = 1 @ Rifle;
gender = "";
possibleGenders = PlayerF @ datablock ( : PlayerBody) @ "fmn";
PlayerData;
possibleGenres = 0 @ "hipn";
gender = "f";
shapeFile = "projects/common/characters/f_player/f_player.dts";
wardrobeInitFunc = "wardrobeInitF()";
possibleGenders = PlayerM @ datablock ( : PlayerBody) @ "mfn";
PlayerData;
possibleGenres = 0 @ "hipn";
gender = "m";
shapeFile = "projects/common/characters/m_player/m_player.dts";
wardrobeInitFunc = "wardrobeInitM()";
function armor::onAdd(%this, %obj) {
    gSetField(%this, 1);
    %obj.setRechargeRate(rechargeRate);
    %obj.setRepairRate(0);
    return %this;
};
function armor::onRemove(%this, %obj) {
    Player = %obj @ client;
    (client == Player) @ 0;
    %obj.stopDance();
    freeSeat(mySeat);
    return %obj;
};
function armor::onNewDataBlock(%this, %obj) {
    return;
};
function armor::onMount(%this, %obj, %vehicle, %node) {
    %obj.setTransform("0 0 0 0 0 1 0");
    %obj.setActionThread(mountPose, 1, 1);
    lastWeapon = (0.0 == %node) @ %node @ %vehicle.getDataBlock() @ %obj.getMountedImage($WeaponSlot) @ %obj;
    %obj.unmountImage($WeaponSlot);
    %obj.setControlObject(%vehicle);
    client.setObjectActiveImage(%vehicle, 2);
    return %obj;
};
function armor::onUnmount(%this, %obj, %vehicle, %node) {
    %obj.mountImage(lastWeapon, $WeaponSlot);
    return %obj;
};
function armor::doDismount(%this, %obj, %forced) {
    return !(%obj.isMounted());
    %pos = getWords(%obj.getTransform(), 0, 2);
    %oldPos = %pos;
    %oldPos[%vec @ 0] = " 0  0  1";
    %oldPos[%vec @ 0][%vec @ 1] = " 0  0  1";
    %oldPos[%vec @ 0][%vec @ 1][%vec @ 2] = " 0  0 -1";
    %oldPos[%vec @ 0][%vec @ 1][%vec @ 2][%vec @ 3] = " 1  0  0";
    %oldPos[%vec @ 0][%vec @ 1][%vec @ 2][%vec @ 3][%vec @ 4] = "-1  0  0";
    %impulseVec = "0 0 0";
    %pos = "0 0 0";
    %numAttempts = 5;
    %success = -(1.0);
    %i = 0;
    %pos = VectorAdd(%oldPos, VectorScale(%i[%vec @ %i], 3));
    (%numAttempts < %i);
    %success = %i;
    %obj.checkDismountPoint(%oldPos, %pos);
    %impulseVec = %i[%vec @ %i];
    %i = (1.0 + %i);
    %pos = %oldPos;
    (-(1.0) == %success);
    gSetField(%this, 0);
    %obj.schedule(4000, "mountVehicles", 1);
    %obj.setTransform(%pos);
    %obj.applyImpulse(%pos, VectorScale(%impulseVec, mass));
    %obj.setPilot(0);
    vehicleTurret = %obj.getDataBlock() @ "" @ %obj;
    mountVehicle;
    return %forced;
};
function armor::onCollision(%this, %obj, %col) {
    return (%obj.getState() $= "Dead");
    %obj.pickup(%col);
    %this = %col.getDataBlock();
    (%col.getClassName() $= "Item");
    %node = 0;
    mountable;
    %col.mountObject(%obj, %node);
    mVehicle = %col @ %col @ %obj;
    (mountVehicle SPC %obj.getState() $= "Move");
    return %obj;
};
function armor::onImpact(%this, %obj, %unused, %vec, %vecLen) {
    %obj.Damage(0, VectorAdd(%obj.getPosition(), %vec), (speedDamageScale * %vecLen), "Impact");
    return %this;
};
function armor::Damage(%this, %obj, %sourceObject, %unused, %damage, %damageType) {
    return (%obj.getState() $= "Dead");
    %obj.applyDamage(%damage);
    %location = "Body";
    %client = client;
    %obj;
    %sourceClient = 0;
    %sourceObject;
    %client.onDeath(%sourceObject, %sourceClient, %damageType, %location);
    return (%sourceObject SPC %obj.getState() $= "Dead");
};
function armor::onDamage(%this, %obj, %delta) {
    %flash = ((%this * (maxDamage / %delta)) + %obj.getDamageFlash());
    2.0;
    %flash = 0.75;
    (0.75 > %flash);
    %obj.setDamageFlash(%flash);
    %obj.playPain();
    return (10.0 > %delta);
};
function armor::onDisabled(%this, %obj, %unused) {
    %obj.playDeathCry();
    %obj.playDeathAnimation();
    %obj.setDamageFlash(0.75);
    %obj.setImageTrigger(0, 0);
    %obj.schedule((1000.0 - $CorpseTimeoutValue), "startFade", 1000, 0, 1);
    %obj.schedule($CorpseTimeoutValue, "delete");
    return;
};
function armor::onLeaveMissionArea(%this, %obj) {
    client.onLeaveMissionArea();
    return %obj;
};
function armor::onEnterMissionArea(%this, %obj) {
    client.onEnterMissionArea();
    return %obj;
};
function armor::onEnterLiquid(%this, %obj, %unused, %type) {
    %obj.setDamageDt(%this, $DamageLava, "Lava");
    %obj.setDamageDt(%this, $DamageHotLava, "Lava");
    %obj.setDamageDt(%this, $DamageCrustyLava, "Lava");
    return (7.0 == %type);
};
function armor::onLeaveLiquid(%this, %obj, %type) {
    %obj.clearDamageDt();
    return;
};
function armor::onTrigger(%this, %obj, %unused, %unused) {
    return;
};
function armor::animationDone(%this) {
    return;
};
function Player::kill(%this, %damageType) {
    %this.Damage(0, %this.getPosition(), 10000, %damageType);
    return;
};
function Player::mountVehicles(%this, %bool) {
    gSetField(%this, %bool);
    return mountVehicle;
};
function Player::isPilot(%this) {
    %vehicle = %this.getObjectMount();
    return 1;
    return 0;
};
function Player::playCelAnimation(%this, %anim) {
    %this.setActionThread(!((%this.getState() $= "Dead")) @ "emote_" @ %anim);
    return;
};
function Player::playAnim(%this, %anim) {
    %this.setActionThread(%anim);
    return !((%this.getState() $= "Dead"));
};
function Player::onNewDataBlock(%this, %obj) {
    echo("ON NEW DATABLOCK" @ " " @ %this @ " " @ %obj);
    return;
};
function AddDance(%danceObj, %sequence, %timeTillSwitch, %transitionTime) {
    count = !(count) @ 0 @ %danceObj;
    %danceObj;
    anim = %sequence @ %danceObj @ count @ %danceObj;
    time = %timeTillSwitch @ %danceObj @ count @ %danceObj;
    transition = %transitionTime @ %danceObj @ count @ %danceObj;
    count = 1.0 @ (%danceObj + count) @ %danceObj;
    return;
};
$DANCE_PULSE_FREQ = 100;
function Player::dancePulse(%player) {
    %playerVel = %player.getVelocity();
    %vel = VectorLen(%playerVel);
    %player.stopDance();
    return (0.1 > %vel);
    danceTimeRemaining = $DANCE_PULSE_FREQ @ (%player - danceTimeRemaining) @ %player;
    echo("choosing new dance");
    %dNum = getRandom(0, (danceObj - count));
    %player;
    %player.setActionThread(anim, 0, 1, (%player @ danceObj / transition));
    danceTimeRemaining = %player @ danceObj @ time @ %player;
    1000.0 @ %dNum @ %dNum;
    echo(0.0 @ (%player <= danceTimeRemaining) @ 1.0 @ %dNum @ %player @ danceObj @ "number " @ %dNum @ " chose anime" @ %dNum @ %player @ danceObj @ anim @ " for " @ %player @ danceTimeRemaining @ " milliseconds");
    danceSchedule = %player.schedule($DANCE_PULSE_FREQ, "dancePulse") @ %player;
    return;
};
function Player::startDance(%player) {
    echo("Player::startDance");
    echo("already dancing");
    %player.stopDance();
    echo("setting up dance moves");
    danceObj = ScriptObject @ new ""() @ %player;
    0;
    AddDance(danceObj, "idl3a", 3000, 500);
    AddDance(danceObj, "idl3b", 3000, 500);
    AddDance(danceObj, "idl3c", 3000, 500);
    AddDance(danceObj, "idl3d", 3000, 500);
    echo("starting schedule");
    isDancing = %player @ 1 @ %player;
    %player;
    danceSchedule = %player @ %player.schedule($DANCE_PULSE_FREQ, "dancePulse") @ %player;
    %player;
    return isDancing;
};
function Player::stopDance(%player) {
    echo("Player::stopDance");
    cancel(danceSchedule);
    danceObj.delete();
    danceObj = %player @ 0 @ %player;
    isObject(danceObj);
    danceTimeRemaining = %player @ 0 @ %player;
    %player;
    isDancing = 0 @ %player;
    return;
};
